### ISSUE TITLE
Regression in 'javax.ws.rs.client' in OH3

### ISSUE THREAD

**Issue by andrewfg** [openhab/openhab-addons#10057]
**How to Fix a Regression in `javax.ws.rs.client` from OH2 to OH3 ??**

I am looking for advice from OH maintainers about how to fix a regression due to a dependency of this binding, so that I can make the appropriate necessary changes and create a new PR to fix it.

**Background:**

This binding uses the `javax.ws.rs.client.*` libraries to invoke web requests on the hub (server): It calls the `javax.ws.rs.client.Invocation` interface method `invoke()` in [`HDPowerViewWebTargets.java`](https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/HDPowerViewWebTargets.java) to query the hub for JSON responses.

```
Response response;
try {
    response = invocation.invoke();
} catch (ProcessingException e) {
    ...
}
```

**Issue:**

In prior versions of the binding (OH2 on Java 8) when `invoke()` fails, it throws `ProcessingException`, which is caught by the binding code above. According to the javax rs documentation `ProcessingException` is the error that one should expect. But now in OH3 I am unexpectedly seeing `NoRouteToHostException` instead, which is i) not caught by the binding code, and ii) not according to the javax rs documentation.

**Potential Solution:**

Of course I could just blindly add `NoRouteToHostException` to the catch clause above; but I wonder if there is an underlying reason why  javax rs  changed its behaviour here? Is there perhaps some versioning issue?

**Comment by andrewfg** [comment]
> I could just blindly add NoRouteToHostException to the catch clause

It is even worse than I thought. If I do add `NoRouteToHostException` to the catch clause, the compiler reports _'Unreachable catch block for NoRouteToHostException'_ -- yet in reality the binding **DOES** throw this exception (as you can see from the entry 'HDPowerViewWebTargets.java:155' in the crash dump below).

Therefore I am totally flummoxed about how to fix this; so I am pinging a few code gurus (@fwolter @J-N-K @cpmeister) kindly asking for your advice :)

```
Response response;
try {
    response = invocation.invoke();
} catch (NoRouteToHostException | ProcessingException e) {
    ...
}
```
---
```
2021-02-05 00:52:45.637 [WARN ] [ache.cxf.phase.PhaseInterceptorChain] - Interceptor for {http://192.168.1.168/api/shades/}WebClient has thrown exception, unwinding now
org.apache.cxf.interceptor.Fault: Could not send Message.
	at org.apache.cxf.interceptor.MessageSenderInterceptor$MessageSenderEndingInterceptor.handleMessage(MessageSenderInterceptor.java:67) ~[bundleFile:1.0.9]
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308) [bundleFile:1.0.9]
	at org.apache.cxf.jaxrs.client.AbstractClient.doRunInterceptorChain(AbstractClient.java:705) [bundleFile:1.0.9]
	at org.apache.cxf.jaxrs.client.WebClient.doChainedInvocation(WebClient.java:1081) [bundleFile:1.0.9]
	at org.apache.cxf.jaxrs.client.WebClient.doInvoke(WebClient.java:927) [bundleFile:1.0.9]
	at org.apache.cxf.jaxrs.client.WebClient.doInvoke(WebClient.java:896) [bundleFile:1.0.9]
	at org.apache.cxf.jaxrs.client.WebClient.invoke(WebClient.java:461) [bundleFile:1.0.9]
	at org.apache.cxf.jaxrs.client.SyncInvokerImpl.method(SyncInvokerImpl.java:150) [bundleFile:1.0.9]
	at org.apache.cxf.jaxrs.client.SyncInvokerImpl.method(SyncInvokerImpl.java:145) [bundleFile:1.0.9]
	at org.apache.cxf.jaxrs.client.spec.InvocationBuilderImpl.method(InvocationBuilderImpl.java:123) [bundleFile:1.0.9]
	at org.apache.cxf.jaxrs.client.spec.InvocationBuilderImpl$InvocationImpl.invoke(InvocationBuilderImpl.java:351) [bundleFile:1.0.9]
	at org.openhab.binding.hdpowerview.internal.HDPowerViewWebTargets.invoke(HDPowerViewWebTargets.java:155) [bundleFile:?]
	at org.openhab.binding.hdpowerview.internal.HDPowerViewWebTargets.getShades(HDPowerViewWebTargets.java:99) [bundleFile:?]
	at org.openhab.binding.hdpowerview.internal.handler.HDPowerViewHubHandler.pollShades(HDPowerViewHubHandler.java:195) [bundleFile:?]
	at org.openhab.binding.hdpowerview.internal.handler.HDPowerViewHubHandler.poll(HDPowerViewHubHandler.java:177) [bundleFile:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.net.NoRouteToHostException: NoRouteToHostException invoking http://192.168.1.168/api/shades/: No route to host (Host unreachable)
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.mapException(HTTPConduit.java:1402) ~[bundleFile:1.0.9]
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.close(HTTPConduit.java:1386) ~[bundleFile:1.0.9]
	at org.apache.cxf.io.AbstractWrappedOutputStream.close(AbstractWrappedOutputStream.java:77) ~[bundleFile:1.0.9]
	at org.apache.cxf.transport.AbstractConduit.close(AbstractConduit.java:56) ~[bundleFile:1.0.9]
	at org.apache.cxf.transport.http.HTTPConduit.close(HTTPConduit.java:673) ~[bundleFile:1.0.9]
	at org.apache.cxf.interceptor.MessageSenderInterceptor$MessageSenderEndingInterceptor.handleMessage(MessageSenderInterceptor.java:63) ~[bundleFile:1.0.9]
	... 20 more
Caused by: java.net.NoRouteToHostException: No route to host (Host unreachable)
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:?]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399) ~[?:?]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242) ~[?:?]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224) ~[?:?]
	at java.net.Socket.connect(Socket.java:609) ~[?:?]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:177) ~[?:?]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:474) ~[?:?]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:569) ~[?:?]
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242) ~[?:?]
	at sun.net.www.http.HttpClient.New(HttpClient.java:341) ~[?:?]
	at sun.net.www.http.HttpClient.New(HttpClient.java:362) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1253) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1232) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1015) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520) ~[?:?]
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527) ~[?:?]
	at org.apache.cxf.transport.http.URLConnectionHTTPConduit$URLConnectionWrappedOutputStream$2.run(URLConnectionHTTPConduit.java:377) ~[bundleFile:1.0.9]
	at org.apache.cxf.transport.http.URLConnectionHTTPConduit$URLConnectionWrappedOutputStream$2.run(URLConnectionHTTPConduit.java:373) ~[bundleFile:1.0.9]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at org.apache.cxf.transport.http.URLConnectionHTTPConduit$URLConnectionWrappedOutputStream.getResponseCode(URLConnectionHTTPConduit.java:373) ~[bundleFile:1.0.9]
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.doProcessResponseCode(HTTPConduit.java:1599) ~[bundleFile:1.0.9]
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleResponseInternal(HTTPConduit.java:1627) ~[bundleFile:1.0.9]
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleResponse(HTTPConduit.java:1572) ~[bundleFile:1.0.9]
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.close(HTTPConduit.java:1373) ~[bundleFile:1.0.9]
	at org.apache.cxf.io.AbstractWrappedOutputStream.close(AbstractWrappedOutputStream.java:77) ~[bundleFile:1.0.9]
	at org.apache.cxf.transport.AbstractConduit.close(AbstractConduit.java:56) ~[bundleFile:1.0.9]
	at org.apache.cxf.transport.http.HTTPConduit.close(HTTPConduit.java:673) ~[bundleFile:1.0.9]
	at org.apache.cxf.interceptor.MessageSenderInterceptor$MessageSenderEndingInterceptor.handleMessage(MessageSenderInterceptor.java:63) ~[bundleFile:1.0.9]
	... 20 more
```

**Comment by J-N-K** [comment]
Not an expert here, but are you sure that the excact same error (no route to host) is handled differently? Or did this just never happen on OH2?

**Comment by andrewfg** [comment]
Yes the same hub error occurs in both OH2 and in OH3 (it is a 'feature' of the hub: it goes offline every night). But in OH2 the JAX-RS framework returns ProcessingException (as documented in the JavaDoc) whereas in OH3 it returns NoRouteToHostException which is not documented.

In the meantime I have been playing around with the code in Eclipse, and I discovered that if I wrap the offending call in a wrapper method and add ' @throws NoRouteToHostException' to its JavaDoc, then I can trick Eclipse to compile properly. One learns something new every day :) -- so I will let the modified code run overnight, and if it works, I will post a PR tomorrow.

```
/**
 * According to JAX-RS specifications, {@link javax.ws.rs.client.Invocation#invoke} only throws ProcessingException;
 * but in practice in this binding it also throws {@link java.net.NoRouteToHostException} so this wrapper method
 * adds NoRouteToHostException formally via the JavaDoc, and thus allows the caller to legally catch{} it.
 *
 * @param invocation the Invocation to be executed
 * @return the Response result of the Invocation
 * @throws ProcessingException
 * @throws NoRouteToHostException
 */
private Response invoke(Invocation invocation) throws ProcessingException, NoRouteToHostException {
    return invocation.invoke();
}
```

**Comment by andrewfg** [comment]
I have been looking more closely at my log messages (above) and I realised that there are actually two entries..

- At 00:52:45.637 `org.apache.cxf.phase.PhaseInterceptorChain` writes a full stack trace in the OH log.
- At 00:52:45.670 `o.o.b.hdpowerview.internal.HDPowerViewHubHandler` writes a log warning entry too.

This means that the problem is NOT in the HDPowerView binding, nor even in the OH core, -- **_the problem is in 'org.apache.cxf.phase.PhaseInterceptorChain' !!_** -- that module (IMHO) should NOT dump log entries into the OH log, but should instead catch `NoRouteToHostException` and throw `ProcessingException` up to the caller in accordance with the JAX-RS specifications.

So my conclusions are as follows..
1. I think this issue must be moved from openhab/addons to openhab/core - perhaps @kaikreuzer could move it?
2. I wonder if openhab/core is built with a debug version of `org.apache.cxf...` e.g. some test version with logging enabled?

```
2021-02-05 00:52:45.637 [WARN ] [ache.cxf.phase.PhaseInterceptorChain] - Interceptor for {http://192.168.1.168/api/shades/}WebClient has thrown exception, unwinding now
org.apache.cxf.interceptor.Fault: Could not send Message.
...
2021-02-05 00:52:45.670 [WARN ] [ternal.handler.HDPowerViewHubHandler] - Error connecting to bridge: java.net.NoRouteToHostException: NoRouteToHostException invoking http://192.168.1.168/api/shades/: No route to host (Host unreachable)
```

**Comment by andrewfg** [comment]
PS it seems to be something to do with JAX-RS Exception Interceptors or Exception Mapping. I suppose something changed recently in the core resp. between OH2 and OH3 ??

**Comment by andrewfg** [comment]
I guess that is may be related to this https://github.com/openhab/openhab-addons/pull/9224
- OH2: the handler created its web Client by calling the `ClientBuilder.newClient()` static method
- OH3: a ClientBuilder is injected into the factory, and the handler creates its Client by calling its `build()` method.

**Comment by andrewfg** [comment]
^
And: OH2 created a Jersey client, whereas OH3 creates a CXF one..

**Comment by andrewfg** [comment]
Another solution would be to refactor the binding to use HttpClient rather than JAX-RS..

**Comment by andrewfg** [comment]
The issue will be resolved by this PR https://github.com/openhab/openhab-addons/pull/10118
