### ISSUE TITLE
[Smartmeter] Binding stopped working since latest changes

### ISSUE THREAD

**Issue by LukasA83** [openhab/openhab-addons#10052]
## Expected Behavior
Thing goes online and receives updates, D mode with delay.

## Current Behavior
Thing is waiting for messages with following error in log:
```
2021-02-04 20:54:46.209 [WARN ] [.iec62056.Iec62056_21SerialConnector] - Exception while listening for mode D data message
java.io.IOException: Received unexpected identification message start byte: 00
	at org.openmuc.j62056.internal.IdentificationMessage.<init>(IdentificationMessage.java:49) ~[bundleFile:?]
	at org.openmuc.j62056.Iec21Port$ModeDReceiver.run(Iec21Port.java:70) [bundleFile:?]
2021-02-04 20:54:46.231 [WARN ] [.iec62056.Iec62056_21SerialConnector] - Exception while listening for mode D data message
java.io.IOException: Received unexpected identification message start byte: 00
	at org.openmuc.j62056.internal.IdentificationMessage.<init>(IdentificationMessage.java:49) ~[bundleFile:?]
	at org.openmuc.j62056.Iec21Port$ModeDReceiver.run(Iec21Port.java:70) [bundleFile:?]
2021-02-04 20:54:46.242 [WARN ] [.iec62056.Iec62056_21SerialConnector] - Exception while listening for mode D data message
java.io.IOException: Received unexpected identification message start byte: 42
	at org.openmuc.j62056.internal.IdentificationMessage.<init>(IdentificationMessage.java:49) ~[bundleFile:?]
	at org.openmuc.j62056.Iec21Port$ModeDReceiver.run(Iec21Port.java:70) [bundleFile:?]
2021-02-04 20:54:46.264 [WARN ] [.iec62056.Iec62056_21SerialConnector] - Exception while listening for mode D data message
java.io.IOException: Received unexpected identification message start byte: 63
	at org.openmuc.j62056.internal.IdentificationMessage.<init>(IdentificationMessage.java:49) ~[bundleFile:?]
	at org.openmuc.j62056.Iec21Port$ModeDReceiver.run(Iec21Port.java:70) [bundleFile:?]
2021-02-04 20:54:46.275 [WARN ] [.iec62056.Iec62056_21SerialConnector] - Exception while listening for mode D data message
java.io.IOException: Received unexpected identification message start byte: 00
	at org.openmuc.j62056.internal.IdentificationMessage.<init>(IdentificationMessage.java:49) ~[bundleFile:?]
	at org.openmuc.j62056.Iec21Port$ModeDReceiver.run(Iec21Port.java:70) [bundleFile:?]
2021-02-04 20:54:46.297 [WARN ] [.iec62056.Iec62056_21SerialConnector] - Exception while listening for mode D data message
java.io.IOException: Received unexpected identification message start byte: 00
	at org.openmuc.j62056.internal.IdentificationMessage.<init>(IdentificationMessage.java:49) ~[bundleFile:?]
	at org.openmuc.j62056.Iec21Port$ModeDReceiver.run(Iec21Port.java:70) [bundleFile:?]
2021-02-04 20:54:46.309 [WARN ] [.iec62056.Iec62056_21SerialConnector] - Exception while listening for mode D data message
java.io.IOException: Received unexpected identification message start byte: 4A
	at org.openmuc.j62056.internal.IdentificationMessage.<init>(IdentificationMessage.java:49) ~[bundleFile:?]
	at org.openmuc.j62056.Iec21Port$ModeDReceiver.run(Iec21Port.java:70) [bundleFile:?]


```

## Your Environment
Openhab build 2180 on docker

**Comment by LukasA83** [comment]
Issue resolved by changing the baud rate, for whatever reason...
