### ISSUE TITLE
[networkupstools] tests fail on windows

### ISSUE THREAD

**Issue by J-N-K** [openhab/openhab-addons#10059]
```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.openhab.binding.networkupstools.internal.nut.NutApiTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.659 s - in org.openhab.binding.networkupstools.internal.nut.NutApiTest
[INFO] Running org.openhab.binding.networkupstools.internal.NutNameChannelsTest
[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.015 s <<< FAILURE! - in org.openhab.binding.networkupstools.internal.NutNameChannelsTest
[ERROR] org.openhab.binding.networkupstools.internal.NutNameChannelsTest.testReadmeMatchingChannels  Time elapsed: 0 s  <<< ERROR!
java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/Users/Jan/Documents/Git/openhab-addons/bundles/org.openhab.binding.networkupstools/target/test-classes/../..\README.md
        at org.openhab.binding.networkupstools.internal.NutNameChannelsTest.readReadme(NutNameChannelsTest.java:124)
        at org.openhab.binding.networkupstools.internal.NutNameChannelsTest.testReadmeMatchingChannels(NutNameChannelsTest.java:73)

[ERROR] org.openhab.binding.networkupstools.internal.NutNameChannelsTest.testNutNameMatchingReadme  Time elapsed: 0.015 s  <<< ERROR!
java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/Users/Jan/Documents/Git/openhab-addons/bundles/org.openhab.binding.networkupstools/target/test-classes/../..\README.md
        at org.openhab.binding.networkupstools.internal.NutNameChannelsTest.readReadme(NutNameChannelsTest.java:124)
        at org.openhab.binding.networkupstools.internal.NutNameChannelsTest.testNutNameMatchingReadme(NutNameChannelsTest.java:104)

[INFO] Running org.openhab.binding.networkupstools.internal.NutNameTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.079 s - in org.openhab.binding.networkupstools.internal.NutNameTest
[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   NutNameChannelsTest.testNutNameMatchingReadme:104->readReadme:124 » InvalidPath
[ERROR]   NutNameChannelsTest.testReadmeMatchingChannels:73->readReadme:124 » InvalidPath
[INFO]
[ERROR] Tests run: 5, Failures: 0, Errors: 2, Skipped: 0
```

**Comment by lolodomo** [comment]
I can confirm.

There was one recent change: #10017. Maybe the cause ?
