### ISSUE TITLE
[avmfritz] Authentication issue of AVM Fritz Binding 

### ISSUE THREAD

**Issue by c--r** [openhab/openhab-addons#10062]
## Expected Behavior
I have added the AVM binding in openhab3 and added the Fritzbox as Thing through the Admin UI. Then I have set username and password in openhab3, accodring to an account configured on the Fritzbox. Access through TR064 had already been activated for OH2. 

## Current Behavior
The AVM Binding is showing Status "Offline", "**COMMUNICATION_ERROR Request is invalid**". Sometimes, after a OH restart, it works (**so the configuration seems to be OK!**), and call reporting works fine. However, most times, after a restart, it throws the error mentioned before. The system log in the Fritzbox shows an authentication error:

`Anmeldung an der FRITZ!Box Benutzeroberfläche von IP-Adresse [IP-Adresse] gescheitert (falsches Kennwort). `

I have already tried using a simple password without special characters, but without success.

Here is the relevant part of the OH log (this repeats with each connection to the Fritzbox):

```
2021-02-06 11:06:06.240 [DEBUG] [nfig.core.status.ConfigStatusService] - There is no config status provider for entity avmfritz:fritzbox:192_168_1_254 available.
2021-02-06 11:06:06.240 [DEBUG] [onfig.core.ConfigDescriptionRegistry] - No config description found for 'thing:avmfritz:fritzbox:192_168_1_254', using alias 'bridge-type:avmfritz:fritzbox' instead
2021-02-06 11:06:06.636 [DEBUG] [ternal.hardware.FritzAhaWebInterface] - GET response complete: <?xml version="1.0" encoding="utf-8"?><SessionInfo><SID>0000000000000000</SID><Challenge>6568cf4f</Challenge><BlockTime>0</BlockTime><Rights></Rights></SessionInfo>

2021-02-06 11:06:07.344 [DEBUG] [ternal.hardware.FritzAhaWebInterface] - GET response complete: <?xml version="1.0" encoding="utf-8"?><SessionInfo><SID>0000000000000000</SID><Challenge>58b1e728</Challenge><BlockTime>128</BlockTime><Rights></Rights></SessionInfo>

2021-02-06 11:06:07.348 [DEBUG] [ternal.hardware.FritzAhaWebInterface] - Starting with SID null
2021-02-06 11:06:07.351 [DEBUG] [al.handler.AVMFritzBaseBridgeHandler] - Start polling job at interval 15s
2021-02-06 11:06:07.788 [DEBUG] [core.karaf.internal.FeatureInstaller] - Running scheduled sync job
2021-02-06 11:06:08.354 [DEBUG] [al.handler.AVMFritzBaseBridgeHandler] - Poll FRITZ!Box for updates avmfritz:fritzbox:192_168_1_254
2021-02-06 11:06:08.802 [DEBUG] [ommunicator.AbstractHomematicGateway] - Received new (String) value 'CCU1' for 'CENTRAL:0#PONG' from gateway with id '3014F711A061A7D8A98C15D7'
2021-02-06 11:06:09.021 [DEBUG] [ternal.hardware.FritzAhaWebInterface] - GET response complete: <?xml version="1.0" encoding="utf-8"?><SessionInfo><SID>0000000000000000</SID><Challenge>d14b72b9</Challenge><BlockTime>126</BlockTime><Rights></Rights></SessionInfo>

2021-02-06 11:06:09.417 [DEBUG] [est.sitemap.internal.SitemapResource] - Run clean SSE subscriptions job
2021-02-06 11:06:09.550 [DEBUG] [ternal.hardware.FritzAhaWebInterface] - GET response complete: <?xml version="1.0" encoding="utf-8"?><SessionInfo><SID>0000000000000000</SID><Challenge>8ea5049e</Challenge><BlockTime>126</BlockTime><Rights></Rights></SessionInfo>

2021-02-06 11:06:10.082 [DEBUG] [nal.hardware.FritzAhaContentExchange] - HTTP response: 403
2021-02-06 11:06:10.084 [DEBUG] [nal.hardware.FritzAhaContentExchange] - HTTP response: 403
2021-02-06 11:06:10.086 [DEBUG] [nal.hardware.FritzAhaContentExchange] - response complete: null
2021-02-06 11:06:12.089 [DEBUG] [ternal.hardware.FritzAhaWebInterface] - response failed: Total timeout 2000 ms elapsed
java.util.concurrent.TimeoutException: Total timeout 2000 ms elapsed
        at org.eclipse.jetty.client.TimeoutCompleteListener.onTimeoutExpired(TimeoutCompleteListener.java:51) ~[?:?]
        at org.eclipse.jetty.io.CyclicTimeout$Wakeup.run(CyclicTimeout.java:282) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
2021-02-06 11:06:12.616 [DEBUG] [ternal.hardware.FritzAhaWebInterface] - GET response complete: <?xml version="1.0" encoding="utf-8"?><SessionInfo><SID>0000000000000000</SID><Challenge>9e030844</Challenge><BlockTime>123</BlockTime><Rights></Rights></SessionInfo>

2021-02-06 11:06:12.638 [DEBUG] [ommunicator.AbstractHomematicGateway] - Received new (String) value '3014F711A061A7D8A98C10BF' for 'CENTRAL:0#PONG' from gateway with id '3014F711A061A7D8A98C10BF'
2021-02-06 11:06:13.214 [DEBUG] [ternal.hardware.FritzAhaWebInterface] - GET response complete: <?xml version="1.0" encoding="utf-8"?><SessionInfo><SID>0000000000000000</SID><Challenge>871b741c</Challenge><BlockTime>122</BlockTime><Rights></Rights></SessionInfo>

2021-02-06 11:06:13.220 [DEBUG] [are.callbacks.FritzAhaUpdateCallback] - request is invalid: 403
2021-02-06 11:06:13.733 [DEBUG] [nal.hardware.FritzAhaContentExchange] - HTTP response: 403
2021-02-06 11:06:13.735 [DEBUG] [nal.hardware.FritzAhaContentExchange] - HTTP response: 403
2021-02-06 11:06:13.737 [DEBUG] [nal.hardware.FritzAhaContentExchange] - response complete: null
2021-02-06 11:06:13.739 [DEBUG] [are.callbacks.FritzAhaUpdateCallback] - request is invalid: 403

```

**Comment by pablotoribio-beta** [comment]
Similar problem here, when i updated from the version Openhab 3.0.2 to 3.1.0 the binding is not working.
The configuration parameters are ok (ip, username dslf-config, password) but i get the message:
 Thing 'tr064:fritzbox:Fritzbox7590' changed from UNKNOWN to OFFLINE (COMMUNICATION_ERROR): com.sun.xml.messaging.saaj.SOAPExceptionImpl: Unable to create envelope from given source:

Thing 'tr064:fritzbox:Fritzbox7590' changed from OFFLINE (COMMUNICATION_ERROR): HTTP-Response-Code 500 (Internal Server Error), SOAP-Fault: 401 () to UNKNOWN

**Comment by cweitkamp** [comment]
Hi @pablotoribio-beta,

Thanks for reporting your issue. The avmfritz and tr064 bindings are two separate bundles. You should open a new issue explaining your situation.

**Comment by lsiepel** [comment]
Can I assume the OP  issue has been fixed? Or is this still an active issue?

**Comment by klsystem1** [comment]
same problem! i can help myself if i change from HTTP to HTTPS in the thing configuration. from that moment on, the error does not come till openhab starts again... Would be fine if this could be done automatic after openhab start.

**Comment by klsystem1** [comment]
after each start of openhab the Problem occurs.
To get rid of the problem I have to toggle from http to https or the other way. it does only work for the actual started openhab session.
A new start of openhab gives the same problem again.

**Comment by lsiepel** [comment]
> r each start of openhab the Problem occurs.
> To get rid of the problem I have to toggle from http to https or the other way. it does only work for the actual started openhab session.
> A new start of o

In the past there where some isses regarding openHAB starts (order, runlevel etc.) not sure if they relate, but can you confirm this issue is still there in openHAB 4.1 ? 

Have not looked at the code, but i assume that changing from http to https invalidates the config, cuasing a binding re-init.

**Comment by klsystem1** [comment]
problem still exists !

**Comment by lsiepel** [comment]
> problem still exists !

Ok, can you create a debug level trace log for the 4.1.x binding? The tracelog from the OP is outdated and no longer usable.

**Comment by klsystem1** [comment]
which class should I log to trace in my log4j2.xml ?

**Comment by lsiepel** [comment]
> which class should I log to trace in my log4j2.xml ?
org.openhab.binding.avmfritz

Maybe the console or UI is more convenient, choose your favorite way: https://www.openhab.org/docs/administration/logging.html
