### ISSUE TITLE
[homekit] Cannot install HomeKit Integration add-on

### ISSUE THREAD

**Issue by f-izzo** [openhab/openhab-addons#10073]
## Expected Behavior

Installing the HomeKit Integration from OpenHAB 3.x.x correctly installs the add-on

## Current Behavior

When installing HomeKit Integration from the "misc add-on" submenu, the installation fails silently, and the UI shows "installing..." forever.

The logs show a possible cause of the issue
```
2021-02-06 21:15:33.505 [ERROR] [core.karaf.internal.FeatureInstaller] - Failed installing 'openhab-misc-homekit': Error:
	Error downloading mvn:javax.json/javax.json-api/1.0
	Error downloading mvn:org.glassfish/javax.json/1.0.4
```

## Possible Solution

This bug is probably caused by a failed dependency download.

Check that the required versions of `javax.json-api` and `javax.json` are available for download.

## Steps to Reproduce (for Bugs)

1. Install OpenHAB 3.x.x
2. Click on Settings/Misc/+ sign/ 
3. Select HomeKit Integration

## Context
I'm trying to add the HomeKit Integration add-on on a fresh OpenHAB installation

## Your Environment

* Version used: bug reproduced on openHAB 3.0.1 and 3.1.0.M1 docker installation, alpine variant.
* Environment name and version: Firefox 84
* Operating System and version Arch Linux on Desktop PC

**Comment by yfre** [comment]
it fails while downloading dependencies from public repository in internet.
please make sure your openHAB server has access to internet.

**Comment by Nimayer** [comment]
I retried to install the HomeKit add-on this morning and it worked.
It must have been a temporary DNS error, or something like that.

Thank you for the support

**Comment by maisun** [comment]
I got a similar problem with HomeKit installation:
org.apache.karaf.features.internal.util.MultiException: Error:
        Error downloading mvn:org.openhab.addons.bundles/org.openhab.io.homekit/3.0.1
        at org.apache.karaf.features.internal.download.impl.MavenDownloadManager$MavenDownloader.<init>(MavenDownloadManager.java:91)
        at org.apache.karaf.features.internal.download.impl.MavenDownloadManager.createDownloader(MavenDownloadManager.java:72)
        at org.apache.karaf.features.internal.region.Subsystem.downloadBundles(Subsystem.java:457)
        at org.apache.karaf.features.internal.region.Subsystem.downloadBundles(Subsystem.java:452)
        at org.apache.karaf.features.internal.region.SubsystemResolver.resolve(SubsystemResolver.java:224)
        at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:393)
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1062)
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.lambda$doProvisionInThread$13(FeaturesServiceImpl.java:998)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
        Suppressed: java.io.IOException: Error downloading mvn:org.openhab.addons.bundles/org.openhab.io.homekit/3.0.1
                at org.apache.karaf.features.internal.download.impl.AbstractRetryableDownloadTask.run(AbstractRetryableDownloadTask.java:77)
                at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
                at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
                at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
                ... 3 more
        Caused by: java.io.IOException: Error resolving artifact org.openhab.addons.bundles:org.openhab.io.homekit:jar:3.0.1: [Could not find artifact org.openhab.addons.bundles:org.openhab.io.homekit:jar:3.0.1 in openhab (https://openhab.jfrog.io/openhab/libs-release/)]
                at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.configureIOException(AetherBasedResolver.java:803)
                at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:774)
                at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:657)
                at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:598)
                at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:565)
                at org.apache.karaf.features.internal.download.impl.MavenDownloadTask.download(MavenDownloadTask.java:52)
                at org.apache.karaf.features.internal.download.impl.AbstractRetryableDownloadTask.run(AbstractRetryableDownloadTask.java:60)
                ... 6 more
                Suppressed: shaded.org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact org.openhab.addons.bundles:org.openhab.io.homekit:jar:3.0.1 in openhab (https://openhab.jfrog.io/openhab/libs-release/)
                        at shaded.org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:48)
                        at shaded.org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:368)
                        at shaded.org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:75)
                        at shaded.org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:642)
                        at shaded.org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:262)
                        at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:489)
                        at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:390)
                        at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:215)
                        at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:192)
                        at shaded.org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:247)
                        at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:767)
                        ... 11 more
        Caused by: shaded.org.eclipse.aether.resolution.ArtifactResolutionException: Error resolving artifact org.openhab.addons.bundles:org.openhab.io.homekit:jar:3.0.1
                at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:413)
                at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:215)
                at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:192)
                at shaded.org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:247)
                at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:767)
                ... 11 more
