### ISSUE TITLE
[bluetooth.bluez]  Discovery cause always errors

### ISSUE THREAD

**Issue by paulianttila** [openhab/openhab-addons#10136]
Environment which doesn't have DBus like OS X, Bluetooth discovery spit every time following exception

```
12:19:04.434 [qtp464949400-60] ERROR o.o.c.c.d.i.DiscoveryServiceRegistryImpl:380 - Cannot trigger scan for thing types '[bluetooth:bluez]' on 'BlueZDiscoveryService'!
java.util.concurrent.CompletionException: org.freedesktop.dbus.exceptions.DBusException: Cannot Resolve Session Bus Address: MachineId file can not be found
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1063)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at org.openhab.binding.bluetooth.util.RetryFuture$CallableTask.run(RetryFuture.java:76)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.freedesktop.dbus.exceptions.DBusException: Cannot Resolve Session Bus Address: MachineId file can not be found
	at org.freedesktop.dbus.connections.impl.DBusConnection.lambda$determineMachineIdFile$5(DBusConnection.java:320)
	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
	at org.freedesktop.dbus.connections.impl.DBusConnection.determineMachineIdFile(DBusConnection.java:320)
	at org.freedesktop.dbus.connections.impl.DBusConnection.getDbusMachineId(DBusConnection.java:303)
	at org.freedesktop.dbus.connections.impl.DBusConnection.getConnection(DBusConnection.java:149)
	at org.freedesktop.dbus.connections.impl.DBusConnection.getConnection(DBusConnection.java:169)
	at org.freedesktop.dbus.connections.impl.DBusConnection.getConnection(DBusConnection.java:219)
	at org.freedesktop.dbus.connections.impl.DBusConnection.getConnection(DBusConnection.java:184)
	at com.github.hypfvieh.bluetooth.DeviceManager.createInstance(DeviceManager.java:74)
	at org.openhab.binding.bluetooth.bluez.internal.DeviceManagerFactory.lambda$0(DeviceManagerFactory.java:82)
	at org.openhab.binding.bluetooth.util.RetryFuture$CallableTask.run(RetryFuture.java:67)
	... 6 common frames omitted

```

At the moment, user can install only bluetooth binding, which then install all bluetooth related bundles (also BlueZ).

Short term solution could be to change logging level of BlueZ binding or just log error ones during start.

Possible long term solution could be that bluetooth binding will be separated to multiple bindings. Then user can select only features which are needed (e.g. BlueGiga + Airthings).

**Comment by kaikreuzer** [comment]
Just stumbled over this myself and created #10153.
