### ISSUE TITLE
[tado] could not apply HVAC change on home and zone: operation updateZoneOverlay failed with error 422

### ISSUE THREAD

**Issue by Timtam** [openhab/openhab-addons#10186]
## Expected Behavior
When setting a hvac mode, everything should work as normal, and it did until some time ago. It probably has something to do with the new features of tado?

## Current Behavior
When trying to set the hvac mode at the moment, the following error is raised and nothing happens:
```
2021-02-17 12:47:17.725 [WARN ] [ado.internal.handler.TadoZoneHandler] - Could not apply HVAC change on home 345661 and zone 2: Operation updateZoneOverlay failed with error 422
org.openhab.binding.tado.internal.api.ApiException: Operation updateZoneOverlay failed with error 422
	at org.openhab.binding.tado.internal.api.client.HomeApi.updateZoneOverlay(HomeApi.java:625) ~[bundleFile:?]
	at org.openhab.binding.tado.internal.handler.TadoZoneHandler.setOverlay(TadoZoneHandler.java:110) ~[bundleFile:?]
	at org.openhab.binding.tado.internal.TadoHvacChange.apply(TadoHvacChange.java:123) ~[bundleFile:?]
	at org.openhab.binding.tado.internal.handler.TadoZoneHandler.lambda$0(TadoZoneHandler.java:298) [bundleFile:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

## Steps to Reproduce (for Bugs)

1. Create a thing + hvac item.
2. try to manually update the hvac item.
3. I don't know since when this issue appears, nor what might be the reason, so I cannot give any more details on how to reproduce it, but i'm here if you need help reproducing it / tracking it down.

## Your Environment

* Version used: openHAB 3.0.1 release build
* Environment name and version: Java 11
* Operating System and version: openHABIAN latest version, openHAB3 branch

**Comment by Timtam** [comment]
bug seems to have fixed itself, probably an issue tado-wise.

**Comment by Artur-Fedjukevits** [comment]
Now I have same issue. Probably after I got mail from Tado: 

> > Hello Artur,
> 
> There is a free update available for your tado° Smart AC Control.
> 
> The update includes the following improvements:
> 
> Additional fan speeds
> More swing functions
> Temperature setting in AUTO mode

 I had a software update on Tado AC Control (Restart AC Setup). Now, I can only turn OFF the AC. For all others HVAC change commands I get a 422 API Exception. I suspect it's because they changed their API along with the new AC Smart Control software.

`2022-01-29 13:16:50.275 [DEBUG] [ado.internal.handler.TadoZoneHandler] - Setting overlay of home 680446 and zone 1
2022-01-29 13:16:50.332 [WARN ] [ado.internal.handler.TadoZoneHandler] - Could not apply HVAC change on home 680446 and zone 1: Operation updateZoneOverlay failed with error 422
org.openhab.binding.tado.internal.api.ApiException: Operation updateZoneOverlay failed with error 422
	at org.openhab.binding.tado.internal.api.client.HomeApi.updateZoneOverlay(HomeApi.java:625) ~[?:?]
	at org.openhab.binding.tado.internal.handler.TadoZoneHandler.setOverlay(TadoZoneHandler.java:110) ~[?:?]
	at org.openhab.binding.tado.internal.TadoHvacChange.apply(TadoHvacChange.java:123) ~[?:?]
	at org.openhab.binding.tado.internal.handler.TadoZoneHandler.lambda$0(TadoZoneHandler.java:303) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]`
