### ISSUE TITLE
[tesla] Erratic exception logged when querying vehicle information

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-addons#10264]
From time to time, the tesla binding logs the following exception when querying the vehicle data:
```
2021-03-01 17:05:52.461 [WARN ] [ache.cxf.phase.PhaseInterceptorChain] - Interceptor for {https://owner-api.teslamotors.com/api/1/vehicles}WebClient has thrown exception, unwinding now
org.apache.cxf.interceptor.Fault: Could not send Message.
	at org.apache.cxf.interceptor.MessageSenderInterceptor$MessageSenderEndingInterceptor.handleMessage(MessageSenderInterceptor.java:67) ~[bundleFile:1.0.9]
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308) [bundleFile:1.0.9]
	at org.apache.cxf.jaxrs.client.AbstractClient.doRunInterceptorChain(AbstractClient.java:705) [bundleFile:1.0.9]
	at org.apache.cxf.jaxrs.client.WebClient.doChainedInvocation(WebClient.java:1081) [bundleFile:1.0.9]
	at org.apache.cxf.jaxrs.client.WebClient.doInvoke(WebClient.java:927) [bundleFile:1.0.9]
	at org.apache.cxf.jaxrs.client.WebClient.doInvoke(WebClient.java:896) [bundleFile:1.0.9]
	at org.apache.cxf.jaxrs.client.WebClient.invoke(WebClient.java:461) [bundleFile:1.0.9]
	at org.apache.cxf.jaxrs.client.SyncInvokerImpl.method(SyncInvokerImpl.java:135) [bundleFile:1.0.9]
	at org.apache.cxf.jaxrs.client.SyncInvokerImpl.method(SyncInvokerImpl.java:130) [bundleFile:1.0.9]
	at org.apache.cxf.jaxrs.client.SyncInvokerImpl.get(SyncInvokerImpl.java:50) [bundleFile:1.0.9]
	at org.apache.cxf.jaxrs.client.spec.InvocationBuilderImpl.get(InvocationBuilderImpl.java:88) [bundleFile:1.0.9]
	at org.openhab.binding.tesla.internal.handler.TeslaVehicleHandler.queryVehicle(TeslaVehicleHandler.java:705) [bundleFile:?]
	at org.openhab.binding.tesla.internal.handler.TeslaVehicleHandler.queryVehicleAndUpdate(TeslaVehicleHandler.java:737) [bundleFile:?]
	at org.openhab.binding.tesla.internal.handler.TeslaVehicleHandler.lambda$2(TeslaVehicleHandler.java:159) [bundleFile:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.io.IOException: IOException invoking https://owner-api.teslamotors.com/api/1/vehicles: HTTPS hostname wrong:  should be <owner-api.teslamotors.com>
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.mapException(HTTPConduit.java:1402) ~[bundleFile:1.0.9]
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.close(HTTPConduit.java:1386) ~[bundleFile:1.0.9]
	at org.apache.cxf.io.AbstractWrappedOutputStream.close(AbstractWrappedOutputStream.java:77) ~[bundleFile:1.0.9]
	at org.apache.cxf.transport.AbstractConduit.close(AbstractConduit.java:56) ~[bundleFile:1.0.9]
	at org.apache.cxf.transport.http.HTTPConduit.close(HTTPConduit.java:673) ~[bundleFile:1.0.9]
	at org.apache.cxf.interceptor.MessageSenderInterceptor$MessageSenderEndingInterceptor.handleMessage(MessageSenderInterceptor.java:63) ~[bundleFile:1.0.9]
	... 19 more
Caused by: java.io.IOException: HTTPS hostname wrong:  should be <owner-api.teslamotors.com>
	at sun.net.www.protocol.https.HttpsClient.checkURLSpoofing(HttpsClient.java:648) ~[?:?]
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:581) ~[?:?]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1581) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509) ~[?:?]
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527) ~[?:?]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:329) ~[?:?]
	at org.apache.cxf.transport.http.URLConnectionHTTPConduit$URLConnectionWrappedOutputStream$2.run(URLConnectionHTTPConduit.java:377) ~[bundleFile:1.0.9]
	at org.apache.cxf.transport.http.URLConnectionHTTPConduit$URLConnectionWrappedOutputStream$2.run(URLConnectionHTTPConduit.java:373) ~[bundleFile:1.0.9]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at org.apache.cxf.transport.http.URLConnectionHTTPConduit$URLConnectionWrappedOutputStream.getResponseCode(URLConnectionHTTPConduit.java:373) ~[bundleFile:1.0.9]
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.doProcessResponseCode(HTTPConduit.java:1599) ~[bundleFile:1.0.9]
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleResponseInternal(HTTPConduit.java:1627) ~[bundleFile:1.0.9]
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleResponse(HTTPConduit.java:1572) ~[bundleFile:1.0.9]
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.close(HTTPConduit.java:1373) ~[bundleFile:1.0.9]
	at org.apache.cxf.io.AbstractWrappedOutputStream.close(AbstractWrappedOutputStream.java:77) ~[bundleFile:1.0.9]
	at org.apache.cxf.transport.AbstractConduit.close(AbstractConduit.java:56) ~[bundleFile:1.0.9]
	at org.apache.cxf.transport.http.HTTPConduit.close(HTTPConduit.java:673) ~[bundleFile:1.0.9]
	at org.apache.cxf.interceptor.MessageSenderInterceptor$MessageSenderEndingInterceptor.handleMessage(MessageSenderInterceptor.java:63) ~[bundleFile:1.0.9]
	... 19 more
```

The next request then usually succeeds, so there is no general issue with the request.

Whenever the issue occurs, the vehicle Thing goes OFFLINE.

**Comment by cguedel** [comment]
From what I understand it complains about the certificate hostname not matching, correct? We can see what it should be, but can you also see what the actual hostname is?

**Comment by kaikreuzer** [comment]
See [here](https://github.com/openhab/openhab-addons/pull/10259#issuecomment-787983104) for my analysis results:

> The "HTTPS hostname wrong" occurs quite regular for me, though, and it makes the vehicle Thing go OFFLINE for a while.
I traced it down to `HttpsClient.checkURLSpoofing()`, where there are no peer certificates available and the session is marked as invalidated. No idea how this happens, though.

**Comment by kaikreuzer** [comment]
I found https://stackoverflow.com/a/50676478, which pretty much looks like our issue.
Adding a file in the etc folder isn't that trivial for a binding, though...
But I'll test and we could add it to the distro in general if necessary.

**Comment by kaikreuzer** [comment]
I don't have any success with this setting, though 😞 .
Had 7 occurrences within one hour.

**Comment by lsiepel** [comment]
This is a three year old issue. Wondering if this is still happening with openHAB 4.2.

**Comment by kaikreuzer** [comment]
I think I have still seen it, but let's close it, since I never found a way to fix it, although having spent quite some time on the issue...
