### ISSUE TITLE
[tellstick] NPE in TelldusLocalBridgeHandler

### ISSUE THREAD

**Issue by jannegpriv** [openhab/openhab-addons#10377]
I found the following NPE in the openhab.log when running the latest Tellstick OH3 binding and testing the new local API support.

```
2021-03-22 02:46:17.327 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception: 
java.lang.NullPointerException: null
        at org.openhab.binding.tellstick.internal.local.TelldusLocalBridgeHandler.updateDevices(TelldusLocalBridgeHandler.java:114) ~[?:?]
        at org.openhab.binding.tellstick.internal.local.TelldusLocalBridgeHandler.refreshDeviceList(TelldusLocalBridgeHandler.java:100) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by jannegpriv** [comment]
Works after fix!
