### ISSUE TITLE
[myStrom] Smart Plug with the firmware 2.68 state Unknown"

### ISSUE THREAD

**Issue by tj2000bch** [openhab/openhab-addons#10432]
The old myStrom Smart Plug with the firmware 2.68 remain on Unknown. The new Mystrom Smart Plug in with the Frimware 3.82 work fine.
myStrom 

## Expected Behavior
 If you're describing a bug, tell us what should happen 
 If you're suggesting a change/improvement, tell us how it should work 

## Current Behavior
The Thing status remains on Unknown and not on Online. 

## Context
The status is not updated., Thing deleted and recreated. 

## Your Environment
Opnehab 3.1.0  Debian 10, Openhabian, Java 8 Nodes.js 12.

**Comment by SwissPoPo** [comment]
I have the same issue after updating from OH 3.0.2 to 3.1

The last version of the binding has introduced some device info properties, which is requested with "/api/v1/info".
But this request is not supported by the first generation of this plug.
So, all "Switch CH v1 - Type 101" plugs with firmware 2.68 are no longer working.
The documentation https://api.mystrom.ch/ does not mention that.

If you request "/api/v1/info" from this older plug you will be redirected to "/index.html".
This html page generate this error:

```
2021-07-31 17:39:19.121 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception: 
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226) ~[?:?]
	at com.google.gson.Gson.fromJson(Gson.java:932) ~[?:?]
	at com.google.gson.Gson.fromJson(Gson.java:897) ~[?:?]
	at com.google.gson.Gson.fromJson(Gson.java:846) ~[?:?]
	at com.google.gson.Gson.fromJson(Gson.java:817) ~[?:?]
	at org.openhab.binding.mystrom.internal.AbstractMyStromHandler.updateProperties(AbstractMyStromHandler.java:96) ~[?:?]
	at org.openhab.binding.mystrom.internal.AbstractMyStromHandler.initializeInternal(AbstractMyStromHandler.java:149) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:386) ~[?:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:215) ~[?:?]
	... 12 more

```
