### ISSUE TITLE
[mail] Cannot send mails: java.lang.NoSuchMethodError: 'boolean javax.activation.MimeType.isSpecial(char)'

### ISSUE THREAD

**Issue by cweitkamp** [openhab/openhab-addons#10448]
I upgraded to openHAB 3.1.0 snapshot build 2306

```
2021-04-03 19:48:02.599 [WARN ] [ab.binding.mail.internal.SMTPHandler] - Sending the email to the following server failed : XXXXX:465
2021-04-03 19:48:02.602 [WARN ] [ab.binding.mail.internal.SMTPHandler] - java.lang.NoSuchMethodError: 'boolean javax.activation.MimeType.isSpecial(char)'
```

**Comment by neonknight** [comment]
same for me: Version:     3.1.0-SNAPSHOT (#2308)

**Comment by andrewfg** [comment]
See also this https://github.com/openhab/openhab-core/issues/2273

**Comment by andrewfg** [comment]
I have been doing some tests as follows..

1. First I modified the mail binding code to emit a full stack trace rather than just the "java.lang.NoSuchMethodError: 'boolean javax.activation.MimeType.isSpecial(char)'" message (see stack trace below), and one can see that the module/method `javax.activation.CommandMap.getDefaultCommandMap()` calls `javax.activation.MailcapCommandMap.<init>` and fails.

2. I then also wrote wrote a small JUnit test (see code below), and when I trace through it in the Eclipse debugger, I can see that it also gets as far as `javax.activation.CommandMap.getDefaultCommandMap()` -- HOWEVER this method does NOT contain a call to `javax.activation.MailcapCommandMap.<init>` and therefore no error occurs.

**Conclusion**: The OpenHAB runtime is loading a different (and faulty) version of `javax.activation.*` than the version that my JUnit test loads when it is running in Eclipse: _=> So I think there must be some problem in the pom dependencies (see pom extract below).._

---
**Stack Trace in OH 3**
```
2021-04-09 16:13:16.271 [WARN ] [ab.binding.mail.internal.SMTPHandler] - Sending the email to the following server failed : login-2.hoststar.ch:465
2021-04-09 16:13:16.273 [WARN ] [ab.binding.mail.internal.SMTPHandler] - {}
java.lang.NoSuchMethodError: 'boolean javax.activation.MimeType.isSpecial(char)'
	at javax.activation.MailcapCommandMap.getToken(MailcapCommandMap.java:313) ~[bundleFile:1.2.1_2]
	at javax.activation.MailcapCommandMap.addMailcap(MailcapCommandMap.java:163) ~[bundleFile:1.2.1_2]
	at javax.activation.MailcapCommandMap.parseMailcap(MailcapCommandMap.java:149) ~[bundleFile:1.2.1_2]
	at javax.activation.MailcapCommandMap.parseMailcap(MailcapCommandMap.java:139) ~[bundleFile:1.2.1_2]
	at javax.activation.MailcapCommandMap.<init>(MailcapCommandMap.java:60) ~[bundleFile:1.2.1_2]
	at javax.activation.CommandMap.getDefaultCommandMap(CommandMap.java:55) ~[bundleFile:1.2.1_2]
	at javax.activation.DataHandler.getCommandMap(DataHandler.java:216) ~[bundleFile:1.2.1_2]
	at javax.activation.DataHandler.getDataContentHandler(DataHandler.java:249) ~[bundleFile:1.2.1_2]
	at javax.activation.DataHandler.writeTo(DataHandler.java:73) ~[bundleFile:1.2.1_2]
	at javax.mail.internet.MimeUtility.getEncoding(MimeUtility.java:340) ~[?:?]
	at javax.mail.internet.MimeBodyPart.updateHeaders(MimeBodyPart.java:1575) ~[?:?]
	at javax.mail.internet.MimeMessage.updateHeaders(MimeMessage.java:2271) ~[?:?]
	at javax.mail.internet.MimeMessage.saveChanges(MimeMessage.java:2231) ~[?:?]
	at javax.mail.Transport.send(Transport.java:123) ~[?:?]
	at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1459) ~[?:?]
	at org.apache.commons.mail.Email.send(Email.java:1496) ~[?:?]
	at org.openhab.binding.mail.internal.SMTPHandler.sendMail(SMTPHandler.java:96) ~[?:?]
```
---
**JUnit Test Unit**
```
package org.openhab.binding.mail;

import javax.mail.internet.AddressException;

import org.apache.commons.mail.DefaultAuthenticator;
import org.apache.commons.mail.Email;
import org.apache.commons.mail.EmailException;
import org.junit.jupiter.api.Test;
import org.openhab.binding.mail.internal.MailBuilder;

class MailSenderTest {

    @Test
    void test() {
        MailBuilder builder;
        Email mail;
        try {
            builder = new MailBuilder("aaa@bbb.ccc");
            builder.withSubject("subject");
            builder.withText("text");
            mail = builder.build();
            mail.setFrom("aaa@bbb.ccc");
            mail.setHostName("XXX");
            mail.setSSLOnConnect(true);
            mail.setSslSmtpPort("465");
            mail.setAuthenticator(new DefaultAuthenticator("XXX", "XXX"));
            mail.send();
        } catch (AddressException | EmailException e) {
        }
    }
}
```
---
**POM Extract**
```
    <dependency>
      <groupId>com.sun.mail</groupId>
      <artifactId>javax.mail</artifactId>
      <version>1.6.2</version>
      <scope>compile</scope>
    </dependency>
```

**Comment by andrewfg** [comment]
PS could it be that `javax.activation` was deprecated since v9, and seems to have been deleted since v11 ??

https://docs.oracle.com/javase/9/docs/api/java.activation-summary.html

**Comment by andrewfg** [comment]
Or this..

https://eclipse-ee4j.github.io/jaf/

**Comment by cweitkamp** [comment]
After upgrading to latest snapshot this morning I got the following error in my logs. This stacktrace points to `org.apache.servicemix.specs.activation` bundle which is used by the framework:

```
2021-04-10 09:39:42.211 [ERROR] [Events.Framework                    ] - FrameworkEvent ERROR
java.lang.NoSuchMethodError: 'boolean javax.activation.MimeType.isSpecial(char)'
	at javax.activation.MailcapCommandMap.getToken(MailcapCommandMap.java:313) ~[javax.activation-1.2.0.jar:1.2.0]
	at javax.activation.MailcapCommandMap.addMailcap(MailcapCommandMap.java:163) ~[javax.activation-1.2.0.jar:1.2.0]
	at javax.activation.MailcapCommandMap.parseMailcap(MailcapCommandMap.java:149) ~[javax.activation-1.2.0.jar:1.2.0]
	at javax.activation.MailcapCommandMap.parseMailcap(MailcapCommandMap.java:139) ~[javax.activation-1.2.0.jar:1.2.0]
	at javax.activation.MailcapCommandMap.<init>(MailcapCommandMap.java:60) ~[javax.activation-1.2.0.jar:1.2.0]
	at org.apache.servicemix.specs.activation.OsgiMailcapCommandMap.<init>(OsgiMailcapCommandMap.java:33) ~[?:?]
	at org.apache.servicemix.specs.activation.Activator.rebuildCommandMap(Activator.java:96) ~[?:?]
	at org.apache.servicemix.specs.activation.Activator.register(Activator.java:79) ~[?:?]
	at org.apache.servicemix.specs.locator.Activator.bundleChanged(Activator.java:95) ~[?:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:945) [org.eclipse.osgi-3.16.200.jar:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234) ~[org.eclipse.osgi-3.16.200.jar:?]
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151) ~[org.eclipse.osgi-3.16.200.jar:?]
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEventPrivileged(EquinoxEventPublisher.java:232) ~[org.eclipse.osgi-3.16.200.jar:?]
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:138) ~[org.eclipse.osgi-3.16.200.jar:?]
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:130) ~[org.eclipse.osgi-3.16.200.jar:?]
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor.publishModuleEvent(EquinoxContainerAdaptor.java:217) ~[org.eclipse.osgi-3.16.200.jar:?]
	at org.eclipse.osgi.container.ModuleContainer.applyDelta(ModuleContainer.java:855) ~[org.eclipse.osgi-3.16.200.jar:?]
	at org.eclipse.osgi.container.ModuleContainer.resolveAndApply(ModuleContainer.java:559) ~[org.eclipse.osgi-3.16.200.jar:?]
	at org.eclipse.osgi.container.ModuleContainer.resolve(ModuleContainer.java:502) ~[org.eclipse.osgi-3.16.200.jar:?]
	at org.eclipse.osgi.container.ModuleContainer.refresh(ModuleContainer.java:1137) ~[org.eclipse.osgi-3.16.200.jar:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerWiring.dispatchEvent(ModuleContainer.java:1518) ~[org.eclipse.osgi-3.16.200.jar:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerWiring.dispatchEvent(ModuleContainer.java:1) ~[org.eclipse.osgi-3.16.200.jar:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234) [org.eclipse.osgi-3.16.200.jar:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345) [org.eclipse.osgi-3.16.200.jar:?]
```

**Comment by J-N-K** [comment]
Probably related to the karaf Upgrade. 
We require javax.activation:1.1

AFAIK there is no mail bundle compatible with 1.2

**Comment by andrewfg** [comment]
> no mail bundle compatible with 1.2

I don't fully understand how OH & Karaf build the dependencies, as compared to running a Junit in the Eclipse compiler; but it is interesting that in the latter it works, but in the former it doesn't.??

**Comment by andrewfg** [comment]
> don't fully understand how OH & Karaf build the dependencies

But I wonder if this `excludeGroupIds` in the pom.xml file has something to do with it?

https://github.com/openhab/openhab-addons/blob/95cdc3cb358013b47a6e4b7074d440135751e07e/bundles/pom.xml#L520

**Comment by J-N-K** [comment]
No. The reason is that the karaf upgrade includes an upgrade to javax.activation:1.2 and that is not compatible because it seems that the bundle is not following semver

**Comment by andrewfg** [comment]
> javax.activation:1.2 and that is not compatible

So perhaps putting 1.1 explicitly in the binding pom should resolve it then?

**Comment by andrewfg** [comment]
> putting 1.1 explicitly in the binding pom should resolve it then?

Nope. Tried it and it did not work (even with "hard" dependency version "[1.1]").

**Comment by andrewfg** [comment]
The javax.activation change notes v1.2 vs. v1.1 are here (link below). The note 1.  relates to our issue concerning 'MailcapCommandMap', it appears that the issue may be solvable via a config file. (??)

https://eclipse-ee4j.github.io/jaf/docs/JAF-1.2-changes.txt

**Comment by andrewfg** [comment]
In case anyone is waiting for me to solve this: I have tried many things, without success, and I give up.
=> So hopefully someone else has an answer.

**Comment by andrewfg** [comment]
^
Also to be clear: this is NOT a problem with the mail binding: -- **_THIS IS A PROBLEM IN THE OH CORE!!_**

**Comment by neonknight** [comment]
Thank you for your effort! Is there an open bug report in core?

**Comment by andrewfg** [comment]
> Is there an open bug report in core?

Yes.

https://github.com/openhab/openhab-core/issues/2273

**Comment by kaikreuzer** [comment]
Then let's close this one and keep the one in openhab-core.
