### ISSUE TITLE
OH 3.1.0-M3 Binding missing dependency on jcifs.netbios.NbtAddress

### ISSUE THREAD

**Issue by andrewfg** [openhab/openhab-addons#10451]
Dependency Regression from OH 3.1.0-M2 => OH 3.1.0-M3 

The M3 release newly causes the HD POWERVIEW binding's discovery service to crash (at HDPowerViewHubDiscoveryService.java:83) due to a missing dependency on `jcifs.netbios.NbtAddress`.

https://community.openhab.org/t/openhab-3-1-milestone-discussion/116025/73?u=andrewfg

```
2021-04-03 16:13:48.926 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception: 
java.lang.NoClassDefFoundError: jcifs/netbios/NbtAddress
	at org.openhab.binding.hdpowerview.internal.discovery.HDPowerViewHubDiscoveryService.lambda$0(HDPowerViewHubDiscoveryService.java:83) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException: jcifs.netbios.NbtAddress cannot be found by org.openhab.binding.hdpowerview_3.1.0.M3
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:484) ~[org.eclipse.osgi-3.12.100.jar:?]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:395) ~[org.eclipse.osgi-3.12.100.jar:?]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:387) ~[org.eclipse.osgi-3.12.100.jar:?]
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:150) ~[org.eclipse.osgi-3.12.100.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	... 7 more
```

**Comment by kaikreuzer** [comment]
@andrewfg #10450 should hopefully fix it!

**Comment by andrewfg** [comment]
@kaikreuzer Ah-ha! Thank you.
