### ISSUE TITLE
[miio] Add support for Roborock S7 vacuum robots

### ISSUE THREAD

**Issue by johker01** [openhab/openhab-addons#10590]
I recently bought a Roborock S7 vacuum robot. The Mi IO binding found the robot, but currently, it is only classified as `miio:generic` and only has 2 channels: `actions#power` and `actions#testcommands`. The "real" thing for this robot is missing. Can you please add support for this model?

In [this thread](https://community.openhab.org/t/xiaomi-robot-vacuum-binding/31317/1846) Marcel asked to supply the debug messages, so that it can be added. Those can be found below:

```
17:45:20.795 [DEBUG] [ternal.handler.MiIoUnsupportedHandler] - Periodic update for 'miio:generic:1750Bxxx' (miio:unsupported)
17:45:20.802 [DEBUG] [rnal.transport.MiIoAsyncCommunication] - Command added to Queue {"id":26,"method":"miIO.info","params":[]} -> 192.168.xxx.yyy (Device: 1750Bxxx token: 3444694EXXXXXXXXXXXXXXXX44533679 Queue: 1).
17:45:20.894 [DEBUG] [.internal.handler.MiIoAbstractHandler] - Received response for 1750Bxxx type: MIIO_INFO, result: {"life":52987,"model":"roborock.vacuum.a15","token":"3444694EXXXXXXXXXXXXXXXX44533679","ipflag":1,"miio_ver":"0.0.8","mac":"B0:4A:39:04:DE:AD","fw_ver":"4.1.2_0928","hw_ver":"Linux","miio_client_ver":"4.1.2","VmPeak":9716,"VmRSS":1180,"MemFree":106392,"ap":{"ssid":"my_wifi","bssid":"2c:91:ab:eb:be:ef","rssi":"","freq":0},"netif":{"localIp":"192.168.xxx.yyy","mask":"255.255.255.0","gw":"192.168.xxx.1"},"miio_times":[52987,24,0,52962]}, fullresponse: {"id":26,"result":{"life":52987,"model":"roborock.vacuum.a15","token":"3444694EXXXXXXXXXXXXXXXX44533679","ipflag":1,"miio_ver":"0.0.8","mac":"B0:4A:39:04:DE:AD","fw_ver":"4.1.2_0928","hw_ver":"Linux","miio_client_ver":"4.1.2","VmPeak":9716,"VmRSS":1180,"MemFree":106392,"ap":{"ssid":"my_wifi","bssid":"2c:91:ab:eb:be:ef","rssi":"","freq":0},"netif":{"localIp":"192.168.xxx.yyy","mask":"255.255.255.0","gw":"192.168.xxx.1"},"miio_times":[52987,24,0,52962]},"exe_time":2}
17:45:20.910 [DEBUG] [.internal.handler.MiIoAbstractHandler] - Could not parse network response: {"life":52987,"model":"roborock.vacuum.a15","token":"3444694EXXXXXXXXXXXXXXXX44533679","ipflag":1,"miio_ver":"0.0.8","mac":"B0:4A:39:04:DE:AD","fw_ver":"4.1.2_0928","hw_ver":"Linux","miio_client_ver":"4.1.2","VmPeak":9716,"VmRSS":1180,"MemFree":106392,"ap":{"ssid":"my_wifi","bssid":"2c:91:ab:eb:be:ef","rssi":"","freq":0},"netif":{"localIp":"192.168.xxx.yyy","mask":"255.255.255.0","gw":"192.168.xxx.1"},"miio_times":[52987,24,0,52962]}
java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:?]
	at java.lang.Long.parseLong(Long.java:702) ~[?:?]
	at java.lang.Long.parseLong(Long.java:817) ~[?:?]
	at com.google.gson.JsonPrimitive.getAsLong(JsonPrimitive.java:242) ~[bundleFile:?]
	at org.openhab.binding.miio.internal.handler.MiIoAbstractHandler.updateNetwork(MiIoAbstractHandler.java:300) [bundleFile:?]
	at org.openhab.binding.miio.internal.handler.MiIoAbstractHandler.onMessageReceived(MiIoAbstractHandler.java:533) [bundleFile:?]
	at org.openhab.binding.miio.internal.handler.MiIoUnsupportedHandler.onMessageReceived(MiIoUnsupportedHandler.java:133) [bundleFile:?]
	at org.openhab.binding.miio.internal.transport.MiIoAsyncCommunication$MessageSenderThread.run(MiIoAsyncCommunication.java:254) [bundleFile:?]
```

I've redacted some information (token, IP addresses, MAC addresses).

Please let me know if you need anything else. I'm happy to help.

**Comment by marcelrv** [comment]
the error you see is because in the response there is a `"rssi":"", `whereas the binding expects a number.
