### ISSUE TITLE
[digitalstrom] Scheduled runnable ended with an exception

### ISSUE THREAD

**Issue by GekoCH** [openhab/openhab-addons#10649]
I'm running openHAB 3.0.1 release build. I just wanted to test the dss-IP device from digitalstrom with the coresponing binding in openhab.
I entered the network adresse, username and password and I get this error in the log file once I start the binding.

```
2021-05-05 12:30:52.605 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'digitalstrom:dssBridge:f56bd9c9e0' changed from UNINITIALIZED (DISABLED) to INITIALIZING

2021-05-05 12:30:52.624 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'digitalstrom:dssBridge:f56bd9c9e0' changed from INITIALIZING to ONLINE (CONFIGURATION_PENDING): Checking configuration...

2021-05-05 12:30:53.438 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception: 

java.lang.NullPointerException: null

	at org.openhab.binding.digitalstrom.internal.lib.manager.impl.TemperatureControlManager.checkZones(TemperatureControlManager.java:171) ~[?:?]

	at org.openhab.binding.digitalstrom.internal.lib.manager.impl.TemperatureControlManager.<init>(TemperatureControlManager.java:151) ~[?:?]

	at org.openhab.binding.digitalstrom.internal.lib.manager.impl.TemperatureControlManager.<init>(TemperatureControlManager.java:130) ~[?:?]

	at org.openhab.binding.digitalstrom.internal.handler.BridgeHandler$Initializer.run(BridgeHandler.java:165) ~[?:?]

	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]

	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]

	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:?]

	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]

	at java.lang.Thread.run(Unknown Source) [?:?]
```

**Comment by Clocker** [comment]
I have the same issue. I am using 

`Thanos Raumbediengerät (thanos rH S dS white) or the Raumfühler (FTW06 dS)`

both are from the company thermokon.

It seems to me that they may cause this issue. 

Is there anything I could do to help?

> 2022-04-24 23:17:47.366 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'digitalstrom:dssBridge:dsServer' changed from UNINITIALIZED (DISABLED) to INITIALIZING

2022-04-24 23:17:47.377 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'digitalstrom:dssBridge:dsServer' changed from INITIALIZING to ONLINE (CONFIGURATION_PENDING): Checking configuration...

==> /var/log/openhab/openhab.log <==

2022-04-24 23:17:48.585 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception: 

java.lang.UnsupportedOperationException: null

	at java.util.AbstractList.add(AbstractList.java:153) ~[?:?]

	at java.util.AbstractList.add(AbstractList.java:111) ~[?:?]

	at org.openhab.binding.digitalstrom.internal.lib.manager.impl.TemperatureControlManager.<init>(TemperatureControlManager.java:154) ~[?:?]

	at org.openhab.binding.digitalstrom.internal.lib.manager.impl.TemperatureControlManager.<init>(TemperatureControlManager.java:130) ~[?:?]

	at org.openhab.binding.digitalstrom.internal.handler.BridgeHandler$Initializer.run(BridgeHandler.java:164) ~[?:?]

	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]

	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]

	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]

	at java.lang.Thread.run(Thread.java:829) [?:?]

**Comment by lsiepel** [comment]
From the log perspective, the issues don;t seem to be the same. I might look into this, but before i do i want to assuer one or both of you is avilable to do some testing as i don't have the devices myself.
