### ISSUE TITLE
[Smartmeter] ConcurrentModificationException in logfile

### ISSUE THREAD

**Issue by vguna** [openhab/openhab-addons#10734]
## Expected Behavior
No errors in the log

## Current Behavior
Sometimes Smartmeter binding fails due to the following exception
```
2021-05-13 12:06:53.021 [WARN ] [ding.smartmeter.internal.MeterDevice] - Failed to read: null. Closing connection and trying again in 2 seconds...; smartmeter:meter:662f1bb352
java.util.ConcurrentModificationException: null
        at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1608) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
        at org.openhab.core.io.transport.serial.internal.SerialPortRegistry.getPortProvidersForPortName(SerialPortRegistry.java:82) ~[?:?]
        at org.openhab.core.io.transport.serial.internal.SerialPortManagerImpl.getIdentifier(SerialPortManagerImpl.java:73) ~[?:?]
        at org.openhab.binding.smartmeter.internal.sml.SmlSerialConnector.openConnection(SmlSerialConnector.java:107) ~[bundleFile:?]
        at org.openhab.binding.smartmeter.internal.MeterDevice.lambda$1(MeterDevice.java:168) ~[bundleFile:?]
        at io.reactivex.internal.operators.flowable.FlowableDoOnLifecycle$SubscriptionLambdaSubscriber.onSubscribe(FlowableDoOnLifecycle.java:63) [bundleFile:?]
        at io.reactivex.internal.operators.flowable.FlowableTimeoutTimed.subscribeActual(FlowableTimeoutTimed.java:47) [bundleFile:?]
        at io.reactivex.Flowable.subscribe(Flowable.java:14479) [bundleFile:?]
        at io.reactivex.internal.operators.flowable.FlowableDoOnLifecycle.subscribeActual(FlowableDoOnLifecycle.java:38) [bundleFile:?]
        at io.reactivex.Flowable.subscribe(Flowable.java:14479) [bundleFile:?]
        at io.reactivex.internal.operators.flowable.FlowableDoOnEach.subscribeActual(FlowableDoOnEach.java:50) [bundleFile:?]
        at io.reactivex.Flowable.subscribe(Flowable.java:14479) [bundleFile:?]
        at io.reactivex.internal.operators.flowable.FlowableDoOnLifecycle.subscribeActual(FlowableDoOnLifecycle.java:38) [bundleFile:?]
        at io.reactivex.Flowable.subscribe(Flowable.java:14479) [bundleFile:?]
        at io.reactivex.internal.operators.flowable.FlowableDoOnEach.subscribeActual(FlowableDoOnEach.java:50) [bundleFile:?]
        at io.reactivex.Flowable.subscribe(Flowable.java:14479) [bundleFile:?]
        at io.reactivex.internal.operators.flowable.FlowablePublish.connect(FlowablePublish.java:130) [bundleFile:?]
        at io.reactivex.internal.operators.flowable.FlowableRefCount.subscribeActual(FlowableRefCount.java:91) [bundleFile:?]
        at io.reactivex.Flowable.subscribe(Flowable.java:14479) [bundleFile:?]
        at io.reactivex.Flowable.subscribe(Flowable.java:14426) [bundleFile:?]
        at io.reactivex.internal.operators.flowable.FlowableRepeatWhen$WhenReceiver.onNext(FlowableRepeatWhen.java:100) [bundleFile:?]
        at io.reactivex.internal.operators.flowable.FlowableRetryWhen.subscribeActual(FlowableRetryWhen.java:62) [bundleFile:?]
        at io.reactivex.Flowable.subscribe(Flowable.java:14479) [bundleFile:?]
        at io.reactivex.Flowable.subscribe(Flowable.java:14426) [bundleFile:?]
        at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82) [bundleFile:?]
        at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:260) [bundleFile:?]
        at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:225) [bundleFile:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

From the stacktrace it could be even core having the issue but not sure. Just stumbled across it while looking for something else in the logs.

## Your Environment

* Version used: 3.0.2
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): Openhabian latest

**Comment by lsiepel** [comment]
There where some concurrency issues in openHAB 3. Those are fixed, not sure if it also fixed this issue.
 Can you confirm if this is still happening with openHAB 3.4?
 If so, can you supply a debug log? Thanks.
