### ISSUE TITLE
[Zigbee] ZigbeeThingHandler exception, possibly causing my Aqara things to always appear offline

### ISSUE THREAD

**Issue by bjerregaardp** [openhab/openhab-addons#10746]
I select Zigbee binding and click Scan. Then I press the button on the Aqara device till its LED starts blinking.

## Expected Behavior
No exceptions in the log.
Zigbee Node updates should make it all the way from discovery to UI.

## Current Behavior
Aqara devices are always listed as either GONE or OFFLINE.
 ```
2021-05-23 12:00:49.894 [DEBUG] [bee.discovery.ZigBeeDiscoveryService] - 00158D00067C1BA7: Node discovery not complete
2021-05-23 12:01:08.518 [DEBUG] [ng.zigbee.handler.ZigBeeThingHandler] - 00158D00067C1BA7: Node updated - ZigBeeNode [state=ONLINE, IEEE=00158D00067C1BA7, NWK=5C66, endpoints=[]]
2021-05-23 12:01:08.519 [WARN ] [zsmartsystems.zigbee.ZigBeeExecutors] - Uncaught exception in thread NotificationService-thread-9
java.lang.NullPointerException: null
	at org.openhab.binding.zigbee.handler.ZigBeeThingHandler.nodeUpdated(ZigBeeThingHandler.java:879) ~[?:?]
	at com.zsmartsystems.zigbee.ZigBeeNetworkManager$14.run(ZigBeeNetworkManager.java:1735) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
 ```

The IEEE value in the logline matches the last part of the zigbee device id of a Thing.

## Steps to Reproduce (for Bugs)

1. I select Zigbee binding and click Scan. 
2. Then I press the button on the Aqara device till its LED starts blinking.

## Your Environment

* Version used: OpenHAB 3.1.0.M4
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...):  Edge, Zulu 11
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): Windows 10
* Device: Aqara button WXKG11LM

**Comment by wborn** [comment]
Can you transfer this issue to the zigbee repo @kaikreuzer?

**Comment by bjerregaardp** [comment]
I would love to, but I don't get a [Transfer issue] menu or button. (Missing permissions?)
I can close this one and make a new identical issue in the zigbee repo if you want.

**Comment by wborn** [comment]
Me neither, you only see it if you have the right permissions in both repos. That's why I mentioned Kai. 😉
