### ISSUE TITLE
Error message: Unresolved requirement: Import-Package: org.apache.commons.lang; version="[2.6.0,3.0.0)"

### ISSUE THREAD

**Issue by chilobo** [openhab/openhab-addons#10776]
I am working with Openhab 3.1.0 M4 and the corresponding binding. 

When starting the Fronius binding an error message pops up, but the thing starts and works fine.

A similar issue with the powerwall binding was resolved with a link to:
`Thanks for testing - that error is similar to that reported in Unresolved requirement: Import-Package: javax.measure; version="[2.1.0,3.0.0)"`, see: [https://community.openhab.org/t/tesla-powerwall-2-integration/63516/149?u=chilobo](url)

`2021-05-30 12:09:33.793 [WARN ] [org.apache.felix.fileinstall        ] - Error while starting bundle: file:/usr/share/openhab/addons/org.openhab.binding.fronius-3.1.0-SNAPSHOT.jar

org.osgi.framework.BundleException: Could not resolve module: org.openhab.binding.fronius [87]

  Unresolved requirement: Import-Package: org.apache.commons.lang; version="[2.6.0,3.0.0)"

	at org.eclipse.osgi.container.Module.start(Module.java:463) ~[org.eclipse.osgi-3.16.200.jar:?]

	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:440) ~[org.eclipse.osgi-3.16.200.jar:?]

	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1260) [bundleFile:3.6.8]

	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1233) [bundleFile:3.6.8]

	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startAllBundles(DirectoryWatcher.java:1221) [bundleFile:3.6.8]

	at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:515) [bundleFile:3.6.8]

	at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:365) [bundleFile:3.6.8]

	at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:316) [bundleFile:3.6.8]

`

**Comment by wborn** [comment]
You seem to be mixing older/newer snapshots with an incompatible OH version.

> Unresolved requirement: Import-Package: javax.measure; version="[2.1.0,3.0.0)

Update to OH 3.1.0.M5 or a recent snapshot to fix this.

> Unresolved requirement: Import-Package: org.apache.commons.lang; version="[2.6.0,3.0.0)"

You get this if you use an older addon with a newer OH version. It depends on an old commons-lang version that has been removed from recent OH 3.1 builds (see https://github.com/openhab/openhab-addons/issues/7722). Update the add-on to a version that does not have this dependency.
