### ISSUE TITLE
[tradfri] Binding goes offline and complains about invalid JSON array, but JSON is actually valid

### ISSUE THREAD

**Issue by shutterfreak** [openhab/openhab-addons#10874]
As of some point this afternoon, the TRADFRI binding suddenly went offline and never returned online in openHAB 3. In `/var/log/openhab.log` I see error messages like below (see the 2nd line for the JSON-related error message):
```text
2021-06-16 20:12:19.563 [WARN ] [.eclipse.californium.core.CoapClient] - exception while handling response
java.lang.IllegalStateException: Not a JSON Array: {"9023":"0.tradfri.pool.ntp.org","9059":1623867137,"9060":"2021-06-16T18:12:17.060496Z","9106":0,"9062":0,"9061":0,"9055":0,"9029":"1.14.24","9081":"7e242d5204400048","9082":false,"9073":25,"9076":10,"9232":215000,"9083":"N/A","9066":5,"9054":0,"9069":1621427130,"9103":"a1nvlh0fc0asuq.iot.eu-central-1.amazonaws.com","9105":0,"9071":1,"9072":5,"9235":"BE","9074":13,"9075":19,"9208":1621948775,"9077":31,"9078":1,"9107":1,"9079":0,"9209":1635642000,"9080":60,"9236":3600,"9092":1,"9093":0,"9200":"9b96752c-97bd-4889-abec-7411af6151e1","9118":1,"9204":0,"9211":0,"9201":1,"9202":1605784737}
	at com.google.gson.JsonElement.getAsJsonArray(JsonElement.java:107) ~[?:?]
	at org.openhab.binding.tradfri.internal.handler.TradfriGatewayHandler.onUpdate(TradfriGatewayHandler.java:310) ~[?:?]
	at org.openhab.binding.tradfri.internal.TradfriCoapHandler.onLoad(TradfriCoapHandler.java:73) ~[?:?]
	at org.eclipse.californium.core.CoapClient$MessageObserverImpl.deliver(CoapClient.java:1466) ~[bundleFile:?]
	at org.eclipse.californium.core.CoapClient$MessageObserverImpl$1.run(CoapClient.java:1448) [bundleFile:?]
	at org.eclipse.californium.core.CoapClient.execute(CoapClient.java:1289) [bundleFile:?]
	at org.eclipse.californium.core.CoapClient$MessageObserverImpl.succeeded(CoapClient.java:1444) [bundleFile:?]
	at org.eclipse.californium.core.CoapClient$MessageObserverImpl.onResponse(CoapClient.java:1434) [bundleFile:?]
	at org.eclipse.californium.core.coap.Request.setResponse(Request.java:711) [bundleFile:?]
	at org.eclipse.californium.core.network.EndpointManager$ClientMessageDeliverer.deliverResponse(EndpointManager.java:272) [bundleFile:?]
	at org.eclipse.californium.core.network.stack.BaseCoapStack$StackTopAdapter.receiveResponse(BaseCoapStack.java:210) [bundleFile:?]
	at org.eclipse.californium.core.network.stack.AbstractLayer.receiveResponse(AbstractLayer.java:89) [bundleFile:?]
	at org.eclipse.californium.core.network.stack.ExchangeCleanupLayer.receiveResponse(ExchangeCleanupLayer.java:93) [bundleFile:?]
	at org.eclipse.californium.core.network.stack.ObserveLayer.receiveResponse(ObserveLayer.java:150) [bundleFile:?]
	at org.eclipse.californium.core.network.stack.BlockwiseLayer.receiveResponse(BlockwiseLayer.java:676) [bundleFile:?]
	at org.eclipse.californium.core.network.stack.ReliabilityLayer.receiveResponse(ReliabilityLayer.java:305) [bundleFile:?]
	at org.eclipse.californium.core.network.stack.AbstractLayer.receiveResponse(AbstractLayer.java:89) [bundleFile:?]
	at org.eclipse.californium.core.network.stack.BaseCoapStack.receiveResponse(BaseCoapStack.java:139) [bundleFile:?]
	at org.eclipse.californium.core.network.CoapEndpoint$1.receiveResponse(CoapEndpoint.java:277) [bundleFile:?]
	at org.eclipse.californium.core.network.UdpMatcher$4.run(UdpMatcher.java:399) [bundleFile:?]
	at org.eclipse.californium.elements.util.SerialExecutor$1.run(SerialExecutor.java:276) [bundleFile:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

If I run the returned JSON reported in the error message though an online JSON validator, I get valid JSON:
```json
{
	"9023": "0.tradfri.pool.ntp.org",
	"9059": 1623867075,
	"9060": "2021-06-16T18:11:15.011464Z",
	"9106": 0,
	"9062": 0,
	"9061": 0,
	"9055": 0,
	"9029": "1.14.24",
	"9081": "7e242d5204400048",
	"9082": false,
	"9073": 25,
	"9076": 10,
	"9232": 214940,
	"9083": "N/A",
	"9066": 5,
	"9054": 0,
	"9069": 1621427130,
	"9103": "a1nvlh0fc0asuq.iot.eu-central-1.amazonaws.com",
	"9105": 0,
	"9071": 1,
	"9072": 5,
	"9235": "BE",
	"9074": 13,
	"9075": 19,
	"9208": 1621948775,
	"9077": 31,
	"9078": 1,
	"9107": 1,
	"9079": 0,
	"9209": 1635642000,
	"9080": 60,
	"9236": 3600,
	"9092": 1,
	"9093": 0,
	"9200": "9b96752c-97bd-4889-abec-7411af6151e1",
	"9118": 1,
	"9204": 0,
	"9211": 0,
	"9201": 1,
	"9202": 1605784737
}
```

## Your Environment

* Version used: latest official openHAB 3.0.2 (latest official release to date)
* Environment name and version: Zulu 11
* Operating System and version: openHABian Buster on Raspberry Pi 3B+:

**Comment by Rossko57** [comment]
Valid JSON, but no array (JSON array has [ ] square brackets).  Wonder if your gateway updated.

> * Version used: latest official openHAB 3

You should qualify this, at a guess it means 3.0.2 today?

**Comment by shutterfreak** [comment]
Yes, 3.0.2 (official release).

**Comment by shutterfreak** [comment]
Tradfri firmware version is 1.14.24

**Comment by lsiepel** [comment]
There are some PR's merged for the trafdri binding (and californium dependency) since. Don't know if it is fixed or not, could you verify if this issue still exists with 3.4.1 and recent tradfri firmware?

**Comment by vivienbo** [comment]
On my end I **cannot** reproduce with:
* OpenHAB 3.4.3 on Debian 11
* Tradfri gateway firmware 1.19.52

It never breaks with uptime of 1 month (and on previous 3.x versions for 6+ months)
