### ISSUE TITLE
[homematic] Removal of callback hostname leads to exception

### ISSUE THREAD

**Issue by bechte** [openhab/openhab-addons#10881]
In:
https://github.com/openhab/openhab-addons/blob/e24d43aecbcfc5af551c8e9087d9be6992e5c69a/bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/server/XmlRpcServer.java#L82

Commit: 
https://github.com/openhab/openhab-addons/commit/45ec538a4076eafd60a96af9b28052e8c6ad72a2

The configuration of the callback hostname was removed. This lets `InetSocketAddress` being initialized with a port only. There are overloaded constructors for the fallback, but it seems like this does lead to an unfortune exception. With my current setup (newly installed STABLE OpenHab3 Release), I get the following exception:

```
2021-06-19 13:05:43.506 [INFO ] [ommunicator.AbstractHomematicGateway] - HmGatewayInfo[id=CCU,type=CCU2,firmware=3.57.5.20210525,address=PEQ2215777,rf=true,wired=false,hmip=true,cuxd=false,group=true]
2021-06-19 13:05:43.512 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception: 
java.lang.IllegalArgumentException: hostname can't be null
	at java.net.InetSocketAddress.checkHost(InetSocketAddress.java:149) ~[?:?]
	at java.net.InetSocketAddress.<init>(InetSocketAddress.java:216) ~[?:?]
	at org.openhab.binding.homematic.internal.communicator.server.XmlRpcServer.start(XmlRpcServer.java:82) ~[?:?]
	at org.openhab.binding.homematic.internal.communicator.AbstractHomematicGateway.startServers(AbstractHomematicGateway.java:254) ~[?:?]
	at org.openhab.binding.homematic.internal.communicator.AbstractHomematicGateway.initialize(AbstractHomematicGateway.java:192) ~[?:?]
	at org.openhab.binding.homematic.internal.handler.HomematicBridgeHandler.initializeInternal(HomematicBridgeHandler.java:111) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

Showing that the JVM picks up the wrong method and therefore does not bind against all interfaces, but expects an hostname other than `null`.

Why was this configured hostname removed here? If null, wouldnt it be better to lookup the hostname and provide it?

Hope this gets fixed soon, I cannot use the binding right now. :-(

**Comment by bechte** [comment]
I could "circumstance" the issue by providing an "bindAddress" configuration that is pointing to my OpenHAB public interface IPv4.

This also means, that my analysis was not absolutely correct, as the 3.0 branch has not removed the configuration as described above. Was this change made to support all public interfaces and will it solve the issue by binding the server to all interfaces? Than I would be happy and we can close this issue.

**Comment by MHerbst** [comment]
Hm that's strange. In my tests I never got an IllegalArgumentException.  The JavaDoc for this constructor says:

> Creates a socket address where the IP address is the wildcard addressand the port number a specified value. 

Can you check the version of the Homematic binding. It seems that you don't have this version of the binding installed.

> I could "circumstance" the issue by providing an "bindAddress" configuration that is pointing to my OpenHAB public interface IPv4.

The configuration setting has definitely been removed but I am not absolutely sure what happens if such an configuration already existet. With the current version of the binding it should be ignored.

**Comment by bechte** [comment]
Hi, I am running on 3.0.2 - Release Build:
- Release = Raspbian GNU/Linux 10 (buster)
- Kernel = Linux 5.10.17-v7l+
- Platform = Raspberry Pi 4 Model B Rev 1.1
- OpenJDK Runtime Environment Zulu11.48+21-CA (build 11.0.11+9-LTS)

So, I also believe that I am running on the previous version of the plugin. Still, I am wondering why it ran into issues even though it was running smooth before. There was a power outtake this one night, and since then, it didnt work without setting the parameters. Very strange.

To me, it looks as this issue can be closed. I will revisit the configuration once your updates have made it to the 3.0 branch.
