### ISSUE TITLE
[http] Exception when only adding one header in OH3.1

### ISSUE THREAD

**Issue by tbnobody** [openhab/openhab-addons#10918]
Please see https://community.openhab.org/t/oh3-1-exception-when-using-http-binding/124123

Sample thing file:
```
Thing http:url:publish [

    baseURL = "https://www.$$$$$$$$$$$$$$$$$/import_test.php?", 
    commandMethod = "POST", 
    headers="X-Auth=$$$$$$$$$$$$$$$$$",
    refresh = 300
] {
    Channels:
        Type string : mainfrontdoorlockstateadv [
            stateExtension = "item=MainGF_Main_Frontdoor_LockState_Adv&type=str",
            mode="WRITEONLY"
        ]
}
```

## Expected Behavior
It should be possible to add only one header to the request

## Current Behavior
Exception when only adding one header:
```
2021-06-30 22:40:55.702 [INFO ] [el.core.internal.ModelRepositoryImpl] - Loading model 'http_publish.things'
2021-06-30 22:40:55.710 [WARN ] [re.config.core.internal.ConfigMapper] - Could not set field value for field 'headers': Can not set java.util.ArrayList field org.openhab.binding.http.internal.config.HttpThingConfig.headers to java.util.ImmutableCollections$List12
java.lang.IllegalArgumentException: Can not set java.util.ArrayList field org.openhab.binding.http.internal.config.HttpThingConfig.headers to java.util.ImmutableCollections$List12
        at jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167) ~[?:?]
        at jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171) ~[?:?]
        at jdk.internal.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81) ~[?:?]
        at java.lang.reflect.Field.set(Field.java:780) ~[?:?]
        at org.openhab.core.config.core.internal.ConfigMapper.as(ConfigMapper.java:101) [bundleFile:?]
        at org.openhab.core.config.core.Configuration.as(Configuration.java:80) [bundleFile:?]
        at org.openhab.core.thing.binding.BaseThingHandler.getConfigAs(BaseThingHandler.java:218) [bundleFile:?]
        at org.openhab.binding.http.internal.HttpThingHandler.initialize(HttpThingHandler.java:139) [bundleFile:?]
        at org.openhab.core.thing.binding.BaseThingHandler.thingUpdated(BaseThingHandler.java:152) [bundleFile:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.openhab.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:154) [bundleFile:?]
        at org.openhab.core.internal.common.Invocation.call(Invocation.java:52) [bundleFile:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
2021-06-30 22:40:55.711 [INFO ] [nding.http.internal.HttpThingHandler] - Using the secure client for thing 'http:url:publish'.
```

When adding a second header it works:
`headers="X-Auth=$$$$$$$$$$$$$$$$$","workaround=bla",`

## Steps to Reproduce (for Bugs)
Please see forum post above

## Your Environment
OpenHAB 3.1 with openJDK 11

(it worked in OH3.0)

**Comment by J-N-K** [comment]
That's not an issue of the binding. The `ConfigMapper` seems to be unable to properly set the config value if a `Collection` is required and only a single value is present.

**Comment by J-N-K** [comment]
This is fixed since https://github.com/openhab/openhab-core/pull/2703
