### ISSUE TITLE
[nest] 3.1 Nest SDM javax.measure dependency

### ISSUE THREAD

**Issue by techie66** [openhab/openhab-addons#10926]
The new Nest SDM binding throws an exception related to javax.measure dependency. It does not seem to break anything. I believe it would just require updating the addon's dependency manifest, but I have no experience with addons development.

I'm not the first one to see this:

https://community.openhab.org/t/accessing-and-controlling-a-nest-thermostat-through-sdm-api/124153/5

## Expected Behavior
No errors in log file

## Current Behavior
```org.osgi.framework.BundleException: Could not resolve module: org.openhab.binding.nest [235]
  Unresolved requirement: Import-Package: javax.measure; version="[1.0.0,2.0.0)"

        at org.eclipse.osgi.container.Module.start(Module.java:463) ~[org.eclipse.osgi-3.16.200.jar:?]
        at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:440) ~[org.eclipse.osgi-3.16.200.jar:?]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1260) [bundleFile:3.6.8]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1233) [bundleFile:3.6.8]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.startAllBundles(DirectoryWatcher.java:1221) [bundleFile:3.6.8]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:515) [bundleFile:3.6.8]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:365) [bundleFile:3.6.8]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:316) [bundleFile:3.6.8]
```

## Possible Solution
Update addon dependency.
My idea for fixing comes from these:
https://community.openhab.org/t/unresolved-requirement-import-package-javax-measure-version-2-1-0-3-0-0/122744/2

https://github.com/openhab/openhab-addons/issues/10776#issuecomment-851075888

## Steps to Reproduce (for Bugs)
install nest binding

## Context
Related to: #8664 , #8947 
## Your Environment
OpenHAB 3.1.0 Release Build (Ubuntu 20.04)

**Comment by wborn** [comment]
You seem to be using an OH 3.1 version of the add-on with OH 3.0 which is not supported and causes this issue.
So either upgrade to OH 3.1 or use the `org.openhab.binding.nest-3.0.3.20210530.jar` with OH 3.0 as instructed in my [community post](https://community.openhab.org/t/google-nest-device-access-console-now-available/105404/260?u=wborn).
