### ISSUE TITLE
[amazonechocontrol] OutOfMemory-Error, if an amazon-domain isn't reachable

### ISSUE THREAD

**Issue by binderth** [openhab/openhab-addons#10999]
## Expected Behavior
If an amazon domain isn't reachable (e.g. using pi-hole as an ad-blocker), the binding should handle connection failures gracefully.

## Current Behavior
If an amazon domain (here: dp-gw-na.amazon.de) is blacklisted or in the gravity table of pi-hole or I suspect otherwise not present the following errors probably are the cause for a memory leak:
```
2021-07-10 04:32:03.174 [INFO ] [control.internal.WebSocketConnection] - Web Socket error
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:777) ~[?:?]
	at org.eclipse.jetty.io.SelectorManager.doFinishConnect(SelectorManager.java:355) ~[?:?]
	at org.eclipse.jetty.io.ManagedSelector.processConnect(ManagedSelector.java:347) ~[?:?]
	at org.eclipse.jetty.io.ManagedSelector.access$1700(ManagedSelector.java:65) ~[?:?]
	at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.processSelected(ManagedSelector.java:676) ~[?:?]
	at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.produce(ManagedSelector.java:535) ~[?:?]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produceTask(EatWhatYouKill.java:360) ~[bundleFile:9.4.40.v20210413]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:184) ~[bundleFile:9.4.40.v20210413]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171) ~[bundleFile:9.4.40.v20210413]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:135) ~[bundleFile:9.4.40.v20210413]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:882) [bundleFile:9.4.40.v20210413]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1036) [bundleFile:9.4.40.v20210413]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```
These messages appear regulary (I guess depending on the amount of echo-devices?) in the log, with my installation it was about every 2mins or so.

![grafik](https://user-images.githubusercontent.com/9037329/125737706-b66b4db6-b9e8-4241-995e-cbb3a042aa05.png)
after whitelisting said domain, the memory consumption and openHAB3 worked as expected. de-whitelisting lead directly to the described behaviour - I didn't change any other configuration for the time displayed here.

see: https://community.openhab.org/t/openhab-3-1-problems-with-threadpoolexecutor-and-subsequenlty-outofmemory-errors/

## Possible Solution
?

## Steps to Reproduce (for Bugs)
1. configure amazon-echocontrol with your echo devices in OH3
2. blacklist dp-gw-na.amazon.de (for at least german based users, I suspect differnet TLDs in differen regions) in your Pi-Hole (or perhaps /etc/hosts?)
2. wait for about 6 hours (Pi4, 4GB)
3. OOM-error appears

## Context
After the OOM error, openHAB3 behaves unpredictable, most parts work fine, but with me, the KNX-binding stops writing telegrams (but receives them nevertheless).

## Your Environment

* Version used: (e.g., openHAB and add-on versions)
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...):
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...):

* Hardware: Raspberry Pi 4+ (4GB)
* OS: openHABian [openHAB3]{2021-05-05T15:53:37-06:00}(3e35b6d) => Raspbian GNU/Linux 10 (buster: 5.10.17-v7l+ #1421)
* openHAB version: 3.1.0 - Release Build
* Java Runtime Environment:
```
openjdk version "11.0.11" 2021-04-20 LTS
OpenJDK Runtime Environment Zulu11.48+21-CA (build 11.0.11+9-LTS)
OpenJDK Client VM Zulu11.48+21-CA (build 11.0.11+9-LTS, mixed mode)
```

**Comment by binderth** [comment]
just fyi: I did some testing afterwards:

1. again de-whitelisted the domain
2. let openHAB3.1 run
3. after three hours whitelisted the domain
4. the memory is not freed (don't know, when or if there's a garbage collection)

**Comment by lsiepel** [comment]
@binderth and @jowutal i might have solved this issue. Are you able to test this?

1. Upgrade to atleast openHAB 4.1.0 if not done allready
2. Uninstall the current amazon binding
3. Download the 4.2.0 snapshot here: https://1drv.ms/u/s!AnMcxmvEeupwjuJ4E3JfPqo6gNXUlw?e=ezacQ9 just 
4. place it in the addons folder of openhab and it should work.

When reproducting, a debug level log file would also be very usefull.

**Comment by binderth** [comment]
@lsiepel it was solved for me with an update of the amazon-binding nearly back in 2021 and/or whitelisting the domain in my pi-hole. Since then, amazon did change their approach, I don't even get dns-calls for "dp-gw-na.amazon.de" anymore - but still loads of blocked domains like "fls-eu.amazon.com" or "device-metrics-us-2.amazon.com", or others.

I didn't encounter the problem anymore since 2021.

**Comment by lsiepel** [comment]
Seems to be fixed, thanks
