### ISSUE TITLE
[Smartmeter] Negation based on channel value produces NumberFormatException

### ISSUE THREAD

**Issue by cvette** [openhab/openhab-addons#11029]
## Expected Behavior
Negating based on a channel value should not lead to a NumberFormatException.

## Current Behavior
The following exception is thrown. Note the double value which fails to be parsed by parseLong().

````
`2021-07-19 08:39:26.179 [WARN ] [martmeter.internal.SmartMeterHandler] - Failed to apply negation for channel: smartmeter:meter:main:1-0_56-7-0
java.lang.NumberFormatException: For input string: "49.0"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:?]
	at java.lang.Long.parseLong(Long.java:692) ~[?:?]
	at java.lang.Long.parseLong(Long.java:817) ~[?:?]
	at org.openhab.binding.smartmeter.internal.conformity.negate.NegateHandler.isNegateSet(NegateHandler.java:67) ~[bundleFile:?]
	at org.openhab.binding.smartmeter.internal.conformity.negate.NegateHandler.shouldNegateState(NegateHandler.java:51) ~[bundleFile:?]
	at org.openhab.binding.smartmeter.internal.conformity.Conformity.applyNegation(Conformity.java:115) ~[bundleFile:?]
	at org.openhab.binding.smartmeter.internal.conformity.Conformity.retrieveOverwrittenNegate(Conformity.java:146) ~[bundleFile:?]
	at org.openhab.binding.smartmeter.internal.conformity.Conformity$1.apply(Conformity.java:48) ~[bundleFile:?]
````

## Steps to Reproduce (for Bugs)
Iskra MT681 with the following settings. Value is a two's complement.
````
smartmeter:meter:main [ port="/dev/serial0", refresh=1 ] {
    Channels:
        Type 1-0_16-7-0 : 1-0_16-7-0 [
            negate="1-0_16-7-0:31:0"
        ]
}
````

## Your Environment
OpenHab 3.1 on openhabian

**Comment by lortas** [comment]
Some smart meter response with a floating point number instead of an integer number, so in

- package "org.openhab.binding.smartmeter.internal.conformity.negate"
- class "NegateHandler" 
- method "isNegateSet"

should
```
Long.parseLong(value)
```
be replaced by something like this
```
Double.parseDouble(value).longValue()
```

**Comment by lsiepel** [comment]
I just reproduced this issue with this test:
`
    @Test
    public void testNegateHandlingDecimalTrue() {
        String negateProperty = "1-0_16-7-0:31:0";

        boolean negateState = NegateHandler.shouldNegateState(negateProperty,
                obis -> new MeterValue<>(obis, "49.0", null));

        assertTrue(negateState);
    }
`

Replacing `49.0` fails. `49,0` succeeds. When i use your suggestion to first parse as double, it is the other way around. As fractional delimiter might depend on the locale set, it is not a robust solution. 

A possible solution is to add the locale to the number converison, but then another question raises; the locale of system, openhab or remote smartmeter setting. @msteigenberger could you (as codeowner) add anything to this issue?

**Comment by lortas** [comment]
At least on plain Java, there is no difference between parsing values with dot or comma:

```
# java --version

openjdk 21.0.1 2023-10-17
OpenJDK Runtime Environment (build 21.0.1+12-Ubuntu-223.10)
OpenJDK 64-Bit Server VM (build 21.0.1+12-Ubuntu-223.10, mixed mode, sharing)
```
```
# echo 'class Simple{public static void main(String args[]){System.out.println(java.lang.Long.parseLong("49"))  ;}}'     > Simple.java; javac Simple.java; java Simple 

49
```
```
# echo 'class Simple{public static void main(String args[]){System.out.println(java.lang.Long.parseLong("49,0"));}}'     > Simple.java; javac Simple.java; java Simple 

Exception in thread "main" java.lang.NumberFormatException: For input string: "49,0"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Long.parseLong(Long.java:708)
	at java.base/java.lang.Long.parseLong(Long.java:831)
	at Simple.main(Simple.java:1)
```
```
# echo 'class Simple{public static void main(String args[]){System.out.println(java.lang.Long.parseLong("49.0"));}}'     > Simple.java; javac Simple.java; java Simple 

Exception in thread "main" java.lang.NumberFormatException: For input string: "49.0"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Long.parseLong(Long.java:708)
	at java.base/java.lang.Long.parseLong(Long.java:831)
	at Simple.main(Simple.java:1)
```
```
# echo 'class Simple{public static void main(String args[]){System.out.println(java.lang.Double.parseDouble("49"));}}'   > Simple.java; javac Simple.java; java Simple 

49.0
```
```
# echo 'class Simple{public static void main(String args[]){System.out.println(java.lang.Double.parseDouble("49,0"));}}' > Simple.java; javac Simple.java; java Simple 

Exception in thread "main" java.lang.NumberFormatException: For input string: "49,0"
	at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
	at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.base/java.lang.Double.parseDouble(Double.java:792)
	at Simple.main(Simple.java:1)
```
```
# echo 'class Simple{public static void main(String args[]){System.out.println(java.lang.Double.parseDouble("49.0"));}}' > Simple.java; javac Simple.java; java Simple 

49.0
```

Also defining the language has no effect:

```
# echo 'class Simple{public static void main(String args[]){System.out.println(java.lang.Double.parseDouble("49.000"));}}' > Simple.java; javac Simple.java; java -Duser.language=de -Duser.country=DE -Duser.variant=DE Simple

49.0
```
```
# echo 'class Simple{public static void main(String args[]){System.out.println(java.lang.Double.parseDouble("49.000"));}}' > Simple.java; javac Simple.java; java -Duser.language=en -Duser.country=US -Duser.variant=US Simple

49.0
```

**Comment by lsiepel** [comment]
We share the conclusion that `parseDouble` is good for `49.0` and it fails for `49,0`. I think i did something wrong with the parseLong accepting the opposite. 

Anyway, i investigated a little more and found a solution that works for both ways. I also added a test in the PR.
