### ISSUE TITLE
[zwave] NPE during shutdown

### ISSUE THREAD

**Issue by mhilbush** [openhab/openhab-addons#1106]
I'm seeing this NPE in the zwave binding periodically during shutdown of OH.

```
> 2016-07-09 07:47:17.127 [ERROR] [ocol.ZWaveController$ZWaveSendThread] - Exception during ZWave thread: Send
> java.lang.NullPointerException
>         at org.openhab.binding.zwave.handler.ZWaveSerialHandler.sendPacket(ZWaveSerialHandler.java:309)[190:org.openhab.binding.zwave:2.0.0.201607080102]
>         at org.openhab.binding.zwave.internal.protocol.ZWaveController$ZWaveSendThread.run(ZWaveController.java:1380)[190:org.openhab.binding.zwave:2.0.0.201607080102]
> 
```

Possibly in the middle of trying to send a packet after the serialPort object has been destroyed?

This is probably not a real big deal, because under normal circumstances, I wouldn't normally be doing a lot of restarts...  :-(

**Comment by cdjackson** [comment]
Is that the extent of the stack trace or is there more?

**Comment by mhilbush** [comment]
That's all there was in the stack trace. I can pull some of the context around it, but that's all there was. 

On Jul 9, 2016 2:40 PM, Chris Jackson <notifications@github.com> wrote:Is that the extent of the stack trace or is there more?

**Comment by cdjackson** [comment]
If there's a few lines before, it might help.

As you say, it's not top of the list right now, but one to keep in mind for tidying up...

**Comment by mhilbush** [comment]
Sorry for the delay.  Here's the context in which the NPE occurs.

```
2016-07-09 08:00:44.138 [DEBUG] [ocol.ZWaveController$ZWaveSendThread] - Took message from queue for sending. Queue length = 1
2016-07-09 08:00:44.138 [DEBUG] [wave.internal.protocol.SerialMessage] - Assembled message buffer = 01 0A 00 13 03 03 70 05 08 25 16 A8 
2016-07-09 08:00:44.138 [DEBUG] [ing.zwave.handler.ZWaveSerialHandler] - NODE 3: Sending REQUEST Message = 01 0A 00 13 03 03 70 05 08 25 16 A8 
2016-07-09 08:00:46.212 [INFO ] [ing.zwave.handler.ZWaveSerialHandler] - Stopped ZWave serial handler
2016-07-09 08:00:46.212 [DEBUG] [wave.discovery.ZWaveDiscoveryService] - Deactivating ZWave discovery service for zwave:serial_zstick:155cf77fa74
2016-07-09 08:00:46.213 [DEBUG] [org.openhab.binding.zwave           ] - ServiceEvent UNREGISTERING - {org.eclipse.smarthome.config.discovery.DiscoveryService}={service.id=314, service.bundleid=190, service.scope=singleton} - org.openhab.binding.zwave
2016-07-09 08:00:46.214 [DEBUG] [org.openhab.binding.zwave           ] - ServiceEvent UNREGISTERING - {org.eclipse.smarthome.config.core.status.ConfigStatusProvider}={service.id=318, service.bundleid=190, service.scope=singleton} - org.openhab.binding.zwave
2016-07-09 08:00:46.215 [DEBUG] [org.openhab.binding.zwave           ] - ServiceEvent UNREGISTERING - {org.eclipse.smarthome.config.core.ConfigOptionProvider, org.eclipse.smarthome.config.core.ConfigDescriptionProvider}={component.name=org.openhab.binding.zwave.ConfigDescription, component.id=158, service.id=278, service.bundleid=190, service.scope=bundle} - org.openhab.binding.zwave
2016-07-09 08:00:46.223 [DEBUG] [inding.zwave.internal.ZWaveActivator] - ZWave binding stopped.
2016-07-09 08:00:46.223 [DEBUG] [org.openhab.binding.zwave           ] - BundleEvent STOPPED - org.openhab.binding.zwave
2016-07-09 08:00:46.230 [INFO ] [.dashboard.internal.DashboardService] - Stopped dashboard
2016-07-09 08:00:46.237 [INFO ] [arthome.ui.paper.internal.PaperUIApp] - Stopped Paper UI
2016-07-09 08:00:48.753 [DEBUG] [wave.internal.protocol.SerialMessage] - Assembled message buffer = 01 03 00 16 EA 
2016-07-09 08:00:48.753 [DEBUG] [ocol.ZWaveController$ZWaveSendThread] - NODE 3: Sending ABORT Message = 01 03 00 16 EA 
2016-07-09 08:00:48.753 [DEBUG] [wave.internal.protocol.SerialMessage] - Assembled message buffer = 01 03 00 16 EA 
2016-07-09 08:00:48.753 [DEBUG] [ing.zwave.handler.ZWaveSerialHandler] - NODE 255: Sending REQUEST Message = 01 03 00 16 EA 
2016-07-09 08:00:48.753 [ERROR] [ocol.ZWaveController$ZWaveSendThread] - Exception during ZWave thread: Send
java.lang.NullPointerException
        at org.openhab.binding.zwave.handler.ZWaveSerialHandler.sendPacket(ZWaveSerialHandler.java:309)[190:org.openhab.binding.zwave:2.0.0.201607080102]
        at org.openhab.binding.zwave.internal.protocol.ZWaveController$ZWaveSendThread.run(ZWaveController.java:1413)[190:org.openhab.binding.zwave:2.0.0.201607080102]
2016-07-09 08:00:48.755 [DEBUG] [ocol.ZWaveController$ZWaveSendThread] - Stopped ZWave thread: Send
2016-07-09 08:00:49.138 [DEBUG] [wave.internal.protocol.SerialMessage] - Assembled message buffer = 01 03 00 16 EA 
2016-07-09 08:00:49.138 [DEBUG] [ocol.ZWaveController$ZWaveSendThread] - NODE 3: Sending ABORT Message = 01 03 00 16 EA 
2016-07-09 08:00:49.138 [DEBUG] [wave.internal.protocol.SerialMessage] - Assembled message buffer = 01 03 00 16 EA 
2016-07-09 08:00:49.138 [DEBUG] [ing.zwave.handler.ZWaveSerialHandler] - NODE 255: Sending REQUEST Message = 01 03 00 16 EA 
2016-07-09 08:00:49.138 [ERROR] [ocol.ZWaveController$ZWaveSendThread] - Exception during ZWave thread: Send
java.lang.NullPointerException
        at org.openhab.binding.zwave.handler.ZWaveSerialHandler.sendPacket(ZWaveSerialHandler.java:309)[190:org.openhab.binding.zwave:2.0.0.201607080102]
        at org.openhab.binding.zwave.internal.protocol.ZWaveController$ZWaveSendThread.run(ZWaveController.java:1413)[190:org.openhab.binding.zwave:2.0.0.201607080102]
2016-07-09 08:00:49.138 [DEBUG] [ocol.ZWaveController$ZWaveSendThread] - Stopped ZWave thread: Send
2016-07-09 08:00:56.276 [INFO ] [ui.habmin.internal.servlet.HABminApp] - Stopped HABmin servlet

```
