### ISSUE TITLE
[tesla] Failed to obtain refresh token with username/password (CONFIGURATION_ERROR)

### ISSUE THREAD

**Issue by rose78ch** [openhab/openhab-addons#11077]
## Expected Behavior
Bug: 
Thing 'tesla:account:xxx' changed from OFFLINE (CONFIGURATION_ERROR): Failed to obtain refresh token with username/password. to OFFLINE (CONFIGURATION_ERROR)

Account failed to obtain code from SSO login page when submitting form, response status code: 200

## Current Behavior

In the thing tesla account the refresh token could not get with username and password.

Log file entries:
```
2021-08-01 14:41:02.207 [DEBUG] [scovery.TeslaVehicleDiscoveryService] - bundle org.openhab.binding.tesla:3.1.0 (268)[org.openhab.binding.tesla.internal.discovery.TeslaVehicleDiscoveryService(327)] : Querying state unsatisfiedReference
2021-08-01 14:41:02.207 [DEBUG] [scovery.TeslaVehicleDiscoveryService] - bundle org.openhab.binding.tesla:3.1.0 (268)[org.openhab.binding.tesla.internal.discovery.TeslaVehicleDiscoveryService(327)] : Changed state from unsatisfiedReference to satisfied
2021-08-01 14:41:02.208 [DEBUG] [scovery.TeslaVehicleDiscoveryService] - bundle org.openhab.binding.tesla:3.1.0 (268)[org.openhab.binding.tesla.internal.discovery.TeslaVehicleDiscoveryService(327)] : registration change queue [registered]
2021-08-01 14:42:05.147 [DEBUG] [internal.handler.TeslaAccountHandler] - Setting up an authenticated connection to the Tesla back-end
2021-08-01 14:42:05.539 [DEBUG] [sla.internal.handler.TeslaSSOHandler] - Obtained SSO login page
2021-08-01 14:42:05.936 [DEBUG] [sla.internal.handler.TeslaSSOHandler] - Failed to obtain code from SSO login page when submitting form, response status code: 200
```

## Possible Solution

no idea

## Steps to Reproduce (for Bugs)

1. instal binding tesla 3.1.0
2. set binding tesla in debug mode
3. add thing tesla account
4. show advanced
5. fill username and password in
6. save
7. the thing status is OFFLINE with CONFIGURATION_ERROR

## Context

The tesla binding no longer works. See also [https://community.openhab.org/t/tesla-binding-communication-error-http-returncode-400/116003/19](url)

## Your Environment

* Version used: openHAB 3.1.0
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...): openHABian v1.6.5
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): Raspbian Buster

**Comment by rose78ch** [comment]
Additional Info: If I generate the refresh token via the Tesla MFA app "Auth for Tesla" and then enter it directly in the "Tesla Account" thing, it works. To do this, I delete the username and password and save the entry.

**Comment by rose78ch** [comment]
and now I habe this NPE-Error in the log:
`2021-08-05 21:17:27.840 [WARN ] [internal.handler.TeslaVehicleHandler] - Got an unsuccessful result, setting vehicle to offline and will try again
2021-08-05 21:17:27.842 [ERROR] [internal.handler.TeslaVehicleHandler] - An error occurred while querying the vehicle
2021-08-05 21:17:27.855 [ERROR] [internal.handler.TeslaAccountHandler] - An exception occurred while executing a request to the vehicle: 'null'
java.lang.NullPointerException: null
	at org.openhab.binding.tesla.internal.handler.TeslaVehicleHandler.getVehicleId(TeslaVehicleHandler.java:226) ~[?:?]
	at org.openhab.binding.tesla.internal.handler.TeslaAccountHandler$Request.run(TeslaAccountHandler.java:465) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at org.openhab.binding.tesla.internal.throttler.QueueChannelThrottler.lambda$0(QueueChannelThrottler.java:45) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]`

**Comment by billfor** [comment]
It looks like (in my case) the tesla servers are requiring a Captcha to be solved to get the initial bearer token.
Somehow OH needs to have a mechanism, to show the captcha to the user and ask them to solve it. Not sure how that can happen interactively if it is running headless. My solution in python is below using the only library that seems to work currently (python). HA appears to be broken the same way because they use a different library. Once you solve the Captcha and get the token you can refresh it when needed and you shouldn't have to solve again.
See https://github.com/tdorssers/TeslaPy for something that works.  It would be nice to have a method to call python libraries from OH as a one-time init, so we could take advantage of work like this.

```

import teslapy
import sys

def solve_captcha(svg):
    with open('/tmp/captcha.svg', 'wb') as f:
        f.write(svg)
        f.close()
    return input('(View /tmp/captcha.svg and reply with code: Captcha: ')

with teslapy.Tesla(user, pass) as tesla:
        tesla.captcha_solver = solve_captcha
        tesla.fetch_token()
        print (tesla.token)
        sys.exit(0)
        vehicles = tesla.vehicle_list()
        print (vehicles)

```

**Comment by ScanxTaz** [comment]
Is there any update on this binding ? I'm facing a 404 issue when trying to use the binding for my tesla, while credentials are correct. I can easily play the beta tester :)

**Comment by kaikreuzer** [comment]
There is indeed an issue with obtaining refresh tokens since last summer due to the newly introduced captchas.
This essentially means that we cannot fix the current options to get hold of the token - so I solved it by adding other ways of getting the refresh token in the documentation with https://github.com/openhab/openhab-addons/pull/12015.
