### ISSUE TITLE
[influxdb] Upgrading from OH2.5 to 3.1 with influx persistence fails

### ISSUE THREAD

**Issue by perrin-1** [openhab/openhab-addons#11182]
Tried multiple times to upgrade from OH 2.5 to current OH 3.1. 
Upgrade itself works, but afterwards persistence in influx cannot load persisted items.

# To reproduce
`VMware ESXi 6.7U3`
`Ubuntu 18.04.5 LTS`
`Openhab 2.5.12`
`InfluxDB 1.8.9`

Upgrade to `Openhab 3.1.0-1`  using repository

after starting OH3 and running setup wizard, openhab.log shows these entries for each persisted item:
```
An error occurred while calling method 'QueryablePersistenceService.query()' on 'org.openhab.persistence.influxdb.InfluxDBPersistenceService@<threadID>': error parsing query: found DEFAULT, expected identifier at line 1, char 40
org.influxdb.InfluxDBException: error parsing query: found DEFAULT, expected identifier at line 1, char 40
	at org.influxdb.InfluxDBException.buildExceptionFromErrorMessage(InfluxDBException.java:161) ~[?:?]
	at org.influxdb.InfluxDBException.buildExceptionForErrorState(InfluxDBException.java:173) ~[?:?]
	at org.influxdb.impl.InfluxDBImpl.execute(InfluxDBImpl.java:827) ~[?:?]
	at org.influxdb.impl.InfluxDBImpl.executeQuery(InfluxDBImpl.java:814) ~[?:?]
	at org.influxdb.impl.InfluxDBImpl.query(InfluxDBImpl.java:714) ~[?:?]
	at org.openhab.persistence.influxdb.internal.influx1.InfluxDB1RepositoryImpl.query(InfluxDB1RepositoryImpl.java:155) ~[?:?]
	at org.openhab.persistence.influxdb.InfluxDBPersistenceService.query(InfluxDBPersistenceService.java:231) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.openhab.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:154) [bundleFile:?]
	at org.openhab.core.internal.common.Invocation.call(Invocation.java:52) [bundleFile:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

# Relevant config files

## influxdb.cfg
```
user=openhab
password=<changed>
retentionPolicy=default
```

## influxdb.persist
```
// persistence strategies have a name and a definition and are referred to in the "Items" section
Strategies {
	everyHour : "0 0 * * * ?"
	everyDay  : "0 0 0 * * ?"
  everyMinute     : "0 * * * * ?"
  every5Minutes   : "0 */5 * * * ?"

	// if no strategy is specified for an item entry below, the default list will be used
	default = everyUpdate
}

Items {
	// persist all items once a day and on every change and restore them from the db at startup
	* : strategy = everyUpdate, everyDay, restoreOnStartup
	
	
}
```

# Steps tried to fix the problem
1. Change influxdb cfg as in https://community.openhab.org/t/oh3-0-0-1-w-influx-1-7-8-2-0-restoreonstartup-fails/114332
2. Backup and Restore influx data while changing retentionpolicy as mentioned in https://community.openhab.org/t/item-averagesince-influxdb-error-parsing-query-found-48h-expected-identifier-at-line-1/111499/4

The latter leads to a new problem:
```
[org.influxdb.impl.BatchProcessor    ] - Batch could not be sent. Data will be lost
org.influxdb.InfluxDBException: retention policy not found: default
	at org.influxdb.InfluxDBException.buildExceptionFromErrorMessage(InfluxDBException.java:161) ~[bundleFile:?]
	at org.influxdb.InfluxDBException.buildExceptionForErrorState(InfluxDBException.java:173) ~[bundleFile:?]
	at org.influxdb.impl.InfluxDBImpl.execute(InfluxDBImpl.java:827) ~[bundleFile:?]
	at org.influxdb.impl.InfluxDBImpl.write(InfluxDBImpl.java:460) ~[bundleFile:?]
	at org.influxdb.impl.OneShotBatchWriter.write(OneShotBatchWriter.java:22) ~[bundleFile:?]
	at org.influxdb.impl.BatchProcessor.write(BatchProcessor.java:340) [bundleFile:?]
	at org.influxdb.impl.BatchProcessor$1.run(BatchProcessor.java:287) [bundleFile:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

I have currently rolled back to OH2.5

**Comment by J-N-K** [comment]
IMO can be closed. OH 2.5 is EOL since 12/2020. I'm not aware of any issues with upgrading from 3.x to 3.y or 4.0 snapshots

**Comment by J-N-K** [comment]
Since no-one objected, I'm closing.
