### ISSUE TITLE
[jsscripting] jsscripting automation bundle installation issues

### ISSUE THREAD

**Issue by ssalonen** [openhab/openhab-addons#11219]
I have observed errors with the jsscripting automation bundle installation.

## Expected Behavior

- after addon install, jsscripting should work without `/home/<RETRACTED>/src/openhab-tests/oh310-jsscripting-test/conf/automation/lib/javascript/personal` folder, or create it automatically.
- after addon install, openHAB restart should not be needed. Above we show how we get NullPointerException without the restart
- after addon install, future executions of javascript/ECMA script rules should use the new javascript engine, not the old one

## Current Behavior

1. User needs to create automation/lib/javascript/personal folder manually
2. User needs to restart openHAB
3. In addition, it seems even after addon installation (but before restart), openHAB might use the old javascript engine (step 7 in steps to reproduce)

## Steps to Reproduce (for Bugs)

Installation issues, steps to reproduce:

1. install 3.1.0 or 3.2.0M2 release manually
2. Settings -> Scripts -> Create Script, with type ECMAScript. We give Unique ID "oldscript"
3. Enter following contents:

```
(function (context) {
  context.log = Java.type('org.slf4j.LoggerFactory').getLogger('org.openhab.rule.' + context.ruleUID)
  
  log.info(itemRegistry)
  log.info( Java.type("org.openhab.core.items.Metadata") )
})(this);
```

4. Save Script
5. Run Now & Watch logs:

( runs without an error  this time)

```
09:32:56.314 [INFO ] [openhab.event.RuleUpdatedEvent       ] - Rule 'oldscript' has been updated.
09:33:07.472 [INFO ] [org.openhab.rule.oldscript           ] - org.openhab.core.internal.items.ItemRegistryImpl@6ab9c334
09:33:07.477 [INFO ] [org.openhab.rule.oldscript           ] - [JavaClass org.openhab.core.items.Metadata]
```

6. Install automation jsscripting through mainui
7. Re-run the oldscript (still passes without an error in logs)
8. Settings -> Scripts -> Create Script, with type ECMAScript. We give Unique ID "newscript". Enter following script contents

```javascript
(function (context) {
  context.log = Java.type('org.slf4j.LoggerFactory').getLogger('org.openhab.rule.' + context.ruleUID)
  
  log.info(itemRegistry)
  log.info( Java.type("org.openhab.core.items.Metadata") )
  const a = "this is const"
  log.info(a)
})(this);
```

9. Save Script
10. Run Now & Watch logs:

```
org.graalvm.polyglot.PolyglotException: Error: Invalid CommonJS root folder: /home/<RETRACTED>/src/openhab-tests/oh310-jsscripting-test/conf/automation/lib/javascript/personal
	at org.graalvm.polyglot.Context.eval(Context.java:345) ~[?:?]
	at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.evalInternal(GraalJSScriptEngine.java:319) ~[?:?]
	at com.oracle.truffle.js.scriptengine.GraalJSBindings.initGlobal(GraalJSBindings.java:94) ~[?:?]
	at com.oracle.truffle.js.scriptengine.GraalJSBindings.initContext(GraalJSBindings.java:90) ~[?:?]
	at com.oracle.truffle.js.scriptengine.GraalJSBindings.requireContext(GraalJSBindings.java:84) ~[?:?]
	at com.oracle.truffle.js.scriptengine.GraalJSBindings.put(GraalJSBindings.java:127) ~[?:?]
	at javax.script.SimpleScriptContext.setAttribute(SimpleScriptContext.java:246) ~[java.scripting:?]
	at org.openhab.core.automation.module.script.internal.ScriptEngineManagerImpl.addAttributeToScriptContext(ScriptEngineManagerImpl.java:249) ~[?:?]
	at org.openhab.core.automation.module.script.internal.ScriptEngineManagerImpl.createScriptEngine(ScriptEngineManagerImpl.java:139) ~[?:?]
```

11. OK -- creating the folder: `mkdir -p /home/<RETRACTED>/src/openhab-tests/oh310-jsscripting-test/conf/automation/lib/javascript/personal` (_not_ restarting openHAB in between)
12. Run script

```
09:36:44.615 [WARN ] [re.automation.internal.RuleEngineImpl] - Fail to execute action: script
java.lang.NullPointerException: null
	at com.oracle.truffle.js.scriptengine.GraalJSBindings.put(GraalJSBindings.java:128) ~[?:?]
	at javax.script.SimpleScriptContext.setAttribute(SimpleScriptContext.java:246) ~[java.scripting:?]
	at org.openhab.core.automation.module.script.internal.handler.AbstractScriptModuleHandler.setExecutionContext(AbstractScriptModuleHandler.java:117) ~[?:?]
	at org.openhab.core.automation.module.script.internal.handler.ScriptActionHandler.lambda$0(ScriptActionHandler.java:60) ~[?:?]
	at java.util.Optional.ifPresent(Optional.java:183) ~[?:?]
	at org.openhab.core.automation.module.script.internal.handler.ScriptActionHandler.execute(ScriptActionHandler.java:59) ~[?:?]
	at org.openhab.core.automation.internal.RuleEngineImpl.executeActions(RuleEngineImpl.java:1183) ~[?:?]
	at org.openhab.core.automation.internal.RuleEngineImpl.runNow(RuleEngineImpl.java:1035) ~[?:?]
```

13. Restart openHAB

14. Run oldscript (this time failing!)

```
09:37:32.147 [ERROR] [ab.automation.script.javascript.stack] - Failed to execute script:
org.graalvm.polyglot.PolyglotException: ReferenceError: "itemRegistry" is not defined
	at <js>.:anonymous(<eval>:4) ~[?:?]
	at <js>.:program(<eval>:1) ~[?:?]
	at org.graalvm.polyglot.Context.eval(Context.java:345) ~[?:?]
	at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.eval(GraalJSScriptEngine.java:379) ~[?:?]
	at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.eval(GraalJSScriptEngine.java:356) ~[?:?]
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264) ~[java.scripting:?]
```

newscript fails with same error.

(filing separate issue on this particular error -- the point is that now the error is different than before)

## Context

Trying to migrate to ES6 in rules/scripts.

## Your Environment

I can reproduce with 3.1.0 release and 3.2.0 M2.

```
Linux  5.13.13-200.fc34.x86_64 #1 SMP Thu Aug 26 17:06:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by jpg0** [comment]
I believe that the bug is that it requires the `automation/lib/javascript/personal` folder to exist, and fails without it, rather than simply warning.

This report includes the second part which has the error message: `ReferenceError: "itemRegistry" is not defined`

This is expected behaviour; if you want access to the item registry it must be imported, there are not magic predefined symbols like in the old runtime.

**Comment by ssalonen** [comment]
The itemRegistry issue is discussed in https://github.com/openhab/openhab-addons/issues/11221

**Comment by florian-h05** [comment]
@ssalonen 
Could you please check if that issue still exists? Otherwise I’ll close.

**Comment by ssalonen** [comment]
I say we close this. Probably lack of mime type separation was problematic?

Is the folder created now automatically?

**Comment by florian-h05** [comment]
> Probably lack of mime type separation was problematic?

Yes, I guess. Combined with the difference between Nashorn and JS Scripting (Nashorn implicitly imports everything, JS Scripting needs explicit imports).

> Is the folder created now automatically?

I am not sure, I’ll check later.

**Comment by florian-h05** [comment]
I’ve just performed a fresh install of openHAB on one of my test systems, the folder is automatically created.
