### ISSUE TITLE
[jsscripting] Unable to import classes from org.openhab.core

### ISSUE THREAD

**Issue by ssalonen** [openhab/openhab-addons#11222]
After installing jsscripting addon (using workaround steps documented in https://github.com/openhab/openhab-addons/issues/11219), I cannot seem to import classes from org.openhab.core, although other java imports seem to work (e.g. `org.slf4j.LoggerFactory`)

## Expected Behavior

`Java.type("org.openhab.core.items.Metadata")` should work successfully with jsscripting bundle installed, similar how it works with the default javascript engine.

## Current Behavior

Error is raised when executing script

```
09:38:32.712 [ERROR] [ab.automation.script.javascript.stack] - Failed to execute script:
org.graalvm.polyglot.PolyglotException: TypeError: Access to host class org.openhab.core.items.Metadata is not allowed or does not exist.
	at <js>.:anonymous(<eval>:5) ~[?:?]
	at <js>.:program(<eval>:1) ~[?:?]
	at org.graalvm.polyglot.Context.eval(Context.java:345) ~[?:?]
	at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.eval(GraalJSScriptEngine.java:379) ~[?:?]
	at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.eval(GraalJSScriptEngine.java:356) ~[?:?]
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264) ~[java.scripting:?]
	at org.openhab.automation.jsscripting.internal.scriptengine.DelegatingScriptEngineWithInvocable.eval(DelegatingScriptEngineWithInvocable.java:51) ~[?:?]
	at org.openhab.automation.jsscripting.internal.scriptengine.InvocationInterceptingScriptEngineWithInvocable.eval(InvocationInterceptingScriptEngineWithInvocable.java:69) ~[?:?]
	at org.openhab.automation.jsscripting.internal.scriptengine.DelegatingScriptEngineWithInvocable.eval(DelegatingScriptEngineWithInvocable.java:51) ~[?:?]
	at org.openhab.automation.jsscripting.internal.scriptengine.InvocationInterceptingScriptEngineWithInvocable.eval(InvocationInterceptingScriptEngineWithInvocable.java:69) ~[?:?]
	at org.openhab.core.automation.module.script.internal.handler.ScriptActionHandler.lambda$0(ScriptActionHandler.java:62) ~[?:?]
	at java.util.Optional.ifPresent(Optional.java:183) ~[?:?]
	at org.openhab.core.automation.module.script.internal.handler.ScriptActionHandler.execute(ScriptActionHandler.java:59) ~[?:?]
	at org.openhab.core.automation.internal.RuleEngineImpl.executeActions(RuleEngineImpl.java:1183) ~[?:?]
	at org.openhab.core.automation.internal.RuleEngineImpl.runNow(RuleEngineImpl.java:1035) ~[?:?]

```

## Steps to Reproduce (for Bugs)

1.  Follow steps in https://github.com/openhab/openhab-addons/issues/11219 to install the addon. After addon installation and openHAB restart, use the following script to get the error:

```
(function (context) {
  var log = Java.type('org.slf4j.LoggerFactory').getLogger('org.openhab.rule.' + context.ruleUID)
  
  log.info( Java.type("org.openhab.core.items.Metadata") )
})(this);
```

## Context

Trying to migrate to ES6 in rules/scripts. This is blocking such transition as, combined with https://github.com/openhab/openhab-addons/issues/11221, openHAB functionality is completely unavailable from rules/script with jsscripting addon installed.

## Your Environment

I can reproduce with 3.1.0 release and 3.2.0 M2.

```
Linux  5.13.13-200.fc34.x86_64 #1 SMP Thu Aug 26 17:06:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by LukasA83** [comment]
I'm having the same issue. The workaround identifed is no longer working:
https://github.com/jpg0/oh-config/issues/2#issuecomment-752120772

I'm unable to get services via the bundlecontext.

Any ideas @jpg0 ?

**Comment by ssalonen** [comment]
@LukasA83 please note that this particular issue I have reported is separate from ohj & ohj-support . 

Here we are talking issues experienced just with the jsscripting addon and the no -working import with openhab packages.

Are the issues you refer to related to these 3rd party plugins (ohj, ohj-support)? If so, it might be better to file the issue to their respective issue handlers?

However, I would be curious to learn if the OSGI service lookup of openHAB services also becomes non-working when jsscripting addon is installed.

**Comment by jpg0** [comment]
It's interesting that the import of the first (sl4j) class succeeds, yet it fails to import the openHAB class.

Currently the bundle is marked as `DynamicImport-Package: *` so it _should_ dynamically look up the class fine.

**Comment by LukasA83** [comment]
Right now I'm not using any ohj support addons and my issue is not related to the module "helpers" ohj provides. 
I can't get the script to recognize the injected scriptExtension object. It seems to be undefined and also not part of @runtime
