### ISSUE TITLE
[surepetcare] Sure Petcare Binding failed to load bridge

### ISSUE THREAD

**Issue by maarten-blokker** [openhab/openhab-addons#11234]
Hello, 

I'm a newcomer to Openhab, i've almost moved all of my devices to this wonderful new ecosystem, except for my two cat feeders. I've created the following thing: 

```
Bridge surepetcare:bridge:bridge_surepetcare "[SurePetcare] SurePetcare API" @ "LivingRoom" [ username="...", password="...", refreshIntervalTopology=36000, refreshIntervalStatus=300 ] {
        Thing pet                 236309 "[SurePetcare] Flint"         @ "LivingRoom"
	Thing pet                 236308 "[SurePetcare] Quinty"        @ "LivingRoom"
	Thing feederDevice 390621 "[SurePetcare] Flint feeder"  @ "LivingRoom"
	Thing feederDevice 391260 "[SurePetcare] Quinty feeder" @ "LivingRoom"
}
```

It looks like the bridge fails to load judging by the status "Status: UNINITIALIZED" and the HANDLER_INITIALIZING_ERROR message. When i dump the logs i see the following error message: 

```
[ERROR] [core.thing.internal.ThingManagerImpl] - Exception occurred while initializing handler of thing 'surepetcare:bridge:bridge_surepetcare': null
java.lang.NullPointerException: null
        at org.openhab.binding.surepetcare.internal.handler.SurePetcarePetHandler.updateThing(SurePetcarePetHandler.java:178) ~[?:?]
        at org.openhab.binding.surepetcare.internal.handler.SurePetcareBridgeHandler.updateThings(SurePetcareBridgeHandler.java:176) ~[?:?]
        at org.openhab.binding.surepetcare.internal.handler.SurePetcareBridgeHandler.initialize(SurePetcareBridgeHandler.java:84) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.openhab.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:154) [bundleFile:?]
        at org.openhab.core.internal.common.Invocation.call(Invocation.java:52) [bundleFile:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
```

It appears that the binding is not quite able to parse the response of the API. When i remove the "Thing pet" entries from the bridge, it starts up just fine. It looks like the [SurePetcarePetHandler](https://github.com/renescherer/openhab-addons/blob/master/bundles/org.openhab.binding.surepetcare/src/main/java/org/openhab/binding/surepetcare/internal/handler/SurePetcarePetHandler.java#L178) is not expecting `pet.status.activity` to be null.

Im running my openhab 3.1.0 on raspberry pi 4 (8GB). 

I created a pull request that should fix this issue: https://github.com/openhab/openhab-addons/pull/11235

**Comment by maarten-blokker** [comment]
This is the result of calling the sure petcare api `/api/pet`

```json
{
    "data": [{
        "id": 236308,
        "name": "Quinty",
        "gender": 1,
        "date_of_birth": "2021-08-01T00:00:00+00:00",
        "weight": "5000",
        "comments": "",
        "household_id": 100836,
        "spayed": 1,
        "breed_id": 342,
        "food_type_id": 3,
        "photo_id": 324351,
        "species_id": 1,
        "tag_id": 219824,
        "version": "Mg==",
        "created_at": "2021-06-25T19:03:35+00:00",
        "updated_at": "2021-09-09T18:23:09+00:00",
        "breed": {
            "id": 342,
            "name": "Britse korthaar ",
            "species_id": 1,
            "version": "MA=="
        },
        "conditions": [{
            "id": 25,
            "version": "MA==",
            "created_at": "2021-09-09T18:23:09+00:00",
            "updated_at": "2021-09-09T18:23:09+00:00"
        }],
        "photo": {
            "id": 324351,
            "location": "...",
            "uploading_user_id": 3139023704,
            "version": "MA==",
            "created_at": "2021-09-09T18:23:09+00:00",
            "updated_at": "2021-09-09T18:23:09+00:00"
        },
        "species": {
            "id": 1,
            "name": "Kat",
            "version": "MA=="
        },
        "status": {
            "feeding": {
                "tag_id": 219824,
                "device_id": 391260,
                "change": [-16.34, 0.01],
                "at": "2021-09-09T16:16:28+00:00"
            }
        },
        "tag": {
            "id": 219824,
            "tag": "528.210004616118",
            "version": "MQ==",
            "created_at": "2021-01-19T17:38:33+00:00",
            "updated_at": "2021-01-19T17:38:33+00:00",
            "supported_product_ids": [3, 4, 6, 8]
        }
    }, {
        "id": 236309,
        "name": "Flint",
        "gender": 1,
        "date_of_birth": "2021-09-06T00:00:00+00:00",
        "weight": "5000",
        "comments": "",
        "household_id": 100836,
        "spayed": 1,
        "breed_id": 342,
        "food_type_id": 3,
        "photo_id": 324352,
        "species_id": 1,
        "tag_id": 219825,
        "version": "Mg==",
        "created_at": "2021-06-25T19:04:37+00:00",
        "updated_at": "2021-09-09T18:24:08+00:00",
        "breed": {
            "id": 342,
            "name": "Britse korthaar ",
            "species_id": 1,
            "version": "MA=="
        },
        "conditions": [{
            "id": 25,
            "version": "MA==",
            "created_at": "2021-09-09T18:24:08+00:00",
            "updated_at": "2021-09-09T18:24:08+00:00"
        }],
        "photo": {
            "id": 324352,
            "location": "...",
            "uploading_user_id": 3139023704,
            "version": "MA==",
            "created_at": "2021-09-09T18:24:07+00:00",
            "updated_at": "2021-09-09T18:24:07+00:00"
        },
        "species": {
            "id": 1,
            "name": "Kat",
            "version": "MA=="
        },
        "status": {
            "feeding": {
                "tag_id": 219825,
                "device_id": 390621,
                "change": [-30.46, -0.08],
                "at": "2021-09-09T16:16:48+00:00"
            }
        },
        "tag": {
            "id": 219825,
            "tag": "528.246002555545",
            "version": "MQ==",
            "created_at": "2021-01-19T17:40:45+00:00",
            "updated_at": "2021-01-19T17:40:45+00:00",
            "supported_product_ids": [3, 4, 6, 8]
        }
    }]
}
```
