### ISSUE TITLE
[mielecloud] AbstractMieleThingHandlerTest unstable

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-addons#11283]
Often the `AbstractMieleThingHandlerTest` fails.

See for instance this build: https://ci.openhab.org/job/openHAB-Addons/478

```
TEST org.openhab.binding.mielecloud.internal.handler.WineStorageDeviceThingHandlerTest#testHandleCommandProgramStopToStartStopChannel() <<< ERROR: 
Wanted but not invoked:
mieleWebservice.putProcessAction(
    "000124430017",
    STOP
);
-> at org.openhab.binding.mielecloud.internal.handler.AbstractMieleThingHandlerTest.lambda$4(AbstractMieleThingHandlerTest.java:437)

However, there was exactly 1 interaction with this mock:
mieleWebservice.dispatchDeviceState(
    "000124430017"
);
-> at org.openhab.binding.mielecloud.internal.handler.AbstractMieleThingHandler.initialize(AbstractMieleThingHandler.java:100)


Wanted but not invoked:
mieleWebservice.putProcessAction(
    "000124430017",
    STOP
);
-> at org.openhab.binding.mielecloud.internal.handler.AbstractMieleThingHandlerTest.lambda$4(AbstractMieleThingHandlerTest.java:437)

However, there was exactly 1 interaction with this mock:
mieleWebservice.dispatchDeviceState(
    "000124430017"
);
-> at org.openhab.binding.mielecloud.internal.handler.AbstractMieleThingHandler.initialize(AbstractMieleThingHandler.java:100)


	at org.openhab.binding.mielecloud.internal.handler.AbstractMieleThingHandlerTest.lambda$4(AbstractMieleThingHandlerTest.java:437)
	at org.openhab.core.test.java.JavaTest.waitForAssert(JavaTest.java:152)
	at org.openhab.core.test.java.JavaTest.waitForAssert(JavaTest.java:120)
	at org.openhab.core.test.java.JavaTest.waitForAssert(JavaTest.java:73)
	at org.openhab.binding.mielecloud.internal.handler.AbstractMieleThingHandlerTest.testHandleCommandProgramStopToStartStopChannel(AbstractMieleThingHandlerTest.java:436)
```

Can you have a look at this @BjoernLange?

**Comment by BjoernLange** [comment]
Of course.

**Comment by BjoernLange** [comment]
Hi @wborn, I had a look at this and suspect a timing issue. The failing tests use `waitForAssert` and, depending on the load on the CI system, the default timeout might be too short. I'll prepare a PR that increases the timeout.
