### ISSUE TITLE
[keba] wallbox not initializing: "Cache expire time must be greater than 0"

### ISSUE THREAD

**Issue by vonEcke** [openhab/openhab-addons#11311]
## Current Behavior
When initializing the wallbox P30 c-series throws an error: "Cache expire time must be greater than 0". The wallbox can be reached by its internal web-server and was working before in openhab. 

## Context
After shutting down the main power and restarting after 2 weeks the binding went into this state. Deleting openhabs cache, reinstalling the things and the keba binding did not solve the issue.

## Your Environment
Running on openhab 3.1.0 in a docker container on a synology.

##Log
2021-09-26 19:28:28.459 [INFO ] [nternal.handler.KeContactTransceiver] - Listening for incoming data on /0:0:0:0:0:0:0:0:7090
2021-09-26 19:28:28.465 [ERROR] [nal.common.AbstractInvocationHandler] - An error occurred while calling method 'ThingHandler.initialize()' on 'org.openhab.binding.keba.internal.handler.KeContactHandler@434b32da': Cache expire time must be greater than 0
java.lang.IllegalArgumentException: Cache expire time must be greater than 0
	at org.openhab.core.cache.ExpiringCache.<init>(ExpiringCache.java:50) ~[bundleFile:?]
	at org.openhab.core.cache.ExpiringCache.<init>(ExpiringCache.java:63) ~[bundleFile:?]
	at org.openhab.core.cache.ExpiringCacheMap.put(ExpiringCacheMap.java:73) ~[bundleFile:?]
	at org.openhab.binding.keba.internal.handler.KeContactHandler.initialize(KeContactHandler.java:111) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor84.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.openhab.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:154) [bundleFile:?]
	at org.openhab.core.internal.common.Invocation.call(Invocation.java:52) [bundleFile:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
2021-09-26 19:28:28.542 [ERROR] [core.thing.internal.ThingManagerImpl] - Exception occurred while initializing handler of thing 'keba:kecontact:Wallbox_links': Cache expire time must be greater than 0
java.lang.IllegalArgumentException: Cache expire time must be greater than 0
	at org.openhab.core.cache.ExpiringCache.<init>(ExpiringCache.java:50) ~[bundleFile:?]
	at org.openhab.core.cache.ExpiringCache.<init>(ExpiringCache.java:63) ~[bundleFile:?]
	at org.openhab.core.cache.ExpiringCacheMap.put(ExpiringCacheMap.java:73) ~[bundleFile:?]
	at org.openhab.binding.keba.internal.handler.KeContactHandler.initialize(KeContactHandler.java:111) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor84.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.openhab.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:154) [bundleFile:?]
	at org.openhab.core.internal.common.Invocation.call(Invocation.java:52) [bundleFile:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
2021-09-26 19:28:43.542 [ERROR] [nal.common.AbstractInvocationHandler] - An error occurred while calling method 'ThingHandler.initialize()' on 'org.openhab.binding.keba.internal.handler.KeContactHandler@343a0f1f': Cache expire time must be greater than 0
java.lang.IllegalArgumentException: Cache expire time must be greater than 0
	at org.openhab.core.cache.ExpiringCache.<init>(ExpiringCache.java:50) ~[bundleFile:?]
	at org.openhab.core.cache.ExpiringCache.<init>(ExpiringCache.java:63) ~[bundleFile:?]
	at org.openhab.core.cache.ExpiringCacheMap.put(ExpiringCacheMap.java:73) ~[bundleFile:?]
	at org.openhab.binding.keba.internal.handler.KeContactHandler.initialize(KeContactHandler.java:111) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor84.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.openhab.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:154) [bundleFile:?]
	at org.openhab.core.internal.common.Invocation.call(Invocation.java:52) [bundleFile:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
2021-09-26 19:28:43.545 [ERROR] [core.thing.internal.ThingManagerImpl] - Exception occurred while initializing handler of thing 'keba:kecontact:Wallbox_rechts': Cache expire time must be greater than 0
java.lang.IllegalArgumentException: Cache expire time must be greater than 0
	at org.openhab.core.cache.ExpiringCache.<init>(ExpiringCache.java:50) ~[bundleFile:?]
	at org.openhab.core.cache.ExpiringCache.<init>(ExpiringCache.java:63) ~[bundleFile:?]
	at org.openhab.core.cache.ExpiringCacheMap.put(ExpiringCacheMap.java:73) ~[bundleFile:?]
	at org.openhab.binding.keba.internal.handler.KeContactHandler.initialize(KeContactHandler.java:111) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor84.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.openhab.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:154) [bundleFile:?]
	at org.openhab.core.internal.common.Invocation.call(Invocation.java:52) [bundleFile:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]

**Comment by vonEcke** [comment]
Problem solved with a work around, the refreshInterval was chosen quite low with 5. Setting this up to 30 solved the issue.
