### ISSUE TITLE
[unifi] CONFIGURATION_ERROR (status code 404) after reloding things-file

### ISSUE THREAD

**Issue by nimric** [openhab/openhab-addons#11334]
I have a Raspberry with openHab 3.1 and the UniFi binding running. My thinks file is the following to integrate my UniFi CloudKey Gen2 Plus:

`Bridge unifi:controller:cloudKey "UniFi CloudKey" [host="192.168.2.2", port=443, username="openHAB", password="...", unifios="true", refresh=30]`

When I reboot my Rasperry everything is fine.
```
2021-10-01 12:04:27.671 [DEBUG] [fi.internal.UniFiThingHandlerFactory] - bundle org.openhab.binding.unifi:3.1.0 (268)[org.openhab.binding.unifi.internal.UniFiThingHandlerFactory(307)] : invoked activate: activate
2021-10-01 12:04:27.672 [DEBUG] [fi.internal.UniFiThingHandlerFactory] - bundle org.openhab.binding.unifi:3.1.0 (268)[org.openhab.binding.unifi.internal.UniFiThingHandlerFactory(307)] : Set implementation object for component
2021-10-01 12:04:27.673 [DEBUG] [fi.internal.UniFiThingHandlerFactory] - bundle org.openhab.binding.unifi:3.1.0 (268)[org.openhab.binding.unifi.internal.UniFiThingHandlerFactory(307)] : Changed state from satisfied to active
2021-10-01 12:04:27.782 [DEBUG] [.handler.UniFiControllerThingHandler] - Initializing the UniFi Controller Handler with config = UniFiControllerConfig{host = 192.168.2.2, port = 443, username = openHAB, password = *****, refresh = 30, unifios = true}
2021-10-01 12:04:27.804 [TRACE] [nal.api.model.UniFiControllerRequest] - >> POST https://192.168.2.2/api/auth/login
2021-10-01 12:04:28.701 [TRACE] [nal.api.model.UniFiControllerRequest] - << 200 OK
```
However, if I change the file the bridge shows me a configuration error because of the status code 404.
 ```
2021-10-01 12:19:08.766 [TRACE] [nal.api.model.UniFiControllerRequest] - >> GET https://192.168.2.2/api/auth/logout
2021-10-01 12:19:08.910 [INFO ] [el.core.internal.ModelRepositoryImpl] - Loading model 'unifi.things'
2021-10-01 12:19:08.982 [DEBUG] [.handler.UniFiControllerThingHandler] - Initializing the UniFi Controller Handler with config = UniFiControllerConfig{host = 192.168.2.2, port = 443, username = openHAB, password = *****, refresh = 30, unifios = true}
2021-10-01 12:19:08.983 [TRACE] [nal.api.model.UniFiControllerRequest] - >> POST https://192.168.2.2/api/auth/login
2021-10-01 12:19:09.017 [ERROR] [.handler.UniFiControllerThingHandler] - Unknown error while configuring the UniFi Controller
org.openhab.binding.unifi.internal.api.UniFiException: Unknown HTTP status code 404 returned by the controller
	at org.openhab.binding.unifi.internal.api.model.UniFiControllerRequest.getContent(UniFiControllerRequest.java:167) ~[bundleFile:?]
	at org.openhab.binding.unifi.internal.api.model.UniFiControllerRequest.execute(UniFiControllerRequest.java:131) ~[bundleFile:?]
	at org.openhab.binding.unifi.internal.api.model.UniFiController.executeRequest(UniFiController.java:207) ~[bundleFile:?]
	at org.openhab.binding.unifi.internal.api.model.UniFiController.login(UniFiController.java:114) ~[bundleFile:?]
	at org.openhab.binding.unifi.internal.api.model.UniFiController.start(UniFiController.java:97) ~[bundleFile:?]
	at org.openhab.binding.unifi.internal.handler.UniFiControllerThingHandler.initialize(UniFiControllerThingHandler.java:92) [bundleFile:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.openhab.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:154) [bundleFile:?]
	at org.openhab.core.internal.common.Invocation.call(Invocation.java:52) [bundleFile:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
2021-10-01 12:19:10.072 [INFO ] [el.core.internal.ModelRepositoryImpl] - Loading model 'unifi.things'
 ```
I am not sure if it's relvant fot this bug, but I noticed that there is no log entry for the request to obtain a csrf token.

**Comment by timbms** [comment]
Same issue for me

**Comment by lsiepel** [comment]
Details are missing, like unifi and openHAB version. Could you check with openHAB 3.4.x and the latest unifi os release if the problem still exists? Many [PRs have been merged since 2021] (https://github.com/openhab/openhab-addons/pulls?q=is%3Apr+is%3Aclosed+unifi+in%3Atitle+) and some are related to stability and unifi os changes. 

If this is no longer an issue, i suggest to close this.
