### ISSUE TITLE
[upb] SerialIoThreadTest unstable

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-addons#11364]
This test failed in: https://ci.openhab.org/job/PR-openHAB-Addons/5798/

```
[ERROR] Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 7.076 s <<< FAILURE! - in org.openhab.binding.upb.internal.SerialIoThreadTest
[ERROR] org.openhab.binding.upb.internal.SerialIoThreadTest.send  Time elapsed: 0.093 s  <<< FAILURE!
org.opentest4j.AssertionFailedError:
expected: <^W70028E
> but was: <^T0810020>
        at org.openhab.binding.upb.internal.SerialIoThreadTest.verifyMessageModeCmd(SerialIoThreadTest.java:168)
        at org.openhab.binding.upb.internal.SerialIoThreadTest.send(SerialIoThreadTest.java:101)
```

Can you have a look at it @marcusb?

**Comment by marcusb** [comment]
@wborn oops. fix here: https://github.com/openhab/openhab-addons/pull/11366
