### ISSUE TITLE
enocean: ConcurrentModificationException while startup

### ISSUE THREAD

**Issue by UrsusS** [openhab/openhab-addons#11393]
On startup of openHAB 3.2.0.M3 I received this error:

```
2021-10-16 12:43:31.567 [ERROR] [core.thing.internal.ThingManagerImpl] - Exception occurred during notification about bridge status change on thing 'enocean:mechanicalHandle:FT1ZI6SV:FensterGriffWoZiWiGa': null
java.util.ConcurrentModificationException: null
	at java.util.HashMap.computeIfAbsent(HashMap.java:1134) ~[?:?]
	at org.openhab.binding.enocean.internal.transceiver.EnOceanTransceiver.addPacketListener(EnOceanTransceiver.java:378) ~[?:?]
	at org.openhab.binding.enocean.internal.handler.EnOceanBridgeHandler.addPacketListener(EnOceanBridgeHandler.java:383) ~[?:?]
	at org.openhab.binding.enocean.internal.handler.EnOceanBridgeHandler.addPacketListener(EnOceanBridgeHandler.java:378) ~[?:?]
	at org.openhab.binding.enocean.internal.handler.EnOceanBaseSensorHandler.validateConfig(EnOceanBaseSensorHandler.java:105) ~[?:?]
	at org.openhab.binding.enocean.internal.handler.EnOceanBaseThingHandler.initializeThing(EnOceanBaseThingHandler.java:99) ~[?:?]
	at org.openhab.binding.enocean.internal.handler.EnOceanBaseThingHandler.bridgeStatusChanged(EnOceanBaseThingHandler.java:259) ~[?:?]
	at org.openhab.core.thing.internal.ThingManagerImpl$5.run(ThingManagerImpl.java:964) [bundleFile:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

In total there are 6 mechanicalHandles, one genericThing and one temperatureHumiditySensor defined.
Only the thing which throws that error does not work. Reloading of the thing-file solved that.

```
Bridge enocean:bridge:FT1ZI6SV	"EnOcean Gateway" @ "Flur EG"
[
	path="/dev/ttyUSB0",
	enableSmack=true,
	espVersion="ESP3"
]
{
	Thing mechanicalHandle FensterGriffWoZiWiGa			"Türgriff Wohnzimmer-Wintergarten" @ "Wohnzimmer"
	[
		enoceanId="0517E6EE",
		receivingEEPId="F6_10_00"
	]
}
```

**Comment by DrRSatzteil** [comment]
This bug also exists in versions prior to 3.2

I'm on 3.1 and I also observe this from time to time
