### ISSUE TITLE
Astro binding: Unable to store Job

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-addons#1154]
Using offline distro 426, sometimes I got this error at startup:

```
23:14:29.108 [ERROR] [ding.astro.handler.AstroThingHandler] - Unable to store Job : 'astro:sun:local.DailyJob', because one already exists with this identification.
org.quartz.ObjectAlreadyExistsException: Unable to store Job : 'astro:sun:local.DailyJob', because one already exists with this identification.
        at org.quartz.simpl.RAMJobStore.storeJob(RAMJobStore.java:279)[101:org.eclipse.smarthome.core.scheduler:0.9.0.201607221840]
        at org.quartz.simpl.RAMJobStore.storeJobAndTrigger(RAMJobStore.java:251)[101:org.eclipse.smarthome.core.scheduler:0.9.0.201607221840]
        at org.quartz.core.QuartzScheduler.scheduleJob(QuartzScheduler.java:886)[101:org.eclipse.smarthome.core.scheduler:0.9.0.201607221840]
        at org.quartz.impl.StdScheduler.scheduleJob(StdScheduler.java:249)[101:org.eclipse.smarthome.core.scheduler:0.9.0.201607221840]
        at org.openhab.binding.astro.handler.AstroThingHandler$1.run(AstroThingHandler.java:185)[189:org.openhab.binding.astro:2.0.0.201607260102]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)[:1.8.0]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)[:1.8.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0]
        at java.lang.Thread.run(Thread.java:744)[:1.8.0]
```

The thing remains in INITIALIZING state.

**Comment by kaikreuzer** [comment]
@gerrieg I saw this once as well - could you have a look?

**Comment by gerrieg** [comment]
Hard to identify if it happens only occasionally. The code looks good, all jobs in the jobGroup (thingID) are removed before they are scheduled.

**Comment by lolodomo** [comment]
@gerrieg  @kaikreuzer : restartJobs() is called in initialize() and in linkedChannelChange().
Maybe a problem of concurrent access ?

**Comment by gerrieg** [comment]
@lolodomo 
yes, that's it. Thanks for the hint!

**Comment by kaikreuzer** [comment]
Fixed through https://github.com/openhab/openhab2-addons/pull/1178.
