### ISSUE TITLE
Netatmo - Thermostat Module  Pending parent object initialization 

### ISSUE THREAD

**Issue by zar1978** [openhab/openhab-addons#11544]
Hello, I'm trying to add my netatmo thermostat.

## Expected Behavior

- Netatmo API **ONLINE**
- Thermostat Module **ONLINE**
- Thermostat Relay/Plug **ONLINE**

## Current Behavior

- Netatmo API **ONLINE**
- Thermostat Module **OFFLINE**
- Thermostat Relay/Plug **ONLINE**

 This is the configuration:

```
    Bridge netatmo:netatmoapi:home [ 
        clientId="",
        clientSecret="",
        username = "", 
        password = "", 
        readStation=true, 
        readHealthyHomeCoach=false,
        readThermostat=true, 
        readWelcome=false]
    {
	    Thing NAPlug    plugtherm  	"Relay Netatmo - CipuHome"				[ id="70:ee:50:1e:84:04", refreshInterval=60000]
        Thing NATherm1  thermostat 	"Termostato - Netatmo CipuHome"			[ id="04:00:00:1e:44:d4", parentId="70:ee:50:1e:84:04" ]
    } 
```
On the web interface I read this error:

```
The thing is offline,  Pending parent object initialization  
```

From the log file:

```
`2021-11-08 07:53:45.006 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception: 

com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected an int but was BOOLEAN at line 1 column 360 path $.body.devices[0].plug_connected_boiler

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226) ~[?:?]

	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[?:?]

	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82) ~[?:?]

	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61) ~[?:?]

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131) ~[?:?]

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222) ~[?:?]

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131) ~[?:?]

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222) ~[?:?]

	at com.google.gson.Gson.fromJson(Gson.java:927) ~[?:?]

	at com.google.gson.Gson.fromJson(Gson.java:892) ~[?:?]

	at com.google.gson.Gson.fromJson(Gson.java:841) ~[?:?]

	at io.swagger.client.JSON.deserialize(JSON.java:134) ~[?:?]

	at io.swagger.client.ApiClient.deserialize(ApiClient.java:711) ~[?:?]

	at io.swagger.client.ApiClient.handleResponse(ApiClient.java:914) ~[?:?]

	at io.swagger.client.ApiClient.execute(ApiClient.java:841) ~[?:?]

	at io.swagger.client.api.ThermostatApi.getthermostatsdataWithHttpInfo(ThermostatApi.java:471) ~[?:?]

	at io.swagger.client.api.ThermostatApi.getthermostatsdata(ThermostatApi.java:457) ~[?:?]

	at org.openhab.binding.netatmo.internal.handler.NetatmoBridgeHandler.lambda$6(NetatmoBridgeHandler.java:315) ~[?:?]

	at java.util.Optional.map(Optional.java:265) ~[?:?]

	at org.openhab.binding.netatmo.internal.handler.NetatmoBridgeHandler.getThermostatsDataBody(NetatmoBridgeHandler.java:315) ~[?:?]

	at org.openhab.binding.netatmo.internal.thermostat.NAPlugHandler.lambda$0(NAPlugHandler.java:50) ~[?:?]

	at java.util.Optional.flatMap(Optional.java:294) ~[?:?]

	at org.openhab.binding.netatmo.internal.thermostat.NAPlugHandler.updateReadings(NAPlugHandler.java:50) ~[?:?]

	at org.openhab.binding.netatmo.internal.handler.NetatmoDeviceHandler.updateChannels(NetatmoDeviceHandler.java:127) ~[?:?]

	at org.openhab.binding.netatmo.internal.handler.NetatmoDeviceHandler.updateChannels(NetatmoDeviceHandler.java:110) ~[?:?]

	at java.util.Optional.ifPresent(Optional.java:183) ~[?:?]

	at org.openhab.binding.netatmo.internal.handler.NetatmoModuleHandler.requestParentRefresh(NetatmoModuleHandler.java:120) ~[?:?]

	at org.openhab.binding.netatmo.internal.handler.NetatmoModuleHandler.lambda$0(NetatmoModuleHandler.java:55) ~[?:?]

	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]

	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]

	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]

	at java.lang.Thread.run(Thread.java:829) [?:?]

Caused by: java.lang.IllegalStateException: Expected an int but was BOOLEAN at line 1 column 360 path $.body.devices[0].plug_connected_boiler

	at com.google.gson.stream.JsonReader.nextInt(JsonReader.java:1197) ~[?:?]

	at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:226) ~[?:?]

	at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:218) ~[?:?]

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131) ~[?:?]

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222) ~[?:?]

	... 33 more
```
## MyEnvironment

- openHAB 3.1.0 Release Build
- Operating System: Raspbian GNU/Linux 10 (buster)
- Kernel: Linux 5.10.63-v7+
- Architecture: arm
- Relè Serial number g1e8404 firmware 222
- Thermostat Module serial number firmware 75
- Raspberry Pi 3 Model B Plus Rev 1.3

## Possible Solution

I saw that the same problem was reported here

#4509

And fixed here:

#4781

But the problem returned.

Thanks.

**Comment by clinique** [comment]
This will not be adressed in current version of the Netatmo binding. It is adressed in [this version](https://github.com/openhab/openhab-addons/pull/10831). While still not merged, you can use it safely.
