### ISSUE TITLE
[mielecloud] HoodDeviceThingHandlerTest unstable

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-addons#11589]
This test failed in: https://github.com/openhab/openhab-addons/actions/runs/1461411153/attempts/1

```
TEST org.openhab.binding.mielecloud.internal.handler.HoodDeviceThingHandlerTest#testFailingPutProcessActionDoesNotSetTheDeviceToOffline() <<< ERROR: 
Unfinished stubbing detected here:
-> at org.openhab.binding.mielecloud.internal.handler.AbstractMieleThingHandlerTest.testFailingPutProcessActionDoesNotSetTheDeviceToOffline(AbstractMieleThingHandlerTest.java:413)
E.g. thenReturn() may be missing.
Examples of correct stubbing:
    when(mock.isOk()).thenReturn(true);
    when(mock.isOk()).thenThrow(exception);
    doThrow(exception).when(mock).someVoidMethod();
Hints:
 1. missing thenReturn()
 2. you are trying to stub a final method, which is not supported
 3. you are stubbing the behaviour of another mock inside before 'thenReturn' instruction is completed
org.mockito.exceptions.misusing.UnfinishedStubbingException: 
Unfinished stubbing detected here:
-> at org.openhab.binding.mielecloud.internal.handler.AbstractMieleThingHandlerTest.testFailingPutProcessActionDoesNotSetTheDeviceToOffline(AbstractMieleThingHandlerTest.java:413)
E.g. thenReturn() may be missing.
Examples of correct stubbing:
    when(mock.isOk()).thenReturn(true);
    when(mock.isOk()).thenThrow(exception);
    doThrow(exception).when(mock).someVoidMethod();
Hints:
 1. missing thenReturn()
 2. you are trying to stub a final method, which is not supported
 3. you are stubbing the behaviour of another mock inside before 'thenReturn' instruction is completed
	at org.openhab.binding.mielecloud.internal.handler.AbstractMieleThingHandlerTest.testFailingPutProcessActionDoesNotSetTheDeviceToOffline(AbstractMieleThingHandlerTest.java:413)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
...
```

Can you have a look at it @BjoernLange?

**Comment by BjoernLange** [comment]
Yes.

**Comment by BjoernLange** [comment]
Are the surefire tests configured to execute in parallel @wborn? Could it be a concurrency issue?

**Comment by wborn** [comment]
It executes tests sequentially, see the plugin [configuration](https://github.com/openhab/openhab-addons/blob/82ac5ee2d90190838a3d5e540834d094e8679173/pom.xml#L383-L392). It can for instance be caused by scheduled tasks that run before the stubbing completed.

**Comment by BjoernLange** [comment]
I think I found the cause for the issues and opened a PR, could you please review it @wborn?
