### ISSUE TITLE
[senechome] null pointer errors with SENEC.Home 8.0 Pb

### ISSUE THREAD

**Issue by thopiekar** [openhab/openhab-addons#11606]
## Expected Behavior
Binding goes from UNINITIALIZED to ONLINE on start and operates normally as in OH2.

## Current Behavior
Binding is stuck in INITIALIZING and the logs mentions a null pointer error.

## Possible Solution
Latest contributions are for more modern products. I can imagine that the old PB device responds unexpected data to OH3.

## Steps to Reproduce (for Bugs)
1. Install the binding
2. Connect it with a SENEC.Home 8.0 Pb

## Context
The binding is not usable at all.

## Your Environment

* Version used: openHAB 3.1.0
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...): Chrome or any other browser
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): Synology DSM

**Comment by thopiekar** [comment]
@vctender @KorbinianP @eguib

**Comment by KorbinianP** [comment]
Hello @thopiekar , tnx for the notification, without it I would have never seen it. Can you copy and post the log message? Without it I have no clue where to start.
Cheers

**Comment by thopiekar** [comment]
Hello @KorbinianP ,

yeah, it was unusually quiet here. That's why I took a look at the list of addon maintainers.
Here is the log message as wished:
```
2022-01-03 18:10:04.134 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception: 
java.lang.NullPointerException: null
        at org.openhab.binding.senechome.internal.SenecHomeHandler.refreshState(SenecHomeHandler.java:214) ~[?:?]
        at org.openhab.core.cache.ExpiringCache.refreshValue(ExpiringCache.java:101) ~[?:?]
        at org.openhab.core.cache.ExpiringCache.getValue(ExpiringCache.java:72) ~[?:?]
        at org.openhab.binding.senechome.internal.SenecHomeHandler.refresh(SenecHomeHandler.java:133) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
        at java.util.concurrent.FutureTask.runAndReset(Unknown Source) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
```

**Comment by eguib** [comment]
I guess that the returned JSON (from 8.0 Pb) has another structure as for the newer devices (Home V2/V3)
Can you enable trace logging for SenecHomeHandler and post the returned JSON?

=> add <Logger level="TRACE" name="org.openhab.binding.senechome"/> to ./userdata/etc/log4j2.xml and restart.

The JSON should be logged with the prefix "received " on the SenecHomeHandler  logger.
=> look into ./userdata/logs/openhab.log

**Comment by thopiekar** [comment]
Thank you both for reaching back! Here is the further info as requested (plus some extra lines):
```
2022-01-05 18:19:25.746 [DEBUG] [ome.internal.SenecHomeHandlerFactory] - bundle org.openhab.binding.senechome:3.1.0 (268)[org.openhab.binding.senechome.internal.SenecHomeHandlerFactory] : BundleComponentActivator : ComponentHolder created.
2022-01-05 18:19:25.749 [DEBUG] [ome.internal.SenecHomeHandlerFactory] - bundle org.openhab.binding.senechome:3.1.0 (268)[org.openhab.binding.senechome.internal.SenecHomeHandlerFactory] : Dependency Manager created $000interface=org.openhab.core.io.net.http.HttpClientFactory, filter=null, policy=static, cardinality=1..1, bind=null, unbind=null, updated=null, field=null, field-option=null, collection-type=null, parameter=0
2022-01-05 18:19:25.754 [DEBUG] [ome.internal.SenecHomeHandlerFactory] - bundle org.openhab.binding.senechome:3.1.0 (268)[org.openhab.binding.senechome.internal.SenecHomeHandlerFactory] : Component created: DS=DS14, implementation=org.openhab.binding.senechome.internal.SenecHomeHandlerFactory, immediate=false, default-enabled=true, factory=null, configuration-policy=optional, activate=activate, deactivate=deactivate, modified=null configuration-pid=[binding.senechome]
2022-01-05 18:19:25.756 [DEBUG] [ome.internal.SenecHomeHandlerFactory] - bundle org.openhab.binding.senechome:3.1.0 (268)[org.openhab.binding.senechome.internal.SenecHomeHandlerFactory] : Component Services: scope=singleton, services=[org.openhab.core.thing.binding.ThingHandlerFactory]
2022-01-05 18:19:25.757 [DEBUG] [ome.internal.SenecHomeHandlerFactory] - bundle org.openhab.binding.senechome:3.1.0 (268)[org.openhab.binding.senechome.internal.SenecHomeHandlerFactory] : Component Properties: {}
2022-01-05 18:19:25.758 [DEBUG] [ome.internal.SenecHomeHandlerFactory] - bundle org.openhab.binding.senechome:3.1.0 (268)[org.openhab.binding.senechome.internal.SenecHomeHandlerFactory] : Querying state disabled
2022-01-05 18:19:25.763 [DEBUG] [ome.internal.SenecHomeHandlerFactory] - bundle org.openhab.binding.senechome:3.1.0 (268)[org.openhab.binding.senechome.internal.SenecHomeHandlerFactory] : Querying state disabled
2022-01-05 18:19:25.767 [DEBUG] [ome.internal.SenecHomeHandlerFactory] - bundle org.openhab.binding.senechome:3.1.0 (268)[org.openhab.binding.senechome.internal.SenecHomeHandlerFactory] : Component can not be activated since it is in state disabled
2022-01-05 18:19:25.790 [DEBUG] [ome.internal.SenecHomeHandlerFactory] - bundle org.openhab.binding.senechome:3.1.0 (268)[org.openhab.binding.senechome.internal.SenecHomeHandlerFactory] : Querying state disabled
2022-01-05 18:19:25.791 [DEBUG] [ome.internal.SenecHomeHandlerFactory] - bundle org.openhab.binding.senechome:3.1.0 (268)[org.openhab.binding.senechome.internal.SenecHomeHandlerFactory(311)] : Updating target filters
2022-01-05 18:19:25.808 [DEBUG] [ome.internal.SenecHomeHandlerFactory] - bundle org.openhab.binding.senechome:3.1.0 (268)[org.openhab.binding.senechome.internal.SenecHomeHandlerFactory(311)] : No change in target property for dependency $000: currently registered: false
2022-01-05 18:19:25.809 [DEBUG] [ome.internal.SenecHomeHandlerFactory] - bundle org.openhab.binding.senechome:3.1.0 (268)[org.openhab.binding.senechome.internal.SenecHomeHandlerFactory(311)] :  No existing service listener to unregister for dependency $000
2022-01-05 18:19:25.823 [DEBUG] [ome.internal.SenecHomeHandlerFactory] - bundle org.openhab.binding.senechome:3.1.0 (268)[org.openhab.binding.senechome.internal.SenecHomeHandlerFactory(311)] : Setting target property for dependency $000 to null
2022-01-05 18:19:25.832 [DEBUG] [ome.internal.SenecHomeHandlerFactory] - bundle org.openhab.binding.senechome:3.1.0 (268)[org.openhab.binding.senechome.internal.SenecHomeHandlerFactory(311)] : New service tracker for $000, initial active: false, previous references: {}, classFilter: (objectClass=org.openhab.core.io.net.http.HttpClientFactory), initialReferenceFilter (objectClass=org.openhab.core.io.net.http.HttpClientFactory)
2022-01-05 18:19:25.833 [DEBUG] [ome.internal.SenecHomeHandlerFactory] - bundle org.openhab.binding.senechome:3.1.0 (268)[org.openhab.binding.senechome.internal.SenecHomeHandlerFactory(311)] : dm $000 tracker reset (closed)
2022-01-05 18:19:25.853 [DEBUG] [ome.internal.SenecHomeHandlerFactory] - bundle org.openhab.binding.senechome:3.1.0 (268)[org.openhab.binding.senechome.internal.SenecHomeHandlerFactory(311)] : dm $000 tracking 1 SingleStatic added {org.openhab.core.io.net.http.HttpClientFactory, org.openhab.core.io.net.http.WebSocketFactory}={service.id=268, service.bundleid=177, service.scope=bundle, component.name=org.openhab.core.io.net.http.internal.WebClientFactoryImpl, component.id=133} (enter)
2022-01-05 18:19:25.854 [DEBUG] [ome.internal.SenecHomeHandlerFactory] - bundle org.openhab.binding.senechome:3.1.0 (268)[org.openhab.binding.senechome.internal.SenecHomeHandlerFactory(311)] : dm $000 tracking 1 SingleStatic active: false trackerOpened: false optional: false
2022-01-05 18:19:25.868 [DEBUG] [ome.internal.SenecHomeHandlerFactory] - bundle org.openhab.binding.senechome:3.1.0 (268)[org.openhab.binding.senechome.internal.SenecHomeHandlerFactory(311)] : dm $000 tracking 1 SingleStatic added {org.openhab.core.io.net.http.HttpClientFactory, org.openhab.core.io.net.http.WebSocketFactory}={service.id=268, service.bundleid=177, service.scope=bundle, component.name=org.openhab.core.io.net.http.internal.WebClientFactoryImpl, component.id=133} (exit)
2022-01-05 18:19:25.875 [DEBUG] [ome.internal.SenecHomeHandlerFactory] - bundle org.openhab.binding.senechome:3.1.0 (268)[org.openhab.binding.senechome.internal.SenecHomeHandlerFactory(311)] : dm $000 tracker opened
2022-01-05 18:19:25.883 [DEBUG] [ome.internal.SenecHomeHandlerFactory] - bundle org.openhab.binding.senechome:3.1.0 (268)[org.openhab.binding.senechome.internal.SenecHomeHandlerFactory(311)] : registering service listener for dependency $000
2022-01-05 18:19:25.884 [DEBUG] [ome.internal.SenecHomeHandlerFactory] - bundle org.openhab.binding.senechome:3.1.0 (268)[org.openhab.binding.senechome.internal.SenecHomeHandlerFactory(311)] : Changed state from disabled to unsatisfiedReference
2022-01-05 18:19:25.914 [DEBUG] [ome.internal.SenecHomeHandlerFactory] - bundle org.openhab.binding.senechome:3.1.0 (268)[org.openhab.binding.senechome.internal.SenecHomeHandlerFactory(311)] : Component enabled
2022-01-05 18:19:25.916 [DEBUG] [ome.internal.SenecHomeHandlerFactory] - bundle org.openhab.binding.senechome:3.1.0 (268)[org.openhab.binding.senechome.internal.SenecHomeHandlerFactory(311)] : ActivateInternal
2022-01-05 18:19:25.932 [DEBUG] [ome.internal.SenecHomeHandlerFactory] - bundle org.openhab.binding.senechome:3.1.0 (268)[org.openhab.binding.senechome.internal.SenecHomeHandlerFactory(311)] : Querying state unsatisfiedReference
2022-01-05 18:19:25.933 [DEBUG] [ome.internal.SenecHomeHandlerFactory] - bundle org.openhab.binding.senechome:3.1.0 (268)[org.openhab.binding.senechome.internal.SenecHomeHandlerFactory(311)] : Querying state unsatisfiedReference
2022-01-05 18:19:25.934 [DEBUG] [ome.internal.SenecHomeHandlerFactory] - bundle org.openhab.binding.senechome:3.1.0 (268)[org.openhab.binding.senechome.internal.SenecHomeHandlerFactory(311)] : Activating component from state unsatisfiedReference
2022-01-05 18:19:25.935 [DEBUG] [ome.internal.SenecHomeHandlerFactory] - bundle org.openhab.binding.senechome:3.1.0 (268)[org.openhab.binding.senechome.internal.SenecHomeHandlerFactory(311)] : Querying state unsatisfiedReference
2022-01-05 18:19:25.936 [DEBUG] [ome.internal.SenecHomeHandlerFactory] - bundle org.openhab.binding.senechome:3.1.0 (268)[org.openhab.binding.senechome.internal.SenecHomeHandlerFactory(311)] : Querying state unsatisfiedReference
2022-01-05 18:19:25.938 [DEBUG] [ome.internal.SenecHomeHandlerFactory] - bundle org.openhab.binding.senechome:3.1.0 (268)[org.openhab.binding.senechome.internal.SenecHomeHandlerFactory(311)] : Changed state from unsatisfiedReference to satisfied
2022-01-05 18:19:25.939 [DEBUG] [ome.internal.SenecHomeHandlerFactory] - bundle org.openhab.binding.senechome:3.1.0 (268)[org.openhab.binding.senechome.internal.SenecHomeHandlerFactory(311)] : registration change queue [registered]
2022-01-05 18:19:25.942 [DEBUG] [ome.internal.SenecHomeHandlerFactory] - bundle org.openhab.binding.senechome:3.1.0 (268)[org.openhab.binding.senechome.internal.SenecHomeHandlerFactory(311)] : Checking constructor public org.openhab.binding.senechome.internal.SenecHomeHandlerFactory(org.openhab.core.io.net.http.HttpClientFactory)
2022-01-05 18:19:25.944 [DEBUG] [ome.internal.SenecHomeHandlerFactory] - bundle org.openhab.binding.senechome:3.1.0 (268)[org.openhab.binding.senechome.internal.SenecHomeHandlerFactory(311)] : getReferenceClass: Looking for interface class org.openhab.core.io.net.http.HttpClientFactory through loader of org.openhab.binding.senechome.internal.SenecHomeHandlerFactory
2022-01-05 18:19:25.945 [DEBUG] [ome.internal.SenecHomeHandlerFactory] - bundle org.openhab.binding.senechome:3.1.0 (268)[org.openhab.binding.senechome.internal.SenecHomeHandlerFactory(311)] : getParameterClass: Found class org.openhab.core.io.net.http.HttpClientFactory
2022-01-05 18:19:25.951 [DEBUG] [ome.internal.SenecHomeHandlerFactory] - bundle org.openhab.binding.senechome:3.1.0 (268)[org.openhab.binding.senechome.internal.SenecHomeHandlerFactory(311)] : Found constructor with 1 arguments : public org.openhab.binding.senechome.internal.SenecHomeHandlerFactory(org.openhab.core.io.net.http.HttpClientFactory)
2022-01-05 18:19:25.967 [DEBUG] [ome.internal.SenecHomeHandlerFactory] - bundle org.openhab.binding.senechome:3.1.0 (268)[org.openhab.binding.senechome.internal.SenecHomeHandlerFactory(311)] : This thread collected dependencies
2022-01-05 18:19:25.968 [DEBUG] [ome.internal.SenecHomeHandlerFactory] - bundle org.openhab.binding.senechome:3.1.0 (268)[org.openhab.binding.senechome.internal.SenecHomeHandlerFactory(311)] : getService (single component manager) dependencies collected.
2022-01-05 18:19:25.969 [DEBUG] [ome.internal.SenecHomeHandlerFactory] - bundle org.openhab.binding.senechome:3.1.0 (268)[org.openhab.binding.senechome.internal.SenecHomeHandlerFactory(311)] : Querying state satisfied
2022-01-05 18:19:25.970 [DEBUG] [ome.internal.SenecHomeHandlerFactory] - bundle org.openhab.binding.senechome:3.1.0 (268)[org.openhab.binding.senechome.internal.SenecHomeHandlerFactory(311)] : Querying state satisfied
2022-01-05 18:19:25.984 [DEBUG] [ome.internal.SenecHomeHandlerFactory] - bundle org.openhab.binding.senechome:3.1.0 (268)[org.openhab.binding.senechome.internal.SenecHomeHandlerFactory(311)] : For dependency $000, optional: false; to bind: [[RefPair: ref: [{org.openhab.core.io.net.http.HttpClientFactory, org.openhab.core.io.net.http.WebSocketFactory}={service.id=268, service.bundleid=177, service.scope=bundle, component.name=org.openhab.core.io.net.http.internal.WebClientFactoryImpl, component.id=133}] service: [null]]]
2022-01-05 18:19:26.009 [DEBUG] [ome.internal.SenecHomeHandlerFactory] - bundle org.openhab.binding.senechome:3.1.0 (268)[org.openhab.binding.senechome.internal.SenecHomeHandlerFactory(311)] : getting activate: activate
2022-01-05 18:19:26.010 [DEBUG] [ome.internal.SenecHomeHandlerFactory] - bundle org.openhab.binding.senechome:3.1.0 (268)[org.openhab.binding.senechome.internal.SenecHomeHandlerFactory(311)] : Locating method activate in class org.openhab.binding.senechome.internal.SenecHomeHandlerFactory
2022-01-05 18:19:26.012 [DEBUG] [ome.internal.SenecHomeHandlerFactory] - bundle org.openhab.binding.senechome:3.1.0 (268)[org.openhab.binding.senechome.internal.SenecHomeHandlerFactory(311)] : Declared Method org.openhab.binding.senechome.internal.SenecHomeHandlerFactory.activate([interface org.osgi.service.component.ComponentContext]) not found
2022-01-05 18:19:26.013 [DEBUG] [ome.internal.SenecHomeHandlerFactory] - bundle org.openhab.binding.senechome:3.1.0 (268)[org.openhab.binding.senechome.internal.SenecHomeHandlerFactory(311)] : Locating method activate in class org.openhab.core.thing.binding.BaseThingHandlerFactory
2022-01-05 18:19:26.015 [DEBUG] [ome.internal.SenecHomeHandlerFactory] - bundle org.openhab.binding.senechome:3.1.0 (268)[org.openhab.binding.senechome.internal.SenecHomeHandlerFactory(311)] : Found activate method: protected void org.openhab.core.thing.binding.BaseThingHandlerFactory.activate(org.osgi.service.component.ComponentContext)
2022-01-05 18:19:26.017 [DEBUG] [ome.internal.SenecHomeHandlerFactory] - bundle org.openhab.binding.senechome:3.1.0 (268)[org.openhab.binding.senechome.internal.SenecHomeHandlerFactory(311)] : invoking activate: activate: parameters [org.apache.felix.scr.impl.manager.ComponentContextImpl]
2022-01-05 18:19:26.024 [DEBUG] [ome.internal.SenecHomeHandlerFactory] - bundle org.openhab.binding.senechome:3.1.0 (268)[org.openhab.binding.senechome.internal.SenecHomeHandlerFactory(311)] : invoked activate: activate
2022-01-05 18:19:26.027 [DEBUG] [ome.internal.SenecHomeHandlerFactory] - bundle org.openhab.binding.senechome:3.1.0 (268)[org.openhab.binding.senechome.internal.SenecHomeHandlerFactory(311)] : Set implementation object for component
2022-01-05 18:19:26.030 [DEBUG] [ome.internal.SenecHomeHandlerFactory] - bundle org.openhab.binding.senechome:3.1.0 (268)[org.openhab.binding.senechome.internal.SenecHomeHandlerFactory(311)] : Changed state from satisfied to active
2022-01-05 18:19:26.350 [TRACE] [.senechome.internal.SenecHomeHandler] - received SenecHomeResponse [power=SenecHomePower [powerLimitation=u3_00000064, mppCur=null, mppPower=null, mppVol=null], energy=SenecHomeEnergy [housePowerConsumption=fl_4407999A, inverterPowerGeneration=fl_80000000, batteryPower=fl_00000000, batteryVoltage=fl_424A2000, batteryCurrent=fl_00000000, batteryFuelCharge=fl_42C80000, systemState=u8_1A], grid=SenecHomeGrid [currentGridValue=fl_4407999A, gridVoltagePerPhase= [Ljava.lang.String;@522d6ce0, currentGridCurrentPerPhase= [Ljava.lang.String;@1e471c28, currentGridPowerPerPhase= [Ljava.lang.String;@bc4415b, currentGridFrequency=fl_42480000], statistics=SenecHomeStatistics [liveBatCharge=fl_46002500, liveBatDischarge=fl_45AF8299, liveGridImport=fl_45EC0FF1, liveGridExport=fl_46BF62A7, liveHouseConsumption=fl_46C19844, livePowerGen=fl_471D2CCF, liveWallboxEnergy=[u6_0000000000000000, u6_0000000000000000, u6_0000000000000000, u6_0000000000000000]]batterySenecHomeBattery{chargedEnergy=null, dischargedEnergy=null, cycles=null, current=null, voltage=null, maxCellVoltage=null, minCellVoltage=null}temperatureSenecHomeTemperature{batteryTemperature='fl_418238F3', caseTemperature='fl_42700000', mcuTemperature='fl_4256C3B2'}wallboxSenecWallbox{l1ChargingCurrent=[fl_00000000, fl_00000000, fl_00000000, fl_00000000], l2ChargingCurrent=[fl_00000000, fl_00000000, fl_00000000, fl_00000000], l3ChargingCurrent=[fl_00000000, fl_00000000, fl_00000000, fl_00000000]}]
2022-01-05 18:19:26.383 [DEBUG] [.senechome.internal.SenecHomeHandler] - Updating power limitation state false
2022-01-05 18:19:26.452 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception: 
java.lang.NullPointerException: null
        at org.openhab.binding.senechome.internal.SenecHomeHandler.refreshState(SenecHomeHandler.java:214) ~[?:?]
        at org.openhab.core.cache.ExpiringCache.refreshValue(ExpiringCache.java:101) ~[?:?]
        at org.openhab.core.cache.ExpiringCache.getValue(ExpiringCache.java:72) ~[?:?]
        at org.openhab.binding.senechome.internal.SenecHomeHandler.refresh(SenecHomeHandler.java:133) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
        at java.util.concurrent.FutureTask.runAndReset(Unknown Source) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
```

**Comment by thopiekar** [comment]
![grafik](https://user-images.githubusercontent.com/1847437/148262586-2ef626c2-2be6-4580-8d6c-a4f66d2d67c2.png)

**Comment by eguib** [comment]
Seems the Home PB does not provide battery details (at least not with the same tag). I should be able to catch the NPE.  Will try to post an updated senechome binding in the next days. 
Just out of curiosity and to see what data the Home Pb is providing. Can you please do the following:
- open the developer tools in your browser for a new tab 
- navigate to http://<IP_OF_YOUR_SENEC>/vars.html
- export the whole network communication from the developer tool
- post the output
Will take a look and compare with my device (Home V3 hybrid)

**Comment by thopiekar** [comment]
Thanks! I lost the issue report from my eyes for some days. Sorry about that!

@eguib I made an export using Firefox and zipped it so I can upload it.
You should be able to load it into Firefox easily again.

![image](https://user-images.githubusercontent.com/1847437/149661954-d8068832-ab72-446d-ab99-9bcf3278c66f.png)


[senecies.fritz.box_Archive [22-01-16 14-25-33].har.zip](https://github.com/openhab/openhab-addons/files/7877022/senecies.fritz.box_Archive.22-01-16.14-25-33.har.zip)

**Comment by thopiekar** [comment]
Any chance to get back to this?

**Comment by thopiekar** [comment]
Opened a PR where I'm trying to fix it myself. No idea, whether it works or not due to an error in my OpenHAB installation (see PR)

**Comment by eguib** [comment]
I posted this as a comment to one of the pull requests some days ago ... might not have been seen.

_From the network communication you posted it looks like the whole section for "battery" is missing, so chances are high that your fix is correct.
Locally on my code branch I added a couple o
f "if" around each array inside battery, but there is no proof that there are cases where part of the data is available ...
On top of that I improved the toString method for some of the response objects, see the attached patch file._
[[senechome]_(#11606)_fixed_NPE,_enhanced_toString.zip](https://github.com/openhab/openhab-addons/files/8349282/senechome._.11606._fixed_NPE._enhanced_toString.zip)

**Comment by thopiekar** [comment]
Thanks! But on the other hand. If there is no proof that there are cases with partly data, why checking for it?
I mean the add-on works perfectly fine with my changes at the moment, so why worrying too much?
If it happens that other products have partly data, e.g. if they have two cells instead of four, then we can fix it on demand.
So far it doesn't hurt anyone :wink:

**Comment by KorbinianP** [comment]
> [[senechome]_(#11606)_fixed_NPE,_enhanced_toString.zip](https://github.com/openhab/openhab-addons/files/8349282/senechome._.11606._fixed_NPE._enhanced_toString.zip)

Hey, I do like this code more than the one in PR #12512 . There the Code is only checking `if (response.battery.chargedEnergy != null)` and then reading all the other values. But I can't say if `chargedEnergy` is a good indication that all other values like `response.battery.dischargedEnergy` or `response.battery.cycles` are there or not. So I do prefer eguib's solution.

**Comment by thopiekar** [comment]
Alright. @eguib would you like to create a PR then? :wink:

**Comment by eguib** [comment]
Hey @thopiekar: would appreciate if you do the PR, I'm still at work and it does not get better ...
And even if our "if" solutions are equivalent at the moment the toString improvements I added will help us understand the next problem better ;-)
And at least for the V2/V3 there is a lot ongoing on the "vars" due to the battery problems ... (one might have heard about it).
