### ISSUE TITLE
[sleepiq] ClassNotFoundException when communicating with CloudIQ service

### ISSUE THREAD

**Issue by mhilbush** [openhab/openhab-addons#11696]
I'm seeing this error when the binding attempts to authenticate with the CloudIQ service. It's failing on the `ClientBuilder` class.

Looks like a similar problem to the one @J-N-K fixed in the hdpowerview and neeo bindings.
https://github.com/openhab/openhab-addons/pull/9224
https://github.com/openhab/openhab-addons/pull/9006

```
2021-12-04 07:01:58.850 [DEBUG] [eepiq.internal.SleepIQHandlerFactory] - Creating SleepIQ cloud thing handler
2021-12-04 07:01:58.851 [DEBUG] [eepiq.internal.SleepIQHandlerFactory] - Registering bed discovery service
2021-12-04 07:01:58.865 [DEBUG] [internal.handler.SleepIQCloudHandler] - Configuring bed status cache
2021-12-04 07:01:58.866 [DEBUG] [internal.handler.SleepIQCloudHandler] - Reading SleepIQ cloud binding configuration
2021-12-04 07:01:58.867 [DEBUG] [internal.handler.SleepIQCloudHandler] - Creating SleepIQ client
2021-12-04 07:01:58.868 [DEBUG] [internal.handler.SleepIQCloudHandler] - Authenticating at the SleepIQ cloud service
2021-12-04 07:01:58.869 [DEBUG] [internal.handler.SleepIQCloudHandler] - Unexpected error while communicating with SleepIQ cloud
java.lang.RuntimeException: java.lang.ClassNotFoundException
	at javax.ws.rs.client.ClientBuilder.newBuilder(ClientBuilder.java:50) ~[bundleFile:?]
	at org.openhab.binding.sleepiq.api.impl.SleepIQImpl.createClient(SleepIQImpl.java:233) ~[bundleFile:?]
	at org.openhab.binding.sleepiq.api.impl.AbstractClient.getClient(AbstractClient.java:35) ~[bundleFile:?]
	at org.openhab.binding.sleepiq.api.impl.SleepIQImpl.login(SleepIQImpl.java:76) ~[bundleFile:?]
	at org.openhab.binding.sleepiq.internal.handler.SleepIQCloudHandler.createCloudConnection(SleepIQCloudHandler.java:115) ~[bundleFile:?]
	at org.openhab.binding.sleepiq.internal.handler.SleepIQCloudHandler.initialize(SleepIQCloudHandler.java:81) [bundleFile:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.openhab.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:154) [bundleFile:?]
	at org.openhab.core.internal.common.Invocation.call(Invocation.java:52) [bundleFile:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.ClassNotFoundException
	at javax.ws.rs.client.ClientFinder.newInstance(ClientFinder.java:120) ~[bundleFile:?]
	at javax.ws.rs.client.ClientFinder.find(ClientFinder.java:96) ~[bundleFile:?]
	at javax.ws.rs.client.ClientBuilder.newBuilder(ClientBuilder.java:44) ~[bundleFile:?]
	... 15 more
Caused by: java.lang.InstantiationException
	at jdk.internal.reflect.InstantiationExceptionConstructorAccessorImpl.newInstance(InstantiationExceptionConstructorAccessorImpl.java:48) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at java.lang.Class.newInstance(Class.java:584) ~[?:?]
	at javax.ws.rs.client.ClientFinder.newInstance(ClientFinder.java:116) ~[bundleFile:?]
	at javax.ws.rs.client.ClientFinder.find(ClientFinder.java:96) ~[bundleFile:?]
	at javax.ws.rs.client.ClientBuilder.newBuilder(ClientBuilder.java:44) ~[bundleFile:?]
	... 15 more
```

**Comment by mhilbush** [comment]
I'd have a go at fixing this, but I don't know how to tweak Eclipse so that it can deal with his 3rdparty API source code here.
https://github.com/openhab/openhab-addons/tree/main/bundles/org.openhab.binding.sleepiq/src/3rdparty

In Eclipse, all those API classes show as unresolved in the binding classes (such as `SleepIQCloudHandler.java`). And, as soon as I use Eclipse to edit a source file that references any of those API classes, the binding no longer builds in Maven.

@cweitkamp or @wborn Do you know what I need to do?

**Comment by wborn** [comment]
If you use the openHAB Eclipse config they should be automatically added to the build path when importing such projects based on the build-helper-maven-plugin config in the POM. In Eclipse you need to have the buildhelper m2e plugin installed for that which was added in: https://github.com/openhab/openhab-distro/pull/1259

You can also add the folders manually to the "Java Build Path" by editing the project properties: 

![Screenshot from 2021-12-04 14-55-40](https://user-images.githubusercontent.com/12213581/144712127-365f72fb-06ba-422c-a9d5-27d770a9bcf3.png)

That results in a `.classpath` file like this:

```
<?xml version="1.0" encoding="UTF-8"?>
<classpath>
	<classpathentry kind="src" output="target/classes" path="src/main/java">
		<attributes>
			<attribute name="optional" value="true"/>
			<attribute name="maven.pomderived" value="true"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="src" output="target/classes" path="src/3rdparty/java">
		<attributes>
			<attribute name="optional" value="true"/>
			<attribute name="maven.pomderived" value="true"/>
		</attributes>
	</classpathentry>
	<classpathentry excluding="**" kind="src" output="target/classes" path="src/main/resources">
		<attributes>
			<attribute name="maven.pomderived" value="true"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="src" output="target/test-classes" path="src/test/java">
		<attributes>
			<attribute name="optional" value="true"/>
			<attribute name="maven.pomderived" value="true"/>
			<attribute name="test" value="true"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="src" output="target/test-classes" path="src/3rdparty/test">
		<attributes>
			<attribute name="optional" value="true"/>
			<attribute name="maven.pomderived" value="true"/>
			<attribute name="test" value="true"/>
		</attributes>
	</classpathentry>
	<classpathentry excluding="**" kind="src" output="target/test-classes" path="src/test/resources">
		<attributes>
			<attribute name="maven.pomderived" value="true"/>
			<attribute name="test" value="true"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-11">
		<attributes>
			<attribute name="maven.pomderived" value="true"/>
			<attribute name="annotationpath" value="target/dependency"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="con" path="org.eclipse.m2e.MAVEN2_CLASSPATH_CONTAINER">
		<attributes>
			<attribute name="maven.pomderived" value="true"/>
			<attribute name="annotationpath" value="target/dependency"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="output" path="target/classes"/>
</classpath>
```

**Comment by mhilbush** [comment]
Thanks @wborn!

My Eclipse install is pretty old (about a year, I think), so I suspect I don't have that plug-in. I'll see if I can install that plugin.

**Comment by mhilbush** [comment]
I got the plug-in installed. But, I still ended up having to hand-edit the classpath. Thanks for posting that - worked perfectly!

**Comment by wborn** [comment]
Most likely you also need to remove plugin from being ignored in the Maven plugin lifecycle execution.

You can edit that using:

Preferences -> Maven -> Lifecycle Mapping -> Open workspace lifecycle mappings metadata

Then remove the [`<pluginExecution>` section like in the PR](https://github.com/openhab/openhab-distro/pull/1259/files#diff-d58e2a68963befc558e5a2dfd9075579df412797e94fb50e4eafdbe859c48beeL2394-L2407) and save the file.

**Comment by mhilbush** [comment]
Good catch. Thank you, Sir!
