### ISSUE TITLE
[jsscripting] Globals cannot be injected automatically on Windows

### ISSUE THREAD

**Issue by ghys** [openhab/openhab-addons#11801]
The JSScripting add-on doesn't seem to load the global variables (the default behavior) for UI-created rules on Windows.
Note that this seems to happen _even_ when the _Use Built-in Global Variables_ option in Settings > Other Services > JS Scripting is set to _Do Not Use Built-in Variables_.

On the same snapshot on Linux, it seems to work.

## Expected Behavior
The global variables should be loaded with no exception.

## Current Behavior
This exception appears in the logs on the first execution of a script, regardless of the option above:
```
[ERROR] [g.internal.OpenhabGraalJSScriptEngine] - Could not inject global script
javax.script.ScriptException: org.graalvm.polyglot.PolyglotException: TypeError: Cannot load CommonJS module: '@jsscripting-globals'
        at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.toScriptException(GraalJSScriptEngine.java:483) ~[?:?]
        at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.eval(GraalJSScriptEngine.java:460) ~[?:?]
        at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.eval(GraalJSScriptEngine.java:426) ~[?:?]
        at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264) ~[java.scripting:?]
<snip>
Caused by: org.graalvm.polyglot.PolyglotException: TypeError: Cannot load CommonJS module: '@jsscripting-globals'
        at com.oracle.truffle.polyglot.PolyglotMapAndFunction.apply(PolyglotMapAndFunction.java:46) ~[?:?]
        at org.openhab.automation.jsscripting.internal.OpenhabGraalJSScriptEngine.lambda$3(OpenhabGraalJSScriptEngine.java:178) ~[?:?]
        at java.util.Optional.orElseGet(Optional.java:369) ~[?:?]
        at org.openhab.automation.jsscripting.internal.OpenhabGraalJSScriptEngine.lambda$1(OpenhabGraalJSScriptEngine.java:178) ~[?:?]
        at <js>.:program(<eval>:1) ~[?:?]
        at org.graalvm.polyglot.Context.eval(Context.java:379) ~[?:?]
        at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.eval(GraalJSScriptEngine.java:458) ~[?:?]
        ... 71 more
```

## Possible Solution
A workaround is to add explitely:
```js
var runtime = require('@runtime');
```
to all scripts and use that, this works, but the exception is ugly and cannot be avoided.

## Steps to Reproduce (for Bugs)
1. Install the JSScripting add-on
2. Create a ECMAScript 2021 script in the UI (Settings > Scripts) or a rule with a script action set to ECMAScript 2021.
3. Run it

This might be because of path separators, for example here:
https://github.com/openhab/openhab-addons/blob/a6cb90f9e5fbdb22e6f1900c7316c0f106eb7811/bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/OpenhabGraalJSScriptEngine.java#L68

## Context
The JSScripting add-on which is a big feature of openHAB 3.2 doesn't work well in the simplest scenario on Windows (e.g. for testing purposes).

## Your Environment

On Windows, Zulu 11, fresh openHAB 3.2.0-SNAPSHOT - Build 2632,

**Comment by digitaldan** [comment]
oof, i'll get a fix in asap for that
