### ISSUE TITLE
[nanoleaf] OpenAPI warning in logs

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-addons#11869]
I am currently seeing this in my logs:

```
18:10:42.764 [WARN ] [inding.nanoleaf.internal.OpenAPIUtils] - OpenAPI request failed with timeout
java.util.concurrent.TimeoutException: Total timeout 10000 ms elapsed
        at org.eclipse.jetty.client.HttpDestination$RequestTimeouts.onExpired(HttpDestination.java:567) ~[?:?]
        at org.eclipse.jetty.client.HttpDestination$RequestTimeouts.onExpired(HttpDestination.java:550) ~[?:?]
        at org.eclipse.jetty.io.CyclicTimeouts.onTimeoutExpired(CyclicTimeouts.java:110) ~[?:?]
        at org.eclipse.jetty.io.CyclicTimeouts.access$100(CyclicTimeouts.java:50) ~[?:?]
        at org.eclipse.jetty.io.CyclicTimeouts$Timeouts.onTimeoutExpired(CyclicTimeouts.java:196) ~[?:?]
        at org.eclipse.jetty.io.CyclicTimeout$Wakeup.run(CyclicTimeout.java:298) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
```
The nanoleaf controller Thing is OFFLINE (although it is on the network and the nanoleaf app can access it.

## Expected Behavior

No warning and the Thing being ONLINE.
Even in case of a communication error, no such warnings should be logged, only the OFFLINE Thing status should indicate that there is a problem.

## Your Environment

* Version used: 3.2.0 Release version

**Comment by kaikreuzer** [comment]
@stefan-hoehn Any idea what might cause this?

**Comment by kaikreuzer** [comment]
This issue occurred after I did a firmware update of my Nanoleaf controller, which in turn caused my router to assign a new IP address. It is thus correct that the Thing is OFFLINE, but the warning must not be logged in such a case.
