### ISSUE TITLE
Firmware upgrade the Bitronvideo BV 2010/10 ZigBee USB dongle

### ISSUE THREAD

**Issue by jogethome** [openhab/openhab-addons#11879]
I'm experiencing similar issues like  
https://community.openhab.org/t/firmware-upgrade-the-bitronvideo-bv-2010-10-zigbee-usb-dongle/128879

After successful upgrading the firmware of the stick to 6.7.8 those things which were already bound before
were discovered after a while. 
It was unpossible to add new things. Having the stick running on 115200baud the stick switched back to 57600baud during scan.
Afterwards it got in unresponsive error state. Switching it back to 115200baud brings it back online.
This was the case for stable version. 
Afterwards I switched to Test / Snapshot versions in the hope getting rid of this. Unfortunately the discovered things are now in state "gone" and the scan has the same behaviour as above.
I tried now the last two snapshots.
What I also unsuccessfully tried is putting the baudrate fix into a things definition file.

In the log file of openhab I get a Java stack trace like 
2021-12-28 21:57:55.792 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception:
java.lang.NullPointerException: null
        at org.openhab.binding.zigbee.ember.handler.EmberHandler.setGroupRegistration(EmberHandler.java:365) ~[?:?]
        at org.openhab.binding.zigbee.ember.handler.EmberHandler.initializeDongleSpecific(EmberHandler.java:120) ~[?:?]
        at org.openhab.binding.zigbee.handler.ZigBeeCoordinatorHandler.initialiseZigBee(ZigBeeCoordinatorHandler.java:551) ~[?:?]
        at org.openhab.binding.zigbee.handler.ZigBeeCoordinatorHandler.lambda$2(ZigBeeCoordinatorHandler.java:559) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]

Thanks & Regards
Georg

## Steps to Reproduce (for Bugs)

1.
2.

## Your Environment

* Version used: (e.g., openHAB and add-on versions)
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...):
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...):

**Comment by wborn** [comment]
Perhaps @kaikreuzer can transfer this issue to the zigbee repo?
