### ISSUE TITLE
[InfluxDB] Crashing influxDB 2.1 with a simpel rule: previousState

### ISSUE THREAD

**Issue by FutureCow** [openhab/openhab-addons#11878]
## Expected Behavior
Getting the prevousState from an item with a simple DSL rule.

## Current Behavior
To make to problem as easy a possible i create a simple DSL rule:

```
configuration: {}
triggers:
  - id: "1"
    configuration:
      itemName: Schakel_Server_Power
    type: core.ItemStateChangeTrigger
conditions: []
actions:
  - inputs: {}
    id: "2"
    configuration:
      type: application/vnd.openhab.dsl.rule
      script: 'logInfo("Test", "recorded: " + Schakel_Server_Power.previousState(false,"influxdb").toString)'
    type: script.ScriptAction
```
This rules make my InfluxDB 2.1.1 crash! (do I need some more InfluxDB debug? how?)
```
Dec 22 22:57:44 server systemd[1]: influxdb.service: A process of this unit has been killed by the OOM killer.
Dec 22 22:57:44 server systemd[1]: influxdb.service: Main process exited, code=killed, status=9/KILL
Dec 22 22:57:44 server systemd[1]: influxdb.service: Failed with result 'oom-kill'.
Dec 22 22:57:44 server systemd[1]: influxdb.service: Consumed 58.711s CPU time.
Dec 22 22:57:46 server systemd[1]: influxdb.service: Scheduled restart job, restart counter is at 43.
Dec 22 22:57:46 server systemd[1]: Stopped InfluxDB is an open-source, distributed, time series database.
Dec 22 22:57:46 server systemd[1]: influxdb.service: Consumed 58.711s CPU time.
Dec 22 22:57:46 server systemd[1]: Starting InfluxDB is an open-source, distributed, time series database...
```
This a the error inside OH3.2:

```
Caused by: java.net.ConnectException: Failed to connect to /192.168.1.2:8086
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:265) ~[?:?]
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:183) ~[?:?]
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224) ~[?:?]
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108) ~[?:?]
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88) ~[?:?]
        at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169) ~[?:?]
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41) ~[?:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[?:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[?:?]
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94) ~[?:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[?:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[?:?]
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) ~[?:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[?:?]
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88) ~[?:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[?:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[?:?]
        at com.influxdb.client.internal.GzipInterceptor.intercept(GzipInterceptor.java:91) ~[?:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[?:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[?:?]
        at com.influxdb.client.internal.AuthenticateInterceptor.intercept(AuthenticateInterceptor.java:96) ~[?:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[?:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[?:?]
        at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:152) ~[?:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[?:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[?:?]
        at com.influxdb.internal.UserAgentInterceptor.intercept(UserAgentInterceptor.java:52) ~[?:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[?:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[?:?]
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229) ~[?:?]
        at okhttp3.RealCall.execute(RealCall.java:81) ~[?:?]
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:188) ~[?:?]
        at io.reactivex.internal.operators.maybe.MaybeMap$MapMaybeObserver.onSuccess(MaybeMap.java:82) ~[?:?]
        at io.reactivex.internal.operators.maybe.MaybeFromCallable.subscribeActual(MaybeFromCallable.java:61) ~[?:?]
        at io.reactivex.Maybe.subscribe(Maybe.java:4290) ~[?:?]
        at io.reactivex.internal.operators.maybe.MaybeMap.subscribeActual(MaybeMap.java:40) ~[?:?]
        at io.reactivex.Maybe.subscribe(Maybe.java:4290) ~[?:?]
        at io.reactivex.internal.operators.maybe.MaybeMap.subscribeActual(MaybeMap.java:40) ~[?:?]
        at io.reactivex.Maybe.subscribe(Maybe.java:4290) ~[?:?]
        at io.reactivex.internal.operators.maybe.MaybeToFlowable.subscribeActual(MaybeToFlowable.java:45) ~[?:?]
        at io.reactivex.Flowable.subscribe(Flowable.java:14935) ~[?:?]
        at io.reactivex.Flowable.subscribe(Flowable.java:14882) ~[?:?]
        at io.reactivex.internal.operators.flowable.FlowableRepeatWhen$WhenReceiver.onNext(FlowableRepeatWhen.java:100) ~[?:?]
        at io.reactivex.internal.operators.flowable.FlowableRetryWhen.subscribeActual(FlowableRetryWhen.java:62) ~[?:?]
        at io.reactivex.Flowable.subscribe(Flowable.java:14935) ~[?:?]
        at io.reactivex.internal.operators.flowable.FlowableSingleMaybe.subscribeActual(FlowableSingleMaybe.java:34) ~[?:?]
        at io.reactivex.Maybe.subscribe(Maybe.java:4290) ~[?:?]
        at io.reactivex.internal.operators.maybe.MaybeMap.subscribeActual(MaybeMap.java:40) ~[?:?]
        at io.reactivex.Maybe.subscribe(Maybe.java:4290) ~[?:?]
        at io.reactivex.internal.operators.maybe.MaybePeek.subscribeActual(MaybePeek.java:56) ~[?:?]
        at io.reactivex.Maybe.subscribe(Maybe.java:4290) ~[?:?]
        at io.reactivex.internal.operators.maybe.MaybeOnErrorNext.subscribeActual(MaybeOnErrorNext.java:46) ~[?:?]
        at io.reactivex.Maybe.subscribe(Maybe.java:4290) ~[?:?]
        at io.reactivex.internal.operators.mixed.FlowableConcatMapMaybe$ConcatMapMaybeSubscriber.drain(FlowableConcatMapMaybe.java:276) ~[?:?]
        ... 37 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:?]
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399) ~[?:?]
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242) ~[?:?]
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224) ~[?:?]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:?]
        at java.net.Socket.connect(Socket.java:609) ~[?:?]
        at okhttp3.internal.platform.Platform.connectSocket(Platform.java:130) ~[?:?]
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:263) ~[?:?]
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:183) ~[?:?]
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224) ~[?:?]
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108) ~[?:?]
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88) ~[?:?]
        at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169) ~[?:?]
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41) ~[?:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[?:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[?:?]
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94) ~[?:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[?:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[?:?]
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) ~[?:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[?:?]
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88) ~[?:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[?:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[?:?]
        at com.influxdb.client.internal.GzipInterceptor.intercept(GzipInterceptor.java:91) ~[?:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[?:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[?:?]
        at com.influxdb.client.internal.AuthenticateInterceptor.intercept(AuthenticateInterceptor.java:96) ~[?:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[?:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[?:?]
        at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:152) ~[?:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[?:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[?:?]
        at com.influxdb.internal.UserAgentInterceptor.intercept(UserAgentInterceptor.java:52) ~[?:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[?:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[?:?]
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229) ~[?:?]
        at okhttp3.RealCall.execute(RealCall.java:81) ~[?:?]
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:188) ~[?:?]
        at io.reactivex.internal.operators.maybe.MaybeMap$MapMaybeObserver.onSuccess(MaybeMap.java:82) ~[?:?]
        at io.reactivex.internal.operators.maybe.MaybeFromCallable.subscribeActual(MaybeFromCallable.java:61) ~[?:?]
        at io.reactivex.Maybe.subscribe(Maybe.java:4290) ~[?:?]
        at io.reactivex.internal.operators.maybe.MaybeMap.subscribeActual(MaybeMap.java:40) ~[?:?]
        at io.reactivex.Maybe.subscribe(Maybe.java:4290) ~[?:?]
        at io.reactivex.internal.operators.maybe.MaybeMap.subscribeActual(MaybeMap.java:40) ~[?:?]
        at io.reactivex.Maybe.subscribe(Maybe.java:4290) ~[?:?]
        at io.reactivex.internal.operators.maybe.MaybeToFlowable.subscribeActual(MaybeToFlowable.java:45) ~[?:?]
        at io.reactivex.Flowable.subscribe(Flowable.java:14935) ~[?:?]
        at io.reactivex.Flowable.subscribe(Flowable.java:14882) ~[?:?]
        at io.reactivex.internal.operators.flowable.FlowableRepeatWhen$WhenReceiver.onNext(FlowableRepeatWhen.java:100) ~[?:?]
        at io.reactivex.internal.operators.flowable.FlowableRetryWhen.subscribeActual(FlowableRetryWhen.java:62) ~[?:?]
        at io.reactivex.Flowable.subscribe(Flowable.java:14935) ~[?:?]
        at io.reactivex.internal.operators.flowable.FlowableSingleMaybe.subscribeActual(FlowableSingleMaybe.java:34) ~[?:?]
        at io.reactivex.Maybe.subscribe(Maybe.java:4290) ~[?:?]
        at io.reactivex.internal.operators.maybe.MaybeMap.subscribeActual(MaybeMap.java:40) ~[?:?]
        at io.reactivex.Maybe.subscribe(Maybe.java:4290) ~[?:?]
        at io.reactivex.internal.operators.maybe.MaybePeek.subscribeActual(MaybePeek.java:56) ~[?:?]
        at io.reactivex.Maybe.subscribe(Maybe.java:4290) ~[?:?]
        at io.reactivex.internal.operators.maybe.MaybeOnErrorNext.subscribeActual(MaybeOnErrorNext.java:46) ~[?:?]
        at io.reactivex.Maybe.subscribe(Maybe.java:4290) ~[?:?]
        at io.reactivex.internal.operators.mixed.FlowableConcatMapMaybe$ConcatMapMaybeSubscriber.drain(FlowableConcatMapMaybe.java:276) ~[?:?]
        ... 37 more
```

## Your Environment

The connection to my InfluxDB 2.1.1 is working good. All values are getting add all the time without errors.

Running OH 3.2 
Debian 11.0
InfluxDB 2.1.1

I migrated 2 months ago from InfluxDB 1.6 to InfluxDB 2.0 and migrated my old data from v1 to v2 using the automated "migration tool" from influxDB. This might be a problem?

**Comment by wborn** [comment]
Your OS is killing influxdb because it is running out of memory (OOM):

> Dec 22 22:57:44 server systemd[1]: influxdb.service: A process of this unit has been killed by the OOM killer.

Maybe the new version uses more memory or you have accumulated too much data causing memory issues?
If your hardware only has a couple of GB memory it may not be enough when using influxdb to store a lot of data.

**Comment by FutureCow** [comment]
I use InfluxDB a lot with grafana using quite some large data collections without any problem. I have 8GB of memory.
Also a simple previousState call shouldn't make InfluxDB crash I think?

**Comment by FutureCow** [comment]
I did a trace and seeing this inside the log: (range start i quite some time ago...)
```
14:11:19.345 [INFO ] [openhab.event.ItemStateChangedEvent  ] - Item 'Schakel_Server_Power' changed from 22 to 37
14:11:19.348 [TRACE] [e.influxdb.InfluxDBPersistenceService] - Storing item Schakel_Server_Power (Type=NumberItem, State=37, Label=Vermogen Server, Category=, Tags=[Point]) in InfluxDB point InfluxPoint{measurementName='Schakel_Server_Power', time=2021-12-29T13:11:19.348546Z, value=37, tags={item=Schakel_Server_Power}}
14:11:19.349 [TRACE] [e.influxdb.InfluxDBPersistenceService] - Storing item Schakel_Server_Power (Type=NumberItem, State=37, Label=Vermogen Server, Category=, Tags=[Point]) in InfluxDB point InfluxPoint{measurementName='Schakel_Server_Power', time=2021-12-29T13:11:19.349543Z, value=37, tags={item=Schakel_Server_Power}}
14:11:19.368 [DEBUG] [e.influxdb.InfluxDBPersistenceService] - Got a query for historic points!
14:11:19.368 [TRACE] [e.influxdb.InfluxDBPersistenceService] - Filter: itemname: Schakel_Server_Power, ordering: DESCENDING, state: null,  operator: EQ, getBeginDate: null, getEndDate: null, getPageSize: 1, getPageNumber: 0
14:11:19.369 [TRACE] [e.influxdb.InfluxDBPersistenceService] - Query from(bucket:"openhab/autogen")
        |> range(start:-100y)
        |> filter(fn: (r) => r["_measurement"] == "Schakel_Server_Power")
        |> keep(columns:["_measurement", "_time", "_value"])
        |> sort(desc:true, columns:["_time"])
        |> limit(n:1, offset:0)

```

**Comment by Rossko57** [comment]
The logical next step is to identify what query or queries OH persistence layer sends to influxdb, then look into why that query breaks influx.

**Comment by FutureCow** [comment]
> |> range(start:-100y)
>         |> filter(fn: (r) => r["_measurement"] == "Schakel_Server_Power")
>         |> keep(columns:["_measurement", "_time", "_value"])
>         |> sort(desc:true, columns:["_time"])
>         |> limit(n:1, offset:0)

If i query this by hand, it takes 14,8s 
because Schakel_Server_Power is changing every 5 seconds, we get the OOM.
So the query need something simple to only see the preiviousState.

**Comment by Rossko57** [comment]
> If i query this by hand, it takes 14,8s

That seems ... disappointing.

> because Schakel_Server_Power is changing every 5 seconds, we get the OOM.

Hmm, if the rule took 15s to complete, the rule triggers should queue up in an ever-growing pile.  But only one query in progress ar a time.
I would expect problems - but revealed as openHAB rule queuing breaking.
I wouldn't expect influx to mind.

Maybe persistence service times out a query, leaving it still in progress, and bangs off the next one.

**Comment by lujop** [comment]
Hi @FutureCow 
Can you try to execute that query directly in InfluxDB:

```
Query from(bucket:"openhab/autogen")
        |> range(start:-100y)
        |> filter(fn: (r) => r["_measurement"] == "Schakel_Server_Power")
        |> keep(columns:["_measurement", "_time", "_value"])
        |> last()
```

And check if the time is nearly instantaneous?

**Comment by FutureCow** [comment]
> Hi @FutureCow Can you try to execute that query directly in InfluxDB:
> 
> ```
> Query from(bucket:"openhab/autogen")
>         |> range(start:-100y)
>         |> filter(fn: (r) => r["_measurement"] == "Schakel_Server_Power")
>         |> keep(columns:["_measurement", "_time", "_value"])
>         |> last()
> ```
> 
> And check if the time is nearly instantaneous?

This query takes around 0,48s to complete

**Comment by lujop** [comment]
The problem here is that OpenHab persistence API translates previousState to sorting by time descending and limit results to 1.
And that it's something that relational database optimize correctly but doesn't fit well with flux.
By now you can use that other addon I developed that allows you to do a native InfluxDB query: https://www.openhab.org/addons/bindings/dbquery/

And possibly an optimization here will be to translate a filter with limit 1 and sort desc to just | last() because measurements are always sorted by time ascending.

**Comment by lujop** [comment]
@FutureCow can you test the fix I done #11993 
In the PR there I've attached a version with the fix.

**Comment by FutureCow** [comment]
I will try this tommorow, thanks for the quick fix.
Quick question, is the last() not outputting the last State and not the previousState?
If Schakel_Power_Server is changing from 15 to 21, i want the previousState, so 15.

**Comment by lujop** [comment]
I think that the current is just not saved when the query is used. If not the previous query should fail too.

**Comment by Rossko57** [comment]
I thought `previousState()` was supposed to return the **latest** record.  (It has no idea when you are creating records i.e. everyMinute, everyChange, on demand, etc.)

And `previousState(true)` to return the latest record that is different from Item existing state - which sometimes might also be the latest record.

**Comment by lujop** [comment]
The version with the `(true)'  won't be optimized as the implementation uses a page size of 1000 elements.
I think an issue to OpenHab core can be opened to change the implementation to use a FilterCriteria with a not equal operator with the current value. 

If you have a lot of data the problem is that current PersistenceExtensions implementations of some operations don't play well with InfluxDB in terms of efficiency.
In especial sort seems to be not lazy at all and something you don't want to do when a lot of data is involved.

**Comment by Rossko57** [comment]
Did you find out why the crash? i.e. is the persistence extension returning before the query completes, but did not (or can not) abandon and clear up the in-progress query.

**Comment by lujop** [comment]
@wborn commented above that the crash was due to influxdb server being killed by the kernel due to lack of memory

**Comment by Rossko57** [comment]
Sure.  Making the query more efficient just shifts the threshold at which the service will still crash.
I was interested in prevention - avoiding if the rule abandons a query but leaves it in progress while the rule may retriggered.  

Not many will get into this situation, though.
