### ISSUE TITLE
[miio] HEX deviceId value is not handled correctly by add-on v3.2.0

### ISSUE THREAD

**Issue by pezoli** [openhab/openhab-addons#12139]
I have just installed Openhab v3.2.0 on a Debian 10 container in Proxmox on x86 machine, using Java11. Everything works fine with the setup. 

I would like to port my V2.5.4 environment, started with my Yeelight bulbs, using Xiaomi Wifi devices (Mi IO) Binding. I have text based configuration, created my thing file with this line:
`Thing miio:basic:lamp [ host="192.168.xxx.yyy", token="12345678901234567890123456789", deviceId="0x00000000036d4243",  model="yeelink.light.color1", communication="direct" ]`

Once the thing file is saved, i see the following error in openhab.log:
`2022-01-27 19:08:13.278 [WARN ] [nal.transport.MiIoAsyncCommunication] - Error while polling/sending message for 0x00000000036d4243
java.nio.BufferOverflowException: null
	at java.nio.HeapByteBuffer.put(HeapByteBuffer.java:221) ~[?:?]
	at java.nio.ByteBuffer.put(ByteBuffer.java:914) ~[?:?]
	at org.openhab.binding.miio.internal.Message.createMsgData(Message.java:70) ~[bundleFile:?]
	at org.openhab.binding.miio.internal.transport.MiIoAsyncCommunication.sendCommand(MiIoAsyncCommunication.java:308) ~[bundleFile:?]
	at org.openhab.binding.miio.internal.transport.MiIoAsyncCommunication.sendMiIoSendCommand(MiIoAsyncCommunication.java:176) ~[bundleFile:?]
	at org.openhab.binding.miio.internal.transport.MiIoAsyncCommunication$MessageSenderThread.run(MiIoAsyncCommunication.java:278) [bundleFile:?]`

In spite of the error, the thing is shown online with green colour on Openhab admin webpage, but if i link any channel to an item, it wont work (of course, looking at the log).

This thing definition was working perfectly on my OpenHAB v2.5.4 installation using same binding version 2.5.4.

If i change deviceId to "57492035", which is the decimal value of 0x00000000036d4243, i see no more error in the log (thing status is still online on admin page) and the thing is working perfectly.

## Possible Solution
Hex conversion to decimal should be checked in the code.

**Comment by pezoli** [comment]
Thank you for the explanation Marcus! I thought it would be helpful to keep the hex to dec  conversion function from the 2.5.4 binding, to help those migrating to 3.2, but if it was not a designed feature, just worked by chance, probably it doesnt make sense to invest time into development now. Hope this will be found by people who have similar issue after migration.
