### ISSUE TITLE
[deutschebahn] DeutscheBahnTimetableHandlerTest unstable

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-addons#12235]
This unit test failed in https://github.com/openhab/openhab-addons/actions/runs/1805107390 :

```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.openhab.binding.deutschebahn.internal.DeutscheBahnTimetableHandlerTest
[ERROR] Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2.708 s <<< FAILURE! - in org.openhab.binding.deutschebahn.internal.DeutscheBahnTimetableHandlerTest
[ERROR] org.openhab.binding.deutschebahn.internal.DeutscheBahnTimetableHandlerTest.testUpdateTrainsToUndefinedIfNotEnoughDataWasProvided  Time elapsed: 2.056 s  <<< FAILURE!
org.mockito.exceptions.verification.WantedButNotInvoked: 

Wanted but not invoked:
thingHandlerCallback.stateUpdated(
    deutschebahn:train:train-2:arrival#line,
    UNDEF
);
-> at org.openhab.binding.deutschebahn.internal.DeutscheBahnTimetableHandlerTest.verifyChannelsUpdatedToUndef(DeutscheBahnTimetableHandlerTest.java:150)

However, there were exactly 4 interactions with this mock:
thingHandlerCallback.statusUpdated(
    Mock for Bridge, hashCode: 1414934182,
    UNKNOWN
);
-> at org.openhab.core.thing.binding.BaseThingHandler.updateStatus(BaseThingHandler.java:344)

thingHandlerCallback.statusUpdated(
    Mock for Bridge, hashCode: 1414934182,
    ONLINE
);
-> at org.openhab.core.thing.binding.BaseThingHandler.updateStatus(BaseThingHandler.java:344)

thingHandlerCallback.stateUpdated(
    deutschebahn:train:train-2:trip#category,
    UNDEF
);
-> at org.openhab.core.thing.binding.BaseThingHandler.updateState(BaseThingHandler.java:232)

thingHandlerCallback.stateUpdated(
    deutschebahn:train:train-2:arrival#planned-time,
    UNDEF
);
-> at org.openhab.core.thing.binding.BaseThingHandler.updateState(BaseThingHandler.java:232)


	at org.openhab.binding.deutschebahn.internal.DeutscheBahnTimetableHandlerTest.verifyChannelsUpdatedToUndef(DeutscheBahnTimetableHandlerTest.java:150)
	at org.openhab.binding.deutschebahn.internal.DeutscheBahnTimetableHandlerTest.testUpdateTrainsToUndefinedIfNotEnoughDataWasProvided(DeutscheBahnTimetableHandlerTest.java:180)

[INFO] Running org.openhab.binding.deutschebahn.internal.EventAttributeTest
[INFO] Tests run: 23, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.183 s - in org.openhab.binding.deutschebahn.internal.EventAttributeTest
[INFO] Running org.openhab.binding.deutschebahn.internal.DeutscheBahnTrainHandlerTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.094 s - in org.openhab.binding.deutschebahn.internal.DeutscheBahnTrainHandlerTest
[INFO] Running org.openhab.binding.deutschebahn.internal.filter.TimetableByStringEventAttributeFilterTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.015 s - in org.openhab.binding.deutschebahn.internal.filter.TimetableByStringEventAttributeFilterTest
[INFO] Running org.openhab.binding.deutschebahn.internal.filter.FilterScannerTest
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.024 s - in org.openhab.binding.deutschebahn.internal.filter.FilterScannerTest
[INFO] Running org.openhab.binding.deutschebahn.internal.filter.FilterParserTest
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.022 s - in org.openhab.binding.deutschebahn.internal.filter.FilterParserTest
[INFO] Running org.openhab.binding.deutschebahn.internal.timetable.TimetableLoaderTest
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.373 s - in org.openhab.binding.deutschebahn.internal.timetable.TimetableLoaderTest
[INFO] Running org.openhab.binding.deutschebahn.internal.timetable.TimetablesV1ImplTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.331 s - in org.openhab.binding.deutschebahn.internal.timetable.TimetablesV1ImplTest
[INFO] Running org.openhab.binding.deutschebahn.internal.TripLabelAttributeTest
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.026 s - in org.openhab.binding.deutschebahn.internal.TripLabelAttributeTest
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   DeutscheBahnTimetableHandlerTest.testUpdateTrainsToUndefinedIfNotEnoughDataWasProvided:180->verifyChannelsUpdatedToUndef:150 
Wanted but not invoked:
thingHandlerCallback.stateUpdated(
    deutschebahn:train:train-2:arrival#line,
    UNDEF
);
-> at org.openhab.binding.deutschebahn.internal.DeutscheBahnTimetableHandlerTest.verifyChannelsUpdatedToUndef(DeutscheBahnTimetableHandlerTest.java:150)

However, there were exactly 4 interactions with this mock:
thingHandlerCallback.statusUpdated(
    Mock for Bridge, hashCode: 1414934182,
    UNKNOWN
);
-> at org.openhab.core.thing.binding.BaseThingHandler.updateStatus(BaseThingHandler.java:344)

thingHandlerCallback.statusUpdated(
    Mock for Bridge, hashCode: 1414934182,
    ONLINE
);
-> at org.openhab.core.thing.binding.BaseThingHandler.updateStatus(BaseThingHandler.java:344)

thingHandlerCallback.stateUpdated(
    deutschebahn:train:train-2:trip#category,
    UNDEF
);
-> at org.openhab.core.thing.binding.BaseThingHandler.updateState(BaseThingHandler.java:232)

thingHandlerCallback.stateUpdated(
    deutschebahn:train:train-2:arrival#planned-time,
    UNDEF
);
-> at org.openhab.core.thing.binding.BaseThingHandler.updateState(BaseThingHandler.java:232)


[INFO] 
[ERROR] Tests run: 57, Failures: 1, Errors: 0, Skipped: 0

```

Can you have a look at it @soenkekueper?

**Comment by soenkekueper** [comment]
Hey,

of course i'll try to figure out what happend...

**Comment by wborn** [comment]
I think most tests just use `JavaTest.waitForAssert(..)` to wait for such assertions to be satisfied.

For testing you could also add a method to your handler so you can inject your own scheduler and use that in tests (when the field in which it is injected is not `null`) and use the `BaseThingHandler.scheduler` when it is `null`.

It would be nice if the core provided some helper class one day for testing that can put synchronous `ExecutorService`s  in `ThreadPoolManager.pools`.
