### ISSUE TITLE
[tado°] Keep status in Initializing

### ISSUE THREAD

**Issue by LorenzoBottaccioli** [openhab/openhab-addons#12253]
Hi I'm new to openHAB. I have just tried to add my tado° system to the openHAB platform. I'm running openHAB in windows 10 with the latest zulu.  I'm facing a problem with the connection, I got stuck with status `INITIALIZING`, I have double checked usr and psw of tado home. Infact if I put wrong psw or usr i get `COMMUNICATION_ERROR Could not connect to server due to Error calling https://auth.tado.com/oauth/token`

The Tado Binding is the 3.2.0.

**Comment by andrewfg** [comment]
Can you please post your Thing configuration?

**Comment by Dustinhoefer** [comment]
Same for me, new openhab installation, windows 10, created the binding and it keeps saying initializing. With the wrong username/password I also get the COMMUNICATION_ERROR. Binding version 3.3.0.M2

Stacktrace:

java.lang.NoSuchFieldException: override
        at java.base/java.lang.Class.getDeclaredField(Class.java:2610)
        at com.google.gson.internal.reflect.UnsafeReflectionAccessor.getOverrideField(UnsafeReflectionAccessor.java:58)
        at com.google.gson.internal.reflect.UnsafeReflectionAccessor.<init>(UnsafeReflectionAccessor.java:32)
        at com.google.gson.internal.reflect.ReflectionAccessor.<clinit>(ReflectionAccessor.java:36)
        at com.google.gson.internal.ConstructorConstructor.<init>(ConstructorConstructor.java:51)
        at com.google.gson.Gson.<init>(Gson.java:205)
        at com.google.gson.GsonBuilder.create(GsonBuilder.java:597)
        at org.openhab.binding.tado.internal.api.HomeApiFactory.create(HomeApiFactory.java:32)
        at org.openhab.binding.tado.internal.handler.TadoHomeHandler.initialize(TadoHomeHandler.java:73)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.openhab.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:154)
        at org.openhab.core.internal.common.Invocation.call(Invocation.java:52)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by andrewfg** [comment]
^
Can you please post your Thing configuration?

**Comment by Dustinhoefer** [comment]
I made the mistake of not specifying the correct java_home....
Working perfectly now, thanks!

**Comment by andrewfg** [comment]
@LorenzoBottaccioli can you please post your Thing configuration?

**Comment by andrewfg** [comment]
I am closing this since the OP has not responded.
