### ISSUE TITLE
[influxdb] Auto reconnect after losing connection not working

### ISSUE THREAD

**Issue by chris922** [openhab/openhab-addons#12340]
## Expected Behavior
If the connection to the influxdb server is lost the binding should retry connecting to the server after some time.

## Current Behavior
I could see in the log files that the connection to the infludb server is lost and no reconnect try is visible. I have to restart openhab to get back to a working state.

It will also do some retries, but after some time it seems to stop. Using e.g. exponential backoff should ensure that it always tries again without doing too many retries in a short time frame.

## Possible Solution
Do retry with exponential backoff when the connection to influxdb was lost.

Or add a configuration option for how long openhab should retry.

## Steps to Reproduce (for Bugs)
1. Use influxdb persistence
2. Stop influxdb server
3. Wait some time so that the binding tries to write to influxdb
4. Start influxdb server
5. Ensure that binding should try to write to influxdb

-> Nothing will be written to influxdb, even if server is again up and running

## Context
I've got several items that persist item changes in an influxdb. For some weeks I sometimes have issues with my influxdb server so that it is unavailable for openhab (at least I expect that this is the case). As soon as the influxdb server is running again openhab will not automatically heal itself and I have to restart openhab.

The following exceptions are visible in the logs (I shortened the stack traces, if you need the full please let me know):

```
2022-02-21 06:21:21.290 [ERROR] [.client.write.events.WriteErrorEvent] - The error occurred during writing of data
com.influxdb.exceptions.BadGatewayException: null
	at com.influxdb.internal.AbstractRestClient.responseToError(AbstractRestClient.java:122) ~[bundleFile:?]
	at com.influxdb.client.internal.AbstractWriteClient.toInfluxException(AbstractWriteClient.java:574) ~[bundleFile:?]
	at com.influxdb.client.internal.AbstractWriteClient.lambda$new$12(AbstractWriteClient.java:181) ~[bundleFile:?]
	at io.reactivex.internal.subscribers.LambdaSubscriber.onNext(LambdaSubscriber.java:65) [bundleFile:?]
[...]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

```
2022-02-21 06:18:39.968 [ERROR] [.client.write.events.WriteErrorEvent] - The error occurred during writing of data
com.influxdb.exceptions.InfluxException: interrupted
	at com.influxdb.client.internal.AbstractWriteClient.toInfluxException(AbstractWriteClient.java:577) ~[bundleFile:?]
	at com.influxdb.client.internal.AbstractWriteClient.lambda$new$12(AbstractWriteClient.java:181) ~[bundleFile:?]
	at io.reactivex.internal.subscribers.LambdaSubscriber.onNext(LambdaSubscriber.java:65) [bundleFile:?]
	at io.reactivex.internal.operators.flowable.FlowableDoFinally$DoFinallySubscriber.onNext(FlowableDoFinally.java:84) [bundleFile:?]
	at io.reactivex.internal.operators.mixed.FlowableConcatMapMaybe$ConcatMapMaybeSubscriber.drain(FlowableConcatMapMaybe.java:284) [bundleFile:?]
[...]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.io.InterruptedIOException: interrupted
	at okio.Timeout.throwIfReached(Timeout.java:146) ~[?:?]
	at okio.Okio$1.write(Okio.java:76) ~[?:?]
	at okio.AsyncTimeout$1.write(AsyncTimeout.java:180) ~[?:?]
	at okio.RealBufferedSink.flush(RealBufferedSink.java:224) ~[?:?]
	at okhttp3.internal.http2.Http2Writer.flush(Http2Writer.java:121) ~[?:?]
[...]
	at io.reactivex.internal.operators.maybe.MaybeOnErrorNext.subscribeActual(MaybeOnErrorNext.java:46) ~[?:?]
	at io.reactivex.Maybe.subscribe(Maybe.java:4290) ~[?:?]
	at io.reactivex.internal.operators.mixed.FlowableConcatMapMaybe$ConcatMapMaybeSubscriber.drain(FlowableConcatMapMaybe.java:276) ~[?:?]
	... 33 more
```

## Your Environment
* Version used: 3.2.0
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...):
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): openHABian 3.2.0 on Raspberry Pi

**Comment by J-N-K** [comment]
Fixed with #14304
