### ISSUE TITLE
[smartmeter] io.reactivex.exceptions.UndeliverableException

### ISSUE THREAD

**Issue by LotharRe** [openhab/openhab-addons#12488]
After some runtime, the smartmeter binding "crashed" somehow for one connected smartmeter.

## Expected Behavior
The smartmeter binding is delivering smart meter data.

## Current Behavior
After some days of system uptime, no more data is delivered from the binding.

Error message from the log:
```
2022-03-18 02:23:17.874 [ERROR] [ding.smartmeter.internal.MeterDevice] - Fatal error occured
io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.io.IOException: Timeout
	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367) [bundleFile:?]
	at io.reactivex.internal.operators.flowable.FlowableCreate$BaseEmitter.onError(FlowableCreate.java:275) [bundleFile:?]
	at io.reactivex.internal.operators.flowable.FlowableCreate.subscribeActual(FlowableCreate.java:74) [bundleFile:?]
	at io.reactivex.Flowable.subscribe(Flowable.java:14479) [bundleFile:?]
	at io.reactivex.Flowable.subscribe(Flowable.java:14426) [bundleFile:?]
	at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onNext(FlowableFlatMap.java:163) [bundleFile:?]
	at io.reactivex.internal.operators.flowable.FlowableTimer$TimerSubscriber.run(FlowableTimer.java:76) [bundleFile:?]
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38) [bundleFile:?]
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26) [bundleFile:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.io.IOException: Timeout
	at org.openmuc.jsml.transport.MessageExtractor.fillBufferWithTimeout(MessageExtractor.java:167) ~[?:?]
	at org.openmuc.jsml.transport.MessageExtractor.waitForStartSequence(MessageExtractor.java:49) ~[?:?]
	at org.openmuc.jsml.transport.MessageExtractor.getSmlMessage(MessageExtractor.java:41) ~[?:?]
	at org.openmuc.jsml.transport.Transport.getSMLFile(Transport.java:101) ~[?:?]
	at org.openhab.binding.smartmeter.internal.sml.SmlSerialConnector.readNext(SmlSerialConnector.java:95) ~[?:?]
	at org.openhab.binding.smartmeter.internal.sml.SmlSerialConnector.readNext(SmlSerialConnector.java:1) ~[?:?]
	at org.openhab.binding.smartmeter.connectors.ConnectorBase.emitValues(ConnectorBase.java:152) ~[?:?]
	at org.openhab.binding.smartmeter.connectors.ConnectorBase.lambda$2(ConnectorBase.java:123) ~[?:?]
	at io.reactivex.internal.operators.flowable.FlowableCreate.subscribeActual(FlowableCreate.java:71) ~[?:?]
	... 11 more
```

A temporary fix for the issue is only a reboot of the system (Raspberry Pi)

## Steps to Reproduce (for Bugs)
Waiting until the issue occurs (unfortunately..).

## Your Environment

* Version used: (e.g., openHAB and add-on versions)  openHAB 3.2.0 - Release Build
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...): smartmeter v3.2.0
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): Linux openhab 5.10.103-v7+; Raspberry Pi 3B+; Openhabian OS

**Comment by lsiepel** [comment]
Older issue, but still relevant. I created a PR to fix this. Would be nice if you can test the binding for a couple of days.
1. Upgrade to openHAB 4.2.0 (if not already using this)
2. Remove the smartemter binding from openHAB
3. Drop the jar from the PR into your addons folder

If you encounter any issue, please provide a debug log.

**Comment by LotharRe** [comment]
Plugin was installed flawlessly, even both smart meters were online without any reboot of the machine. I will now wait If any error occurs and provide feedback within the next two weeks (usually, I have at least one error per week that has to be fixed by rebooting).

**Comment by LotharRe** [comment]
After backup and reboot tonight, smart meters did not came back online. 
[openhab.log](https://github.com/user-attachments/files/16477938/openhab.log)
[events.log](https://github.com/user-attachments/files/16477943/events.log)

**Comment by lsiepel** [comment]
You restored a backup? I see many more issues not related to smart meter. Looks like old configuration settings (pre 4.0 or even 2,5)

regarding smart meter please check your configuration and can you post it here?

**Comment by LotharRe** [comment]
Sorry, I created a backup tonight.
Maybe an important additional fact: I am running 2 smart meter adaptors, the issue that they are not coming online is happening on both, sometimes on one of them.

Configuration:
`UID: smartmeter:meter:054b553303
label: Stromzähler Haus
thingTypeUID: smartmeter:meter
configuration:
  mode: SML
  refresh: 10
  baudrate: AUTO
  conformity: NONE
  port: /dev/ttyUSB_SM_House`

**Comment by lsiepel** [comment]
Did you manage to fix the startup issues?

**Comment by lsiepel** [comment]
There seems to be some configuration issues here. 
`unable to open port /dev/ttyUSB_SM_House`

As it worked before and the issues started when the backup was replaced, this does not seem to be related to the PR.
