### ISSUE TITLE
[JDBC] TimescaleDB not a valid JDBC entry

### ISSUE THREAD

**Issue by TBail** [openhab/openhab-addons#12513]
Playing around with persistence i found some stragne behavior regarding timestamp. Based on this i tested serveral scenarios. One Scenario is to use the jdbc postgresql persistens with the timescaledb extension.

with timescaledb extension a postgresql database could converted to a timeline orientated database like influx. The process to setup a timescaledb in postgresql is very simpel an straight forward. The benefit using tomescaledb is that normal tables are converted to hypertables but we can still use common sql to query the database. To enable this there are some step to perform

1.) Add the extension to an empty database

2.) for each table to be created convert it to a hypertable in the second step.

for jdbc the is an extension that extends the postgresql jdbc code with the conversion of the tables.

But and this is the bug. There is no option to activate this code extension. The documentation shows that the keyword timescaledb should be used to determin that it is an timescaldb, but this does not work.

```
2022-03-24 12:59:09.811 [WARN ] [ence.internal.PersistenceManagerImpl] - bundle org.openhab.core.persistence:3.3.0.202203240305 (208)[org.openhab.core.persistence.internal.PersistenceManagerImpl(63)] : Could not get service from ref {org.openhab.core.persistence.PersistenceService, org.openhab.core.persistence.QueryablePersistenceService}={service.id=510, service.bundleid=286, service.scope=bundle, enableLogTime=false, user=openhab, url=jdbc:timescaledb://idun.iot.thing.home:5432/openhab_db, component.name=org.openhab.persistence.jdbc.internal.JdbcPersistenceService, service.config.label=JDBC Persistence Service, component.id=324, service.config.factory=false, password=bycucumber, tableUseRealItemNames=true, rebuildTableNames=false, service.config.category=persistence, service.config.description.uri=persistence:jdbc, service.pid=[org.openhab.jdbc, org.openhab.jdbc]}
2022-03-24 12:59:09.819 [WARN ] [ence.internal.PersistenceManagerImpl] - bundle org.openhab.core.persistence:3.3.0.202203240305 (208)[org.openhab.core.persistence.internal.PersistenceManagerImpl(63)] : DependencyManager : invokeBindMethod : Service not available from service registry for ServiceReference {org.openhab.core.persistence.PersistenceService, org.openhab.core.persistence.QueryablePersistenceService}={service.id=510, service.bundleid=286, service.scope=bundle, enableLogTime=false, user=openhab, url=jdbc:timescaledb://idun.iot.thing.home:5432/openhab_db, component.name=org.openhab.persistence.jdbc.internal.JdbcPersistenceService, service.config.label=JDBC Persistence Service, component.id=324, service.config.factory=false, password=bycucumber, tableUseRealItemNames=true, rebuildTableNames=false, service.config.category=persistence, service.config.description.uri=persistence:jdbc, service.pid=[org.openhab.jdbc, org.openhab.jdbc]} for reference PersistenceService
2022-03-24 12:59:09.825 [INFO ] [persistence.jdbc.internal.JdbcMapper] - JDBC::openConnection: Driver is available::Yank setupDataSource
2022-03-24 12:59:09.832 [ERROR] [jdbc.internal.JdbcPersistenceService] - bundle org.openhab.persistence.jdbc:3.3.0.202203240413 (286)[org.openhab.persistence.jdbc.internal.JdbcPersistenceService(324)] : The activate method has thrown an exception
java.lang.RuntimeException: Driver org.postgresql.Driver claims to not accept jdbcUrl, jdbc:timescaledb://idun.iot.thing.home:5432/openhab_db
        at com.zaxxer.hikari.util.DriverDataSource.<init>(DriverDataSource.java:84) ~[?:?]
        at com.zaxxer.hikari.pool.PoolBase.initializeDataSource(PoolBase.java:298) ~[?:?]
        at com.zaxxer.hikari.pool.PoolBase.<init>(PoolBase.java:91) ~[?:?]
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:101) ~[?:?]
        at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:71) ~[?:?]
        at org.knowm.yank.YankPoolManager.createPool(YankPoolManager.java:101) ~[?:?]
        at org.knowm.yank.YankPoolManager.addDefaultConnectionPool(YankPoolManager.java:69) ~[?:?]
        at org.knowm.yank.Yank.setupDefaultConnectionPool(Yank.java:705) ~[?:?]
        at org.openhab.persistence.jdbc.internal.JdbcMapper.openConnection(JdbcMapper.java:215) ~[?:?]
        at org.openhab.persistence.jdbc.internal.JdbcMapper.pingDB(JdbcMapper.java:70) ~[?:?]
        at org.openhab.persistence.jdbc.internal.JdbcMapper.checkDBAccessability(JdbcMapper.java:248) ~[?:?]
        at org.openhab.persistence.jdbc.internal.JdbcPersistenceService.updateConfig(JdbcPersistenceService.java:231) ~[?:?]
        at org.openhab.persistence.jdbc.internal.JdbcPersistenceService.activate(JdbcPersistenceService.java:89) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.apache.felix.scr.impl.inject.methods.BaseMethod.invokeMethod(BaseMethod.java:244) ~[?:?]
        at org.apache.felix.scr.impl.inject.methods.BaseMethod.access$500(BaseMethod.java:41) ~[?:?]
        at org.apache.felix.scr.impl.inject.methods.BaseMethod$Resolved.invoke(BaseMethod.java:685) ~[?:?]
        at org.apache.felix.scr.impl.inject.methods.BaseMethod.invoke(BaseMethod.java:529) ~[?:?]
        at org.apache.felix.scr.impl.inject.methods.ActivateMethod.invoke(ActivateMethod.java:318) ~[?:?]
        at org.apache.felix.scr.impl.inject.methods.ActivateMethod.invoke(ActivateMethod.java:308) ~[?:?]
        at org.apache.felix.scr.impl.manager.SingleComponentManager.createImplementationObject(SingleComponentManager.java:354) ~[?:?]
        at org.apache.felix.scr.impl.manager.SingleComponentManager.createComponent(SingleComponentManager.java:115) ~[?:?]
        at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:1000) ~[?:?]
        at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:973) ~[?:?]
        at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:918) ~[?:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse$1.run(ServiceFactoryUse.java:216) ~[org.eclipse.osgi-3.16.300.jar:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.factoryGetService(ServiceFactoryUse.java:213) ~[org.eclipse.osgi-3.16.300.jar:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.getService(ServiceFactoryUse.java:114) ~[org.eclipse.osgi-3.16.300.jar:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceConsumer$2.getService(ServiceConsumer.java:48) ~[org.eclipse.osgi-3.16.300.jar:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.getService(ServiceRegistrationImpl.java:547) ~[org.eclipse.osgi-3.16.300.jar:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.getService(ServiceRegistry.java:533) ~[org.eclipse.osgi-3.16.300.jar:?]
        at org.eclipse.osgi.internal.framework.BundleContextImpl.getService(BundleContextImpl.java:656) ~[org.eclipse.osgi-3.16.300.jar:?]
        at org.apache.felix.scr.impl.manager.SingleRefPair.getServiceObject(SingleRefPair.java:88) ~[?:?]
        at org.apache.felix.scr.impl.inject.methods.BindMethod.getServiceObject(BindMethod.java:675) ~[?:?]
        at org.apache.felix.scr.impl.manager.DependencyManager.getServiceObject(DependencyManager.java:2556) ~[?:?]
        at org.apache.felix.scr.impl.manager.DependencyManager.doInvokeBindMethod(DependencyManager.java:2075) ~[?:?]
        at org.apache.felix.scr.impl.manager.DependencyManager.invokeBindMethod(DependencyManager.java:2058) ~[?:?]
        at org.apache.felix.scr.impl.manager.SingleComponentManager.invokeBindMethod(SingleComponentManager.java:443) ~[?:?]
        at org.apache.felix.scr.impl.manager.DependencyManager$MultipleDynamicCustomizer.addedService(DependencyManager.java:333) ~[?:?]
        at org.apache.felix.scr.impl.manager.DependencyManager$MultipleDynamicCustomizer.addedService(DependencyManager.java:301) ~[?:?]
        at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.customizerAdded(ServiceTracker.java:1200) ~[?:?]
        at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.customizerAdded(ServiceTracker.java:1121) ~[?:?]
        at org.apache.felix.scr.impl.manager.ServiceTracker$AbstractTracked.trackAdding(ServiceTracker.java:928) ~[?:?]
        at org.apache.felix.scr.impl.manager.ServiceTracker$AbstractTracked.track(ServiceTracker.java:864) ~[?:?]
        at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:1152) ~[?:?]
        at org.apache.felix.scr.impl.BundleComponentActivator$ListenerInfo.serviceChanged(BundleComponentActivator.java:114) ~[?:?]
        at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:120) ~[org.eclipse.osgi-3.16.300.jar:?]
        at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:957) ~[org.eclipse.osgi-3.16.300.jar:?]
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234) ~[org.eclipse.osgi-3.16.300.jar:?]
        at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151) ~[org.eclipse.osgi-3.16.300.jar:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:936) ~[org.eclipse.osgi-3.16.300.jar:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:873) ~[org.eclipse.osgi-3.16.300.jar:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:141) ~[org.eclipse.osgi-3.16.300.jar:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:261) ~[org.eclipse.osgi-3.16.300.jar:?]
        at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:496) ~[org.eclipse.osgi-3.16.300.jar:?]
        at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:929) ~[?:?]
        at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:915) ~[?:?]
        at org.apache.felix.scr.impl.manager.RegistrationManager.changeRegistration(RegistrationManager.java:133) ~[?:?]
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.registerService(AbstractComponentManager.java:984) ~[?:?]
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:752) ~[?:?]
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.enableInternal(AbstractComponentManager.java:674) ~[?:?]
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.enable(AbstractComponentManager.java:437) ~[?:?]
        at org.apache.felix.scr.impl.manager.ConfigurableComponentHolder.enableComponents(ConfigurableComponentHolder.java:667) ~[?:?]
        at org.apache.felix.scr.impl.BundleComponentActivator.initialEnable(BundleComponentActivator.java:305) ~[?:?]
        at org.apache.felix.scr.impl.Activator.loadComponents(Activator.java:554) ~[?:?]
        at org.apache.felix.scr.impl.Activator.access$200(Activator.java:70) ~[?:?]
        at org.apache.felix.scr.impl.Activator$ScrExtension.start(Activator.java:421) ~[?:?]
        at org.apache.felix.scr.impl.AbstractExtender.createExtension(AbstractExtender.java:196) ~[?:?]
        at org.apache.felix.scr.impl.AbstractExtender.modifiedBundle(AbstractExtender.java:169) ~[?:?]
        at org.apache.felix.scr.impl.AbstractExtender.modifiedBundle(AbstractExtender.java:49) ~[?:?]
        at org.osgi.util.tracker.BundleTracker$Tracked.customizerModified(BundleTracker.java:488) ~[osgi.core-7.0.0.jar:?]
        at org.osgi.util.tracker.BundleTracker$Tracked.customizerModified(BundleTracker.java:420) ~[osgi.core-7.0.0.jar:?]
        at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:232) ~[osgi.core-7.0.0.jar:?]
        at org.osgi.util.tracker.BundleTracker$Tracked.bundleChanged(BundleTracker.java:450) ~[osgi.core-7.0.0.jar:?]
        at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:945) ~[org.eclipse.osgi-3.16.300.jar:?]
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234) ~[org.eclipse.osgi-3.16.300.jar:?]
        at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151) ~[org.eclipse.osgi-3.16.300.jar:?]
        at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEventPrivileged(EquinoxEventPublisher.java:232) ~[org.eclipse.osgi-3.16.300.jar:?]
        at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:138) ~[org.eclipse.osgi-3.16.300.jar:?]
        at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:130) ~[org.eclipse.osgi-3.16.300.jar:?]
        at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor.publishModuleEvent(EquinoxContainerAdaptor.java:217) ~[org.eclipse.osgi-3.16.300.jar:?]
        at org.eclipse.osgi.container.Module.publishEvent(Module.java:499) ~[org.eclipse.osgi-3.16.300.jar:?]
        at org.eclipse.osgi.container.Module.start(Module.java:486) ~[org.eclipse.osgi-3.16.300.jar:?]
        at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:445) ~[org.eclipse.osgi-3.16.300.jar:?]
        at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:464) ~[org.eclipse.osgi-3.16.300.jar:?]
        at org.apache.karaf.features.internal.service.BundleInstallSupportImpl.startBundle(BundleInstallSupportImpl.java:165) ~[?:?]
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.startBundle(FeaturesServiceImpl.java:1160) ~[?:?]
        at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:1041) ~[?:?]
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1069) ~[?:?]
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.lambda$doProvisionInThread$13(FeaturesServiceImpl.java:1004) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
2022-03-24 12:59:09.908 [WARN ] [ernal.PersistenceServiceRegistryImpl] - bundle org.openhab.core.persistence:3.3.0.202203240305 (208)[org.openhab.core.persistence.internal.PersistenceServiceRegistryImpl(64)] : Could not get service from ref {org.openhab.core.persistence.PersistenceService, org.openhab.core.persistence.QueryablePersistenceService}={service.id=510, service.bundleid=286, service.scope=bundle, enableLogTime=false, user=openhab, url=jdbc:timescaledb://idun.iot.thing.home:5432/openhab_db, component.name=org.openhab.persistence.jdbc.internal.JdbcPersistenceService, service.config.label=JDBC Persistence Service, component.id=324, service.config.factory=false, password=bycucumber, tableUseRealItemNames=true, rebuildTableNames=false, service.config.category=persistence, service.config.description.uri=persistence:jdbc, service.pid=[org.openhab.jdbc, org.openhab.jdbc]}
2022-03-24 12:59:09.909 [WARN ] [ernal.PersistenceServiceRegistryImpl] - bundle org.openhab.core.persistence:3.3.0.202203240305 (208)[org.openhab.core.persistence.internal.PersistenceServiceRegistryImpl(64)] : DependencyManager : invokeBindMethod : Service not available from service registry for ServiceReference {org.openhab.core.persistence.PersistenceService, org.openhab.core.persistence.QueryablePersistenceService}={service.id=510, service.bundleid=286, service.scope=bundle, enableLogTime=false, user=openhab, url=jdbc:timescaledb://idun.iot.thing.home:5432/openhab_db, component.name=org.openhab.persistence.jdbc.internal.JdbcPersistenceService, service.config.label=JDBC Persistence Service, component.id=324, service.config.factory=false, password=bycucumber, tableUseRealItemNames=true, rebuildTableNames=false, service.config.category=persistence, service.config.description.uri=persistence:jdbc, service.pid=[org.openhab.jdbc, org.openhab.jdbc]} for reference PersistenceService
```

If i change timescaldb to postgresql persitence is working but not with the timescale feature

**Comment by digitaldan** [comment]
Hi, I don't use this binding, but looking at the docs at https://www.openhab.org/addons/persistence/jdbc/  it gives the example of this for postgresql/timescale 
`jdbc:postgresql://192.168.0.1:5432/testPostgresql`  

Does changing the JDBC connection string to use 
`jdbc:postgresql://idun.iot.thing.home:5432/openhab_db` 
work for you ?

**Comment by TBail** [comment]
@digitaldan Hi, your are right, but and the but is a big one. If i change tinescaledb to postgresql it is working, but the timescale functionality is simply not used.

prostgesql and timescale persistence are using both the porstgresql database system. The main difference is that for time scale each table needs to be converted to a hypertable. this is done in [JdbcTimescaledbDAO.java](https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/db/JdbcTimescaledbDAO.java) with the following code

```
   private void initSqlQueries() {
        this.logger.debug("JDBC::initSqlQueries: '{}'", this.getClass().getSimpleName());

        this.sqlCreateHypertable = "SELECT create_hypertable('#tableName#', 'time')";
    }

```

With this hypertable postgresql acts as a timescaledb. At the end the different behaviour is hidden behinde the scenes. So the postgresql driver does no see if this should be a timescaledb or a standard prostgresql db.

From my point of view the database driver code needs to be altered in that way that if the jdbc url has the timescaldb entry the extended (timescaledb) driver should be loaded. At the moment this does not happen.

Unfortunatly i am not that deep in Java to find the right position and create a PR

**Comment by digitaldan** [comment]
Hmm, it would  seem there is a  separate Timescale DB class, so indeed `timescaledb` is needed in the URL ,  and the class that handles that does create the table the way you pointed out.  Whats interesting is it looks like the class is suppose to replace `timescaledb` with `postgresql` in the actual connection string it uses, but maybe thats not being called correctly?  It's odd others are not having this issue, although i have no idea how many use timescale.   
https://github.com/openhab/openhab-addons/blob/4774f8a7e76f6b5fbf3ea8e41fe3f14758c4de0c/bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/db/JdbcTimescaledbDAO.java#L45

**Comment by TBail** [comment]
I think other have this issue too, but if you change the timescaledb string to postgreesql it works, because timescale in only an extension to postgre. So postgre insead of timescale is working but without the timescale features.

There is another open issue with timescale not using utc time. https://github.com/openhab/openhab-addons/issues/12315

An a second to enhance the functionality https://github.com/openhab/openhab-addons/issues/12051 from @lujop 

Maybe one of the could check if hypertables are working on their side.

**Comment by TBail** [comment]
Having another look on it i think that there is a driver initialisation problem. There is no timescaleDB jdbc driver. There is only the one for postgresql. That is the reason for the renaming. But openHAB  tried to use the timescaledb driver before the url has renamed to postgre and there is no driver

**Comment by digitaldan** [comment]
yes, if you look at the link i posted above, it would seem that replacement is not happening when getting the connection string. 

Looking at this a little more closely, i think the author named that function incorrectly instead of
```java
 public Properties getDatabaseProperties() 
```
it should be

```java
public Properties  getConnectionProperties()
```
I can open a PR if you can test it for me (i'm not running timescaledb) .  You may want to make sure that table is dropped so the driver can create it with the right timescale engine type.

**Comment by digitaldan** [comment]
Once the PR build finishes, i'll post a link to the artifact

**Comment by TBail** [comment]
Will try that as soon as get the link :-)

**Comment by digitaldan** [comment]
Latest PR build is at

https://openhab.jfrog.io/openhab/libs-pullrequest-local/org/openhab/addons/bundles/org.openhab.persistence.jdbc/3.3.0-SNAPSHOT/org.openhab.persistence.jdbc-3.3.0-SNAPSHOT.jar

**Comment by TBail** [comment]
Ok, i downloaded the build, deinstall jdbc persistence and droped the new one to the Addon folder. Now i got a new error message:

```
2022-03-26 17:15:04.827 [ERROR] [ence.jdbc.internal.JdbcConfiguration] - JDBC::updateConfig: could NOT load JDBC-driverClassName or JDBC-dataSourceClassName. ClassNotFoundException: 'org.postgresql.Driver cannot be found by org.openhab.persistence.jdbc_3.3.0.202203261451'
2022-03-26 17:15:04.828 [WARN ] [ence.jdbc.internal.JdbcConfiguration] - 

        !!!
        To avoid this error, place an appropriate JDBC driver file for serviceName 'timescaledb' in addons directory.
        Copy missing JDBC-Driver-jar to your openHab/addons Folder.
        !!!
        DOWNLOAD: 

2022-03-26 17:15:04.830 [WARN ] [persistence.jdbc.internal.JdbcMapper] - JDBC::openConnection: no driver available!
```

That could be fixed by plaing the postgre jdbc driver into the addon folder, but now i got the same error as in the first post

**Comment by digitaldan** [comment]
yeah, found another issue, i'm not sure this was ever tested or working, as soon as the build finishes you can download again and try.  Its at least doing the right thing on my system now and trying to connect to a DB

**Comment by TBail** [comment]
I think the problem ist that with the postgre sql the database is working anyway and i assume the the typicall openHAB environment does not bring postgre to its limits.

**Comment by digitaldan** [comment]
Ok, give it another shot

https://openhab.jfrog.io/artifactory/libs-pullrequest-local/org/openhab/addons/bundles/org.openhab.persistence.jdbc/3.3.0-SNAPSHOT/org.openhab.persistence.jdbc-3.3.0-SNAPSHOT.jar

**Comment by TBail** [comment]
Almost there. Database is connected, tables are created, hypertables are created, data is written.

Only getting one error. While creating the hypertable there is a result that is not expected. The SQl statement is from my point of view ok.

```
2022-03-26 19:47:15.905 [ERROR] [org.knowm.yank.Yank                 ] - Error in SQL query!!!
java.sql.SQLException: Die Anweisung lieferte ein Ergebnis obwohl keines erwartet wurde. Query: SELECT create_hypertable('rb_hc_buderus_cylinderbottomteperature_0001', 'time') Parameters: []
        at org.apache.commons.dbutils.AbstractQueryRunner.rethrow(AbstractQueryRunner.java:392) ~[?:?]
        at org.apache.commons.dbutils.QueryRunner.update(QueryRunner.java:491) ~[?:?]
        at org.apache.commons.dbutils.QueryRunner.update(QueryRunner.java:457) ~[?:?]
        at org.knowm.yank.Yank.execute(Yank.java:194) ~[?:?]
        at org.knowm.yank.Yank.execute(Yank.java:177) ~[?:?]
        at org.openhab.persistence.jdbc.db.JdbcTimescaledbDAO.doCreateItemTable(JdbcTimescaledbDAO.java:63) ~[?:?]
        at org.openhab.persistence.jdbc.internal.JdbcMapper.createItemTable(JdbcMapper.java:149) ~[?:?]
        at org.openhab.persistence.jdbc.internal.JdbcMapper.getTable(JdbcMapper.java:316) ~[?:?]
        at org.openhab.persistence.jdbc.internal.JdbcMapper.storeItemValue(JdbcMapper.java:156) ~[?:?]
        at org.openhab.persistence.jdbc.internal.JdbcPersistenceService.internalStore(JdbcPersistenceService.java:156) ~[?:?]
        at org.openhab.persistence.jdbc.internal.JdbcPersistenceService.store(JdbcPersistenceService.java:135) ~[?:?]
        at org.openhab.core.persistence.internal.PersistenceManagerImpl.handleStateEvent(PersistenceManagerImpl.java:152) ~[?:?]
        at org.openhab.core.persistence.internal.PersistenceManagerImpl.stateUpdated(PersistenceManagerImpl.java:478) ~[?:?]
        at org.openhab.core.items.GenericItem.lambda$1(GenericItem.java:257) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
2022-03-26 19:47:18.410 [ERROR] [org.knowm.yank.Yank                 ] - Error in SQL query!!!
java.sql.SQLException: Die Anweisung lieferte ein Ergebnis obwohl keines erwartet wurde. Query: SELECT create_hypertable('rb_br_ambientsensor_humidity_0002', 'time') Parameters: []
        at org.apache.commons.dbutils.AbstractQueryRunner.rethrow(AbstractQueryRunner.java:392) ~[?:?]
        at org.apache.commons.dbutils.QueryRunner.update(QueryRunner.java:491) ~[?:?]
        at org.apache.commons.dbutils.QueryRunner.update(QueryRunner.java:457) ~[?:?]
        at org.knowm.yank.Yank.execute(Yank.java:194) ~[?:?]
        at org.knowm.yank.Yank.execute(Yank.java:177) ~[?:?]
        at org.openhab.persistence.jdbc.db.JdbcTimescaledbDAO.doCreateItemTable(JdbcTimescaledbDAO.java:63) ~[?:?]
        at org.openhab.persistence.jdbc.internal.JdbcMapper.createItemTable(JdbcMapper.java:149) ~[?:?]
        at org.openhab.persistence.jdbc.internal.JdbcMapper.getTable(JdbcMapper.java:316) ~[?:?]
        at org.openhab.persistence.jdbc.internal.JdbcMapper.storeItemValue(JdbcMapper.java:156) ~[?:?]
        at org.openhab.persistence.jdbc.internal.JdbcPersistenceService.internalStore(JdbcPersistenceService.java:156) ~[?:?]
        at org.openhab.persistence.jdbc.internal.JdbcPersistenceService.store(JdbcPersistenceService.java:135) ~[?:?]
        at org.openhab.core.persistence.internal.PersistenceManagerImpl.handleStateEvent(PersistenceManagerImpl.java:152) ~[?:?]
        at org.openhab.core.persistence.internal.PersistenceManagerImpl.stateUpdated(PersistenceManagerImpl.java:478) ~[?:?]
        at org.openhab.core.items.GenericItem.lambda$1(GenericItem.java:257) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
```

Thanks for your help so far.

**Comment by digitaldan** [comment]
Yep, i think it still might work, but the original author was doing a query where the underlying driver expects something like an update which does not return results.  I put in fix for this as well, build will be done shortly with a new jar.  I spun up a little docker container with timescaledb to test and its working for me so far.  You may want to blow away the timescale database (or at least the tables in it) and let this create everything from scratch again.

**Comment by TBail** [comment]
If you send me the link to the jar i could check the latest update. Currently there is not much data in the DB. So blow it away and set it up from scratch is no promblem.

**Comment by digitaldan** [comment]
Sorry, the link i posted above doesn't change and points to the latest PR build for the binding .  Hopefully it's still valid.  I'm on a plane today, but will post a jar or trigger a rebuild if that link is not working atm.

**Comment by TBail** [comment]
No problem, the above link give me a jar file, but the sql error is still there. We are at 99% so no need to hurry.

**Comment by TBail** [comment]
@digitaldan It would be really kind if you could provide a working version link, because the pr is not merged and i did not save the latest working version.

Thanks
Thomas

**Comment by digitaldan** [comment]
HI @TBail i was out of town for the last few days.   Here is a link to the latest build on my github repo

https://github.com/digitaldan/openhab-addons/releases/tag/jdbc-timescale-fix-12513

**Comment by TBail** [comment]
Hi @digitaldan 

thanks a lot for the link. Know i schould be able to move data to another system and see historical data :-)

Thanks
