### ISSUE TITLE
[homematic] Some command(s) are not received by the CCU

### ISSUE THREAD

**Issue by BOFH90** [openhab/openhab-addons#12549]
Im running OH 3.2.0 on Debian and 3 different CCUs (RaspberryMatic OVA´s on Proxmox). 
It´s running great, except some commands are randomly(?) not send to the CCU 1-2 times a day to different times.
as openhab runs on the same Proxmox Host as the CCUs (RaspberryMatic), there should be no network problems.
After the error occours, everything works as a expected again. Just the one command got missing and did not re-execute.

The following message appears in the log when the issue occours:

```
2022-03-30 20:54:11.686 [ERROR] [ternal.handler.HomematicThingHandler] - java.util.concurrent.ExecutionException: java.io.EOFException: HttpConnectionOverHTTP@2783a4bf::SocketChannelEndPoint@6299555a{l=/10.0.0.15:60862,r=/10.0.6.1:2000,ISHUT,fill=-,flush=-,to=0/0}{io=1/0,kio=1,kro=1}->HttpConnectionOverHTTP@2783a4bf(l:/10.0.0.15:60862 <-> r:/10.0.6.1:2000,closed=false)=>HttpChannelOverHTTP@776ef4b5(exchange=HttpExchange@695136ec{req=HttpRequest[POST / HTTP/1.1]@534dd125[TERMINATED/null] res=HttpResponse[null 0 null]@7b566d93[PENDING/null]})[send=HttpSenderOverHTTP@7b1df510(req=QUEUED,snd=COMPLETED,failure=null)[HttpGenerator@1b9b5ac9{s=START}],recv=HttpReceiverOverHTTP@26627466(rsp=IDLE,failure=null)[HttpParser{s=CLOSED,0 of -1}]]
java.io.IOException: java.util.concurrent.ExecutionException: java.io.EOFException: HttpConnectionOverHTTP@2783a4bf::SocketChannelEndPoint@6299555a{l=/10.0.0.15:60862,r=/10.0.6.1:2000,ISHUT,fill=-,flush=-,to=0/0}{io=1/0,kio=1,kro=1}->HttpConnectionOverHTTP@2783a4bf(l:/10.0.0.15:60862 <-> r:/10.0.6.1:2000,closed=false)=>HttpChannelOverHTTP@776ef4b5(exchange=HttpExchange@695136ec{req=HttpRequest[POST / HTTP/1.1]@534dd125[TERMINATED/null] res=HttpResponse[null 0 null]@7b566d93[PENDING/null]})[send=HttpSenderOverHTTP@7b1df510(req=QUEUED,snd=COMPLETED,failure=null)[HttpGenerator@1b9b5ac9{s=START}],recv=HttpReceiverOverHTTP@26627466(rsp=IDLE,failure=null)[HttpParser{s=CLOSED,0 of -1}]]
        at org.openhab.binding.homematic.internal.communicator.client.XmlRpcClient.send(XmlRpcClient.java:121) ~[bundleFile:?]
        at org.openhab.binding.homematic.internal.communicator.client.XmlRpcClient.sendMessage(XmlRpcClient.java:73) ~[bundleFile:?]
        at org.openhab.binding.homematic.internal.communicator.client.RpcClient.setDatapointValue(RpcClient.java:379) ~[bundleFile:?]
        at org.openhab.binding.homematic.internal.communicator.AbstractHomematicGateway$1.execute(AbstractHomematicGateway.java:691) ~[bundleFile:?]
        at org.openhab.binding.homematic.internal.misc.DelayedExecuter.start(DelayedExecuter.java:65) ~[bundleFile:?]
        at org.openhab.binding.homematic.internal.communicator.AbstractHomematicGateway.sendDatapoint(AbstractHomematicGateway.java:670) ~[bundleFile:?]
        at org.openhab.binding.homematic.internal.communicator.AbstractHomematicGateway.sendDatapoint(AbstractHomematicGateway.java:649) ~[bundleFile:?]
        at org.openhab.binding.homematic.internal.handler.HomematicThingHandler.sendDatapoint(HomematicThingHandler.java:364) ~[bundleFile:?]
        at org.openhab.binding.homematic.internal.handler.HomematicThingHandler.handleCommand(HomematicThingHandler.java:340) [bundleFile:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.openhab.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:154) [bundleFile:?]
        at org.openhab.core.internal.common.InvocationHandlerSync.invoke(InvocationHandlerSync.java:59) [bundleFile:?]
        at com.sun.proxy.$Proxy15939.handleCommand(Unknown Source) [?:?]
        at org.openhab.core.thing.internal.profiles.ProfileCallbackImpl.handleCommand(ProfileCallbackImpl.java:80) [bundleFile:?]
        at org.openhab.core.thing.internal.profiles.SystemDefaultProfile.onCommandFromItem(SystemDefaultProfile.java:48) [bundleFile:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.openhab.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:154) [bundleFile:?]
        at org.openhab.core.internal.common.Invocation.call(Invocation.java:52) [bundleFile:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.util.concurrent.ExecutionException: java.io.EOFException: HttpConnectionOverHTTP@2783a4bf::SocketChannelEndPoint@6299555a{l=/10.0.0.15:60862,r=/10.0.6.1:2000,ISHUT,fill=-,flush=-,to=0/0}{io=1/0,kio=1,kro=1}->HttpConnectionOverHTTP@2783a4bf(l:/10.0.0.15:60862 <-> r:/10.0.6.1:2000,closed=false)=>HttpChannelOverHTTP@776ef4b5(exchange=HttpExchange@695136ec{req=HttpRequest[POST / HTTP/1.1]@534dd125[TERMINATED/null] res=HttpResponse[null 0 null]@7b566d93[PENDING/null]})[send=HttpSenderOverHTTP@7b1df510(req=QUEUED,snd=COMPLETED,failure=null)[HttpGenerator@1b9b5ac9{s=START}],recv=HttpReceiverOverHTTP@26627466(rsp=IDLE,failure=null)[HttpParser{s=CLOSED,0 of -1}]]
        at org.eclipse.jetty.client.util.FutureResponseListener.getResult(FutureResponseListener.java:118) ~[bundleFile:9.4.43.v20210629]
        at org.eclipse.jetty.client.util.FutureResponseListener.get(FutureResponseListener.java:110) ~[bundleFile:9.4.43.v20210629]
        at org.openhab.binding.homematic.internal.communicator.client.XmlRpcClient.send(XmlRpcClient.java:111) ~[bundleFile:?]
        ... 27 more
Caused by: java.io.EOFException: HttpConnectionOverHTTP@2783a4bf::SocketChannelEndPoint@6299555a{l=/10.0.0.15:60862,r=/10.0.6.1:2000,ISHUT,fill=-,flush=-,to=0/0}{io=1/0,kio=1,kro=1}->HttpConnectionOverHTTP@2783a4bf(l:/10.0.0.15:60862 <-> r:/10.0.6.1:2000,closed=false)=>HttpChannelOverHTTP@776ef4b5(exchange=HttpExchange@695136ec{req=HttpRequest[POST / HTTP/1.1]@534dd125[TERMINATED/null] res=HttpResponse[null 0 null]@7b566d93[PENDING/null]})[send=HttpSenderOverHTTP@7b1df510(req=QUEUED,snd=COMPLETED,failure=null)[HttpGenerator@1b9b5ac9{s=START}],recv=HttpReceiverOverHTTP@26627466(rsp=IDLE,failure=null)[HttpParser{s=CLOSED,0 of -1}]]
        at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.earlyEOF(HttpReceiverOverHTTP.java:376) ~[?:?]
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1614) ~[?:?]
        at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.shutdown(HttpReceiverOverHTTP.java:259) ~[?:?]
        at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.process(HttpReceiverOverHTTP.java:181) ~[?:?]
        at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:79) ~[?:?]
        at org.eclipse.jetty.client.http.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:131) ~[?:?]
        at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:172) ~[?:?]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) ~[?:?]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) ~[?:?]
        at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) ~[?:?]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338) ~[?:?]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315) ~[?:?]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173) ~[?:?]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131) ~[?:?]
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:386) ~[?:?]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883) ~[?:?]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034) ~[?:?]
        ... 1 more
```

**Comment by MHerbst** [comment]
As far as I remember, these problems happen if the server side (the CCU) closes the connection unexpectedly (maybe because of some timeouts). It is really hard to figure out what causes the problem. 
I know about a similar problem with a CCU2 if there are many requests from OH at the same time. In these cases the CCU2 probably was too slow. Maybe you can assign more resources  to your CCU VMs.

**Comment by BOFH90** [comment]
Thanks for your answer. I got 4Cores and 2G Ram assigned to the RaspberryMatic-VM. This should be okay compared to any RaspberryPi. I´ll just change the Memory to 4G and see if it makes any difference.

**Comment by lsiepel** [comment]
As @BOFH90 did not report back in and many [pull requests](https://github.com/openhab/openhab-addons/pulls?q=is%3Apr+is%3Aclosed+merged%3A2021-05-01..2025-01-01+in%3Atitle+homematic+) have been merged since raising this issue. It might already be fixed.

Would be nice if it can be confirmed to be no longer an issue. (please confirm with openHAB 4.2.0)

**Comment by BOFH90** [comment]
Sorry for the missing feedback. As I encountered other errors in OH, I‘ve made the switch to HA and could not test it any further, but the added memory didn’t fix the issue. I’ll close this issue.
