### ISSUE TITLE
MAP transformation: Failing tests on Windows

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-addons#12619]
Here are the results on Windows:
```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.openhab.transform.map.internal.MapTransformationServiceTest
[ERROR] Tests run: 7, Failures: 0, Errors: 5, Skipped: 0, Time elapsed: 0.634 s <<< FAILURE! - in org.openhab.transform.map.internal.MapTransformationServiceTest
[ERROR] org.openhab.transform.map.internal.MapTransformationServiceTest.setTransformationConfigurationIsNotUpdatedIfOldElementMissing  Time elapsed: 0.573 s  <<< ERROR!
java.lang.NullPointerException
        at org.openhab.transform.map.internal.MapTransformationServiceTest.setTransformationConfigurationIsNotUpdatedIfOldElementMissing(MapTransformationServiceTest.java:126)

[ERROR] org.openhab.transform.map.internal.MapTransformationServiceTest.setTransformationConfigurationIsRemoved  Time elapsed: 0.006 s  <<< ERROR!
org.openhab.core.transform.TransformationException: Could not find configuration 'map/doorstatus_de.map' or failed to parse it.
        at org.openhab.transform.map.internal.MapTransformationServiceTest.setTransformationConfigurationIsRemoved(MapTransformationServiceTest.java:112)

[ERROR] org.openhab.transform.map.internal.MapTransformationServiceTest.testTransformSucceeds  Time elapsed: 0.003 s  <<< ERROR!
org.openhab.core.transform.TransformationException: Could not find configuration 'map/doorstatus_de.map' or failed to parse it.
        at org.openhab.transform.map.internal.MapTransformationServiceTest.testTransformSucceeds(MapTransformationServiceTest.java:90)

[ERROR] org.openhab.transform.map.internal.MapTransformationServiceTest.setTransformationConfigurationIsUpdatedIfOldElementPresent  Time elapsed: 0.003 s  <<< ERROR!
org.openhab.core.transform.TransformationException: Could not find configuration 'map/doorstatus_de.map' or failed to parse it.
        at org.openhab.transform.map.internal.MapTransformationServiceTest.setTransformationConfigurationIsUpdatedIfOldElementPresent(MapTransformationServiceTest.java:142)

[ERROR] org.openhab.transform.map.internal.MapTransformationServiceTest.testTransformSucceedsWithDefault  Time elapsed: 0.003 s  <<< ERROR!
org.openhab.core.transform.TransformationException: Could not find configuration 'map/doorstatus_defaulted.map' or failed to parse it.
        at org.openhab.transform.map.internal.MapTransformationServiceTest.testTransformSucceedsWithDefault(MapTransformationServiceTest.java:102)

[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   MapTransformationServiceTest.setTransformationConfigurationIsNotUpdatedIfOldElementMissing:126 ▒ NullPointer
[ERROR]   MapTransformationServiceTest.setTransformationConfigurationIsRemoved:112 ▒ Transformation
[ERROR]   MapTransformationServiceTest.setTransformationConfigurationIsUpdatedIfOldElementPresent:142 ▒ Transformation
[ERROR]   MapTransformationServiceTest.testTransformSucceeds:90 ▒ Transformation Could n...
[ERROR]   MapTransformationServiceTest.testTransformSucceedsWithDefault:102 ▒ Transformation
[INFO]
[ERROR] Tests run: 7, Failures: 0, Errors: 5, Skipped: 0
```

**Comment by lolodomo** [comment]
@J-N-K : is it related to #12433 ?

**Comment by J-N-K** [comment]
No idea. I don‘t have a windows machine anymore. It seems to work for the Linux CI builds and also locally ok MacOS.

I think the NPE results from an issue with loading the transformation.

**Comment by lolodomo** [comment]
> I think the NPE results from an issue with loading the transformation.

Yes, paths were hardcoded Unix paths. This is now fixed.
There was another problem related to string built with wrong encoding. Fixed too.
