### ISSUE TITLE
[homematic] Changing Homematic thermostat temp does not work in sitemap anymore

### ISSUE THREAD

**Issue by sidamos** [openhab/openhab-addons#12644]
## Expected Behavior
When I change the temperature of an Homematic IP heating group in a sitemap, it should work. This may be a regression in 3.2.0 or 3.x.

## Current Behavior
Exception happens:
```
2022-04-16 16:53:10.976 [ERROR] [ternal.handler.HomematicThingHandler] - null
java.lang.NullPointerException: null
        at org.openhab.binding.homematic.internal.converter.type.QuantityTypeConverter.toBinding(QuantityTypeConverter.java:51) ~[bundleFile:?]
        at org.openhab.binding.homematic.internal.converter.type.QuantityTypeConverter.toBinding(QuantityTypeConverter.java:1) ~[bundleFile:?]
        at org.openhab.binding.homematic.internal.converter.type.AbstractTypeConverter.convertToBinding(AbstractTypeConverter.java:103) ~[bundleFile:?]
        at org.openhab.binding.homematic.internal.handler.HomematicThingHandler.handleCommand(HomematicThingHandler.java:338) [bundleFile:?]
        at jdk.internal.reflect.GeneratedMethodAccessor179.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.openhab.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:154) [bundleFile:?]
        at org.openhab.core.internal.common.InvocationHandlerSync.invoke(InvocationHandlerSync.java:59) [bundleFile:?]
        at com.sun.proxy.$Proxy2193.handleCommand(Unknown Source) [?:?]
        at org.openhab.core.thing.internal.profiles.ProfileCallbackImpl.handleCommand(ProfileCallbackImpl.java:80) [bundleFile:?]
        at org.openhab.core.thing.internal.profiles.SystemDefaultProfile.onCommandFromItem(SystemDefaultProfile.java:48) [bundleFile:?]
        at jdk.internal.reflect.GeneratedMethodAccessor178.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.openhab.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:154) [bundleFile:?]
        at org.openhab.core.internal.common.Invocation.call(Invocation.java:52) [bundleFile:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
```

## Steps to Reproduce (for Bugs)
Create a sitemap with such an entry:
```
Setpoint item=HM_HeizungWohnzimmer_1_SetPointTemperature label="Wohnzimmer Solltemp. [%.1f°C]" minValue=4.5 maxValue=25 step=0.5
```
Try to change the temperature.

## Your Environment
* Version used: openHAB 3.2.0
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...): Java 11
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): Gentoo Linux
* Homematic IP heating group running with CCU3

See also: https://community.openhab.org/t/changing-homematic-thermostat-temp-does-not-work-in-sitemap-anymore/135195

**Comment by MHerbst** [comment]
The QuantityConverter class where the NPE happens has not been touched for 3.x. So maybe there is problem in combination with changes in the sitemap implemementation.
Can you set the log level to TRACE, change the temperature and post the excerpt from the log where I can see the exception and what happens before the exception?

**Comment by sidamos** [comment]
Here it is:
```
2022-04-24 16:09:21.568 [DEBUG] [ternal.handler.HomematicThingHandler] - Received command '23 °' for channel 'homematic:HmIP-HEATING:3014F711A0001F98A9A6E22D:INT0000007:1#SET_POINT_TEMPERATURE'
2022-04-24 16:09:21.569 [DEBUG] [converter.type.AbstractTypeConverter] - Converting type QuantityType with value '23 °' using QuantityTypeConverter to datapoint 'INT0000007:1#SET_POINT_TEMPERATURE' (dpType='FLOAT', dpUnit='°C')
2022-04-24 16:09:21.569 [ERROR] [ternal.handler.HomematicThingHandler] - null
java.lang.NullPointerException: null
        at org.openhab.binding.homematic.internal.converter.type.QuantityTypeConverter.toBinding(QuantityTypeConverter.java:51) ~[bundleFile:?]
        at org.openhab.binding.homematic.internal.converter.type.QuantityTypeConverter.toBinding(QuantityTypeConverter.java:1) ~[bundleFile:?]
        at org.openhab.binding.homematic.internal.converter.type.AbstractTypeConverter.convertToBinding(AbstractTypeConverter.java:103) ~[bundleFile:?]
        at org.openhab.binding.homematic.internal.handler.HomematicThingHandler.handleCommand(HomematicThingHandler.java:338) [bundleFile:?]
        at jdk.internal.reflect.GeneratedMethodAccessor181.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.openhab.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:154) [bundleFile:?]
        at org.openhab.core.internal.common.InvocationHandlerSync.invoke(InvocationHandlerSync.java:59) [bundleFile:?]
        at com.sun.proxy.$Proxy407.handleCommand(Unknown Source) [?:?]
        at org.openhab.core.thing.internal.profiles.ProfileCallbackImpl.handleCommand(ProfileCallbackImpl.java:80) [bundleFile:?]
        at org.openhab.core.thing.internal.profiles.SystemDefaultProfile.onCommandFromItem(SystemDefaultProfile.java:48) [bundleFile:?]
        at jdk.internal.reflect.GeneratedMethodAccessor180.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.openhab.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:154) [bundleFile:?]
        at org.openhab.core.internal.common.Invocation.call(Invocation.java:52) [bundleFile:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
```

**Comment by sidamos** [comment]
I think I found the issue:
I have a State Description for this item as "%.1f°". When I set this to "%.1f °C", then it works.
Is this a bug? It is at least a bit annoying.

**Comment by MHerbst** [comment]
The correct unit definition for a temperature is °C and not not only °. But I don't like that an exception is thrown in this case. I would expect an error message that gives a hint what is wrong. I will have a look into the code and try to implement a better error handling for these cases.

**Comment by sidamos** [comment]
Hmm, I mean, the whole State Description feature is available, so that I can define how I want the value to look, right?
The sitemap could send the raw value to the item. But I know that the whole Quantity Type thing is a bit strange sometimes.

**Comment by MHerbst** [comment]
In this case you have to valid unit types: ° as the representation of a degree of arc and °C for a temperature. It is not possible to convert a degree of arc to a temperature :-).

But I agree, the unit support could be more intuitive in some cases. I already had some problems with State Descriptions for percent values.

**Comment by sidamos** [comment]
The thing is, I use the State Description to describe how a value should look like in the UI. And if I want to save space, I use only the value or a shortened unit type. But OK, this is not a problem of the binding, more a general issue with openHAB.

**Comment by MHerbst** [comment]
@sidamos Can you close this issue here?
