### ISSUE TITLE
[homie] HomieImplementationTest unstable

### ISSUE THREAD

**Issue by J-N-K** [openhab/openhab-addons#12667]
https://github.com/openhab/openhab-addons/runs/6230228701?check_suite_focus=true
https://github.com/openhab/openhab-addons/runs/6231105334?check_suite_focus=true

```
2022-04-29T15:51:48.5276685Z TEST org.openhab.binding.mqtt.homie.HomieImplementationTest#parseHomieTree() <<< ERROR: 
2022-04-29T15:51:48.5276771Z Expected: is "false"
2022-04-29T15:51:48.5276852Z      but: was null
2022-04-29T15:51:48.5276954Z java.lang.AssertionError: 
2022-04-29T15:51:48.5277038Z Expected: is "false"
2022-04-29T15:51:48.5277113Z      but: was null
2022-04-29T15:51:48.5277292Z 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
2022-04-29T15:51:48.5277451Z 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
2022-04-29T15:51:48.5277752Z 	at org.openhab.binding.mqtt.homie.HomieImplementationTest.parseHomieTree(HomieImplementationTest.java:303)
2022-04-29T15:51:48.5278027Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-04-29T15:51:48.5278298Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2022-04-29T15:51:48.5278577Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-04-29T15:51:48.5278733Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2022-04-29T15:51:48.5278984Z 	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
2022-04-29T15:51:48.5279228Z 	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
2022-04-29T15:51:48.5279554Z 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
2022-04-29T15:51:48.5279800Z 	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
2022-04-29T15:51:48.5280108Z 	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
2022-04-29T15:51:48.5280393Z 	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
2022-04-29T15:51:48.5280695Z 	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
2022-04-29T15:51:48.5280952Z 	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
2022-04-29T15:51:48.5281282Z 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
2022-04-29T15:51:48.5281587Z 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
2022-04-29T15:51:48.5281919Z 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
2022-04-29T15:51:48.5282219Z 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
2022-04-29T15:51:48.5282464Z 	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
2022-04-29T15:51:48.5282706Z 	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
2022-04-29T15:51:48.5283027Z 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:214)
2022-04-29T15:51:48.5283359Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2022-04-29T15:51:48.5283696Z 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:210)
2022-04-29T15:51:48.5283996Z 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
2022-04-29T15:51:48.5284290Z 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)
2022-04-29T15:51:48.5284581Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
2022-04-29T15:51:48.5284877Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2022-04-29T15:51:48.5285163Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
2022-04-29T15:51:48.5285380Z 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
2022-04-29T15:51:48.5285664Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
2022-04-29T15:51:48.5285956Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2022-04-29T15:51:48.5286257Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
2022-04-29T15:51:48.5286571Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
2022-04-29T15:51:48.5286724Z 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
2022-04-29T15:51:48.5287203Z 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
2022-04-29T15:51:48.5287496Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
2022-04-29T15:51:48.5287801Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2022-04-29T15:51:48.5288088Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
2022-04-29T15:51:48.5288307Z 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
2022-04-29T15:51:48.5288594Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
2022-04-29T15:51:48.5288895Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2022-04-29T15:51:48.5289198Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
2022-04-29T15:51:48.5289460Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
2022-04-29T15:51:48.5289613Z 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
2022-04-29T15:51:48.5290075Z 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
2022-04-29T15:51:48.5290361Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
2022-04-29T15:51:48.5290651Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2022-04-29T15:51:48.5290930Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
2022-04-29T15:51:48.5291149Z 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
2022-04-29T15:51:48.5291430Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
2022-04-29T15:51:48.5291718Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2022-04-29T15:51:48.5292063Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
2022-04-29T15:51:48.5292321Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
2022-04-29T15:51:48.5292775Z 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
2022-04-29T15:51:48.5293112Z 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
2022-04-29T15:51:48.5293435Z 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
2022-04-29T15:51:48.5293662Z 	at aQute.tester.bundle.engine.BundleDescriptor.executeChild(BundleDescriptor.java:49)
2022-04-29T15:51:48.5293869Z 	at aQute.tester.bundle.engine.BundleEngine.lambda$executeBundle$7(BundleEngine.java:120)
2022-04-29T15:51:48.5294050Z 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
2022-04-29T15:51:48.5294243Z 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
2022-04-29T15:51:48.5294407Z 	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
2022-04-29T15:51:48.5294625Z 	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
2022-04-29T15:51:48.5294825Z 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
2022-04-29T15:51:48.5295043Z 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
2022-04-29T15:51:48.5295288Z 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
2022-04-29T15:51:48.5295492Z 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
2022-04-29T15:51:48.5295682Z 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
2022-04-29T15:51:48.5295885Z 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
2022-04-29T15:51:48.5296102Z 	at aQute.tester.bundle.engine.BundleEngine.executeBundle(BundleEngine.java:120)
2022-04-29T15:51:48.5296309Z 	at aQute.tester.bundle.engine.BundleEngine.lambda$executeBundle$8(BundleEngine.java:133)
2022-04-29T15:51:48.5296485Z 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
2022-04-29T15:51:48.5296680Z 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
2022-04-29T15:51:48.5296870Z 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
2022-04-29T15:51:48.5297032Z 	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
2022-04-29T15:51:48.5297244Z 	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
2022-04-29T15:51:48.5297447Z 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
2022-04-29T15:51:48.5297665Z 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
2022-04-29T15:51:48.5297861Z 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
2022-04-29T15:51:48.5298059Z 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
2022-04-29T15:51:48.5298261Z 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
2022-04-29T15:51:48.5298466Z 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
2022-04-29T15:51:48.5298682Z 	at aQute.tester.bundle.engine.BundleEngine.executeBundle(BundleEngine.java:133)
2022-04-29T15:51:48.5298890Z 	at aQute.tester.bundle.engine.BundleEngine.lambda$execute$5(BundleEngine.java:100)
2022-04-29T15:51:48.5299072Z 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
2022-04-29T15:51:48.5299259Z 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
2022-04-29T15:51:48.5299482Z 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
2022-04-29T15:51:48.5299651Z 	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
2022-04-29T15:51:48.5299866Z 	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
2022-04-29T15:51:48.5300067Z 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
2022-04-29T15:51:48.5300284Z 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
2022-04-29T15:51:48.5300482Z 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
2022-04-29T15:51:48.5300681Z 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
2022-04-29T15:51:48.5300880Z 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
2022-04-29T15:51:48.5301079Z 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
2022-04-29T15:51:48.5301274Z 	at aQute.tester.bundle.engine.BundleEngine.execute(BundleEngine.java:100)
2022-04-29T15:51:48.5301571Z 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
2022-04-29T15:51:48.5301869Z 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
2022-04-29T15:51:48.5302172Z 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
2022-04-29T15:51:48.5302616Z 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
2022-04-29T15:51:48.5302908Z 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
2022-04-29T15:51:48.5303131Z 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
2022-04-29T15:51:48.5303352Z 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
2022-04-29T15:51:48.5303635Z 	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
2022-04-29T15:51:48.5303928Z 	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
2022-04-29T15:51:48.5304110Z 	at aQute.tester.junit.platform.Activator.test(Activator.java:439)
2022-04-29T15:51:48.5304288Z 	at aQute.tester.junit.platform.Activator.automatic(Activator.java:344)
2022-04-29T15:51:48.5304464Z 	at aQute.tester.junit.platform.Activator.run(Activator.java:216)
2022-04-29T15:51:48.5304656Z 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
2022-04-29T15:51:48.5304796Z 	at aQute.launcher.Launcher.launch(Launcher.java:450)
2022-04-29T15:51:48.5304924Z 	at aQute.launcher.Launcher.run(Launcher.java:184)
2022-04-29T15:51:48.5305054Z 	at aQute.launcher.Launcher.main(Launcher.java:160)
2022-04-29T15:51:48.5305285Z 	at aQute.launcher.pre.EmbeddedLauncher.executeWithRunPath(EmbeddedLauncher.java:170)
2022-04-29T15:51:48.5305507Z 	at aQute.launcher.pre.EmbeddedLauncher.findAndExecute(EmbeddedLauncher.java:135)
2022-04-29T15:51:48.5305704Z 	at aQute.launcher.pre.EmbeddedLauncher.main(EmbeddedLauncher.java:52)
```

**Comment by wborn** [comment]
Still unstable, see: https://ci.openhab.org/job/openHAB-Addons/1458/console

```
TEST org.openhab.binding.mqtt.homie.HomieImplementationTest#retrieveOneAttribute() <<< ERROR: 
Expected: is "3.0"
     but: was null
java.lang.AssertionError: 
Expected: is "3.0"
     but: was null
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
	at org.openhab.binding.mqtt.homie.HomieImplementationTest.retrieveOneAttribute(HomieImplementationTest.java:171)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at aQute.tester.bundle.engine.BundleDescriptor.executeChild(BundleDescriptor.java:49)
	at aQute.tester.bundle.engine.BundleEngine.lambda$executeBundle$7(BundleEngine.java:120)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at aQute.tester.bundle.engine.BundleEngine.executeBundle(BundleEngine.java:120)
	at aQute.tester.bundle.engine.BundleEngine.lambda$executeBundle$8(BundleEngine.java:133)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at aQute.tester.bundle.engine.BundleEngine.executeBundle(BundleEngine.java:133)
	at aQute.tester.bundle.engine.BundleEngine.lambda$execute$5(BundleEngine.java:100)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at aQute.tester.bundle.engine.BundleEngine.execute(BundleEngine.java:100)
```

**Comment by jlaur** [comment]
[Still unstable](https://github.com/openhab/openhab-addons/actions/runs/12677468350/job/35332873035):
```
TEST org.openhab.binding.mqtt.homie.HomieImplementationTest#retrieveOneAttribute() <<< ERROR: 
Expected: is "3.0"
     but: was null
java.lang.AssertionError: 
Expected: is "3.0"
     but: was null
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
	at org.openhab.binding.mqtt.homie.HomieImplementationTest.retrieveOneAttribute(HomieImplementationTest.java:171)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at aQute.tester.bundle.engine.BundleDescriptor.executeChild(BundleDescriptor.java:49)
	at aQute.tester.bundle.engine.BundleEngine.lambda$executeBundle$7(BundleEngine.java:120)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at aQute.tester.bundle.engine.BundleEngine.executeBundle(BundleEngine.java:120)
	at aQute.tester.bundle.engine.BundleEngine.lambda$executeBundle$8(BundleEngine.java:133)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at aQute.tester.bundle.engine.BundleEngine.executeBundle(BundleEngine.java:133)
	at aQute.tester.bundle.engine.BundleEngine.lambda$execute$5(BundleEngine.java:100)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at aQute.tester.bundle.engine.BundleEngine.execute(BundleEngine.java:100)
org.openhab.binding.mqtt.homie [io.moquette.broker.DefaultMoquetteSslContextCreator] WARN : The key manager password is null or empty. The SSL context won't be initialized.
org.openhab.binding.mqtt.homie [io.moquette.broker.NewNettyAcceptor] ERROR : Can't initialize SSLHandler layer! Exiting, check your configuration of jks
org.openhab.binding.mqtt.ruuvigateway [io.moquette.broker.DefaultMoquetteSslContextCreator] WARN : The key manager password is null or empty. The SSL context won't be initialized.
org.openhab.binding.mqtt.ruuvigateway [io.moquette.broker.NewNettyAcceptor] ERROR : Can't initialize SSLHandler layer! Exiting, check your configuration of jks
org.openhab.binding.mqtt.homie [io.moquette.broker.Session] WARN : Received a PUBACK with not matching packetId
org.openhab.binding.mqtt.homie [io.moquette.broker.Session] WARN : Received a PUBACK with not matching packetId
org.openhab.binding.mqtt.homie [io.moquette.broker.Session] WARN : Received a PUBACK with not matching packetId
org.openhab.binding.mqtt.homie [io.moquette.broker.Session] WARN : Received a PUBACK with not matching packetId
org.openhab.binding.mqtt.homie [io.moquette.broker.Session] WARN : Received a PUBACK with not matching packetId
org.openhab.binding.mqtt.homie [io.moquette.broker.Session] WARN : Received a PUBACK with not matching packetId
org.openhab.binding.mqtt.homie [io.moquette.broker.Session] WARN : Received a PUBACK with not matching packetId
org.openhab.binding.mqtt.homie [io.moquette.broker.Session] WARN : Received a PUBACK with not matching packetId
org.openhab.binding.mqtt.homie [io.moquette.broker.Session] WARN : Received a PUBACK with not matching packetId
org.openhab.binding.mqtt.homie [io.moquette.broker.Session] WARN : Received a PUBACK with not matching packetId
org.openhab.binding.mqtt.homie [io.moquette.broker.Session] WARN : Received a PUBACK with not matching packetId
org.openhab.binding.mqtt.homie [io.moquette.broker.Session] WARN : Received a PUBACK with not matching packetId
org.openhab.binding.mqtt.homie [io.moquette.broker.Session] WARN : Received a PUBACK with not matching packetId
org.openhab.binding.mqtt.homie [io.moquette.broker.Session] WARN : Received a PUBACK with not matching packetId
org.openhab.binding.mqtt.homie [io.moquette.broker.Session] WARN : Received a PUBACK with not matching packetId
org.openhab.binding.mqtt.homie [io.moquette.broker.Session] WARN : Received a PUBACK with not matching packetId
org.openhab.binding.mqtt.homie [io.moquette.broker.Session] WARN : Received a PUBACK with not matching packetId
org.openhab.binding.mqtt.ruuvigateway [org.openhab.binding.mqtt.ruuvigateway.internal.handler.RuuviTagHandler] WARN : Using overridden timeout: 9000000
[INFO] 1 Error(s)
Error:  Error   : Exit code remote process 1: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/21.0.5-11/x64/bin/java -cp /home/runner/work/openhab-addons/openhab-addons/itests/org.openhab.binding.mqtt.homie.tests/target/test/tmp/testing/itest/cnf/cache/7.1.0/bnd-cache/biz.aQute.launcher/biz.aQute.launcher.pre.jar -Dlauncher.properties=/home/runner/work/openhab-addons/openhab-addons/itests/org.openhab.binding.mqtt.homie.tests/target/test/tmp/testing/itest/generated/launch10047460283604229009.properties -Djdk.util.zip.disableZip64ExtraFieldValidation=true -Dorg.osgi.service.http.port=37059 -DJETTY_AVAILABLE_PROCESSORS=4 --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.base/java.security=ALL-UNNAMED --add-opens=java.base/java.text=ALL-UNNAMED --add-opens=java.base/java.time=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.desktop/java.awt.font=ALL-UNNAMED --add-opens=java.naming/javax.naming.spi=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport.tcp=ALL-UNNAMED -Dio.netty.noUnsafe=true -Dmqttbroker.port=42617 -ea -Dlauncher.runpath=/home/runner/work/openhab-addons/openhab-addons/itests/org.openhab.binding.mqtt.homie.tests/target/test/tmp/testing/itest/cnf/cache/7.1.0/org.openhab.core.bom.runtime-index/org.eclipse.osgi-3.18.0.v20220516-2155.jar,/home/runner/work/openhab-addons/openhab-addons/itests/org.openhab.binding.mqtt.homie.tests/target/test/tmp/testing/itest/cnf/cache/7.1.0/bnd-cache/biz.aQute.launcher/biz.aQute.launcher-7.1.0.jar aQute.launcher.pre.EmbeddedLauncher
[INFO] Done SpotBugs Analysis....
[INFO] 
```
