### ISSUE TITLE
[tado] Server timeouts and HTTP 409 errors

### ISSUE THREAD

**Issue by andrewfg** [openhab/openhab-addons#12704]
Recently I have been observing errors from the tado binding. This is a placeholder to report the issue. But I am already investigating ways to solve them.

There are two potential causes (TBD)..
- Perhaps due to regressions caused by changes in recent PRs.
- Perhaps due to recent changes in the tado hub web server / resp. hub firmware.

Two types of errors have been observed..

1. HTTP 409 (Conflict) errors as shown in the log below..

```
2022-05-09 10:19:09.726 [WARN ] [ado.internal.handler.TadoZoneHandler] - Could not apply HVAC change on home 248302 and zone 1: Operation updateZoneOverlay failed with error 409
org.openhab.binding.tado.internal.api.ApiException: Operation updateZoneOverlay failed with error 409
	at org.openhab.binding.tado.internal.api.client.HomeApi.updateZoneOverlay(HomeApi.java:625) ~[?:?]
	at org.openhab.binding.tado.internal.handler.TadoZoneHandler.setOverlay(TadoZoneHandler.java:145) ~[?:?]
	at org.openhab.binding.tado.internal.TadoHvacChange.apply(TadoHvacChange.java:144) ~[?:?]
	at org.openhab.binding.tado.internal.handler.TadoZoneHandler.lambda$3(TadoZoneHandler.java:424) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

3. Socket timeout and DNS timeout errors as shown in the log below..

```
2022-05-09 10:24:37.668 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'tado:zone:g24:t07' changed from OFFLINE (COMMUNICATION_ERROR): Could not connect to server due to java.util.concurrent.TimeoutException: Total timeout 5000 ms elapsed to UNINITIALIZED
2022-05-09 10:24:37.685 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'tado:zone:g24:t07' changed from UNINITIALIZED to UNINITIALIZED (HANDLER_MISSING_ERROR)
2022-05-09 10:24:37.687 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'tado:zone:g24:t04' changed from OFFLINE (COMMUNICATION_ERROR): Could not connect to server due to java.util.concurrent.TimeoutException: Total timeout 5000 ms elapsed to UNINITIALIZED
2022-05-09 10:24:37.696 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'tado:zone:g24:t04' changed from UNINITIALIZED to UNINITIALIZED (HANDLER_MISSING_ERROR)
2022-05-09 10:24:37.697 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'tado:zone:g24:t01' changed from OFFLINE (COMMUNICATION_ERROR): Could not connect to server due to java.util.concurrent.TimeoutException: Total timeout 5000 ms elapsed to UNINITIALIZED
2022-05-09 10:24:37.707 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'tado:zone:g24:t01' changed from UNINITIALIZED to UNINITIALIZED (HANDLER_MISSING_ERROR)
2022-05-09 10:24:37.709 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'tado:zone:g24:t05' changed from OFFLINE (COMMUNICATION_ERROR): Could not connect to server due to java.util.concurrent.TimeoutException: DNS timeout 15000 ms to UNINITIALIZED
2022-05-09 10:24:37.720 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'tado:zone:g24:t05' changed from UNINITIALIZED to UNINITIALIZED (HANDLER_MISSING_ERROR)
2022-05-09 10:24:37.722 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'tado:zone:g24:t02' changed from OFFLINE (COMMUNICATION_ERROR): Could not connect to server due to java.util.concurrent.TimeoutException: DNS timeout 15000 ms to UNINITIALIZED
2022-05-09 10:24:37.734 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'tado:zone:g24:t02' changed from UNINITIALIZED to UNINITIALIZED (HANDLER_MISSING_ERROR)
2022-05-09 10:24:37.737 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'tado:zone:g24:t10' changed from OFFLINE (COMMUNICATION_ERROR): Could not connect to server due to java.util.concurrent.TimeoutException: DNS timeout 15000 ms to UNINITIALIZED
2022-05-09 10:24:37.748 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'tado:zone:g24:t10' changed from UNINITIALIZED to UNINITIALIZED (HANDLER_MISSING_ERROR)
2022-05-09 10:24:37.749 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'tado:zone:g24:t08' changed from OFFLINE (COMMUNICATION_ERROR): Could not connect to server due to java.util.concurrent.TimeoutException: Total timeout 5000 ms elapsed to UNINITIALIZED
```

**Comment by Freeride79** [comment]
@andrewfg Hello again ;-) I also have issues with communication errors of the tado binding. Maybe 3 errors during the last week. 
![grafik](https://user-images.githubusercontent.com/101657171/168460006-7951b971-4d7d-4c53-969e-cdae0600af9e.png)
![grafik](https://user-images.githubusercontent.com/101657171/168460041-0928679d-2ea6-40f5-a92c-056abec0a2c1.png)
Disabling and enabling again brings it back to Online
![grafik](https://user-images.githubusercontent.com/101657171/168460070-fd734e5f-9a8c-49ec-bcd1-1b7178ebda93.png)

**Comment by andrewfg** [comment]
@Freeride79 which Jar version are you using when you see this?

**Comment by Freeride79** [comment]
@andrewfg this was your jar from May 5th

**Comment by router-hub** [comment]
What was the reason for this error, btw?

**Comment by andrewfg** [comment]
> What was the reason for this error, btw?

I think that version of the binding was not doing proper consistency checks of the command payload against the capabilities schema that had been provided previously by the device. So those inconsistent commands were being rejected with an HTTP 409 error.
