### ISSUE TITLE
[rfxcom] Support for RFXtrx433XL firmware

### ISSUE THREAD

**Issue by ghost** [openhab/openhab-addons#13024]
## Expected Behavior

I have firmware version 1045  and hardware version 3.1

## Current Behavior

2022-06-26 21:59:29.564 [WARN ] [rnal.messages.RFXComInterfaceMessage] - The firmware type reported (19) isn't known to the RFXCom binding. Please raise an issue at https://github.com/openhab/openhab-addons/ to have it included.

2022-06-26 21:59:29.301 [ERROR] [internal.handler.RFXComBridgeHandler] - Connection to RFXCOM transceiver failed

org.openhab.binding.rfxcom.internal.exceptions.RFXComException: No serial port /dev/ttyUSB-rfxcom

	at org.openhab.binding.rfxcom.internal.connector.RFXComSerialConnector.connect(RFXComSerialConnector.java:61) ~[?:?]

	at org.openhab.binding.rfxcom.internal.handler.RFXComBridgeHandler.connect(RFXComBridgeHandler.java:211) ~[?:?]

	at org.openhab.binding.rfxcom.internal.handler.RFXComBridgeHandler.lambda$0(RFXComBridgeHandler.java:184) ~[?:?]

	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]

	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]

	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]

	at java.lang.Thread.run(Thread.java:829) [?:?]

## Steps to Reproduce (for Bugs)

1. Start or restart openhab and the message will apear
2.

## Your Environment

* Version used: (e.g., openHAB and add-on versions)
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...):
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...):

**Comment by lolodomo** [comment]
What model do you own and what firmware type did you install?

**Comment by lolodomo** [comment]
It may be the ProXL firmware?

**Comment by ajseesink** [comment]
I got the RFXtrx433XL with the current firmware version 1045. It's the latest firmware version. 
The message is that openhab sends is that it doesnt support the 1045 version (yet?) and asks me to raise an issue. So I did. My guess is that openhab rfxcom binding needs to be updated?

**Comment by lolodomo** [comment]
Yes this warning was to detect new firmware types, meaning those not officially supported by the binding. 
I do not know what is specific in this firmware and whether or not the API was updated. Unfortunately, the RFXCOM API is apparently no more public, at least I did not find any information on the RFXCOM website. 
Maybe the API changes are minor and the binding will work, difficult to say without any technical information. 
I would suggest you to test the binding anyway.

And someone having the specs should analyze them and update the binding if necessary. 

PS: Your logs also show another problem, you setup apparently an invalid serial port.

**Comment by ajseesink** [comment]
Thanks for the reply. 
I've seen the serial part thing and managed that one. That problem is gone.

**Comment by Mickroz** [comment]
i got the same problem with the same model.

**Comment by lolodomo** [comment]
This would require a contribution to support this new model/firmware.

**Comment by lolodomo** [comment]
Nothing new. A contributor developing this enhancement is still required and he will have yo contact RFXCOM to get the new API.

**Comment by wborn** [comment]
Maybe @martinvw or @paulianttila can have a look at this?

**Comment by martinvw** [comment]
I added it to the code,  but did not test it myself, I would expect it to just work, it is more like a safe guard:

https://download.martinvw.nl/org.openhab.binding.rfxcom-5.1.0-SNAPSHOT.13024.jar
