### ISSUE TITLE
[myq] JsonSyntaxException during login breaks binding operation

### ISSUE THREAD

**Issue by tlendacky** [openhab/openhab-addons#13181]
## Expected Behavior

Any exception processing a login should be caught so that the binding can retry later and continue working.

## Current Behavior

Sometimes a login will return information that results in a JsonSyntaxException:

```
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226) ~[?:?]
        at com.google.gson.Gson.fromJson(Gson.java:932) ~[?:?]
        at com.google.gson.Gson.fromJson(Gson.java:897) ~[?:?]
        at com.google.gson.Gson.fromJson(Gson.java:846) ~[?:?]
        at com.google.gson.Gson.fromJson(Gson.java:817) ~[?:?]
        at org.openhab.binding.myq.internal.handler.MyQAccountHandler.login(MyQAccountHandler.java:345) ~[?:?]
        at org.openhab.binding.myq.internal.handler.MyQAccountHandler.sendRequest(MyQAccountHandler.java:405) ~[?:?]
        at org.openhab.binding.myq.internal.handler.MyQAccountHandler.getAccounts(MyQAccountHandler.java:357) ~[?:?]
        at org.openhab.binding.myq.internal.handler.MyQAccountHandler.fetchData(MyQAccountHandler.java:285) ~[?:?]
        at org.openhab.binding.myq.internal.handler.MyQAccountHandler.normalPoll(MyQAccountHandler.java:275) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
```
Once this occurs, I have to restart openhab in order for the MyQ binding to function again.

## Possible Solution

Catch the JsonSyntaxException that can be thrown by fromJson() in the login() function of MyQAccountHandler.java and return a MyQCommunicationException()?

## Steps to Reproduce (for Bugs)

1. I can't reliably reproduce this, just every now and then the MyQ servers will return data from a login() that causes this.

## Context

It isn't always noticeable that this issue has occurred until you notice that MyQ says your garage doors are closed when they are really open, etc.

## Your Environment

* Version used: (e.g., openHAB and add-on versions): 3.2.0-1
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...): Java 11
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): Ubuntu 20.04

**Comment by digitaldan** [comment]
I think i have seen this as well and will take a look, thanks.

**Comment by Moxified** [comment]
I have also been experiencing this issue.  Disabling the bridge multiple times often brings it back or a restart of OH as previously mentioned.

**Comment by tlendacky** [comment]
Thanks, Dan, I'll give this a try.
