### ISSUE TITLE
[vosk] Missing native dependency

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-addons#13423]
@GiviMAD : after installing the snapshot 3089 (generated yesterday), I can see this warning at OH startup:
```
20:24:37.125 [WARN ] [voice.voskstt.internal.VoskSTTService] - Missing native dependency: Error looking up function 'vosk_recognizer_set_partial_words': /home/xxx/.cache/JNA/temp/jna2618161390205275901.tmp: undefined symbol: vosk_recognizer_set_partial_words
```
Any idea what is wrong ?

**Comment by GiviMAD** [comment]
I have this same error after updating the library, and I found a comment on the vosk issue tracker that said it's caused by not doing a clean install after the dependency upgrade. So I clean install the binding and the problem got solved.
Is maybe the CI using the cache of the previous build? If so it's maybe needed to clean the cache for that module.

**Comment by lolodomo** [comment]
I removed the `.cache` directory and restarted OH. Still the same warning.

**Comment by lolodomo** [comment]
Could it be my vosk model being outdated ?
I have not downloaded a new ZIP file since a long time.
I am using this file vosk-model-small-fr-0.22.zip

**Comment by GiviMAD** [comment]
> I removed the `.cache` directory and restarted OH. Still the same warning.

Sorry, I think I explained myself wrong, I was talking about the maven cache.

So what happened to me was:
I build the binding doing mvn install -pl org.openhab.binding.voskstt and that build gave that error, after that I rebuild with mvn clean install -pl org.openhab.binding.voskstt and that jar worked for me perfectly.
So I think the issue happened  on the build, not related to your local installation.

**Comment by GiviMAD** [comment]
This is the issue where I found the solution https://github.com/alphacep/vosk-api/issues/574

**Comment by lolodomo** [comment]
Ah ok. 
I am using the jar file from the kar file built last night. We should be sure that this one is working. 
I have not played with vosk. I guess that it doesn't work at all when we have this warning?

**Comment by GiviMAD** [comment]
No it doesn't work at all when that warning is shown.

**Comment by GiviMAD** [comment]
I'm not sure where that kar is built, I think that by Jenkins. In that case maybe we need someone with access to invalidate/delete de build cache for the Addons-repo.

**Comment by lolodomo** [comment]
Maybe @wborn can have an idea.

**Comment by wborn** [comment]
Maybe if you're using an ARM based computer the [libraries](https://github.com/wborn/openhab-addons/tree/main/bundles/org.openhab.voice.voskstt/src/main/resources) need to be updated for the [SDK upgrade](https://github.com/openhab/openhab-addons/pull/13391)?
If possible I would also not [embed JNA](https://github.com/wborn/openhab-addons/blob/4e860361c8b6458fe1e1f2c8a52830e3321877b1/bundles/org.openhab.voice.voskstt/pom.xml#L23-L29) since it will be automatically installed with https://github.com/openhab/openhab-core/pull/3049.

> This is the issue where I found the solution https://github.com/alphacep/vosk-api/issues/574

I would expect the updated libraries to be part of every release since 0.3.29. So clearing caches will not help. You can generate/compare the checksums of the libraries in the JARs generated by Jenkins to see if the correct libraries are packaged.

**Comment by lolodomo** [comment]
Hiu @GiviMAD 
I just installed the very last snapshot and I got that at startup:
```
10:04:53.367 [WARN ] [voice.voskstt.internal.VoskSTTService] - UnsatisfiedLinkError: /home/pi/.cache/JNA/temp/jna11425669424795407456.tmp: undefined symbol: __atomic_load_8
10:04:53.382 [ERROR] [voice.voskstt.internal.VoskSTTService] - bundle org.openhab.voice.voskstt:3.4.0.202210160416 (276)[org.openhab.voice.voskstt.internal.VoskSTTService(322)] : The activate method has thrown an exception
java.lang.NoClassDefFoundError: Could not initialize class org.vosk.LibVosk
        at org.vosk.Model.<init>(Model.java:11) ~[?:?]
        at org.openhab.voice.voskstt.internal.VoskSTTService.loadModel(VoskSTTService.java:191) ~[?:?]
        at org.openhab.voice.voskstt.internal.VoskSTTService.configChange(VoskSTTService.java:120) ~[?:?]
        at org.openhab.voice.voskstt.internal.VoskSTTService.activate(VoskSTTService.java:99) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.apache.felix.scr.impl.inject.methods.BaseMethod.invokeMethod(BaseMethod.java:244) ~[?:?]
        at org.apache.felix.scr.impl.inject.methods.BaseMethod.access$500(BaseMethod.java:41) ~[?:?]
        at org.apache.felix.scr.impl.inject.methods.BaseMethod$Resolved.invoke(BaseMethod.java:685) ~[?:?]
        at org.apache.felix.scr.impl.inject.methods.BaseMethod.invoke(BaseMethod.java:529) ~[?:?]
        at org.apache.felix.scr.impl.inject.methods.ActivateMethod.invoke(ActivateMethod.java:318) ~[?:?]
        at org.apache.felix.scr.impl.inject.methods.ActivateMethod.invoke(ActivateMethod.java:308) ~[?:?]
        at org.apache.felix.scr.impl.manager.SingleComponentManager.createImplementationObject(SingleComponentManager.java:354) ~[?:?]
        at org.apache.felix.scr.impl.manager.SingleComponentManager.createComponent(SingleComponentManager.java:115) ~[?:?]
        at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:1000) ~[?:?]
        at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:973) ~[?:?]
        at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:918) ~[?:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse$1.run(ServiceFactoryUse.java:220) ~[org.eclipse.osgi-3.17.200.jar:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.factoryGetService(ServiceFactoryUse.java:217) ~[org.eclipse.osgi-3.17.200.jar:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.getService(ServiceFactoryUse.java:118) ~[org.eclipse.osgi-3.17.200.jar:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceConsumer$2.getService(ServiceConsumer.java:48) ~[org.eclipse.osgi-3.17.200.jar:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.getService(ServiceRegistrationImpl.java:547) ~[org.eclipse.osgi-3.17.200.jar:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.getService(ServiceRegistry.java:533) ~[org.eclipse.osgi-3.17.200.jar:?]
        at org.eclipse.osgi.internal.framework.BundleContextImpl.getService(BundleContextImpl.java:655) ~[org.eclipse.osgi-3.17.200.jar:?]
        at org.apache.felix.scr.impl.manager.SingleRefPair.getServiceObject(SingleRefPair.java:88) ~[?:?]
        at org.apache.felix.scr.impl.inject.methods.BindMethod.getServiceObject(BindMethod.java:675) ~[?:?]
        at org.apache.felix.scr.impl.manager.DependencyManager.getServiceObject(DependencyManager.java:2556) ~[?:?]
        at org.apache.felix.scr.impl.manager.DependencyManager.doInvokeBindMethod(DependencyManager.java:2075) ~[?:?]
        at org.apache.felix.scr.impl.manager.DependencyManager.invokeBindMethod(DependencyManager.java:2058) ~[?:?]
        at org.apache.felix.scr.impl.manager.SingleComponentManager.invokeBindMethod(SingleComponentManager.java:443) ~[?:?]
        at org.apache.felix.scr.impl.manager.DependencyManager$MultipleDynamicCustomizer.addedService(DependencyManager.java:333) ~[?:?]
        at org.apache.felix.scr.impl.manager.DependencyManager$MultipleDynamicCustomizer.addedService(DependencyManager.java:301) ~[?:?]
        at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.customizerAdded(ServiceTracker.java:1200) ~[?:?]
        at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.customizerAdded(ServiceTracker.java:1121) ~[?:?]
        at org.apache.felix.scr.impl.manager.ServiceTracker$AbstractTracked.trackAdding(ServiceTracker.java:928) ~[?:?]
        at org.apache.felix.scr.impl.manager.ServiceTracker$AbstractTracked.track(ServiceTracker.java:864) ~[?:?]
        at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:1152) ~[?:?]
        at org.apache.felix.scr.impl.BundleComponentActivator$ListenerInfo.serviceChanged(BundleComponentActivator.java:114) ~[?:?]
        at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:120) ~[org.eclipse.osgi-3.17.200.jar:?]
        at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:956) ~[org.eclipse.osgi-3.17.200.jar:?]
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234) ~[org.eclipse.osgi-3.17.200.jar:?]
        at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151) ~[org.eclipse.osgi-3.17.200.jar:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:936) ~[org.eclipse.osgi-3.17.200.jar:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:873) ~[org.eclipse.osgi-3.17.200.jar:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:141) ~[org.eclipse.osgi-3.17.200.jar:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:261) ~[org.eclipse.osgi-3.17.200.jar:?]
        at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:495) ~[org.eclipse.osgi-3.17.200.jar:?]
        at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:929) ~[?:?]
        at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:915) ~[?:?]
        at org.apache.felix.scr.impl.manager.RegistrationManager.changeRegistration(RegistrationManager.java:133) ~[?:?]
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.registerService(AbstractComponentManager.java:984) ~[?:?]
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:752) ~[?:?]
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.enableInternal(AbstractComponentManager.java:674) ~[?:?]
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.enable(AbstractComponentManager.java:437) ~[?:?]
        at org.apache.felix.scr.impl.manager.ConfigurableComponentHolder.enableComponents(ConfigurableComponentHolder.java:667) ~[?:?]
        at org.apache.felix.scr.impl.BundleComponentActivator.initialEnable(BundleComponentActivator.java:305) ~[?:?]
        at org.apache.felix.scr.impl.Activator.loadComponents(Activator.java:554) ~[?:?]
        at org.apache.felix.scr.impl.Activator.access$200(Activator.java:70) ~[?:?]
        at org.apache.felix.scr.impl.Activator$ScrExtension.start(Activator.java:421) ~[?:?]
        at org.apache.felix.scr.impl.AbstractExtender.createExtension(AbstractExtender.java:196) ~[?:?]
        at org.apache.felix.scr.impl.AbstractExtender.modifiedBundle(AbstractExtender.java:169) ~[?:?]
        at org.apache.felix.scr.impl.AbstractExtender.modifiedBundle(AbstractExtender.java:49) ~[?:?]
        at org.osgi.util.tracker.BundleTracker$Tracked.customizerModified(BundleTracker.java:488) ~[osgi.core-7.0.0.jar:?]
        at org.osgi.util.tracker.BundleTracker$Tracked.customizerModified(BundleTracker.java:420) ~[osgi.core-7.0.0.jar:?]
        at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:232) ~[osgi.core-7.0.0.jar:?]
        at org.osgi.util.tracker.BundleTracker$Tracked.bundleChanged(BundleTracker.java:450) ~[osgi.core-7.0.0.jar:?]
        at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:944) ~[org.eclipse.osgi-3.17.200.jar:?]
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234) ~[org.eclipse.osgi-3.17.200.jar:?]
        at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151) ~[org.eclipse.osgi-3.17.200.jar:?]
        at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEventPrivileged(EquinoxEventPublisher.java:229) ~[org.eclipse.osgi-3.17.200.jar:?]
        at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:138) ~[org.eclipse.osgi-3.17.200.jar:?]
        at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:130) ~[org.eclipse.osgi-3.17.200.jar:?]
        at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor.publishModuleEvent(EquinoxContainerAdaptor.java:217) ~[org.eclipse.osgi-3.17.200.jar:?]
        at org.eclipse.osgi.container.Module.publishEvent(Module.java:499) ~[org.eclipse.osgi-3.17.200.jar:?]
        at org.eclipse.osgi.container.Module.start(Module.java:486) ~[org.eclipse.osgi-3.17.200.jar:?]
        at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:445) ~[org.eclipse.osgi-3.17.200.jar:?]
        at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:464) ~[org.eclipse.osgi-3.17.200.jar:?]
        at org.apache.karaf.features.internal.service.BundleInstallSupportImpl.startBundle(BundleInstallSupportImpl.java:165) ~[?:?]
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.startBundle(FeaturesServiceImpl.java:1160) ~[?:?]
        at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:1041) ~[?:?]
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1069) ~[?:?]
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.lambda$doProvisionInThread$13(FeaturesServiceImpl.java:1004) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
10:04:53.498 [WARN ] [.core.voice.internal.VoiceManagerImpl] - bundle org.openhab.core.voice:3.4.0.202210160306 (216)[org.openhab.core.voice.internal.VoiceManagerImpl(204)] : Could not get service from ref {org.openhab.core.voice.STTService}={noResultsMessage=Désolé, je n'ai pas compris, errorMessage=Désolé, un problème est survenu, service.id=547, service.bundleid=276, service.scope=bundle, component.name=org.openhab.voice.voskstt.internal.VoskSTTService, service.config.label=Vosk Speech-to-Text, component.id=322, service.config.factory=false, service.config.category=voice, service.config.description.uri=voice:voskstt, service.pid=[org.openhab.voice.voskstt, org.openhab.voice.voskstt]}
10:04:53.502 [WARN ] [.core.voice.internal.VoiceManagerImpl] - bundle org.openhab.core.voice:3.4.0.202210160306 (216)[org.openhab.core.voice.internal.VoiceManagerImpl(204)] : DependencyManager : invokeBindMethod : Service not available from service registry for ServiceReference {org.openhab.core.voice.STTService}={noResultsMessage=Désolé, je n'ai pas compris, errorMessage=Désolé, un problème est survenu, service.id=547, service.bundleid=276, service.scope=bundle, component.name=org.openhab.voice.voskstt.internal.VoskSTTService, service.config.label=Vosk Speech-to-Text, component.id=322, service.config.factory=false, service.config.category=voice, service.config.description.uri=voice:voskstt, service.pid=[org.openhab.voice.voskstt, org.openhab.voice.voskstt]} for reference STTService
```
Is it still the same issue ?

**Comment by GiviMAD** [comment]
> Hi @GiviMAD I just installed the very last snapshot and I got that at startup:
> 
> ```
> 10:04:53.367 [WARN ] [voice.voskstt.internal.VoskSTTService] - UnsatisfiedLinkError: /home/pi/.cache/JNA/temp/jna11425669424795407456.tmp: undefined symbol: __atomic_load_8
> 10:04:53.382 [ERROR] [voice.voskstt.internal.VoskSTTService] - bundle org.openhab.voice.voskstt:3.4.0.202210160416 (276)[org.openhab.voice.voskstt.internal.VoskSTTService(322)] : The activate method has thrown an exception
> java.lang.NoClassDefFoundError: Could not initialize class org.vosk.LibVosk
>         at org.vosk.Model.<init>(Model.java:11) ~[?:?]
>         at org.openhab.voice.voskstt.internal.VoskSTTService.loadModel(VoskSTTService.java:191) ~[?:?]
>         at org.openhab.voice.voskstt.internal.VoskSTTService.configChange(VoskSTTService.java:120) ~[?:?]
>         at org.openhab.voice.voskstt.internal.VoskSTTService.activate(VoskSTTService.java:99) ~[?:?]
>         at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
>         at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
>         at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
>         at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
>         at org.apache.felix.scr.impl.inject.methods.BaseMethod.invokeMethod(BaseMethod.java:244) ~[?:?]
>         at org.apache.felix.scr.impl.inject.methods.BaseMethod.access$500(BaseMethod.java:41) ~[?:?]
>         at org.apache.felix.scr.impl.inject.methods.BaseMethod$Resolved.invoke(BaseMethod.java:685) ~[?:?]
>         at org.apache.felix.scr.impl.inject.methods.BaseMethod.invoke(BaseMethod.java:529) ~[?:?]
>         at org.apache.felix.scr.impl.inject.methods.ActivateMethod.invoke(ActivateMethod.java:318) ~[?:?]
>         at org.apache.felix.scr.impl.inject.methods.ActivateMethod.invoke(ActivateMethod.java:308) ~[?:?]
>         at org.apache.felix.scr.impl.manager.SingleComponentManager.createImplementationObject(SingleComponentManager.java:354) ~[?:?]
>         at org.apache.felix.scr.impl.manager.SingleComponentManager.createComponent(SingleComponentManager.java:115) ~[?:?]
>         at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:1000) ~[?:?]
>         at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:973) ~[?:?]
>         at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:918) ~[?:?]
>         at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse$1.run(ServiceFactoryUse.java:220) ~[org.eclipse.osgi-3.17.200.jar:?]
>         at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
>         at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.factoryGetService(ServiceFactoryUse.java:217) ~[org.eclipse.osgi-3.17.200.jar:?]
>         at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.getService(ServiceFactoryUse.java:118) ~[org.eclipse.osgi-3.17.200.jar:?]
>         at org.eclipse.osgi.internal.serviceregistry.ServiceConsumer$2.getService(ServiceConsumer.java:48) ~[org.eclipse.osgi-3.17.200.jar:?]
>         at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.getService(ServiceRegistrationImpl.java:547) ~[org.eclipse.osgi-3.17.200.jar:?]
>         at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.getService(ServiceRegistry.java:533) ~[org.eclipse.osgi-3.17.200.jar:?]
>         at org.eclipse.osgi.internal.framework.BundleContextImpl.getService(BundleContextImpl.java:655) ~[org.eclipse.osgi-3.17.200.jar:?]
>         at org.apache.felix.scr.impl.manager.SingleRefPair.getServiceObject(SingleRefPair.java:88) ~[?:?]
>         at org.apache.felix.scr.impl.inject.methods.BindMethod.getServiceObject(BindMethod.java:675) ~[?:?]
>         at org.apache.felix.scr.impl.manager.DependencyManager.getServiceObject(DependencyManager.java:2556) ~[?:?]
>         at org.apache.felix.scr.impl.manager.DependencyManager.doInvokeBindMethod(DependencyManager.java:2075) ~[?:?]
>         at org.apache.felix.scr.impl.manager.DependencyManager.invokeBindMethod(DependencyManager.java:2058) ~[?:?]
>         at org.apache.felix.scr.impl.manager.SingleComponentManager.invokeBindMethod(SingleComponentManager.java:443) ~[?:?]
>         at org.apache.felix.scr.impl.manager.DependencyManager$MultipleDynamicCustomizer.addedService(DependencyManager.java:333) ~[?:?]
>         at org.apache.felix.scr.impl.manager.DependencyManager$MultipleDynamicCustomizer.addedService(DependencyManager.java:301) ~[?:?]
>         at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.customizerAdded(ServiceTracker.java:1200) ~[?:?]
>         at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.customizerAdded(ServiceTracker.java:1121) ~[?:?]
>         at org.apache.felix.scr.impl.manager.ServiceTracker$AbstractTracked.trackAdding(ServiceTracker.java:928) ~[?:?]
>         at org.apache.felix.scr.impl.manager.ServiceTracker$AbstractTracked.track(ServiceTracker.java:864) ~[?:?]
>         at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:1152) ~[?:?]
>         at org.apache.felix.scr.impl.BundleComponentActivator$ListenerInfo.serviceChanged(BundleComponentActivator.java:114) ~[?:?]
>         at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:120) ~[org.eclipse.osgi-3.17.200.jar:?]
>         at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:956) ~[org.eclipse.osgi-3.17.200.jar:?]
>         at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234) ~[org.eclipse.osgi-3.17.200.jar:?]
>         at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151) ~[org.eclipse.osgi-3.17.200.jar:?]
>         at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:936) ~[org.eclipse.osgi-3.17.200.jar:?]
>         at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:873) ~[org.eclipse.osgi-3.17.200.jar:?]
>         at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:141) ~[org.eclipse.osgi-3.17.200.jar:?]
>         at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:261) ~[org.eclipse.osgi-3.17.200.jar:?]
>         at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:495) ~[org.eclipse.osgi-3.17.200.jar:?]
>         at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:929) ~[?:?]
>         at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:915) ~[?:?]
>         at org.apache.felix.scr.impl.manager.RegistrationManager.changeRegistration(RegistrationManager.java:133) ~[?:?]
>         at org.apache.felix.scr.impl.manager.AbstractComponentManager.registerService(AbstractComponentManager.java:984) ~[?:?]
>         at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:752) ~[?:?]
>         at org.apache.felix.scr.impl.manager.AbstractComponentManager.enableInternal(AbstractComponentManager.java:674) ~[?:?]
>         at org.apache.felix.scr.impl.manager.AbstractComponentManager.enable(AbstractComponentManager.java:437) ~[?:?]
>         at org.apache.felix.scr.impl.manager.ConfigurableComponentHolder.enableComponents(ConfigurableComponentHolder.java:667) ~[?:?]
>         at org.apache.felix.scr.impl.BundleComponentActivator.initialEnable(BundleComponentActivator.java:305) ~[?:?]
>         at org.apache.felix.scr.impl.Activator.loadComponents(Activator.java:554) ~[?:?]
>         at org.apache.felix.scr.impl.Activator.access$200(Activator.java:70) ~[?:?]
>         at org.apache.felix.scr.impl.Activator$ScrExtension.start(Activator.java:421) ~[?:?]
>         at org.apache.felix.scr.impl.AbstractExtender.createExtension(AbstractExtender.java:196) ~[?:?]
>         at org.apache.felix.scr.impl.AbstractExtender.modifiedBundle(AbstractExtender.java:169) ~[?:?]
>         at org.apache.felix.scr.impl.AbstractExtender.modifiedBundle(AbstractExtender.java:49) ~[?:?]
>         at org.osgi.util.tracker.BundleTracker$Tracked.customizerModified(BundleTracker.java:488) ~[osgi.core-7.0.0.jar:?]
>         at org.osgi.util.tracker.BundleTracker$Tracked.customizerModified(BundleTracker.java:420) ~[osgi.core-7.0.0.jar:?]
>         at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:232) ~[osgi.core-7.0.0.jar:?]
>         at org.osgi.util.tracker.BundleTracker$Tracked.bundleChanged(BundleTracker.java:450) ~[osgi.core-7.0.0.jar:?]
>         at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:944) ~[org.eclipse.osgi-3.17.200.jar:?]
>         at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234) ~[org.eclipse.osgi-3.17.200.jar:?]
>         at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151) ~[org.eclipse.osgi-3.17.200.jar:?]
>         at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEventPrivileged(EquinoxEventPublisher.java:229) ~[org.eclipse.osgi-3.17.200.jar:?]
>         at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:138) ~[org.eclipse.osgi-3.17.200.jar:?]
>         at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:130) ~[org.eclipse.osgi-3.17.200.jar:?]
>         at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor.publishModuleEvent(EquinoxContainerAdaptor.java:217) ~[org.eclipse.osgi-3.17.200.jar:?]
>         at org.eclipse.osgi.container.Module.publishEvent(Module.java:499) ~[org.eclipse.osgi-3.17.200.jar:?]
>         at org.eclipse.osgi.container.Module.start(Module.java:486) ~[org.eclipse.osgi-3.17.200.jar:?]
>         at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:445) ~[org.eclipse.osgi-3.17.200.jar:?]
>         at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:464) ~[org.eclipse.osgi-3.17.200.jar:?]
>         at org.apache.karaf.features.internal.service.BundleInstallSupportImpl.startBundle(BundleInstallSupportImpl.java:165) ~[?:?]
>         at org.apache.karaf.features.internal.service.FeaturesServiceImpl.startBundle(FeaturesServiceImpl.java:1160) ~[?:?]
>         at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:1041) ~[?:?]
>         at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1069) ~[?:?]
>         at org.apache.karaf.features.internal.service.FeaturesServiceImpl.lambda$doProvisionInThread$13(FeaturesServiceImpl.java:1004) ~[?:?]
>         at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
>         at java.lang.Thread.run(Thread.java:834) [?:?]
> 10:04:53.498 [WARN ] [.core.voice.internal.VoiceManagerImpl] - bundle org.openhab.core.voice:3.4.0.202210160306 (216)[org.openhab.core.voice.internal.VoiceManagerImpl(204)] : Could not get service from ref {org.openhab.core.voice.STTService}={noResultsMessage=Désolé, je n'ai pas compris, errorMessage=Désolé, un problème est survenu, service.id=547, service.bundleid=276, service.scope=bundle, component.name=org.openhab.voice.voskstt.internal.VoskSTTService, service.config.label=Vosk Speech-to-Text, component.id=322, service.config.factory=false, service.config.category=voice, service.config.description.uri=voice:voskstt, service.pid=[org.openhab.voice.voskstt, org.openhab.voice.voskstt]}
> 10:04:53.502 [WARN ] [.core.voice.internal.VoiceManagerImpl] - bundle org.openhab.core.voice:3.4.0.202210160306 (216)[org.openhab.core.voice.internal.VoiceManagerImpl(204)] : DependencyManager : invokeBindMethod : Service not available from service registry for ServiceReference {org.openhab.core.voice.STTService}={noResultsMessage=Désolé, je n'ai pas compris, errorMessage=Désolé, un problème est survenu, service.id=547, service.bundleid=276, service.scope=bundle, component.name=org.openhab.voice.voskstt.internal.VoskSTTService, service.config.label=Vosk Speech-to-Text, component.id=322, service.config.factory=false, service.config.category=voice, service.config.description.uri=voice:voskstt, service.pid=[org.openhab.voice.voskstt, org.openhab.voice.voskstt]} for reference STTService
> ```
> 
> Is it still the same issue ?

@lolodomo Can you try to install the libatomic? 
```apt install libatomic1```
Because I'm using the snapshot version right now and it seems to work for me.

Other idea will be to remove the /home/pi/.cache/JNA directory. I'm running on docker so this directory is not persistent for me. Maybe is related to the error.

**Comment by lolodomo** [comment]
Removing the `.cache/JNA` directory does not help.

**Comment by GiviMAD** [comment]
```
bundle:list -s | grep vosk
272 │ Active │  80 │ 3.4.0.202210150417     │ org.openhab.voice.voskstt
```
I'm using this one on the arm64 Debian image, with libatomic1 installed.
Just to check, are you running in armv7 or arm64?
The only idea I have left is to stop openHAB remove the cache and tmp dir from the userdata and start it again, because I did it recently, but I don't think it will work.

**Comment by GiviMAD** [comment]
After searching in google that problem seems related to missed libatomic lib.

**Comment by lolodomo** [comment]
openHAB is run on a RPI 3. Not sure if this is armv7 or arm64.

> After searching in google that problem seems related to missed libatomic lib.

If something must be installed, this must be documented in the README.
What is strange is that it was not necessary in the past.

**Comment by GiviMAD** [comment]
Maybe I messed-up replacing the armv7 binary :S
i'm checking...

**Comment by GiviMAD** [comment]
```uname -m```
will show your architecture.

**Comment by lolodomo** [comment]
> `uname -m`
> will show your architecture.

armv7l

**Comment by GiviMAD** [comment]
Can you try the jar from this pr when it gets built? https://github.com/openhab/openhab-addons/pull/13556
The file is different but it do not match with the arm64 binary either so I think it was due to some kind of download error, as I still have the previous download folder and the version was the right one, so not sure what happened :S
