### ISSUE TITLE
[gce] Dynamic creation of channel prevents usage of .things file

### ISSUE THREAD

**Issue by clinique** [openhab/openhab-addons#13522]
## Expected Behavior
Thing should be created without error message, even if it is declared in a things file.

## Current Behavior
Declaring the IPX thing in a things file conflicts with dynamic creation of channels because the creation does not take in account already existing channels.

## Possible Solution
Take in account existing channels when defining dynamically created once.

## Steps to Reproduce (for Bugs)
1. Create a things file : 
```
Thing gce:ipx800v3:ipx "GCE IPX800" @ "node0" [hostname="192.168.0.244", portNumber=9870] 
{
	Channels:
		Type relay : relay#1 [       // Actionneur porte de garage
			pulse=true    
		]
}
```
2. Save the things file
3. Look at openhab.log : 
```
2022-10-09 09:33:35.534 [ERROR] [nal.common.AbstractInvocationHandler] - An error occurred while calling method 'ThingHandler.initialize()' on 'org.openhab.binding.gce.internal.handler.Ipx800v3Handler@620bb655': Duplicate channels gce:ipx800v3:ipx:relay#1
java.lang.IllegalArgumentException: Duplicate channels gce:ipx800v3:ipx:relay#1
	at org.openhab.core.thing.util.ThingHelper.ensureUniqueChannels(ThingHelper.java:152) ~[?:?]
	at org.openhab.core.thing.util.ThingHelper.ensureUniqueChannels(ThingHelper.java:128) ~[?:?]
	at org.openhab.core.thing.binding.builder.ThingBuilder.withChannels(ThingBuilder.java:86) ~[?:?]
	at org.openhab.binding.gce.internal.handler.Ipx800v3Handler.discoverAttributes(Ipx800v3Handler.java:174) ~[?:?]
	at org.openhab.binding.gce.internal.handler.Ipx800v3Handler.initialize(Ipx800v3Handler.java:124) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor87.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.openhab.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:154) [bundleFile:?]
	at org.openhab.core.internal.common.Invocation.call(Invocation.java:52) [bundleFile:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
2022-10-09 09:33:35.589 [ERROR] [core.thing.internal.ThingManagerImpl] - Exception occurred while initializing handler of thing 'gce:ipx800v3:ipx': Duplicate channels gce:ipx800v3:ipx:relay#1
java.lang.IllegalArgumentException: Duplicate channels gce:ipx800v3:ipx:relay#1
	at org.openhab.core.thing.util.ThingHelper.ensureUniqueChannels(ThingHelper.java:152) ~[?:?]
	at org.openhab.core.thing.util.ThingHelper.ensureUniqueChannels(ThingHelper.java:128) ~[?:?]
	at org.openhab.core.thing.binding.builder.ThingBuilder.withChannels(ThingBuilder.java:86) ~[?:?]
	at org.openhab.binding.gce.internal.handler.Ipx800v3Handler.discoverAttributes(Ipx800v3Handler.java:174) ~[?:?]
	at org.openhab.binding.gce.internal.handler.Ipx800v3Handler.initialize(Ipx800v3Handler.java:124) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor87.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.openhab.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:154) [bundleFile:?]
	at org.openhab.core.internal.common.Invocation.call(Invocation.java:52) [bundleFile:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]

```

**Comment by lolodomo** [comment]
Fixed by #13526
