### ISSUE TITLE
[nest] WWNThermostatHandlerTest unstable

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-addons#13525]
This test failed in: https://github.com/openhab/openhab-addons/actions/runs/3204310203/jobs/5235448304

```
TEST org.openhab.binding.nest.internal.wwn.handler.WWNThermostatHandlerTest#handleFanTimerActiveCommands() <<< ERROR: 
Expected: is "false"
     but: was "true"
java.lang.AssertionError: 
Expected: is "false"
     but: was "true"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
	at org.openhab.binding.nest.internal.wwn.handler.WWNThingHandlerOSGiTest.lambda$13(WWNThingHandlerOSGiTest.java:350)
	at org.openhab.core.test.java.JavaTest.waitForAssert(JavaTest.java:245)
	at org.openhab.core.test.java.JavaTest.waitForAssert(JavaTest.java:213)
	at org.openhab.core.test.java.JavaTest.waitForAssert(JavaTest.java:166)
	at org.openhab.binding.nest.internal.wwn.handler.WWNThingHandlerOSGiTest.assertNestApiPropertyState(WWNThingHandlerOSGiTest.java:350)
	at org.openhab.binding.nest.internal.wwn.handler.WWNThermostatHandlerTest.handleFanTimerActiveCommands(WWNThermostatHandlerTest.java:186)
```

**Comment by wborn** [comment]
Another one: https://github.com/openhab/openhab-addons/actions/runs/3101529683/jobs/5022987195

```
TEST org.openhab.binding.nest.internal.wwn.handler.WWNThermostatHandlerTest#handleFanTimerDurationCommands() <<< ERROR: 
Expected: is "30"
     but: was "15"
java.lang.AssertionError: 
Expected: is "30"
     but: was "15"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
	at org.openhab.binding.nest.internal.wwn.handler.WWNThingHandlerOSGiTest.lambda$13(WWNThingHandlerOSGiTest.java:350)
```

**Comment by wborn** [comment]
Maybe #14642 makes it more stable!
