### ISSUE TITLE
[systeminfo] SysteminfoOSGiTest unstable

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-addons#13524]
This test failed in: https://github.com/openhab/openhab-addons/actions/runs/3213563417/jobs/5253323286

```
TEST org.openhab.binding.systeminfo.test.SysteminfoOSGiTest#assertMediumPriorityChannelIsUpdated() <<< ERROR: 
Expected: is <UNDEF>
     but: was <NULL>
java.lang.AssertionError: 
Expected: is <UNDEF>
     but: was <NULL>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
	at org.openhab.binding.systeminfo.test.SysteminfoOSGiTest.lambda$4(SysteminfoOSGiTest.java:267)
	at org.openhab.core.test.java.JavaTest.waitForAssert(JavaTest.java:245)
	at org.openhab.core.test.java.JavaTest.waitForAssert(JavaTest.java:213)
	at org.openhab.core.test.java.JavaTest.waitForAssert(JavaTest.java:177)
	at org.openhab.binding.systeminfo.test.SysteminfoOSGiTest.assertItemState(SysteminfoOSGiTest.java:265)
	at org.openhab.binding.systeminfo.test.SysteminfoOSGiTest.assertMediumPriorityChannelIsUpdated(SysteminfoOSGiTest.java:336)
```

This test failed in: https://github.com/openhab/openhab-addons/actions/runs/3195031635/jobs/5215227925

```
TEST org.openhab.binding.systeminfo.test.SysteminfoOSGiTest#assertChannelCpuDescriptionIsUpdated() <<< ERROR: 
Expected: is <Mocked Cpu Descr>
     but: was <NULL>
java.lang.AssertionError: 
Expected: is <Mocked Cpu Descr>
     but: was <NULL>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
	at org.openhab.binding.systeminfo.test.SysteminfoOSGiTest.lambda$4(SysteminfoOSGiTest.java:267)
	at org.openhab.core.test.java.JavaTest.waitForAssert(JavaTest.java:245)
	at org.openhab.core.test.java.JavaTest.waitForAssert(JavaTest.java:213)
	at org.openhab.core.test.java.JavaTest.waitForAssert(JavaTest.java:177)
	at org.openhab.binding.systeminfo.test.SysteminfoOSGiTest.assertItemState(SysteminfoOSGiTest.java:265)
	at org.openhab.binding.systeminfo.test.SysteminfoOSGiTest.assertChannelCpuDescriptionIsUpdated(SysteminfoOSGiTest.java:431)
```

**Comment by wborn** [comment]
Can you have a look at this @svilenvul?

**Comment by mherwege** [comment]
@wborn @svilenvul Is this still an issue after the [#13562](https://github.com/openhab/openhab-addons/pull/13562) merge?

Note there is a follow-up PR [#13804](https://github.com/openhab/openhab-addons/pull/13804) intended to convert the channels to QuantityType that will also include changes to the tests. However, I am struggling there to make Number:DataAmount conversions work. See also [#13709](https://github.com/openhab/openhab-addons/issues/13709). I didn’t figure out what is wrong and I don’t think it is binding dependent. Unit conversions with DataAmount seem to fail.

**Comment by jlaur** [comment]
Newest example here: https://github.com/openhab/openhab-addons/actions/runs/3722131599/jobs/6312740428

**Comment by mherwege** [comment]
@jlaur In that same run, also the ntp test fails. The nest test seems to generate an error, but it is then swallowed by the test and not returned as a failure.
I have the impression there are timing issues with all of these. The tests will wait for something to get a specific value, but will time out of this does not happen, evidenced by the value being null. We could lengthen the timeout, but I am not sure this is the right thing to do.
