### ISSUE TITLE
[smartmeter] TestMeterReading unstable

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-addons#13530]
This test failed in: https://github.com/wborn/openhab-addons/actions/runs/3211692034/jobs/5250039186

```
[ERROR] Tests run: 4, Failures: 3, Errors: 0, Skipped: 0, Time elapsed: 32.547 s <<< FAILURE! - in org.openhab.binding.smartmeter.TestMeterReading
[ERROR] org.openhab.binding.smartmeter.TestMeterReading.testRetryHandling  Time elapsed: 7.636 s  <<< FAILURE!
org.mockito.exceptions.verification.WantedButNotInvoked: 

Wanted but not invoked:
meterValueListener.errorOccurred(<any>);
-> at org.openhab.binding.smartmeter.TestMeterReading.testRetryHandling(TestMeterReading.java:80)
Actually, there were zero interactions with this mock.

	at org.openhab.binding.smartmeter.TestMeterReading.testRetryHandling(TestMeterReading.java:80)

[ERROR] org.openhab.binding.smartmeter.TestMeterReading.testContinousReading  Time elapsed: 5.83 s  <<< FAILURE!
org.mockito.exceptions.verification.TooFewActualInvocations: 

meterValueListener.valueChanged(<any>);
Wanted 5 times:
-> at org.openhab.binding.smartmeter.TestMeterReading.testContinousReading(TestMeterReading.java:61)
But was 4 times:
-> at org.openhab.binding.smartmeter.internal.MeterDevice.lambda$9(MeterDevice.java:220)
-> at org.openhab.binding.smartmeter.internal.MeterDevice.lambda$9(MeterDevice.java:220)
-> at org.openhab.binding.smartmeter.internal.MeterDevice.lambda$9(MeterDevice.java:220)
-> at org.openhab.binding.smartmeter.internal.MeterDevice.lambda$9(MeterDevice.java:220)

	at org.openhab.binding.smartmeter.TestMeterReading.testContinousReading(TestMeterReading.java:61)

[ERROR] org.openhab.binding.smartmeter.TestMeterReading.testTimeoutHandling  Time elapsed: 8.659 s  <<< FAILURE!
org.mockito.exceptions.verification.WantedButNotInvoked: 

Wanted but not invoked:
meterValueListener.errorOccurred(
    <any java.util.concurrent.TimeoutException>
);
-> at org.openhab.binding.smartmeter.TestMeterReading.testTimeoutHandling(TestMeterReading.java:103)
Actually, there were zero interactions with this mock.

	at org.openhab.binding.smartmeter.TestMeterReading.testTimeoutHandling(TestMeterReading.java:103)
```

**Comment by wborn** [comment]
Can you have a look at this @msteigenberger?

**Comment by msteigenberger** [comment]
This is a timing related Test. It is working fine in my environment. I would increase the timing constraints a bit in order to be on the safe side.
