### ISSUE TITLE
[hue] Binding broken until you update the new protocol setting to "http" (bridge V1)

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-addons#13586]
I just installed snapshot 3143 containing the PR #11842 merged yesterday.
The binding does no more initialize properly:
```
09:32:18.362 [ERROR] [connection.HueTlsTrustManagerProvider] - An unexpected exception occurred - returning a TrustAllTrustManager: java.net.ConnectException: Connexion refusée (Connection refused)
org.openhab.core.io.net.http.PEMTrustManager$CertificateInstantiationException: java.net.ConnectException: Connexion refusée (Connection refused)
        at org.openhab.core.io.net.http.PEMTrustManager.getPEMCertificateFromServer(PEMTrustManager.java:220) ~[bundleFile:?]
        at org.openhab.core.io.net.http.PEMTrustManager.getInstanceFromServer(PEMTrustManager.java:131) ~[bundleFile:?]
        at org.openhab.core.io.net.http.PEMTrustManager.getInstanceFromServer(PEMTrustManager.java:116) ~[bundleFile:?]
        at org.openhab.binding.hue.internal.connection.HueTlsTrustManagerProvider.getTrustManager(HueTlsTrustManagerProvider.java:63) [bundleFile:?]
        at org.openhab.core.io.net.http.internal.ExtensibleTrustManagerImpl.addTlsTrustManagerProvider(ExtensibleTrustManagerImpl.java:220) [bundleFile:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.apache.felix.scr.impl.inject.methods.BaseMethod.invokeMethod(BaseMethod.java:244) [bundleFile:?]
        at org.apache.felix.scr.impl.inject.methods.BaseMethod.access$500(BaseMethod.java:41) [bundleFile:?]
        at org.apache.felix.scr.impl.inject.methods.BaseMethod$Resolved.invoke(BaseMethod.java:685) [bundleFile:?]
        at org.apache.felix.scr.impl.inject.methods.BaseMethod.invoke(BaseMethod.java:529) [bundleFile:?]
        at org.apache.felix.scr.impl.inject.methods.BindMethod.invoke(BindMethod.java:42) [bundleFile:?]
        at org.apache.felix.scr.impl.manager.DependencyManager.doInvokeBindMethod(DependencyManager.java:2083) [bundleFile:?]
        at org.apache.felix.scr.impl.manager.DependencyManager.invokeBindMethod(DependencyManager.java:2058) [bundleFile:?]
        at org.apache.felix.scr.impl.manager.SingleComponentManager.invokeBindMethod(SingleComponentManager.java:443) [bundleFile:?]
        at org.apache.felix.scr.impl.manager.DependencyManager$MultipleDynamicCustomizer.addedService(DependencyManager.java:333) [bundleFile:?]
        at org.apache.felix.scr.impl.manager.DependencyManager$MultipleDynamicCustomizer.addedService(DependencyManager.java:301) [bundleFile:?]
        at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.customizerAdded(ServiceTracker.java:1200) [bundleFile:?]
        at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.customizerAdded(ServiceTracker.java:1121) [bundleFile:?]
        at org.apache.felix.scr.impl.manager.ServiceTracker$AbstractTracked.trackAdding(ServiceTracker.java:928) [bundleFile:?]
        at org.apache.felix.scr.impl.manager.ServiceTracker$AbstractTracked.track(ServiceTracker.java:864) [bundleFile:?]
        at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:1152) [bundleFile:?]
        at org.apache.felix.scr.impl.BundleComponentActivator$ListenerInfo.serviceChanged(BundleComponentActivator.java:114) [bundleFile:?]
        at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:120) [org.eclipse.osgi-3.17.200.jar:?]
        at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:956) [org.eclipse.osgi-3.17.200.jar:?]
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234) [org.eclipse.osgi-3.17.200.jar:?]
        at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151) [org.eclipse.osgi-3.17.200.jar:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:936) [org.eclipse.osgi-3.17.200.jar:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:873) [org.eclipse.osgi-3.17.200.jar:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:141) [org.eclipse.osgi-3.17.200.jar:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:261) [org.eclipse.osgi-3.17.200.jar:?]
        at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:495) [org.eclipse.osgi-3.17.200.jar:?]
        at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:514) [org.eclipse.osgi-3.17.200.jar:?]
        at org.openhab.binding.hue.internal.handler.HueBridgeHandler.initialize(HueBridgeHandler.java:713) [bundleFile:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.openhab.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:154) [bundleFile:?]
        at org.openhab.core.internal.common.Invocation.call(Invocation.java:52) [bundleFile:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.net.ConnectException: Connexion refusée (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:?]
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399) ~[?:?]
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242) ~[?:?]
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224) ~[?:?]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403) ~[?:?]
        at java.net.Socket.connect(Socket.java:609) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:289) ~[?:?]
        at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173) ~[?:?]
        at sun.net.NetworkClient.doConnect(NetworkClient.java:182) ~[?:?]
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:474) ~[?:?]
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:569) ~[?:?]
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265) ~[?:?]
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:372) ~[?:?]
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081) ~[?:?]
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177) ~[?:?]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:168) ~[?:?]
        at org.openhab.core.io.net.http.PEMTrustManager.getPEMCertificateFromServer(PEMTrustManager.java:209) ~[bundleFile:?]
        ... 45 more
```
The bridge thing remains in status UNKNOWN.

**Comment by lolodomo** [comment]
Fallback to snapshot 3135 and the hue binding is working again.
This is clearly the PR #11842 which broke something.
@cweitkamp @jlaur @andrewfg for information

**Comment by jlaur** [comment]
Which Hue bridge generation?

**Comment by lolodomo** [comment]
Starting looking at the code, it is associated to the HTTPS protocol which is now the default protocol.
Is HTTPS compatible with bridge V1 ?
Maybe the default value for this new configuration parameter should have been set to HTTP for backward compatibility ?
Anyway, the error should be handled in a better way to provide real information to the user (status UNKNOW is not enough).

I will try again later today switching to HTTP protocol to see if the binding is working without HTTPS.

**Comment by lolodomo** [comment]
> Which Hue bridge generation?

V1

**Comment by lolodomo** [comment]
In case bridge V1 does not support HTTPS, the binding should simply implement a fallback to HTTP?

**Comment by lolodomo** [comment]
The binding seems to work again after updating the protocol setting to "http".

So I see two problems:

1. default value not working for bridge V1
2. no exception caught to inform the user to switch to HTTP

**Comment by jlaur** [comment]
It's easily reproducible without a V1 bridge by setting `ipAddress` to some host refusing connections on port 443. In this case bridge should be offline with description from exception ("Connection refused").

Regarding default value I'm in doubt. For V1 bridge we should obviously use http, but for the V2 bridge, https would be the better default as otherwise new users would use the insecure protocol by default, and might never notice or change this. I wonder if it would be feasible to detect the bridge/API version?

**Comment by jlaur** [comment]
Also to consider regarding default protocol: https://developers.meethue.com/new-hue-api/ - "HTTP has been replaced by [HTTPS](https://developers.meethue.com/develop/application-design-guidance/using-https/) since November 2018. **The V2 API does not support HTTP, but also for the V1 API it will be blocked when all bridges have received Signify signed certificates**."

So right now v1 is broken by the new default, but eventually v2 will be broken if default is https.

**Comment by lolodomo** [comment]
From the link you provided, I read nothing saying API V1 is only HTTP.

**Comment by jlaur** [comment]
It says that V1 API (currently implemented in openHAB) will eventually be blocked from using HTTP when all (V2) bridges have received new certificates.

Can you try to get configuration values from your bridge? See https://developers.meethue.com/develop/hue-api/7-configuration-api/.

GET: `/api/<username>/config`

Response from my V2 bridge:

```json
{
    "name": "Philips hue",
    "zigbeechannel": 25,
    "bridgeid": "xxx",
    "mac": "xxx",
    "dhcp": true,
    "ipaddress": "192.168.0.251",
    "netmask": "255.255.255.0",
    "gateway": "192.168.0.254",
    "proxyaddress": "none",
    "proxyport": 0,
    "UTC": "2022-10-23T14:29:56",
    "localtime": "2022-10-23T16:29:56",
    "timezone": "Europe/Copenhagen",
    "modelid": "BSB002",
    "datastoreversion": "131",
    "swversion": "1953188020",
    "apiversion": "1.53.0",
    "swupdate": {
        "updatestate": 1,
        "checkforupdate": false,
        "devicetypes": {
            "bridge": false,
            "lights": [],
            "sensors": []
        },
        "url": "",
        "text": "",
        "notify": true
    },
    "swupdate2": {
        "checkforupdate": false,
        "lastchange": "2022-09-26T16:37:29",
        "bridge": {
            "state": "noupdates",
            "lastinstall": "2022-09-26T15:51:55"
        },
        "state": "transferring",
        "autoinstall": {
            "updatetime": "T14:00:00",
            "on": false
        }
    },
    "linkbutton": false,
    "portalservices": true,
    "portalconnection": "connecting",
    "portalstate": {
        "signedon": true,
        "incoming": false,
        "outgoing": false,
        "communication": "disconnected"
    },
    "internetservices": {
        "internet": "connected",
        "remoteaccess": "connected",
        "time": "connected",
        "swupdate": "connected"
    },
    "factorynew": false,
    "replacesbridgeid": null,
    "backup": {
        "status": "idle",
        "errorcode": 0
    },
    "starterkitid": "",
    "whitelist": {
        "..."
    }
}
```

**Comment by andrewfg** [comment]
^
It should be possible for the binding to query the bridge firmware version, using one HTTP call to start with, and if it is below the f/w version for V1 hubs, default to continue using HTTP, or if it is above the f/w version for V2 hubs, then default to using HTTPS.

**Comment by jlaur** [comment]
> ^ It should be possible for the binding to query the bridge firmware version, using one HTTP call to start with, and if it is below the f/w version for V1 hubs, default to continue using HTTP, or if it is above the f/w version for V2 hubs, then default to using HTTPS.

Yes, that's why I'm interested in the above information from a V1 bridge. Mentioned in release notes:
https://www.philips-hue.com/en-us/support/release-notes/bridge

```
June 28, 2018
Firmware 1806051111 (Bridge V2) 

Beta release of HTTPS connection on the bridge and SDK
Various stability and performance improvements

May 15, 2018
Firmware 1804201116 (Bridge V2)

(only released in NL, GB and CAN)

Beta release of HTTPS connection on the bridge and SDK
Various stability and performance improvements
```

From my bridge:
`"swversion": "1953188020",`

this corresponds to the latest version in the release notes. So if we can get confirmation that swversion of @lolodomo's bridge is < 1804201116, and we can assume that this version is a sequential number, I believe we could query this once and use http as default if version < 1806051111.

**Comment by andrewfg** [comment]
@jlaur I was editing my prior post while you posted your message above, so please scroll up to see my edited post..

**Comment by andrewfg** [comment]
PS from the Philips documentation the cutoff version for CLIP 2 is >=1948086000

**Comment by lolodomo** [comment]
> Hoping for 01043155 as a result. :-)

Bingo ;)

No need to run any API, the information are only provided by the binding as thing properties ;)

![image](https://user-images.githubusercontent.com/10186704/197402467-660831d3-e913-4bbd-b44d-0a9bbb73d595.png)

**Comment by jlaur** [comment]
@lolodomo - I don't see those properties, so either because of V2 or because I have file-based configuration:
![image](https://user-images.githubusercontent.com/19519842/197402719-74d854e0-1f68-4500-8220-4a852345c948.png)

So this would need to be fixed also. But I think we are getting closer to a solution.

**Comment by jlaur** [comment]
@andrewfg - 01043155 was the last firmware for V1 bridge. You might be mistaking V1/V2 API with V1/V2 bridge.

**Comment by lolodomo** [comment]
> I don't see those properties, so either because of V2 or because I have file-based configuration:

File-based configuration on my side.

**Comment by andrewfg** [comment]
> 01043155 was the last firmware for V1 bridge. You might be mistaking V1/V2 API with V1/V2 bridge.

@jlaur I am referring to this..

https://developers.meethue.com/develop/hue-api-v2/migration-guide-to-the-new-hue-api/

![image](https://user-images.githubusercontent.com/893994/197405509-59d46491-721b-4d4e-9a80-90f6121a6bde.png)

**Comment by jlaur** [comment]
@andrewfg - okay, thanks. This confirms that `/api/config` for checking `swversion` is a correct approach. However, to detect bridge v1 or v2 we cannot use the mentioned version number for CLIPv2 API. Well, we could still use it, but the bridge supported HTTPS even before that version, so we might as well enable HTTPS as default since its introduction.

**Comment by andrewfg** [comment]
> but the bridge supported HTTPS even before that version,

Ok, I see your point. Perhaps an easy way out would be to try one HTTPS API call, and if it fails, downgrade automatically to HTTP (to not break functionality), and also perhaps log a warning to the user.

**Comment by jlaur** [comment]
@lolodomo - I found the code setting these properties:
https://github.com/openhab/openhab-addons/blob/42d93c3b970bdd81496b25e2c3dadcaf27707878/bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueBridgeHandler.java#L759-L763

So I tried to pause and resume the thing, and after that all properties were set. I'll try to see if I can figure out what might have happened.

**Comment by jlaur** [comment]
@lolodomo - okay, that was easy. After changing `ipAddress` configuration parameter to something else and then back again, the properties were lost. I'll provide a quick PR for that.

**Comment by jlaur** [comment]
In order to use the `/api/config` endpoint for checking `swversion`, we need to use either HTTP or HTTPS, so it's kind of a chicken or egg problem.

**Comment by lolodomo** [comment]
What do we decide finally? 
I think we have to change/improve something before next 3.4 milestone is released.

**Comment by jlaur** [comment]
> What do we decide finally? I think we have to change/improve something before next 3.4 milestone is released.

My input after the investigations above: Keep **HTTPS** as **default protocol**. If it fails, mark bridge as **OFFLINE** with a description that "HTTPS secure connection failed" and log a warning advising user to change configuration to HTTP when using a V1 bridge (if it's not a V1 bridge something else is wrong, so we might need a bug report).

This way we would have [security by default](https://en.wikipedia.org/wiki/Secure_by_default) and default settings would ready for Signify pulling the plug on HTTP on V2 bridges. We would avoid silently reverting to HTTP without users noticing. I think the decision to revert to HTTP should be manually taken by the user. We should also add a note about this breaking change for bridge V1 users.

Unfortunately I don't know how to implement this fallback or even handle the exception. Exception is thrown from core after calling interface method in binding, IIRC.

@cweitkamp - do you have any input?

**Comment by lolodomo** [comment]
> My input after the investigations above: Keep **HTTPS** as **default protocol**. If it fails, mark bridge as **OFFLINE** with a description that "HTTPS secure connection failed" and log a warning advising user to change configuration to HTTP when using a V1 bridge (if it's not a V1 bridge something else is wrong, so we might need a bug report).

Fine for me.

**Comment by cweitkamp** [comment]
> Unfortunately I don't know how to implement this fallback or even handle the exception. Exception is thrown from core after calling interface method in binding, IIRC.
>
> @cweitkamp - do you have any input?

The exception is thrown by the `PEMTrustManager`. It throws a `CertificateInstantiationException` with cause `java.net.ConnectException` "(Connection refused)". We imo do not have a change to catch and handle this exception properly because it is thrown during service registration of the `HueTlsTrustManagerProvider`. Maybe we can pass the `HueBridgeHandler` instance to the `HueTlsTrustManagerProvider` and add a public method to set the handler status.

ftr: the same exception will be thrown if a user sets a wrong port.

**Comment by lolodomo** [comment]
I think I know how to handle that easily. We could check PEMTrustManager.getInstanceFromServer in the bridge handler before registering the service.
