### ISSUE TITLE
[ahawastecollection] AhaWasteCollectionHandlerTest unstable

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-addons#13651]
This test failed in: https://github.com/wborn/openhab-addons/actions/runs/3350846650/jobs/5554259381

```
[INFO] Running org.openhab.binding.ahawastecollection.internal.AhaWasteCollectionHandlerTest
[ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 4.471 s <<< FAILURE! - in org.openhab.binding.ahawastecollection.internal.AhaWasteCollectionHandlerTest
[ERROR] org.openhab.binding.ahawastecollection.internal.AhaWasteCollectionHandlerTest.testUpdateChannels  Time elapsed: 4.44 s  <<< FAILURE!
org.mockito.exceptions.verification.WantedButNotInvoked: 

Wanted but not invoked:
thingHandlerCallback.statusUpdated(
    Mock for Thing, hashCode: 851033362,
    <custom argument matcher>
);
-> at org.openhab.binding.ahawastecollection.internal.AhaWasteCollectionHandlerTest.testUpdateChannels(AhaWasteCollectionHandlerTest.java:149)

However, there was exactly 1 interaction with this mock:
thingHandlerCallback.statusUpdated(
    Mock for Thing, hashCode: 851033362,
    UNKNOWN
);
-> at org.openhab.core.thing.binding.BaseThingHandler.updateStatus(BaseThingHandler.java:380)


	at org.openhab.binding.ahawastecollection.internal.AhaWasteCollectionHandlerTest.testUpdateChannels(AhaWasteCollectionHandlerTest.java:149)
```

**Comment by wborn** [comment]
Can you have a look at this @soenkekueper?

**Comment by soenkekueper** [comment]
Hey,
yes i'll try to find some free time and have a look.

**Comment by soenkekueper** [comment]
It's the same timing issue in tests as in #12404.
A general way of providing a predictable ScheduledExecutorService in Handler for tests would be great.
I've now fixed it the same way - by providing an individual ExecutorService in test cases.
