### ISSUE TITLE
[nanoleaf] Unit tests failing

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-addons#13902]
On Windows 10:
```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.openhab.binding.nanoleaf.internal.handler.NanoleafControllerHandlerTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.254 s - in org.openhab.binding.nanoleaf.internal.handler.NanoleafControllerHandlerTest
[INFO] Running org.openhab.binding.nanoleaf.internal.layout.NanoleafLayoutTest
[ERROR] Tests run: 6, Failures: 0, Errors: 6, Skipped: 0, Time elapsed: 0.923 s <<< FAILURE! - in org.openhab.binding.nanoleaf.internal.layout.NanoleafLayoutTest
[ERROR] org.openhab.binding.nanoleaf.internal.layout.NanoleafLayoutTest.testFile(String)[1]  Time elapsed: 0.436 s  <<< ERROR!
java.lang.UnsupportedOperationException: 'posix:permissions' not supported as initial attribute
        at org.openhab.binding.nanoleaf.internal.layout.NanoleafLayoutTest.testFile(NanoleafLayoutTest.java:71)

[ERROR] org.openhab.binding.nanoleaf.internal.layout.NanoleafLayoutTest.testFile(String)[2]  Time elapsed: 0.06 s  <<< ERROR!
java.lang.UnsupportedOperationException: 'posix:permissions' not supported as initial attribute
        at org.openhab.binding.nanoleaf.internal.layout.NanoleafLayoutTest.testFile(NanoleafLayoutTest.java:71)

[ERROR] org.openhab.binding.nanoleaf.internal.layout.NanoleafLayoutTest.testFile(String)[3]  Time elapsed: 0.038 s  <<< ERROR!
java.lang.UnsupportedOperationException: 'posix:permissions' not supported as initial attribute
        at org.openhab.binding.nanoleaf.internal.layout.NanoleafLayoutTest.testFile(NanoleafLayoutTest.java:71)

[ERROR] org.openhab.binding.nanoleaf.internal.layout.NanoleafLayoutTest.testFile(String)[4]  Time elapsed: 0.051 s  <<< ERROR!
java.lang.UnsupportedOperationException: 'posix:permissions' not supported as initial attribute
        at org.openhab.binding.nanoleaf.internal.layout.NanoleafLayoutTest.testFile(NanoleafLayoutTest.java:71)

[ERROR] org.openhab.binding.nanoleaf.internal.layout.NanoleafLayoutTest.testFile(String)[5]  Time elapsed: 0.05 s  <<< ERROR!
java.lang.UnsupportedOperationException: 'posix:permissions' not supported as initial attribute
        at org.openhab.binding.nanoleaf.internal.layout.NanoleafLayoutTest.testFile(NanoleafLayoutTest.java:71)

[ERROR] org.openhab.binding.nanoleaf.internal.layout.NanoleafLayoutTest.testFile(String)[6]  Time elapsed: 0.01 s  <<< ERROR!
java.lang.UnsupportedOperationException: 'posix:permissions' not supported as initial attribute
        at org.openhab.binding.nanoleaf.internal.layout.NanoleafLayoutTest.testFile(NanoleafLayoutTest.java:71)

[INFO] Running org.openhab.binding.nanoleaf.internal.LayoutTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.05 s - in org.openhab.binding.nanoleaf.internal.LayoutTest
[INFO] Running org.openhab.binding.nanoleaf.internal.model.GlobalOrientationTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.008 s - in org.openhab.binding.nanoleaf.internal.model.GlobalOrientationTest
[INFO] Running org.openhab.binding.nanoleaf.internal.model.LayoutTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 s - in org.openhab.binding.nanoleaf.internal.model.LayoutTest
[INFO] Running org.openhab.binding.nanoleaf.internal.model.PanelLayoutTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.018 s - in org.openhab.binding.nanoleaf.internal.model.PanelLayoutTest
[INFO] Running org.openhab.binding.nanoleaf.internal.model.PositionDatumTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.008 s - in org.openhab.binding.nanoleaf.internal.model.PositionDatumTest
[INFO] Running org.openhab.binding.nanoleaf.internal.OpenAPIUtilsTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.02 s - in org.openhab.binding.nanoleaf.internal.OpenAPIUtilsTest
[INFO] Running org.openhab.binding.nanoleaf.internal.TouchTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.01 s - in org.openhab.binding.nanoleaf.internal.TouchTest
[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   NanoleafLayoutTest.testFile:71 ▒ UnsupportedOperation 'posix:permissions' not ...
[ERROR]   NanoleafLayoutTest.testFile:71 ▒ UnsupportedOperation 'posix:permissions' not ...
[ERROR]   NanoleafLayoutTest.testFile:71 ▒ UnsupportedOperation 'posix:permissions' not ...
[ERROR]   NanoleafLayoutTest.testFile:71 ▒ UnsupportedOperation 'posix:permissions' not ...
[ERROR]   NanoleafLayoutTest.testFile:71 ▒ UnsupportedOperation 'posix:permissions' not ...
[ERROR]   NanoleafLayoutTest.testFile:71 ▒ UnsupportedOperation 'posix:permissions' not ...
[INFO]
[ERROR] Tests run: 22, Failures: 0, Errors: 6, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

**Comment by jlaur** [comment]
FYI @austvik

**Comment by austvik** [comment]
Thanks, @jlaur! https://github.com/openhab/openhab-addons/pull/13905
