### ISSUE TITLE
[jdbc] Exception thrown because of three-byte Unicode character

### ISSUE THREAD

**Issue by jlaur** [openhab/openhab-addons#13920]
When trying to persist a string with a [special character](https://unicode-table.com/en/1F534/) in MySQL, an exception is thrown:

```
2022-12-11 20:22:19.953 [DEBUG] [persistence.jdbc.internal.JdbcMapper] - JDBC::storeItemValue: item=Title (Type=StringItem, State=🔴, Label=Title, Category=) state=🔴 date=null
2022-12-11 20:22:19.953 [DEBUG] [persistence.jdbc.internal.dto.ItemVO] - JDBC:ItemVO tableName=Item0006; newTableName=null; 
2022-12-11 20:22:19.954 [DEBUG] [istence.jdbc.internal.db.JdbcBaseDAO] - JDBC::storeItemValueProvider: item 'Title' as Type 'STRINGITEM' in 'Item0006' with state '🔴'
2022-12-11 20:22:19.954 [DEBUG] [istence.jdbc.internal.db.JdbcBaseDAO] - JDBC::storeItemValueProvider: itemState: '🔴'
2022-12-11 20:22:19.955 [DEBUG] [persistence.jdbc.internal.dto.ItemVO] - JDBC:ItemVO setValueTypes dbType=VARCHAR(21717); javaType=class java.lang.String;
2022-12-11 20:22:19.955 [DEBUG] [istence.jdbc.internal.db.JdbcBaseDAO] - JDBC::storeItemValueProvider: other: itemState: '🔴'
2022-12-11 20:22:19.955 [DEBUG] [istence.jdbc.internal.db.JdbcBaseDAO] - JDBC::doStoreItemValue sql=INSERT INTO Item0006 (time, value) VALUES( NOW(3), ? ) ON DUPLICATE KEY UPDATE VALUE= ? value='🔴'
2022-12-11 20:22:19.957 [WARN ] [jdbc.internal.JdbcPersistenceService] - JDBC::store: Unable to store item
org.openhab.persistence.jdbc.internal.exceptions.JdbcSQLException: Error in SQL query!!!; Incorrect string value: '\xF0\x9F\x94\xB4' for column 'value' at row 1 Query: INSERT INTO Item0006 (time, value) VALUES( NOW(3), ? ) ON DUPLICATE KEY UPDATE VALUE= ? Parameters: [🔴, 🔴]; Pool Name= yank-default; SQL= INSERT INTO Item0006 (time, value) VALUES( NOW(3), ? ) ON DUPLICATE KEY UPDATE VALUE= ?
	at org.openhab.persistence.jdbc.internal.db.JdbcBaseDAO.doStoreItemValue(JdbcBaseDAO.java:443) ~[?:?]
	at org.openhab.persistence.jdbc.internal.JdbcMapper.storeItemValue(JdbcMapper.java:218) ~[?:?]
	at org.openhab.persistence.jdbc.internal.JdbcPersistenceService.internalStore(JdbcPersistenceService.java:162) ~[?:?]
	at org.openhab.persistence.jdbc.internal.JdbcPersistenceService.store(JdbcPersistenceService.java:140) ~[?:?]
	at org.openhab.core.persistence.internal.PersistenceManagerImpl.handleStateEvent(PersistenceManagerImpl.java:152) ~[?:?]
	at org.openhab.core.persistence.internal.PersistenceManagerImpl.stateChanged(PersistenceManagerImpl.java:473) ~[?:?]
	at org.openhab.core.items.GenericItem.lambda$1(GenericItem.java:259) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

Charset for table and column is latin1, collation **latin1_swedish_ci**, so character is not supported.

After changing to **utf8mb4_general_ci**, I was able to persist the string correctly. However, for this to work, I had to reduce the max size of the column:

```
openhab> jdbc schema check
Table     Item                    Issue
--------  ----------------------  ----------------------------------------------------------------
Item0006  Title                   Column type 'VARCHAR(21717)' expected, but is 'VARCHAR(16381)'
```

When creating a new item and setting the same value, after configuration **utf8mb4_general_ci** at database level:

```
2022-12-11 23:01:30.712 [DEBUG] [istence.jdbc.internal.db.JdbcBaseDAO] - JDBC::doCreateItemTable sql=CREATE TABLE IF NOT EXISTS Item0007 (time TIMESTAMP(3) NOT NULL, value VARCHAR(21717), PRIMARY KEY(time))
2022-12-11 23:01:30.715 [WARN ] [jdbc.internal.JdbcPersistenceService] - JDBC::store: Unable to store item
org.openhab.persistence.jdbc.internal.exceptions.JdbcSQLException: Error in SQL query!!!; Column length too big for column 'value' (max = 16383); use BLOB or TEXT instead Query: CREATE TABLE IF NOT EXISTS Item0007 (time TIMESTAMP(3) NOT NULL, value VARCHAR(21717), PRIMARY KEY(time)) Parameters: []; Pool Name= yank-default; SQL= CREATE TABLE IF NOT EXISTS Item0007 (time TIMESTAMP(3) NOT NULL, value VARCHAR(21717), PRIMARY KEY(time))
	at org.openhab.persistence.jdbc.internal.db.JdbcBaseDAO.doCreateItemTable(JdbcBaseDAO.java:416) ~[?:?]
	at org.openhab.persistence.jdbc.internal.JdbcMapper.createItemTable(JdbcMapper.java:200) ~[?:?]
	at org.openhab.persistence.jdbc.internal.JdbcMapper.getTable(JdbcMapper.java:385) ~[?:?]
	at org.openhab.persistence.jdbc.internal.JdbcMapper.storeItemValue(JdbcMapper.java:215) ~[?:?]
	at org.openhab.persistence.jdbc.internal.JdbcPersistenceService.internalStore(JdbcPersistenceService.java:162) ~[?:?]
	at org.openhab.persistence.jdbc.internal.JdbcPersistenceService.store(JdbcPersistenceService.java:140) ~[?:?]
	at org.openhab.core.persistence.internal.PersistenceManagerImpl.handleStateEvent(PersistenceManagerImpl.java:152) ~[?:?]
	at org.openhab.core.persistence.internal.PersistenceManagerImpl.stateChanged(PersistenceManagerImpl.java:473) ~[?:?]
	at org.openhab.core.items.GenericItem.lambda$1(GenericItem.java:259) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

## Expected Behavior

- Exceptions should not be thrown.
- Unicode characters should be supported, if possible.
- If special configuration is needed, this should be documented.
- Column types should be created with database collation and corresponding size restrictions, possibly.

## Current Behavior

MySQL:
- Exception is thrown when trying to persist three-byte Unicode character.
- If database collation is **utf8mb4_general_ci**, exception is thrown when creating new table.

## Possible Solution

I will need to analyze the problem further.

## Steps to Reproduce
From console - for a persisted String item:
```
openhab> openhab:update Title "🔴"
Update has been sent successfully.
```

## Your Environment
MySQL 8.0.23
openHAB 3.4M5

**Comment by jlaur** [comment]
Reopening, since after changing character set for the `value` column to **utf8mb4** I now get:
```
2024-08-22 23:14:46.343 [WARN ] [jdbc.internal.JdbcPersistenceService] - JDBC::store: Unable to store item
org.openhab.persistence.jdbc.internal.exceptions.JdbcSQLException: Error in SQL query!!!; Incorrect string value: '\xF0\x9F\x94\xB4' for column 'value' at row 1 Query: INSERT INTO Chromecast3_MediaTitle (time, value) VALUES( NOW(3), ? ) ON DUPLICATE KEY UPDATE VALUE= ? Parameters: [🔴, 🔴]; Pool Name= yank-default; SQL= INSERT INTO Chromecast3_MediaTitle (time, value) VALUES( NOW(3), ? ) ON DUPLICATE KEY UPDATE VALUE= ?
	at org.openhab.persistence.jdbc.internal.db.JdbcBaseDAO.doStoreItemValue(JdbcBaseDAO.java:441) ~[?:?]
	at org.openhab.persistence.jdbc.internal.JdbcMapper.storeItemValue(JdbcMapper.java:220) ~[?:?]
	at org.openhab.persistence.jdbc.internal.JdbcPersistenceService.internalStore(JdbcPersistenceService.java:174) ~[?:?]
	at org.openhab.persistence.jdbc.internal.JdbcPersistenceService.lambda$1(JdbcPersistenceService.java:146) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:840) [?:?]
```

**Comment by jlaur** [comment]
It seems the migration to **utf8mb4** failed. I will close this issue again when I have successfully migrated and verified that the concrete case is resolved.

**Comment by jlaur** [comment]
It works:
![image](https://github.com/user-attachments/assets/1175694f-2a31-4d00-b06c-37e201b8cfcc)
