### ISSUE TITLE
[homekit] 3.4.0M4 - after ios 16.2 / homekit bundle update 

### ISSUE THREAD

**Issue by JacekKac** [openhab/openhab-addons#14047]
i have problems after updating to 
`update org.openhab.io.homekit https://github.com/ccutrer/openhab-addons/releases/download/homekit-20221220-02/org.openhab.io.homekit-3.4.0-SNAPSHOT.jar
`
everythinkg is working but my thermostat items are gone... probably because the TempSensor are gone ;) 

[INFO ] [mekit.internal.HomekitChangeListener] - Created 13 HomeKit items in instance 1.

openjdk 11.0.9 2020-10-20 LTS
OpenJDK Runtime Environment Zulu11.43+88-CA (build 11.0.9+11-LTS)
OpenJDK Client VM Zulu11.43+88-CA (build 11.0.9+11-LTS, mixed mode)
openhab:
**Version:     3.4.0.M4 (Build)**

TempSensor group/items: 

```
items.replaceItem({ type: 'Group', name: `gRoom${i}_TempSensor`, label: `Czujnik temperatury ${i}`, tags: [`Room${i}`], category: 'temperature', groups: [`gRoom${i}`], metadata: {homekit: `TemperatureSensor,Battery` } } );
    items.replaceItem({ type: `Number`, name: `TempSensor${i}_CurrentTemp`, label: `Temperatura aktualna`, tags: [`Room${i}`], category: `temperature`, groups: [`gRoom${i}_TempSensor`,`gRoom${i}`,`gRoom${i}_termostat`], metadata: { homekit: `TemperatureSensor.CurrentTemperature,Thermostat.CurrentTemperature`, ga: { value: 'thermostatTemperatureAmbient', config: {roomHint: roomlabels[i], structureHint: roomlabels[0]}}, stateDescription: { value: ` `, config: { pattern: `%.1f °C`} } }, channels: { [`mqtt:topic:mymqttbroker:Temp_${i}:temperature`]: {} } });
    items.replaceItem({ type: `Switch`, name: `TempSensor${i}_BatteryLow`, label: `Niski poziom baterii`, tags: [`Room${i}`], category: `temperature`, groups: [`gRoom${i}_TempSensor`,`gRoom${i}`,`gRoom${i}_termostat`], metadata: { stateDescription: { value: ` `, config: { pattern: `%s`} }, homekit: {value: `TemperatureSensor.BatteryLowStatus,Battery.BatteryLowStatus`}}  });
    items.replaceItem({ type: `Number`, name: `TempSensor${i}_Battery`, label: `Poziom baterii`, tags: [`Room${i}`], category: `temperature`, groups: [`gRoom${i}`,`gRoom${i}_TempSensor`,`gRoom${i}_termostat`], metadata: { stateDescription: { value: ` `, config: { pattern: `%.1f %%`} }, homekit: {value: `Battery.BatteryLevel`} }, channels: { [`mqtt:topic:mymqttbroker:Temp_${i}:battery`]: {} } });
    items.replaceItem({ type: `Switch`, name: `TempSensor${i}_FaultStatus`, label: `Czujnik temperatury`, tags: [`Room${i}`], category: ``, groups: [`gRoom${i}`,`gRoom${i}_TempSensor`,`gRoom${i}_termostat`], metadata: { stateDescription: { value: ` `, config: { pattern: `%s`} }, homekit: {value: `TemperatureSensor.FaultStatus`} }, channels: { [`mqtt:topic:mymqttbroker:Temp_${i}:availability`]: {} } });
```

```

2022-12-22 14:16:52.485 [WARN ] [.accessories.HomekitAccessoryFactory] - Cannot instantiate accessory implementation for accessory TemperatureSensor
java.lang.reflect.InvocationTargetException: null
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
        at org.openhab.io.homekit.internal.accessories.HomekitAccessoryFactory.create(HomekitAccessoryFactory.java:192) ~[?:?]
        at org.openhab.io.homekit.internal.HomekitChangeListener.createRootAccessories(HomekitChangeListener.java:457) ~[?:?]
        at java.util.Optional.ifPresent(Optional.java:183) ~[?:?]
        at org.openhab.io.homekit.internal.HomekitChangeListener.applyUpdates(HomekitChangeListener.java:297) ~[?:?]
        at org.openhab.io.homekit.internal.Debouncer.tryActionOrPostpone(Debouncer.java:102) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NoSuchMethodError: 'org.openhab.core.library.types.QuantityType org.openhab.core.library.types.QuantityType.toUnitRelative(javax.measure.Unit)'
        at org.openhab.io.homekit.internal.HomekitTaggedItem.getConfigurationAsQuantity(HomekitTaggedItem.java:430) ~[?:?]
        at org.openhab.io.homekit.internal.accessories.HomekitCharacteristicFactory.getTemperatureStep(HomekitCharacteristicFactory.java:306) ~[?:?]
        at org.openhab.io.homekit.internal.accessories.HomekitTemperatureSensorImpl.getMinStepCurrentTemperature(HomekitTemperatureSensorImpl.java:78) ~[?:?]
        at io.github.hapjava.services.impl.TemperatureSensorService.<init>(TemperatureSensorService.java:30) ~[?:?]
        at org.openhab.io.homekit.internal.accessories.HomekitTemperatureSensorImpl.<init>(HomekitTemperatureSensorImpl.java:41) ~[?:?]
        ... 15 more
2022-12-22 14:16:52.495 [WARN ] [mekit.internal.HomekitChangeListener] - Cannot create accessory Item:gRoom2_TempSensor (Type=GroupItem, Members=4, State=NULL, Label=Czujnik temperatury 2, Category=temperature, Tags=[Room2, _DYNAMIC_], Groups=[gRoom2])  HomeKit type: 'TemperatureSensor' characteristic: 'Empty'
2022-12-22 14:16:52.503 [WARN ] [.accessories.HomekitAccessoryFactory] - Cannot instantiate accessory implementation for accessory Thermostat
java.lang.reflect.InvocationTargetException: null
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
        at org.openhab.io.homekit.internal.accessories.HomekitAccessoryFactory.create(HomekitAccessoryFactory.java:192) ~[?:?]
        at org.openhab.io.homekit.internal.HomekitChangeListener.createRootAccessories(HomekitChangeListener.java:457) ~[?:?]
        at java.util.Optional.ifPresent(Optional.java:183) ~[?:?]
        at org.openhab.io.homekit.internal.HomekitChangeListener.applyUpdates(HomekitChangeListener.java:297) ~[?:?]
        at org.openhab.io.homekit.internal.Debouncer.tryActionOrPostpone(Debouncer.java:102) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NoSuchMethodError: 'org.openhab.core.library.types.QuantityType org.openhab.core.library.types.QuantityType.toUnitRelative(javax.measure.Unit)'
        at org.openhab.io.homekit.internal.HomekitTaggedItem.getConfigurationAsQuantity(HomekitTaggedItem.java:430) ~[?:?]
        at org.openhab.io.homekit.internal.accessories.HomekitCharacteristicFactory.getTemperatureStep(HomekitCharacteristicFactory.java:306) ~[?:?]
        at org.openhab.io.homekit.internal.accessories.HomekitThermostatImpl.getMinStepCurrentTemperature(HomekitThermostatImpl.java:137) ~[?:?]
        at io.github.hapjava.services.impl.ThermostatService.<init>(ThermostatService.java:53) ~[?:?]
        at org.openhab.io.homekit.internal.accessories.HomekitThermostatImpl.<init>(HomekitThermostatImpl.java:84) ~[?:?]
        ... 15 more
2022-12-22 14:16:52.513 [WARN ] [mekit.internal.HomekitChangeListener] - Cannot create accessory Item:gRoom3_termostat (Type=GroupItem, Members=22, State=NULL, Label=Termostat 3, Category=heating, Tags=[_DYNAMIC_, Room3], Groups=[gRoom3])  HomeKit type: 'Thermostat' characteristic: 'Empty'
2022-12-22 14:16:52.521 [WARN ] [.accessories.HomekitAccessoryFactory] - Cannot instantiate accessory implementation for accessory Thermostat
java.lang.reflect.InvocationTargetException: null
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
        at org.openhab.io.homekit.internal.accessories.HomekitAccessoryFactory.create(HomekitAccessoryFactory.java:192) ~[?:?]
        at org.openhab.io.homekit.internal.HomekitChangeListener.createRootAccessories(HomekitChangeListener.java:457) ~[?:?]
        at java.util.Optional.ifPresent(Optional.java:183) ~[?:?]

```

_Originally posted by @JacekKac in https://github.com/openhab/openhab-addons/issues/13949#issuecomment-1362833500_

**Comment by JacekKac** [comment]
#13949

**Comment by JacekKac** [comment]
@ccutrer hi, i moved it to new issue. Openhab version is 3.4.0M4 but i did only bundle update. What to do next? should i wait for new homekit budle for 3.4.0M4 or hmmm ? don't know what to do. :)
@yfre fyi

**Comment by JacekKac** [comment]
upgrading to 3.4.0 resolved it
