### ISSUE TITLE
[hue] Exception due to empty response from API (sensors) 

### ISSUE THREAD

**Issue by dan-m-joha** [openhab/openhab-addons#14218]
Hallo,

To day I updated my OpenHab 3.3 to OpenHab 3.4 and promptly the hue-bridge fails.
I have tried with all combinations of Port (80/443) and Protocol (HTTP/HTTPS), but still always the same result.

In the "events.log" I see the following:
```
023-01-14 12:03:49.543 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'hue:bridge:huebridge' changed from UNINITIALIZED (DISABLED) to INITIALIZING
2023-01-14 12:03:49.550 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'hue:bridge:huebridge' changed from INITIALIZING to UNKNOWN
2023-01-14 12:03:49.554 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'hue:0107:huebridge:PresenceSensor' changed from UNINITIALIZED (BRIDGE_UNINITIALIZED) to INITIALIZING
2023-01-14 12:03:49.556 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'hue:0010:huebridge:3' changed from UNINITIALIZED (BRIDGE_UNINITIALIZED) to INITIALIZING
2023-01-14 12:03:49.560 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'hue:0010:huebridge:2' changed from UNINITIALIZED (BRIDGE_UNINITIALIZED) to INITIALIZING
2023-01-14 12:03:49.561 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'hue:0010:huebridge:3' changed from INITIALIZING to OFFLINE (BRIDGE_OFFLINE)
2023-01-14 12:03:49.567 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'hue:0107:huebridge:PresenceSensor' changed from INITIALIZING to OFFLINE (BRIDGE_OFFLINE)
2023-01-14 12:03:49.569 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'hue:0010:huebridge:2' changed from INITIALIZING to OFFLINE (BRIDGE_OFFLINE)
2023-01-14 12:03:52.571 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'hue:bridge:huebridge' changed from UNKNOWN to ONLINE
2023-01-14 12:03:52.573 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'hue:0107:huebridge:PresenceSensor' changed from OFFLINE (BRIDGE_OFFLINE) to ONLINE
2023-01-14 12:03:52.575 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'hue:0010:huebridge:2' changed from OFFLINE (BRIDGE_OFFLINE) to ONLINE
2023-01-14 12:03:52.576 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'hue:0010:huebridge:3' changed from OFFLINE (BRIDGE_OFFLINE) to ONLINE
2023-01-14 12:03:54.130 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'hue:bridge:huebridge' changed from ONLINE to OFFLINE: Hue Bridge connection lost.
2023-01-14 12:03:54.131 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'hue:0010:huebridge:2' changed from ONLINE to OFFLINE (BRIDGE_OFFLINE)
2023-01-14 12:03:54.132 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'hue:0010:huebridge:3' changed from ONLINE to OFFLINE (BRIDGE_OFFLINE)
2023-01-14 12:03:54.133 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'hue:0107:huebridge:PresenceSensor' changed from ONLINE to OFFLINE (BRIDGE_OFFLINE)
2023-01-14 12:03:54.566 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'hue:bridge:huebridge' changed from OFFLINE: Hue Bridge connection lost. to ONLINE
2023-01-14 12:03:54.568 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'hue:0010:huebridge:2' changed from OFFLINE (BRIDGE_OFFLINE) to ONLINE
2023-01-14 12:03:54.569 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'hue:0010:huebridge:3' changed from OFFLINE (BRIDGE_OFFLINE) to ONLINE
2023-01-14 12:03:54.570 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'hue:0107:huebridge:PresenceSensor' changed from OFFLINE (BRIDGE_OFFLINE) to ONLINE
2023-01-14 12:03:54.637 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'hue:bridge:huebridge' changed from ONLINE to OFFLINE: Hue Bridge connection lost.
2023-01-14 12:03:54.638 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'hue:0010:huebridge:2' changed from ONLINE to OFFLINE (BRIDGE_OFFLINE)
2023-01-14 12:03:54.638 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'hue:0010:huebridge:3' changed from ONLINE to OFFLINE (BRIDGE_OFFLINE)
2023-01-14 12:03:54.639 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'hue:0107:huebridge:PresenceSensor' changed from ONLINE to OFFLINE (BRIDGE_OFFLINE)
2023-01-14 12:03:58.193 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'hue:bridge:huebridge' changed from OFFLINE: Hue Bridge connection lost. to ONLINE
2023-01-14 12:03:58.194 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'hue:0010:huebridge:3' changed from OFFLINE (BRIDGE_OFFLINE) to ONLINE
2023-01-14 12:03:58.195 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'hue:0107:huebridge:PresenceSensor' changed from OFFLINE (BRIDGE_OFFLINE) to ONLINE
2023-01-14 12:03:58.196 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'hue:0010:huebridge:2' changed from OFFLINE (BRIDGE_OFFLINE) to ONLINE
2023-01-14 12:03:58.698 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'hue:bridge:huebridge' changed from ONLINE to OFFLINE: Hue Bridge connection lost.
2023-01-14 12:03:58.699 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'hue:0010:huebridge:3' changed from ONLINE to OFFLINE (BRIDGE_OFFLINE)
2023-01-14 12:03:58.700 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'hue:0010:huebridge:2' changed from ONLINE to OFFLINE (BRIDGE_OFFLINE)
2023-01-14 12:03:58.700 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'hue:0107:huebridge:PresenceSensor' changed from ONLINE to OFFLINE (BRIDGE_OFFLINE)

```
And in openhab.log the following repeats over and over again:
```
2023-01-14 12:03:58.696 [WARN ] [ue.internal.handler.HueBridgeHandler] - An unexpected error occurred: null
java.lang.NullPointerException: null
        at org.openhab.binding.hue.internal.connection.HueBridge.getSensors(HueBridge.java:280) ~[bundleFile:?]
        at org.openhab.binding.hue.internal.handler.HueBridgeHandler$1.doConnectedRun(HueBridgeHandler.java:199) ~[bundleFile:?]
        at org.openhab.binding.hue.internal.handler.HueBridgeHandler$PollingRunnable.run(HueBridgeHandler.java:136) [bundleFile:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]

```

## Expected Behavior
hue-bridge starts as "usual" :-)

## Your Environment
* Version used: openHAB 3.4.1, hue-binding 3.4.1
* Operating System and version:
  OpenHab: Fedora Linux 35 (Server Edition)
  deconz: Raspbian GNU/Linux 10 (buster), deconz version 2.19.03 / 9/19/2022

Any suggestions?

Dan

**Comment by jlaur** [comment]
@dan-m-joha - can you enable trace logging, so we can see the received payload leading to this problem?

**Comment by Distrikt26** [comment]
Hello,
Same problem. Openhabian 3.2 to 3.4.1 on RPI.

**Comment by Distrikt26** [comment]
Solution  :  Binding Hue configuration, change port 80 to 443 if protocole https

**Comment by dan-m-joha** [comment]
OK, here are a log (I hope I have done it correctly, I am not used to debug OpenHab).

[openhab.log.gz](https://github.com/openhab/openhab-addons/files/10419923/openhab.log.gz)

As I wrote, I have tried all four combinations of protocol and port and none of them works.

**Comment by marcusfacius** [comment]
Same problem as above, no issues before upgrade to OH 3.4.1. Also have tired every combination of HTTP/HTTPS and port 80/443/blank.

**Comment by SE232** [comment]
Same problem as above, no issues before upgrade to OH 3.4.1. Also have tired every combination of HTTP/HTTPS and port 80/443/blank. 
Update was from 3.2 --> 3.41. No issues with HUE before.

**Comment by SE232** [comment]
I deleted soem not longer used bindings, things and items, upgraded deconz and phoscon (I understand - nothing to change the situation...) changed port to 443 again, saved - and it works :-)

**Comment by jlaur** [comment]
> I deleted soem not longer used bindings

Which ones?

> upgraded deconz and phoscon (I understand - nothing to change the situation...) changed port to 443 again, saved - and it works :-)

It could be related as one of the Hue changes in 3.4 was using the framework's shared HTTP client. So problems in other bindings could affect the Hue binding.

**Comment by SE232** [comment]
@jlaur 
>>>I deleted soem not longer used bindings
>>>Which ones?
Just doublechecked:  It was just LGTV, but....
Triying to rebember what I did before: I'm not sure, I pressed the save button after changing the PORT to 443 previously...
So it might have been a level 8 error ;-) (User level...)

**Comment by dan-m-joha** [comment]
That sadly does not change anything here.
The Hue-Bridge goes ONLINE (also shows as green in the GUI) for a short time ~1s and then to OFFLINE.

```
2023-01-27 16:37:26.223 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'hue:bridge:huebridge' changed from UNINITIALIZED (DISABLED) to INITIALIZING
2023-01-27 16:37:26.232 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'hue:bridge:huebridge' changed from INITIALIZING to UNKNOWN
2023-01-27 16:37:26.239 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'hue:0107:huebridge:PresenceSensor' changed from UNINITIALIZED (BRIDGE_UNINITIALIZED) to INITIALIZING
2023-01-27 16:37:26.241 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'hue:0010:huebridge:2' changed from UNINITIALIZED (BRIDGE_UNINITIALIZED) to INITIALIZING
2023-01-27 16:37:26.244 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'hue:0010:huebridge:3' changed from UNINITIALIZED (BRIDGE_UNINITIALIZED) to INITIALIZING
2023-01-27 16:37:26.251 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'hue:0010:huebridge:3' changed from INITIALIZING to OFFLINE (BRIDGE_OFFLINE)
2023-01-27 16:37:26.252 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'hue:0107:huebridge:PresenceSensor' changed from INITIALIZING to OFFLINE (BRIDGE_OFFLINE)
2023-01-27 16:37:26.253 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'hue:0010:huebridge:2' changed from INITIALIZING to OFFLINE (BRIDGE_OFFLINE)
2023-01-27 16:37:29.254 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'hue:bridge:huebridge' changed from UNKNOWN to ONLINE
2023-01-27 16:37:29.255 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'hue:0010:huebridge:2' changed from OFFLINE (BRIDGE_OFFLINE) to ONLINE
2023-01-27 16:37:29.256 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'hue:0107:huebridge:PresenceSensor' changed from OFFLINE (BRIDGE_OFFLINE) to ONLINE
2023-01-27 16:37:29.257 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'hue:0010:huebridge:3' changed from OFFLINE (BRIDGE_OFFLINE) to ONLINE
2023-01-27 16:37:30.809 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'hue:bridge:huebridge' changed from ONLINE to OFFLINE: Hue Bridge connection lost.
2023-01-27 16:37:30.810 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'hue:0010:huebridge:2' changed from ONLINE to OFFLINE (BRIDGE_OFFLINE)
2023-01-27 16:37:30.810 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'hue:0010:huebridge:3' changed from ONLINE to OFFLINE (BRIDGE_OFFLINE)
2023-01-27 16:37:30.811 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'hue:0107:huebridge:PresenceSensor' changed from ONLINE to OFFLINE (BRIDGE_OFFLINE)
2023-01-27 16:37:31.257 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'hue:bridge:huebridge' changed from OFFLINE: Hue Bridge connection lost. to ONLINE
2023-01-27 16:37:31.258 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'hue:0010:huebridge:2' changed from OFFLINE (BRIDGE_OFFLINE) to ONLINE
2023-01-27 16:37:31.259 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'hue:0010:huebridge:3' changed from OFFLINE (BRIDGE_OFFLINE) to ONLINE
2023-01-27 16:37:31.260 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'hue:0107:huebridge:PresenceSensor' changed from OFFLINE (BRIDGE_OFFLINE) to ONLINE
2023-01-27 16:37:31.314 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'hue:bridge:huebridge' changed from ONLINE to OFFLINE: Hue Bridge connection lost.
2023-01-27 16:37:31.315 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'hue:0010:huebridge:2' changed from ONLINE to OFFLINE (BRIDGE_OFFLINE)
2023-01-27 16:37:31.316 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'hue:0010:huebridge:3' changed from ONLINE to OFFLINE (BRIDGE_OFFLINE)
2023-01-27 16:37:31.319 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'hue:0107:huebridge:PresenceSensor' changed from ONLINE to OFFLINE (BRIDGE_OFFLINE)

```

**Comment by lolodomo** [comment]
@dan-m-joha : please enable DEBUG logs for the hue binding, there might be a log that could explain why your connection to the hue bridge is lost.

https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueBridgeHandler.java#L155

**Comment by lolodomo** [comment]
> OK, here are a log (I hope I have done it correctly, I am not used to debug OpenHab).
> 
> [openhab.log.gz](https://github.com/openhab/openhab-addons/files/10419923/openhab.log.gz)

I opened your file but you have apparently not enabled TRACE logs of the hue binding. I see only the WARN logs with the exception. At the reverse, your file is flooded with Jetty client DEBUG logs we don't need.

What was requested is that you run this console command: log:set TRACE org.openhab.binding.hue

**Comment by lolodomo** [comment]
And please show us how is setup your bridge thing, I mean by doing a capture of this page in MainUI:
![image](https://user-images.githubusercontent.com/10186704/215340281-d8e8fef6-ee3b-43e7-b626-ecc047972291.png)

**Comment by dan-m-joha** [comment]
OK, here is a new log file:
[openhab.log.gz](https://github.com/openhab/openhab-addons/files/10530772/openhab.log.gz)

And here are some screenshots:
![Screenshot_20230129_211721](https://user-images.githubusercontent.com/36599761/215354395-0c800d0b-ebde-4f31-93e0-0cae7883faf8.png)
![Screenshot_20230129_211806](https://user-images.githubusercontent.com/36599761/215354398-c2528940-88fd-45be-a310-e19b686023ab.png)
![Screenshot_20230129_211832](https://user-images.githubusercontent.com/36599761/215354399-2732823a-ecb1-4506-929d-aa332d175519.png)


Sorry, this is the first time that I am having problem with OpenHab and has to do debugging.
Thanks for your support.

**Comment by lolodomo** [comment]
Please mask your username. 
I am removing your captain.

**Comment by dan-m-joha** [comment]
Ouups, missed that one as well as the logfile.
Here are they again without Username....
![Screenshot_20230129_214443](https://user-images.githubusercontent.com/36599761/215354856-4a73a2cd-7ac4-4962-b231-22e9434178ac.png)
[openhab.log.gz](https://github.com/openhab/openhab-addons/files/10530814/openhab.log.gz)

**Comment by marcusfacius** [comment]
Unfortunately I'm still experiencing the same problems, hue bridge disconnects after upgrade to OH 3.4.1. I have noticed a few additional details though since initially posting:

First - I can get the Hue binding to connect to the bridge successfully after rebooting my raspberry pi and OpenHAB. I tried to se if cleaning the cache would also fix the connection, but ended up corrupting my installation so started from scratch with OH 3.4.1 and then restored from my most recent backup, but still have the same problems. 

Second- when I am able to get the connection working again, it seems to last for 4 days before disconnecting again. 

I have enabled TRACE logging for hue but as I did this after the 4 day mark when the disconnection occurred, it may not contain the reason why this is happening. After the disconnection happened, the TRACE logging was not showing anything at all - except with bundle:restart of the Hue binding or with disabling and re-enabling the bridge thing from the UI - not sure if that would be helpful or not. 

Here is my configuration:  
![Bridge configuration](https://user-images.githubusercontent.com/83624610/215354412-cdd78520-e36f-48b3-9e53-eeb1f6439d8f.jpg)
![Bridge configuration text](https://user-images.githubusercontent.com/83624610/215364897-4c13de66-4575-46ef-b0c7-d3157ee9f6d6.jpg)

I am going to keep track of the TRACE logs and will post them when the next disconnection occurs, anticipate ~4 days from now as I just did a re-start to get the connection working again. I will note that I am seeing this repeatedly approximately every 500 milliseconds, don't know if that is normal... 

`2023-01-29 17:25:26.647 [TRACE] [ue.internal.handler.HueBridgeHandler] - Hue sensor '1' added.
2023-01-29 17:25:27.147 [TRACE] [ng.hue.internal.connection.HueBridge] - Hue request: GET - URL = 'https://192.168.68.61:443/api/XXXXXXXXXXXXXXXXXXXXXXX/sensors'
2023-01-29 17:25:27.155 [TRACE] [ng.hue.internal.connection.HueBridge] - Hue response: status = 200, content = '{"1":{"state":{"daylight":null,"lastupdated":"none"},"config":{"on":true,"configured":false,"sunriseoffset":30,"sunsetoffset":-30},"name":"Daylight","type":"Daylight","modelid":"PHDL00","manufacturername":"Signify Netherlands B.V.","swversion":"1.0"}}'`

Thanks in advance!

**Comment by lolodomo** [comment]
@marcusfacius : your problem looks very different: the binding is able to connect and is working many days. Then the connection is lost and you can't reconnect. 

@dan-m-joha 's problem is apparently to not be able to connect at all. 

So maybe you should create a separate issue. 

And yes, the request you see every 590 ms is the poll for sensors data. If you have no sensors, set the polling interval to 0 to avoid all these requests.

**Comment by jlaur** [comment]
> Second- when I am able to get the connection working again, it seems to last for 4 days before disconnecting again.

That's interesting and very similar to the problem I experienced with instability caused by another binding blocking threads recently: #14162

Can you list all the bindings you are using? And the next time it happens, can you fetch the output from this command in the Karaf console?

```
threads --monitors --locks
```

**Comment by lolodomo** [comment]
Come back to @dan-m-joha 's problem:
```
2023-01-29 21:23:14.809 [TRACE] [ng.hue.internal.connection.HueBridge] - Hue request: GET - URL = 'http://192.168.xx.yy:80/api/xxxxxxxxxx/sensors'
2023-01-29 21:23:14.814 [TRACE] [ng.hue.internal.connection.HueBridge] - Hue response: status = 200, content = ''
2023-01-29 21:23:14.815 [WARN ] [ue.internal.handler.HueBridgeHandler] - An unexpected error occurred: null
java.lang.NullPointerException: null
        at org.openhab.binding.hue.internal.connection.HueBridge.getSensors(HueBridge.java:280) ~[bundleFile:?]
````

@jlaur: the request returns status 200 but an empty content ! In that case, `sensorMap` is then null. You should handle that case. The fix will be easy.

**Comment by lolodomo** [comment]
If we do not accept such result, the bridge will go OFFLINE. If we accept such result, the bridge will remain ONLINE but all sensor things will go OFFLINE.

**Comment by lolodomo** [comment]
Or we should just ignore such result.

**Comment by lolodomo** [comment]
@dan-m-joha : for your information, the fix is available in snapshot 3301 (OH 4.0) and will also be available (later) in next 3.4 release (3.4.2).

**Comment by dan-m-joha** [comment]
Great, thanks for your effort in solving this.
Do you have any ETA for 3.4.2 (and 4.0)?

**Comment by lolodomo** [comment]
> Do you have any ETA for 3.4.2 (and 4.0)?

No.
But 3.4.1 was released 26 days ago, so it is probable that 3.4.2 will be released relatively soon.
Official release of OH 4.0 is certainly not for tomorrow. But I assume a first milestone could arrive in the coming weeks.

**Comment by marcusfacius** [comment]
> > Second- when I am able to get the connection working again, it seems to last for 4 days before disconnecting again.
> 
> That's interesting and very similar to the problem I experienced with instability caused by another binding blocking threads recently: #14162
> 
> Can you list all the bindings you are using? And the next time it happens, can you fetch the output from this command in the Karaf console?
> 
> ```
> threads --monitors --locks
> ```

Hey @jlaur so sorry I lost track of this! The bindings I'm using are: alarm decoder, amazon echo control, astro, ecobee, exec, hue, iCalendar, mail, MQTT, nest, network, NTP, OpenWeatherMap, sonos, spotify, system info, TP link smart home, and Z-Wave. I'm not using a couple of those anymore so I suppose I could stand to remove them. As for running threads --monitors --locks - I just ran it (Hue stopped working a couple days ago)  but the output is massive - so much so that I can't even see it all, it outran the history in Putty. Can you tell me what exactly that command does?

**Comment by dan-m-joha** [comment]
Yes, in 3.4.2 the problem is gone. :-)
Thanks for your support and efforts!
