### ISSUE TITLE
Bindings setting `ThingStatus.UNINITIALIZED`

### ISSUE THREAD

**Issue by jlaur** [openhab/openhab-addons#14268]
The following bindings:
- cbus
- semsportal
- km200
- kostalinverter

are setting `ThingStatus.UNINITIALIZED` explicitly.

These bugs will be exposed by openhab/openhab-core#3330

#### cbus
https://github.com/openhab/openhab-addons/blob/f808edf725bf52942245ba2033b529a5e0b1ba3b/bundles/org.openhab.binding.cbus/src/main/java/org/openhab/binding/cbus/handler/CBusNetworkHandler.java#L174

https://github.com/openhab/openhab-addons/blob/f808edf725bf52942245ba2033b529a5e0b1ba3b/bundles/org.openhab.binding.cbus/src/main/java/org/openhab/binding/cbus/handler/CBusCGateHandler.java#L79-L80

#### semsportal

https://github.com/openhab/openhab-addons/blob/f808edf725bf52942245ba2033b529a5e0b1ba3b/bundles/org.openhab.binding.semsportal/src/main/java/org/openhab/binding/semsportal/internal/PortalHandler.java#L143

#### km200

https://github.com/openhab/openhab-addons/blob/f808edf725bf52942245ba2033b529a5e0b1ba3b/bundles/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/handler/KM200GatewayHandler.java#L95

#### kostalinverter

https://github.com/openhab/openhab-addons/blob/f808edf725bf52942245ba2033b529a5e0b1ba3b/bundles/org.openhab.binding.kostalinverter/src/main/java/org/openhab/binding/kostalinverter/internal/thirdgeneration/ThirdGenerationHandler.java#L330

**Comment by jlaur** [comment]
FYI @jpharvey, @Markinus, @cschneider

**Comment by jlaur** [comment]
Consequence in 3.4:
```
java.lang.IllegalArgumentException: Illegal status UNINITIALIZED. Bindings only may set UNKNOWN, ONLINE, OFFLINE or REMOVED.
	at org.openhab.core.thing.internal.ThingManagerImpl$1.ensureValidStatus(ThingManagerImpl.java:230) ~[?:?]
	at org.openhab.core.thing.internal.ThingManagerImpl$1.statusUpdated(ThingManagerImpl.java:193) ~[?:?]
	at org.openhab.core.thing.binding.BaseThingHandler.updateStatus(BaseThingHandler.java:380) ~[?:?]
	at org.openhab.core.thing.binding.BaseThingHandler.updateStatus(BaseThingHandler.java:404) ~[?:?]
```
