### ISSUE TITLE
[unifi] 404 returned by controller

### ISSUE THREAD

**Issue by Orscheler** [openhab/openhab-addons#14378]
After the Update-Process from OH3.1 to OH3.4.1 the unifi-binding is not working any longer. Reboots and restarts of the unifi-service has been tried without success. 

Within the logs following message is being shown:
```
2023-02-10 09:45:22.606 [INFO ] [.internal.api.UniFiControllerRequest] - 
UniFi returned a status code 404: 
<!doctype html><html lang="en"><head><title>HTTP Status 404 – Not Found</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 404 – Not Found</h1></body></html>
```

The UI returns:
```
COMMUNICATION_ERROR
Unknown HTTP status code 404 returned by the controller
```

Configuration between the OH3.1. and OH3.4.1 is still the same:
```
openhabian@RPI-1:~ $ cat /etc/openhab/things/unifi.things 
Bridge unifi:controller:home "UniFi Controller" [ host="10.10.10.2", port=8443, username="admin", password="******", refresh=30, unifios="yes" ] {
        Thing wirelessClient PhoneL "L Phone" [ cid="MAC", site="SSID", considerHome=600 ]
        Thing wirelessClient PhoneS "S Phone" [ cid="MAC", site="SSID", considerHome=600 ]
}
```

Unifi has also been updated from 7.1.x to 7.2.97 - without success.

```
openhabian@RPI-1:~ $ oh-version 
[1] 5075

Version:     3.4.1 (Build)

User:        openhab (Active Process 527)
User Groups: openhab tty dialout audio bluetooth gpio

Directories: Folder Name      | Path                        | User:Group
             -----------      | ----                        | ----------
             OPENHAB_HOME     | /usr/share/openhab          | openhab:openhab
             OPENHAB_RUNTIME  | /usr/share/openhab/runtime  | openhab:openhab
             OPENHAB_USERDATA | /var/lib/openhab            | openhab:openhab
             OPENHAB_CONF     | /etc/openhab                | openhab:openhab
             OPENHAB_LOGDIR   | /var/log/openhab            | root:root
             OPENHAB_BACKUPS  | /var/lib/openhab/backups    | openhab:openhab

URLs:        http://10.10.10.11:8080
             https://10.10.10.11:8443

###############################################################################
###############  openhabian  ##################################################
###############################################################################
##        Ip = 10.10.10.11
##   Release = Raspbian GNU/Linux 11 (bullseye)
##    Kernel = Linux 5.15.84-v7+
##  Platform = Raspberry Pi 3 Model B Plus Rev 1.3
##    Uptime = 0 day(s). 0:35:10
## CPU Usage = 2.99% avg over 4 cpu(s) (4 core(s) x 1 socket(s))
##  CPU Load = 1m: 0.24, 5m: 0.16, 15m: 0.16
##    Memory = Free: 0.28GB (30%), Used: 0.66GB (70%), Total: 0.94GB
##      Swap = Free: 1.89GB (100%), Used: 0.00GB (0%), Total: 1.89GB
##      Root = Free: 48.87GB (87%), Used: 7.01GB (13%), Total: 58.29GB
##   Updates = 0 apt updates available.
##  Sessions = 1 session(s)
## Processes = 122 running processes of 32768 maximum processes
###############################################################################
```

**Comment by Hilbrand** [comment]
Can you try with the correct setting of the unifios parameter: `unifios=true`.

**Comment by Orscheler** [comment]
Unfortunately this didn't solved the issue - still getting the same result.

**Comment by Hilbrand** [comment]
It could also be the port changed on UniFi (on the forum users had reported the 404 too when upgrading in the past). Can you try port `443`?

**Comment by Orscheler** [comment]
Leider ebenfalls nicht - User/Passwort sind natürlich weiterhin unverständert:

```
2023-02-10 11:46:19.574 [INFO ] [.internal.api.UniFiControllerRequest] - UniFi returned a status code 412: {
  "data": [],
  "meta": {
    "rc": "error",
    "msg": "api.err.LoginRequired"
  }
}
```

**Comment by Orscheler** [comment]
Running on a official build - Trace-Log attached.

`https://10.10.10.2:8443/proxy/network/api/self/sites` seems to be the call causing the issue.

```
2023-02-10 21:27:49.067 [INFO ] [openhab.event.ThingStatusInfoEvent  ] - Thing 'unifi:controller:home' updated: INITIALIZING
2023-02-10 21:27:49.077 [DEBUG] [.handler.UniFiControllerThingHandler] - Initializing the UniFi Controller Handler with config = UniFiControllerConfig{host = 10.10.10.2, port = 8443, username = admin, password = *****, refresh = 30, unifios = true}
2023-02-10 21:27:49.082 [INFO ] [openhab.event.ThingStatusInfoEvent  ] - Thing 'unifi:controller:home' updated: UNKNOWN
2023-02-10 21:27:49.085 [INFO ] [openhab.event.ThingStatusInfoEvent  ] - Thing 'unifi:wirelessClient:home:PhoneS' updated: INITIALIZING
2023-02-10 21:27:49.089 [INFO ] [openhab.event.ThingStatusInfoEvent  ] - Thing 'unifi:wirelessClient:home:PhoneL' updated: INITIALIZING
2023-02-10 21:27:49.098 [DEBUG] [rnal.handler.UniFiClientThingHandler] - Initializing the UniFi Client Handler with config = UniFiClientConfig{cid: '26:d5:32:1c:fd:16', site: 'HGIB9', considerHome: 600}
2023-02-10 21:27:49.102 [INFO ] [openhab.event.ThingStatusInfoEvent  ] - Thing 'unifi:wirelessClient:home:PhoneS' updated: ONLINE
2023-02-10 21:27:49.101 [DEBUG] [rnal.handler.UniFiClientThingHandler] - Initializing the UniFi Client Handler with config = UniFiClientConfig{cid: '3c:2e:ff:9f:b9:2c', site: 'HGIB9', considerHome: 600}
2023-02-10 21:27:49.101 [TRACE] [.internal.api.UniFiControllerRequest] - >> GET https://10.10.10.2:8443/
2023-02-10 21:27:49.108 [INFO ] [openhab.event.ThingStatusInfoEvent  ] - Thing 'unifi:wirelessClient:home:PhoneL' updated: ONLINE
2023-02-10 21:27:49.167 [TRACE] [.internal.api.UniFiControllerRequest] - << 200 OK 
<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><title>UniFi Network</title><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" unifi-prevent-focus-zoom><meta name="apple-itunes-app" content="app-id=1057750338"><base href="/manage/"><link rel="apple-touch-icon-precomposed" href="angular/g9491db021/images/favicons/favicon-152.png?v=2"><meta name="msapplication-TileColor" content="#0193d7"><meta name="msapplication-TileImage" content="angular/g9491db021/images/favicons/favicon-144.png?v=2"><link rel="apple-touch-icon-precomposed" sizes="152x152" href="angular/g9491db021/images/favicons/favicon-152.png?v=2"><link rel="apple-touch-icon-precomposed" sizes="144x144" href="angular/g9491db021/images/favicons/favicon-144.png?v=2"><link rel="apple-touch-icon-precomposed" sizes="120x120" href="angular/g9491db021/images/favicons/favicon-120.png?v=2"><link rel="apple-touch-icon-precomposed" sizes="72x72" href="angular/g9491db021/images/favicons/favicon-72.png?v=2"><link rel="apple-touch-icon-precomposed" href="angular/g9491db021/images/favicons/favicon-57.png?v=2"><link rel="icon" href="angular/g9491db021/images/favicons/favicon-32.png?v=2" sizes="32x32"><script src="angular/g9491db021/js/index.js" defer></script></head><body id="unifi-network-app-container"></body></html>
2023-02-10 21:27:49.170 [DEBUG] [.internal.api.UniFiControllerRequest] - Body parameters for request '/api/auth/login': {"remember":false,"password":"********","strict":false,"username":"admin"}
2023-02-10 21:27:49.173 [TRACE] [.internal.api.UniFiControllerRequest] - >> POST https://10.10.10.2:8443/api/auth/login
2023-02-10 21:27:49.193 [INFO ] [openhab.event.ThingStatusInfoEvent  ] - Thing 'unifi:controller:home' updated: OFFLINE (COMMUNICATION_ERROR): Error communicating with the UniFi controller.
2023-02-10 21:27:49.193 [DEBUG] [.handler.UniFiControllerThingHandler] - Scheduling refresh job every 30s
2023-02-10 21:27:49.196 [TRACE] [.handler.UniFiControllerThingHandler] - Executing refresh job
2023-02-10 21:27:49.197 [INFO ] [openhab.event.ThingStatusInfoEvent  ] - Thing 'unifi:wirelessClient:home:PhoneS' updated: OFFLINE (BRIDGE_OFFLINE)
2023-02-10 21:27:49.198 [DEBUG] [.handler.UniFiControllerThingHandler] - Refreshing the UniFi Controller unifi:controller:home
2023-02-10 21:27:49.200 [INFO ] [openhab.event.ThingStatusInfoEvent  ] - Thing 'unifi:wirelessClient:home:PhoneL' updated: OFFLINE (BRIDGE_OFFLINE)
2023-02-10 21:27:49.201 [TRACE] [.internal.api.UniFiControllerRequest] - >> GET https://10.10.10.2:8443/proxy/network/api/self/sites
2023-02-10 21:27:49.217 [INFO ] [.internal.api.UniFiControllerRequest] - UniFi returned a status code 404: <!doctype html><html lang="en"><head><title>HTTP Status 404 – Not Found</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 404 – Not Found</h1></body></html>
2023-02-10 21:27:49.218 [DEBUG] [.handler.UniFiControllerThingHandler] - Unhandled exception while refreshing the UniFi Controller unifi:controller:home
org.openhab.binding.unifi.internal.api.UniFiException: Unknown HTTP status code 404 returned by the controller
        at org.openhab.binding.unifi.internal.api.UniFiControllerRequest.getContent(UniFiControllerRequest.java:168) ~[?:?]
        at org.openhab.binding.unifi.internal.api.UniFiControllerRequest.execute(UniFiControllerRequest.java:128) ~[?:?]
        at org.openhab.binding.unifi.internal.api.UniFiController.executeRequest(UniFiController.java:228) ~[?:?]
        at org.openhab.binding.unifi.internal.api.UniFiController.executeRequest(UniFiController.java:221) ~[?:?]
        at org.openhab.binding.unifi.internal.api.UniFiController.refreshSites(UniFiController.java:249) ~[?:?]
        at org.openhab.binding.unifi.internal.api.UniFiController.refresh(UniFiController.java:144) ~[?:?]
        at org.openhab.binding.unifi.internal.handler.UniFiControllerThingHandler.refresh(UniFiControllerThingHandler.java:188) ~[?:?]
        at org.openhab.binding.unifi.internal.handler.UniFiControllerThingHandler.run(UniFiControllerThingHandler.java:171) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
2023-02-10 21:27:49.227 [INFO ] [openhab.event.ThingStatusInfoEvent  ] - Thing 'unifi:controller:home' updated: OFFLINE (COMMUNICATION_ERROR): Unknown HTTP status code 404 returned by the controller
2023-02-10 21:27:49.231 [INFO ] [openhab.event.ThingStatusInfoEvent  ] - Thing 'unifi:wirelessClient:home:PhoneS' updated: OFFLINE (BRIDGE_OFFLINE)
2023-02-10 21:27:49.233 [INFO ] [openhab.event.ThingStatusInfoEvent  ] - Thing 'unifi:wirelessClient:home:PhoneL' updated: OFFLINE (BRIDGE_OFFLINE)
```

**Comment by Orscheler** [comment]
Adjusting the URL to `https://10.10.10.2:8443/api/self/sites` and the call is running without an issue. Not sure, why the prefix was implemented:

`{"meta":{"rc":"ok"},"data":[{"_id":"5c0b8990e74bd90485703177","anonymous_id":"44b0d1ca-b1d6-4fb5-9b67-ecda674d0369","attr_hidden_id":"default","attr_no_delete":true,"desc":"SSID","name":"default","role":"admin"}]}`

**Comment by Hilbrand** [comment]
Can you try with setting `unifos=false`? Because the prefix is not set when it's false.

**Comment by Hilbrand** [comment]
@Orscheler Did you try running with `unifos=false`?

**Comment by Orscheler** [comment]
Hi @Hilbrand ,
I've retested it with the `unifos=false` setting and for the Cloud Key 1 this is working fine!
Thx for your support!
