### ISSUE TITLE
[Netatmo] Supporting siren on Netatmo Presence Outdoor Camera with Siren 

### ISSUE THREAD

**Issue by multimartin** [openhab/openhab-addons#14466]
I would like to suggest the Netatmo binding enhanced for the Netatmo Presence Outdoor camera (with siren) - so that the siren gets an own on/off channel.

According to the api (dev.netatmo.com) the siren can be turned on/off as easy as you can turn the floodlight on/off.

I have tried this - and can verify that it works , as I tested with this command (security values x'd out);
`curl -X POST "https://api.netatmo.com/api/setstate" -H "accept: application/json" -H "Authorization: Bearer xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" -H  "Content-Type: application/json" -d "{\"home\":{\"id\":\"xxxxxxxxxxxxxxxxxxxxxxxxxxxxx\",\"modules\":[{\"id\":\"xx:xx:xx:xx:xx:xx\",\"siren_status\":\"sound\"}]}}"`

I can confirm that the home id (x'd out above" as well as the module id (x'd out mac address above) is exactly the same as I use in the api to turn the floodlight on/off/auto.

To turn the siren off again, the siren_status have to receive a "no_sound".

I will be very happy to test when implemented - as I have the device at hand.

**Comment by clinique** [comment]
Thanks for opening this PR. Could you please make me a screenshot of the siren group values in your Presence thing ? I have a doubt on two values regarding "status" and "sirenStatus".

**Comment by multimartin** [comment]
These are the snapshots of the thing for my presence. There is no Siren group...

![Skærmbillede 2023-02-21 180447](https://user-images.githubusercontent.com/15985474/220415470-9d70352b-d464-4e9d-8dfc-48ba5de1b799.png)

![Skærmbillede 2023-02-21 181517](https://user-images.githubusercontent.com/15985474/220414834-e8e1ed1f-dec7-4a93-af07-f37325c23263.png)
![Skærmbillede 2023-02-21 181535](https://user-images.githubusercontent.com/15985474/220414851-f3ec9f59-bfb8-4a1f-8e6c-f500082734ca.png)

**Comment by clinique** [comment]
Don't you have a "Siren" group ?

**Comment by multimartin** [comment]
no - ref. the screenshots

**Comment by clinique** [comment]
> no - ref. the screenshots

Ok, this is a good starting point :-)

**Comment by clinique** [comment]
Could you please try [this version](https://github.com/clinique/marketplace/blob/main/org.openhab.binding.netatmo-4.0.0-SNAPSHOT-23022023.jar).

You'll have to trash your presence thing and recreate it. A new channel should be presented in the "Presence" group named "siren".
Let me know.

**Comment by multimartin** [comment]
will it work on OH 3.4 ?

**Comment by clinique** [comment]
It could if you're on Java 17

Le jeu. 23 févr. 2023, 20:16, multimartin ***@***.***> a
écrit :

**Comment by multimartin** [comment]
OK - good oppertunity to upgrade ;-) - I am now on 3.4.2 with Java 17.
However, the .jar file won't load. Is it corrupt ?

**Comment by clinique** [comment]
No, I'm not sure a v4 binding can work with v3.4.2

**Comment by multimartin** [comment]
OK. I get it now. I tried to update my installation to latest snapshot 4.0.0 - but too many things stopped working/gives errors - and I need to wait upgrading my "production setup" until it is more stable/I have the time to fix whatever changes happened.

I will try to spin up a parallel installation to test your updated binding in a 4.0 environment, but that may take me a few days to get working. I will be back when I can. Thanks for the effort so far !

**Comment by multimartin** [comment]
I got a OH 4 + Java 17 server up and running to test the v4 binding. The floodlight function seem to work (see comment in seperate issue) - but the siren doesnt. With the new version of the binding, I now have a siren channel;

![image](https://user-images.githubusercontent.com/15985474/221504918-0bed1bc7-20c3-4d3f-bf8e-f584f911d08e.png)

However - it does not sync its state.

This is the error in my log when I try to switch the channel in the OH UI:

`2023-02-27 08:52:24.875 [TRACE] [mo.internal.handler.ApiBridgeHandler] - executeUri POST  https://api.netatmo.com/api/setstate 
2023-02-27 08:52:25.064 [TRACE] [mo.internal.handler.ApiBridgeHandler] - executeUri returned : code [400 Bad Request] body {"error":{"code":21,"message":"property /home/modules/0: should NOT have additional properties ['siren_status']"}}
2023-02-27 08:52:25.069 [DEBUG] [mo.internal.handler.ApiBridgeHandler] - Error deserializing payload from error response
org.openhab.binding.netatmo.internal.api.NetatmoException: Rest call failed: statusCode=INVALID_ARGUMENT, message=property /home/modules/0: should NOT have additional properties ['siren_status']
	at org.openhab.binding.netatmo.internal.handler.ApiBridgeHandler.executeUri(ApiBridgeHandler.java:277) ~[?:?]
	at org.openhab.binding.netatmo.internal.api.RestManager.executeUri(RestManager.java:67) ~[?:?]
	at org.openhab.binding.netatmo.internal.api.RestManager.post(RestManager.java:57) ~[?:?]
	at org.openhab.binding.netatmo.internal.api.SecurityApi.changeSirenStatus(SecurityApi.java:134) ~[?:?]
	at org.openhab.binding.netatmo.internal.handler.capability.SecurityCapability.lambda$23(SecurityCapability.java:246) ~[?:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at org.openhab.binding.netatmo.internal.handler.capability.SecurityCapability.changeSirenStatus(SecurityCapability.java:244) ~[?:?]
	at org.openhab.binding.netatmo.internal.handler.capability.PresenceCapability.lambda$0(PresenceCapability.java:61) ~[?:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at org.openhab.binding.netatmo.internal.handler.capability.PresenceCapability.handleCommand(PresenceCapability.java:61) ~[?:?]
	at org.openhab.binding.netatmo.internal.handler.CommonInterface.lambda$10(CommonInterface.java:171) ~[?:?]
	at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4780) [?:?]
	at org.openhab.binding.netatmo.internal.handler.CommonInterface.commonHandleCommand(CommonInterface.java:171) [bundleFile:?]
	at org.openhab.binding.netatmo.internal.handler.ModuleHandler.handleCommand(ModuleHandler.java:72) [bundleFile:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.openhab.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:147) [bundleFile:?]
	at org.openhab.core.internal.common.InvocationHandlerSync.invoke(InvocationHandlerSync.java:59) [bundleFile:?]
	at jdk.proxy68.$Proxy174.handleCommand(Unknown Source) [?:?]
	at org.openhab.core.thing.internal.profiles.ProfileCallbackImpl.handleCommand(ProfileCallbackImpl.java:85) [bundleFile:?]
	at org.openhab.core.thing.internal.profiles.SystemDefaultProfile.onCommandFromItem(SystemDefaultProfile.java:48) [bundleFile:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.openhab.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:147) [bundleFile:?]
	at org.openhab.core.internal.common.Invocation.call(Invocation.java:52) [bundleFile:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
2023-02-27 08:52:25.375 [WARN ] [andler.capability.SecurityCapability] - Error changing siren status 'SOUND' : Bad Request
`

**Comment by clinique** [comment]
Noticed. I'll be away 3 days. Will resume work on this end of week

**Comment by clinique** [comment]
I do not see the difference between the request I send, and the one you curl'ed in the first post of this topic. Can you, using trace log, try to identify what's wrong / different from your own script ?

**Comment by clinique** [comment]
@multimartin : have you seen my question ?

**Comment by multimartin** [comment]
yes - will look at this later today or tomorrow. I am not sure I know what to look for - but will come back to you

**Comment by clinique** [comment]
Try to see if the emitted request is correct toward the one you put above. I get the same error but have no siren - so for me the error seems quite normal. BTW, digging in the documentation, the siren activation is not currently present.

**Comment by multimartin** [comment]
I am still getting the error:

`2023-03-04 15:06:04.463 [TRACE] [mo.internal.handler.ApiBridgeHandler] - executeUri POST  https://api.netatmo.com/api/setstate 
2023-03-04 15:06:04.517 [TRACE] [mo.internal.handler.ApiBridgeHandler] - executeUri returned : code [400 Bad Request] body {"error":{"code":21,"message":"property /home/modules/0: should NOT have additional properties ['siren_status']"}}
2023-03-04 15:06:04.532 [DEBUG] [mo.internal.handler.ApiBridgeHandler] - Error deserializing payload from error response
org.openhab.binding.netatmo.internal.api.NetatmoException: Rest call failed: statusCode=INVALID_ARGUMENT, message=property /home/modules/0: should NOT have additional properties ['siren_status']
	at org.openhab.binding.netatmo.internal.handler.ApiBridgeHandler.executeUri(ApiBridgeHandler.java:277) ~[?:?]
	at org.openhab.binding.netatmo.internal.api.RestManager.executeUri(RestManager.java:67) ~[?:?]
	at org.openhab.binding.netatmo.internal.api.RestManager.post(RestManager.java:57) ~[?:?]
	at org.openhab.binding.netatmo.internal.api.SecurityApi.changeSirenStatus(SecurityApi.java:134) ~[?:?]
	at org.openhab.binding.netatmo.internal.handler.capability.SecurityCapability.lambda$23(SecurityCapability.java:246) ~[?:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at org.openhab.binding.netatmo.internal.handler.capability.SecurityCapability.changeSirenStatus(SecurityCapability.java:244) ~[?:?]
	at org.openhab.binding.netatmo.internal.handler.capability.PresenceCapability.lambda$0(PresenceCapability.java:61) ~[?:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at org.openhab.binding.netatmo.internal.handler.capability.PresenceCapability.handleCommand(PresenceCapability.java:61) ~[?:?]
	at org.openhab.binding.netatmo.internal.handler.CommonInterface.lambda$10(CommonInterface.java:171) ~[?:?]
	at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4780) [?:?]
	at org.openhab.binding.netatmo.internal.handler.CommonInterface.commonHandleCommand(CommonInterface.java:171) [bundleFile:?]
	at org.openhab.binding.netatmo.internal.handler.ModuleHandler.handleCommand(ModuleHandler.java:72) [bundleFile:?]
	at jdk.internal.reflect.GeneratedMethodAccessor175.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.openhab.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:147) [bundleFile:?]
	at org.openhab.core.internal.common.InvocationHandlerSync.invoke(InvocationHandlerSync.java:59) [bundleFile:?]
	at jdk.proxy100.$Proxy207.handleCommand(Unknown Source) [?:?]
	at org.openhab.core.thing.internal.profiles.ProfileCallbackImpl.handleCommand(ProfileCallbackImpl.java:85) [bundleFile:?]
	at org.openhab.core.thing.internal.profiles.SystemDefaultProfile.onCommandFromItem(SystemDefaultProfile.java:48) [bundleFile:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.openhab.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:147) [bundleFile:?]
	at org.openhab.core.internal.common.Invocation.call(Invocation.java:52) [bundleFile:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
2023-03-04 15:06:04.546 [WARN ] [andler.capability.SecurityCapability] - Error changing siren status 'SOUND' : Bad Request`

I cannot see in this error message, what happens when the post is sent - i.e. if it is formatted wrongly...
Sorry that I cannot be of more help - I haven't learned to understand the java code in the bindings to do digging in the code myself yet...

**Comment by multimartin** [comment]
Diving into some of the binding files, I can see that the definition of the siren channel has: `<state pattern="%s" readOnly="true">`. Could this be the issue - if the binding don't expect the siren channel to be updated but only used to reflect the current state from the API ?

**Comment by clinique** [comment]
The important part is this one : `Rest call failed: statusCode=INVALID_ARGUMENT, message=property /home/modules/0: should NOT have additional properties ['siren_status']` . This error message is returned by Netatmo API, telling it does not accept "siren_status" property. Hence, I don't see what I should do to make it work.

**Comment by clinique** [comment]
> Diving into some of the binding files, I can see that the definition of the siren channel has: `<state pattern="%s" readOnly="true">`. Could this be the issue - if the binding don't expect the siren channel to be updated but only used to reflect the current state from the API ?

This may probably be the Siren channel of the Siren module (not the one of the Presence).

**Comment by multimartin** [comment]
> The important part is this one : `Rest call failed: statusCode=INVALID_ARGUMENT, message=property /home/modules/0: should NOT have additional properties ['siren_status']` . This error message is returned by Netatmo API, telling it does not accept "siren_status" property. Hence, I don't see what I should do to make it work.

Is it somehow possible to trace the contents of the POST to the API ? - as mentioned in my first post, the API does accept turning the siren on/off - so it has to be something about the formatting of what is from the binding ?

**Comment by multimartin** [comment]
it should look something like this:
`{
  "home": {
    "id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "modules": [
      {
        "id": "xx:xx:xx:xx:xx:xx",
        "siren_status": "sound"
      }
    ]
  }
}`

**Comment by clinique** [comment]
> it should look something like this: `{ "home": { "id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx", "modules": [ { "id": "xx:xx:xx:xx:xx:xx", "siren_status": "sound" } ] } }`

Yes, in your trace log you should see such a request sent by the binding before the error.

**Comment by multimartin** [comment]
Well - I see that a post is sent - but not the contents of it. I just see that a POST is sent to api.netatmo.com/api/setstate - but I cannot see the JSON message which is POST'ed. The line after in the log, is just the error-message from the API that the message posted was wrong.

`2023-03-04 15:04:37.406 [TRACE] [mo.internal.handler.ApiBridgeHandler] - executeUri POST  https://api.netatmo.com/api/setstate 
2023-03-04 15:04:37.445 [TRACE] [mo.internal.handler.ApiBridgeHandler] - executeUri returned : code [400 Bad Request] body {"error":{"code":21,"message":"property /home/modules/0: should NOT have additional properties ['siren_status']"}}
`

**Comment by clinique** [comment]
Ok. Good. I will provide you with an update that displays the content of the POST.

**Comment by clinique** [comment]
Here you are : [new version with more logging](https://github.com/clinique/marketplace/blob/main/org.openhab.binding.netatmo-4.0.0-SNAPSHOT-siren-05032023.jar)

**Comment by multimartin** [comment]
Thanks for the new version. I does indeed give more log-info - and I can see that the POST seem to be formatted correctly.
However, the error still remain.
This is very strange behaviour. I just tried to send the "sound" parameter to the "siren_status" and it works perfectly through CURL. Just not when through the binding.
I am at a loss ?

**Comment by clinique** [comment]
Could you try adjusting the headers sent by your curl command to these (to see if the difference lays here) : 
```
Accept-Encoding: gzip
User-Agent: Jetty/9.4.50.v20221201
Authorization: Bearer 51c55d0418xxxxxxxxxx 
Content-Type: application/json;charset=utf-8
Accept: application/json
```
