### ISSUE TITLE
[mqtt.homeassistant] Home assistant discovery null pointer exception 

### ISSUE THREAD

**Issue by miloit** [openhab/openhab-addons#14463]
Hello,

Here is one bug in the mqtt binding for the home assistant discovery throws a null pointer exception see also here https://community.openhab.org/t/warning-org-openhab-binding-mqtt-homeassistant-internal-discovery-homeassistantdiscovery-publishresults/144271/3

`java.lang.NullPointerException: null
	at org.openhab.binding.mqtt.generic.MqttChannelTypeProvider.derive(MqttChannelTypeProvider.java:132) ~[?:?]
	at org.openhab.binding.mqtt.homeassistant.internal.discovery.HomeAssistantDiscovery.publishResults(HomeAssistantDiscovery.java:248) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]`

It was already there in a previous version according to here https://community.openhab.org/t/broken-homeassistant-mqtt-discovery/125102/10

It was solved or is still there.......

**Comment by ccutrer** [comment]
Can you test again with the latest snapshot? If it still fails, can you post your MQTT Home Assistant discovery topics and values, so we can try to reproduce?

**Comment by miloit** [comment]
It can be closed..no issues any more....
