### ISSUE TITLE
[network] PresenceDetectionTest unstable

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-addons#14472]
This test failed in a GHA Windows build: https://github.com/wborn/openhab-addons/actions/runs/4233027883/jobs/7353466566

```
[ERROR] Tests run: 4, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.863 s <<< FAILURE! - in org.openhab.binding.network.internal.PresenceDetectionTest
[ERROR] org.openhab.binding.network.internal.PresenceDetectionTest.partialAndFinalCallbackTests  Time elapsed: 0.57 s  <<< FAILURE!
org.mockito.exceptions.verification.TooFewActualInvocations: 

listener.partialDetectionResult(<any>);
Wanted 3 times:
-> at org.openhab.binding.network.internal.PresenceDetectionTest.partialAndFinalCallbackTests(PresenceDetectionTest.java:130)
But was 2 times:
-> at org.openhab.binding.network.internal.PresenceDetection.lambda$6(PresenceDetection.java:460)
-> at org.openhab.binding.network.internal.PresenceDetection.lambda$9(PresenceDetection.java:540)

	at org.openhab.binding.network.internal.PresenceDetectionTest.partialAndFinalCallbackTests(PresenceDetectionTest.java:130)
```

**Comment by wborn** [comment]
Still unstable: https://github.com/wborn/openhab-addons/actions/runs/6024903414/job/16352721081

```
[ERROR] Tests run: 4, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.743 s <<< FAILURE! -- in org.openhab.binding.network.internal.PresenceDetectionTest
[ERROR] org.openhab.binding.network.internal.PresenceDetectionTest.threadCountTest -- Time elapsed: 0.009 s <<< FAILURE!
java.lang.AssertionError: 

Expected: is <3>
     but: was <0>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
	at org.openhab.binding.network.internal.PresenceDetectionTest.threadCountTest(PresenceDetectionTest.java:106)
```

**Comment by lsiepel** [comment]
The test has not failed recently. The refactoring in https://github.com/openhab/openhab-addons/pull/17972 makes the detection run synchronous (in test), so less likely to be unstable.

I suggest to close it for now and if it happens again we can further investigate.
