### ISSUE TITLE
[somfytahoma] unable to register events after a week

### ISSUE THREAD

**Issue by panis16** [openhab/openhab-addons#14530]
Ruling ok, but binding and gateway stops, more or less, after a week.

Status:
OFFLINE
COMMUNICATION_ERROR
unable to register events

Refresh
7200
Status Timeout
6000
Retries
1
Retry delay
20000

LAN mode and developer mode active with last release.

what are appropiate values for refresh and status timeout?

thx

**Comment by lsiepel** [comment]
Do you have debug logs available? That would help analyse the problem.

**Comment by sid3windr** [comment]
I have the same issue with developer mode on - in cloud mode it is working. How can I get yo uthe debug log?

I am using the Somfy Connectivity Kit. Not after a week here because I only have the kit for a few days...

**Comment by YinYangDD** [comment]
Are there any updates? Issue occurs since three days on my site. Neither with local mode or cloud mode.
Logfile says:
`
2023-06-09 07:32:05.995 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'somfytahoma:bridge:****' changed from OFFLINE (COMMUNICATION_ERROR) to OFFLINE (COMMUNICATION_ERROR): unable to register events
`
and
`
2023-06-09 07:32:56.084 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception: 

java.lang.NullPointerException: null

	at org.openhab.binding.somfytahoma.internal.handler.SomfyTahomaBridgeHandler.sendRequestBuilderCloud(SomfyTahomaBridgeHandler.java:837) ~[?:?]

	at org.openhab.binding.somfytahoma.internal.handler.SomfyTahomaBridgeHandler.sendRequestBuilder(SomfyTahomaBridgeHandler.java:829) ~[?:?]

	at org.openhab.binding.somfytahoma.internal.handler.SomfyTahomaBridgeHandler.login(SomfyTahomaBridgeHandler.java:266) ~[?:?]

	at org.openhab.binding.somfytahoma.internal.handler.SomfyTahomaBridgeHandler.reLogin(SomfyTahomaBridgeHandler.java:1021) ~[?:?]

	at org.openhab.binding.somfytahoma.internal.handler.SomfyTahomaBridgeHandler.getTahomaUpdates(SomfyTahomaBridgeHandler.java:571) ~[?:?]

	at org.openhab.binding.somfytahoma.internal.handler.SomfyTahomaBridgeHandler.lambda$4(SomfyTahomaBridgeHandler.java:221) ~[?:?]

	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]

	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]

	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]

	at java.lang.Thread.run(Thread.java:829) [?:?]

`
I'm using openHab 3.4.4.

**Comment by lsiepel** [comment]
Several connection [related PR's](https://github.com/openhab/openhab-addons/pulls?q=is%3Apr+in%3Atitle+somfytahoma+is%3Aclosed+merged%3A2023-01-01..2025-01-01+) have been merged since 3.4.4 Could you confirm this still happens in openHAB 4.2.x and if so provide a fresh debug log ?
