### ISSUE TITLE
[InfluxDB] stopped working for diff_last graphs with OH 4.M1

### ISSUE THREAD

**Issue by LukasA83** [openhab/openhab-addons#14593]
## Expected Behavior

Analyze an item, select an aggregation, e.g. per day, with "diff_last" and see the chart showing delta values per day as bar chart. 

## Current Behavior
Trying the above results in no change when changing aggregation to "diff_last" with an exception in log:

```
2023-03-12 20:55:46.162 [ERROR] [internal.JSONResponseExceptionMapper] - Unexpected exception occurred while processing REST request.
com.influxdb.exceptions.BadRequestException: error in building plan while starting program: cannot query an empty range
	at com.influxdb.internal.AbstractRestClient.responseToError(AbstractRestClient.java:96) ~[?:?]
	at com.influxdb.internal.AbstractQueryApi$1.onResponse(AbstractQueryApi.java:145) ~[?:?]
	at com.influxdb.internal.AbstractQueryApi.query(AbstractQueryApi.java:193) ~[?:?]
	at com.influxdb.internal.AbstractQueryApi.query(AbstractQueryApi.java:104) ~[?:?]
	at com.influxdb.client.internal.QueryApiImpl.query(QueryApiImpl.java:803) ~[?:?]
	at com.influxdb.client.internal.QueryApiImpl.query(QueryApiImpl.java:105) ~[?:?]
	at com.influxdb.client.internal.QueryApiImpl.query(QueryApiImpl.java:83) ~[?:?]
	at com.influxdb.client.internal.QueryApiImpl.query(QueryApiImpl.java:73) ~[?:?]
	at org.openhab.persistence.influxdb.internal.influx2.InfluxDB2RepositoryImpl.query(InfluxDB2RepositoryImpl.java:157) ~[?:?]
	at org.openhab.persistence.influxdb.InfluxDBPersistenceService.query(InfluxDBPersistenceService.java:187) ~[?:?]
	at org.openhab.core.io.rest.core.internal.persistence.PersistenceResource.createDTO(PersistenceResource.java:352) ~[?:?]
	at org.openhab.core.io.rest.core.internal.persistence.PersistenceResource.getItemHistoryDTO(PersistenceResource.java:226) ~[?:?]
	at org.openhab.core.io.rest.core.internal.persistence.PersistenceResource.httpGetPersistenceItemData(PersistenceResource.java:175) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor64.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179) ~[bundleFile:3.4.5]
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96) ~[bundleFile:3.4.5]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201) ~[bundleFile:3.4.5]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104) ~[bundleFile:3.4.5]
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59) ~[bundleFile:3.4.5]
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96) ~[bundleFile:3.4.5]
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308) ~[bundleFile:3.4.5]
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121) ~[bundleFile:3.4.5]
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:265) ~[bundleFile:3.4.5]
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234) ~[bundleFile:3.4.5]
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208) ~[bundleFile:3.4.5]
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160) ~[bundleFile:3.4.5]
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225) ~[bundleFile:3.4.5]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:298) ~[bundleFile:3.4.5]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doGet(AbstractHTTPServlet.java:222) ~[bundleFile:3.4.5]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:497) ~[bundleFile:4.0.4]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:273) ~[bundleFile:3.4.5]
	at org.ops4j.pax.web.service.spi.servlet.OsgiInitializedServlet.service(OsgiInitializedServlet.java:102) ~[bundleFile:?]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799) ~[bundleFile:9.4.50.v20221201]
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1656) ~[bundleFile:9.4.50.v20221201]
	at org.ops4j.pax.web.service.spi.servlet.OsgiFilterChain.doFilter(OsgiFilterChain.java:100) ~[bundleFile:?]
	at org.ops4j.pax.web.service.jetty.internal.PaxWebServletHandler.doHandle(PaxWebServletHandler.java:310) ~[bundleFile:?]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) ~[bundleFile:9.4.50.v20221201]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:600) ~[bundleFile:9.4.50.v20221201]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[bundleFile:9.4.50.v20221201]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235) ~[bundleFile:9.4.50.v20221201]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624) ~[bundleFile:9.4.50.v20221201]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[bundleFile:9.4.50.v20221201]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1440) ~[bundleFile:9.4.50.v20221201]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) ~[bundleFile:9.4.50.v20221201]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:505) ~[bundleFile:9.4.50.v20221201]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594) ~[bundleFile:9.4.50.v20221201]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) ~[bundleFile:9.4.50.v20221201]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355) ~[bundleFile:9.4.50.v20221201]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[bundleFile:9.4.50.v20221201]
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:234) ~[bundleFile:9.4.50.v20221201]
	at org.ops4j.pax.web.service.jetty.internal.PrioritizedHandlerCollection.handle(PrioritizedHandlerCollection.java:96) ~[bundleFile:?]
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:772) ~[bundleFile:9.4.50.v20221201]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[bundleFile:9.4.50.v20221201]
	at org.eclipse.jetty.server.Server.handle(Server.java:516) ~[bundleFile:9.4.50.v20221201]
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487) ~[bundleFile:9.4.50.v20221201]
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732) ~[bundleFile:9.4.50.v20221201]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479) ~[bundleFile:9.4.50.v20221201]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277) ~[bundleFile:9.4.50.v20221201]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) ~[bundleFile:9.4.50.v20221201]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) ~[bundleFile:9.4.50.v20221201]
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) ~[bundleFile:9.4.50.v20221201]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338) ~[bundleFile:9.4.50.v20221201]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315) ~[bundleFile:9.4.50.v20221201]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173) ~[bundleFile:9.4.50.v20221201]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131) ~[bundleFile:9.4.50.v20221201]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409) ~[bundleFile:9.4.50.v20221201]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883) ~[bundleFile:9.4.50.v20221201]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034) ~[bundleFile:9.4.50.v20221201]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

## Possible Solution
Did not find any, ao far.

## Steps to Reproduce (for Bugs)

1. See above under expected behaviour.
2.

## Your Environment

* Version used: 4.0.M1
* Environment name and version: Independent of browser
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): Raspi 4b with Ubuntu 22 running Openhab in a docker container

**Comment by J-N-K** [comment]
Works fine for me (on MacOS):

<img width="1321" alt="Bildschirm­foto 2023-03-12 um 21 17 11" src="https://user-images.githubusercontent.com/5159123/224571091-32f17314-4277-4148-aab4-efe3bf9b740e.png">

What type of item is that? And does the error only occur when using aggregates (i.e. "Analyze" shows all values)?

**Comment by LukasA83** [comment]
All of the sudden it started to work, not sure what changed. I use a predefined chart and have done no changes. Anyway thank you for now, will close the issue and see, if it occurs again.

**Comment by LukasA83** [comment]
Ok, it becomes more and more weired. I tried it with a Number item holding the outside temperature. If I just change to fixed range, it works with any aggregation but "diff_last". It occurs since my upgrade to OH 4 M1. Might it be related to the time of day?

**Comment by LukasA83** [comment]
I have increased the log level and it seems the query generated is wrong, start is after now:

`2023-03-15 02:39:27.471 [TRACE] [.influxdb.InfluxDBPersistenceService] - Query-Filter: itemname: Vitodata_General_Temp_ats_r, ordering: ASCENDING, state: null,  operator: EQ, getBeginDate: 2023-03-15T22:59:59.999Z, getEndDate: null, getPageSize: 1, getPageNumber: 0
2023-03-15 02:39:27.472 [TRACE] [.influxdb.InfluxDBPersistenceService] - Query from(bucket:"openhab_db")
	|> range(start:2023-03-15T22:59:59.999000000Z)
	|> filter(fn: (r) => r["_measurement"] == "Vitodata_General_Temp_ats_r")
	|> keep(columns:["_measurement", "_time", "_value"])
	|> sort(desc:false, columns:["_time"])
	|> limit(n:1, offset:0)`

**Comment by J-N-K** [comment]
Can you please check in the browser what is actually requested? This might be a front-end issue.

**Comment by LukasA83** [comment]
Request looks correct to me:
https://openhab.fritz.box/rest/persistence/items/Vitodata_General_Temp_ats_r?starttime=2023-03-15T23:00:00.000Z&endtime=2023-03-16T22:59:59.999Z&boundary=true

**Comment by J-N-K** [comment]
Can you please show both (request and generated query to InfluxDB)together? I have the impression that is a timezone issue if `boundary=true` is set and the database time and requested time (or systems local time) have different timezones.

**Comment by LukasA83** [comment]
Working (boundary = false):

`/rest/persistence/items/Vitodata_General_Temp_ats_r?starttime=2023-03-16T23%3A00%3A00.000Z&endtime=2023-03-17T22%3A59%3A59.999Z&boundary=false`
results in:
`2023-03-17 08:23:12.259 [TRACE] [.influxdb.InfluxDBPersistenceService] - Query-Filter: itemname: Vitodata_General_Temp_ats_r, ordering: ASCENDING, state: null,  operator: EQ, getBeginDate: 2023-03-16T23:00Z, getEndDate: 2023-03-17T22:59:59.999Z, getPageSize: 2147483647, getPageNumber: 0
2023-03-17 08:23:12.260 [TRACE] [.influxdb.InfluxDBPersistenceService] - Query from(bucket:"openhab_db")
	|> range(start:2023-03-16T23:00:00.000000000Z, stop:2023-03-17T22:59:59.999000000Z)
	|> filter(fn: (r) => r["_measurement"] == "Vitodata_General_Temp_ats_r")
	|> keep(columns:["_measurement", "_time", "_value"])
	|> sort(desc:false, columns:["_time"])`

not working (boundary=true):
`/rest/persistence/items/Vitodata_General_Temp_ats_r?starttime=2023-03-16T23%3A00%3A00.000Z&endtime=2023-03-17T22%3A59%3A59.999Z&boundary=true`
results in:
`2023-03-17 08:23:12.283 [TRACE] [.influxdb.InfluxDBPersistenceService] - Query-Filter: itemname: Vitodata_General_Temp_ats_r, ordering: ASCENDING, state: null,  operator: EQ, getBeginDate: 2023-03-17T22:59:59.999Z, getEndDate: null, getPageSize: 1, getPageNumber: 0
2023-03-17 08:23:12.284 [TRACE] [.influxdb.InfluxDBPersistenceService] - Query from(bucket:"openhab_db")
	|> range(start:2023-03-17T22:59:59.999000000Z)
	|> filter(fn: (r) => r["_measurement"] == "Vitodata_General_Temp_ats_r")
	|> keep(columns:["_measurement", "_time", "_value"])
	|> sort(desc:false, columns:["_time"])
	|> limit(n:1, offset:0)`

General request headers, just if it helps:
![grafik](https://user-images.githubusercontent.com/58861945/225840559-1ac67658-6fe9-487e-a506-7a16286c8c43.png)
![grafik](https://user-images.githubusercontent.com/58861945/225840623-eab4aafb-de5b-489d-976a-55600640e2ca.png)

**Comment by J-N-K** [comment]
In the case of `boundary==true` you should see two queries, not one. Is that Influx1 or Influx2?

**Comment by LukasA83** [comment]
It is influx2.

See both checks:
boundary=false:
`/rest/persistence/items/Vitodata_General_Temp_ats_r?starttime=2023-03-12T23%3A00%3A00.000Z&endtime=2023-03-19T22%3A59%3A59.999Z&boundary=false`
`2023-03-17 21:52:23.719 [TRACE] [.influxdb.InfluxDBPersistenceService] - Query-Filter: itemname: Vitodata_General_Temp_ats_r, ordering: ASCENDING, state: null,  operator: EQ, getBeginDate: 2023-03-12T23:00Z, getEndDate: 2023-03-19T22:59:59.999Z, getPageSize: 2147483647, getPageNumber: 0
2023-03-17 21:52:23.721 [TRACE] [.influxdb.InfluxDBPersistenceService] - Query from(bucket:"openhab_db")
	|> range(start:2023-03-12T23:00:00.000000000Z, stop:2023-03-19T22:59:59.999000000Z)
	|> filter(fn: (r) => r["_measurement"] == "Vitodata_General_Temp_ats_r")
	|> keep(columns:["_measurement", "_time", "_value"])
	|> sort(desc:false, columns:["_time"])`

boundary=true:
`/rest/persistence/items/Vitodata_General_Temp_ats_r?starttime=2023-03-12T23%3A00%3A00.000Z&endtime=2023-03-19T22%3A59%3A59.999Z&boundary=true`
`2023-03-17 21:55:33.599 [TRACE] [.influxdb.InfluxDBPersistenceService] - Query-Filter: itemname: Vitodata_General_Temp_ats_r, ordering: DESCENDING, state: null,  operator: EQ, getBeginDate: null, getEndDate: 2023-03-12T23:00Z, getPageSize: 1, getPageNumber: 0
2023-03-17 21:55:33.600 [TRACE] [.influxdb.InfluxDBPersistenceService] - Query from(bucket:"openhab_db")
	|> range(start:-100y, stop:2023-03-12T23:00:00.000000000Z)
	|> filter(fn: (r) => r["_measurement"] == "Vitodata_General_Temp_ats_r")
	|> keep(columns:["_measurement", "_time", "_value"])
	|> last()
2023-03-17 21:55:33.714 [TRACE] [.influxdb.InfluxDBPersistenceService] - Query-Filter: itemname: Vitodata_General_Temp_ats_r, ordering: ASCENDING, state: null,  operator: EQ, getBeginDate: 2023-03-12T23:00Z, getEndDate: 2023-03-19T22:59:59.999Z, getPageSize: 2147483647, getPageNumber: 0
2023-03-17 21:55:33.715 [TRACE] [.influxdb.InfluxDBPersistenceService] - Query from(bucket:"openhab_db")
	|> range(start:2023-03-12T23:00:00.000000000Z, stop:2023-03-19T22:59:59.999000000Z)
	|> filter(fn: (r) => r["_measurement"] == "Vitodata_General_Temp_ats_r")
	|> keep(columns:["_measurement", "_time", "_value"])
	|> sort(desc:false, columns:["_time"])
2023-03-17 21:55:33.772 [TRACE] [.influxdb.InfluxDBPersistenceService] - Query-Filter: itemname: Vitodata_General_Temp_ats_r, ordering: ASCENDING, state: null,  operator: EQ, getBeginDate: 2023-03-19T22:59:59.999Z, getEndDate: null, getPageSize: 1, getPageNumber: 0
2023-03-17 21:55:33.773 [TRACE] [.influxdb.InfluxDBPersistenceService] - Query from(bucket:"openhab_db")
	|> range(start:2023-03-19T22:59:59.999000000Z)
	|> filter(fn: (r) => r["_measurement"] == "Vitodata_General_Temp_ats_r")
	|> keep(columns:["_measurement", "_time", "_value"])
	|> sort(desc:false, columns:["_time"])
	|> limit(n:1, offset:0)
2023-03-17 21:55:33.796 [ERROR] [internal.JSONResponseExceptionMapper] - Unexpected exception occurred while processing REST request.
com.influxdb.exceptions.BadRequestException: error in building plan while starting program: cannot query an empty range
	at com.influxdb.internal.AbstractRestClient.responseToError(AbstractRestClient.java:96) ~[?:?]
	at com.influxdb.internal.AbstractQueryApi$1.onResponse(AbstractQueryApi.java:145) ~[?:?]
	at com.influxdb.internal.AbstractQueryApi.query(AbstractQueryApi.java:193) ~[?:?]
	at com.influxdb.internal.AbstractQueryApi.query(AbstractQueryApi.java:104) ~[?:?]
	at com.influxdb.client.internal.QueryApiImpl.query(QueryApiImpl.java:803) ~[?:?]
	at com.influxdb.client.internal.QueryApiImpl.query(QueryApiImpl.java:105) ~[?:?]
	at com.influxdb.client.internal.QueryApiImpl.query(QueryApiImpl.java:83) ~[?:?]
	at com.influxdb.client.internal.QueryApiImpl.query(QueryApiImpl.java:73) ~[?:?]
	at org.openhab.persistence.influxdb.internal.influx2.InfluxDB2RepositoryImpl.query(InfluxDB2RepositoryImpl.java:157) ~[?:?]
	at org.openhab.persistence.influxdb.InfluxDBPersistenceService.query(InfluxDBPersistenceService.java:187) ~[?:?]
	at org.openhab.core.io.rest.core.internal.persistence.PersistenceResource.createDTO(PersistenceResource.java:352) ~[?:?]
	at org.openhab.core.io.rest.core.internal.persistence.PersistenceResource.getItemHistoryDTO(PersistenceResource.java:226) ~[?:?]
	at org.openhab.core.io.rest.core.internal.persistence.PersistenceResource.httpGetPersistenceItemData(PersistenceResource.java:175) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor64.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179) ~[bundleFile:3.4.5]
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96) ~[bundleFile:3.4.5]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201) ~[bundleFile:3.4.5]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104) ~[bundleFile:3.4.5]
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59) ~[bundleFile:3.4.5]
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96) ~[bundleFile:3.4.5]
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308) ~[bundleFile:3.4.5]
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121) ~[bundleFile:3.4.5]
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:265) ~[bundleFile:3.4.5]
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234) ~[bundleFile:3.4.5]
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208) ~[bundleFile:3.4.5]
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160) ~[bundleFile:3.4.5]
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225) ~[bundleFile:3.4.5]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:298) ~[bundleFile:3.4.5]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doGet(AbstractHTTPServlet.java:222) ~[bundleFile:3.4.5]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:497) ~[bundleFile:4.0.4]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:273) ~[bundleFile:3.4.5]
	at org.ops4j.pax.web.service.spi.servlet.OsgiInitializedServlet.service(OsgiInitializedServlet.java:102) ~[bundleFile:?]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799) ~[bundleFile:9.4.50.v20221201]
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1656) ~[bundleFile:9.4.50.v20221201]
	at org.ops4j.pax.web.service.spi.servlet.OsgiFilterChain.doFilter(OsgiFilterChain.java:100) ~[bundleFile:?]
	at org.ops4j.pax.web.service.jetty.internal.PaxWebServletHandler.doHandle(PaxWebServletHandler.java:310) ~[bundleFile:?]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) ~[bundleFile:9.4.50.v20221201]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:600) ~[bundleFile:9.4.50.v20221201]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[bundleFile:9.4.50.v20221201]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235) ~[bundleFile:9.4.50.v20221201]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624) ~[bundleFile:9.4.50.v20221201]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[bundleFile:9.4.50.v20221201]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1440) ~[bundleFile:9.4.50.v20221201]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) ~[bundleFile:9.4.50.v20221201]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:505) ~[bundleFile:9.4.50.v20221201]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594) ~[bundleFile:9.4.50.v20221201]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) ~[bundleFile:9.4.50.v20221201]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355) ~[bundleFile:9.4.50.v20221201]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[bundleFile:9.4.50.v20221201]
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:234) ~[bundleFile:9.4.50.v20221201]
	at org.ops4j.pax.web.service.jetty.internal.PrioritizedHandlerCollection.handle(PrioritizedHandlerCollection.java:96) ~[bundleFile:?]
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:772) ~[bundleFile:9.4.50.v20221201]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[bundleFile:9.4.50.v20221201]
	at org.eclipse.jetty.server.Server.handle(Server.java:516) ~[bundleFile:9.4.50.v20221201]
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487) ~[bundleFile:9.4.50.v20221201]
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732) ~[bundleFile:9.4.50.v20221201]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479) ~[bundleFile:9.4.50.v20221201]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277) ~[bundleFile:9.4.50.v20221201]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) ~[bundleFile:9.4.50.v20221201]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) ~[bundleFile:9.4.50.v20221201]
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) ~[bundleFile:9.4.50.v20221201]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338) ~[bundleFile:9.4.50.v20221201]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315) ~[bundleFile:9.4.50.v20221201]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173) ~[bundleFile:9.4.50.v20221201]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131) ~[bundleFile:9.4.50.v20221201]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409) ~[bundleFile:9.4.50.v20221201]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883) ~[bundleFile:9.4.50.v20221201]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034) ~[bundleFile:9.4.50.v20221201]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]`

Seems it is generating 3 queries.

**Comment by J-N-K** [comment]
I can now reproduce it and it seems we run into https://github.com/influxdata/flux/issues/3543.

**Comment by LukasA83** [comment]
Mh it was working with OH 3.x. Any changes here, that might had a workaround implemented? Sort of regression?

**Comment by J-N-K** [comment]
InfluxDB dependencies were upgraded, it might be that the behavior in InfluxDB changed. There were no changes to the code in the persistence add-on or core. I'm working on a fix,

**Comment by LukasA83** [comment]
Thank you!
