### ISSUE TITLE
[Air Quality Binding] don't work properly with stantionid contains more than 4 symbols

### ISSUE THREAD

**Issue by Alex-Smart** [openhab/openhab-addons#14601]
##Expected Behavior
[Air Quality Binding] don't work properly with stantionid contains more than 4 symbols.
With default stationId (automatically assigned) works as desired.

##Current Behavior
When I add a custom stationId with 4 or more symbols - thing is failed to initialize:
Status: UNINITIALIZED HANDLER_INITIALIZING_ERROR
`
2023-03-14 08:50:08.153 [ERROR] [nal.common.AbstractInvocationHandler] - An error occurred while calling method 'ThingHandler.initialize()' on 'org.openhab.binding.airquality.internal.handler.AirQualityStationHandler@49eaae55': null
java.lang.NullPointerException: null
	at org.openhab.binding.airquality.internal.handler.AirQualityStationHandler.lambda$1(AirQualityStationHandler.java:117) ~[?:?]
	at java.util.Optional.ifPresent(Optional.java:183) ~[?:?]
	at org.openhab.binding.airquality.internal.handler.AirQualityStationHandler.discoverAttributes(AirQualityStationHandler.java:111) ~[?:?]
	at org.openhab.binding.airquality.internal.handler.AirQualityStationHandler.initialize(AirQualityStationHandler.java:96) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor109.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.openhab.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:154) [bundleFile:?]
	at org.openhab.core.internal.common.Invocation.call(Invocation.java:52) [bundleFile:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
2023-03-14 08:50:08.158 [ERROR] [core.thing.internal.ThingManagerImpl] - Exception occurred while initializing handler of thing 'airquality:station:main:cv_air_quality': null
java.lang.NullPointerException: null
	at org.openhab.binding.airquality.internal.handler.AirQualityStationHandler.lambda$1(AirQualityStationHandler.java:117) ~[?:?]
	at java.util.Optional.ifPresent(Optional.java:183) ~[?:?]
	at org.openhab.binding.airquality.internal.handler.AirQualityStationHandler.discoverAttributes(AirQualityStationHandler.java:111) ~[?:?]
	at org.openhab.binding.airquality.internal.handler.AirQualityStationHandler.initialize(AirQualityStationHandler.java:96) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor109.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.openhab.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:154) [bundleFile:?]
	at org.openhab.core.internal.common.Invocation.call(Invocation.java:52) [bundleFile:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
2023-03-14 08:51:00.864 [INFO ] [openhab.core.model.script.DEBUG-INFO] - System RQ end
2023-03-14 08:51:20.839 [INFO ] [el.core.internal.ModelRepositoryImpl] - Loading model 'airquality.things'
2023-03-14 08:51:21.698 [ERROR] [nal.common.AbstractInvocationHandler] - An error occurred while calling method 'ThingHandler.initialize()' on 'org.openhab.binding.airquality.internal.handler.AirQualityStationHandler@249a882b': null
java.lang.NullPointerException: null
	at org.openhab.binding.airquality.internal.handler.AirQualityStationHandler.lambda$1(AirQualityStationHandler.java:117) ~[?:?]
	at java.util.Optional.ifPresent(Optional.java:183) ~[?:?]
	at org.openhab.binding.airquality.internal.handler.AirQualityStationHandler.discoverAttributes(AirQualityStationHandler.java:111) ~[?:?]
	at org.openhab.binding.airquality.internal.handler.AirQualityStationHandler.initialize(AirQualityStationHandler.java:96) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor109.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.openhab.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:154) [bundleFile:?]
	at org.openhab.core.internal.common.Invocation.call(Invocation.java:52) [bundleFile:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
2023-03-14 08:51:21.699 [ERROR] [core.thing.internal.ThingManagerImpl] - Exception occurred while initializing handler of thing 'airquality:station:main:cv_air_quality': null
java.lang.NullPointerException: null
	at org.openhab.binding.airquality.internal.handler.AirQualityStationHandler.lambda$1(AirQualityStationHandler.java:117) ~[?:?]
	at java.util.Optional.ifPresent(Optional.java:183) ~[?:?]
	at org.openhab.binding.airquality.internal.handler.AirQualityStationHandler.discoverAttributes(AirQualityStationHandler.java:111) ~[?:?]
	at org.openhab.binding.airquality.internal.handler.AirQualityStationHandler.initialize(AirQualityStationHandler.java:96) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor109.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.openhab.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:154) [bundleFile:?]
	at org.openhab.core.internal.common.Invocation.call(Invocation.java:52) [bundleFile:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
`
failure occurs both when I create things with file and web UI. Sometimes it is not failing but nonetheless data from stationId with more than 4 symbols are missing

## Your Environment
openHAB 3.4.2

**Comment by clinique** [comment]
Could you give me an example of faultly station ID ?

**Comment by Alex-Smart** [comment]
349423, 351532, 351520
https://aqicn.org/station/@349423/
https://aqicn.org/station/@351532/
https://aqicn.org/station/@351520/

**Comment by clinique** [comment]
At this step, what I observe it that the error comes from the API, not returning any data for these stations. This is doubled by a faultly error managing in the binding that I'm going to correct.
As a workaround, you should try to access the data using alternative lat,long approach.

**Comment by Alex-Smart** [comment]
> As a workaround, you should try to access the data using alternative lat,long approach.

Im not sure I'm understanding your advise...

**Comment by jaywiseman1971** [comment]
I'm running this binding in different states, I'd be glad to test this once it's fixed.  I'm NOT using a 5 digit code on my instances though.

Best, Jay

**Comment by clinique** [comment]
> I'm running this binding in different states, I'd be glad to test this once it's fixed. I'm NOT using a 5 digit code on my instances though.
> 
> Best, Jay

I'm not sure it's related to station ID being 5 digits. The feed reports "Unknown ID" for these three stations located in Ukraine. When requested by coordinates, the answer points to Romania.

**Comment by Alex-Smart** [comment]
> Could this be related to war ?

it seems so. API disabled for Ukraine, but data is available on website. Weird.

**Comment by jlaur** [comment]
@clinique - will this issue be resolved by #14602 or is it unrelated?
