### ISSUE TITLE
[dwdunwetter] should handle properly response messages

### ISSUE THREAD

**Issue by UrsusS** [openhab/openhab-addons#14691]
The binding should handle properly the non-XML response messages.
In this case: "This service is not available due to technical problems!" The warning message "Exception occurred while parsing the XML response: Unexpected character 'T' (code 84) in prolog; expected '<' at [row,col {unknown-source}]: [1,1]" is not really helpful.

```
2023-03-27 07:33:07.918 [DEBUG] [er.internal.dto.DwdWarningDataAccess] - Refreshing Data for cell 809xxxxxx
2023-03-27 07:33:07.995 [TRACE] [er.internal.dto.DwdWarningDataAccess] - Raw request: https://maps.dwd.de/geoserver/dwd/ows?service=WFS&version=2.0.0&request=GetFeature&typeName=dwd:Warnungen_Gemeinden&CQL_FILTER=WARNCELLID+LIKE+%27809xxxxxx%27
2023-03-27 07:33:07.995 [TRACE] [er.internal.dto.DwdWarningDataAccess] - Raw response: This service is not available due to technical problems!
2023-03-27 07:33:07.996 [WARN ] [nwetter.internal.dto.DwdWarningsData] - Exception occurred while parsing the XML response: Unexpected character 'T' (code 84) in prolog; expected '<'
 at [row,col {unknown-source}]: [1,1]
2023-03-27 07:33:07.997 [DEBUG] [nwetter.internal.dto.DwdWarningsData] - Exception trace
com.ctc.wstx.exc.WstxUnexpectedCharException: Unexpected character 'T' (code 84) in prolog; expected '<'
 at [row,col {unknown-source}]: [1,1]
	at com.ctc.wstx.sr.StreamScanner.throwUnexpectedChar(StreamScanner.java:666) ~[?:?]
	at com.ctc.wstx.sr.BasicStreamReader.nextFromProlog(BasicStreamReader.java:2148) ~[?:?]
	at com.ctc.wstx.sr.BasicStreamReader.next(BasicStreamReader.java:1180) ~[?:?]
	at com.ctc.wstx.evt.WstxEventReader.nextEvent(WstxEventReader.java:283) ~[?:?]
	at org.openhab.binding.dwdunwetter.internal.dto.DwdWarningsData.refresh(DwdWarningsData.java:127) ~[?:?]
	at org.openhab.binding.dwdunwetter.internal.handler.DwdUnwetterHandler.refresh(DwdUnwetterHandler.java:96) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
2023-03-27 07:33:08.001 [DEBUG] [.internal.handler.DwdUnwetterHandler] - Failed to retrieve new data from the server.
```

This behavior exists since a long time. Currently observed with OH 3.4.1.

**Comment by lsiepel** [comment]
The method responsible for the data access is not very smart. It just calls an url and returns its body:
https://github.com/openhab/openhab-addons/blob/6115cd39a7298605735d416b3bc5c64f363d285b/bundles/org.openhab.binding.dwdunwetter/src/main/java/org/openhab/binding/dwdunwetter/internal/dto/DwdWarningDataAccess.java#L42-L65

I could not find any documentation regarding this API and errors. It could have been nice if we could react to the http response code. But at this moment the only thing i can think of is performing a check to see if the body is (valid) xml and if not, raise an IOException. Maybe @limdul79 as codewoner can give some advise?

**Comment by lsiepel** [comment]
Made a fix. Test jar 4.x is here: https://1drv.ms/u/s!AnMcxmvEeupwjrMmX76PHq61-JUHFQ?e=K0E0TR

Please let me know your test results.
