### ISSUE TITLE
[netatmo] Handler initialization fails (duplicate element)

### ISSUE THREAD

**Issue by J-N-K** [openhab/openhab-addons#14764]
I upgraded a 3.4.0 instance to 4.0.0 SNAPSHOT today and found:

```
15:57:14.040 [INFO ] [hab.event.ThingStatusInfoChangedEvent] - Thing 'netatmo:home:383aed4627:6022fd77c380915550359cfd' changed from UNINITIALIZED (NOT_YET_READY) to UNINITIALIZED (HANDLER_REGISTERING_ERROR): duplicate element: 
15:57:14.026 [ERROR] [.core.thing.internal.ThingManagerImpl] - Exception occurred while calling thing handler factory 'org.openhab.binding.netatmo.internal.NetatmoHandlerFactory@46fc12bb': duplicate element: 
java.lang.IllegalArgumentException: duplicate element: 
	at java.util.ImmutableCollections$SetN.<init>(ImmutableCollections.java:918) ~[?:?]
	at java.util.Set.of(Set.java:505) ~[?:?]
	at org.openhab.binding.netatmo.internal.handler.capability.HomeCapability.initialize(HomeCapability.java:61) ~[?:?]
	at org.openhab.binding.netatmo.internal.handler.capability.CapabilityMap.put(CapabilityMap.java:34) ~[?:?]
	at org.openhab.binding.netatmo.internal.NetatmoHandlerFactory.lambda$4(NetatmoHandlerFactory.java:148) ~[?:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at org.openhab.binding.netatmo.internal.NetatmoHandlerFactory.buildHandler(NetatmoHandlerFactory.java:120) ~[?:?]
	at org.openhab.binding.netatmo.internal.NetatmoHandlerFactory.lambda$2(NetatmoHandlerFactory.java:107) ~[?:?]
	at java.util.Optional.map(Optional.java:260) ~[?:?]
	at org.openhab.binding.netatmo.internal.NetatmoHandlerFactory.createHandler(NetatmoHandlerFactory.java:107) ~[?:?]
	at org.openhab.core.thing.binding.BaseThingHandlerFactory.registerHandler(BaseThingHandlerFactory.java:129) ~[?:?]
	at org.openhab.core.thing.internal.ThingManagerImpl.doRegisterHandler(ThingManagerImpl.java:528) ~[?:?]
	at org.openhab.core.thing.internal.ThingManagerImpl.registerHandler(ThingManagerImpl.java:516) ~[?:?]
	at org.openhab.core.thing.internal.ThingManagerImpl.registerAndInitializeHandler(ThingManagerImpl.java:924) ~[?:?]
	at org.openhab.core.thing.internal.ThingManagerImpl.checkMissingPrerequisites(ThingManagerImpl.java:1120) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

```
UID: netatmo:home:383aed4627:<id>
label: Netatmo Home
thingTypeUID: netatmo:home
configuration:
  refreshInterval: 180
  id: <id>
bridgeUID: netatmo:account:383aed4627
```

**Comment by clinique** [comment]
I've got the fix for this. Will push it soon

**Comment by lolodomo** [comment]
I just encountered the problem while I installed the snapshot 3401.
This is probably in link with PR #14595

**Comment by lolodomo** [comment]
@kaikreuzer : please do not release 4.0 milestone 2 before this issue is fixed.

**Comment by clinique** [comment]
Ok, this puts pressure on me. Pushing the PR right now.
