### ISSUE TITLE
[californium] - UdpMulticastConnector] - error: multicast set interface

### ISSUE THREAD

**Issue by Mark-VG** [openhab/openhab-addons#14847]
Since upgrading to OH4.0 I am seeing the following error in the logs. Can not see any impact on the services etc - all seems to work.

Mentioned on Comminity at: https://community.openhab.org/t/oh4-californium-elements-error-rnium-elements-udpmulticastconnector-error-multicast-set-interface/146144

```
2023-04-18 13:55:20.975 [ERROR] [rnium.elements.UdpMulticastConnector] - error: multicast set interface
java.net.SocketException: Invalid argument: no further information
	at sun.nio.ch.Net.setInterface6(Native Method) ~[?:?]
	at sun.nio.ch.DatagramChannelImpl.setOption(DatagramChannelImpl.java:364) ~[?:?]
	at sun.nio.ch.DatagramSocketAdaptor.setOption(DatagramSocketAdaptor.java:420) ~[?:?]
	at sun.nio.ch.DatagramSocketAdaptor.setNetworkInterface(DatagramSocketAdaptor.java:605) ~[?:?]
	at sun.nio.ch.DatagramSocketAdaptor.setInterface(DatagramSocketAdaptor.java:569) ~[?:?]
	at java.net.MulticastSocket.setInterface(MulticastSocket.java:405) ~[?:?]
	at org.eclipse.californium.elements.UdpMulticastConnector.start(UdpMulticastConnector.java:277) ~[?:?]
	at org.eclipse.californium.core.network.CoapEndpoint.start(CoapEndpoint.java:679) ~[?:?]
	at org.eclipse.californium.core.CoapClient.setEndpoint(CoapClient.java:366) ~[?:?]
	at org.openhab.binding.shelly.internal.api1.Shelly1CoapHandler.start(Shelly1CoapHandler.java:131) ~[?:?]
	at org.openhab.binding.shelly.internal.handler.ShellyBaseHandler.startCoap(ShellyBaseHandler.java:1072) ~[?:?]
	at org.openhab.binding.shelly.internal.handler.ShellyBaseHandler.initializeThing(ShellyBaseHandler.java:327) ~[?:?]
	at org.openhab.binding.shelly.internal.handler.ShellyBaseHandler.lambda$0(ShellyBaseHandler.java:188) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```
I use the following Bindings, but am only aware that the Shelly Binding uses Californium.

```
250 │ Active │  80 │ 4.0.0.M2               │ openHAB Add-ons :: Bundles :: Automation :: JavaScript Scripting
251 │ Active │  80 │ 4.0.0.M2               │ openHAB Add-ons :: Bundles :: Astro Binding
252 │ Active │  80 │ 4.0.0.M2               │ openHAB Add-ons :: Bundles :: Chromecast Binding
253 │ Active │  80 │ 4.0.0.M2               │ openHAB Add-ons :: Bundles :: GPSTracker Binding
254 │ Active │  80 │ 4.0.0.M2               │ openHAB Add-ons :: Bundles :: HarmonyHub Binding
255 │ Active │  80 │ 4.0.0.M2               │ openHAB Add-ons :: Bundles :: LG webOS Binding
256 │ Active │  80 │ 4.0.0.M2               │ openHAB Add-ons :: Bundles :: NTP Binding
257 │ Active │  80 │ 4.0.0.M2               │ openHAB Add-ons :: Bundles :: OpenWeatherMap Binding
258 │ Active │  80 │ 4.0.0.M2               │ openHAB Add-ons :: Bundles :: Shelly Binding Gen1+2
259 │ Active │  80 │ 4.0.0.M2               │ openHAB Add-ons :: Bundles :: Systeminfo Binding
260 │ Active │  80 │ 4.0.0.M2               │ openHAB Core :: Bundles :: Configuration UPnP Discovery
261 │ Active │  80 │ 4.0.0.M2               │ openHAB Core :: Bundles :: UPnP Transport
262 │ Active │  80 │ 4.0.0.M2               │ openHAB Add-ons :: Bundles :: IO :: openHAB Cloud Connector
263 │ Active │  80 │ 4.0.0.M2               │ openHAB Add-ons :: Bundles :: Persistence Service :: InfluxDB
264 │ Active │  80 │ 4.0.0.M2               │ openHAB Add-ons :: Bundles :: Persistence Service :: MapDB
265 │ Active │  80 │ 4.0.0.M2               │ openHAB Add-ons :: Bundles :: Persistence Service :: RRD4j
266 │ Active │  75 │ 4.0.0.M2               │ openHAB Add-ons :: Bundles :: Transformation Service :: Map
267 │ Active │  75 │ 4.0.0.M2               │ openHAB Add-ons :: Bundles :: Transformation Service :: Scale
268 │ Active │  80 │ 4.0.0.M2               │ openHAB Add-ons :: Bundles :: Voice :: Google Cloud Text-to-Speech

```
## Expected Behavior
Would expect no error in the logs 

## Current Behavior
Always get an error in the logs on restart of OH

## Steps to Reproduce (for Bugs)
Reboot machine and watch logs

## Your Environment

* Version used: openHAB 4.0.0.M2 (though also happened on 4.0.0.M1 and SNAPSHOTS
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...):
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): Windows 10/10.0 (amd64) with 17.0.6 (Zulu17.40+19-CA)

**Comment by wborn** [comment]
Does the workaround work?

**Comment by Mark-VG** [comment]
> Does the workaround work?

Sorry... edited my response above. Adding to wrapper.conf dud work. Thank you.

**Comment by markus7017** [comment]
@wborn Could I force this from the binding side?
I check Californium. 2.7.4 is the latest version for the V2.x branch, so no update there

**Comment by markus7017** [comment]
no answer
