### ISSUE TITLE
[mapdb] ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by ccutrer** [openhab/openhab-addons#14991]
I get this error in my logs a _lot_ now, and after restart openHAB things seem to have reverted to a prior state, so I suspect mapDB is not persisting _any_ new changes. I'm guessing I could just delete the persistence file and get it to regenerate to get around this, but wanted to file this to see if I should do any more debugging before I do that in order to help find the underlying issue.

```
2023-05-13 19:39:45.307 [WARN ] [org.openhab.core.items.GenericItem  ] - failed notifying listener 'org.openhab.core.persistence.internal.PersistenceManagerImpl@3f8745af' about state update of item HeatPump_SuctionPressure: Index 0 out of bounds for length 0
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
        at org.mapdb.StoreWAL.longStackPut(StoreWAL.java:976) ~[?:?]
        at org.mapdb.StoreDirect.freePhysPut(StoreDirect.java:1090) ~[?:?]
        at org.mapdb.StoreWAL.update(StoreWAL.java:393) ~[?:?]
        at org.mapdb.Caches$HashTable.update(Caches.java:270) ~[?:?]
        at org.mapdb.EngineWrapper.update(EngineWrapper.java:63) ~[?:?]
        at org.mapdb.BTreeMap.put2(BTreeMap.java:707) ~[?:?]
        at org.mapdb.BTreeMap.put(BTreeMap.java:643) ~[?:?]
        at org.openhab.persistence.mapdb.internal.MapDbPersistenceService.store(MapDbPersistenceService.java:186) ~[?:?]
        at org.openhab.core.persistence.internal.PersistenceManagerImpl.handleStateEvent(PersistenceManagerImpl.java:152) ~[?:?]
        at org.openhab.core.persistence.internal.PersistenceManagerImpl.stateChanged(PersistenceManagerImpl.java:473) ~[?:?]
        at org.openhab.core.items.GenericItem.lambda$1(GenericItem.java:268) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by ccutrer** [comment]
I forgot to say I'm on openHAB 4.0.0.M2. But given these seems to be an internal MapDB issue, and we're two major versions behind, perhaps I should just focus on updating openHAB to latest stable MapDB.

**Comment by ccutrer** [comment]
after digging in, I've decided to just give up on MapDB. it seems pathetically under-maintained, the latest version adds several large dependencies, and is way overkill for use as a persistence service that simply maintains the most recent state anyway. it was trivial for me to write a persistence service in ruby that just serializes the most recent state (after 5s) to YAML (https://gist.github.com/ccutrer/49d9aa48fbe2c0c2afe306c7c6344b42 if anyone is interested - I don't know that enough people care about the use case for the MapDB persistence service enough for me to implement in Java and get it in as a new binding)
