### ISSUE TITLE
[robonect] exception when changing thing config

### ISSUE THREAD

**Issue by chund** [openhab/openhab-addons#15001]
## Expected Behavior
I change the host in my robonect.things file (I had a typo in it)
I would expect the plugin to accept the change of the host and connect to the new fixed host.

## Current Behavior

It gives following exceptions in the openHAB log viewer.
It still uses the old host with the typo

2023-05-17 17:05:51.271 [ERROR] [ect.internal.handler.RobonectHandler] - Exception while trying to start http client
java.lang.NullPointerException: null
	at org.openhab.binding.robonect.internal.handler.RobonectHandler.initialize(RobonectHandler.java:366) [bundleFile:?]
	at org.openhab.core.thing.binding.BaseThingHandler.thingUpdated(BaseThingHandler.java:155) [bundleFile:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.openhab.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:154) [bundleFile:?]
	at org.openhab.core.internal.common.Invocation.call(Invocation.java:52) [bundleFile:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
2023-05-17 17:05:51.276 [ERROR] [nal.common.AbstractInvocationHandler] - An error occurred while calling method 'ThingHandler.thingUpdated()' on 'org.openhab.binding.robonect.internal.handler.RobonectHandler@1b69f': Exception while trying to start http client
java.lang.RuntimeException: Exception while trying to start http client
	at org.openhab.binding.robonect.internal.handler.RobonectHandler.initialize(RobonectHandler.java:370) ~[?:?]
	at org.openhab.core.thing.binding.BaseThingHandler.thingUpdated(BaseThingHandler.java:155) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.openhab.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:154) [bundleFile:?]
	at org.openhab.core.internal.common.Invocation.call(Invocation.java:52) [bundleFile:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.NullPointerException
	at org.openhab.binding.robonect.internal.handler.RobonectHandler.initialize(RobonectHandler.java:366) ~[?:?]
	... 11 more

## Possible Solution

Workaround: restart openHAB

## Steps to Reproduce (for Bugs)

1. follow instructions of documentation: https://www.openhab.org/addons/bindings/robonect/
2. configure a host with typo (not reachable)
3. change the host in config file

## Your Environment

* Version used: (e.g., openHAB and add-on versions)
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...):
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...):
openHAB 3.4.4 Release Build

**Comment by jlaur** [comment]
@chund - can you try this version? [org.openhab.binding.robonect-3.4.5-SNAPSHOT.jar](https://drive.google.com/file/d/1wpeK-9pDoFNJJcz34qGG3s8MEL7nWGjk/view?usp=sharing)

**Comment by jlaur** [comment]
@chund - any chance you could verify if the bugfix I made for you is working correctly?

**Comment by chund** [comment]
@jlaur How do I try the new version? I copied to addons folder and restartet openhab.service but it still seems the same version and the issue still occurs.

**Comment by jlaur** [comment]
> @jlaur How do I try the new version? I copied to addons folder and restartet openhab.service but it still seems the same version and the issue still occurs.

You need also to uninstall the bundled version of the binding, maybe that could be the problem?
