### ISSUE TITLE
[mikrotik] binding

### ISSUE THREAD

**Issue by sasbibic** [openhab/openhab-addons#15100]
On latest version of routeros (7.10) and openhab 3.4.4 there is warning in log at fixed interval which corresponds to refresh interval in thing. Interface counters are not returned anymore.

`2023-06-16 11:14:22.717 [WARN ] [nal.handler.MikrotikBaseThingHandler] - Unhandled exception while refreshing the mikrotik:interface:rtr:ISP Mikrotik thing
java.time.format.DateTimeParseException: Text '2023-06-16 11:03:02' could not be parsed at index 0
	at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2046) ~[?:?]
	at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1948) ~[?:?]
	at java.time.LocalDateTime.parse(LocalDateTime.java:492) ~[?:?]
	at org.openhab.binding.mikrotik.internal.util.Converter.fromRouterosTime(Converter.java:43) ~[?:?]
	at org.openhab.binding.mikrotik.internal.model.RouterosInterfaceBase.getLastLinkUpTime(RouterosInterfaceBase.java:95) ~[?:?]
	at org.openhab.binding.mikrotik.internal.handler.MikrotikInterfaceThingHandler.refreshChannel(MikrotikInterfaceThingHandler.java:141) ~[?:?]
	at org.openhab.binding.mikrotik.internal.handler.MikrotikBaseThingHandler.scheduledRun(MikrotikBaseThingHandler.java:203) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]`

**Comment by lsiepel** [comment]
In the provided excpetion, it looks like the date format is: 'yyy-MM-dd HH:mm:SS'

The expected format is "MMM/dd/yyyy kk:mm:ss",  found here: https://github.com/openhab/openhab-addons/blob/6115cd39a7298605735d416b3bc5c64f363d285b/bundles/org.openhab.binding.mikrotik/src/main/java/org/openhab/binding/mikrotik/internal/util/Converter.java#L33

I could prepare a fix, are you able to test?

**Comment by sasbibic** [comment]
I'm able to test.

Regards
/Saš

**Comment by sasbibic** [comment]
I was to quick, I'll upgrade to 4.0 this week, then I'll test. OK?

Regards
/Saš

**Comment by Kraken70** [comment]
Hi,
I can confirm that after implementing SNAPSHOT has binding correct behavior.
Good job.
