### ISSUE TITLE
[androidtv] ShiledTV Parser Issue With New Update

### ISSUE THREAD

**Issue by morph166955** [openhab/openhab-addons#15163]
Separated from #15153 as they are two issues

```
2023-06-30 16:56:06.072 [TRACE] [tocol.shieldtv.ShieldTVMessageParser] - dd406711 - Received ShieldTV message from: SHIELD - Message: 080b123808b51012330a06534849454c44189b462210363035333834333264643430363731312a0b61726d656162692d7637612a0761726d65616269180b
2023-06-30 16:56:06.073 [TRACE] [tocol.shieldtv.ShieldTVMessageParser] - dd406711 - Longer Hostname Reply
2023-06-30 16:56:06.089 [INFO ] [tocol.shieldtv.ShieldTVMessageParser] - dd406711 - Message Parser Caught Exception
java.lang.ArrayIndexOutOfBoundsException: Index 124 out of bounds for length 124
	at org.openhab.binding.androidtv.internal.protocol.shieldtv.ShieldTVMessageParser.handleMessage(ShieldTVMessageParser.java:132) ~[?:?]
	at org.openhab.binding.androidtv.internal.protocol.shieldtv.ShieldTVConnectionManager.finishReaderMessage(ShieldTVConnectionManager.java:738) ~[?:?]
	at org.openhab.binding.androidtv.internal.protocol.shieldtv.ShieldTVConnectionManager.readerThreadJob(ShieldTVConnectionManager.java:777) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

The structure that I've always observied is:
080b 12 5b08b510 12 TOTALLEN? 0a LEN Hostname 12 LEN IPADDR Padding? 22 LEN DeviceID 2a LEN arm64-v8a 2a LEN armeabi-v7a 2a LEN armeabi 180b

The offending line in comparison:
080b 12 3808b510 12 33 0a 06 534849454c44 18 9b46 22 10 36303533383433326464343036373131 2a 0b 61726d656162692d763761 2a 07 61726d65616269 180b

The difference here being that we normally see "12 LEN IPADDR Padding?" but we're getting "18 9b46" which is unexpected.

**Comment by morph166955** [comment]
Update, the problem is that padding isn't padding apparently like I had thought.

**Comment by morph166955** [comment]
Update again, my device just updated and now it's throwing the same errors as reported.  This is NOT an IPv6 issue apparently.  The IP address is now removed from the string for reasons unknown.  The attached PR fixes this exception.
