### ISSUE TITLE
[shelly] Exception: Expected a string but was BEGIN_OBJECT

### ISSUE THREAD

**Issue by mstormi** [openhab/openhab-addons#15173]
Running S3515, I keep getting this exception more or less any 2 minutes for no apparent reason.

```
2023-07-03 09:00:10.792 [ERROR] [org.openhab.core.internal.common.AbstractInvocationHandler       ] - An error occurred while calling method 'ThingHandler.handleCommand()' on 'org.openhab.binding.shelly.internal.handler.ShellyRelayHandler@f40997': java.lang.IllegalState
Exception: Expected a string but was BEGIN_OBJECT at line 1 column 2 path $
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 2 path $
        at com.google.gson.Gson.fromJson(Gson.java:1070) ~[?:?]
        at com.google.gson.Gson.fromJson(Gson.java:1016) ~[?:?]
        at com.google.gson.Gson.fromJson(Gson.java:959) ~[?:?]
        at com.google.gson.Gson.fromJson(Gson.java:927) ~[?:?]
        at org.openhab.binding.shelly.internal.api2.Shelly2ApiRpc.apiRequest(Shelly2ApiRpc.java:1064) ~[?:?]
        at org.openhab.binding.shelly.internal.api2.Shelly2ApiRpc.apiRequest(Shelly2ApiRpc.java:1073) ~[?:?]
        at org.openhab.binding.shelly.internal.api2.Shelly2ApiRpc.setRollerPos(Shelly2ApiRpc.java:764) ~[?:?]
        at org.openhab.binding.shelly.internal.handler.ShellyRelayHandler.handleRoller(ShellyRelayHandler.java:290) ~[?:?]
        at org.openhab.binding.shelly.internal.handler.ShellyRelayHandler.handleDeviceCommand(ShellyRelayHandler.java:110) ~[?:?]
        at org.openhab.binding.shelly.internal.handler.ShellyBaseHandler.handleCommand(ShellyBaseHandler.java:464) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor228.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.openhab.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:147) ~[?:?]
        at org.openhab.core.internal.common.InvocationHandlerSync.invoke(InvocationHandlerSync.java:59) ~[?:?]
        at jdk.proxy12543.$Proxy12673.handleCommand(Unknown Source) ~[?:?]
        at org.openhab.core.thing.internal.profiles.ProfileCallbackImpl.handleCommand(ProfileCallbackImpl.java:85) ~[?:?]
        at org.openhab.core.thing.internal.profiles.SystemDefaultProfile.onCommandFromItem(SystemDefaultProfile.java:48) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor361.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.openhab.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:147) ~[?:?]
        at org.openhab.core.internal.common.Invocation.call(Invocation.java:52) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by markus7017** [comment]
check the latest DEV build, I think it's fixed

https://community.openhab.org/t/shelly-binding/56862/3311?u=markus7017

**Comment by markus7017** [comment]
no response

**Comment by mstormi** [comment]
Sorry it took me longer to upgrade to validate.
Haven't seen the issue again since.
