### ISSUE TITLE
[smartmeter] TestMeterReading unstable

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-addons#15198]
This test failed in: https://github.com/openhab/openhab-addons/actions/runs/5485349584/jobs/9994059971

```
[ERROR] Tests run: 4, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 24.562 s <<< FAILURE! - in org.openhab.binding.smartmeter.TestMeterReading
[ERROR] org.openhab.binding.smartmeter.TestMeterReading.shouldNotReportToFallbackException  Time elapsed: 6.851 s  <<< FAILURE!
org.mockito.exceptions.verification.NoInteractionsWanted: 

No interactions wanted here:
-> at org.openhab.binding.smartmeter.TestMeterReading.shouldNotReportToFallbackException(TestMeterReading.java:128)
But found this interaction on mock 'consumer':
-> at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:373)
Actually, above is the only interaction with this mock.
	at org.openhab.binding.smartmeter.TestMeterReading.shouldNotReportToFallbackException(TestMeterReading.java:128)
```

Can you have a look at this @msteigenberger?

**Comment by wborn** [comment]
Another failure today: https://github.com/wborn/openhab-addons/actions/runs/6024903414/job/16352721541

```
[ERROR] Tests run: 4, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 27.67 s <<< FAILURE! -- in org.openhab.binding.smartmeter.TestMeterReading
[ERROR] org.openhab.binding.smartmeter.TestMeterReading.shouldNotReportToFallbackException -- Time elapsed: 8.673 s <<< FAILURE!
Wanted but not invoked:
meterValueListener.errorOccurred(
    <any java.util.concurrent.TimeoutException>
);
-> at org.openhab.binding.smartmeter.TestMeterReading.shouldNotReportToFallbackException(TestMeterReading.java:127)
Actually, there were zero interactions with this mock.

	at org.openhab.binding.smartmeter.TestMeterReading.shouldNotReportToFallbackException(TestMeterReading.java:127)


[ERROR] org.openhab.binding.smartmeter.TestMeterReading.testContinousReading -- Time elapsed: 5.847 s <<< FAILURE!
org.mockito.exceptions.verification.TooFewActualInvocations: 

meterValueListener.valueChanged(<any>);
Wanted 5 times:
-> at org.openhab.binding.smartmeter.TestMeterReading.testContinousReading(TestMeterReading.java:61)
But was 3 times:
-> at org.openhab.binding.smartmeter.internal.MeterDevice.lambda$9(MeterDevice.java:220)
-> at org.openhab.binding.smartmeter.internal.MeterDevice.lambda$9(MeterDevice.java:220)
-> at org.openhab.binding.smartmeter.internal.MeterDevice.lambda$9(MeterDevice.java:220)

	at org.openhab.binding.smartmeter.TestMeterReading.testContinousReading(TestMeterReading.java:61)
```

Can you fix it @msteigenberger or should we disable it?
