### ISSUE TITLE
[Tesla] Trunk does not close on OFF

### ISSUE THREAD

**Issue by sindalschmidt** [openhab/openhab-addons#15226]
## Expected Behavior

When switching Rear Trunk channel to "OFF" it should close the rear trunk.

## Current Behavior

When switching the rear trunk to "ON" the trunk opens. When switching it back to "OFF" it is expected to close. It doesn't close. If switching back to "ON" when the trunk is open, it will close.

The following error appears in the log a couple of seconds after switching the channel to OFF.
`2023-07-12 13:23:35.017 [ERROR] [nternal.items.ItemStateConverterImpl] - A conversion of null was requested:
java.lang.IllegalArgumentException: State must not be null.
	at org.openhab.core.internal.items.ItemStateConverterImpl.convertToAcceptedState(ItemStateConverterImpl.java:58) ~[?:?]
	at org.openhab.core.thing.internal.profiles.ProfileCallbackImpl.sendUpdate(ProfileCallbackImpl.java:126) ~[?:?]
	at org.openhab.core.thing.internal.profiles.SystemDefaultProfile.onStateUpdateFromHandler(SystemDefaultProfile.java:53) ~[?:?]
	at org.openhab.core.thing.internal.CommunicationManager.lambda$13(CommunicationManager.java:566) ~[?:?]
	at org.openhab.core.thing.internal.CommunicationManager.lambda$15(CommunicationManager.java:586) ~[?:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at org.openhab.core.thing.internal.CommunicationManager.handleCallFromHandler(CommunicationManager.java:582) ~[?:?]
	at org.openhab.core.thing.internal.CommunicationManager.stateUpdated(CommunicationManager.java:564) ~[?:?]
	at org.openhab.core.thing.internal.ThingManagerImpl$1.stateUpdated(ThingManagerImpl.java:178) ~[?:?]
	at org.openhab.core.thing.binding.BaseThingHandler.updateState(BaseThingHandler.java:268) ~[?:?]
	at org.openhab.core.thing.binding.BaseThingHandler.updateState(BaseThingHandler.java:287) ~[?:?]
	at org.openhab.binding.tesla.internal.handler.TeslaVehicleHandler.parseAndUpdate(TeslaVehicleHandler.java:937) ~[?:?]
	at org.openhab.binding.tesla.internal.handler.TeslaAccountHandler$Request.run(TeslaAccountHandler.java:459) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at org.openhab.binding.tesla.internal.throttler.QueueChannelThrottler.lambda$0(QueueChannelThrottler.java:45) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]`

## Context
I'm doing integration with Google Assistant, but when an "ON" command it required to close the rear trunk as well, it doesn't work as desired.

## Your Environment

* OpenHAB 3.4.4

**Comment by lsiepel** [comment]
@sindalschmidt i might be able to look at this, are you available to test? 
I just created a PR not specific to this, but would be nice if you can test: https://github.com/openhab/openhab-addons/pull/17582 
When this is tested i can try to fix the trunk handling. I already expect some improvement due to the null check in your exception log.

1. Update openHAB to 4.2.2 (preferably 4.3.0 milestone2)
2. Uninstall tesla binding (all tthings, channels etc, will not be deleted)
3. Drop the jar file into your addon folder.
4. Observe if all works as expected.
