### ISSUE TITLE
[ambient-weather] Issue with Ambient Weather Binding and Alexa voice commands

### ISSUE THREAD

**Issue by filthyjason** [openhab/openhab-addons#15221]
## Expected Behavior
From 4.0.0 M3 onward, the binding generates an error whenever I try to control any devices from my Alexa. The binding only needs to be installed for this to occur, all things, items etc are not present.

## Current Behavior
Log message comes out as:

[io.socket.thread.EventThread        ] - Task threw exception
java.lang.ClassCastException: class org.json.JSONObject cannot be cast to class org.json.JSONObject (org.json.JSONObject is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @362d844f; org.json.JSONObject is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @37e881cc)
	at org.openhab.io.openhabcloud.internal.CloudClient.lambda$15(CloudClient.java:358) ~[?:?]
	at io.socket.emitter.Emitter.emit(Emitter.java:117) ~[?:?]
	at io.socket.client.Socket.onevent(Socket.java:338) ~[?:?]
	at io.socket.client.Socket.onpacket(Socket.java:289) ~[?:?]
	at io.socket.client.Socket.access$100(Socket.java:24) ~[?:?]
	at io.socket.client.Socket$2$2.call(Socket.java:120) ~[?:?]
	at io.socket.emitter.Emitter.emit(Emitter.java:117) ~[?:?]
	at io.socket.client.Manager.ondecoded(Manager.java:431) ~[?:?]
	at io.socket.client.Manager.access$1600(Manager.java:30) ~[?:?]
	at io.socket.client.Manager$7.call(Manager.java:407) ~[?:?]
	at io.socket.parser.IOParser$Decoder.add(IOParser.java:105) ~[?:?]
	at io.socket.client.Manager.ondata(Manager.java:423) ~[?:?]
	at io.socket.client.Manager.access$1000(Manager.java:30) ~[?:?]
	at io.socket.client.Manager$2.call(Manager.java:374) ~[?:?]
	at io.socket.emitter.Emitter.emit(Emitter.java:117) ~[?:?]
	at io.socket.engineio.client.Socket.onPacket(Socket.java:551) ~[?:?]
	at io.socket.engineio.client.Socket.access$1000(Socket.java:36) ~[?:?]
	at io.socket.engineio.client.Socket$5.call(Socket.java:335) ~[?:?]
	at io.socket.emitter.Emitter.emit(Emitter.java:117) ~[?:?]
	at io.socket.engineio.client.Transport.onPacket(Transport.java:126) ~[?:?]
	at io.socket.engineio.client.Transport.onData(Transport.java:118) ~[?:?]
	at io.socket.engineio.client.transports.WebSocket.access$100(WebSocket.java:24) ~[?:?]
	at io.socket.engineio.client.transports.WebSocket$1$2.run(WebSocket.java:71) ~[?:?]
	at io.socket.thread.EventThread$2.run(EventThread.java:80) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

This seems to be reported by Openhab Cloud Connector (which restarts every time I load the binding for some reason) but with the binding removed, everything works fine.

## Possible Solution
No idea, but happy to help troubleshoot a .jar file etc

## Steps to Reproduce (for Bugs)
1. install Alexa binding TTS -> Openhab and configure at least 1 device for Alexa control (on OH 4.0.0 M3 +)
2. test a voice command
3. install Ambient Weather Binding
4. Test a voice command, view openhab.log
5. remove binding

## Context
Unable to use Ambient Weather binding for controlling smart shades based on outdoor sunlight levels, temperature and also smart lighting.

## Your Environment
Distributor ID:	Ubuntu
Description:	Ubuntu 23.04
Release:	23.04
Codename:	lunar
Openhab 4.0.0 M4 S3533-1 now, trying to see if it fixed the issue, latest Snapshot as of this post
openjdk 17.0.7 2023-04-18 LTS
OpenJDK Runtime Environment Zulu17.42+19-CA (build 17.0.7+7-LTS)
OpenJDK 64-Bit Server VM Zulu17.42+19-CA (build 17.0.7+7-LTS, mixed mode, sharing)
Running on an older Intel NUC, directly on Ubuntu, no containers etc.

**Comment by mhilbush** [comment]
I suppose PR #14803 could be reverted if the 2 versions of the json library are causing a problem.

@J-N-K @wborn WDYT?

**Comment by J-N-K** [comment]
I think the dependency should be upgraded in openhabcloud, which is the only bundle left that uses the old version

**Comment by mhilbush** [comment]
As I have no way to test openhabcloud, maybe @digitaldan would want to do a PR to bump the json version?

**Comment by digitaldan** [comment]
I’m flying back from holiday today, will take a look tomorrow or the next day.

**Comment by filthyjason** [comment]
Thanks @digitaldan 
Do you think this will be able to make it into the 4.0 release coming up, or at least a snapshot for testing?

**Comment by filthyjason** [comment]
Looks like I may be able to use the Personal Weather Station binding instead. After ~3 years, my solar went out for a few days and with my weather management down, I didn’t know until my bill almost doubled :-/ of all the timing!
I think the PWS will pull what I need at least, I’ll try it out tomorrow.

**Comment by digitaldan** [comment]
Sorry this slipped my mind, i have a PR for this shortly

**Comment by filthyjason** [comment]
Confirmed working with Snapshot 3559. Thanks for all the help with this! Closing the issue.
