### ISSUE TITLE
[bluetooth.bluez] NPE during discovery

### ISSUE THREAD

**Issue by pbloigu** [openhab/openhab-addons#15291]
## Expected Behavior
There should be no NPE. I'm not sure what else should happen, as this occurs during device discovery, and I'm not entirely sure what / which that device is. There's a huge number of bluetooth devices within range.

## Current Behavior
In the logs I see this:

```
2023-07-22 17:21:50.207 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'bluetooth:beacon:hci0:c9c6309a81a4' to inbox.
2023-07-22 17:21:50.228 [WARN ] [y.internal.BluetoothDiscoveryService] - Error occured during discovery of C9:C6:30:9A:81:A4
java.util.concurrent.CompletionException: java.lang.NullPointerException
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) [?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1702) [?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.NullPointerException
        at org.openhab.binding.bluetooth.bluez.internal.BlueZBluetoothDevice.readCharacteristic(BlueZBluetoothDevice.java:473) ~[?:?]
        at org.openhab.binding.bluetooth.DelegateBluetoothDevice.readCharacteristic(DelegateBluetoothDevice.java:111) ~[?:?]
        at org.openhab.binding.bluetooth.discovery.internal.BluetoothDiscoveryProcess.fecthGattCharacteristic(BluetoothDiscoveryProcess.java:223) ~[?:?]
        at org.openhab.binding.bluetooth.discovery.internal.BluetoothDiscoveryProcess.readDeviceInformationIfMissing(BluetoothDiscoveryProcess.java:198) ~[?:?]
        at org.openhab.binding.bluetooth.discovery.internal.BluetoothDiscoveryProcess.findConnectionResult(BluetoothDiscoveryProcess.java:174) ~[?:?]
        at org.openhab.binding.bluetooth.discovery.internal.BluetoothDiscoveryProcess.get(BluetoothDiscoveryProcess.java:98) ~[?:?]
        at org.openhab.binding.bluetooth.discovery.internal.BluetoothDiscoveryProcess.get(BluetoothDiscoveryProcess.java:1) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700) ~[?:?]
        ... 6 more
```

## Possible Solution
Unfortunately I have no solution to suggest at this time. However, by looking at the relevant code, it seems that an additional null check should be added here: https://github.com/openhab/openhab-addons/blob/2982cc891183be3ee2f2023d20434194e3b9c977/bundles/org.openhab.binding.bluetooth.bluez/src/main/java/org/openhab/binding/bluetooth/bluez/internal/BlueZBluetoothDevice.java#L473
because `com.github.hypfvieh.bluetooth.wrapper.BluetoothDevice` might return null from `isConnected()`(See the javadoc [here](https://github.com/hypfvieh/bluez-dbus/blob/0e49c67d8578984cad0de174faacdcdbc435bce7/bluez-dbus/src/main/java/com/github/hypfvieh/bluetooth/wrapper/BluetoothDevice.java#L216C20-L216C31)) and in this case it indeed seems to return null, hence the NPE when unboxing.

## Steps to Reproduce (for Bugs)
I just noticed this in the logs. I will try to narrow down the issue, maybe try to figure out which / what device that is that's causing this. 

## Context
I'm not yet sure what side effects this issue has, but I'll post updates as things unfold.

## Your Environment
Thiis is OH3.4.4 stable on RPi4 running Raspbian.

**Comment by lsiepel** [comment]
Coudl you check if this is still happening in openHAB 4.0? As several PR's relateed to bluetooth and null checks have been merged.

**Comment by lsiepel** [comment]
I could create a 4.x jar for you to test, let me know if you have time to do so.

**Comment by pbloigu** [comment]
Hi!

After upgrading my OH instance to 4.0.0 I still see the same exception in the logs from time to time. The discovered device seems to vary, so it's definitely not connected to a specific device. Here's an example:

```
2023-07-29 22:49:06.081 [WARN ] [y.internal.BluetoothDiscoveryService] - Error occured during discovery of 6D:86:E6:FA:A9:96
java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "com.github.hypfvieh.bluetooth.wrapper.BluetoothDevice.isConnected()" is null
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "com.github.hypfvieh.bluetooth.wrapper.BluetoothDevice.isConnected()" is null
        at org.openhab.binding.bluetooth.bluez.internal.BlueZBluetoothDevice.readCharacteristic(BlueZBluetoothDevice.java:472) ~[?:?]
        at org.openhab.binding.bluetooth.DelegateBluetoothDevice.readCharacteristic(DelegateBluetoothDevice.java:111) ~[bundleFile:?]
        at org.openhab.binding.bluetooth.discovery.internal.BluetoothDiscoveryProcess.fecthGattCharacteristic(BluetoothDiscoveryProcess.java:223) ~[?:?]
        at org.openhab.binding.bluetooth.discovery.internal.BluetoothDiscoveryProcess.readDeviceInformationIfMissing(BluetoothDiscoveryProcess.java:198) ~[?:?]
        at org.openhab.binding.bluetooth.discovery.internal.BluetoothDiscoveryProcess.findConnectionResult(BluetoothDiscoveryProcess.java:174) ~[?:?]
        at org.openhab.binding.bluetooth.discovery.internal.BluetoothDiscoveryProcess.get(BluetoothDiscoveryProcess.java:98) ~[?:?]
        at org.openhab.binding.bluetooth.discovery.internal.BluetoothDiscoveryProcess.get(BluetoothDiscoveryProcess.java:1) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        ... 6 more
```

As you can see  `isConnected()` returns null, which then yields an NPE when unboxing.

**Comment by jlaur** [comment]
@pbloigu - you have found the correct line causing the NPE because `dev.isConnected()` is boxed as `Boolean` which can be null, so a check is needed when unboxing. A possible fix could be:
```java
if (dev == null || dev.isConnected() == null || !dev.isConnected()) {
```

@lsiepel - please go ahead if you'd like to provide a fix, we could also get this into 4.0.2.

**Comment by lsiepel** [comment]
Test jar for 4.x: https://1drv.ms/u/s!AnMcxmvEeupwjq5h3gjs3RQsYWOHTA?e=ka9jTS

Please let me know if this fixed your issue. @jlaur, that was exactly what i wanted to do (and did)

**Comment by pbloigu** [comment]
Hi! 

Sure, I can try that out. It might take a while though as I have no idea how to trigger the NPE at will...

**Comment by lsiepel** [comment]
The PR is allready merged and the error you have is not related. Thanks!
