### ISSUE TITLE
[unifi] unable to connect

### ISSUE THREAD

**Issue by GekoCH** [openhab/openhab-addons#15309]
running OpenhAB 4.0 wiht UDM Pro v3.1.15 the binding can't connect to the UDM. See error.
Seems a openhab 4.0 problem?

```
2023-07-26 17:32:35.319 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception: 
java.lang.NoSuchMethodError: 'void org.openhab.core.library.types.DecimalType.<init>(long)'
	at org.openhab.binding.unifi.internal.handler.UniFiClientThingHandler.getWirelessChannelState(UniFiClientThingHandler.java:289) ~[?:?]
	at org.openhab.binding.unifi.internal.handler.UniFiClientThingHandler.getChannelState(UniFiClientThingHandler.java:255) ~[?:?]
	at org.openhab.binding.unifi.internal.handler.UniFiClientThingHandler.getChannelState(UniFiClientThingHandler.java:1) ~[?:?]
	at org.openhab.binding.unifi.internal.handler.UniFiBaseThingHandler.lambda$1(UniFiBaseThingHandler.java:140) ~[?:?]
	at java.util.Optional.map(Optional.java:260) ~[?:?]
	at org.openhab.binding.unifi.internal.handler.UniFiBaseThingHandler.updateState(UniFiBaseThingHandler.java:140) ~[?:?]
	at org.openhab.binding.unifi.internal.handler.UniFiBaseThingHandler.lambda$0(UniFiBaseThingHandler.java:134) ~[?:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at org.openhab.binding.unifi.internal.handler.UniFiBaseThingHandler.refresh(UniFiBaseThingHandler.java:134) ~[?:?]
	at org.openhab.binding.unifi.internal.handler.UniFiControllerThingHandler.lambda$2(UniFiControllerThingHandler.java:203) ~[?:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at org.openhab.binding.unifi.internal.handler.UniFiControllerThingHandler.refresh(UniFiControllerThingHandler.java:199) ~[?:?]
	at org.openhab.binding.unifi.internal.handler.UniFiControllerThingHandler.run(UniFiControllerThingHandler.java:175) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by mherwege** [comment]
From what I can tell, the error message does not correspond to the latest code. Could it be you are using a marketplace version or .jar version of the unifi binding in your install? Make sure you are using the version that comes with OH4. I don't have an issue in my install, but I may not be using the specific channel with the error.
Also try removing the thing and recreating it. I believe some channels got converted to having a UOM at some point.

**Comment by GekoCH** [comment]
thx for the hint I was on a BETA release from January now its working!

**Comment by lolodomo** [comment]
Maybe the beta version could be unpublished from marketplace?

**Comment by mherwege** [comment]
Here is the [marketplace](https://community.openhab.org/t/unifi-binding-beta-3-2-0-4-0-0/131156) entry, but I am not the owner and don’t have permissions to unpublish. The marketplace entry seems to be for 3.4 and not 4, so new installs shouldn’t happen. It is only when upgrading and not uninstalling this is an issue.
