### ISSUE TITLE
[googletts] Exception thrown on dispose()

### ISSUE THREAD

**Issue by seime** [openhab/openhab-addons#15303]
OH Version: 4.0.0

Happens consistently, might be related to common TTS cache implementation in OH4?

```
2023-07-25 18:09:23.186 [ERROR] [.googletts.internal.GoogleTTSService] - bundle org.openhab.voice.googletts:4.0.0 (355)[org.openhab.voice.googletts.internal.GoogleTTSService(454)] : The dispose method has thrown an exception
java.lang.UnsupportedOperationException: null
	at java.util.Collections$UnmodifiableCollection.clear(Collections.java:1086) ~[?:?]
	at org.openhab.voice.googletts.internal.GoogleTTSService.dispose(GoogleTTSService.java:139) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.apache.felix.scr.impl.inject.methods.BaseMethod.invokeMethod(BaseMethod.java:245) ~[?:?]
	at org.apache.felix.scr.impl.inject.methods.BaseMethod.access$500(BaseMethod.java:41) ~[?:?]
	at org.apache.felix.scr.impl.inject.methods.BaseMethod$Resolved.invoke(BaseMethod.java:687) ~[?:?]
...

```

**Comment by lolodomo** [comment]
> might be related to common TTS cache implementation in OH4?

No. 
It was introduced by PR #14937 . 
We try to clear an unmodified collection returned by initAudioFormats.

**Comment by lolodomo** [comment]
@jlaur : do you see a reason to return an unmodified collection? In case it is relevant, we have to remove the call to clear.

**Comment by jlaur** [comment]
> @jlaur : do you see a reason to return an unmodified collection? In case it is relevant, we have to remove the call to clear.

I don't really know this code. But a quick look:

https://github.com/openhab/openhab-addons/blob/33dd5e7f7010116146cc60cfecd16d854f41e69c/bundles/org.openhab.voice.googletts/src/main/java/org/openhab/voice/googletts/internal/GoogleTTSService.java#L260-L263

It might be undesirable to return this object to callers and enable them to mangle with it. It could be cloned here, but I'm wondering if there is a reason to `clear()` it rather than just reassigning with `audioFormats = new HashSet<>();`

**Comment by lolodomo** [comment]
Ok, you're right. 
I will submit a PR.

**Comment by lolodomo** [comment]
@seime : I assume it does not prevent using Google TTS? It is only an exception when you stop OH?
