### ISSUE TITLE
[hue] NPE at motion detector with API v2

### ISSUE THREAD

**Issue by Novanic** [openhab/openhab-addons#15311]
I'm trying to upgrade my Hue things from API v1 to API v2 via the discovery service. The motion detector throws NullPointerExceptions every few seconds:

java.lang.NullPointerException: Cannot invoke "String.toUpperCase()" because "this.lastEvent" is null
	at org.openhab.binding.hue.internal.dto.clip2.Button.getLastEvent(Button.java:36) ~[?:?]
	at org.openhab.binding.hue.internal.dto.clip2.Resource.getButtonEventState(Resource.java:191) ~[?:?]
	at org.openhab.binding.hue.internal.handler.Clip2ThingHandler.updateChannels(Clip2ThingHandler.java:787) ~[?:?]
	at org.openhab.binding.hue.internal.handler.Clip2ThingHandler.onResource(Clip2ThingHandler.java:609) ~[?:?]
	at org.openhab.binding.hue.internal.handler.Clip2ThingHandler.lambda$26(Clip2ThingHandler.java:1055) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at org.openhab.binding.hue.internal.handler.Clip2ThingHandler.updateResource(Clip2ThingHandler.java:1055) ~[?:?]
	at org.openhab.binding.hue.internal.handler.Clip2ThingHandler.updateServiceContributors(Clip2ThingHandler.java:1121) ~[?:?]
	at org.openhab.binding.hue.internal.handler.Clip2ThingHandler.updateDependencies(Clip2ThingHandler.java:904) ~[?:?]
	at org.openhab.binding.hue.internal.handler.Clip2ThingHandler.lambda$3(Clip2ThingHandler.java:596) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
2023-07-27 12:18:01.514 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception: 
java.lang.NullPointerException: Cannot invoke "String.toUpperCase()" because "this.lastEvent" is null
	at org.openhab.binding.hue.internal.dto.clip2.Button.getLastEvent(Button.java:36) ~[?:?]
	at org.openhab.binding.hue.internal.dto.clip2.Resource.getButtonEventState(Resource.java:191) ~[?:?]
	at org.openhab.binding.hue.internal.handler.Clip2ThingHandler.updateChannels(Clip2ThingHandler.java:787) ~[?:?]
	at org.openhab.binding.hue.internal.handler.Clip2ThingHandler.onResource(Clip2ThingHandler.java:609) ~[?:?]
	at org.openhab.binding.hue.internal.handler.Clip2ThingHandler.lambda$26(Clip2ThingHandler.java:1055) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at org.openhab.binding.hue.internal.handler.Clip2ThingHandler.updateResource(Clip2ThingHandler.java:1055) ~[?:?]
	at org.openhab.binding.hue.internal.handler.Clip2ThingHandler.updateServiceContributors(Clip2ThingHandler.java:1121) ~[?:?]
	at org.openhab.binding.hue.internal.handler.Clip2ThingHandler.updateDependencies(Clip2ThingHandler.java:904) ~[?:?]
	at org.openhab.binding.hue.internal.handler.Clip2ThingHandler.lambda$3(Clip2ThingHandler.java:596) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

## Environment
* Version used: OpenHAB 4.0.0
* Operating System and version: Raspberry Pi OS - Bullseye

**Comment by jlaur** [comment]
@andrewfg - FYI.

**Comment by jlaur** [comment]
Will be fixed by #15169
