### ISSUE TITLE
[LCN] throws NoSuchMethodError exception

### ISSUE THREAD

**Issue by pene8** [openhab/openhab-addons#15312]
after upgrade to Openhab 4 my Log is filled with error messages like: 
`
2023-07-27 20:51:45.480 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception:
java.lang.NoSuchMethodError: 'void org.openhab.core.library.types.DecimalType.<init>(long)'
        at org.openhab.binding.lcn.internal.common.VariableValue.getState(VariableValue.java:93) ~[?:?]
        at org.openhab.binding.lcn.internal.subhandler.AbstractLcnModuleSubHandler.fireUpdateAndReset(AbstractLcnModuleSubHandler.java:173) ~[?:?]
        at org.openhab.binding.lcn.internal.subhandler.LcnModuleVariableSubHandler.handleStatusMessage(LcnModuleVariableSubHandler.java:84) ~[?:?]
        at org.openhab.binding.lcn.internal.subhandler.AbstractLcnModuleSubHandler.lambda$3(AbstractLcnModuleSubHandler.java:129) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
        at org.openhab.binding.lcn.internal.subhandler.AbstractLcnModuleSubHandler.tryParse(AbstractLcnModuleSubHandler.java:127) ~[?:?]
        at org.openhab.binding.lcn.internal.LcnModuleHandler.lambda$3(LcnModuleHandler.java:259) ~[?:?]
        at java.util.HashMap$Values.forEach(HashMap.java:1065) ~[?:?]
        at org.openhab.binding.lcn.internal.LcnModuleHandler.handleStatusMessage(LcnModuleHandler.java:259) ~[?:?]
        at org.openhab.binding.lcn.internal.PckGatewayHandler$1.lambda$4(PckGatewayHandler.java:105) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
        at java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
        at org.openhab.binding.lcn.internal.PckGatewayHandler$1.onPckMessageReceived(PckGatewayHandler.java:105) ~[?:?]
        at org.openhab.binding.lcn.internal.connection.Connection$1.lambda$0(Connection.java:189) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
`
I'm using a rule in Openhab to send the Values of Items to a script thats transmits the Values to FHEM. Wotked until today without a Problem. 
Now, after the Upgrade to OH4 all the Items that have units with it (e.g. 19C) trhow this exeption. Items that just send plain Number or plain Text work as expectet.

**Comment by fwolter** [comment]
Thanks for raising this. I'll have a look.

**Comment by fwolter** [comment]
It seems you are using a custom built JAR file in the `addons` folder, which was compiled for OH 3.x. In OH 4, there were some constructors for primitive types (`long` in this case) removed. These are now handled by autoboxing by the `DecimalType(Number)` constructor. The byte code of the OH 3.x JAR still tries to access the constructor for primitive type, which aren't present anymore. Try to remove the JAR from the `addons` folder and install the binding of the official distribution or compile the JAR for OH 4.

Reference: https://community.openhab.org/t/lcn-scripts-dont-work-after-upgrade-to-java-17-and-oh/148089
