### ISSUE TITLE
[digitalstrom] Startup error - Scheduled runnable ended with an exception

### ISSUE THREAD

**Issue by alexf2015** [openhab/openhab-addons#15318]
Since upgrade to openhab 4.0.0 there is an exception thrown during startup of binding. The bridge reaches state ONLINE (CONFIGURATION PENDING) and remains there as that expceptions stops the binding:

```
java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 64
        at java.lang.String.checkBoundsBeginEnd(String.java:4602) ~[?:?]
        at java.lang.String.substring(String.java:2705) ~[?:?]
        at org.openhab.binding.digitalstrom.internal.lib.serverconnection.impl.HttpTransportImpl.addSessionToken(HttpTransportImpl.java:352) ~[?:?]
        at org.openhab.binding.digitalstrom.internal.lib.serverconnection.impl.HttpTransportImpl.checkSessionToken(HttpTransportImpl.java:329) ~[?:?]
        at org.openhab.binding.digitalstrom.internal.lib.serverconnection.impl.HttpTransportImpl.execute(HttpTransportImpl.java:254) ~[?:?]
        at org.openhab.binding.digitalstrom.internal.lib.serverconnection.impl.HttpTransportImpl.execute(HttpTransportImpl.java:240) ~[?:?]
        at org.openhab.binding.digitalstrom.internal.lib.serverconnection.impl.DsAPIImpl.propertyTreeGetChildren(DsAPIImpl.java:1280) ~[?:?]
        at org.openhab.binding.digitalstrom.internal.lib.manager.impl.TemperatureControlManager.isHeatingControllerInstallated(TemperatureControlManager.java:190) ~[?:?]
        at org.openhab.binding.digitalstrom.internal.handler.BridgeHandler$Initializer.run(BridgeHandler.java:161) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

This can be reproduced with both UI and textual configuration. I tested with both token based and username/password authentication the result is always the same.

**Comment by alexf2015** [comment]
@lsiepel this is introduced by your code refactoring: https://github.com/openhab/openhab-addons/pull/14402

**Comment by lolodomo** [comment]
The PR was merged on February. Between February and the release date, there were 4 or 5 milestone versions and a release candidate version and no one complains.

**Comment by jlaur** [comment]
@lolodomo - unfortunately no one tested #14402 and probably that couldn't be expected without any agreements for that.

@alexf2015 - thanks for your report! I have provided a pull request for reverting the code to the last known working state. We aim to get this into a 4.0.1 hotfix.

Unfortunately that reintroduces the usage of `org.apache.commons.lang3.StringUtils`. If @lsiepel would refactor this again, would you be willing to test a JAR?

**Comment by alexf2015** [comment]
Problem here is that we have an edge case. `substringBefore` returns the full string if the search string(character is not found. lastIndexOf returns `-1` which causes the `substring`to fail. So result of `lastIndexOf` needs to be checked before passing it to `subString`

**Comment by jlaur** [comment]
@alexf2015 - can you test [org.openhab.binding.digitalstrom-4.1.0-SNAPSHOT.jar](https://drive.google.com/file/d/1b6XesBdzamwNkS0I7XFIlC9RAKEAHJNs/view?usp=sharing) just to be sure everything is working as expected?

**Comment by alexf2015** [comment]
the reverted code works and I also found a fix for the refactored code. There were 3 issues:

1. unchecked usage of `request.indexOf("?")` in `checkNeededSessionToken`
2. unchecked usage of `lastIndexOf("&") in `addSessionToken`
3.  usage of `lastIndexOf("&") instead of `indexOf("&")`in `addSessionToken`

This code looks a little bit ugly but at least it works. Binding is initialized and things are discovered. I could test it further in my production environment but first smoke test looks good.

```
    private boolean checkNeededSessionToken(String request) {
        String requestFirstPart = request;
        int indexOfSeparator = request.indexOf("?");
        if (indexOfSeparator >= 0) {
            requestFirstPart = request.substring(0, request.indexOf("?"));
        }
        String functionName = requestFirstPart.substring(requestFirstPart.lastIndexOf("/") + 1);
        return !DsAPIImpl.METHODS_MUST_NOT_BE_LOGGED_IN.contains(functionName);
    }

    private String addSessionToken(String request, String sessionToken) {
        String correctedRequest = request;
        if (!correctedRequest.contains(ParameterKeys.TOKEN)) {
            if (correctedRequest.contains("?")) {
                correctedRequest = correctedRequest + "&" + ParameterKeys.TOKEN + "=" + sessionToken;
            } else {
                correctedRequest = correctedRequest + "?" + ParameterKeys.TOKEN + "=" + sessionToken;
            }
        } else {
            String strippedRequest = correctedRequest
                    .substring(correctedRequest.indexOf(ParameterKeys.TOKEN + "=") + ParameterKeys.TOKEN.length() + 1);
            int indexOfSeparator = strippedRequest.indexOf("&");
            if (indexOfSeparator >= 0) {
                strippedRequest = strippedRequest.substring(0, indexOfSeparator);
            }
            correctedRequest = correctedRequest.replaceFirst(strippedRequest, sessionToken);
        }
        return correctedRequest;
    }
```

**Comment by jlaur** [comment]
@alexf2015 - would you like to prepare a pull request for getting rid of `org.apache.commons.lang3.StringUtils` again?

**Comment by alexf2015** [comment]
sure I will do this later
