### ISSUE TITLE
[gpstracker] Error when location report contains float altitude value

### ISSUE THREAD

**Issue by krocans** [openhab/openhab-addons#15327]
Openhab version 4.0.1

Looks like addon is expecting only integer altitude value  (#14396). Some trackers report float altitude value and that cause error.

```2023-07-29 15:36:04.664 [ERROR] [nal.provider.AbstractCallbackServlet] - Error processing location report:
com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: Expected an int but was 35.4 at line 1 column 56 path $.alt
        at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:243) ~[?:?]
        at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:233) ~[?:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:161) ~[?:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:266) ~[?:?]
        at com.google.gson.Gson.fromJson(Gson.java:1058) ~[?:?]
        at com.google.gson.Gson.fromJson(Gson.java:1016) ~[?:?]
        at com.google.gson.Gson.fromJson(Gson.java:959) ~[?:?]`
        ...
Caused by: java.lang.NumberFormatException: Expected an int but was 35.4 at line 1 column 56 path $.alt
        at com.google.gson.stream.JsonReader.nextInt(JsonReader.java:1214) ~[?:?]
        at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:241) ~[?:?]
        ... 50 more```

**Comment by lsiepel** [comment]
I’ll come up with a fix and a jar to rest.

**Comment by lsiepel** [comment]
Could you test: https://1drv.ms/u/s!AnMcxmvEeupwjq5cdMTEKdBph73qcQ?e=p5p6vO
4.1.0 jar file?

**Comment by traschke** [comment]
Had the same issue with OpenHAB 4.0.1 and PhoneTrack. The jar @lsiepel linked fixes the issue. Had to manually uninstall the original binding, then add the jar to the `addons` folder to get it to work.

**Comment by lsiepel** [comment]
> Had the same issue with OpenHAB 4.0.1 and PhoneTrack. The jar @lsiepel linked fixes the issue. Had to manually uninstall the original binding, then add the jar to the `addons` folder to get it to work.

Thanks for the feedback!
