### ISSUE TITLE
[easee] Binding stops working after date parsing error

### ISSUE THREAD

**Issue by alexf2015** [openhab/openhab-addons#15497]
```
2023-08-25 04:41:55.453 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception:
java.time.DateTimeException: Invalid value for EpochDay (valid values -365243219162 - 365241780471): -365243219528
        at java.time.temporal.ValueRange.checkValidValue(ValueRange.java:319) ~[?:?]
        at java.time.temporal.ChronoField.checkValidValue(ChronoField.java:718) ~[?:?]
        at java.time.LocalDate.ofEpochDay(LocalDate.java:343) ~[?:?]
        at java.time.LocalDateTime.ofEpochSecond(LocalDateTime.java:424) ~[?:?]
        at java.time.ZonedDateTime.create(ZonedDateTime.java:458) ~[?:?]
        at java.time.ZonedDateTime.ofInstant(ZonedDateTime.java:411) ~[?:?]
        at java.time.chrono.IsoChronology.zonedDateTime(IsoChronology.java:400) ~[?:?]
        at java.time.chrono.IsoChronology.zonedDateTime(IsoChronology.java:126) ~[?:?]
        at java.time.format.DateTimePrintContext.adjust(DateTimePrintContext.java:150) ~[?:?]
        at java.time.format.DateTimePrintContext.<init>(DateTimePrintContext.java:119) ~[?:?]
        at java.time.format.DateTimeFormatter.formatTo(DateTimeFormatter.java:1847) ~[?:?]
        at java.time.format.DateTimeFormatter.format(DateTimeFormatter.java:1823) ~[?:?]
        at org.openhab.binding.easee.internal.Utils.formatDate(Utils.java:79) ~[?:?]
        at org.openhab.binding.easee.internal.connector.WebInterface$WebRequestExecutor.refreshAccessToken(WebInterface.java:228) ~[?:?]
        at org.openhab.binding.easee.internal.connector.WebInterface$WebRequestExecutor.run(WebInterface.java:193) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

The binding should at least recover from such errors

**Comment by alexf2015** [comment]
This is weird. Given that simple date formatter function

```
    public static String formatDate(Instant date) {
        final DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")
                .withZone(ZoneId.systemDefault());
        return formatter.format(date);
    }
```

this simple test fails:

```
    @Test
    public void formatDateTest() {
        assertNotNull(Utils.formatDate(Instant.MIN));
    }
```

with exactly the same exception like above. I used `Instant.MIN` as invalid/initial dates and this was not changed. But this seems to cause problems in openhab 4.0. Most likely the new Java version has a different (faulty) behaviour.

**Comment by lsiepel** [comment]
Maybe something regarding the timezone or some inner precission? as it is only 366 outside the limits?

Workaround could be to add something like:
```
if (instant == Instant.MIN) {
      return "0001-01-01 00:00:00"; //  (double check if that is the right string) 
}
```

**Comment by jlaur** [comment]
Why try to format `Instant.MIN` at all? See https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/time/Instant.html#MIN

The year is -1000000000.

**Comment by alexf2015** [comment]
Well I used this date to set an "invalid" token expiry. To avoid similar issues with other dates coming from the API I fixed the helper function and also switched to `Instant.EPOCH` instead of `Instant.MIN`
