### ISSUE TITLE
[hue] Unhandled HTTP status code 207 (API v2)

### ISSUE THREAD

**Issue by jlaur** [openhab/openhab-addons#15511]
I noticed this during system startup:
```
2023-08-27 17:18:58.698 [WARN ] [e.internal.handler.Clip2ThingHandler] - Command 'OFF' for thing 'hue:device:home:traadfri_white_bulb2', channel 'hue:device:home:traadfri_white_bulb2:brightness' failed with error 'Unexpected HTTP status '207''.
2023-08-27 17:18:58.762 [WARN ] [e.internal.handler.Clip2ThingHandler] - Command 'OFF' for thing 'hue:device:home:traadfri_color_bulb2', channel 'hue:device:home:traadfri_color_bulb2:color' failed with error 'Unexpected HTTP status '207''.
2023-08-27 17:18:58.795 [WARN ] [e.internal.handler.Clip2ThingHandler] - Command 'OFF' for thing 'hue:device:home:traadfri_white_bulb1', channel 'hue:device:home:traadfri_white_bulb1:brightness' failed with error 'Unexpected HTTP status '207''.
2023-08-27 17:18:58.845 [WARN ] [e.internal.handler.Clip2ThingHandler] - Command 'OFF' for thing 'hue:device:home:traadfri_color_bulb1', channel 'hue:device:home:traadfri_color_bulb1:color' failed with error 'Unexpected HTTP status '207''.
```

This was exposed by #15477 because status code is now checked and logged when different than 200.

## Expected Behavior
207 Multi-Status should be handled.

## Current Behavior
207 Multi-Status is not supported.

## Possible Solution
Documented [here](https://developers.meethue.com/develop/hue-api-v2/api-reference/#resource_light__id__put):

HTTP status code [207](http://httpstatus.es/207)
Body
**Media type:** application/json

**Type:** object

**Properties**

- **errors:** _required(array of Error)_
**Items:** Error
<pre>
description: required(string)
a human-readable explanation specific to this occurrence of the problem.
</pre>

- **data:** _required(array of ResourceIdentifierPut)_
**Items:** ResourceIdentifierPut
<pre>
rid: (string – pattern: ^[0-9a-f]{8}-([0-9a-f]{4}-){3}[0-9a-f]{12}$)
The unique id of the referenced resource

rtype: (one of device, bridge_home, room, zone, light, button, relative_rotary, temperature, light_level, motion, entertainment, grouped_light, device_power, zigbee_bridge_connectivity, zigbee_connectivity, zgp_connectivity, bridge, zigbee_device_discovery, homekit, matter, matter_fabric, scene, entertainment_configuration, public_image, auth_v1, behavior_script, behavior_instance, geofence, geofence_client, geolocation, smart_scene)
The type of the referenced resource
</pre>

## Steps to Reproduce
So far I have been able to reproduce this shortly after restarts. With trace logging enabled the first occurrence looks like this:
```
2023-08-27 18:02:45.178 [DEBUG] [e.internal.handler.Clip2ThingHandler] - 00000000-0000-0000-0000-000000000000 -> handleCommand() put resource id:11111111-1111-1111-1111-111111111111, type:light
2023-08-27 18:02:45.180 [DEBUG] [.internal.handler.Clip2BridgeHandler] - putResource() id:11111111-1111-1111-1111-111111111111, type:light
2023-08-27 18:02:45.182 [TRACE] [.hue.internal.connection.Clip2Bridge] - PUT https://192.168.0.251/clip/v2/resource/light/11111111-1111-1111-1111-111111111111 HTTP/2 >> {"type":"light","id":"11111111-1111-1111-1111-111111111111","on":{"on":false}}
2023-08-27 18:02:45.216 [TRACE] [.hue.internal.connection.Clip2Bridge] - HTTP/2 207 (Content-Type: application/json) << {"data":[{"rid":"11111111-1111-1111-1111-111111111111","rtype":"light"}],"errors":[{"description":"device (light) has communication issues, command (.on.on) may not have effect"}]}
2023-08-27 18:02:45.218 [DEBUG] [e.internal.handler.Clip2ThingHandler] - 00000000-0000-0000-0000-000000000000 -> handleCommand() error Unexpected HTTP status '207'
org.openhab.binding.hue.internal.exceptions.ApiException: Unexpected HTTP status '207'
        at org.openhab.binding.hue.internal.connection.Clip2Bridge.putResource(Clip2Bridge.java:1110) ~[?:?]
        at org.openhab.binding.hue.internal.handler.Clip2BridgeHandler.putResource(Clip2BridgeHandler.java:565) ~[?:?]
        at org.openhab.binding.hue.internal.handler.Clip2ThingHandler.handleCommand(Clip2ThingHandler.java:513) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.openhab.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:147) ~[?:?]
        at org.openhab.core.internal.common.InvocationHandlerSync.invoke(InvocationHandlerSync.java:59) ~[?:?]
        at jdk.proxy1151.$Proxy1279.handleCommand(Unknown Source) ~[?:?]
        at org.openhab.core.thing.internal.profiles.ProfileCallbackImpl.handleCommand(ProfileCallbackImpl.java:85) ~[?:?]
        at org.openhab.core.thing.internal.profiles.SystemDefaultProfile.onCommandFromItem(SystemDefaultProfile.java:48) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.openhab.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:147) ~[?:?]
        at org.openhab.core.internal.common.Invocation.call(Invocation.java:52) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

Pretty-printed payload:
```json
{
	"data": [
		{
			"rid": "11111111-1111-1111-1111-111111111111",
			"rtype": "light"
		}
	],
	"errors": [
		{
			"description": "device (light) has communication issues, command (.on.on) may not have effect"
		}
	]
}
```

## Your Environment
* Version used: 4.0.2 with binding compiled after merging #15477

**Comment by jlaur** [comment]
@andrewfg - FYI, I randomly encountered this today.

**Comment by jlaur** [comment]
I will propose a fix.

**Comment by andrewfg** [comment]
@jlaur Haha. A classic example of your request to check HTTP codes having unintended consequences. The request, even though it returns 207 instead of 200, does actually carry a valid JSON response. The 207 message in this case means that you commanded a light which is not connected to power; so the Hue Bridge says it received a valid command, but the actual state will not have changed. Principally you can ignore it. I am on vacation for 2 weeks, so I can make another PR when I return. Or you can make a PR yourself to treat 207 as 200 (probably treat all 20x as "success" i.e. not throw an exception. The returned JSON contains an Errors field which is logged anyway..

**Comment by andrewfg** [comment]
Change `if (status != HttpStatus.OK_200) {`  => `if (status >= 300) {`
