### ISSUE TITLE
[amazonechocontrol] Fails getting smart home state from Ring Alarm system

### ISSUE THREAD

**Issue by ghost** [openhab/openhab-addons#15581]
## Expected Behavior
The binding fails to update the states with the following error

```
updateSmartHomeState started with deviceFilterId=null
2023-09-12 21:24:47.843 [DEBUG] [.amazonechocontrol.internal.handler.AccountHandler] - updateSmartHomeState started with deviceFilterId=null
2023-09-12 21:24:47.844 [DEBUG] [nhab.binding.amazonechocontrol.internal.Connection] - Make request to https://alexa.amazon.de/api/phoenix/state
2023-09-12 21:24:47.844 [DEBUG] [nhab.binding.amazonechocontrol.internal.Connection] - POST
2023-09-12 21:24:48.931 [DEBUG] [nhab.binding.amazonechocontrol.internal.Connection] - Call to https://alexa.amazon.de/api/phoenix/state succeeded
2023-09-12 21:24:48.932 [DEBUG] [nhab.binding.amazonechocontrol.internal.Connection] - Result of POST 
2023-09-12 21:24:48.949 [DEBUG] [chocontrol.internal.handler.SmartHomeDeviceHandler] - Updating states failed
java.lang.UnsupportedOperationException: JsonObject
	at com.google.gson.JsonElement.getAsString(JsonElement.java:179) ~[?:?]
	at org.openhab.binding.amazonechocontrol.internal.smarthome.HandlerSecurityPanelController.updateChannels(HandlerSecurityPanelController.java:133) ~[?:?]
	at org.openhab.binding.amazonechocontrol.internal.handler.SmartHomeDeviceHandler.updateChannelStates(SmartHomeDeviceHandler.java:233) ~[?:?]
	at org.openhab.binding.amazonechocontrol.internal.handler.AccountHandler.updateSmartHomeState(AccountHandler.java:920) ~[?:?]
	at org.openhab.binding.amazonechocontrol.internal.handler.AccountHandler.lambda$2(AccountHandler.java:167) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

The result received is

```
"capabilityStates": [
    "{\"namespace\":\"Alexa.SecurityPanelController.Alert\",\"name\":\"sirenState\",\"value\":{\"state\":\"OFF\"},\"timeOfSample\":\"2023-09-12T19:24:48Z\",\"uncertaintyInMilliseconds\":0,\"deepQuery\":true,\"timeOfStateChange\":\"\"}",
    "{\"namespace\":\"Alexa.SecurityPanelController.Alert\",\"name\":\"delayState\",\"value\":{\"state\":\"NONE\"},\"timeOfSample\":\"2023-09-12T19:24:48Z\",\"uncertaintyInMilliseconds\":0,\"deepQuery\":true,\"timeOfStateChange\":\"\"}",
    "{\"namespace\":\"Alexa.StatusCodeController\",\"name\":\"statusCodes\",\"value\":[],\"timeOfSample\":\"2023-09-12T19:24:48Z\",\"uncertaintyInMilliseconds\":0,\"deepQuery\":true,\"timeOfStateChange\":\"\"}",
    "{\"namespace\":\"Alexa.SecurityPanelController\",\"name\":\"armState\",\"value\":\"DISARMED\",\"timeOfSample\":\"2023-09-12T19:24:48Z\",\"uncertaintyInMilliseconds\":0,\"deepQuery\":true,\"timeOfStateChange\":\"\"}",
    "{\"namespace\":\"Alexa.SecurityPanelController\",\"name\":\"fireAlarm\",\"value\":{\"value\":\"OK\"},\"timeOfSample\":\"2023-09-12T19:24:48Z\",\"uncertaintyInMilliseconds\":0,\"deepQuery\":true,\"timeOfStateChange\":\"\"}",
    "{\"namespace\":\"Alexa.EndpointHealth\",\"name\":\"connectivity\",\"value\":{\"value\":\"OK\"},\"timeOfSample\":\"2023-09-12T19:24:48Z\",\"uncertaintyInMilliseconds\":0,\"deepQuery\":true,\"timeOfStateChange\":\"\"}",
    "{\"namespace\":\"Alexa.SecurityPanelController\",\"name\":\"burglaryAlarm\",\"value\":{\"value\":\"OK\"},\"timeOfSample\":\"2023-09-12T19:24:48Z\",\"uncertaintyInMilliseconds\":0,\"deepQuery\":true,\"timeOfStateChange\":\"\"}",
    "{\"namespace\":\"Alexa.SecurityPanelController\",\"name\":\"carbonMonoxideAlarm\",\"value\":{\"value\":\"OK\"},\"timeOfSample\":\"2023-09-12T19:24:48Z\",\"uncertaintyInMilliseconds\":0,\"deepQuery\":true,\"timeOfStateChange\":\"\"}"
]
```

The error then happens when the binding parses the fireAlarm state in [HandlerSecurityPanelController ](https://github.com/openhab/openhab-addons/blob/43ed48d34a4d9841712d67ebb3f3f1875fe4d9bf/bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/smarthome/HandlerSecurityPanelController.java#L133)line 133
```
} else if (FIRE_ALARM.propertyName.equals(state.get("name").getAsString())) {
    if (fireAlarmValue == null) {
        fireAlarmValue = "ALARM".equals(state.get("value").getAsString());
```

## Possible Solution
I think the reason for this is that the value is not a string it is an json object which again includes `{\"value\":\"OK\"}`
I do not know if this has changed in the protocoll or what the reason for this is. But if the value is like this getValueAsString needs to be changed to get the object and then the value.
In my opinion the same is true for connectivity, burglaryAlarm and carbonMonoxideAlarm

## Steps to Reproduce (for Bugs)
This happens with the Ring Alarm system connected to alexa

## Context
Want to show the state of my alarm system

## Your Environment
* openHAB 3.4.4 Release Build
* Using docker image 3.4.4 on my synology

**Comment by ThE-TiGeR** [comment]
I implemented a fix for this and testet it with my ring alarm system.
Changes can be found [here ](https://github.com/openhab/openhab-addons/compare/3.4.x...ThE-TiGeR:openhab-addons:3.4.x)

**Comment by ThE-TiGeR** [comment]
Is it possible to get this integrated as I always have to build the addon by my own

**Comment by lsiepel** [comment]
This was fixed. First in the smarthomej version (see above linked pullrequest) and as of 5.0.0 as a port of the smarthomej version into openHAB itself. openHAB 5.0.1 contains some important fixes. Similar for openHAB 4.3.7, but that would need a snapshot version of the binding as 4.3.8 is not yet released.  jar file: https://1drv.ms/u/c/70ea7ac46bc61c73/EbOmfyg9h9RCobVf9wIwQiUBRaV32b1sWMGoaHvW2ZvaeQ?e=zPdce2
