### ISSUE TITLE
[groheondus] Sense guard equipment failing to initialize

### ISSUE THREAD

**Issue by PottiMc** [openhab/openhab-addons#15584]
My Grohe Sense Guard is failiung to initialize. The failure always states "Could not load data from API.". Switching the valve is actually working sometimes. The account thing itself is online too.

Since another test environment of myself in NodeRed also is not able to request any data from Grohe I think they changed something in the API. The failure in NodeRed  is similar to the one in Openhab "getApplianceData failed: Not Found"

Can somebody with more knowledge have a look at this?

* Version used: OH 4.0.3

```
2023-09-13 06:55:42.123 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'groheondus:senseguard:XXX' changed from OFFLINE (COMMUNICATION_ERROR): Failed to find appliance data to OFFLINE (COMMUNICATION_ERROR): Could not load data from API.

	at org.openhab.binding.groheondus.internal.handler.GroheOndusSenseGuardHandler.getLastMeasurement(GroheOndusSenseGuardHandler.java:140) ~[?:?]

	at org.openhab.binding.groheondus.internal.handler.GroheOndusSenseGuardHandler.updateChannel(GroheOndusSenseGuardHandler.java:91) ~[?:?]

	at org.openhab.binding.groheondus.internal.handler.GroheOndusSenseGuardHandler.updateChannel(GroheOndusSenseGuardHandler.java:1) ~[?:?]

	at org.openhab.binding.groheondus.internal.handler.GroheOndusBaseHandler.lambda$1(GroheOndusBaseHandler.java:119) ~[?:?]

	at org.openhab.binding.groheondus.internal.handler.GroheOndusBaseHandler.updateChannels(GroheOndusBaseHandler.java:119) ~[?:?]
```

**Comment by PottiMc** [comment]
Hey @seime, there is an issue again with the Grohe Binding. Maybe can I get your help again? You were the best last time!

**Comment by CyberChris79** [comment]
Same error here :(

**Comment by seime** [comment]
I think the binding is due for a complete rewrite. Error messages from the cloud server is "hidden" from the binding by the jar SDK the author wrote, and are mostly replaced with a "null" value in the binding.  

There are also more features that should be supported:
- Store all historic data, not just the latest value when device connects to cloud server
- Cache data to avoid the current rate limiting (very agressive one)
- Support push messages in case water is detected - either by listening to cloud push messages or tapping into the 433Mhz data sent from the Sense to the Guard when water is detected

I'm short on available time, but I'd be supportive if someone wants to take on the above. I've massaged the existing binding enough times to conclude that a complete rewrite is a good thing.

**Comment by PottiMc** [comment]
I am new in programming but I understand the logics, etc. Just never used programming language before, more like Blocky, etc. Do you think it makes any sense to use this binding as a starting project? Or is it more complicated than it should be for a newbie?

**Comment by seime** [comment]
Take a look at https://www.openhab.org/docs/developer/bindings/ as well as the existing code.

**Comment by CyberChris79** [comment]
My Ondus Sense Guard Binding is connected again.
Maybe it was an problem with service.

**Comment by PottiMc** [comment]
Mine still has the same issue. What firmware and OH version are you on?

My Sense Guard firmware is 01.50.Z22.0400.0101
My OH version is 4.0.3

**Comment by CyberChris79** [comment]
Hello, @PottiMc 

My Sense Guard firmware is 01.44.Z22.0400.0101
My OH version is 4.0.3

**Comment by PottiMc** [comment]
Looks like the NodeRed Version fixed it somehow:
https://github.com/windkh/node-red-contrib-grohe-sense/issues/12

**Comment by CyberChris79** [comment]
Hi there,

same Error again

Status: Offline
COMMUNICATION_ERROR
Could not load data from API.

**Comment by PottiMc** [comment]
@CyberChris79 

FYI, I did install the NodeRed [https://github.com/windkh/node-red-contrib-grohe-sense](url) and send the values to my OpenHab via MQTT. Switching the valve is also possible via MQTT. The module is working fine and you can get daily and hourly values as you like. Probably it would also be possible to send the values directly to OpenHab via the OH-NodeRed Plugin, but i prefer MQTT.

**Comment by CyberChris79** [comment]
Hello @PottiMc ,
than you FYI.
Where did you install the https://github.com/windkh/node-red-contrib-grohe-sense ?

**Comment by PottiMc** [comment]
Hi @CyberChris79 ,
as I said, I installed it in NodeRed. Please check the documentation of NodeRed. Either you install it on the same system like your OpenHab instance (e.g. Raspberry Pi) or (like me) in a separate VM container on your server. Depends on your infrastructure.

**Comment by CyberChris79** [comment]
Hello @PottiMc 

ok, i already got this running on my NodeRed on ioBroker, but never used MQTT, although i have a MQTT Broker running on ioBroker.
Thanks

**Comment by heikowuest** [comment]
i'm also using the grohe ondus addon and got the above error. Seems like the API changed slightly a while ago.

Additional to the node red which allready included the changes i found somtheing else:

https://github.com/FlorianSW/grohe-ondus-api-java/commit/6ee8d1eaa8837baab710887ed202d6e3dc16e5b7

Is anybody looking at this? I can help debug/test but i have no java knowledge doing the changes by my own.

**Comment by CyberChris79** [comment]
Hello @heikowuest,

I installed the Grohe node red also a long time ago, but I always get „initialisation“ and that’s it. 
Does this works for you?

Cheers 
Cyberchris

**Comment by PottiMc** [comment]
Hi, since this is off-topic now for the openhab bindung, I apologize. But I wanna try to help you.
Looks like you did something wrong in your configuration. You really need to enter all location and name data like you have it in the Grohe app.

Looks like this for me:

**Comment by PottiMc** [comment]
> i'm also using the grohe ondus addon and got the above error. Seems like the API changed slightly a while ago.
> 
> Additional to the node red which allready included the changes i found somtheing else:
> 
> [FlorianSW/grohe-ondus-api-java@6ee8d1e](https://github.com/FlorianSW/grohe-ondus-api-java/commit/6ee8d1eaa8837baab710887ed202d6e3dc16e5b7)
> 
> Is anybody looking at this? I can help debug/test but i have no java knowledge doing the changes by my own.

I asked FlorianSW to update his binding and he did so, see the closed issued. It should work now. The update is on maven but I was not succesful in letting the openhab binding use the new version of the api. 
But I guess @seime is right, somebody really needs to rewrite this binding (not me actually, since I obviously can't even bring the binding to use the new Java API from FlorianSW). The NodeRed-node is working really well, I didn't have a single error in months. The openhab binding was failing constantly.

**Comment by heikowuest** [comment]
ok so it will go into one of the next Snapshots?

**Comment by CyberChris79** [comment]
Hallo @PottiMc ,

thank you very much.
After i set up my right locations, i could get it to work.
Could you send me your Node as a Json Export?

Thank you

**Comment by PottiMc** [comment]
@CyberChris79 
[flows.json](https://github.com/openhab/openhab-addons/files/13504454/flows.json)

There you go. The variables assigned will not match, but you can get an idea of what I am doing.

**Comment by CyberChris79** [comment]
> @CyberChris79 [flows.json](https://github.com/openhab/openhab-addons/files/13504454/flows.json)
> 
> There you go. The variables assigned will not match, but you can get an idea of what I am doing.

Hello @PottiMc ,

many thanks for your help.
I already imported it and wil check it at the weekend.
Have a nice day.

Cheers
CyberChris

**Comment by tnemrap** [comment]
Any updates on this?

**Comment by PottiMc** [comment]
Unfortunately not. The binding is still not working right and I am not capable of adjusting it (tried it anyway but had way more errors than before). I'm still fine using the NodeRed version. It didn't have even one issue in the meantime.

**Comment by pelerner** [comment]
Same error here ..... 

Sense - OK
Sense Guard - NOT OK

See binding debug logs ... maybe this helps ... to get a quick fix ...

```
2024-03-04 15:00:07.787 [DEBUG] [ternal.handler.GroheOndusBaseHandler] - Updating channels for appliance groheondus:senseguard:0be1209a-0eaa-493c-9a69-8d55195a6c2c
2024-03-04 15:00:07.979 [DEBUG] [.handler.GroheOndusSenseGuardHandler] - Fetching data for groheondus:senseguard:0be1209a-0eaa-493c-9a69-8d55195a6c2c from 2024-03-01T14:00:07.978774958Z to
2024-03-05T14:00:07.978778346Z
2024-03-04 15:00:08.014 [ERROR] [ore.common.registry.AbstractRegistry] - Cannot inform the listener "org.openhab.core.thing.internal.ChannelLinkNotifier@574fad15" about the "ADDED" event: C
annot invoke "java.util.List.isEmpty()" because "measurementList" is null
java.lang.NullPointerException: Cannot invoke "java.util.List.isEmpty()" because "measurementList" is null
        at org.openhab.binding.groheondus.internal.handler.GroheOndusSenseGuardHandler.getLastMeasurement(GroheOndusSenseGuardHandler.java:139) ~[?:?]
        at org.openhab.binding.groheondus.internal.handler.GroheOndusSenseGuardHandler.updateChannel(GroheOndusSenseGuardHandler.java:91) ~[?:?]
        at org.openhab.binding.groheondus.internal.handler.GroheOndusSenseGuardHandler.updateChannel(GroheOndusSenseGuardHandler.java:1) ~[?:?]
        at org.openhab.binding.groheondus.internal.handler.GroheOndusBaseHandler.lambda$1(GroheOndusBaseHandler.java:119) ~[?:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at org.openhab.binding.groheondus.internal.handler.GroheOndusBaseHandler.updateChannels(GroheOndusBaseHandler.java:119) ~[?:?]
        at org.openhab.binding.groheondus.internal.handler.GroheOndusSenseGuardHandler.handleCommand(GroheOndusSenseGuardHandler.java:238) ~[?:?]
        at org.openhab.core.thing.binding.BaseThingHandler.channelLinked(BaseThingHandler.java:182) ~[?:?]
        at org.openhab.core.thing.internal.ChannelLinkNotifier.lambda$3(ChannelLinkNotifier.java:72) ~[?:?]
        at org.openhab.core.thing.internal.ChannelLinkNotifier.call(ChannelLinkNotifier.java:96) ~[?:?]
        at org.openhab.core.thing.internal.ChannelLinkNotifier.added(ChannelLinkNotifier.java:72) ~[?:?]
        at org.openhab.core.thing.internal.ChannelLinkNotifier.added(ChannelLinkNotifier.java:1) ~[?:?]
        at org.openhab.core.common.registry.AbstractRegistry.notifyListeners(AbstractRegistry.java:375) ~[?:?]
        at org.openhab.core.common.registry.AbstractRegistry.notifyListenersAboutAddedElement(AbstractRegistry.java:408) ~[?:?]
        at org.openhab.core.thing.link.ItemChannelLinkRegistry.notifyListenersAboutAddedElement(ItemChannelLinkRegistry.java:181) ~[?:?]
        at org.openhab.core.thing.link.ItemChannelLinkRegistry.notifyListenersAboutAddedElement(ItemChannelLinkRegistry.java:1) ~[?:?]
        at org.openhab.core.common.registry.AbstractRegistry.added(AbstractRegistry.java:175) ~[?:?]
        at org.openhab.core.common.registry.AbstractRegistry.added(AbstractRegistry.java:1) ~[?:?]
        at org.openhab.core.common.registry.AbstractProvider.notifyListeners(AbstractProvider.java:60) ~[?:?]
        at org.openhab.core.common.registry.AbstractProvider.notifyListeners(AbstractProvider.java:79) ~[?:?]
        at org.openhab.core.common.registry.AbstractProvider.notifyListenersAboutAddedElement(AbstractProvider.java:83) ~[?:?]
        at org.openhab.core.model.thing.internal.GenericItemChannelLinkProvider.createItemChannelLink(GenericItemChannelLinkProvider.java:107) ~[?:?]
        at org.openhab.core.model.thing.internal.GenericItemChannelLinkProvider.processBindingConfiguration(GenericItemChannelLinkProvider.java:77) ~[?:?]
        at org.openhab.core.model.item.internal.GenericItemProvider.internalDispatchBindings(GenericItemProvider.java:371) ~[?:?]
        at org.openhab.core.model.item.internal.GenericItemProvider.internalDispatchBindings(GenericItemProvider.java:340) ~[?:?]
        at org.openhab.core.model.item.internal.GenericItemProvider.processBindingConfigsFromModel(GenericItemProvider.java:212) ~[?:?]
        at org.openhab.core.model.item.internal.GenericItemProvider.modelChanged(GenericItemProvider.java:406) ~[?:?]
        at org.openhab.core.model.core.internal.ModelRepositoryImpl.notifyListeners(ModelRepositoryImpl.java:299) ~[?:?]
        at org.openhab.core.model.core.internal.ModelRepositoryImpl.addOrRefreshModel(ModelRepositoryImpl.java:139) ~[?:?]
        at org.openhab.core.model.core.internal.folder.FolderObserver.checkPath(FolderObserver.java:255) ~[?:?]
        at org.openhab.core.model.core.internal.folder.FolderObserver.processWatchEvent(FolderObserver.java:314) ~[?:?]
        at org.openhab.core.internal.service.WatchServiceImpl$Listener.notify(WatchServiceImpl.java:293) ~[?:?]
        at org.openhab.core.internal.service.WatchServiceImpl.lambda$6(WatchServiceImpl.java:278) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
        at org.openhab.core.internal.service.WatchServiceImpl.doNotify(WatchServiceImpl.java:278) ~[?:?]
        at org.openhab.core.internal.service.WatchServiceImpl.notifyListeners(WatchServiceImpl.java:271) ~[?:?]
        at org.openhab.core.internal.service.WatchServiceImpl.lambda$4(WatchServiceImpl.java:232) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:840) [?:?]
2024-03-04 15:00:08.038 [DEBUG] [ternal.handler.GroheOndusBaseHandler] - Updating channels for appliance groheondus:senseguard:0be1209a-0eaa-493c-9a69-8d55195a6c2c
2024-03-04 15:00:08.231 [DEBUG] [.handler.GroheOndusSenseGuardHandler] - Fetching data for groheondus:senseguard:0be1209a-0eaa-493c-9a69-8d55195a6c2c from 2024-03-01T14:00:08.231078884Z to 2024-03-05T14:00:08.231082328Z
2024-03-04 15:00:08.264 [ERROR] [ore.common.registry.AbstractRegistry] - Cannot inform the listener "org.openhab.core.thing.internal.ChannelLinkNotifier@574fad15" about the "ADDED" event: Cannot invoke "java.util.List.isEmpty()" because "measurementList" is null
java.lang.NullPointerException: Cannot invoke "java.util.List.isEmpty()" because "measurementList" is null
        at org.openhab.binding.groheondus.internal.handler.GroheOndusSenseGuardHandler.getLastMeasurement(GroheOndusSenseGuardHandler.java:139) ~[?:?]
        at org.openhab.binding.groheondus.internal.handler.GroheOndusSenseGuardHandler.updateChannel(GroheOndusSenseGuardHandler.java:91) ~[?:?]
        at org.openhab.binding.groheondus.internal.handler.GroheOndusSenseGuardHandler.updateChannel(GroheOndusSenseGuardHandler.java:1) ~[?:?]
        at org.openhab.binding.groheondus.internal.handler.GroheOndusBaseHandler.lambda$1(GroheOndusBaseHandler.java:119) ~[?:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at org.openhab.binding.groheondus.internal.handler.GroheOndusBaseHandler.updateChannels(GroheOndusBaseHandler.java:119) ~[?:?]
        at org.openhab.binding.groheondus.internal.handler.GroheOndusSenseGuardHandler.handleCommand(GroheOndusSenseGuardHandler.java:238) ~[?:?]
        at org.openhab.core.thing.binding.BaseThingHandler.channelLinked(BaseThingHandler.java:182) ~[?:?]
        at org.openhab.core.thing.internal.ChannelLinkNotifier.lambda$3(ChannelLinkNotifier.java:72) ~[?:?]
        at org.openhab.core.thing.internal.ChannelLinkNotifier.call(ChannelLinkNotifier.java:96) ~[?:?]
        at org.openhab.core.thing.internal.ChannelLinkNotifier.added(ChannelLinkNotifier.java:72) ~[?:?]
        at org.openhab.core.thing.internal.ChannelLinkNotifier.added(ChannelLinkNotifier.java:1) ~[?:?]
        at org.openhab.core.common.registry.AbstractRegistry.notifyListeners(AbstractRegistry.java:375) ~[?:?]
        at org.openhab.core.common.registry.AbstractRegistry.notifyListenersAboutAddedElement(AbstractRegistry.java:408) ~[?:?]
        at org.openhab.core.thing.link.ItemChannelLinkRegistry.notifyListenersAboutAddedElement(ItemChannelLinkRegistry.java:181) ~[?:?]
        at org.openhab.core.thing.link.ItemChannelLinkRegistry.notifyListenersAboutAddedElement(ItemChannelLinkRegistry.java:1) ~[?:?]
        at org.openhab.core.common.registry.AbstractRegistry.added(AbstractRegistry.java:175) ~[?:?]
        at org.openhab.core.common.registry.AbstractRegistry.added(AbstractRegistry.java:1) ~[?:?]
        at org.openhab.core.common.registry.AbstractProvider.notifyListeners(AbstractProvider.java:60) ~[?:?]
        at org.openhab.core.common.registry.AbstractProvider.notifyListeners(AbstractProvider.java:79) ~[?:?]
        at org.openhab.core.common.registry.AbstractProvider.notifyListenersAboutAddedElement(AbstractProvider.java:83) ~[?:?]
        at org.openhab.core.model.thing.internal.GenericItemChannelLinkProvider.createItemChannelLink(GenericItemChannelLinkProvider.java:107) ~[?:?]
        at org.openhab.core.model.thing.internal.GenericItemChannelLinkProvider.processBindingConfiguration(GenericItemChannelLinkProvider.java:77) ~[?:?]
        at org.openhab.core.model.item.internal.GenericItemProvider.internalDispatchBindings(GenericItemProvider.java:371) ~[?:?]
        at org.openhab.core.model.item.internal.GenericItemProvider.internalDispatchBindings(GenericItemProvider.java:340) ~[?:?]
        at org.openhab.core.model.item.internal.GenericItemProvider.processBindingConfigsFromModel(GenericItemProvider.java:212) ~[?:?]
        at org.openhab.core.model.item.internal.GenericItemProvider.modelChanged(GenericItemProvider.java:406) ~[?:?]
        at org.openhab.core.model.core.internal.ModelRepositoryImpl.notifyListeners(ModelRepositoryImpl.java:299) ~[?:?]
        at org.openhab.core.model.core.internal.ModelRepositoryImpl.addOrRefreshModel(ModelRepositoryImpl.java:139) ~[?:?]
        at org.openhab.core.model.core.internal.folder.FolderObserver.checkPath(FolderObserver.java:255) ~[?:?]
        at org.openhab.core.model.core.internal.folder.FolderObserver.processWatchEvent(FolderObserver.java:314) ~[?:?]
        at org.openhab.core.internal.service.WatchServiceImpl$Listener.notify(WatchServiceImpl.java:293) ~[?:?]
        at org.openhab.core.internal.service.WatchServiceImpl.lambda$6(WatchServiceImpl.java:278) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
        at org.openhab.core.internal.service.WatchServiceImpl.doNotify(WatchServiceImpl.java:278) ~[?:?]
        at org.openhab.core.internal.service.WatchServiceImpl.notifyListeners(WatchServiceImpl.java:271) ~[?:?]
        at org.openhab.core.internal.service.WatchServiceImpl.lambda$4(WatchServiceImpl.java:232) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:840) [?:?]
```

Peter

**Comment by PottiMc** [comment]
Hi @pelerner,
I can only recommend the Node-Red connection again. It is working fully without any problems at all since months. Didn't have one disconnect. 

I spend so much time trying to debug the Openhab binding without success. I don't think the binding will be existing in the future without a full rewrite (which I can't do since I am not a developer).

**Comment by pelerner** [comment]
@PottiMC 
Maybe yyou're right. Will try to get it working soon ...
P

**Comment by Hammerball** [comment]
Same issue here (OH 4.1.2). Scan found Guard und three sensors. Guard says: Could not load data from API. The three sensors report the appliance name as well as the battery level but no humidity and no temperature.

Uli

**Comment by lsiepel** [comment]
I have created a PR that updated some dependency's that should fix (some) issues.  Would be aqppreciated if anyone can give it a spin:

1. make sure you have openHAB 5.0.0 
2. unintall the current binding (all things, channesl etc will not be lost)
3. download the jar: https://1drv.ms/u/c/70ea7ac46bc61c73/ER43ESyamQRBgdhwtEjyWfsBJ1R4KWCJaO8rWQLjY3XP4w?e=bvE7Rd
4. place the jar into the addon folder 
5. report your findings and we will see from there
