### ISSUE TITLE
[homematic] Cant' convert FLOAT value '' with PercentTypeConverter for '.....:3#LEVEL'

### ISSUE THREAD

**Issue by GiovanniBattista** [openhab/openhab-addons#15597]
## Expected Behavior
If the CCU returns an empty string for a percentage type (e.g. 3#LEVEL) no exception should occur.

## Current Behavior
I have a few HmIP-BROLL-2 actors connected to raspberrymatic, which work fine. 
Every night, all devices get shut down, e.g. router, switches, openHAB & raspberrymatic (personal decision).
Now, from time to time, raspberrymatic loses the state/datapoint (raspberrymatic shows '??' as value) of some BROLL actors, which results in an exception when openHAB tries to update the state of the connected thing/item:
```
2023-09-14 07:01:38.613 [ERROR] [ternal.handler.HomematicThingHandler] - Can't convert FLOAT value '' with PercentTypeConverter for '00369F2999F3C1:3#LEVEL'
org.openhab.binding.homematic.internal.converter.ConverterTypeException: Can't convert FLOAT value '' with PercentTypeConverter for '00369F2999F3C1:3#LEVEL'
        at org.openhab.binding.homematic.internal.converter.type.AbstractTypeConverter.convertFromBinding(AbstractTypeConverter.java:120) ~[?:?]
        at org.openhab.binding.homematic.internal.handler.HomematicThingHandler.updateChannelState(HomematicThingHandler.java:468) ~[?:?]
        at org.openhab.binding.homematic.internal.handler.HomematicThingHandler.updateDatapointState(HomematicThingHandler.java:411) ~[?:?]
        at org.openhab.binding.homematic.internal.handler.HomematicBridgeHandler.onStateUpdated(HomematicBridgeHandler.java:281) ~[?:?]
        at org.openhab.binding.homematic.internal.communicator.AbstractHomematicGateway.lambda$1(AbstractHomematicGateway.java:744) ~[?:?]
        at org.openhab.binding.homematic.internal.misc.DelayedExecuter.start(DelayedExecuter.java:65) ~[?:?]
        at org.openhab.binding.homematic.internal.communicator.AbstractHomematicGateway.eventReceived(AbstractHomematicGateway.java:741) ~[?:?]
        at org.openhab.binding.homematic.internal.communicator.server.RpcResponseHandler.handleEvent(RpcResponseHandler.java:98) ~[?:?]
        at org.openhab.binding.homematic.internal.communicator.server.RpcResponseHandler.handleMethodCall(RpcResponseHandler.java:51) ~[?:?]
        at org.openhab.binding.homematic.internal.communicator.server.RpcResponseHandler.handleMethodCall(RpcResponseHandler.java:68) ~[?:?]
        at org.openhab.binding.homematic.internal.communicator.server.XmlRpcServer$ResponseHandler.handle(XmlRpcServer.java:125) ~[?:?]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[?:?]
        at org.eclipse.jetty.server.Server.handle(Server.java:516) ~[?:?]
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487) ~[?:?]
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732) ~[?:?]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479) ~[?:?]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277) ~[?:?]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) ~[?:?]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) ~[?:?]
        at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) ~[?:?]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338) ~[bundleFile:9.4.50.v20221201]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315) ~[bundleFile:9.4.50.v20221201]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173) ~[bundleFile:9.4.50.v20221201]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131) ~[bundleFile:9.4.50.v20221201]
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409) ~[bundleFile:9.4.50.v20221201]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883) ~[bundleFile:9.4.50.v20221201]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034) ~[bundleFile:9.4.50.v20221201]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```
The openHAB log is flooded with these exception until the blinds are being opened/closed. Then, rasperrymatic knows the state again and sends a number back.

## Possible Solution
When the binding or especially the PercentTypeConverter encounters an empty string, it should either ignore it until the CCU provides a reasonable value, or at least log a warning (maybe even as debug message), but it should not throw an exception.
The other converters should also be minded.

## Your Environment
* Version used: openHAB 4.0.3 Release Build & Raspberrymatic 3.69.7.20230626
* Operating System and version: Raspberry Pi OS Lite - Debian Buster (I know I should update to the latest OS)

**Comment by EvilPingu** [comment]
Hi,
same problem here:

```
 09:36:00.728 [ERROR] [ternal.handler.HomematicThingHandler] - Can't convert FLOAT value '' with PercentTypeConverter for '000A18A9A63D13:1#LEVEL'                               
  org.openhab.binding.homematic.internal.converter.ConverterTypeException: Can't convert FLOAT value '' with PercentTypeConverter for '000A18A9A63D13:1#LEVEL'                    
      at org.openhab.binding.homematic.internal.converter.type.AbstractTypeConverter.convertFromBinding(AbstractTypeConverter.java:120) ~[?:?]                                    
      at org.openhab.binding.homematic.internal.handler.HomematicThingHandler.updateChannelState(HomematicThingHandler.java:469) ~[?:?]                                           
      at org.openhab.binding.homematic.internal.handler.HomematicThingHandler.updateDatapointState(HomematicThingHandler.java:412) ~[?:?]                                         
      at org.openhab.binding.homematic.internal.handler.HomematicBridgeHandler.onStateUpdated(HomematicBridgeHandler.java:281) ~[?:?]                                             
      at org.openhab.binding.homematic.internal.communicator.AbstractHomematicGateway.lambda$1(AbstractHomematicGateway.java:744) ~[?:?]                                          
      at org.openhab.binding.homematic.internal.misc.DelayedExecuter.start(DelayedExecuter.java:65) ~[?:?]                                                                        
      at org.openhab.binding.homematic.internal.communicator.AbstractHomematicGateway.eventReceived(AbstractHomematicGateway.java:741) ~[?:?]                                     
      at org.openhab.binding.homematic.internal.communicator.server.RpcResponseHandler.handleEvent(RpcResponseHandler.java:98) ~[?:?]                                             
      at org.openhab.binding.homematic.internal.communicator.server.RpcResponseHandler.handleMethodCall(RpcResponseHandler.java:51) ~[?:?]                                        
      at org.openhab.binding.homematic.internal.communicator.server.RpcResponseHandler.handleMethodCall(RpcResponseHandler.java:68) ~[?:?]                                        
      at org.openhab.binding.homematic.internal.communicator.server.XmlRpcServer$ResponseHandler.handle(XmlRpcServer.java:125) ~[?:?]                                             
      at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[bundleFile:9.4.52.v20230823]                                                           
      at org.eclipse.jetty.server.Server.handle(Server.java:516) ~[bundleFile:9.4.52.v20230823]                                                                                   
      at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487) ~[bundleFile:9.4.52.v20230823]                                                                
      at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732) [bundleFile:9.4.52.v20230823]                                                                        
      at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479) [bundleFile:9.4.52.v20230823]                                                                          
      at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277) [bundleFile:9.4.52.v20230823]                                                                
      at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) [bundleFile:9.4.52.v20230823]                                                
      at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) [bundleFile:9.4.52.v20230823]                                                                          
      at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) [bundleFile:9.4.52.v20230823]                                                                       
      at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338) [bundleFile:9.4.52.v20230823]                                                     
      at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315) [bundleFile:9.4.52.v20230823]                                                   
      at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173) [bundleFile:9.4.52.v20230823]                                                  
      at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131) [bundleFile:9.4.52.v20230823]                                                         
      at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409) [bundleFile:9.4.52.v20230823]                                   
      at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883) [bundleFile:9.4.52.v20230823]                                                           
      at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034) [bundleFile:9.4.52.v20230823]                                                      
      at java.lang.Thread.run(Thread.java:833) [?:?]
```
