### ISSUE TITLE
[vallox] Add Vallox Binding

### ISSUE THREAD

**Issue by SuperOok** [openhab/openhab-addons#1559]
New Binding for Vallox central venting units.
Use a RS485-to-Ethernet-Gateway to interface to the Vallox ECU.
http://www.vallox.com/en/products/vallox_ventilation_units.html

**Comment by SuperOok** [comment]
@kaikreuzer, how to proceed from here?

**Comment by kaikreuzer** [comment]
With a lot of patience, please!

**Comment by SuperOok** [comment]
but that was quick ;) thanks, I'm not in a hurry
think I forgot to sign-off my commits, sigh

**Comment by mstormi** [comment]
Hi,
any chance that you also support the current Vallox MV series ?
Those units provide control through a builtin webserver. Essentially it's sending out a compact, static piece of JavaScript to get executed in the browser.
That script ultimately encodes Modbus commands and sends them over websockets to the Vallox unit, just like you currently do over RS485/TCP, so you possibly just need to implement the websocket part.
I can provide you with access to a live unit for testing if needed, and eventually with a contact at Vallox.
regards
Markus

**Comment by majherek** [comment]
Hi, 
after moving vallox binding to openhab2-addons I can't use it.
I clone SuperOok openhab2-addons branch:

```
git clone -b#1559-vallox-binding https://github.com/SuperOok/openhab2-addons.git
cd openhab2-addons/addons/binding/org.openhab.binding.vallox/
majherek@atom:~/openhab2-addons/addons/binding/org.openhab.binding.vallox$ mvn package
[INFO] Scanning for projects...
Downloading: https://openhab.jfrog.io/openhab/libs-snapshot/org/openhab/pom-tycho/2.2.0-SNAPSHOT/maven-metadata.xml
Downloaded: https://openhab.jfrog.io/openhab/libs-snapshot/org/openhab/pom-tycho/2.2.0-SNAPSHOT/maven-metadata.xml (599 B at 0.5 KB/sec)
[WARNING] Could not transfer metadata org.openhab:pom-tycho:2.2.0-SNAPSHOT/maven-metadata.xml from/to p2-smarthome (https://openhab.jfrog.io/openhab/eclipse-smarthome-stable): Cannot access https://openhab.jfrog.io/openhab/eclipse-smarthome-stable with type p2 using the available connector factories: BasicRepositoryConnectorFactory
[WARNING] Could not transfer metadata org.openhab:pom-tycho:2.2.0-SNAPSHOT/maven-metadata.xml from/to p2-openhab-deps-repo (https://dl.bintray.com/openhab/p2/openhab-deps-repo/${ohdr.version}): Cannot access https://dl.bintray.com/openhab/p2/openhab-deps-repo/${ohdr.version} with type p2 using the available connector factories: BasicRepositoryConnectorFactory
Downloading: https://openhab.jfrog.io/openhab/libs-snapshot/org/openhab/pom/2.2.0-SNAPSHOT/maven-metadata.xml
Downloaded: https://openhab.jfrog.io/openhab/libs-snapshot/org/openhab/pom/2.2.0-SNAPSHOT/maven-metadata.xml (593 B at 2.1 KB/sec)
[WARNING] Could not transfer metadata org.openhab:pom:2.2.0-SNAPSHOT/maven-metadata.xml from/to p2-smarthome (https://openhab.jfrog.io/openhab/eclipse-smarthome-stable): Cannot access https://openhab.jfrog.io/openhab/eclipse-smarthome-stable with type p2 using the available connector factories: BasicRepositoryConnectorFactory
[WARNING] Could not transfer metadata org.openhab:pom:2.2.0-SNAPSHOT/maven-metadata.xml from/to p2-openhab-deps-repo (https://dl.bintray.com/openhab/p2/openhab-deps-repo/${ohdr.version}): Cannot access https://dl.bintray.com/openhab/p2/openhab-deps-repo/${ohdr.version} with type p2 using the available connector factories: BasicRepositoryConnectorFactory
[INFO] Computing target platform for MavenProject: org.openhab.binding:org.openhab.binding.vallox:2.2.0-SNAPSHOT @ /home/majherek/openhab2-addons/addons/binding/org.openhab.binding.vallox/pom.xml
[INFO] Fetching p2.index from https://openhab.jfrog.io/openhab/eclipse-smarthome-stable/ (172B)
[INFO] Adding repository https://openhab.jfrog.io/openhab/eclipse-smarthome-stable
[INFO] Fetching p2.index from https://dl.bintray.com/openhab/p2/openhab-deps-repo/1.0.19/ (172B)
[INFO] Adding repository https://dl.bintray.com/openhab/p2/openhab-deps-repo/1.0.19
[INFO] Resolving dependencies of MavenProject: org.openhab.binding:org.openhab.binding.vallox:2.2.0-SNAPSHOT @ /home/majherek/openhab2-addons/addons/binding/org.openhab.binding.vallox/pom.xml
[INFO] Resolving class path of MavenProject: org.openhab.binding:org.openhab.binding.vallox:2.2.0-SNAPSHOT @ /home/majherek/openhab2-addons/addons/binding/org.openhab.binding.vallox/pom.xml
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Vallox Binding 2.2.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- tycho-packaging-plugin:1.0.0:build-qualifier (default-build-qualifier) @ org.openhab.binding.vallox ---
[INFO] The project's OSGi version is 2.2.0.201711302158
[INFO]
[INFO] --- tycho-packaging-plugin:1.0.0:validate-id (default-validate-id) @ org.openhab.binding.vallox ---
[INFO]
[INFO] --- tycho-packaging-plugin:1.0.0:validate-version (default-validate-version) @ org.openhab.binding.vallox ---
[INFO]
[INFO] --- maven-resources-plugin:2.4.3:resources (default-resources) @ org.openhab.binding.vallox ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/majherek/openhab2-addons/addons/binding/org.openhab.binding.vallox/src/main/resources
[INFO]
[INFO] --- tycho-compiler-plugin:1.0.0:compile (default-compile) @ org.openhab.binding.vallox ---
[WARNING] Parameter 'useProjectSettings' is set to true, but preferences file '/home/majherek/openhab2-addons/addons/binding/org.openhab.binding.vallox/.settings/org.eclipse.jdt.core.prefs' could not be found!
[INFO] Compiling 14 source files to /home/majherek/openhab2-addons/addons/binding/org.openhab.binding.vallox/target/classes
[WARNING] /home/majherek/openhab2-addons/addons/binding/org.openhab.binding.vallox/src/main/java/org/openhab/binding/vallox/handler/ValloxSerialHandler.java:[393]
        this.updateState(channel, state);
                                  ^^^^^
Null type mismatch: required '@NonNull State' but the provided value is inferred as @Nullable
[WARNING] /home/majherek/openhab2-addons/addons/binding/org.openhab.binding.vallox/src/main/java/org/openhab/binding/vallox/handler/ValloxSerialHandler.java:[401]
        updateStatus(status);
                     ^^^^^^
Null type safety (type annotations): The expression of type 'ThingStatus' needs unchecked conversion to conform to '@NonNull ThingStatus'
[WARNING] /home/majherek/openhab2-addons/addons/binding/org.openhab.binding.vallox/src/main/java/org/openhab/binding/vallox/handler/ValloxSerialHandler.java:[403]
        updateStatus(status, detail);
                     ^^^^^^
Null type safety (type annotations): The expression of type 'ThingStatus' needs unchecked conversion to conform to '@NonNull ThingStatus'
[WARNING] /home/majherek/openhab2-addons/addons/binding/org.openhab.binding.vallox/src/main/java/org/openhab/binding/vallox/handler/ValloxSerialHandler.java:[403]
        updateStatus(status, detail);
                             ^^^^^^
Null type safety (type annotations): The expression of type 'ThingStatusDetail' needs unchecked conversion to conform to '@NonNull ThingStatusDetail'
[WARNING] /home/majherek/openhab2-addons/addons/binding/org.openhab.binding.vallox/src/main/java/org/openhab/binding/vallox/handler/ValloxSerialHandler.java:[406]
        updateStatus(status, detail, message);
                     ^^^^^^
Null type safety (type annotations): The expression of type 'ThingStatus' needs unchecked conversion to conform to '@NonNull ThingStatus'
[WARNING] /home/majherek/openhab2-addons/addons/binding/org.openhab.binding.vallox/src/main/java/org/openhab/binding/vallox/handler/ValloxSerialHandler.java:[406]
        updateStatus(status, detail, message);
                             ^^^^^^
Null type safety (type annotations): The expression of type 'ThingStatusDetail' needs unchecked conversion to conform to '@NonNull ThingStatusDetail'
[WARNING] /home/majherek/openhab2-addons/addons/binding/org.openhab.binding.vallox/src/main/java/org/openhab/binding/vallox/ValloxBindingConstants.java:[22]
        public static final ThingTypeUID THING_TYPE_VALLOX_SERIAL = new ThingTypeUID(BINDING_ID, "kwl90se");
                                                                                     ^^^^^^^^^^
Null type safety (type annotations): The expression of type 'String' needs unchecked conversion to conform to '@NonNull String'
7 problems (7 warnings)
[INFO]
[INFO] --- maven-compiler-plugin:3.6.1:compile (default) @ org.openhab.binding.vallox ---
[INFO] Changes detected - recompiling the module!
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-scr-plugin:1.24.0:scr (generate-scr-scrdescriptor) @ org.openhab.binding.vallox ---[INFO]
[INFO] --- maven-resources-plugin:2.4.3:testResources (default-testResources) @ org.openhab.binding.vallox ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/majherek/openhab2-addons/addons/binding/org.openhab.binding.vallox/src/test/resources
[INFO]
[INFO] --- target-platform-configuration:1.0.0:target-platform (default-target-platform) @ org.openhab.binding.vallox ---
[INFO]
[INFO] --- tycho-packaging-plugin:1.0.0:package-plugin (default-package-plugin) @ org.openhab.binding.vallox ---
[INFO] Building jar: /home/majherek/openhab2-addons/addons/binding/org.openhab.binding.vallox/target/org.openhab.binding.vallox-2.2.0-SNAPSHOT.jar
[INFO]
[INFO] --- tycho-p2-plugin:1.0.0:p2-metadata-default (default-p2-metadata-default) @ org.openhab.binding.vallox ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9.592 s
[INFO] Finished at: 2017-11-30T22:58:25+01:00
[INFO] Final Memory: 30M/367M
[INFO] ------------------------------------------------------------------------
```

After adding things:
```
Thing vallox:kwl90se:vallox "Vallox 096 SE" @ "Rekuperacja" [ host="127.0.0.1", port=1026 ]
```
I get errors:

```
2017-11-30 22:35:37.766 [INFO ] [el.core.internal.ModelRepositoryImpl] - Loading model 'vallox.things'
2017-11-30 22:35:37.806 [INFO ] [el.core.internal.ModelRepositoryImpl] - Refreshing model 'vallox.things'
2017-11-30 22:35:38.002 [ERROR] [ome.core.thing.internal.ThingManager] - Exception occurred while calling thing updated at ThingHandler 'org.openhab.binding.vallox.handler.ValloxSerialHandler@40b83c87': java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@2db427a4 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@70e89f02[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 63]
java.util.concurrent.ExecutionException: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPo
olExecutor$ScheduledFutureTask@2db427a4 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@70e89f02[Terminated, pool size
 = 0, active threads = 0, queued tasks = 0, completed tasks = 63]
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)[:1.8.0_151]
        at java.util.concurrent.FutureTask.get(FutureTask.java:206)[:1.8.0_151]
        at org.eclipse.smarthome.core.common.SafeMethodCaller.callAsynchronous(SafeMethodCaller.java:194)
        at org.eclipse.smarthome.core.common.SafeMethodCaller.call(SafeMethodCaller.java:83)
        at org.eclipse.smarthome.core.common.SafeMethodCaller.call(SafeMethodCaller.java:67)
        at org.eclipse.smarthome.core.thing.internal.ThingManager.thingUpdated(ThingManager.java:524)
        at org.eclipse.smarthome.core.thing.internal.ThingRegistryImpl.notifyTrackers(ThingRegistryImpl.java:221)
        at org.eclipse.smarthome.core.thing.internal.ThingRegistryImpl.notifyListenersAboutUpdatedElement(ThingRegistryImpl.java:144)
        at org.eclipse.smarthome.core.thing.internal.ThingRegistryImpl.notifyListenersAboutUpdatedElement(ThingRegistryImpl.java:1)
        at org.eclipse.smarthome.core.common.registry.AbstractRegistry.updated(AbstractRegistry.java:177)[98:org.eclipse.smarthome.co
re:0.9.0.b5]
        at org.eclipse.smarthome.core.common.registry.AbstractProvider.notifyListeners(AbstractProvider.java:57)[98:org.eclipse.smart
home.core:0.9.0.b5]
        at org.eclipse.smarthome.model.thing.internal.GenericThingProvider.lambda$18(GenericThingProvider.java:978)[133:org.eclipse.s
marthome.model.thing:0.9.0.b5]
        at java.util.ArrayList.forEach(ArrayList.java:1255)[:1.8.0_151]
        at org.eclipse.smarthome.model.thing.internal.GenericThingProvider.createThingsFromModelForThingHandlerFactory(GenericThingPr
ovider.java:987)[133:org.eclipse.smarthome.model.thing:0.9.0.b5]
        at org.eclipse.smarthome.model.thing.internal.GenericThingProvider.access$1(GenericThingProvider.java:950)[133:org.eclipse.sm
arthome.model.thing:0.9.0.b5]
        at org.eclipse.smarthome.model.thing.internal.GenericThingProvider$1.lambda$0(GenericThingProvider.java:234)[133:org.eclipse.
smarthome.model.thing:0.9.0.b5]
        at java.util.concurrent.ConcurrentHashMap$KeySetView.forEach(ConcurrentHashMap.java:4649)[:1.8.0_151]
        at org.eclipse.smarthome.model.thing.internal.GenericThingProvider$1.apply(GenericThingProvider.java:236)[133:org.eclipse.sma
rthome.model.thing:0.9.0.b5]
        at org.eclipse.smarthome.model.thing.internal.GenericThingProvider$1.apply(GenericThingProvider.java:1)[133:org.eclipse.smart
home.model.thing:0.9.0.b5]
        at org.eclipse.smarthome.config.core.BundleProcessorVetoManager.applyActionFor(BundleProcessorVetoManager.java:124)
        at org.eclipse.smarthome.model.thing.internal.GenericThingProvider.lambda$3(GenericThingProvider.java:304)[133:org.eclipse.sm
arthome.model.thing:0.9.0.b5]
        at java.lang.Iterable.forEach(Iterable.java:75)[:1.8.0_151]
        at org.eclipse.smarthome.model.thing.internal.GenericThingProvider.createThingsFromModel(GenericThingProvider.java:306)[133:o
rg.eclipse.smarthome.model.thing:0.9.0.b5]
        at org.eclipse.smarthome.model.thing.internal.GenericThingProvider.modelChanged(GenericThingProvider.java:847)[133:org.eclips
e.smarthome.model.thing:0.9.0.b5]
        at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.notifyListeners(ModelRepositoryImpl.java:286)[122:org.eclips
e.smarthome.model.core:0.9.0.b5]
        at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.addOrRefreshModel(ModelRepositoryImpl.java:136)[122:org.ecli
pse.smarthome.model.core:0.9.0.b5]
        at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.checkFile(FolderObserver.java:234)[122:org.eclipse.smartho
me.model.core:0.9.0.b5]
        at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.processWatchEvent(FolderObserver.java:297)[122:org.eclipse
.smarthome.model.core:0.9.0.b5]
        at org.eclipse.smarthome.core.service.WatchQueueReader.run(WatchQueueReader.java:206)[98:org.eclipse.smarthome.core:0.9.0.b5]        at java.lang.Thread.run(Thread.java:748)[:1.8.0_151]
Caused by: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask
@2db427a4 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@70e89f02[Terminated, pool size = 0, active threads = 0, queu
ed tasks = 0, completed tasks = 63]
        at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)[:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)[:1.8.0_151]
        at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326)[:1.8.0_151]
        at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533)[:1.8.0_151]
        at java.util.concurrent.ScheduledThreadPoolExecutor.submit(ScheduledThreadPoolExecutor.java:632)[:1.8.0_151]
        at org.openhab.binding.vallox.internal.serial.ValloxSerialInterface.startListening(ValloxSerialInterface.java:330)[218:org.op
enhab.binding.vallox:2.2.0.201711292235]
        at org.openhab.binding.vallox.handler.ValloxSerialHandler.initialize(ValloxSerialHandler.java:94)[218:org.openhab.binding.val
lox:2.2.0.201711292235]
        at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.thingUpdated(BaseThingHandler.java:192)[105:org.eclipse.smarthom
e.core.thing:0.9.0.b5]
        at org.eclipse.smarthome.core.thing.internal.ThingManager$7.call(ThingManager.java:528)[105:org.eclipse.smarthome.core.thing:
0.9.0.b5]
        at org.eclipse.smarthome.core.thing.internal.ThingManager$7.call(ThingManager.java:1)[105:org.eclipse.smarthome.core.thing:0.
9.0.b5]
        at org.eclipse.smarthome.core.common.SafeMethodCaller$CallableWrapper.call(SafeMethodCaller.java:181)[98:org.eclipse.smarthom
e.core:0.9.0.b5]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)[:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)[:1.8.0_151]
        ... 1 more
```

Is there any posobility to do something with it? 

I have old compiled jar and it is working. 
```
219 | Active   |  80 | 2.0.0.201612122051     | Vallox
org.eclipse.smarthome.binding.vallox-2.0.0-SNAPSHOT.jar
```

**Comment by hmerk** [comment]
closed due to inactivity
