### ISSUE TITLE
[Shelly] java.lang.IllegalArgumentException: Last segment must not be blank

### ISSUE THREAD

**Issue by pkarrer** [openhab/openhab-addons#15650]
## Expected Behavior

unexpected error message

## Current Behavior

```
   3301 2023-09-25 16:00:00.081 [WARN ] [ab.core.internal.events.EventHandler] - Dispatching/filtering event for subscriber 'org.openhab.core.events.EventSubscriber' failed: Last segment must not be blank: [shelly, shellyplugs, ]
   3302 java.lang.IllegalArgumentException: Last segment must not be blank: [shelly, shellyplugs, ]
   3303         at org.openhab.core.common.AbstractUID.<init>(AbstractUID.java:79) ~[?:?]
   3304         at org.openhab.core.common.AbstractUID.<init>(AbstractUID.java:59) ~[?:?]
   3305         at org.openhab.core.thing.UID.<init>(UID.java:57) ~[?:?]
   3306         at org.openhab.core.thing.ThingUID.<init>(ThingUID.java:139) ~[?:?]
   3307         at org.openhab.core.thing.ChannelUID.getThingUID(ChannelUID.java:150) ~[?:?]
   3308         at org.openhab.core.thing.internal.AutoUpdateManager.shouldAutoUpdate(AutoUpdateManager.java:205) ~[?:?]
   3309         at org.openhab.core.thing.internal.AutoUpdateManager.receiveCommand(AutoUpdateManager.java:145) ~[?:?]
   3310         at org.openhab.core.thing.internal.CommunicationManager.receiveCommand(CommunicationManager.java:335) ~[?:?]
   3311         at org.openhab.core.thing.internal.CommunicationManager.receive(CommunicationManager.java:190) ~[?:?]
   3312         at org.openhab.core.internal.events.EventHandler.lambda$2(EventHandler.java:168) ~[?:?]
   3313         at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
   3314         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
   3315         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
   3316         at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

## Possible Solution

no glue

## Steps to Reproduce (for Bugs)

1. install Shelly Binding on OH 4.0.3
2. Discover devices
3. Create items

## Your Environment

* Version used: OH 4.0.3
* Linux raspberrypi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux

**Comment by pkarrer** [comment]
Hi, this error is gone. It was a wrong configuration line in the .items file nested in the channel={} statement. This also killed the semantic scheme. 

Sorry forgot to update

Paul

**Comment by markus7017** [comment]
perfect
