### ISSUE TITLE
[surepetcare] Support Felaqua

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-addons#15654]
Sure Petcare sells a water bowl that can be connected to the (already supported) hub. It's would be great if Felaqua will be supported as well.

If you need any dumps of http traffic, just poke me :)

**Comment by mueller-ma** [comment]
If anyone else is interested in this, poke me, so I can reopen this issue. I don't own this device anymore.

**Comment by HerzScheisse** [comment]
Hi @mueller-ma 

Just want to let you know that I'm currently working on implementing this device as I've been owning this for quite some years now, but didnt have had time to work on this...

I also want to add some other things to the binding...

**Comment by HerzScheisse** [comment]
thanks...
sure... will add a 4.3.x version jar here... please test... make sure you make a backup of your data first... I've changed some of the old items and added UoM (Units) to some...

Please let me know if something is not working...

A updated Readme with new Items to make use of the semanctic classes have been added too... take a look in my [forked repo](https://github.com/HerzScheisse/openhab-addons/tree/surepet_water/bundles/org.openhab.binding.surepetcare#readme)...

[org.openhab.binding.surepetcare-4.3.3-SNAPSHOT.zip](https://github.com/user-attachments/files/18444919/org.openhab.binding.surepetcare-4.3.3-SNAPSHOT.zip)

P.S.: If you reopen this Issue i can later mention it in the PR...

**Comment by mueller-ma** [comment]
Is it compiled from #18114?

**Comment by HerzScheisse** [comment]
yes I've created this on my PC with `mvn clean install -pl :org.openhab.binding.surepetcare` based on these last changes

**Comment by mueller-ma** [comment]
Ok, then I won't need to try it as it only contains the support for Felauqa (correct?) and I don't own one anymore.

**Comment by HerzScheisse** [comment]
yeah right now these are the only changes...  I'm working on some other things too... but cant tell any releasetime yet...

**Comment by PatMan6889** [comment]
> yeah right now these are the only changes... I'm working on some other things too... but cant tell any releasetime yet...

Getting this error log because I do not get any data for the hubrssi from the API:

```
2025-08-03 11:25:00.917 [ERROR] [nal.common.AbstractInvocationHandler] - An error occurred while calling method 'ThingHandler.handleCommand()' on 'org.openhab.binding.surepetcare.internal.handler.SurePetcareBridgeHandler@4dec59d5': Cannot invoke "java.lang.Float.floatValue()" because "device.status.signal.hubRssi" is null

java.lang.NullPointerException: Cannot invoke "java.lang.Float.floatValue()" because "device.status.signal.hubRssi" is null

	at org.openhab.binding.surepetcare.internal.handler.SurePetcareDeviceHandler.updateThing(SurePetcareDeviceHandler.java:145) ~[?:?]

	at org.openhab.binding.surepetcare.internal.handler.SurePetcareBridgeHandler.updateThings(SurePetcareBridgeHandler.java:189) ~[?:?]

	at org.openhab.binding.surepetcare.internal.handler.SurePetcareBridgeHandler.handleCommand(SurePetcareBridgeHandler.java:144) ~[?:?]

	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?]

	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]

	at org.openhab.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:149) ~[?:?]

	at org.openhab.core.internal.common.InvocationHandlerSync.invoke(InvocationHandlerSync.java:59) ~[?:?]

	at jdk.proxy6406.$Proxy6576.handleCommand(Unknown Source) ~[?:?]

	at org.openhab.core.thing.internal.profiles.ProfileCallbackImpl.handleCommand(ProfileCallbackImpl.java:95) ~[?:?]

	at org.openhab.core.thing.internal.profiles.SystemDefaultProfile.onCommandFromItem(SystemDefaultProfile.java:49) ~[?:?]

	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?]

	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]

	at org.openhab.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:149) ~[?:?]

	at org.openhab.core.internal.common.Invocation.call(Invocation.java:52) ~[?:?]

	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]

	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]

	at java.lang.Thread.run(Unknown Source) [?:?]
```

Seems like hubrssi is used even though it is null in SurePetcareDeviceHandler.java:

```
updateState(DEVICE_CHANNEL_HUB_RSSI,
                        new QuantityType<>(device.status.signal.hubRssi, Units.DECIBEL_MILLIWATTS));
```
Maybe it could be changed to something like that?

```
Float rssi = device.status.signal.hubRssi;
if (rssi != null) {
    updateState(DEVICE_CHANNEL_HUB_RSSI, new QuantityType<>(rssi, Units.DECIBEL_MILLIWATTS));
} else {
    updateState(DEVICE_CHANNEL_HUB_RSSI, UnDefType.UNDEF);
}
```

Any chance to fix it?

**Comment by jlaur** [comment]
> Maybe it could be changed to something like that?
> 
> ```
> Float rssi = device.status.signal.hubRssi;
> if (rssi != null) {
>     updateState(DEVICE_CHANNEL_HUB_RSSI, new QuantityType<>(rssi, Units.DECIBEL_MILLIWATTS));
> } else {
>     updateState(DEVICE_CHANNEL_HUB_RSSI, UnDefType.UNDEF);
> }
> ```
> 
> Any chance to fix it?

That seems about right to me, can you create a PR with that fix?

**Comment by PatMan6889** [comment]
> That seems about right to me, can you create a PR with that fix?

I tried but I have trouble with the PR. Its my first time doing it.
I have the PR in my fork but I cannot see it on the main repository
https://github.com/PatMan6889/openhab-addons/pull/1

**Comment by jlaur** [comment]
> I tried but I have trouble with the PR. Its my first time doing it.

You need to create the PR in the addons repository rather than in your own fork - using the branch in your fork:
https://github.com/openhab/openhab-addons/pulls

When you create it, if your branch is not automatically suggested, you can select your fork and branch to the right here:

<img width="1241" height="200" alt="Image" src="https://github.com/user-attachments/assets/84a536cf-da3f-49cb-a2ba-81aba75578d9" />

Please also make sure to sign your commit: https://www.openhab.org/docs/developer/contributing.html#sign-your-work

I can see that your current commit is not signed. You can configure Git to do this automatically when using the `--signoff` argument when committing, or you can add the sign-off manually with `-m  "Signed-off-by: Full name <e-mail address>"`. To sign off your already pushed commit, you can amend it (for last commit only), e.g.:
- `git commit --amend -m "your commit message" --signoff`
- `git push --force-with-lease origin`

**Comment by jlaur** [comment]
Oh, I see now that you already created the PR in the correct repository. 👍

**Comment by PatMan6889** [comment]
> Oh, I see now that you already created the PR in the correct repository. 👍

It seems that I have some formatting errors but I can not run mvn spotless:apply.
Never used java before. I edited the code in VS Code. Tried to install JAVA JDK, change environment variables for Java Home, tried .\mvnw.cmd spotless:apply.
No sucess though...

**Comment by lsiepel** [comment]
@PatMan6889 would you be available to test the linked PR for the added support of the Felaqua ? I can provide a jar, would be appreciated.

**Comment by PatMan6889** [comment]
> [@PatMan6889](https://github.com/PatMan6889) would you be available to test the linked PR for the added support of the Felaqua ? I can provide a jar, would be appreciated.

@lsiepel yes I would like to test it. I don't know how to create the jar so it would be nice if you can provide it.

**Comment by lsiepel** [comment]
Nice.

1. make sure you habe openHAB 5.0 installed
2. uninstall the current surepetcare binding (all links things etc will remain there)
3. download an updated jar here: https://1drv.ms/u/c/70ea7ac46bc61c73/EVTW1s_eJxZPvGIwPiX9lu0BAaKC4urO5sp2p2e0mszoDw?e=dj09jO
4. drop the jar in your addon folder
5. all should work as expected, please report your feedback here.

**Comment by PatMan6889** [comment]
> Nice.
> 
>     1. make sure you habe openHAB 5.0 installed
> 
>     2. uninstall the current surepetcare binding (all links things etc will remain there)
> 
>     3. download an updated jar here: https://1drv.ms/u/c/70ea7ac46bc61c73/EVTW1s_eJxZPvGIwPiX9lu0BAaKC4urO5sp2p2e0mszoDw?e=dj09jO
> 
>     4. drop the jar in your addon folder
> 
>     5. all should work as expected, please report your feedback here.

I tested it. I own all surepet devices and they all work except hubrssi, but this was fixed here #19106 .
The error message for hubrssi is gone.
There were some data points that were showing UNDEF but they all present data now.
Thanks a lot!
Maybe there is more data on the api? Unfortunately I don't know how to find out more.
Best regards

**Comment by lsiepel** [comment]
Thanks @PatMan6889 for testing, really appreciated.
