### ISSUE TITLE
[modbus] ModbusDataHandlerTest unstable

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-addons#15683]
This test failed in: https://github.com/openhab/openhab-addons/actions/runs/6377170852/job/17305335904

```
TEST org.openhab.binding.modbus.tests.ModbusDataHandlerTest#testReadValueTypeIllegal() <<< ERROR: 
Expected: is not null
     but: was null
java.lang.AssertionError: 
Expected: is not null
     but: was null
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
	at org.openhab.binding.modbus.tests.AbstractModbusOSGiTest.lambda$1(AbstractModbusOSGiTest.java:223)
	at org.openhab.core.test.java.JavaTest.waitForAssert(JavaTest.java:245)
	at org.openhab.core.test.java.JavaTest.waitForAssert(JavaTest.java:213)
	at org.openhab.core.test.java.JavaTest.waitForAssert(JavaTest.java:166)
	at org.openhab.binding.modbus.tests.AbstractModbusOSGiTest.linkItem(AbstractModbusOSGiTest.java:223)
	at org.openhab.binding.modbus.tests.ModbusDataHandlerTest.createDataHandler(ModbusDataHandlerTest.java:268)
	at org.openhab.binding.modbus.tests.ModbusDataHandlerTest.createDataHandler(ModbusDataHandlerTest.java:230)
	at org.openhab.binding.modbus.tests.ModbusDataHandlerTest.testInitGeneric(ModbusDataHandlerTest.java:1036)
	at org.openhab.binding.modbus.tests.ModbusDataHandlerTest.testInitGeneric(ModbusDataHandlerTest.java:999)
	at org.openhab.binding.modbus.tests.ModbusDataHandlerTest.testReadValueTypeIllegal(ModbusDataHandlerTest.java:1335)
```

Maybe you can look into it @ssalonen?

**Comment by ssalonen** [comment]
Thanks for the ping

The code fails when asserting that link that was just added, is actually available from ItemChannelLinkProvider. See below

This would imply that default timeout of 10s is not enough.

Should I simply increase the timeout? Then again, the pattern here is very typical I would assume. Has there been some other regression or change that simply surfaces here?

```java
ItemChannelLink link = new ItemChannelLink(itemName, channelUID);
        assertThat(addedLinks.contains(link), not(equalTo(true)));
        itemChannelLinkProvider.add(link);
        waitForAssert(() -> assertThat(itemChannelLinkRegistry.get(AbstractLink.getIDFor(itemName, channelUID)),
                is(notNullValue())));
```

**Comment by wborn** [comment]
I haven't studied this particular code so I do not know if increasing the timeout will help. Sometimes I also run into tests failing because some service asynchronously subscribes itself as listener to some kind of event. In that case you want to make sure the service is subscribed to the events before executing the code that sends the event.

**Comment by ssalonen** [comment]
The implementation seems to be very straightforward in the test, I am having hard time finding the root cause.

`ManagedItemChannelLinkProvider itemChannelLinkProvider` is called first with `.add()` and then we check the link exists with `.get()`. 

`ManagedItemChannelLinkProvider::add` is actually implemented in `AbstractManagedProvider::add` which is basically shallow wrapper to `put` to underlying `Storage`. Similarly with `get`

The behaviour does not even seem to care whether item exists.

---

Only thing I can think of is some sort of race condition if the previous test's `@AfterEach AbstractModbusOSGiTest.tearDownAbstractModbusOSGiTest` is run when the next test is already executing. I presume the channel links are tied into one global instance `ManagedItemChannelLinkProvider`... if the tearDown is in the process of clearing links we could expect this kind of failure.

Do you know @wborn if this is how the tests are run in CI?

**Comment by ssalonen** [comment]
Quick seach is showing that actually no other `itest` is tearing down the created links... supporting the speculation above 

Quick comparison to `ntp.tests` yielded more defensive approach with links (pay note of the comment):

```
 itemRegistry.add(testItem);

        // Wait for the item , linked to the NTP thing to be added to the
        // ManagedThingProvider.
        final ManagedItemChannelLinkProvider itemChannelLinkProvider = waitForAssert(() -> {
            final ManagedItemChannelLinkProvider tmp = getService(ManagedItemChannelLinkProvider.class);
            assertNotNull(tmp);
            return tmp;
        });
        itemChannelLinkProvider.add(new ItemChannelLink(TEST_ITEM_NAME, channelUID));
```

Based on comment, maybe we should be waiting for item to be added stil?

**Comment by ssalonen** [comment]
Answering myself, tests are run in parallel in github actions: https://github.com/openhab/openhab-addons/blob/729a19a8da9c6100a7caa8a8670a989b0d2fa04c/.github/scripts/maven-build#L5C1-L5C1

As commented above, tear down after the test is inherently non-thread safe, and should be fixed.

Will publish a fix

**Comment by ssalonen** [comment]
Hmm @wborn  I think I might have misread the CI build script, it was calling mvn with `-T` parameter but that does not tell anything but JUnit test execution.

I [did not find](https://github.com/search?q=org%3Aopenhab+junit.jupiter.execution&type=code) anything on [commanding JUnit to execute parallel](https://junit.org/junit5/docs/5.3.0-M1/user-guide/index.html#writing-tests-parallel-execution). Default would be single thread non-parallel and non-concurrent.

So there goes my fix-theory...

**Comment by lsiepel** [comment]
We have not seen this test failure for a very long time. i would suggest we close this, @wborn wdyt?

**Comment by wborn** [comment]
The failure might be caused by a race in `openhab-core`'s `AbstractRegistry` startup.

Provider tracking is initialized asynchronously, and there is a small window where an element can be added to a provider before the registry has fully registered that provider/listener. In that case the element is stored by the provider, but the registry may never see it. This matches the observed failure where `ManagedItemChannelLinkProvider.add()` succeeds but `ItemChannelLinkRegistry` still returns `null`.

This is not proven to be the root cause of this particular historical failure, but it is a plausible explanation and the relevant race still appears to exist in `openhab-core`.

As a workaround, the Modbus test can wait for the registry's asynchronous activation to finish during setup:

```java
itemChannelLinkRegistry.waitForCompletedAsyncActivationTasks();
```

This should ensure provider tracking is fully initialized before the test starts adding links. The underlying `AbstractRegistry` race could be investigated separately in `openhab-core`.

**Comment by wborn** [comment]
There are three other `openhab-addons` integration test suites that definitely use the same item-channel linking pattern without waiting for `ItemChannelLinkRegistry` asynchronous activation to complete:

- **NTP** — #9720
- **SystemInfo** — #13524
- **Miele Cloud** — #13938

All three also have reported unstable tests where expected channel state updates sometimes do not reach the item and it remains `NULL`.

This does not prove that the registry startup race caused every reported failure, but these tests are definitely exposed to the same race and would benefit from the same synchronization.
