### ISSUE TITLE
[JDBC] MySQL OH DateTime items sets DB value field to TimeStamp instead of DateTime

### ISSUE THREAD

**Issue by marioschouten** [openhab/openhab-addons#15697]
## Expected Behaviour
When a DateTime item is persisted, it should persist :-)

## Current Behaviour
The reason I run into this issue is when I tried to persist a DateTime item and the value cannot be saved if the time is smaller than the time zone, in addition on a restart none of the persisted values are not restored. 

## Possible Solution
When creating a new DateTime persisted item set the value field to DateTime instead of TimeStamp. I've manually changed my database table fields and the system works as expected.
![image](https://github.com/openhab/openhab-addons/assets/49558628/6e18558f-9a68-4847-8702-2fc365d7bbae)

## Steps to Reproduce (for Bugs)
Create a DateTime items and set a time smaller than the Time Zone. In my case I'm +7 so 00:00 to 07:00 results in the following error:

```
2023-10-04 18:30:30.323 [DEBUG] [persistence.jdbc.internal.JdbcMapper] - JDBC::storeItemValue: item=ROBSched1StartTim (Type=DateTimeItem, State=1970-01-01T03:00:00.000+0700, Label=Start time, Category=time, Tags=[Measurement, Duration], Groups=[gRobotLIV, gVacumeRU, PersistY]) state=1970-01-01T03:00:00.000+0700 date=null
2023-10-04 18:30:30.323 [DEBUG] [persistence.jdbc.internal.dto.ItemVO] - JDBC:ItemVO tableName=robsched1starttim_3757; newTableName=null; 
2023-10-04 18:30:30.323 [DEBUG] [istence.jdbc.internal.db.JdbcBaseDAO] - JDBC::storeItemValueProvider: item 'ROBSched1StartTim' as Type 'DATETIMEITEM' in 'robsched1starttim_3757' with state '1970-01-01T03:00:00.000+0700'
2023-10-04 18:30:30.324 [DEBUG] [istence.jdbc.internal.db.JdbcBaseDAO] - JDBC::storeItemValueProvider: itemState: '1970-01-01T03:00:00.000+0700'
2023-10-04 18:30:30.324 [DEBUG] [persistence.jdbc.internal.dto.ItemVO] - JDBC:ItemVO setValueTypes dbType=TIMESTAMP(3); javaType=class java.sql.Timestamp;
2023-10-04 18:30:30.324 [DEBUG] [istence.jdbc.internal.db.JdbcBaseDAO] - JDBC::storeItemValueProvider: DateTimeItem: '1970-01-01 03:00:00.0'
2023-10-04 18:30:30.324 [DEBUG] [istence.jdbc.internal.db.JdbcBaseDAO] - JDBC::doStoreItemValue sql=INSERT INTO robsched1starttim_3757 (time, value) VALUES( NOW(3), ? ) ON DUPLICATE KEY UPDATE VALUE= ? value='1970-01-01 03:00:00.0'
2023-10-04 18:30:30.334 [WARN ] [jdbc.internal.JdbcPersistenceService] - JDBC::store: Unable to store item
org.openhab.persistence.jdbc.internal.exceptions.JdbcSQLException: Error in SQL query!!!; Data truncation: Incorrect datetime value: '1970-01-01 03:00:00' for column 'value' at row 1 Query: INSERT INTO robsched1starttim_3757 (time, value) VALUES( NOW(3), ? ) ON DUPLICATE KEY UPDATE VALUE= ? Parameters: [1970-01-01 03:00:00.0, 1970-01-01 03:00:00.0]; Pool Name= yank-default; SQL= INSERT INTO robsched1starttim_3757 (time, value) VALUES( NOW(3), ? ) ON DUPLICATE KEY UPDATE VALUE= ?
	at org.openhab.persistence.jdbc.internal.db.JdbcBaseDAO.doStoreItemValue(JdbcBaseDAO.java:443) ~[?:?]
	at org.openhab.persistence.jdbc.internal.JdbcMapper.storeItemValue(JdbcMapper.java:220) ~[?:?]
	at org.openhab.persistence.jdbc.internal.JdbcPersistenceService.internalStore(JdbcPersistenceService.java:162) ~[?:?]
	at org.openhab.persistence.jdbc.internal.JdbcPersistenceService.store(JdbcPersistenceService.java:140) ~[?:?]
	at org.openhab.core.persistence.internal.PersistenceManager.lambda$7(PersistenceManager.java:170) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at org.openhab.core.persistence.internal.PersistenceManager.lambda$3(PersistenceManager.java:168) ~[?:?]
	at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4780) ~[?:?]
	at org.openhab.core.persistence.internal.PersistenceManager.handleStateEvent(PersistenceManager.java:165) ~[?:?]
	at org.openhab.core.persistence.internal.PersistenceManager.stateChanged(PersistenceManager.java:329) ~[?:?]
	at org.openhab.core.items.GenericItem.lambda$1(GenericItem.java:260) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

When changing the value field to DateTime the Debug log shows:

```
2023-10-04 18:49:00.175 [DEBUG] [persistence.jdbc.internal.JdbcMapper] - JDBC::storeItemValue: item=ROBSched1StartTim (Type=DateTimeItem, State=1970-01-01T03:00:00.000+0700, Label=Start time, Category=time, Tags=[Measurement, Duration], Groups=[gRobotLIV, gVacumeRU, PersistY]) state=1970-01-01T03:00:00.000+0700 date=null
2023-10-04 18:49:00.175 [DEBUG] [persistence.jdbc.internal.dto.ItemVO] - JDBC:ItemVO tableName=robsched1starttim_3757; newTableName=null; 
2023-10-04 18:49:00.176 [DEBUG] [istence.jdbc.internal.db.JdbcBaseDAO] - JDBC::storeItemValueProvider: item 'ROBSched1StartTim' as Type 'DATETIMEITEM' in 'robsched1starttim_3757' with state '1970-01-01T03:00:00.000+0700'
2023-10-04 18:49:00.176 [DEBUG] [istence.jdbc.internal.db.JdbcBaseDAO] - JDBC::storeItemValueProvider: itemState: '1970-01-01T03:00:00.000+0700'
2023-10-04 18:49:00.176 [DEBUG] [persistence.jdbc.internal.dto.ItemVO] - JDBC:ItemVO setValueTypes dbType=TIMESTAMP(3); javaType=class java.sql.Timestamp;
2023-10-04 18:49:00.176 [DEBUG] [istence.jdbc.internal.db.JdbcBaseDAO] - JDBC::storeItemValueProvider: DateTimeItem: '1970-01-01 03:00:00.0'
2023-10-04 18:49:00.176 [DEBUG] [istence.jdbc.internal.db.JdbcBaseDAO] - JDBC::doStoreItemValue sql=INSERT INTO robsched1starttim_3757 (time, value) VALUES( NOW(3), ? ) ON DUPLICATE KEY UPDATE VALUE= ? value='1970-01-01 03:00:00.0'
```

## Context
Using the DateTime item to set the time for a vacuum scheduler, as the schedule is mostly just after midnight I run into this issue.

## Your Environment
OH 4.0.3 running on a Proxmox VM with Debian 11
MySQL running on a Proxmox VM with Debian 11 and MySQL version 8.0.34 (MySQL Community Server - GPL)
JDBC version 4.0.3 with mysql-connector-j-8.0.33.jar

**Comment by jlaur** [comment]
See also #13775.

**Comment by marioschouten** [comment]
Hi, Thanks, had a look a the issue you mention. Correct me if I'm wrong but is that not about the`time` field timestamp(3) of the record? That in my case is fine, my issue is with the type of the `value` field witch is created as timestamp but in my case works only when changed to datetime. The time is selected here with the sitemap Element Type 'Input' using the time parameter.
![image](https://github.com/openhab/openhab-addons/assets/49558628/2509c0d1-7ba1-4994-a0a5-2e1ef064541d)

**Comment by miloit** [comment]
@marioschouten hello now it's about the value column..... By default it is set to timestamp but it must be Datetime I am running currently in the same issue....changed the column value data type to DateTime all is good

**Comment by jlaur** [comment]
After changing type to `DATETIME`:
```shell
openhab> jdbc schema check
Table                                       Item                                        Issue
------------------------------------------  ------------------------------------------  ----------------------------------------------------------------
TestDateTime                                TestDateTime                                Column type 'DATETIME' expected, but is 'TIMESTAMP(3)'
openhab> jdbc schema fix
Fixed table 'TestDateTime' for item 'TestDateTime'
openhab> openhab:update TestDateTime 0
Update has been sent successfully.
openhab> openhab:update TestDateTime "1900-01-01T00:00Z"
Update has been sent successfully.
openhab> openhab:update TestDateTime "1899-01-01T00:00Z"
Update has been sent successfully.
openhab> openhab:update TestDateTime "0001-01-01T00:00Z"
Update has been sent successfully.
openhab> openhab:update TestDateTime "0001-01-03T00:00Z"
Update has been sent successfully.
openhab> openhab:update TestDateTime "2100-01-01T00:00Z"
Update has been sent successfully.
```

Persisted values:
- 1900-01-01 01:00:00
- 1899-01-01 01:00:00
- 0001-01-03 01:00:00
- 0001-01-05 01:00:00
- 2100-01-01 01:00:00

There is probably a reason for the discrepancy between 0001-01-01T00:00Z and 0001-01-03 01:00:00, but overall it looks good enough, and it also looks like `java.sql.Timestamp` can handle it.

**Comment by marioschouten** [comment]
Thanks for all your help and efforts 👍

**Comment by jlaur** [comment]
> Thanks for all your help and efforts 👍

You're welcome. 🙂 Out of curiosity, what is your use-case for persisting a DateTime item?

**Comment by marioschouten** [comment]
Hi, thanks for asking. I persist a user selected time for various equipment like fountains, irrigation, and pool filter pump in one of my systems. Made this so my wife can update to her liking (And I know when changes were made). Need to persist to restore during restarts of OpenHAB. 

Only issue with it now (I did not report as not sure it's an OpenHAB issue) is that you need to select a different date every time you update the time otherwise it will not persist and throw a duplicate error using the same date. Guess it's intended behavior so you must update the sitemap input item with date/time, only time will not work.


![image](https://github.com/openhab/openhab-addons/assets/49558628/4f6b8bdb-0a6d-45bd-8a35-2cdd684a7321)

**Comment by jlaur** [comment]
> Hi, thanks for asking. I persist a user selected time for various equipment like fountains, irrigation, and pool filter pump in one of my systems. Made this so my wife can update to her liking (And I know when changes were made). Need to persist to restore during restarts of OpenHAB.

I see. So if you need the history of changes to this "configuration value", it makes sense. Otherwise [MapDB](https://www.openhab.org/addons/persistence/mapdb/) might have been a better fit for the use-case.

**Comment by marioschouten** [comment]
Thanks, never looked at MapDB and didn't know it. Currently use JDBC (MariaDB) as I also persist flowrate, power meters, temperature sensor and some other stuff.  Google just thought me I can use multiple DB for persistence simultaneously, something to look at for a next project. Thanks @jlaur

**Comment by jlaur** [comment]
> Currently use JDBC (MariaDB)

Just to be sure, this issue was created for MySQL:
> MySQL running on a Proxmox VM with Debian 11 and MySQL version 8.0.34 (MySQL Community Server - GPL)
> JDBC version 4.0.3 with mysql-connector-j-8.0.33.jar

Did you switch to MariaDB in the meantime? The fix I have provided is explicitly for MySQL. If you are using JDBC MariaDB, I would need to fix that too. Unfortunately I cannot test this myself, so in this case, would you be able to?

**Comment by marioschouten** [comment]
Sorry, my mistake. Have 3 systems running and working on a MariaDB at the moment. The error was however for the MySQL version as I reported.
