### ISSUE TITLE
[roku] Handler warning when TV crashes

### ISSUE THREAD

**Issue by morph166955** [openhab/openhab-addons#15797]
I'm not sure if this is fixable, noticed it last night.  From time to time my Roku TVs (TCLs if that matters) will crash.  I believe they get into a bad state, usually because I'm using my Nvidia Shield and it tries to push Atmos through the TV to the eARC sound bar, and then they just reboot when they can't resolve their issue.  It happened last night and I found these logs this morning.  I believe this could have been happening in the time imminently before the TV actually rebooted since it looks like I was still trying to hit buttons.  I don't have any more granular logs than this, and it's not something I can reproduce on demand, it just happens.

```
2023-10-21 19:26:07.888 [WARN ] [.core.thing.binding.BaseThingHandler] - Handler RokuHandler of thing roku:roku_tv:ROKUS05FY11FLEVS tried updating channel activeApp although the handler was already disposed.
2023-10-21 19:26:07.888 [WARN ] [.core.thing.binding.BaseThingHandler] - Handler RokuHandler of thing roku:roku_tv:ROKUS05FY11FLEVS tried updating channel activeAppName although the handler was already disposed
.
2023-10-21 19:26:07.888 [WARN ] [.core.thing.binding.BaseThingHandler] - Handler RokuHandler tried updating the thing status although the handler was already disposed.
2023-10-21 19:26:07.888 [WARN ] [.core.thing.binding.BaseThingHandler] - Handler RokuHandler of thing roku:roku_tv:ROKUS05FY11FLEVS tried updating channel playMode although the handler was already disposed.
2023-10-21 19:26:07.888 [WARN ] [.core.thing.binding.BaseThingHandler] - Handler RokuHandler of thing roku:roku_tv:ROKUS05FY11FLEVS tried updating channel timeElapsed although the handler was already disposed.
2023-10-21 19:26:07.888 [WARN ] [.core.thing.binding.BaseThingHandler] - Handler RokuHandler of thing roku:roku_tv:ROKUS05FY11FLEVS tried updating channel timeTotal although the handler was already disposed.
2023-10-21 19:26:07.919 [WARN ] [nternal.profiles.ProfileCallbackImpl] - Cannot delegate command 'HOME' for item 'ROKUS05FY11FLEVS_Button' to handler for channel 'roku:roku_tv:ROKUS05FY11FLEVS:button', because
no handler is assigned. Maybe the binding is not installed or not propertly initialized.
2023-10-21 19:26:07.919 [WARN ] [nternal.profiles.ProfileCallbackImpl] - Cannot delegate command 'BACK' for item 'ROKUS05FY11FLEVS_Button' to handler for channel 'roku:roku_tv:ROKUS05FY11FLEVS:button', because
no handler is assigned. Maybe the binding is not installed or not propertly initialized.
2023-10-21 19:26:07.920 [WARN ] [nternal.profiles.ProfileCallbackImpl] - Cannot delegate command 'BACK' for item 'ROKUS05FY11FLEVS_Button' to handler for channel 'roku:roku_tv:ROKUS05FY11FLEVS:button', because
no handler is assigned. Maybe the binding is not installed or not propertly initialized.
2023-10-21 19:26:07.920 [WARN ] [nternal.profiles.ProfileCallbackImpl] - Cannot delegate command 'BACK' for item 'ROKUS05FY11FLEVS_Button' to handler for channel 'roku:roku_tv:ROKUS05FY11FLEVS:button', because
no handler is assigned. Maybe the binding is not installed or not propertly initialized.
2023-10-21 19:26:07.920 [WARN ] [nternal.profiles.ProfileCallbackImpl] - Cannot delegate command 'BACK' for item 'ROKUS05FY11FLEVS_Button' to handler for channel 'roku:roku_tv:ROKUS05FY11FLEVS:button', because
no handler is assigned. Maybe the binding is not installed or not propertly initialized.
```

**Comment by mlobstein** [comment]
I think you will need to turn on debug and catch the error that causes the handler to crash. I am not sure why the TV rebooting would cause this. Maybe it responds with some invalid XML that the parser can't handle?

**Comment by morph166955** [comment]
I'll throw the binding into debug and have it peel off to a new log file. This could be a good month or two until it happens again.  The TV just goes down hill fast and hard crashes. I'll let ya know!

**Comment by morph166955** [comment]
I had a device crash, not sure if this is causing it but this exception is being thrown (and a ton of them are throwing):

```
2023-11-14 20:51:01.406 [DEBUG] [ernal.communication.RokuCommunicator] - Error executing player GET command, URL: http://10.255.0.11:8060/query/device-info, java.net.ConnectException: Connection refused
2023-11-14 20:51:01.406 [DEBUG] [ng.roku.internal.handler.RokuHandler] - Unable to retrieve Roku device-info.
org.openhab.binding.roku.internal.RokuHttpException: Exception creating DeviceInfo Unmarshaller: null
        at org.openhab.binding.roku.internal.communication.RokuCommunicator.getDeviceInfo(RokuCommunicator.java:128) ~[?:?]
        at org.openhab.binding.roku.internal.handler.RokuHandler.refreshPlayerState(RokuHandler.java:146) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:840) [?:?]

```

**Comment by mlobstein** [comment]
> I had a device crash, not sure if this is causing it but this exception is being thrown (and a ton of them are throwing). To note, the handler warning didn't throw at all this time so this may just be an errant exception hidden in the debugs.
> 
Did this leave the binding in a hung state? I think the exception handling of RokuCommunicator could be improved a little bit. Instead of swallowing the http exception and returning empty string, it could throw a RokuHttpException instead and therefore prevent the xml parsing from being done on an empty string:

```
private String getCommand(String url) throws RokuHttpException {
        try {
            return httpClient.GET(url).getContentAsString();
        } catch (InterruptedException | TimeoutException | ExecutionException e) {
            logger.debug("Error executing player GET command, URL: {}, {} ", url, e.getMessage());
            throw new RokuHttpException("Error executing player GET command, URL: " + url);
        }
    }
```
