### ISSUE TITLE
[unifi] NPE from channelConfigPoeEnableMode

### ISSUE THREAD

**Issue by morph166955** [openhab/openhab-addons#15850]
I just updated to snapshot 3707 and I'm now getting this NPE on start.  I believe I was on 3683 before this.

```
2023-11-05 14:27:07.416 [ERROR] [nal.common.AbstractInvocationHandler] - An error occurred while calling method 'ThingHandler.initialize()' on 'org.openhab.binding.unifi.internal.handler.UniFiPoePortThingHandler@1d506e4b': Cannot invoke "String.isBlank()" because "channelConfigPoeEnableMode" is null
java.lang.NullPointerException: Cannot invoke "String.isBlank()" because "channelConfigPoeEnableMode" is null
        at org.openhab.binding.unifi.internal.handler.UniFiPoePortThingHandler.initPoeEnableMode(UniFiPoePortThingHandler.java:92) ~[?:?]
        at org.openhab.binding.unifi.internal.handler.UniFiPoePortThingHandler.initialize(UniFiPoePortThingHandler.java:81) ~[?:?]
        at org.openhab.binding.unifi.internal.handler.UniFiPoePortThingHandler.initialize(UniFiPoePortThingHandler.java:1) ~[?:?]
        at org.openhab.binding.unifi.internal.handler.UniFiBaseThingHandler.initialize(UniFiBaseThingHandler.java:67) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor71.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.openhab.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:147) [bundleFile:?]
        at org.openhab.core.internal.common.Invocation.call(Invocation.java:52) [bundleFile:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:840) [?:?]
```

**Comment by lsiepel** [comment]
Weird. This is a configuration setting for the `poePort` thing with channel `enable` typeId `poeEnable` that defaults to AUTO.

So you managed to not have a configuration while it has a default ?!

**Comment by morph166955** [comment]
Yeah not entirely sure how it happened either.  I did import a bunch of configs from text a while back (I migrated all things and items into the database), I suppose it could have been a failing when that happened?

**Comment by lsiepel** [comment]
Might be. As there is already a fallback to default when an empty configuration is available, i added a defensive null check that should fix this in any case.
