### ISSUE TITLE
[miio] sends empty commands leading to big delays

### ISSUE THREAD

**Issue by tiller** [openhab/openhab-addons#15994]
Having a Roborock Vacuum Q Revo configured in openhab 4.0.4 (same version for addons), sending commands to the robot usually takes 30s before being registered by the robot.

After some digging, my issue is that some empty commands are sent to the robot, commands that the robot ignore and doesn't even bother to respond to. This leads to the MiIoAsyncCommunication waiting for a reply that'll never come, and then timeout after 15s. As it schedules these empty commands by pairs, I have to wait 30s before my command is processed.

## Expected Behavior
No delay in the command execution

## Current Behavior
Empty commands are regularly scheduled:
```
2023-12-02 18:15:20.429 [DEBUG] [nal.transport.MiIoAsyncCommunication] - Command added to Queue {"id":8844,"method":"get_dnd_timer","params":[]} -> 192.168.2.190 (Device: 736234649 token: 39743934XXXXXXXXXXXXXXXX43306454 Queue: 1).
2023-12-02 18:15:20.429 [DEBUG] [nal.transport.MiIoAsyncCommunication] - Command added to Queue {"id":8845,"method":"get_clean_summary","params":[]} -> 192.168.2.190 (Device: 736234649 token: 39743934XXXXXXXXXXXXXXXX43306454 Queue: 2).
2023-12-02 18:15:20.429 [DEBUG] [nal.transport.MiIoAsyncCommunication] - Command added to Queue {"id":8846,"method":"get_status","params":[]} -> 192.168.2.190 (Device: 736234649 token: 39743934XXXXXXXXXXXXXXXX43306454 Queue: 3).
2023-12-02 18:15:20.429 [DEBUG] [nal.transport.MiIoAsyncCommunication] - Command added to Queue {"id":8847,"method":"get_consumable","params":[]} -> 192.168.2.190 (Device: 736234649 token: 39743934XXXXXXXXXXXXXXXX43306454 Queue: 4).
2023-12-02 18:15:20.429 [DEBUG] [nal.transport.MiIoAsyncCommunication] - Command added to Queue {"id":8848,"method":"","params":[]} -> 192.168.2.190 (Device: 736234649 token: 39743934XXXXXXXXXXXXXXXX43306454 Queue: 5).
2023-12-02 18:15:20.430 [DEBUG] [nal.transport.MiIoAsyncCommunication] - Command added to Queue {"id":8849,"method":"","params":[]} -> 192.168.2.190 (Device: 736234649 token: 39743934XXXXXXXXXXXXXXXX43306454 Queue: 6).
2023-12-02 18:15:50.430 [DEBUG] [nal.transport.MiIoAsyncCommunication] - Command added to Queue {"id":8850,"method":"get_dnd_timer","params":[]} -> 192.168.2.190 (Device: 736234649 token: 39743934XXXXXXXXXXXXXXXX43306454 Queue: 1).
2023-12-02 18:15:50.430 [DEBUG] [nal.transport.MiIoAsyncCommunication] - Command added to Queue {"id":8851,"method":"get_clean_summary","params":[]} -> 192.168.2.190 (Device: 736234649 token: 39743934XXXXXXXXXXXXXXXX43306454 Queue: 2).
2023-12-02 18:15:50.430 [DEBUG] [nal.transport.MiIoAsyncCommunication] - Command added to Queue {"id":8852,"method":"get_status","params":[]} -> 192.168.2.190 (Device: 736234649 token: 39743934XXXXXXXXXXXXXXXX43306454 Queue: 3).
2023-12-02 18:15:50.430 [DEBUG] [nal.transport.MiIoAsyncCommunication] - Command added to Queue {"id":8853,"method":"miIO.info","params":[]} -> 192.168.2.190 (Device: 736234649 token: 39743934XXXXXXXXXXXXXXXX43306454 Queue: 4).
2023-12-02 18:15:50.430 [DEBUG] [nal.transport.MiIoAsyncCommunication] - Command added to Queue {"id":8854,"method":"get_consumable","params":[]} -> 192.168.2.190 (Device: 736234649 token: 39743934XXXXXXXXXXXXXXXX43306454 Queue: 5).
2023-12-02 18:15:50.430 [DEBUG] [nal.transport.MiIoAsyncCommunication] - Command added to Queue {"id":8855,"method":"","params":[]} -> 192.168.2.190 (Device: 736234649 token: 39743934XXXXXXXXXXXXXXXX43306454 Queue: 6).
2023-12-02 18:15:50.430 [DEBUG] [nal.transport.MiIoAsyncCommunication] - Command added to Queue {"id":8856,"method":"","params":[]} -> 192.168.2.190 (Device: 736234649 token: 39743934XXXXXXXXXXXXXXXX43306454 Queue: 7).
2023-12-02 18:16:20.431 [DEBUG] [nal.transport.MiIoAsyncCommunication] - Command added to Queue {"id":8857,"method":"get_dnd_timer","params":[]} -> 192.168.2.190 (Device: 736234649 token: 39743934XXXXXXXXXXXXXXXX43306454 Queue: 1).
2023-12-02 18:16:20.431 [DEBUG] [nal.transport.MiIoAsyncCommunication] - Command added to Queue {"id":8858,"method":"get_clean_summary","params":[]} -> 192.168.2.190 (Device: 736234649 token: 39743934XXXXXXXXXXXXXXXX43306454 Queue: 2).
2023-12-02 18:16:20.431 [DEBUG] [nal.transport.MiIoAsyncCommunication] - Command added to Queue {"id":8859,"method":"get_status","params":[]} -> 192.168.2.190 (Device: 736234649 token: 39743934XXXXXXXXXXXXXXXX43306454 Queue: 3).
2023-12-02 18:16:20.431 [DEBUG] [nal.transport.MiIoAsyncCommunication] - Command added to Queue {"id":8860,"method":"get_consumable","params":[]} -> 192.168.2.190 (Device: 736234649 token: 39743934XXXXXXXXXXXXXXXX43306454 Queue: 4).
2023-12-02 18:16:20.431 [DEBUG] [nal.transport.MiIoAsyncCommunication] - Command added to Queue {"id":8861,"method":"","params":[]} -> 192.168.2.190 (Device: 736234649 token: 39743934XXXXXXXXXXXXXXXX43306454 Queue: 5).
2023-12-02 18:16:20.431 [DEBUG] [nal.transport.MiIoAsyncCommunication] - Command added to Queue {"id":8862,"method":"","params":[]} -> 192.168.2.190 (Device: 736234649 token: 39743934XXXXXXXXXXXXXXXX43306454 Queue: 6).
2023-12-02 18:16:50.431 [DEBUG] [nal.transport.MiIoAsyncCommunication] - Command added to Queue {"id":8863,"method":"get_dnd_timer","params":[]} -> 192.168.2.190 (Device: 736234649 token: 39743934XXXXXXXXXXXXXXXX43306454 Queue: 1).
2023-12-02 18:16:50.432 [DEBUG] [nal.transport.MiIoAsyncCommunication] - Command added to Queue {"id":8864,"method":"get_clean_summary","params":[]} -> 192.168.2.190 (Device: 736234649 token: 39743934XXXXXXXXXXXXXXXX43306454 Queue: 2).
2023-12-02 18:16:50.432 [DEBUG] [nal.transport.MiIoAsyncCommunication] - Command added to Queue {"id":8865,"method":"get_status","params":[]} -> 192.168.2.190 (Device: 736234649 token: 39743934XXXXXXXXXXXXXXXX43306454 Queue: 3).
2023-12-02 18:16:50.432 [DEBUG] [nal.transport.MiIoAsyncCommunication] - Command added to Queue {"id":8866,"method":"miIO.info","params":[]} -> 192.168.2.190 (Device: 736234649 token: 39743934XXXXXXXXXXXXXXXX43306454 Queue: 4).
2023-12-02 18:16:50.432 [DEBUG] [nal.transport.MiIoAsyncCommunication] - Command added to Queue {"id":8867,"method":"get_consumable","params":[]} -> 192.168.2.190 (Device: 736234649 token: 39743934XXXXXXXXXXXXXXXX43306454 Queue: 5).
2023-12-02 18:16:50.432 [DEBUG] [nal.transport.MiIoAsyncCommunication] - Command added to Queue {"id":8868,"method":"","params":[]} -> 192.168.2.190 (Device: 736234649 token: 39743934XXXXXXXXXXXXXXXX43306454 Queue: 6).
2023-12-02 18:16:50.432 [DEBUG] [nal.transport.MiIoAsyncCommunication] - Command added to Queue {"id":8869,"method":"","params":[]} -> 192.168.2.190 (Device: 736234649 token: 39743934XXXXXXXXXXXXXXXX43306454 Queue: 7).
```

![image](https://github.com/openhab/openhab-addons/assets/831119/4b2afeb9-de5e-48e1-ad5e-b7e5fadbd236)

JSON body of first packet is : {"id":8244,"method":"","params":[]}
We can see that we receive no answer from robot, then timeout after 15s

## Possible Solution
Don't add empty commands to queue, or ignore empty commands that are in the queue.

## Steps to Reproduce (for Bugs)
I simply have my robot:
```
Thing miio:vacuum:vacuum3  "Robot aspirateur"  [ host="192.168.2.190", token="...", deviceId="736234649", model="roborock.vacuum.a75", communication="direct" ]
```

## Your Environment
OpenHAB (add-ons) from branch 4.0.x + cherrypick [5555d68](https://github.com/openhab/openhab-addons/commit/5555d68f923d76d0b1b70b4ab6caa5e50362ffd6)
then after upgrade, I have the same issue with vanilla openhab 4.1.1

**Comment by Tiller** [comment]
```
        at org.openhab.binding.miio.internal.transport.MiIoAsyncCommunication.queueCommand(MiIoAsyncCommunication.java:158) ~[?:?]
        at org.openhab.binding.miio.internal.handler.MiIoAbstractHandler.sendCommand(MiIoAbstractHandler.java:315) ~[?:?]
        at org.openhab.binding.miio.internal.handler.MiIoAbstractHandler.sendCommand(MiIoAbstractHandler.java:292) ~[?:?]
        at org.openhab.binding.miio.internal.handler.MiIoAbstractHandler.sendCommand(MiIoAbstractHandler.java:270) ~[?:?]
        at org.openhab.binding.miio.internal.handler.MiIoVacuumHandler.updateData(MiIoVacuumHandler.java:531) ~[?:?]
        at org.openhab.binding.miio.internal.handler.MiIoAbstractHandler.lambda$2(MiIoAbstractHandler.java:196) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

So this is probably due to empty strings in RobotCababilities

**Comment by Tiller** [comment]
Just updated to openhab 4.1.1, with no customizations, and I still have empty commands that are sent and that delays all legitimates commands

```
2024-01-24 10:49:34.965 [DEBUG] [nal.transport.MiIoAsyncCommunication] - Command added to Queue {"id":12618,"method":"","params":[]} -> 192.168.2.190 (Device: 736234649 token: 39743934XXXXXXXXXXXXXXXX43306454 Queue: 6).
2024-01-24 10:49:34.965 [DEBUG] [nal.transport.MiIoAsyncCommunication] - Command added to Queue {"id":12619,"method":"","params":[]} -> 192.168.2.190 (Device: 736234649 token: 39743934XXXXXXXXXXXXXXXX43306454 Queue: 7).
```

**Comment by marcelrv** [comment]
my guess is that the specific PR you cherry picked is the cause. 
Indeed this needs to be further investigated.
