### ISSUE TITLE
[Synop] stops updating

### ISSUE THREAD

**Issue by matmai** [openhab/openhab-addons#16006]
## Expected Behavior
The synop items should be updated every 60mins.

## Current Behavior
Around every week the synop items are not updated any more.
In `openhab.log` I get the following error:
```
2023-12-04 00:43:59.756 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception:
java.lang.ArrayIndexOutOfBoundsException: Index -12 out of bounds for length 16
        at org.openhab.binding.synopanalyzer.internal.synop.WindDirections.getWindDirection(WindDirections.java:47) ~[?:?]
        at org.openhab.binding.synopanalyzer.internal.handler.SynopAnalyzerHandler.getChannelState(SynopAnalyzerHandler.java:188) ~[?:?]
        at org.openhab.binding.synopanalyzer.internal.handler.SynopAnalyzerHandler.lambda$5(SynopAnalyzerHandler.java:158) ~[?:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at org.openhab.binding.synopanalyzer.internal.handler.SynopAnalyzerHandler.lambda$3(SynopAnalyzerHandler.java:155) ~[?:?]
        at java.util.Optional.ifPresentOrElse(Optional.java:196) ~[?:?]
        at org.openhab.binding.synopanalyzer.internal.handler.SynopAnalyzerHandler.updateChannels(SynopAnalyzerHandler.java:153) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

## Possible Solution
As a workaround I can disable the Synop thing via UI and enable it. Than it works for around a week. The log shows the following right after enabling:
```
2023-12-04 14:54:04.657 [INFO ] [nternal.handler.SynopAnalyzerHandler] - Scheduling Synop update thread to run every 60 minute for Station '4711'
```

## Steps to Reproduce (for Bugs)

1. Install Synop Analyzer Binding
2. Add thing configuration (station ID)
3. Link items to thing as in [example](https://www.openhab.org/addons/bindings/synopanalyzer/#items)
4. Wait for items to not be updated any longer

## Context

I already had similar issues with synop on OH 2.5 but not that often. This is a new installation started from scratch with not many configs yet.

## Your Environment

* Version used: 4.0.3
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...): openhabian
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): Bullseye Linux 6.1.21

**Comment by clinique** [comment]
Hello @matmai , can you please try [this](https://drive.google.com/file/d/1maBzGiZfPtJXdlmvDDanD_NAwaEK0pl3/view?usp=drive_link)

**Comment by matmai** [comment]
I am trying your 4.1.0 snapshot of synop but could not find it after [installing via addons folder](https://www.openhab.org/docs/administration/bundles.html#installation-via-the-addons-folder). Do I need the 4.1.0.M4 of openHAB Core?

 At least I can confirm in the meantime that it is a data problem because my old OH 2.5.x installation with the same synop thing had the same exceptions 9 mins later in the log.

**Comment by clinique** [comment]
Yes, there's a great probability that you need to use OH4.1 to get it running.
