### ISSUE TITLE
Venstar Binding - java.lang.NoSuchMethodError, 4.0.4 and 4.1.0M4

### ISSUE THREAD

**Issue by jferfolia** [openhab/openhab-addons#16040]
Updated openHAB, was running stable 4.04. Tried with milestone build, same error.

Depreciated var type?

2023-12-10 13:44:02.922 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception: 
java.lang.NoSuchMethodError: 'void org.openhab.core.library.types.DecimalType.<init>(long)'
	at org.openhab.binding.venstarthermostat.internal.handler.VenstarThermostatHandler.updateData(VenstarThermostatHandler.java:509) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:840) [?:?]

**Comment by maniac103** [comment]
Sounds like the (external) binding you're using isn't suited for the OH version you're using?

**Comment by jferfolia** [comment]
> Sounds like the (external) binding you're using isn't suited for the OH version you're using?

It's the Venstar 4.0.4 binding. I thought I opened this bug under that.

Was working now fails with that error. No luck updating to the 4.1 snapshot build of the binding either.

**Comment by maniac103** [comment]
Line numbers don't match up here. Line 509 in VenstarThermostatHandler.java in 4.0.4 sources don't reference DecimalType.
Do you have by any chance a 3.x binding in your addons folder?

**Comment by jferfolia** [comment]
> Line numbers don't match up here. Line 509 in VenstarThermostatHandler.java in 4.0.4 sources doesn't reference DecimalType. Do you have by any chance a 3.x binding in your addons folder?

I did in fact still have the 3.2 version in my addons folder. Removed it and all is well in the world again.

Feel stupid about that, but live and learn.

Much appreciated.
