### ISSUE TITLE
[iCalendar] iCalendar Binding fails to install on 4.1.0

### ISSUE THREAD

**Issue by icompas** [openhab/openhab-addons#16123]
## Expected Behavior
After downloading the addo-on from the addon store the bundles should refresh and the addon should be active and available.

## Current Behavior
Installation fails with the following error message:

```
2023-12-27 16:15:45.164 [ERROR] [core.karaf.internal.FeatureInstaller] - Failed installing 'openhab-binding-icalendar': Error:
	invalid header field (line 1505)
2023-12-27 16:15:45.480 [ERROR] [core.karaf.internal.FeatureInstaller] - Failed to refresh bundles after processing config update
org.apache.karaf.features.internal.util.MultiException: Error:
	invalid header field (line 1505)
	at org.apache.karaf.features.internal.download.impl.MavenDownloadManager$MavenDownloader.<init>(MavenDownloadManager.java:91) ~[?:?]
	at org.apache.karaf.features.internal.download.impl.MavenDownloadManager.createDownloader(MavenDownloadManager.java:72) ~[?:?]
	at org.apache.karaf.features.internal.region.Subsystem.downloadBundles(Subsystem.java:474) ~[?:?]
	at org.apache.karaf.features.internal.region.Subsystem.downloadBundles(Subsystem.java:469) ~[?:?]
	at org.apache.karaf.features.internal.region.SubsystemResolver.resolve(SubsystemResolver.java:223) ~[?:?]
	at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:399) ~[?:?]
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1069) ~[?:?]
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.lambda$doProvisionInThread$13(FeaturesServiceImpl.java:1004) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:840) [?:?]
	Suppressed: java.io.IOException: invalid header field (line 1505)
		at java.util.jar.Attributes.read(Attributes.java:406) ~[?:?]
		at java.util.jar.Manifest.read(Manifest.java:347) ~[?:?]
		at java.util.jar.Manifest.<init>(Manifest.java:100) ~[?:?]
		at java.util.jar.Manifest.<init>(Manifest.java:76) ~[?:?]
		at org.apache.karaf.features.internal.region.Subsystem.getMetadata(Subsystem.java:682) ~[?:?]
		at org.apache.karaf.features.internal.region.Subsystem.lambda$downloadBundles$1(Subsystem.java:516) ~[?:?]
		at org.apache.karaf.features.internal.download.impl.MavenDownloadManager$MavenDownloader.lambda$download$0(MavenDownloadManager.java:138) ~[?:?]
		at org.apache.karaf.features.internal.download.impl.DefaultFuture.notifyListener(DefaultFuture.java:350) ~[?:?]
		at org.apache.karaf.features.internal.download.impl.DefaultFuture.notifyListeners(DefaultFuture.java:335) ~[?:?]
		at org.apache.karaf.features.internal.download.impl.DefaultFuture.setValue(DefaultFuture.java:259) ~[?:?]
		at org.apache.karaf.features.internal.download.impl.AbstractDownloadTask.setFile(AbstractDownloadTask.java:61) ~[?:?]
		at org.apache.karaf.features.internal.download.impl.AbstractRetryableDownloadTask.run(AbstractRetryableDownloadTask.java:61) ~[?:?]
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
		at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
		at java.lang.Thread.run(Thread.java:840) [?:?]
```

## Steps to Reproduce (for Bugs)
1. Simply start the instalaltion via the Add-on Store
2. Monitor the openhab.log file

## Your Environment
* Version used: 4.1.0 with 4.1.0 addon repository
* Environment name and version: Firefox 121 
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): Debian GNU/Linux 12 (bookworm)

**Comment by wborn** [comment]
> 1. Simply start the instalaltion via the Add-on Store
> 2. Monitor the openhab.log file

It installs just fine for me. Did you try to clean the cache and reinstall the add-on? Maybe the download got corrupt somehow.

**Comment by icompas** [comment]
Reboot/Restart fixed the issue.
