### ISSUE TITLE
[boschshc] NullPointerException during discovery

### ISSUE THREAD

**Issue by david-pace** [openhab/openhab-addons#16188]
## Expected Behavior
The discovery should never run into a `NullPointerException`

## Current Behavior
User @mike-bike reported that the discovery ran into the following NPE on his system:

```
2024-01-02 21:10:59.070 [ERROR] [y.mdns.internal.MDNSDiscoveryService] - Participant 'org.openhab.binding.boschshc.internal.discovery.BridgeDiscoveryParticipant' threw an exception
java.lang.NullPointerException: Cannot invoke "String.isBlank()" because "ipAddress" is null
  at org.openhab.binding.boschshc.internal.discovery.BridgeDiscoveryParticipant.getThingUID(BridgeDiscoveryParticipant.java:114) ~[?:?]
  at org.openhab.binding.boschshc.internal.discovery.BridgeDiscoveryParticipant.createResult(BridgeDiscoveryParticipant.java:97) ~[?:?]
  at org.openhab.core.config.discovery.mdns.internal.MDNSDiscoveryService.createDiscoveryResult(MDNSDiscoveryService.java:222) [bundleFile:?]
  at org.openhab.core.config.discovery.mdns.internal.MDNSDiscoveryService.considerService(MDNSDiscoveryService.java:214) [bundleFile:?]
  at org.openhab.core.config.discovery.mdns.internal.MDNSDiscoveryService.serviceResolved(MDNSDiscoveryService.java:207) [bundleFile:?]
  at javax.jmdns.impl.ListenerStatus$ServiceListenerStatus.serviceResolved(ListenerStatus.java:106) [bundleFile:3.5.8
  at javax.jmdns.impl.JmDNSImpl$1.run(JmDNSImpl.java:911) [bundleFile:3.5.8]
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
  at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
  at java.lang.Thread.run(Thread.java:840) [?:?]
```

## Possible Solution
At first glance the IP address should never be null at this point. All objects of type `PublicInformation` should have a non-null `ipAddress` because it is always initialized to an empty string:

```java
public PublicInformation() {
    this.shcIpAddress = "";
    this.shcGeneration = "";
}
```

Has to be analyzed further.

## Steps to Reproduce (for Bugs)
It is not clear yet if this issue can be reproduced in a deterministic fashion.

## Context
Binding becomes unusable after a certain amount of time.

## Your Environment
* Version: openHAB `4.1.0`
* Operating System: openHABbian

**Comment by GerdZanker** [comment]
Based on a five minute code review of the BridgeDiscoveryParticipant the NPE is strange.
Small brain storing result of root causes:
* Is it possible that "new PublicInformation();" returns Null?
* Can threading/race conditions result in an invalid bridgeInformation field value?

**Comment by david-pace** [comment]
Regarding point 1: I don't think that `new PublicInformation()` can be `null`. If it was `null`, I think we would get the NPE already in the line before:

```java
String ipAddress = discoverBridge(serviceInfo).shcIpAddress;
```

However, we get the NPE later in the next line:

```
if (!ipAddress.isBlank())
```

So we are dealing with a non-null `PublicInformation` object that has the property `ipAddress` set to `null`. But I still can't see how this could happen, even with multiple threads...

**Comment by david-pace** [comment]
This issue will probably also be solved with https://github.com/openhab/openhab-addons/pull/16211.
