### ISSUE TITLE
[hue] "Cannot read field "ct" because "capabilities.control"" after upgrade to 4.1.0 from 3.x

### ISSUE THREAD

**Issue by dan-m-joha** [openhab/openhab-addons#16180]
After upgrading to openHAB 4.1.0 from 3.x (sorry can not say exact release) I have started getting the following error from my HUE-Bridge (deCONZ) in the openhab-log:

```
2024-01-02 08:44:32.973 [ERROR] [core.thing.internal.ThingManagerImpl] - Exception occurred during notification about bridge status change on thing 'hue:0010:huebridge:3': Cannot read field "ct" because "capabilities.control"
java.lang.NullPointerException: Cannot read field "ct" because "capabilities.control" is null
        at org.openhab.binding.hue.internal.handler.HueLightHandler.initializeCapabilities(HueLightHandler.java:197) ~[?:?]
        at org.openhab.binding.hue.internal.handler.HueLightHandler.initializeThing(HueLightHandler.java:148) ~[?:?]
        at org.openhab.binding.hue.internal.handler.HueLightHandler.bridgeStatusChanged(HueLightHandler.java:129) ~[?:?]
        at org.openhab.core.thing.internal.ThingManagerImpl.lambda$11(ThingManagerImpl.java:822) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

And the Things changes to "ERROR:BRIDGE" status while the HUE-Bridge "stays" in ONLINE status:

![image](https://github.com/openhab/openhab-addons/assets/36599761/baf821ff-8102-4982-b712-2d2d73ce429c)

![image](https://github.com/openhab/openhab-addons/assets/36599761/473ea357-5491-4426-b757-cedc9bdb67a5)

After a reboot everything is once again green for some time, then it fails again.

## My Environment
- OS: Fedora Linux 37 (Server Edition)
- openhab.noarch  4.1.0-1 @openHAB-Stable
- openhab-addons.noarch    4.1.0-1  @openHAB-Stable
- java-17-openjdk.x86_64     1:17.0.8.0.7-1.fc37     @updates
- java-17-openjdk-headless.x86_64     1:17.0.8.0.7-1.fc37    @updates
- nodejs.x86_64     1:18.18.2-1.fc37    @updates
- deCONZ - Phoscon App Gateway version 2.24.2, Firmware 26720700

I have deleted and "reinstalled" the HUE-Bridge-Binding and deCONZ-Bindig , but this did not help.

Any suggestions for a solution or "workaround"?

-- 
Dan

**Comment by andrewfg** [comment]
Can you please explain what is deconz and how does it relate to hue?

**Comment by maniac103** [comment]
Deconz is a [Zigbee central software](https://phoscon.de/en/conbee2/software), and AFAIK one of its features is emulating a Hue bridge ... apparently the emulation isn't perfect.
@dan-m-joha Is there any reason why you use the hue binding instead of the deconz binding to talk to it? As far as I am aware, ultimately both bindings should bridge the Zigbee devices into openHAB.

**Comment by andrewfg** [comment]
> one of its features is emulating a Hue bridge ... apparently the emulation isn't perfect.

@maniac103 so the OP has a problem that the deconz emulation is wrongly interacting with the OH binding via API v1. Or??

As Philips has deprecated API v1 and is only focussing on API v2, I see little chance of anyone here wanting to spend time on v1 code -- in particular if it relates to a broken emulation. (To be clear: 'not me'..)

So does deconz now also (try to) emulate API v2? If that was the case, we could perhaps look at that. WDYT?

**Comment by jlaur** [comment]
@dan-m-joha - there's a JAR here for 4.1 which should fix the issue: [org.openhab.binding.hue-4.1.2-SNAPSHOT.jar](https://drive.google.com/file/d/1ctIPmD1S9BFcMZiVRXRHdzQMOMjXkG4d/view?usp=sharing)

**Comment by dan-m-joha** [comment]
And how do I install that jar-file?
(sorry that I have not reacted before, I have had some issues with notifications from github)

**Comment by jlaur** [comment]
> And how do I install that jar-file?

See https://www.openhab.org/docs/configuration/addons.html#through-manually-provided-add-ons. Before copying the JAR file into your addons directory, you need to uninstall the official binding.

**Comment by dan-m-joha** [comment]
Great, thanks for the fix and the info on how to install.
It seems to work now (at least I do not get an error message directly on startup).
Once again thanks for your support!
