### ISSUE TITLE
[tellstick] HTTP 401 Error

### ISSUE THREAD

**Issue by andrewfg** [openhab/openhab-addons#16242]
> I still use Telldus live bridge, but it seams to not work for me with new jar  "org.openhab.binding.tellstick-4.2.0-SNAPSHOT.jar" 

```
Request [http://pa-api.telldus.com/xml/devices/list?supportedMethods=19] failed: ExecutionException HTTP request returned status code 401
2024-01-07 15:06:53.774 [WARN ] [ternal.live.TelldusLiveBridgeHandler] - Failed to update
org.openhab.binding.tellstick.internal.live.TelldusLiveException: HTTP request returned status code 401
	at org.openhab.binding.tellstick.internal.live.TelldusLiveDeviceController.callRestMethod(TelldusLiveDeviceController.java:299) ~[?:?]
	at org.openhab.binding.tellstick.internal.live.TelldusLiveBridgeHandler.updateDevices(TelldusLiveBridgeHandler.java:155) ~[?:?]
	at org.openhab.binding.tellstick.internal.live.TelldusLiveBridgeHandler.refreshDeviceList(TelldusLiveBridgeHandler.java:124) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.util.concurrent.ExecutionException: HTTP request returned status code 401
	at org.openhab.binding.tellstick.internal.live.TelldusLiveDeviceController.innerCallRest(TelldusLiveDeviceController.java:350) ~[?:?]
	at org.openhab.binding.tellstick.internal.live.TelldusLiveDeviceController.callRestMethod(TelldusLiveDeviceController.java:290) ~[?:?]
	... 8 more
```

_Originally posted by @dabj123 in https://github.com/openhab/openhab-addons/issues/16220#issuecomment-1880071877_

**Comment by andrewfg** [comment]
an HTTP 401 error means 'authentication failed' so check your login credentials please.

> still recieve 401 or 429.

these are TWO different issues..

* HTTP 401 is an authentication error
* HTTP 429 is because you are sending a retry request faster than 10 seconds _"Kontrollera och dubbelkolla att dina skript inte gör nya försök att kontakta Telldus API utan att vänta minst 10 sekunder. Försök på nytt utan fördröjning kommer innebära HTTP 429 error."_
 
I am guessing that if the HTTP 401 error is fixed, then there will not be any retries, so the HTTP 429 error will probably go away.

> Request [http://pa-api.telldus.com/xml/devices/list?supportedMethods=19] failed: ExecutionException HTTP request returned status code 401
> 
> OAuth Verification Failed: Can't verify request, missing oauth_consumer_key or oauth_token

> I have renew new keys etc. Maybe TellStick have new logic in the new api to handle OAuth Verification...

https://api.telldus.com/documentation/live

**Comment by andrewfg** [comment]
@dabj123 the bridge configuration asks for the configuration parameters below .. the [readme](https://www.openhab.org/addons/bindings/tellstick/#telldus-live-bridge) and the [api documentation](https://api.telldus.com/documentation/live) say you need to follow **_four_** steps. Probably you must redo **_all_** of those four mentioned steps since the API is on a new url and any keys associated with the old url will almost certainly not be valid for the new one.

**_Note: that when renewing the keys, anywhere that it mentions the old url `https://api.telldis.com` in the documentation you obviously need to use the new url `https://pa-api.telldis.com` instead._**

```
public class TelldusLiveConfiguration {
    public String publicKey;
    public String privateKey;
    public String token;
    public String tokenSecret;
}
```

**Comment by dabj123** [comment]
You will get "429 Too Many Requests", when you try to surf to https://pa-api.telldus.com/ and click a round...  I think telldus have som problem with their server.

**Comment by andrewfg** [comment]
> telldus have som problem with their server.

Can you ask them?

**Comment by dabj123** [comment]
Certainly, I have already sent them an email. I will let you know when I receive a response.

**Comment by dabj123** [comment]
https://x.com/telldus_status/status/1732778890391609597?s=20

**Comment by andrewfg** [comment]
^
No news since December 7th 2023..

**Comment by lsiepel** [comment]
Is this still an active issue to look at? @AndrewFG or @dabj123 ?

**Comment by andrewfg** [comment]
I gave up on this one. The manufacturer changed their api and refuses to respond to any queries. From my perspective you can close it as "won't fix"

**Comment by lsiepel** [comment]
Can you write some words on the impact of this? Does it meen that this binding is crippled, should be removed, or some lines to the readme?

**Comment by andrewfg** [comment]
I am not a tellstick user so I don't know the answer. Either they reverted to the prior api (in which case it works again) or they did not (in which case it is permanently broken and should be removed). Maybe @dabj123 can give a better answer?
