### ISSUE TITLE
[rotel] SocketException: connection reset (serial over IP connection)

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-addons#16289]
As there were no changes in the binding itself, I am afraid something in the core framework broke the binding !

```
19:12:49.676 [DEBUG] [ternal.communication.RotelIpConnector] - Opening IP connection on IP 192.xxx.xx.xx port YYYY
19:12:52.887 [DEBUG] [ternal.communication.RotelIpConnector] - IP connection opened
19:12:52.887 [DEBUG] [ernal.communication.RotelReaderThread] - Data listener started
19:12:52.894 [DEBUG] [g.rotel.internal.handler.RotelHandler] - openConnection(): connected
19:12:52.900 [DEBUG] [g.rotel.internal.handler.RotelHandler] - Schedule power OFF job
19:12:52.905 [DEBUG] [.protocol.hex.RotelHexProtocolHandler] - Command "Display Refresh" => FE03C210FFD4
19:12:52.912 [DEBUG] [internal.communication.RotelConnector] - Send command "Display Refresh" succeeded
19:12:52.918 [INFO ] [hab.event.ThingStatusInfoChangedEvent] - Thing 'rotel:rsp1066:preamp' changed from UNKNOWN to ONLINE
19:12:53.747 [DEBUG] [ternal.communication.RotelIpConnector] - readInput failed: Connection reset
19:12:53.754 [DEBUG] [ernal.communication.RotelReaderThread] - Reading failed: readInput failed
org.openhab.binding.rotel.internal.RotelException: readInput failed
        at org.openhab.binding.rotel.internal.communication.RotelIpConnector.readInput(RotelIpConnector.java:127) ~[bundleFile:?]
        at org.openhab.binding.rotel.internal.communication.RotelReaderThread.run(RotelReaderThread.java:60) [bundleFile:?]
Caused by: java.net.SocketException: Connection reset
        at sun.nio.ch.NioSocketImpl.implRead(Unknown Source) ~[?:?]
        at sun.nio.ch.NioSocketImpl.read(Unknown Source) ~[?:?]
        at sun.nio.ch.NioSocketImpl$1.read(Unknown Source) ~[?:?]
        at java.net.Socket$SocketInputStream.read(Unknown Source) ~[?:?]
        at java.io.DataInputStream.read(Unknown Source) ~[?:?]
        at org.openhab.binding.rotel.internal.communication.RotelIpConnector.readInput(RotelIpConnector.java:122) ~[bundleFile:?]
        ... 1 more
19:12:53.765 [DEBUG] [g.rotel.internal.handler.RotelHandler] - onNewMessageEvent: key error = on
19:12:53.771 [DEBUG] [g.rotel.internal.handler.RotelHandler] - Reading feedback message failed
19:12:53.778 [DEBUG] [ternal.communication.RotelIpConnector] - Closing IP connection
19:12:53.779 [INFO ] [hab.event.ThingStatusInfoChangedEvent] - Thing 'rotel:rsp1066:preamp' changed from ONLINE to OFFLINE (COMMUNICATION_ERROR): Fin du thread de lecture
19:12:53.787 [DEBUG] [ternal.communication.RotelIpConnector] - IP connection closed
19:12:53.793 [DEBUG] [g.rotel.internal.handler.RotelHandler] - closeConnection(): disconnected
19:12:53.798 [DEBUG] [ernal.communication.RotelReaderThread] - Data listener stopped
```

**Comment by lolodomo** [comment]
Same with OH 4.1.0.

Could be a problem introduced by my migration to new PI OS. Apparently the socket connection between my 2 PIs is now failing...

**Comment by lolodomo** [comment]
Sorry, a reboot of my remote raspi solved the issue.
