### ISSUE TITLE
[XMPP] not functional EDIT: at first start

### ISSUE THREAD

**Issue by udo1toni** [openhab/openhab-addons#16375]
## Expected Behavior
To get a connection established to the xmpp server (EDIT: without the need of at least one restart)

## Current Behavior
does not connect at all...

When creating a bridge (with valid account) I only get this error message:
```
2024-02-05 15:22:52.949 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'xmppclient:xmppBridge:account' changed from UNINITIALIZED to INITIALIZING
2024-02-05 15:22:52.952 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'xmppclient:xmppBridge:account' changed from INITIALIZING to UNKNOWN
==> /var/log/openhab/openhab.log <==
2024-02-05 15:22:52.987 [ERROR] [esoftware.smack.util.dns.DNSResolver] - Could not construct InitialDirContext
javax.naming.NoInitialContextException: Cannot instantiate class: com.sun.jndi.dns.DnsContextFactory
    at javax.naming.spi.NamingManager.getFactory(NamingManager.java:762) ~[?:?]
    at javax.naming.spi.NamingManager.lambda$getInitialContext$1(NamingManager.java:724) ~[?:?]
    at jdk.internal.loader.AbstractClassLoaderValue$Memoizer.get(AbstractClassLoaderValue.java:329) ~[?:?]
    at jdk.internal.loader.AbstractClassLoaderValue.computeIfAbsent(AbstractClassLoaderValue.java:205) ~[?:?]
    at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:724) ~[?:?]
    at javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:305) ~[?:?]
    at javax.naming.InitialContext.init(InitialContext.java:236) ~[?:?]
    at javax.naming.InitialContext.<init>(InitialContext.java:208) ~[?:?]
    at javax.naming.directory.InitialDirContext.<init>(InitialDirContext.java:130) ~[?:?]
    at org.jivesoftware.smack.util.dns.javax.JavaxResolver.<clinit>(JavaxResolver.java:58) ~[?:?]
    at java.lang.Class.forName0(Native Method) ~[?:?]
    at java.lang.Class.forName(Class.java:467) ~[?:?]
    at org.jivesoftware.smack.SmackInitialization.loadSmackClass(SmackInitialization.java:193) ~[?:?]
    at org.jivesoftware.smack.SmackInitialization.parseClassesToLoad(SmackInitialization.java:173) ~[?:?]
    at org.jivesoftware.smack.SmackInitialization.processConfigFile(SmackInitialization.java:143) ~[?:?]
    at org.jivesoftware.smack.SmackInitialization.processConfigFile(SmackInitialization.java:128) ~[?:?]
    at org.jivesoftware.smack.SmackInitialization.<clinit>(SmackInitialization.java:93) ~[?:?]
    at org.jivesoftware.smack.SmackConfiguration.getVersion(SmackConfiguration.java:93) ~[?:?]
    at org.jivesoftware.smack.ConnectionConfiguration.<clinit>(ConnectionConfiguration.java:61) ~[?:?]
    at org.openhab.binding.xmppclient.internal.XMPPClient.connect(XMPPClient.java:73) ~[?:?]
    at org.openhab.binding.xmppclient.internal.handler.XMPPClientHandler.doConnect(XMPPClientHandler.java:91) ~[?:?]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
    at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
    at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.lang.IllegalAccessException: class javax.naming.spi.NamingManager (in module java.naming) cannot access class com.sun.jndi.dns.DnsContextFactory (in module jdk.naming.dns) because module jdk.naming.dns does not export com.sun.jndi.dns to module java.naming
    at jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:392) ~[?:?]
    at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:674) ~[?:?]
    at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:489) ~[?:?]
    at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
    at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347) ~[?:?]
    at java.lang.Class.newInstance(Class.java:645) ~[?:?]
    at javax.naming.spi.NamingManager.getFactory(NamingManager.java:759) ~[?:?]
    ... 26 more
2024-02-05 15:22:53.001 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception: 
java.lang.ExceptionInInitializerError: null
    at java.lang.Class.forName0(Native Method) ~[?:?]
    at java.lang.Class.forName(Class.java:467) ~[?:?]
    at org.jivesoftware.smack.SmackInitialization.loadSmackClass(SmackInitialization.java:193) ~[?:?]
    at org.jivesoftware.smack.SmackInitialization.parseClassesToLoad(SmackInitialization.java:173) ~[?:?]
    at org.jivesoftware.smack.SmackInitialization.processConfigFile(SmackInitialization.java:143) ~[?:?]
    at org.jivesoftware.smack.SmackInitialization.processConfigFile(SmackInitialization.java:128) ~[?:?]
    at org.jivesoftware.smack.SmackInitialization.<clinit>(SmackInitialization.java:93) ~[?:?]
    at org.jivesoftware.smack.SmackConfiguration.getVersion(SmackConfiguration.java:93) ~[?:?]
    at org.jivesoftware.smack.ConnectionConfiguration.<clinit>(ConnectionConfiguration.java:61) ~[?:?]
    at org.openhab.binding.xmppclient.internal.XMPPClient.connect(XMPPClient.java:73) ~[?:?]
    at org.openhab.binding.xmppclient.internal.handler.XMPPClientHandler.doConnect(XMPPClientHandler.java:91) ~[?:?]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
    at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
    at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.lang.NullPointerException
    at org.jivesoftware.smack.util.Objects.requireNonNull(Objects.java:23) ~[?:?]
    at org.jivesoftware.smack.util.Objects.requireNonNull(Objects.java:29) ~[?:?]
    at org.jivesoftware.smack.util.DNSUtil.setDNSResolver(DNSUtil.java:57) ~[?:?]
    at org.jivesoftware.smack.util.dns.javax.JavaxResolver.setup(JavaxResolver.java:79) ~[?:?]
    at org.jivesoftware.smack.util.dns.javax.JavaxResolver.<clinit>(JavaxResolver.java:64) ~[?:?]
    ... 17 more
```

## Steps to Reproduce (for Bugs)
1. Install a fresh openHAB4 Instance (on a fresh system, here LXC Container)
2. Add xmpp Addon through Addon Store
3. create a thing (xmpp bridge)

## Your Environment
* openHAB4.1.1 Release Build (installed with openHABian unattended setup)
* Java 17.0.10 64 Bit 
* Kernel Linux/6.5.11-7-pve (amd64)
* Debian 12 (inside a LXC on Proxmox 8.1.4)

**Comment by udo1toni** [comment]
So I did a restart of my test system and suddenly xmpp is awake. Seems to be a "you have to shutdown after adding the addon" problem...

**Comment by udo1toni** [comment]
Yes, it's absolutely reproducible. I did a fresh install for testing like written in the first message.
My guess is, there is some stuff which gets loaded only on system start - and obviously the developer won't notice as this stuff then will be already installed.
And even more, I tested and reproduced it with bare metal openHABian on a Raspberry Pi400 (had some laying around...)
So after getting the addon for the first time, you'll have to restart openHAB to get it working.

**Comment by lsiepel** [comment]
I can't reproduce this. The steps i followed:

1. Downloaded 4.3.0 milestone 1 
2. Started this instance, during setup i only installed some basics (astro, js automation, rrd4j, mapdb persistence) and configured location and account.
3. The log is allomst clear. Installed the XMPP-client binding. I noticed the 'installing' spinner is taking long, but at some point i navigated away and it was listed as installed.
4. I added a `xmppBridge` Thing manually in the mainUI and configured it.
5. The Thing is only and seems to function as expected. 

So i assume this issue with dependency loading has been solved between 4.1.1. and 4.3.0 milestone 1.
