### ISSUE TITLE
[KEBA] Scheduled runnable ended with an exception

### ISSUE THREAD

**Issue by Andre1Becker** [openhab/openhab-addons#16472]
## Expected Behavior
Get state of Items from Wallbox

## Current Behavior
Items not updated with values (staying at NULL). Heres something i found in openhab.log after disable and enable the keba thing:

```
2024-03-01 07:41:16.937 [DEBUG] [nternal.handler.KeContactTransceiver] - Stopping the the KEBA KeContact transceiver
2024-03-01 07:41:16.939 [DEBUG] [ba.internal.handler.KeContactHandler] - isKebaReachable() returns true
2024-03-01 07:41:16.939 [DEBUG] [nternal.handler.KeContactTransceiver] - Starting the the KEBA KeContact transceiver
2024-03-01 07:41:16.939 [INFO ] [nternal.handler.KeContactTransceiver] - Listening for incoming data on /[0:0:0:0:0:0:0:0]:7090
2024-03-01 07:41:16.939 [DEBUG] [nternal.handler.KeContactTransceiver] - Establishing the connection to the KEBA KeContact 'keba:kecontact:1a3b4b58a7'
2024-03-01 07:41:16.940 [DEBUG] [ba.internal.handler.KeContactHandler] - Running pollingRunnable to connect Keba wallbox
2024-03-01 07:41:16.941 [DEBUG] [ba.internal.handler.KeContactHandler] - isKebaReachable() returns true
2024-03-01 07:41:17.040 [DEBUG] [nternal.handler.KeContactTransceiver] - Sending 'report 1' on the channel '/openHABIP:57814'->'/WALLBOXIP:7090'
2024-03-01 07:41:17.140 [DEBUG] [nternal.handler.KeContactTransceiver] - Received {
"ID": "1",
"Product": "KC-P30-EC2204U2-M0R-CC",
"Serial": "12345678 (MASK",
"Firmware":"P30 v 3.10.53 (230713-211537)",
"COM-module": 1,
"Backend": 0,
"timeQ": 3,
"DIP-Sw1": "0xa2",
"DIP-Sw2": "0x08",
"Sec": 53381
}
 from /WALLBOXIP:7090 on the transceiver listener port 
2024-03-01 07:41:17.141 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception: 
java.lang.IllegalArgumentException: Not a valid series: 'U'
	at org.openhab.binding.keba.internal.KebaBindingConstants$KebaSeries.getSeries(KebaBindingConstants.java:106) ~[?:?]
	at org.openhab.binding.keba.internal.handler.KeContactHandler.onData(KeContactHandler.java:263) ~[?:?]
	at org.openhab.binding.keba.internal.handler.KeContactHandler.pollingRunnable(KeContactHandler.java:192) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:840) [?:?]
```

## Your Environment
using obenHAB Docker Container 4.1.1
Wallbox firmware version(s):
![image](https://github.com/openhab/openhab-addons/assets/25841903/d7cbe61e-2876-4c18-ac4c-39179e9072c3)

DSW Settings:

![image](https://github.com/openhab/openhab-addons/assets/25841903/c70a51ee-3946-473d-affb-5f7afb6f6d4d)

**Comment by MikeTheTux** [comment]
Right now the binding supports the following types:

```
        E('0'),
        B('1'),
        C('2', '3'),
        X('A', 'B', 'C', 'D', 'E', 'G', 'H');
```

You have an "U" (char 13):
`"Product": "KC-P30-EC2204U2-M0R-CC"`

Can you provide some info's on your actual device?

**Comment by MikeTheTux** [comment]
found it - it's an "X". "U" as well as "S" are missing in the above list:

![image](https://github.com/openhab/openhab-addons/assets/44850211/70e79885-6de8-4b09-bbbb-5d3068835931)

Others seem to be mapped as "X" while they miss in the screenshot ("A", "C", "D", "G").

**Comment by Andre1Becker** [comment]
Hey, @MikeTheTux,

Thanks for looking in to this!

So what does that actually mean? Could I provide you with something else like log files from the wallbox it self?

Cheers,
Andre

**Comment by MikeTheTux** [comment]
> So what does that actually mean? Could I provide you with something else like log files from the wallbox it self?

Everything needed should be available.
I will start working on a fix. While it is in review process I will ask you to give it already a try in order to test the implementation.

**Comment by Andre1Becker** [comment]
Sure, of course. Glad to help! Thanks again for your time!
Just hit me up when ists ready to test :-)

**Comment by MikeTheTux** [comment]
> Just hit me up when it's ready to test :-)

Ready: [org.openhab.binding.keba-4.2.0-SNAPSHOT-2024-03-01.zip](https://www.dropbox.com/scl/fi/4f10fw3d2dcgmzxfzbm7h/org.openhab.binding.keba-4.2.0-SNAPSHOT-2024-03-01.zip?rlkey=rcxs7gm5uypy6oz6aao1ybas8&dl=0)

**Comment by Andre1Becker** [comment]
Perfect! Will get back to you maybe tonight or tomorrow morning!

**Comment by Andre1Becker** [comment]
> > Just hit me up when it's ready to test :-)
> 
> Ready: [org.openhab.binding.keba-4.2.0-SNAPSHOT-2024-03-01.zip](https://www.dropbox.com/scl/fi/4f10fw3d2dcgmzxfzbm7h/org.openhab.binding.keba-4.2.0-SNAPSHOT-2024-03-01.zip?rlkey=rcxs7gm5uypy6oz6aao1ybas8&dl=0)

Works perfect! 
![image](https://github.com/openhab/openhab-addons/assets/25841903/6ba95c2f-0166-48a3-992f-b56fe0ce3ab3)

Thanks for the Quick Fix!

You just won the Internet Today! Have a good one mate!

**Comment by Andre1Becker** [comment]
Closed as it is fixed ;-)

**Comment by Andre1Becker** [comment]
> found it - it's an "X". "U" as well as "S" are missing in the above list:
> 
> 
> Others seem to be mapped as "X" while they miss in the screenshot ("A", "C", "D", "G").

Just for Reference:
I found it in a [different manual](https://www.keba.com/file/downloads/e-mobility/KeContact_KCP20_30_ih_de.pdf) :

![Screenshot_20240302_074817_Drive](https://github.com/openhab/openhab-addons/assets/25841903/cd521cfa-42a2-43f2-aa52-e9d147ceda38)
