### ISSUE TITLE
[upnpcontrol] Error when retrieving album art at line 1654 

### ISSUE THREAD

**Issue by mjcumming** [openhab/openhab-addons#16622]
With this change, I am now seeing the following error:

`
2024-04-06 06:18:00.224 [TRACE] [internal.handler.UpnpRendererHandler] - UPnP device Arylic Kitchen received variable InstanceID with value 0 from service AVTransport
2024-04-06 06:18:00.225 [TRACE] [internal.handler.UpnpRendererHandler] - UPnP device Arylic Kitchen received variable CurrentTrackMetaData with value <?xml version="1.0" encoding="UTF-8"?> <DIDL-Lite xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/" xmlns:song="www.wiimu.com/song/" xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/"> <upnp:class>object.item.audioItem.musicTrack</upnp:class> <item id="0"> <song:subid></song:subid> <song:description></song:description> <song:skiplimit>0</song:skiplimit> <song:id></song:id> <song:like>0</song:like> <song:singerid>0</song:singerid> <song:albumid>0</song:albumid> <song:rate_hz></song:rate_hz> <song:format_s></song:format_s> <song:bitrate>0</song:bitrate> <res protocolInfo="http-get:*:audio/mpeg:DLNA.ORG_PN=MP3;DLNA.ORG_OP=01;" duration="00:00:00.000"></res> <dc:title></dc:title> <dc:creator></dc:creator> <upnp:artist></upnp:artist> <upnp:album></upnp:album> <upnp:albumArtURI>un_known</upnp:albumArtURI> </item> </DIDL-Lite>  from service AVTransport
2024-04-06 06:18:00.228 [TRACE] [internal.handler.UpnpRendererHandler] - Renderer Arylic Kitchen, received media ID: 0
2024-04-06 06:18:00.229 [TRACE] [internal.handler.UpnpRendererHandler] - Current queue res: 
2024-04-06 06:18:00.230 [TRACE] [internal.handler.UpnpRendererHandler] - Updated media res: 
2024-04-06 06:18:00.230 [TRACE] [internal.handler.UpnpRendererHandler] - Received meta data is for current entry: true
	at org.openhab.binding.upnpcontrol.internal.handler.UpnpRendererHandler.updateMetaDataState(UpnpRendererHandler.java:1654) ~[?:?]
	at org.openhab.binding.upnpcontrol.internal.handler.UpnpRendererHandler.onValueReceivedCurrentMetaData(UpnpRendererHandler.java:1306) ~[?:?]
	at org.openhab.binding.upnpcontrol.internal.handler.UpnpRendererHandler.onValueReceived(UpnpRendererHandler.java:1089) ~[?:?]
	at org.openhab.binding.upnpcontrol.internal.handler.UpnpRendererHandler.lambda$3(UpnpRendererHandler.java:1161) ~[?:?]
2024-04-06 06:18:11.072 [DEBUG] [very.UpnpControlDiscoveryParticipant] - Device type MediaRenderer, manufacturer Rakoit Technology(SZ) Co., Ltd., model H50, SN# 00001, UDN FF97F35D-4C0A-1EB1-DA5E-0714FF97F35D
2024-04-06 06:18:11.074 [DEBUG] [control.internal.handler.UpnpHandler] - UPnP device Arylic Kitchen received status update false
2024-04-06 06:18:11.074 [DEBUG] [very.UpnpControlDiscoveryParticipant] - Media renderer found: Rakoit Technology(SZ) Co., Ltd., H50
2024-04-06 06:18:11.077 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'upnpcontrol:upnprenderer:FF97F35D-4C0A-1EB1-DA5E-0714FF97F35D' changed from ONLINE to OFFLINE (COMMUNICATION_ERROR): Communication lost with Arylic Kitchen
2024-04-06 06:19:00.151 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'upnpcontrol:upnprenderer:FF97F35D-4C0A-1EB1-DA5E-0714FF97F35D' changed from OFFLINE (COMMUNICATION_ERROR): Communication lost with Arylic Kitchen to OFFLINE (COMMUNICATION_ERROR): UPnP device with UDN FF97F35D-4C0A-1EB1-DA5E-0714FF97F35D not yet registered
`

_Originally posted by @mjcumming in https://github.com/openhab/openhab-addons/issues/16595#issuecomment-2041147440_

**Comment by mherwege** [comment]
Your newlines got lost in copying the log, making it harder to read. Could you update?

**Comment by mherwege** [comment]
Also, this looks strange, it looks like the text of the exception is partially lost. Are you sure nothing is lost in copying the log?

> 2024-04-06 06:18:00.230 [TRACE] [internal.handler.UpnpRendererHandler] - Received meta data is for current entry: true at org.openhab.binding.upnpcontrol.internal.handler.UpnpRendererHandler.updateMetaDataState(UpnpRendererHandler.java:1654) ~[?:?] at org.openhab.binding.upnpcontrol.internal.handler.UpnpRendererHandler.onValueReceivedCurrentMetaData(UpnpRendererHandler.java:1306) ~[?:?] at org.openhab.binding.upnpcontrol.internal.handler.UpnpRendererHandler.onValueReceived(UpnpRendererHandler.java:1089) ~[?:?] at org.openhab.binding.upnpcontrol.internal.handler.UpnpRendererHandler.lambda$3(UpnpRendererHandler.java:1161) ~[?:?]

**Comment by mjcumming** [comment]
I'm closing this as I think when I updated the snapshot this fix had not made it...
