### ISSUE TITLE
[jdbc] UPDATE of values in MariaDB persistence changes historic timestamp to current time

### ISSUE THREAD

**Issue by binderth** [openhab/openhab-addons#16635]
## Expected Behavior
If there's an update for a value of an item in persistence, the historic timestamp should be preserved

## Current Behavior
The UPDATE-Statement overwrites the historic timestamp with the current time.

0. create an item value with a specific timestamp
1. update the item value for that specific timestamp - at least with JDBC MariaDB/MySQL
2. the historic timestamp will be updated with current_timestamp

log-entry for first entry:
```
2024-04-10 09:52:46.658 [DEBUG] [persistence.jdbc.internal.JdbcMapper] - JDBC::storeItemValue: item=KNX_DiningWalllight (Type=SwitchItem, State=OFF, Label=Esszimmer Wandlampe, Category=lightbulb, Tags=[Light, Switch], Groups=[PL12DiningLights]) state=ON date=2024-04-09T06:00+02:00
2024-04-10 09:52:46.658 [DEBUG] [persistence.jdbc.internal.dto.ItemVO] - JDBC:ItemVO tableName=item0140; newTableName=null; 
2024-04-10 09:52:46.659 [DEBUG] [istence.jdbc.internal.db.JdbcBaseDAO] - JDBC::storeItemValueProvider: item 'KNX_DiningWalllight' as Type 'SWITCHITEM' in 'item0140' with state 'ON'
2024-04-10 09:52:46.659 [DEBUG] [istence.jdbc.internal.db.JdbcBaseDAO] - JDBC::storeItemValueProvider: itemState: 'ON'
2024-04-10 09:52:46.660 [DEBUG] [persistence.jdbc.internal.dto.ItemVO] - JDBC:ItemVO setValueTypes dbType=VARCHAR(6); javaType=class java.lang.String;
2024-04-10 09:52:46.660 [DEBUG] [istence.jdbc.internal.db.JdbcBaseDAO] - JDBC::storeItemValueProvider: other: itemState: 'ON'
2024-04-10 09:52:46.660 [DEBUG] [istence.jdbc.internal.db.JdbcBaseDAO] - JDBC::doStoreItemValue sql=INSERT INTO item0140 (time, value) VALUES( ?, ? ) ON DUPLICATE KEY UPDATE VALUE= ? timestamp=2024-04-09 06:00:00.0 value='ON'
2024-04-10 09:52:46.675 [DEBUG] [jdbc.internal.JdbcPersistenceService] - JDBC: Stored item 'KNX_DiningWalllight' as 'ON' in SQL database at Wed Apr 10 09:52:46 CEST 2024 in 17 ms.
```
![5ffaf22e4bbe05b2506165f961090be3cfe8c0b2](https://github.com/openhab/openhab-addons/assets/9037329/423780da-111f-49e4-82fa-be4410c2841a)

log-entry for 1
```
2024-04-10 09:52:46.658 [DEBUG] [persistence.jdbc.internal.JdbcMapper] - JDBC::storeItemValue: item=KNX_DiningWalllight (Type=SwitchItem, State=OFF, Label=Esszimmer Wandlampe, Category=lightbulb, Tags=[Light, Switch], Groups=[PL12DiningLights]) state=ON date=2024-04-09T06:00+02:00
2024-04-10 09:52:46.658 [DEBUG] [persistence.jdbc.internal.dto.ItemVO] - JDBC:ItemVO tableName=item0140; newTableName=null; 
2024-04-10 09:52:46.659 [DEBUG] [istence.jdbc.internal.db.JdbcBaseDAO] - JDBC::storeItemValueProvider: item 'KNX_DiningWalllight' as Type 'SWITCHITEM' in 'item0140' with state 'ON'
2024-04-10 09:52:46.659 [DEBUG] [istence.jdbc.internal.db.JdbcBaseDAO] - JDBC::storeItemValueProvider: itemState: 'ON'
2024-04-10 09:52:46.660 [DEBUG] [persistence.jdbc.internal.dto.ItemVO] - JDBC:ItemVO setValueTypes dbType=VARCHAR(6); javaType=class java.lang.String;
2024-04-10 09:52:46.660 [DEBUG] [istence.jdbc.internal.db.JdbcBaseDAO] - JDBC::storeItemValueProvider: other: itemState: 'ON'
2024-04-10 09:52:46.660 [DEBUG] [istence.jdbc.internal.db.JdbcBaseDAO] - JDBC::doStoreItemValue sql=INSERT INTO item0140 (time, value) VALUES( ?, ? ) ON DUPLICATE KEY UPDATE VALUE= ? timestamp=2024-04-09 06:00:00.0 value='ON'
2024-04-10 09:52:46.675 [DEBUG] [jdbc.internal.JdbcPersistenceService] - JDBC: Stored item 'KNX_DiningWalllight' as 'ON' in SQL database at Wed Apr 10 09:52:46 CEST 2024 in 17 ms.
```
![3db74520b71763be9eb7b7d1b5b07126fc8cb814](https://github.com/openhab/openhab-addons/assets/9037329/79155d15-c712-4fa4-83c3-3d77cb7e53e7)

## Possible Solution
The SQL-Statement "INSERT INTO item0140 (time, value) VALUES( ?, ? ) ON DUPLICATE KEY UPDATE VALUE= ? timestamp=2024-04-09 06:00:00.0 value='ON'" will not work, as items are created with "ON UPDATE CURRENT_TIMESTAMP(3) ".

Don't know how to tackle this, because, I'm sure, there's a reason for the ON UPDATE configuration.

## Steps to Reproduce (for Bugs)
see above

## Context
First encountered with the discussion in https://community.openhab.org/t/batched-data-persistence/155285/12 but could possibly be of importance with using time series.

## Your Environment
* Version used: openHAB 4.1.2 release build
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...): not applicable
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): openHABian 1.9 using Rasbian bookworm, MariaDB on an seperate DB server.

**Comment by jlaur** [comment]
@binderth - did you test with both MySQL and MariaDB? I'm using MySQL and time series are persisted correctly with provided timestamps.

**Comment by binderth** [comment]
@jlaur - to be honest, I didn't test with MySQL as it is very basic functionality I didn't expect to differ between MySQL and the fork MariaDB.

**Comment by jlaur** [comment]
@binderth - can I also ask how you reproduce it?

**Comment by binderth** [comment]
@jlaur I did use the REST API endpoint `/persistence/items/{itemname}`

**Comment by jlaur** [comment]
@binderth - thanks. So with MySQL, I was not able to reproduce. I created a Switch item, **TestSwitch**, with persistence strategy **everyChange**. I updated it to ON to have the table created and first row inserted. Then `http://openhab:8080/rest/persistence/items/TestSwitch?serviceId=jdbc&time=2024-04-01T06%3A00%3A00Z&state=OFF`. Table contents after this:
```
2024-04-01 08:00:00.000, 'OFF'
2024-04-10 22:42:29.210, 'ON'
```

I should add this was with one of the latest 4.2 snapshots, so I should probably repeat my test on 4.1.2.

**Comment by jlaur** [comment]
> I should add this was with one of the latest 4.2 snapshots, so I should probably repeat my test on 4.1.2.

This works in 4.1.2 as well, so either we are doing something differently, or it might be isolated to MariaDB.

**Comment by binderth** [comment]
@jlaur 
It _was_ both MariaDB **and** MySQL. It seems, that along the lines the CREATE-statements changed from:

```
CREATE TABLE `item0001` (
  `time` timestamp(3) NOT NULL DEFAULT current_timestamp(3) ON UPDATE current_timestamp(3),
  `value` double DEFAULT NULL,
  PRIMARY KEY (`time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;
```
to
```
CREATE TABLE `item1680` (
  `time` timestamp(3) NOT NULL,
  `value` varchar(16255) DEFAULT NULL,
  PRIMARY KEY (`time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
```

So I guess, the prolem is solved für "new" items, but for the "old" ones created in the persistence by openHAB before some version, it exists. And I think, that's true for both MySQL and MariaDB.

for reference: I recreated my current openHAB-version back in October 2023, so the current openHAB-version the persistence-items were created was [4.0.3](https://github.com/openhab/openhab-distro/releases/tag/4.0.3)

**Comment by jlaur** [comment]
That's strange. I went all the way back to openHAB 1.x in Git history and didn't find anything related to `DEFAULT current_timestamp(3) ON UPDATE current_timestamp(3)`. I have no idea how your schema was created/updated like that. My production MySQL schema also doesn't look like that, and some tables are several years old.

I'm wondering if these issues are found by the console command [`jdbc schema check`](https://www.openhab.org/addons/persistence/jdbc/#check-fix-schema)?

**Comment by binderth** [comment]
Of course I can't rule out anything related with a configuration of the MariaDB schema as I created it in the database.

**I can verify, that items created from 01.03.2024 on don't have the "ON UPDATE" argument anymore.**

* openHAB 4.1.1-release was released in January and I updated end of January
* openHAB 4.1.2-release was released 23.03.2024 ...

So:
* I can't rule out, that some MariaDB update did this. as 11.4 was released on 16.02.2024, so perhaps I did an upgrade on March 1st.
* What I also can confirm, that I did not change some configuration in MariaDB that time. I only configured the database on creation, 2 years ago

So, if I'm the only one, we can close this issue.

**Comment by jlaur** [comment]
@binderth - have you used your db instance with any other tools/ORM's/frameworks that might have changed your schema?

**Comment by binderth** [comment]
@jlaur I'm using MySQL Workbench for this, but didn't change the schema, just read/write data in tables.

**Comment by binderth** [comment]
FWIW, if someone has a similar issue, I used Excel for a simple "ALTER TABLE"-creation for "item0001" until "itemxxxx":

```
ALTER TABLE `openHAB`.`item0001` CHANGE COLUMN `time` `time` TIMESTAMP(3) NOT NULL ;
ALTER TABLE `openHAB`.`item0002` CHANGE COLUMN `time` `time` TIMESTAMP(3) NOT NULL ;
ALTER TABLE `openHAB`.`item0003` CHANGE COLUMN `time` `time` TIMESTAMP(3) NOT NULL ;
...
```

just be sure to use the schema name (openHAB in my case).

**Comment by jlaur** [comment]
> FWIW, if someone has a similar issue, I used Excel for a simple "ALTER TABLE"-creation for "item0001" until "itemxxxx":

So console command [`jdbc schema check`](https://www.openhab.org/addons/persistence/jdbc/#check-fix-schema) didn't detect this issue?

**Comment by binderth** [comment]
> So console command [jdbc schema check](https://www.openhab.org/addons/persistence/jdbc/#check-fix-schema) didn't detect this issue?

at least no errors. mostly those:
```
item0594  EV6_lastupdate                                Column 'time' expected to be NOT NULL, but is nullable
item0594  EV6_lastupdate                                Column type 'TIMESTAMP(3)' expected, but is 'VARCHAR(16255)'
item0598  EV6_odometer                                  Column 'time' expected to be NOT NULL, but is nullable
item0595  EV6_sleepModeCheck                            Column 'time' expected to be NOT NULL, but is nullable
item1364  EV6_smartKeyBatteryWarning                    Column 'time' expected to be NOT NULL, but is nullable
item0596  EV6_systemCutOffAlert                         Column 'time' expected to be NOT NULL, but is nullable
item1368  EV6_tailLampStatus                            Column 'time' expected to be NOT NULL, but is nullable
item0609  EV6_temperature                               Column 'time' expected to be NOT NULL, but is nullable
item0911  EV6_trunkOpen                                 Column 'time' expected to be NOT NULL, but is nullable
item0590  EV6_vehicleLocation                           Column 'time' expected to be NOT NULL, but is nullable
item0696  EV6_vehicleStatus                             Column 'time' expected to be NOT NULL, but is nullable
item1367  EV6_windowOpen                                Column 'time' expected to be NOT NULL, but is nullable
item1550  FRZ_Call_Deflection_0                         Column 'time' expected to be NOT NULL, but is nullable
item1554  FRZ_Call_List_5                               Column 'time' expected to be NOT NULL, but is nullable
item1564  FRZ_Device_Log                                Column 'time' expected to be NOT NULL, but is nullable
item1564  FRZ_Device_Log                                Column type 'VARCHAR(16255)' expected, but is 'LONGTEXT'
item1553  FRZ_Inbound_Calls_5                           Column 'time' expected to be NOT NULL, but is nullable
```

the `Column 'time' expected to be NOT NULL, but is nullable` is present for every single item, also those created after 01.03.2024.

**Comment by jlaur** [comment]
> the `Column 'time' expected to be NOT NULL, but is nullable` is present for every single item, also those created after 01.03.2024.
> 
> I then `jdbc schema fix`ed my tables. But they still got the `CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)` as default. (and still, the "Column 'time' expected to be NOT NULL, but is nullable" info is still present, even after `jdbc schema fix`, even though `time timestamp(3) NOT NULL` is on every item)

I'll have a look at fixing these issues. Would you be willing to test a fix?

**Comment by jlaur** [comment]
I thought that maybe the schema information was cached and not refreshed after the repair, but actually it is. In MySQL this worked (after setting **value** column to `NOT NULL`):

```
openhab> jdbc schema check
Table                                       Item                                        Issue
------------------------------------------  ------------------------------------------  ----------------------------------------------------------------
TestSwitch                                  TestSwitch                                  Column 'value' expected to be nullable, but is NOT NULL
openhab> jdbc schema fix
Fixed table 'TestSwitch' for item 'TestSwitch'
openhab> jdbc schema check
Table                                       Item                                        Issue
------------------------------------------  ------------------------------------------  ----------------------------------------------------------------
```

Can you try to run this query (replacing openhab by your schema)?
```sql
SELECT column_name, column_type, is_nullable
FROM information_schema.columns
WHERE table_schema='openhab' AND table_name='EV6_lastupdate'
```

And also show how the table looks from MySQL Workbench?

**Comment by jlaur** [comment]
@binderth - I found the following documentation for MySQL:
https://dev.mysql.com/doc/refman/8.3/en/timestamp-initialization.html

I would assume the same or similar applies to MariaDB, and this could be the cause of your problem:
> [TIMESTAMP](https://dev.mysql.com/doc/refman/8.3/en/datetime.html) and [DATETIME](https://dev.mysql.com/doc/refman/8.3/en/datetime.html) columns have no automatic properties unless they are specified explicitly, with this exception: If the [explicit_defaults_for_timestamp](https://dev.mysql.com/doc/refman/8.3/en/server-system-variables.html#sysvar_explicit_defaults_for_timestamp) system variable is disabled, the first [TIMESTAMP](https://dev.mysql.com/doc/refman/8.3/en/datetime.html) column has both DEFAULT CURRENT_TIMESTAMP and ON UPDATE CURRENT_TIMESTAMP if neither is specified explicitly.

Perhaps the behavior changed in the 11.4 upgrade you mentioned. There is also this comparison table:
https://mariadb.com/kb/en/system-variable-differences-between-mariadb-10-4-and-mysql-8-0/

I have prepared an enhancement for dropping already existing default. I would also still like to figure out why `jdbc schema fix` is not working as expected for you.

**Comment by binderth** [comment]
I'll set up some tests on the weekend and come back after.

**Comment by binderth** [comment]
sorry @jlaur I was completely offline the last days due to illness.
What I did:

1. installed current MySQL
2. configured a test-openHAB to use that MySQL
3. changed the value my "NewTestItem" (String-item)
4. encountered a different error

```
2024-04-23 11:40:45.531 [DEBUG] [persistence.jdbc.internal.JdbcMapper] - JDBC::storeItemValue: item=NewTestItem (Type=StringItem, State=stringtest, Label=New Item, Category=) state=stringtest date=null
2024-04-23 11:40:45.533 [DEBUG] [persistence.jdbc.internal.JdbcMapper] - JDBC::getTable: no table found for item 'NewTestItem' in itemNameToTableNameMap
2024-04-23 11:40:45.534 [DEBUG] [persistence.jdbc.internal.JdbcMapper] - JDBC::createNewEntryInItemsTable
2024-04-23 11:40:45.534 [DEBUG] [istence.jdbc.internal.db.JdbcBaseDAO] - JDBC::doCreateNewEntryInItemsTable sql=INSERT INTO items (ItemName) VALUES ('NewTestItem')
2024-04-23 11:40:45.755 [DEBUG] [persistence.jdbc.internal.JdbcMapper] - JDBC::getTable: getTableName with rowId=1 itemName=NewTestItem
2024-04-23 11:40:45.756 [DEBUG] [persistence.jdbc.internal.dto.ItemVO] - JDBC:ItemVO tableName=item0001; newTableName=NewTestItem; 
2024-04-23 11:40:45.757 [DEBUG] [persistence.jdbc.internal.JdbcMapper] - JDBC::createItemTable
2024-04-23 11:40:45.757 [DEBUG] [istence.jdbc.internal.db.JdbcBaseDAO] - JDBC::doCreateItemTable sql=CREATE TABLE IF NOT EXISTS item0001 (time TIMESTAMP(3) NOT NULL, value VARCHAR(21717), PRIMARY KEY(time))
2024-04-23 11:40:45.778 [WARN ] [jdbc.internal.JdbcPersistenceService] - JDBC::store: Unable to store item
org.openhab.persistence.jdbc.internal.exceptions.JdbcSQLException: Error in SQL query!!!; Column length too big for column 'value' (max = 16383); use BLOB or TEXT instead Query: CREATE TABLE IF NOT EXISTS item0001 (time TIMESTAMP(3) NOT NULL, value VARCHAR(21717), PRIMARY KEY(time)) Parameters: []; Pool Name= yank-default; SQL= CREATE TABLE IF NOT EXISTS item0001 (time TIMESTAMP(3) NOT NULL, value VARCHAR(21717), PRIMARY KEY(time))
	at org.openhab.persistence.jdbc.internal.db.JdbcBaseDAO.doCreateItemTable(JdbcBaseDAO.java:414) ~[?:?]
	at org.openhab.persistence.jdbc.internal.JdbcMapper.createItemTable(JdbcMapper.java:202) ~[?:?]
	at org.openhab.persistence.jdbc.internal.JdbcMapper.getTable(JdbcMapper.java:392) ~[?:?]
	at org.openhab.persistence.jdbc.internal.JdbcMapper.storeItemValue(JdbcMapper.java:217) ~[?:?]
	at org.openhab.persistence.jdbc.internal.JdbcPersistenceService.internalStore(JdbcPersistenceService.java:174) ~[?:?]
	at org.openhab.persistence.jdbc.internal.JdbcPersistenceService.lambda$1(JdbcPersistenceService.java:146) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:840) [?:?]
```

**Comment by jlaur** [comment]
@binderth - I hope you are well.

Can you create a separate issue for that? Also please state your schema default character set in that issue. See:
https://github.com/openhab/openhab-addons/blob/6ebf0f974e204aacde9d62c1d37c6bf10c475e8f/bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/db/JdbcMysqlDAO.java#L58-L64

**Comment by binderth** [comment]
i also tried the same above, but instead of using current MariaDB with v11.2 (the one running on my production openHAB on October 2023) I don't get any errors, and also no Default Expression. 
So it really seems, there was something I did on whatever kind of at database level...

> Can you create a separate issue for that? Also please state your schema default character set in that issue. See:

i used utf8mb4 as standard (must check, but AFAIK utf8 points to utf8mb3 in current MySQL/MariaDB).

**Comment by binderth** [comment]
> I thought that maybe the schema information was cached and not refreshed after the repair, but actually it is. In MySQL this worked (after setting value column to NOT NULL):

So i did that:
![grafik](https://github.com/openhab/openhab-addons/assets/9037329/5bb274a7-9d31-4aaa-bc91-99205042fe29)

and the `schema fix` on that item:
```
openhab> jdbc schema fix EV6_lastupdate
Failed to fix table 'item0594' for item 'EV6_lastupdate': Error in SQL query!!!; (conn=4029) Incorrect datetime value: '"2022-10-28T07:30:17.000Z"' Query: ALTER TABLE item0594 MODIFY COLUMN value TIMESTAMP(3) Parameters: []; Pool Name= yank-default; SQL= ALTER TABLE item0594 MODIFY COLUMN value TIMESTAMP(3)
```

and indeed:
![grafik](https://github.com/openhab/openhab-addons/assets/9037329/252c2bcb-5b91-4abf-98ca-d8e0043abc84)
