### ISSUE TITLE
[jdbc] [mysql] Using current MySQL database as persistence leads to error in String Item-creation

### ISSUE THREAD

**Issue by binderth** [openhab/openhab-addons#16678]
## Expected Behavior
If using a MySQL database as persistence, Items should be created there and filled with the item's history

## Current Behavior
If using a MySQL database, there are no item-tables created for String Items.

## Possible Solution
change the maximum length of an item in the SQL-statements - or try to change the table configuration to TEXT

## Steps to Reproduce (for Bugs)
1. install current MySQL (8.3.0-1.el8 in my case)
2. configure a test-openHAB to use that MySQL (in TRACE-mode)
3. chang the value of a "NewTestItem" (String-item)
4. the following error appears in the openhab.log

```
2024-04-23 11:40:45.531 [DEBUG] [persistence.jdbc.internal.JdbcMapper] - JDBC::storeItemValue: item=NewTestItem (Type=StringItem, State=stringtest, Label=New Item, Category=) state=stringtest date=null
2024-04-23 11:40:45.533 [DEBUG] [persistence.jdbc.internal.JdbcMapper] - JDBC::getTable: no table found for item 'NewTestItem' in itemNameToTableNameMap
2024-04-23 11:40:45.534 [DEBUG] [persistence.jdbc.internal.JdbcMapper] - JDBC::createNewEntryInItemsTable
2024-04-23 11:40:45.534 [DEBUG] [istence.jdbc.internal.db.JdbcBaseDAO] - JDBC::doCreateNewEntryInItemsTable sql=INSERT INTO items (ItemName) VALUES ('NewTestItem')
2024-04-23 11:40:45.755 [DEBUG] [persistence.jdbc.internal.JdbcMapper] - JDBC::getTable: getTableName with rowId=1 itemName=NewTestItem
2024-04-23 11:40:45.756 [DEBUG] [persistence.jdbc.internal.dto.ItemVO] - JDBC:ItemVO tableName=item0001; newTableName=NewTestItem; 
2024-04-23 11:40:45.757 [DEBUG] [persistence.jdbc.internal.JdbcMapper] - JDBC::createItemTable
2024-04-23 11:40:45.757 [DEBUG] [istence.jdbc.internal.db.JdbcBaseDAO] - JDBC::doCreateItemTable sql=CREATE TABLE IF NOT EXISTS item0001 (time TIMESTAMP(3) NOT NULL, value VARCHAR(21717), PRIMARY KEY(time))
2024-04-23 11:40:45.778 [WARN ] [jdbc.internal.JdbcPersistenceService] - JDBC::store: Unable to store item
org.openhab.persistence.jdbc.internal.exceptions.JdbcSQLException: Error in SQL query!!!; Column length too big for column 'value' (max = 16383); use BLOB or TEXT instead Query: CREATE TABLE IF NOT EXISTS item0001 (time TIMESTAMP(3) NOT NULL, value VARCHAR(21717), PRIMARY KEY(time)) Parameters: []; Pool Name= yank-default; SQL= CREATE TABLE IF NOT EXISTS item0001 (time TIMESTAMP(3) NOT NULL, value VARCHAR(21717), PRIMARY KEY(time))
	at org.openhab.persistence.jdbc.internal.db.JdbcBaseDAO.doCreateItemTable(JdbcBaseDAO.java:414) ~[?:?]
	at org.openhab.persistence.jdbc.internal.JdbcMapper.createItemTable(JdbcMapper.java:202) ~[?:?]
	at org.openhab.persistence.jdbc.internal.JdbcMapper.getTable(JdbcMapper.java:392) ~[?:?]
	at org.openhab.persistence.jdbc.internal.JdbcMapper.storeItemValue(JdbcMapper.java:217) ~[?:?]
	at org.openhab.persistence.jdbc.internal.JdbcPersistenceService.internalStore(JdbcPersistenceService.java:174) ~[?:?]
	at org.openhab.persistence.jdbc.internal.JdbcPersistenceService.lambda$1(JdbcPersistenceService.java:146) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:840) [?:?]
```

## Context
* after changing the CREATE statement to use only 16000 as VARCHAR-length, the item0001 was created and was then filled by openHAB while changing the value of it.
* using current MariaDB as persistence, the VARCHAR item gets created with 16255.

## Your Environment
* Version used: openHAB 4.1.2-release (docker) and MySQL 8.3.0 (docker)
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...): not applicable
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): docker

**Comment by jlaur** [comment]
Related type defined here:
https://github.com/openhab/openhab-addons/blob/6ebf0f974e204aacde9d62c1d37c6bf10c475e8f/bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/db/JdbcMysqlDAO.java#L58-L64

And character set used in relation to this issue is **utf8mb4** (see https://github.com/openhab/openhab-addons/issues/16635#issuecomment-2071948729)

For that character set, `VARCHAR` is limited to 16383 - see https://dev.mysql.com/doc/refman/8.3/en/storage-requirements.html:
> The effective maximum number of bytes that can be stored in a [VARCHAR](https://dev.mysql.com/doc/refman/8.3/en/char.html) or [VARBINARY](https://dev.mysql.com/doc/refman/8.3/en/binary-varbinary.html) column is subject to the maximum row size of 65,535 bytes, which is shared among all columns. For a [VARCHAR](https://dev.mysql.com/doc/refman/8.3/en/char.html) column that stores multibyte characters, the effective maximum number of characters is less. For example, utf8mb4 characters can require up to four bytes per character, so a [VARCHAR](https://dev.mysql.com/doc/refman/8.3/en/char.html) column that uses the utf8mb4 character set can be declared to be a maximum of 16,383 characters. See [Section 10.4.7, “Limits on Table Column Count and Row Size”](https://dev.mysql.com/doc/refman/8.3/en/column-count-limit.html).

**Comment by jlaur** [comment]
See also #13920.

**Comment by jlaur** [comment]
@binderth - as a work-around you can configure the size here:
![image](https://github.com/openhab/openhab-addons/assets/19519842/7b6f5fd7-699d-43bc-a84d-c9dfdf42c71e)

Or in `services/jdbc.config`:
```ini
sqltype.STRING        =   VARCHAR(16255)
```

I have provided a PR for fixing the default size for MySQL.
