### ISSUE TITLE
[freeboxos] NPE in APManager

### ISSUE THREAD

**Issue by clinique** [openhab/openhab-addons#16697]
This error is generated from time to time : 
```
2024-04-28 21:00:38.078 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception: 
java.lang.NullPointerException: Cannot invoke "org.openhab.binding.freeboxos.internal.api.rest.APManager$WifiInformation.signal()" because "this.wifiInformation" is null
	at org.openhab.binding.freeboxos.internal.api.rest.APManager$LanAccessPoint.getSignal(APManager.java:52) ~[?:?]
	at org.openhab.binding.freeboxos.internal.handler.WifiStationHandler.internalPoll(WifiStationHandler.java:76) ~[?:?]
	at org.openhab.binding.freeboxos.internal.handler.ApiConsumerHandler.lambda$2(ApiConsumerHandler.java:219) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:842) [?:?]
```

**Comment by lolodomo** [comment]
Closed by #16700
