### ISSUE TITLE
[samsungtv] Exception thrown when changing input source on legacy TV

### ISSUE THREAD

**Issue by jlaur** [openhab/openhab-addons#16783]
Logs when attempting to change input source on a Samsung UE55D8005/XXE (`SamsungTV_SourceName` is linked to channel `sourceName`):

```
2024-05-21 22:03:54.450 [INFO ] [openhab.event.ItemCommandEvent      ] - Item 'SamsungTV_SourceName' received command HDMI1/DVI
2024-05-21 22:03:54.451 [INFO ] [penhab.event.ItemStatePredictedEvent] - Item 'SamsungTV_SourceName' predicted to become HDMI1/DVI
2024-05-21 22:03:54.452 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'SamsungTV_SourceName' changed from HDMI-CEC to HDMI1/DVI
2024-05-21 22:03:54.454 [DEBUG] [tv.internal.handler.SamsungTvHandler] - 192.168.0.41: Received channel: samsungtv:tv:office:sourceName, command: HDMI1/DVI
2024-05-21 22:03:54.454 [TRACE] [tv.internal.handler.SamsungTvHandler] - 192.168.0.41: Received: sourceName, command: HDMI1/DVI
2024-05-21 22:03:54.455 [TRACE] [rnal.service.RemoteControllerService] - 192.168.0.41: getSupportedChannelNames: [keyCode, power, channel]
2024-05-21 22:03:54.455 [TRACE] [internal.service.MainTVServerService] - 192.168.0.41: getSupportedChannelNames: [sourceName, sourceId, url, stopBrowser]
2024-05-21 22:03:54.455 [TRACE] [internal.service.MainTVServerService] - 192.168.0.41: Received channel: sourceName, command: HDMI1/DVI
2024-05-21 22:03:54.496 [TRACE] [internal.service.MainTVServerService] - 192.168.0.41: Received channel: channel, command: REFRESH
2024-05-21 22:03:54.514 [ERROR] [nal.common.AbstractInvocationHandler] - An error occurred while calling method 'ThingHandler.handleCommand()' on 'org.openhab.binding.samsungtv.internal.handler.SamsungTvHandler@bc65b9a': Duplicate key HDMI-CEC (attempted merging values 0 and 1)
java.lang.IllegalStateException: Duplicate key HDMI-CEC (attempted merging values 0 and 1)
	at java.util.stream.Collectors.duplicateKeyException(Collectors.java:135) ~[?:?]
	at java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:182) ~[?:?]
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.stream.IntPipeline$1$1.accept(IntPipeline.java:180) ~[?:?]
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104) ~[?:?]
	at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:711) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at org.openhab.binding.samsungtv.internal.service.MainTVServerService.lambda$13(MainTVServerService.java:347) ~[?:?]
	at java.util.Optional.map(Optional.java:260) ~[?:?]
	at org.openhab.binding.samsungtv.internal.service.MainTVServerService.getSourceMap(MainTVServerService.java:346) ~[?:?]
	at org.openhab.binding.samsungtv.internal.service.MainTVServerService.setSourceName(MainTVServerService.java:306) ~[?:?]
	at org.openhab.binding.samsungtv.internal.service.MainTVServerService.handleCommand(MainTVServerService.java:173) ~[?:?]
	at org.openhab.binding.samsungtv.internal.handler.SamsungTvHandler.handleCommand(SamsungTvHandler.java:373) ~[?:?]
	at org.openhab.binding.samsungtv.internal.handler.SamsungTvHandler.handleCommand(SamsungTvHandler.java:363) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor800.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.openhab.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:147) [bundleFile:?]
	at org.openhab.core.internal.common.InvocationHandlerSync.invoke(InvocationHandlerSync.java:59) [bundleFile:?]
	at jdk.proxy187004.$Proxy187159.handleCommand(Unknown Source) [?:?]
	at org.openhab.core.thing.internal.profiles.ProfileCallbackImpl.handleCommand(ProfileCallbackImpl.java:95) [bundleFile:?]
	at org.openhab.core.thing.internal.profiles.SystemDefaultProfile.onCommandFromItem(SystemDefaultProfile.java:49) [bundleFile:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.openhab.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:147) [bundleFile:?]
	at org.openhab.core.internal.common.Invocation.call(Invocation.java:52) [bundleFile:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:840) [?:?]
```

## Expected Behavior
Input source should be changed according to command.

## Current Behavior
Exception is thrown.

## Steps to Reproduce
I have tried a few times where it worked, so the current state seems to have some impact, or it might be timing-related. However, it was not very hard to reproduce, at least not right after turning on the TV.

## Context
I'm testing the new version of the binding. I have backported to changes to 4.1.x and testing on my production system.

## Your Environment
* Version used: 4.2 as of today (compiled the binding myself after #11895 was merged)

**Comment by jlaur** [comment]
@NickWaterton - FYI, it seems I'm experiencing a regression here when trying to switch source on a legacy TV.

**Comment by NickWaterton** [comment]
It looks like you may have two inputs on the TV both called HDMI-CEC. Can you list the inputs on your TV (on the screen), take a picture and post it here?

The binding queries the source list, and ID's and fills a variable `Map<String, String>` - and it looks like you have a duplicate source name. This is the same as the old binding though, so not sure what is different.

Thanks,

**Comment by jlaur** [comment]
> It looks like you may have two inputs on the TV both called HDMI-CEC. Can you list the inputs on your TV (on the screen), take a picture and post it here?

Yes, indeed, you are right:

![image](https://github.com/openhab/openhab-addons/assets/19519842/be3abc63-a6c2-4f56-b830-a0f62720f333)

**Comment by NickWaterton** [comment]
Fortunately I have one of these legacy TV's as well, with one HDMI-CEC device. I will have to think about how to deal with this situation.

**Comment by NickWaterton** [comment]
Ok,

I found the issue. In the original binding, the duplicate key simply overwrote the first key. In the new version I am using a stream to generate the Map, which throws the "duplicate key" exception.

Fortunately the toMap() function has a method for dealing with duplicate keys (which I had not implemented), so it's an easy fix.

**Comment by NickWaterton** [comment]
@jlaur 

Can you try this [jar](https://github.com/NickWaterton/openhab-addons/releases/download/V2.0/org.openhab.binding.samsungtv-4.2.0-SNAPSHOT.jar) if it fixes the issue, I'll issue a PR.

Thanks.

**Comment by jlaur** [comment]
> Can you try this [jar](https://github.com/NickWaterton/openhab-addons/releases/download/V2.0/org.openhab.binding.samsungtv-4.2.0-SNAPSHOT.jar) if it fixes the issue, I'll issue a PR.

Sure, thanks! Perhaps you can already create the PR and add label "additional testing preferred"? I can then backport the fix and test it on my production system in the evening - and perform a review as well?
