### ISSUE TITLE
[kostalinverter] Exception

### ISSUE THREAD

**Issue by martin-hu** [openhab/openhab-addons#16899]
## Current Behavior

I upgraded from openhab 3.2 to 4.1.3. after the upgrade the kostalinverter binding does not work anymore.

after starting/initializing the kostalinverter binding i get the following exception: 

```
2024-06-21 16:05:45.875 [INFO ] [el.core.internal.ModelRepositoryImpl] - Loading model 'kostal.things'
...
2024-06-21 16:05:56.107 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception:
java.lang.NoSuchMethodError: 'void org.openhab.core.library.types.DecimalType.<init>(long)'
        at org.openhab.binding.kostalinverter.internal.thirdgeneration.ThirdGenerationHandler.updateChannelValue(ThirdGenerationHandler.java:223) ~[?:?]
        at org.openhab.binding.kostalinverter.internal.thirdgeneration.ThirdGenerationHandler.updateChannelValues(ThirdGenerationHandler.java:206) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:840) [?:?]
```

## Steps to Reproduce (for Bugs)

1. use openhab 4.1.3 with kostalinverter binding

Minimal configuration:

things/kostal.things: 
`Thing kostalinverter:PLENTICOREPLUS100WITHBATTERY:PlentiCore01 [ url = "<ip address of the inverter>", userPassword="<secret>", refreshInternalInSeconds="30"]`

items/kostal.items:
`Number:Energy                PlentiCore01_DEVICE_LOCAL_DC_POWER                         "DC - Leistung" <energy> { channel="kostalinverter:PLENTICOREPLUS100WITHBATTERY:PlentiCore01:deviceLocalDCPower"}
`

## Context

No measurements from my inverter are updated

## Your Environment

  * Version used: openHAB 4.1.3 (docker openhab/openhab:4.1.3-debian on arm64)
* Operating System and version: Raspbian Buster
* PLENTICORE plus 10 (v1)
* UI-Version: 01.30.12092

**Comment by martin-hu** [comment]
I was stupid and hat an old version of the kostalinverter binding laying around. I will close the issue.
