### ISSUE TITLE
[govee] discovery fails

### ISSUE THREAD

**Issue by JacekKac** [openhab/openhab-addons#17101]
Version:     4.2.0 (Build)

```
2024-07-19 09:46:03.958 [DEBUG] [govee.internal.GoveeDiscoveryService] - starting Scan
2024-07-19 09:46:03.963 [DEBUG] [govee.internal.GoveeDiscoveryService] - Discovering Govee devices on name:eth0 (eth0) ...
2024-07-19 09:46:03.966 [WARN ] [.govee.internal.CommunicationManager] - exception when receiving status packet
java.net.SocketException: Socket closed
        at sun.nio.ch.DatagramSocketAdaptor.receive(DatagramSocketAdaptor.java:252) ~[?:?]
        at java.net.DatagramSocket.receive(DatagramSocket.java:710) ~[?:?]
        at org.openhab.binding.govee.internal.CommunicationManager$StatusReceiver.run(CommunicationManager.java:202) [bundleFile:?]
Caused by: java.nio.channels.AsynchronousCloseException
        at sun.nio.ch.DatagramChannelImpl.endRead(DatagramChannelImpl.java:523) ~[?:?]
        at sun.nio.ch.DatagramChannelImpl.trustedBlockingReceive(DatagramChannelImpl.java:677) ~[?:?]
        at sun.nio.ch.DatagramChannelImpl.blockingReceive(DatagramChannelImpl.java:635) ~[?:?]
        at sun.nio.ch.DatagramSocketAdaptor.receive(DatagramSocketAdaptor.java:240) ~[?:?]
        ... 2 more
2024-07-19 09:46:03.969 [DEBUG] [govee.internal.GoveeDiscoveryService] - Discovery with IO exception: Invalid argument
```

**Comment by lsiepel** [comment]
If you put the binding logging in trace it might show the actual packet

**Comment by JacekKac** [comment]
it's already in trace log level. i have also another problem with this binding.. 
the switch in the govee app "Lan ON " is turning off randomly, the device is connected to a wifi, but i can not enter the wifi settings in the app. Anyone experienced the same issue?

i can't find the device in LAN via arp / mac address - but it seems to be connected to a wifi because i can controle it via app. It's remote location so i am not able to check everythink localy

**Comment by lsiepel** [comment]
You can reproduce this issue?
Since the inital contribution, this logic has not changed in the binding. The `socket` does not seem to have a Threads safe implementation, so it might happen that another thread (regular update) interferes with the discovery thread. 

@stefan-hoehn would you be able to comment on this?

**Comment by stefan-hoehn** [comment]
I finally experienced it on an installation in front of me. However, it is completely unclear even after a four eyes review why the socket would be closed. I will provide a patch that at least should make it more resilient.

**Comment by stefan-hoehn** [comment]
As an additional information: as I mentioned we noticed the issue this morning and the device wasn't detected, but (!) it had nothing to do with this issue with the socket. The reason why it wasn't detected was that (even) I had forgotten to set the WIFI mode for that device. I set it, it immediately got detected even though I saw the socket problem again in the logs.
