### ISSUE TITLE
[deconz] Fails tests. Breaks CI build

### ISSUE THREAD

**Issue by andrewfg** [openhab/openhab-addons#17104]
The deconz binding is failing tests during the CI build process, thus killing the whole addons build process.

**Comment by J-N-K** [comment]
Please link a failed build.

**Comment by andrewfg** [comment]
^
https://github.com/openhab/openhab-addons/actions/runs/10006865459/job/27660397782?pr=17099

**Comment by andrewfg** [comment]
I wonder if the Junit tests in #17099 are somehow affecting the state of the (following) Junit tests in deconz? It is hard to imagine why or how that could be..

**Comment by J-N-K** [comment]
I don't think this is an issue with the deconz tests, because they succeed in Jenkins. It's more likely an issue with the GitHub build configuration. I also don't see which test fails, because the log doesn't contain that information.

**Comment by andrewfg** [comment]
It also fails on a local Maven build. Tomorrow I  will run that again, and post the log.

**Comment by andrewfg** [comment]
@J-N-K below is the log from a local Maven build attempt..

```
[INFO] Running org.openhab.binding.deconz.internal.handler.SensorThermostatThingHandlerTest
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.415 s -- in org.openhab.binding.deconz.internal.handler.SensorThermostatThingHandlerTest
[INFO] Running org.openhab.binding.deconz.internal.handler.SensorThingHandlerTest
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.086 s -- in org.openhab.binding.deconz.internal.handler.SensorThingHandlerTest
[INFO] Running org.openhab.binding.deconz.LightGroupTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.039 s -- in org.openhab.binding.deconz.LightGroupTest
[INFO] Running org.openhab.binding.deconz.LightsTest
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.063 s -- in org.openhab.binding.deconz.LightsTest
[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   DeconzTest.discoveryTest:99
discoveryListener.thingDiscovered(
    <any>,
    <any>
);
Wanted 20 times:
-> at org.openhab.binding.deconz.DeconzTest.discoveryTest(DeconzTest.java:99)
But was 40 times:
-> at org.openhab.core.config.discovery.AbstractDiscoveryService.thingDiscovered(AbstractDiscoveryService.java:256)
-> at org.openhab.core.config.discovery.AbstractDiscoveryService.thingDiscovered(AbstractDiscoveryService.java:256)
-> at org.openhab.core.config.discovery.AbstractDiscoveryService.thingDiscovered(AbstractDiscoveryService.java:256)
-> at org.openhab.core.config.discovery.AbstractDiscoveryService.thingDiscovered(AbstractDiscoveryService.java:256)
-> at org.openhab.core.config.discovery.AbstractDiscoveryService.thingDiscovered(AbstractDiscoveryService.java:256)
-> at org.openhab.core.config.discovery.AbstractDiscoveryService.thingDiscovered(AbstractDiscoveryService.java:256)
-> at org.openhab.core.config.discovery.AbstractDiscoveryService.thingDiscovered(AbstractDiscoveryService.java:256)
-> at org.openhab.core.config.discovery.AbstractDiscoveryService.thingDiscovered(AbstractDiscoveryService.java:256)
-> at org.openhab.core.config.discovery.AbstractDiscoveryService.thingDiscovered(AbstractDiscoveryService.java:256)
-> at org.openhab.core.config.discovery.AbstractDiscoveryService.thingDiscovered(AbstractDiscoveryService.java:256)
-> at org.openhab.core.config.discovery.AbstractDiscoveryService.thingDiscovered(AbstractDiscoveryService.java:256)
-> at org.openhab.core.config.discovery.AbstractDiscoveryService.thingDiscovered(AbstractDiscoveryService.java:256)
-> at org.openhab.core.config.discovery.AbstractDiscoveryService.thingDiscovered(AbstractDiscoveryService.java:256)
-> at org.openhab.core.config.discovery.AbstractDiscoveryService.thingDiscovered(AbstractDiscoveryService.java:256)
-> at org.openhab.core.config.discovery.AbstractDiscoveryService.thingDiscovered(AbstractDiscoveryService.java:256)
-> at org.openhab.core.config.discovery.AbstractDiscoveryService.thingDiscovered(AbstractDiscoveryService.java:256)
-> at org.openhab.core.config.discovery.AbstractDiscoveryService.thingDiscovered(AbstractDiscoveryService.java:256)
-> at org.openhab.core.config.discovery.AbstractDiscoveryService.thingDiscovered(AbstractDiscoveryService.java:256)
-> at org.openhab.core.config.discovery.AbstractDiscoveryService.thingDiscovered(AbstractDiscoveryService.java:256)
-> at org.openhab.core.config.discovery.AbstractDiscoveryService.thingDiscovered(AbstractDiscoveryService.java:256)
-> at org.openhab.core.config.discovery.AbstractDiscoveryService.thingDiscovered(AbstractDiscoveryService.java:256)
-> at org.openhab.core.config.discovery.AbstractDiscoveryService.thingDiscovered(AbstractDiscoveryService.java:256)
-> at org.openhab.core.config.discovery.AbstractDiscoveryService.thingDiscovered(AbstractDiscoveryService.java:256)
-> at org.openhab.core.config.discovery.AbstractDiscoveryService.thingDiscovered(AbstractDiscoveryService.java:256)
-> at org.openhab.core.config.discovery.AbstractDiscoveryService.thingDiscovered(AbstractDiscoveryService.java:256)
-> at org.openhab.core.config.discovery.AbstractDiscoveryService.thingDiscovered(AbstractDiscoveryService.java:256)
-> at org.openhab.core.config.discovery.AbstractDiscoveryService.thingDiscovered(AbstractDiscoveryService.java:256)
-> at org.openhab.core.config.discovery.AbstractDiscoveryService.thingDiscovered(AbstractDiscoveryService.java:256)
-> at org.openhab.core.config.discovery.AbstractDiscoveryService.thingDiscovered(AbstractDiscoveryService.java:256)
-> at org.openhab.core.config.discovery.AbstractDiscoveryService.thingDiscovered(AbstractDiscoveryService.java:256)
-> at org.openhab.core.config.discovery.AbstractDiscoveryService.thingDiscovered(AbstractDiscoveryService.java:256)
-> at org.openhab.core.config.discovery.AbstractDiscoveryService.thingDiscovered(AbstractDiscoveryService.java:256)
-> at org.openhab.core.config.discovery.AbstractDiscoveryService.thingDiscovered(AbstractDiscoveryService.java:256)
-> at org.openhab.core.config.discovery.AbstractDiscoveryService.thingDiscovered(AbstractDiscoveryService.java:256)
-> at org.openhab.core.config.discovery.AbstractDiscoveryService.thingDiscovered(AbstractDiscoveryService.java:256)
-> at org.openhab.core.config.discovery.AbstractDiscoveryService.thingDiscovered(AbstractDiscoveryService.java:256)
-> at org.openhab.core.config.discovery.AbstractDiscoveryService.thingDiscovered(AbstractDiscoveryService.java:256)
-> at org.openhab.core.config.discovery.AbstractDiscoveryService.thingDiscovered(AbstractDiscoveryService.java:256)
-> at org.openhab.core.config.discovery.AbstractDiscoveryService.thingDiscovered(AbstractDiscoveryService.java:256)
-> at org.openhab.core.config.discovery.AbstractDiscoveryService.thingDiscovered(AbstractDiscoveryService.java:256)


[INFO]
[ERROR] Tests run: 18, Failures: 1, Errors: 0, Skipped: 0
```

**Comment by J-N-K** [comment]
It's probably a result of https://github.com/openhab/openhab-core/pull/4323

**Comment by andrewfg** [comment]
^ probably a result of https://github.com/openhab/openhab-core/pull/4323

@lolodomo ping!
