### ISSUE TITLE
[lutron] pico remote button mapping is broken in 4.2.0

### ISSUE THREAD

**Issue by androdev88** [openhab/openhab-addons#17111]
## Expected Behavior
Buttons should be mapped correctly, no exception should be thrown when using `buttonlower`.

## Current Behavior
1. pressing `button3` triggers `buttonlower`
2. pressing `buttonlower` throws exception:
```
2024-07-21 00:30:37.998 [WARN ] [ron.internal.handler.IPBridgeHandler] - Runtime exception while processing update: ~DEVICE,53,6,4
java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "java.util.Map.get(Object)" is null
	at org.openhab.binding.lutron.internal.handler.BaseKeypadHandler.handleUpdate(BaseKeypadHandler.java:367) ~[bundleFile:?]
	at org.openhab.binding.lutron.internal.handler.IPBridgeHandler.parseUpdates(IPBridgeHandler.java:406) [bundleFile:?]
	at org.openhab.binding.lutron.internal.handler.IPBridgeHandler$1.inputAvailable(IPBridgeHandler.java:120) [bundleFile:?]
	at org.openhab.binding.lutron.internal.net.TelnetSession.notifyInputAvailable(TelnetSession.java:89) [bundleFile:?]
	at org.openhab.binding.lutron.internal.net.TelnetSession.readInput(TelnetSession.java:170) [bundleFile:?]
	at org.openhab.binding.lutron.internal.net.TelnetSession$1.telnetInputAvailable(TelnetSession.java:71) [bundleFile:?]
	at org.apache.commons.net.telnet.TelnetClient.notifyInputListener(TelnetClient.java:238) [bundleFile:3.9.0]
	at org.apache.commons.net.telnet.TelnetInputStream.run(TelnetInputStream.java:531) [bundleFile:3.9.0]
	at java.lang.Thread.run(Thread.java:840) [?:?]
```

## Steps to Reproduce (for Bugs)

1. Add `casetahubpro` thing `Thing pico LivingRoomLEDPico @ "Living Room LED Pico" [ integrationId=53, model="3BRL", autorelease=false ]` 
2. Map to items: 
```
Switch Living_Room_LED_Pico_0 "Living Room LED Pico 1" { channel="lutron:pico:casetahubpro:LivingRoomLEDPico:button1" }
Switch Living_Room_LED_Pico_1 "Living Room LED Pico 2" { channel="lutron:pico:casetahubpro:LivingRoomLEDPico:button2" }
Switch Living_Room_LED_Pico_2 "Living Room LED Pico 3" { channel="lutron:pico:casetahubpro:LivingRoomLEDPico:button3" }
Switch Living_Room_LED_Pico_Raise "Living Room LED Pico Raise" { channel="lutron:pico:casetahubpro:LivingRoomLEDPico:buttonraise" }
Switch Living_Room_LED_Pico_Lower "Living Room LED Pico Lower" { channel="lutron:pico:casetahubpro:LivingRoomLEDPico:buttonlower" }
```
4. Press buttons

## Context
The bug was introduced in 4.2.0 (most likely https://github.com/openhab/openhab-addons/pull/16550), reverting to 4.1.1 fixes the problem.

## Your Environment

* Version used: 4.2.0
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): openhabian

**Comment by lsiepel** [comment]
The linked PR is probably the cause, to be more specific the key is not found in the map or the value is null in this Map: https://github.com/openhab/openhab-addons/blob/49a43a43c1d71f03454a15bff79f48026b2ed5d7/bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/BaseKeypadHandler.java#L366-L368

@ccutrer as i'm not familiair with this binding and you created the PR, can you come up with a fix?

**Comment by ccutrer** [comment]
@androdev88 : can you please post your your configuration for your bridge? I have a Caseta Smart Hub (nonpro), and use a `leapbridge` type thing as my bridge. I'm hoping it's just that the mapping for LEAP is incorrectly being apply for you, and you're using non-LEAP.

**Comment by ccutrer** [comment]
Assuming you're not using a `leapbridge`, can you try this JAR (hopeful fix is https://github.com/ccutrer/openhab-addons/commit/668c4c23b8c5e69cfbc7d34dac70d4e173e0fffd):

[org.openhab.binding.lutron-4.3.0-SNAPSHOT.jar.zip](https://github.com/user-attachments/files/16383734/org.openhab.binding.lutron-4.3.0-SNAPSHOT.jar.zip)

**Comment by ccutrer** [comment]
Ping @androdev88: can you test this please? It's probably something we'll want to get into 4.2.1

**Comment by androdev88** [comment]
provided jar file: `4.3.0.202407252103` fixes the problem, all buttons on 3BRL are mapped correctly
