### ISSUE TITLE
[freeboxos] IAE when sending remote keycode to player

### ISSUE THREAD

**Issue by clinique** [openhab/openhab-addons#17216]
Sending a key code to the Devialet generates this IAE:

```
2024-08-08 11:04:54.258 [ERROR] [nal.common.AbstractInvocationHandler] - An error occurred while calling method 'ThingHandler.handleCommand()' on 'org.openhab.binding.freeboxos.internal.handler.ActivePlayerHandler@7659e275': Null result deserializing '', please file a bug report.
java.lang.IllegalArgumentException: Null result deserializing '', please file a bug report.
	at org.openhab.binding.freeboxos.internal.api.ApiHandler.deserialize(ApiHandler.java:140) ~[?:?]
	at org.openhab.binding.freeboxos.internal.api.ApiHandler.executeUri(ApiHandler.java:116) ~[?:?]
	at org.openhab.binding.freeboxos.internal.api.rest.FreeboxOsSession.execute(FreeboxOsSession.java:125) ~[?:?]
	at org.openhab.binding.freeboxos.internal.api.rest.FreeboxOsSession.execute(FreeboxOsSession.java:149) ~[?:?]
	at org.openhab.binding.freeboxos.internal.api.rest.PlayerManager.sendKey(PlayerManager.java:248) ~[?:?]
	at org.openhab.binding.freeboxos.internal.handler.PlayerHandler.sendKey(PlayerHandler.java:93) ~[?:?]
	at org.openhab.binding.freeboxos.internal.handler.PlayerHandler.internalHandleCommand(PlayerHandler.java:71) ~[?:?]
	at org.openhab.binding.freeboxos.internal.handler.ApiConsumerHandler.handleCommand(ApiConsumerHandler.java:153) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor258.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:569) ~[?:?]
	at org.openhab.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:147) [bundleFile:?]
	at org.openhab.core.internal.common.InvocationHandlerSync.invoke(InvocationHandlerSync.java:59) [bundleFile:?]
	at jdk.proxy4992.$Proxy5151.handleCommand(Unknown Source) [?:?]
	at org.openhab.core.thing.internal.profiles.ProfileCallbackImpl.handleCommand(ProfileCallbackImpl.java:95) [bundleFile:?]
	at org.openhab.core.thing.internal.profiles.SystemDefaultProfile.onCommandFromItem(SystemDefaultProfile.java:49) [bundleFile:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:569) ~[?:?]
	at org.openhab.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:147) [bundleFile:?]
	at org.openhab.core.internal.common.Invocation.call(Invocation.java:52) [bundleFile:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:840) [?:?]
```

**Comment by lolodomo** [comment]
I have not yet tested this feature with the Revolution player but it was one of my next steps. I will tell you if I encounter the same issue.

PS: I was asking myself if this feature is supposed to work also with the mini 4k?

**Comment by clinique** [comment]
> I have not yet tested this feature with the Revolution player but it was one of my next steps. I will tell you if I encounter the same issue.
> 
> PS: I was asking myself if this feature is supposed to work also with the mini 4k player?

You will face the same issue for sure (see PR).
I don't know if this works with the mini 4k player.

**Comment by lolodomo** [comment]
@clinique : FYU, works well with the revolution player. Not all codes are supported but I guess that few of them are specific to a new model.
Regarding the mini 4k player, I can't find any trace of a remote code in the UI, so it is probably not supported.

I was asking myself if this feature should be on player or active-player thing type.
At your knowledge, what are the player models that are active or not ? I can tell you:
- revolution player => active-player and supports remote codes
- mini 4k player => player and apparently do not support remote codes

**Comment by clinique** [comment]
active-player should be those that handle API requests via FreeboxOs. I agree with your above proposal.

**Comment by lolodomo** [comment]
Do you know what player models support these remote codes ?

**Comment by clinique** [comment]
Apart from Devialet and Revolution player, no. And I guess these will be the last as IIUW Free will stop providing home made players.

**Comment by lolodomo** [comment]
Yes, that is more than probable. Pop player is also a Google TV box I believe.
So no problem for the Devialet player if we move this feature to the active-player thing type ?

**Comment by clinique** [comment]
It makes sense. Maybe older player, before revolution did accept these remote codes but I guess there are not that much around as of today.

**Comment by lolodomo** [comment]
If you mean the freebox v5, I don't think it is used by anyone. Free made sure to replace all these models by a new model, maybe 10 years ago. I believe the oldest models that any user can have today is the Revolution.
