### ISSUE TITLE
[mqtt.homeassistant] `availability` doesn't have to be a list

### ISSUE THREAD

**Issue by adielsa** [openhab/openhab-addons#17375]
There is amazing nuki_hub over esp32 that send mqtt 
i tried to connet it to OpenHAb. Its even send homeassisnt mqtt message but its doesnt get register.

Which config topic should i use?

I see that MQTT got connected from nuki_hub to openhab

OpenHab side: 
![image](https://github.com/user-attachments/assets/ebdac194-97cd-4bce-94c6-1e2c24816c6c)
![image](https://github.com/user-attachments/assets/29573702-4b96-42da-bf0b-f2498b59d47e)

NukiHub ESP:
![image](https://github.com/user-attachments/assets/e7abace7-3a45-4776-85d9-cda7aed3573e)
![image](https://github.com/user-attachments/assets/94578b57-6e60-4a32-9484-b34bb3f06bd8)

**Comment by adielsa** [comment]
I fixed missing config of topic. And i see now the following topic+message on the broker but they are not been consume by the add-on
![image](https://github.com/user-attachments/assets/ad623631-63b0-4389-a929-427c3bc5587e)

**Comment by adielsa** [comment]
using openhab-cli showlogs i manage to discover:

```
openhabian@openhabian:~ $ openhab-cli showlogs

==> /var/log/openhab/events.log <==
2024-09-06 10:39:11.325 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'mqtt:homeassistant:c4b5e522c7:c6ebc32482' changed from UNINITIALIZED (DISABLED) to INITIALIZING
2024-09-06 10:39:11.424 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'mqtt:homeassistant:c4b5e522c7:c6ebc32482' changed from INITIALIZING to UNKNOWN
2024-09-06 10:39:32.424 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'mqtt:homeassistant:c4b5e522c7:c6ebc32482' changed from UNKNOWN to UNINITIALIZED
2024-09-06 10:39:32.595 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'mqtt:homeassistant:c4b5e522c7:c6ebc32482' changed from UNINITIALIZED to UNINITIALIZED (DISABLED)
2024-09-06 10:39:33.611 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'mqtt:homeassistant:c4b5e522c7:c6ebc32482' changed from UNINITIALIZED (DISABLED) to INITIALIZING
2024-09-06 10:39:33.728 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'mqtt:homeassistant:c4b5e522c7:c6ebc32482' changed from INITIALIZING to UNKNOWN
2024-09-06 10:40:28.825 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'mqtt:homeassistant:c4b5e522c7:c6ebc32482' changed from UNKNOWN to UNINITIALIZED
2024-09-06 10:40:28.978 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'mqtt:homeassistant:c4b5e522c7:c6ebc32482' changed from UNINITIALIZED to UNINITIALIZED (DISABLED)
2024-09-06 10:40:30.369 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'mqtt:homeassistant:c4b5e522c7:c6ebc32482' changed from UNINITIALIZED (DISABLED) to INITIALIZING
2024-09-06 10:40:30.471 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'mqtt:homeassistant:c4b5e522c7:c6ebc32482' changed from INITIALIZING to UNKNOWN

==> /var/log/openhab/openhab.log <==
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173) [bundleFile:9.4.54.v20240208]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131) [bundleFile:9.4.54.v20240208]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409) [bundleFile:9.4.54.v20240208]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883) [bundleFile:9.4.54.v20240208]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034) [bundleFile:9.4.54.v20240208]
	at java.lang.Thread.run(Thread.java:840) [?:?]
2024-09-06 10:40:27.368 [WARN ] [nal.discovery.HomeAssistantDiscovery] - HomeAssistant discover error: invalid configuration of thing smartlock component lock: Cannot parse channel configuration JSON
2024-09-06 10:40:27.391 [WARN ] [ssistant.internal.DiscoverComponents] - HomeAssistant discover error: invalid configuration of thing smartlock component lock: Cannot parse channel configuration JSON
2024-09-06 10:40:30.529 [WARN ] [nal.discovery.HomeAssistantDiscovery] - HomeAssistant discover error: invalid configuration of thing smartlock component lock: Cannot parse channel configuration JSON
2024-09-06 10:40:30.563 [WARN ] [ssistant.internal.DiscoverComponents] - HomeAssistant discover error: invalid configuration of thing smartlock component lock: Cannot parse channel configuration JSON

```

**Comment by ccutrer** [comment]
Can you post the full value of the `homeassistant/lock/3a855b25/smartlock/config` topic from MQTT? And I assume you're on 4.3.0.M1 (or a recent snapshot)?

**Comment by adielsa** [comment]
nuki>configuration>basicjson
{"nukiID":"3a855b25","name":"F1","autoUnlatch":0,"pairingEnabled":1,"buttonEnabled":1,"ledEnabled":1,"ledBrightness":3,"currentTime":"2024-09-10 06:39:22","timeZoneOffset":0,"dstMode":0,"hasFob":0,"fobAction1":"Intelligent","fobAction2":"Unlock","fobAction3":"Lock","singleLock":0,"advertisingMode":"Automatic","hasKeypad":0,"hasKeypadV2":0,"firmwareVersion":"4.3.10","hardwareRevision":"8.3","homeKitStatus":"Not Available","timeZone":"Asia/Jerusalem"}

nuki>configuration>advancesjson
{"totalDegrees":0,"unlockedPositionOffsetDegrees":0,"lockedPositionOffsetDegrees":0,"singleLockedPositionOffsetDegrees":0,"unlockedToLockedTransitionOffsetDegrees":0,"lockNgoTimeout":20,"singleButtonPressAction":"Intelligent","doubleButtonPressAction":"Lock n Go","detachedCylinder":0,"batteryType":"Accumulators","automaticBatteryTypeDetection":1,"unlatchDuration":3,"autoLockTimeOut":300,"autoUnLockDisabled":0,"nightModeEnabled":0,"nightModeStartTime":"22:00","nightModeEndTime":"06:00","nightModeAutoLockEnabled":1,"nightModeAutoUnlockDisabled":1,"nightModeImmediateLockOnStart":1,"autoLockEnabled":1,"immediateAutoLockEnabled":1,"autoUpdateEnabled":1}

nuki>lock>json
{"lock_state":"locked","lockngo_state":0,"trigger":"autoLock","currentTime":"2024-09-10 07:07:06","timeZoneOffset":0,"nightModeActive":0,"last_lock_action":"Unlock","last_lock_action_trigger":"autoLock","lock_completion_status":"success","door_sensor_state":"unavailable","auth_id":0,"auth_name":""}


![image](https://github.com/user-attachments/assets/88b45cab-e5b9-45ec-85d2-a68524b0cf8f)

**Comment by ccutrer** [comment]
Those are all values about the device itself, and not the discovery information from the topic I requested.

**Comment by adielsa** [comment]
> Those are all values about the device itself, and not the discovery information from the topic I requested.

How do i provide it you? what is the path?

**Comment by adielsa** [comment]
> Can you post the full value of the `homeassistant/lock/3a855b25/smartlock/config` topic from MQTT? And I assume you're on 4.3.0.M1 (or a recent snapshot)?

{"dev":{"ids":["nuki_3a855b25"],"mf":"Nuki","mdl":"SmartLock","name":"F1","sw":"4.3.10","hw":"8.3","cu":"http://192.168.82.153"},"~":"nuki","name":null,"unique_id":"3a855b25_lock","cmd_t":"~/lock/action","avty":{"t":"~/maintenance/mqttConnectionState"},"pl_lock":"lock","pl_unlk":"unlock","pl_open":"unlatch","stat_t":"~/lock/hastate","stat_jammed":"jammed","stat_locked":"locked","stat_locking":"locking","stat_unlocked":"unlocked","stat_unlocking":"unlocking","stat_open":"open","stat_opening":"opening","opt":"false"}

**Comment by ccutrer** [comment]
The configuration JSON does not follow the specification. For the `"avty"` entry, [the docs](https://www.home-assistant.io/integrations/lock.mqtt/#availability) describe it as a list [of objects] (i.e. an Array), but your device is sending a single object. I've opened [a PR](https://github.com/technyon/nuki_hub/pull/475) against nuki_hub to fix it, but I have no way of testing that code change works on their end. I have confirmed that changing the configuration metadata as I show there, the device then shows up in my openHAB inbox.

**Comment by lsiepel** [comment]
Would be nice if you can link the PR so we can track it here.

**Comment by ccutrer** [comment]
I did link it in my comment (but as an inline link, not as part of the text). https://github.com/technyon/nuki_hub/pull/475. Do we need to put it anywhere else?

**Comment by lsiepel** [comment]
No, just somehow misread it. Perfectly fine as is.

**Comment by ccutrer** [comment]
Just an update on this, including discussion from elsewhere - Home Assistant's docs imply that `availability` is a list, but deep in their code they silently convert a single string to a list, so in reality it's okay. nuki_hub has changed their discovery message to work with openHAB, but we really should add a custom Gson parser for availability to accept both formats to ensure compatibility with other devices that potentially do the same thing.
