### ISSUE TITLE
[http] RateLimitedHttpClientTest unstable

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-addons#17385]
This test failed in: https://ci.openhab.org/job/openHAB-Addons/1500/

```
Expected: (a value equal to or greater than <1000> and a value less than <1100>)
     but: a value equal to or greater than <1000> <992> was less than <1000>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
	at org.openhab.binding.http.RateLimitedHttpClientTest.testWithLimitAndPriority(RateLimitedHttpClientTest.java:99)
```

CC: @J-N-K

**Comment by wborn** [comment]
Still failing: https://ci.openhab.org/job/openHAB-Addons/1507/

```
Expected: (a value equal to or greater than <500> and a value less than <600>)
     but: a value equal to or greater than <500> <493> was less than <500>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
	at org.openhab.binding.http.RateLimitedHttpClientTest.testWithLimit(RateLimitedHttpClientTest.java:83)
```

**Comment by wborn** [comment]
Still failing: https://github.com/openhab/openhab-addons/actions/runs/14727916236/job/41334948025

```
[ERROR] Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 5.375 s <<< FAILURE! -- in org.openhab.binding.http.RateLimitedHttpClientTest
[ERROR] org.openhab.binding.http.RateLimitedHttpClientTest.testWithLimit -- Time elapsed: 0.562 s <<< FAILURE!
java.lang.AssertionError: 

Expected: (a value equal to or greater than <500> and a value less than <600>)
     but: a value equal to or greater than <500> <498> was less than <500>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
	at org.openhab.binding.http.RateLimitedHttpClientTest.testWithLimit(RateLimitedHttpClientTest.java:83)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
```
