### ISSUE TITLE
[netatmo] IndexOutOfBoundsException during camera thing initialization

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-addons#17446]
```

00:07:19.253 [WARN ] [ommon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception:
java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 0
        at jdk.internal.util.Preconditions.outOfBounds(Unknown Source) ~[?:?]
        at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source) ~[?:?]
        at jdk.internal.util.Preconditions.checkIndex(Unknown Source) ~[?:?]
        at java.util.Objects.checkIndex(Unknown Source) ~[?:?]
        at java.util.ArrayList.get(Unknown Source) ~[?:?]
        at org.openhab.binding.netatmo.internal.api.SecurityApi.getHomeEvents(SecurityApi.java:89) ~[?:?]
        at org.openhab.binding.netatmo.internal.handler.capability.SecurityCapability.updateReadings(SecurityCapability.java:124) ~[?:?]
        at org.openhab.binding.netatmo.internal.handler.capability.SecurityCapability.updateReadings(SecurityCapability.java:1) ~[?:?]
        at org.openhab.binding.netatmo.internal.handler.capability.RestCapability.lambda$1(RestCapability.java:59) ~[?:?]
        at java.util.Optional.ifPresent(Unknown Source) ~[?:?]
        at org.openhab.binding.netatmo.internal.handler.capability.RestCapability.updateReadings(RestCapability.java:59) ~[?:?]
        at org.openhab.binding.netatmo.internal.handler.CommonInterface.lambda$16(CommonInterface.java:219) ~[?:?]
        at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(Unknown Source) ~[?:?]
        at org.openhab.binding.netatmo.internal.handler.CommonInterface.updateReadings(CommonInterface.java:219) ~[?:?]
        at org.openhab.binding.netatmo.internal.handler.CommonInterface.proceedWithUpdate(CommonInterface.java:214) ~[?:?]
        at org.openhab.binding.netatmo.internal.handler.capability.RefreshCapability.proceedWithUpdate(RefreshCapability.java:87) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
```

I am runnign 4.3 Milestone 1.

@clinique for information

**Comment by lolodomo** [comment]
Just restarting the binding does not help.

Rebooting the camera and then restarting the binding solved the issue.
