### ISSUE TITLE
[SamsungTV] When adding smartThingsApiKey and smartThingsDeviceId see Null Pointer exception

### ISSUE THREAD

**Issue by ballle98** [openhab/openhab-addons#17704]
I have a 2020 Samsung Frame TV trying to enable smartThings API

## Expected Behavior
TV would transition to ONLINE

## Current Behavior
TV goes into unknown state and I see the following log

```
2024-11-05 19:46:20.925 [ERROR] [nal.common.AbstractInvocationHandler] - An error occurred while calling method 'ThingHandler.thingUpdated()' on 'org.openhab.binding.samsungtv.internal.handler.SamsungTvHandler@41263d2d': Cannot invoke "org.openhab.binding.samsungtv.internal.service.SmartThingsApiService.parseTVChannel(String)" because "this.this$0" is null
java.lang.NullPointerException: Cannot invoke "org.openhab.binding.samsungtv.internal.service.SmartThingsApiService.parseTVChannel(String)" because "this.this$0" is null
	at org.openhab.binding.samsungtv.internal.service.SmartThingsApiService$TvValues.lambda$11(SmartThingsApiService.java:250) ~[?:?]
	at java.util.Optional.map(Optional.java:260) ~[?:?]
	at org.openhab.binding.samsungtv.internal.service.SmartThingsApiService$TvValues.getTvChannel(SmartThingsApiService.java:250) ~[?:?]
	at org.openhab.binding.samsungtv.internal.service.SmartThingsApiService.lambda$2(SmartThingsApiService.java:488) ~[?:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at org.openhab.binding.samsungtv.internal.service.SmartThingsApiService.updateTV(SmartThingsApiService.java:486) ~[?:?]
	at org.openhab.binding.samsungtv.internal.service.SmartThingsApiService.lambda$14(SmartThingsApiService.java:719) ~[?:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at org.openhab.binding.samsungtv.internal.service.SmartThingsApiService.receiveSSEEvents(SmartThingsApiService.java:718) ~[?:?]
	at org.openhab.binding.samsungtv.internal.service.SmartThingsApiService.startSSE(SmartThingsApiService.java:613) ~[?:?]
	at org.openhab.binding.samsungtv.internal.service.SmartThingsApiService.start(SmartThingsApiService.java:867) ~[?:?]
	at org.openhab.binding.samsungtv.internal.handler.SamsungTvHandler.startService(SamsungTvHandler.java:701) ~[?:?]
	at org.openhab.binding.samsungtv.internal.handler.SamsungTvHandler.createService(SamsungTvHandler.java:652) ~[?:?]
	at org.openhab.binding.samsungtv.internal.handler.SamsungTvHandler.checkAndCreateServices(SamsungTvHandler.java:617) ~[?:?]
	at org.openhab.binding.samsungtv.internal.handler.SamsungTvHandler.initialize(SamsungTvHandler.java:457) ~[?:?]
	at org.openhab.core.thing.binding.BaseThingHandler.thingUpdated(BaseThingHandler.java:157) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor69.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:569) ~[?:?]
	at org.openhab.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:147) [bundleFile:?]
	at org.openhab.core.internal.common.Invocation.call(Invocation.java:52) [bundleFile:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:840) [?:?]

```

## Steps to Reproduce (for Bugs)
1. Scan for TV
2. Add TV, toggle advanced settings and enter API tolken and deviceID

## Your Environment
* Version used:  openHAB 4.2.1
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...): Chrome Version 130.0.6723.92
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): Openhabian, bookworm, RPi 4
* TV Model: QN50LS03TAFXZA
* TV FW:  2505.4

**Comment by lsiepel** [comment]
Please upgrade to 4.2.2 as this has been fixed.
See release notes here:
https://github.com/openhab/openhab-distro/releases/tag/4.2.2
