### ISSUE TITLE
[homewizard] The p1 meter stays in status unknow

### ISSUE THREAD

**Issue by bucofski** [openhab/openhab-addons#17758]
I Upgraded to 4.3m4 and there is one problem with the homewizard binding. It stays in status unkown.

> 2024-11-16 20:38:37.735 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception:
com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: Expected an int but was 226.800 at line 1 column 515 path $.active_voltage_l1_v
at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:251) ~[?:?]
at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:241) ~[?:?]
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.readIntoField(ReflectiveTypeAdapterFactory.java:212) ~[?:?]
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$FieldReflectionAdapter.readField(ReflectiveTypeAdapterFactory.java:433) ~[?:?]
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:393) ~[?:?]
at com.google.gson.Gson.fromJson(Gson.java:1227) ~[?:?]
at com.google.gson.Gson.fromJson(Gson.java:1137) ~[?:?]
at com.google.gson.Gson.fromJson(Gson.java:1047) ~[?:?]
at com.google.gson.Gson.fromJson(Gson.java:982) ~[?:?]
at org.openhab.binding.homewizard.internal.handler.HomeWizardDeviceHandler.pollData(HomeWizardDeviceHandler.java:140) ~[?:?]
at org.openhab.binding.homewizard.internal.handler.HomeWizardDeviceHandler.pollingCode(HomeWizardDeviceHandler.java:160) ~[?:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.lang.NumberFormatException: Expected an int but was 226.800 at line 1 column 515 path $.active_voltage_l1_v
at com.google.gson.stream.JsonReader.nextInt(JsonReader.java:1218) ~[?:?]
at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:249) ~[?:?]
… 16 more

If i can do somthing let me know! 
thank you in advance!!

**Comment by lsiepel** [comment]
Clear issue, I’ll try to come up with a fix

**Comment by bucofski** [comment]
Thx let me know if I have to test something!

**Comment by lsiepel** [comment]
Could you try:
https://1drv.ms/u/s!AnMcxmvEeupwjvhXkfIKBYTP1txbyg?e=jrQzDU

**Comment by bucofski** [comment]
Ok Friday I will do the test. I have 4.3m4 running so that will not be a problem keep you posted!

**Comment by bucofski** [comment]
Hey lsiepel,

 

It is in use and it works fine. I let it run no wand if there is a problem i will let you know.

Thanks fort he update!

 

Kind regards

 

Tom

 

Van: lsiepel ***@***.***> 
Verzonden: woensdag 20 november 2024 22:05
Aan: openhab/openhab-addons ***@***.***>
CC: bucofski ***@***.***>; Author ***@***.***>
Onderwerp: Re: [openhab/openhab-addons] [homewizard] The p1 meter stays in status unknow (Issue #17758)

 

Could you try:
https://1drv.ms/u/s!AnMcxmvEeupwjvhXkfIKBYTP1txbyg?e=jrQzDU
