### ISSUE TITLE
[yamahareceiver] If receiver is not reachable, binding might starve thing handler thread pool

### ISSUE THREAD

**Issue by maniac103** [openhab/openhab-addons#17768]
## Expected Behavior
Depending on whether a receiver is reachable or not, binding communication should stop eventually.

## Current Behavior
Under not yet clear circumstances, communication with the receiver can block indefinitely, blocking the OH thing handler thread pool and thus other bindings as well.
As an example, I just observed the following situation over (at least) multiple minutes:
```
"OH-thingHandler-1" Id=453 in RUNNABLE (running in native)
    at java.base@17.0.13/sun.nio.ch.SocketDispatcher.read0(Native Method)
    at java.base@17.0.13/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:47)
    at java.base@17.0.13/sun.nio.ch.NioSocketImpl.tryRead(NioSocketImpl.java:266)
    at java.base@17.0.13/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:317)
    at java.base@17.0.13/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:355)
    at java.base@17.0.13/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:808)
    at java.base@17.0.13/java.net.Socket$SocketInputStream.read(Socket.java:966)
    at java.base@17.0.13/java.io.BufferedInputStream.fill(BufferedInputStream.java:244)
    at java.base@17.0.13/java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
    at java.base@17.0.13/java.io.BufferedInputStream.read(BufferedInputStream.java:343)
      - locked java.io.BufferedInputStream@5b1d4cc8
    at java.base@17.0.13/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:826)
    at java.base@17.0.13/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:761)
    at java.base@17.0.13/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1724)
    at java.base@17.0.13/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1625)
    at java.base@17.0.13/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:529)
    at org.openhab.binding.yamahareceiver.internal.protocol.xml.XMLConnection.postMessage(XMLConnection.java:91)
    at org.openhab.binding.yamahareceiver.internal.protocol.xml.XMLConnection.sendReceive(XMLConnection.java:124)
    at org.openhab.binding.yamahareceiver.internal.protocol.xml.XMLProtocolService.getResponse(XMLProtocolService.java:82)
    at org.openhab.binding.yamahareceiver.internal.protocol.xml.XMLProtocolService.getZoneResponse(XMLProtocolService.java:68)
    at org.openhab.binding.yamahareceiver.internal.protocol.xml.ZoneControlXML.update(ZoneControlXML.java:307)
    at org.openhab.binding.yamahareceiver.internal.handler.YamahaZoneThingHandler.lambda$2(YamahaZoneThingHandler.java:734)
    at org.openhab.binding.yamahareceiver.internal.handler.YamahaZoneThingHandler$$Lambda$2312/0x0000000101555928.run(Unknown Source)
    at java.base@17.0.13/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
    at java.base@17.0.13/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base@17.0.13/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
    at java.base@17.0.13/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.base@17.0.13/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.base@17.0.13/java.lang.Thread.run(Thread.java:840)

"OH-thingHandler-2" Id=463 in RUNNABLE (running in native)
    at java.base@17.0.13/sun.nio.ch.SocketDispatcher.read0(Native Method)
    at java.base@17.0.13/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:47)
    at java.base@17.0.13/sun.nio.ch.NioSocketImpl.tryRead(NioSocketImpl.java:266)
    at java.base@17.0.13/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:317)
    at java.base@17.0.13/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:355)
    at java.base@17.0.13/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:808)
    at java.base@17.0.13/java.net.Socket$SocketInputStream.read(Socket.java:966)
    at java.base@17.0.13/java.io.BufferedInputStream.fill(BufferedInputStream.java:244)
    at java.base@17.0.13/java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
    at java.base@17.0.13/java.io.BufferedInputStream.read(BufferedInputStream.java:343)
      - locked java.io.BufferedInputStream@5e1d942d
    at java.base@17.0.13/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:826)
    at java.base@17.0.13/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:761)
    at java.base@17.0.13/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1724)
    at java.base@17.0.13/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1625)
    at java.base@17.0.13/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:529)
    at org.openhab.binding.yamahareceiver.internal.protocol.xml.XMLConnection.postMessage(XMLConnection.java:91)
    at org.openhab.binding.yamahareceiver.internal.protocol.xml.XMLConnection.sendReceive(XMLConnection.java:124)
    at org.openhab.binding.yamahareceiver.internal.protocol.xml.XMLProtocolService.getResponse(XMLProtocolService.java:82)
    at org.openhab.binding.yamahareceiver.internal.protocol.xml.SystemControlXML.update(SystemControlXML.java:149)
    at org.openhab.binding.yamahareceiver.internal.handler.YamahaBridgeHandler.updateAllZoneInformation(YamahaBridgeHandler.java:248)
    at org.openhab.binding.yamahareceiver.internal.handler.YamahaBridgeHandler.lambda$0(YamahaBridgeHandler.java:215)
    at org.openhab.binding.yamahareceiver.internal.handler.YamahaBridgeHandler$$Lambda$1664/0x0000000100f92238.run(Unknown Source)
    at java.base@17.0.13/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
    at java.base@17.0.13/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
    at java.base@17.0.13/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
    at java.base@17.0.13/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.base@17.0.13/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.base@17.0.13/java.lang.Thread.run(Thread.java:840)

"OH-thingHandler-3" Id=477 in RUNNABLE (running in native)
    at java.base@17.0.13/sun.nio.ch.SocketDispatcher.read0(Native Method)
    at java.base@17.0.13/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:47)
    at java.base@17.0.13/sun.nio.ch.NioSocketImpl.tryRead(NioSocketImpl.java:266)
    at java.base@17.0.13/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:317)
    at java.base@17.0.13/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:355)
    at java.base@17.0.13/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:808)
    at java.base@17.0.13/java.net.Socket$SocketInputStream.read(Socket.java:966)
    at java.base@17.0.13/java.io.BufferedInputStream.fill(BufferedInputStream.java:244)
    at java.base@17.0.13/java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
    at java.base@17.0.13/java.io.BufferedInputStream.read(BufferedInputStream.java:343)
      - locked java.io.BufferedInputStream@3f5f152f
    at java.base@17.0.13/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:826)
    at java.base@17.0.13/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:761)
    at java.base@17.0.13/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1724)
    at java.base@17.0.13/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1625)
    at java.base@17.0.13/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:529)
    at org.openhab.binding.yamahareceiver.internal.protocol.xml.XMLConnection.postMessage(XMLConnection.java:91)
    at org.openhab.binding.yamahareceiver.internal.protocol.xml.XMLConnection.sendReceive(XMLConnection.java:124)
    at org.openhab.binding.yamahareceiver.internal.protocol.xml.XMLProtocolService.getResponse(XMLProtocolService.java:82)
    at org.openhab.binding.yamahareceiver.internal.protocol.xml.XMLProtocolService.getZoneResponse(XMLProtocolService.java:68)
    at org.openhab.binding.yamahareceiver.internal.protocol.xml.XMLProtocolService.getInputs(XMLProtocolService.java:101)
    at org.openhab.binding.yamahareceiver.internal.protocol.xml.ZoneAvailableInputsXML.update(ZoneAvailableInputsXML.java:71)
    at org.openhab.binding.yamahareceiver.internal.handler.YamahaZoneThingHandler.lambda$2(YamahaZoneThingHandler.java:734)
    at org.openhab.binding.yamahareceiver.internal.handler.YamahaZoneThingHandler$$Lambda$2312/0x0000000101555928.run(Unknown Source)
    at java.base@17.0.13/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
    at java.base@17.0.13/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base@17.0.13/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
    at java.base@17.0.13/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.base@17.0.13/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.base@17.0.13/java.lang.Thread.run(Thread.java:840)

"OH-thingHandler-4" Id=478 in RUNNABLE (running in native)
    at java.base@17.0.13/sun.nio.ch.SocketDispatcher.read0(Native Method)
    at java.base@17.0.13/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:47)
    at java.base@17.0.13/sun.nio.ch.NioSocketImpl.tryRead(NioSocketImpl.java:266)
    at java.base@17.0.13/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:317)
    at java.base@17.0.13/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:355)
    at java.base@17.0.13/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:808)
    at java.base@17.0.13/java.net.Socket$SocketInputStream.read(Socket.java:966)
    at java.base@17.0.13/java.io.BufferedInputStream.fill(BufferedInputStream.java:244)
    at java.base@17.0.13/java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
    at java.base@17.0.13/java.io.BufferedInputStream.read(BufferedInputStream.java:343)
      - locked java.io.BufferedInputStream@1beeb0ed
    at java.base@17.0.13/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:826)
    at java.base@17.0.13/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:761)
    at java.base@17.0.13/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1724)
    at java.base@17.0.13/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1625)
    at java.base@17.0.13/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:529)
    at org.openhab.binding.yamahareceiver.internal.protocol.xml.XMLConnection.postMessage(XMLConnection.java:91)
    at org.openhab.binding.yamahareceiver.internal.protocol.xml.XMLConnection.sendReceive(XMLConnection.java:124)
    at org.openhab.binding.yamahareceiver.internal.protocol.xml.XMLProtocolService.getResponse(XMLProtocolService.java:82)
    at org.openhab.binding.yamahareceiver.internal.protocol.xml.XMLProtocolService.getZoneResponse(XMLProtocolService.java:68)
    at org.openhab.binding.yamahareceiver.internal.protocol.xml.XMLProtocolService.getInputs(XMLProtocolService.java:101)
    at org.openhab.binding.yamahareceiver.internal.protocol.xml.ZoneAvailableInputsXML.update(ZoneAvailableInputsXML.java:71)
    at org.openhab.binding.yamahareceiver.internal.handler.YamahaZoneThingHandler.lambda$2(YamahaZoneThingHandler.java:734)
    at org.openhab.binding.yamahareceiver.internal.handler.YamahaZoneThingHandler$$Lambda$2312/0x0000000101555928.run(Unknown Source)
    at java.base@17.0.13/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
    at java.base@17.0.13/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base@17.0.13/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
    at java.base@17.0.13/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.base@17.0.13/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.base@17.0.13/java.lang.Thread.run(Thread.java:840)

"OH-thingHandler-5" Id=481 in RUNNABLE (running in native)
    at java.base@17.0.13/sun.nio.ch.SocketDispatcher.read0(Native Method)
    at java.base@17.0.13/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:47)
    at java.base@17.0.13/sun.nio.ch.NioSocketImpl.tryRead(NioSocketImpl.java:266)
    at java.base@17.0.13/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:317)
    at java.base@17.0.13/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:355)
    at java.base@17.0.13/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:808)
    at java.base@17.0.13/java.net.Socket$SocketInputStream.read(Socket.java:966)
    at java.base@17.0.13/java.io.BufferedInputStream.fill(BufferedInputStream.java:244)
    at java.base@17.0.13/java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
    at java.base@17.0.13/java.io.BufferedInputStream.read(BufferedInputStream.java:343)
      - locked java.io.BufferedInputStream@3905e87d
    at java.base@17.0.13/sun.net.www.MeteredStream.read(MeteredStream.java:141)
    at java.base@17.0.13/java.io.FilterInputStream.read(FilterInputStream.java:132)
    at java.base@17.0.13/sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3734)
    at java.base@17.0.13/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:281)
    at java.base@17.0.13/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:324)
    at java.base@17.0.13/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:189)
      - locked java.io.InputStreamReader@57024e68
    at java.base@17.0.13/java.io.InputStreamReader.read(InputStreamReader.java:177)
    at java.base@17.0.13/java.io.BufferedReader.fill(BufferedReader.java:162)
    at java.base@17.0.13/java.io.BufferedReader.readLine(BufferedReader.java:329)
      - locked java.io.InputStreamReader@57024e68
    at java.base@17.0.13/java.io.BufferedReader.readLine(BufferedReader.java:396)
    at org.openhab.binding.yamahareceiver.internal.protocol.xml.XMLConnection.consumeResponse(XMLConnection.java:135)
    at org.openhab.binding.yamahareceiver.internal.protocol.xml.XMLConnection.lambda$1(XMLConnection.java:124)
    at org.openhab.binding.yamahareceiver.internal.protocol.xml.XMLConnection$$Lambda$1535/0x0000000100f47a00.apply(Unknown Source)
    at org.openhab.binding.yamahareceiver.internal.protocol.xml.XMLConnection.postMessage(XMLConnection.java:95)
    at org.openhab.binding.yamahareceiver.internal.protocol.xml.XMLConnection.sendReceive(XMLConnection.java:124)
    at org.openhab.binding.yamahareceiver.internal.protocol.xml.XMLProtocolService.getResponse(XMLProtocolService.java:82)
    at org.openhab.binding.yamahareceiver.internal.protocol.xml.XMLProtocolService.getZoneResponse(XMLProtocolService.java:68)
    at org.openhab.binding.yamahareceiver.internal.protocol.xml.XMLProtocolService.getInputs(XMLProtocolService.java:101)
    at org.openhab.binding.yamahareceiver.internal.protocol.xml.ZoneAvailableInputsXML.update(ZoneAvailableInputsXML.java:71)
    at org.openhab.binding.yamahareceiver.internal.handler.YamahaZoneThingHandler.lambda$2(YamahaZoneThingHandler.java:734)
    at org.openhab.binding.yamahareceiver.internal.handler.YamahaZoneThingHandler$$Lambda$2312/0x0000000101555928.run(Unknown Source)
    at java.base@17.0.13/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
    at java.base@17.0.13/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base@17.0.13/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
    at java.base@17.0.13/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.base@17.0.13/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.base@17.0.13/java.lang.Thread.run(Thread.java:840)
```

At that point, e.g. the Hue binding could not process incoming events anymore due to blocked thread pool.

## Possible Solution
The binding should use timeouts for communication.

## Steps to Reproduce (for Bugs)
Unclear, but it's likely related to the receiver not being reachable at OH startup time.

## Your Environment
* Version used: OH 4.2.2
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...): OpenJDK 17
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): Ubuntu 22.04 server

**Comment by maniac103** [comment]
The uncertain circumstances probably are the receiver going away while being polled. Since the binding [only sets a connect timeout, but no read timeout](https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.binding.yamahareceiver/src/main/java/org/openhab/binding/yamahareceiver/internal/protocol/xml/XMLConnection.java#L79), connection failures lead to a timeout, but if connect succeeded and subsequent read stalls, the binding blocks indefinitely.
