### ISSUE TITLE
[HomeKit] Error trying to add a Television from OpenHAB

### ISSUE THREAD

**Issue by mjcumming** [openhab/openhab-addons#17800]
I am getting the following dump in the logs and trying to add a television with these settings.

Item:

`/*
// Master Bedroom LG TV Equipment
Group          gEquipMasterTV                   "Master Bedroom TV"         <device:screen>      (gEquip_SecondFloor_MasterBedroom_Television)    ["Equipment","Television"]     {homekit="Television"}

// Core Controls
Switch         MasterTV_Power                   "TV Power"                  <device:switch>      (gEquipMasterTV)                                 ["Point","Control","Power"]    {homekit="Television.Active"}
Player         MasterTV_Player                  "TV Player"                 <device:player>      (gEquipMasterTV)                                 ["Point","Control"]            {homekit="Television.CurrentMediaState", channel="lgwebos:WebOSTV:masterbedroom:mediaPlayer"}
String         MasterTV_RemoteKey               "Remote Control"            <device:remote>      (gEquipMasterTV)                                 ["Point","Control"]            {homekit="Television.RemoteKey", channel="lgwebos:WebOSTV:masterbedroom:rcButton"}

// Audio Controls
Dimmer         MasterTV_Volume                  "Volume"                    <device:volume>      (gEquipMasterTV)                                 ["Point","Control","Sound"]    {homekit="Speaker.Volume", channel="lgwebos:WebOSTV:masterbedroom:volume"}
Switch         MasterTV_Mute                    "Mute"                      <device:mute>        (gEquipMasterTV)                                 ["Point","Control","Sound"]    {homekit="Speaker.Mute"}

// Input Sources
String         MasterTV_Input                   "Input Source"              <device:status>      (gEquipMasterTV)                                 ["Point","Status"]             {homekit="Television.ActiveIdentifier", channel="lgwebos:WebOSTV:masterbedroom:channel"}

// Input Source Definitions
Group          gMasterTVInput_HDMI1             "HDMI 1"                    <device:screen>      (gEquipMasterTV)                                 ["Equipment"]                  {homekit="InputSource" [Identifier=1, InputDeviceType="HDMI", InputSourceType="HDMI"]}
Group          gMasterTVInput_Apps              "TV Apps"                   <device:screen>      (gEquipMasterTV)                                 ["Equipment"]                  {homekit="InputSource" [Identifier=2, InputDeviceType="TV", InputSourceType="APPLICATION"]}
`

LOGS:

`2024-11-24 07:07:46.172 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception: 
java.lang.IllegalArgumentException: No enum constant io.github.hapjava.characteristics.impl.inputsource.InputDeviceTypeEnum.HDMI
	at java.lang.Enum.valueOf(Enum.java:273) ~[?:?]
	at org.openhab.io.homekit.internal.accessories.HomekitMetadataCharacteristicFactory.getEnum(HomekitMetadataCharacteristicFactory.java:153) ~[?:?]
	at org.openhab.io.homekit.internal.accessories.HomekitMetadataCharacteristicFactory.createInputDeviceTypeCharacteristic(HomekitMetadataCharacteristicFactory.java:260) ~[?:?]
	at org.openhab.io.homekit.internal.accessories.HomekitMetadataCharacteristicFactory.access$12(HomekitMetadataCharacteristicFactory.java:259) ~[?:?]
	at org.openhab.io.homekit.internal.accessories.HomekitMetadataCharacteristicFactory.createCharacteristic(HomekitMetadataCharacteristicFactory.java:129) ~[?:?]
	at org.openhab.io.homekit.internal.accessories.HomekitMetadataCharacteristicFactory.createCharacteristic(HomekitMetadataCharacteristicFactory.java:122) ~[?:?]
	at org.openhab.io.homekit.internal.accessories.HomekitAccessoryFactory.addOptionalMetadataCharacteristics(HomekitAccessoryFactory.java:440) ~[?:?]
	at org.openhab.io.homekit.internal.accessories.HomekitAccessoryFactory.create(HomekitAccessoryFactory.java:224) ~[?:?]
	at org.openhab.io.homekit.internal.accessories.HomekitAccessoryFactory.addLinkedServices(HomekitAccessoryFactory.java:493) ~[?:?]
	at org.openhab.io.homekit.internal.accessories.HomekitAccessoryFactory.create(HomekitAccessoryFactory.java:228) ~[?:?]
	at org.openhab.io.homekit.internal.accessories.HomekitAccessoryFactory.create(HomekitAccessoryFactory.java:190) ~[?:?]
	at org.openhab.io.homekit.internal.HomekitChangeListener.createRootAccessories(HomekitChangeListener.java:462) ~[?:?]
	at org.openhab.io.homekit.internal.HomekitChangeListener.<init>(HomekitChangeListener.java:146) ~[?:?]
	at org.openhab.io.homekit.internal.HomekitImpl.startHomekitServer(HomekitImpl.java:265) ~[?:?]
	at org.openhab.io.homekit.internal.HomekitImpl.startHomekitServer(HomekitImpl.java:275) ~[?:?]
	at org.openhab.io.homekit.internal.HomekitImpl.onReadyMarkerAdded(HomekitImpl.java:205) ~[?:?]
	at org.openhab.core.internal.service.ReadyServiceImpl.lambda$0(ReadyServiceImpl.java:51) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1850) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at org.openhab.core.internal.service.ReadyServiceImpl.notifyTrackers(ReadyServiceImpl.java:75) ~[?:?]
	at org.openhab.core.internal.service.ReadyServiceImpl.markReady(ReadyServiceImpl.java:51) ~[?:?]
	at org.openhab.core.service.StartLevelService.setStartLevel(StartLevelService.java:249) ~[?:?]
	at org.openhab.core.service.StartLevelService.lambda$0(StartLevelService.java:123) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:840) [?:?]`

**Comment by ccutrer** [comment]
The log is pretty clear: `No enum constant io.github.hapjava.characteristics.impl.inputsource.InputDeviceTypeEnum.HDMI`  - i.e. HDMI is not a valid value for InputDeviceType.

See https://www.openhab.org/addons/integrations/homekit/#supported-accessory-types for the valid values:

> Type of the input device. possible values (OTHER, TV, RECORDING, TUNER, PLAYBACK, AUDIO_SYSTEM). Custom mapping can be defined at item level. Can also be configured via metadata, e.g. [InputDeviceType="OTHER"].
