### ISSUE TITLE
[onewire] binding<>server connection loss after Owserver is restarted

### ISSUE THREAD

**Issue by Jetblack31** [openhab/openhab-addons#17941]
Hello,

I have an issue with onewire binding :

## Current Behavior
When the OW server is stopped (and restarted), I obtain many lines like these in the OH logs :

```
2024-12-21 04:17:34.403 [WARN ] [internal.owserver.OwserverConnection] - EOFException: exception while reading packet - null
...
2024-12-21 04:17:34.437 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception: 
	at org.openhab.binding.onewire.internal.owserver.OwserverConnection.request(OwserverConnection.java:304) ~[?:?]
	at org.openhab.binding.onewire.internal.owserver.OwserverConnection.request(OwserverConnection.java:304) ~[?:?]
...
```

Following that, the connection is lost between the binding and the OWserver and sensors are not updated anymore in OH.
My current solution is to disable/wait 5 s/enable the OW Thing to restart the connection.

## Environment

* OH 4.3 (this bug is present since OH4, and did not exist on my previous OH2 installation)
* Openhabian, Raspberry 4 Bullseye
* The OWserver runs on a separate Raspberry Pi

**Comment by lsiepel** [comment]
I can try to fix this issue, do you encounter this often ? 
Any way to force/reproduce it?

**Comment by Jetblack31** [comment]
Hello,

It happens each time owserver is stopped and restarted.
In my case, owserver runs on a separate raspberry. This raspberry reboots each day by schedule so owserver stops and restarts each day. It takes a few minutes.
Each day, the connection between openhab and owserver is lost, and the OW Thing needs to be stopped and restarted to recover the connection.

Many thanks,
Jetblack

**Comment by lsiepel** [comment]
There is a reconnection mechanism, but it has a 5 second delay and tries max 5 times. So i guess in your case 25 seconds is not enough for the reboot.
Would you be able to set the binding into debug logging and trigger the problem? I would be interested in the part from `EOFException: exception while reading packet - null` and all lines directly after that.

I might be able to make some of these delays and reconnection attempts configurable to fix your use case. 

As a side note, i do wonder why you reboot that machine every day.

**Comment by lsiepel** [comment]
Created an updated jar for improved logging. Make sure the 

1. Make sure you have openHAB 5.1.0 or later
2. Uninstall the shipped binding
3. Download the updated jar from here: https://1drv.ms/u/c/70ea7ac46bc61c73/IQCFpjS8m5r4T4FZ75q9oV4VAUkrb66uMYeD1s-1JNoBwlY?e=joscBZ
4. Drop the jar file in your openHAB addon folder.
5. Set the binding log level in debug and observe your logs and report your feedback.
