### ISSUE TITLE
Generac MobileLink binding fails to initialize on 4.3.0

### ISSUE THREAD

**Issue by DrTron** [openhab/openhab-addons#17961]
It seems the upgrade from 4.2.3-1 to 4.3.0-1 affected the Generac Mobile Link binding, it now fails to initialize.
username/password are correct and I can log into the Generac account using these credentials.

The bridge thing shows: COMMUNICATION_ERROR, Session Expired

A stop and re-start of the bridge shows this in the logs:

```
08:51:41.377 [INFO ] [hab.event.ThingStatusInfoChangedEvent] - Thing 'generacmobilelink:account:ced1bbc17f' changed from UNINITIALIZED (DISABLED) to INITIALIZING
08:51:41.379 [INFO ] [hab.event.ThingStatusInfoChangedEvent] - Thing 'generacmobilelink:account:ced1bbc17f' changed from INITIALIZING to UNKNOWN
08:51:41.381 [INFO ] [hab.event.ThingStatusInfoChangedEvent] - Thing 'generacmobilelink:generator:ced1bbc17f:918466' changed from UNINITIALIZED (BRIDGE_UNINITIALIZED) to INITIALIZING
08:51:41.383 [INFO ] [hab.event.ThingStatusInfoChangedEvent] - Thing 'generacmobilelink:generator:ced1bbc17f:918466' changed from INITIALIZING to UNKNOWN
08:51:45.898 [INFO ] [hab.event.ThingStatusInfoChangedEvent] - Thing 'generacmobilelink:account:ced1bbc17f' changed from UNKNOWN to ONLINE
08:51:46.039 [INFO ] [hab.event.ThingStatusInfoChangedEvent] - Thing 'generacmobilelink:account:ced1bbc17f' changed from ONLINE to OFFLINE (COMMUNICATION_ERROR): Session Expired
08:51:46.040 [INFO ] [hab.event.ThingStatusInfoChangedEvent] - Thing 'generacmobilelink:generator:ced1bbc17f:918466' changed from UNKNOWN to OFFLINE (BRIDGE_OFFLINE)
```

I'm not sure if something has changed on the Generac side or if the binding has issues with the Openhab upgrade.

**Comment by digitaldan** [comment]
So mine was offline as well, but i just paused and unpaused the account thing and its back online, can you try that as well?   Also nice to know there are others using this binding ;-)

**Comment by DrTron** [comment]
That's exactly what I did, pause and unpause the account thing. Didn't help, sadly, still offline.

**Comment by digitaldan** [comment]
Hmm, i'll take a look at it.

**Comment by lsiepel** [comment]
If you set the binding’s log level to debug it should show some useful data for troubleshooting.

**Comment by DrTron** [comment]
Absolutely, here it is:

```
2024-12-23 17:39:48.392 [DEBUG] [dler.GeneracMobileLinkAccountHandler] - Attempting login
2024-12-23 17:39:49.796 [DEBUG] [dler.GeneracMobileLinkAccountHandler] - login response status 200
2024-12-23 17:39:51.151 [DEBUG] [dler.GeneracMobileLinkAccountHandler] - getEndpoint [{"apparatusId":918466,"serialNumber":"xxxxxxxx","name":"xxxxx","type":0,"localizedAddress":"xxxx
2024-12-23 17:39:51.345 [DEBUG] [dler.GeneracMobileLinkAccountHandler] - Session expired
org.openhab.binding.generacmobilelink.internal.handler.GeneracMobileLinkAccountHandler$SessionExpiredException: API returned status code: 403
        at org.openhab.binding.generacmobilelink.internal.handler.GeneracMobileLinkAccountHandler.getEndpoint(GeneracMobileLinkAccountHandler.java:234) ~[?:?]
        at org.openhab.binding.generacmobilelink.internal.handler.GeneracMobileLinkAccountHandler.updateGeneratorThing(GeneracMobileLinkAccountHandler.java:218) ~[?:?]
        at org.openhab.binding.generacmobilelink.internal.handler.GeneracMobileLinkAccountHandler.updateGeneratorThings(GeneracMobileLinkAccountHandler.java:210) ~[?:?]
        at org.openhab.binding.generacmobilelink.internal.handler.GeneracMobileLinkAccountHandler.poll(GeneracMobileLinkAccountHandler.java:164) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
2024-12-23 17:40:26.671 [DEBUG] [dler.GeneracMobileLinkAccountHandler] - childHandlerInitialized generacmobilelink:generator:ced1bbc17f:918466
2024-12-23 17:40:26.672 [DEBUG] [dler.GeneracMobileLinkAccountHandler] - No device for id 918466
2024-12-23 17:40:27.668 [DEBUG] [dler.GeneracMobileLinkAccountHandler] - Attempting login
2024-12-23 17:40:28.555 [DEBUG] [dler.GeneracMobileLinkAccountHandler] - Could not load login page
2024-12-23 17:40:28.555 [DEBUG] [dler.GeneracMobileLinkAccountHandler] - parseSettings: {"remoteResource":"https://gpsprodpltazureb2c.blob.core.windows.net/mobile-link/SignIn.html","retryLimi
2024-12-23 17:40:29.183 [DEBUG] [dler.GeneracMobileLinkAccountHandler] - selfAssertedRequest response 200
2024-12-23 17:40:30.653 [DEBUG] [dler.GeneracMobileLinkAccountHandler] - login response status 200
2024-12-23 17:40:31.871 [DEBUG] [dler.GeneracMobileLinkAccountHandler] - getEndpoint [{"apparatusId":918466,"serialNumber":"xxxxxx","name":"xxxxx","type":0,"localizedAddress":"xxxxx
2024-12-23 17:40:32.188 [DEBUG] [dler.GeneracMobileLinkAccountHandler] - Session expired
org.openhab.binding.generacmobilelink.internal.handler.GeneracMobileLinkAccountHandler$SessionExpiredException: API returned status code: 403
        at org.openhab.binding.generacmobilelink.internal.handler.GeneracMobileLinkAccountHandler.getEndpoint(GeneracMobileLinkAccountHandler.java:234) ~[?:?]
        at org.openhab.binding.generacmobilelink.internal.handler.GeneracMobileLinkAccountHandler.updateGeneratorThing(GeneracMobileLinkAccountHandler.java:218) ~[?:?]
        at org.openhab.binding.generacmobilelink.internal.handler.GeneracMobileLinkAccountHandler.updateGeneratorThings(GeneracMobileLinkAccountHandler.java:210) ~[?:?]
        at org.openhab.binding.generacmobilelink.internal.handler.GeneracMobileLinkAccountHandler.poll(GeneracMobileLinkAccountHandler.java:164) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by DrTron** [comment]
Interestingly enough, I can get the Generac bridge back online if I disable (or delete) the Generator thing itself. But enabling (or adding from the inbox) of the Generator thing results in both going offline again, with the same error (Session Expired)...

**Comment by lsiepel** [comment]
@digitaldan did you look into this? Seems like a cached value or something that survives an enable disable
