### ISSUE TITLE
[sonyprojector] Scheduled runnable ended with an exception

### ISSUE THREAD

**Issue by morph166955** [openhab/openhab-addons#17989]
Just brought my Sony VPLVW285ES back online a few days ago.  I'm seeing this randomly in my logs.

```
2024-12-27 09:28:19.119 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception:
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
        at org.openhab.binding.sonyprojector.internal.communication.SonyProjectorConnector.convertDataToInt(SonyProjectorConnector.java:1203) ~[?:?]
        at org.openhab.binding.sonyprojector.internal.communication.SonyProjectorConnector.getHue(SonyProjectorConnector.java:265) ~[?:?]
        at org.openhab.binding.sonyprojector.internal.handler.SonyProjectorHandler.requestProjectorValue(SonyProjectorHandler.java:670) ~[?:?]
        at org.openhab.binding.sonyprojector.internal.handler.SonyProjectorHandler.refreshChannel(SonyProjectorHandler.java:751) ~[?:?]
        at org.openhab.binding.sonyprojector.internal.handler.SonyProjectorHandler.pollProjector(SonyProjectorHandler.java:446) ~[?:?]
        at org.openhab.binding.sonyprojector.internal.handler.SonyProjectorHandler.lambda$0(SonyProjectorHandler.java:406) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) [?:?]

```

**Comment by lolodomo** [comment]
Is it always when getting hue ?
Please enable DEBUG log and show what they are just before the exception.
I would like to see what is the answer of the projector.

**Comment by morph166955** [comment]
Ill turn on debug and see. I only really use a few channels, I don't have a hue item so I can't compare it as easily. I have noticed that my power channel goes from off to undef when I power it off about 50% of the time which I found odd.

**Comment by morph166955** [comment]
This hasn't happened again since that message.  I'll close this assuming it was an anomaly and reopen if it happens again.
