### ISSUE TITLE
[xmppclient] regression: host parameter required

### ISSUE THREAD

**Issue by skazi0** [openhab/openhab-addons#18007]
## Expected Behavior
The `host` parameter should not be required and `domain` should be used as default (as [documented](https://www.openhab.org/addons/bindings/xmppclient/)).
```
Bridge xmppclient:xmppBridge:xmpp "XMPP Client" [ username="user", domain="example.com", password="secret" ] {
}
```

## Current Behavior
Since last update (debian bookworm) the configuration as in example above stopped working. The log says:
```
[INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'xmppclient:xmppBridge:xmpp' changed from UNKNOWN to OFFLINE (CONFIGURATION_ERROR): Please check configuration
```

## Possible Solution
I think the regression comes from [recent change in xmpp binding](https://github.com/openhab/openhab-addons/pull/14397).
Looks like the `if (!host.isBlank())` condition doesn't work as expected if `host` is missing.
For now my workaround is:
```
Bridge xmppclient:xmppBridge:xmpp "XMPP Client" [ username="user", domain="example.com", host="example.com", password="secret" ] {
}
```

## Steps to Reproduce (for Bugs)
1. remove `host=...` from xmpp bridge configuration.
2. observe above error in events log.

## Your Environment
```
# dpkg -l | grep openhab
ii  openhab                                          4.3.1-1                                   all          openhab
ii  openhab-addons                                   4.3.1-1                                   all          openhab-addons

# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by lsiepel** [comment]
And when the host is empty, where do you expect it to connect to ? The default might be local host, might have overlooked that case

**Comment by riorado** [comment]
Hello,

I have the same behavior on Openhabian 4.3.2. It happened after the upgrade.
Impossible to get online with the XMPP Client binding. CONFIGURATION_ERROR Please check configuration
If I put the domain string in the Server Hostname/IP, the status becom "UNKNOWN"
I tried all possibilities, no way to let it work.

**Comment by lsiepel** [comment]
Sorry it took so long. Created a new JAR that should fix this case. Please download it from the linked PR and test it:

1. Make sure you have openHAB 4.3.x (latest stable)
2. Uninstall the current XMPP binding (all links etc won;t be affected)
3. Drop the downloaded JAR in the addon folder.
4. Report your results.

**Comment by skazi0** [comment]
I'm getting following error:
```
2025-02-20 11:12:25.773 [WARN ] [org.apache.felix.fileinstall        ] - Error while starting bundle: file:/usr/share/openhab/addons/org.openhab.binding.xmppclient-4.3.3-SNAPSHOT.j
org.osgi.framework.BundleException: Could not resolve module: org.openhab.binding.xmppclient [413]
  Unresolved requirement: Import-Package: org.jivesoftware.smack; version="[4.3.0,5.0.0)"

    at org.eclipse.osgi.container.Module.start(Module.java:463) ~[org.eclipse.osgi-3.18.0.jar:?]
    at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:445) ~[org.eclipse.osgi-3.18.0.jar:?]
    at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1260) [bundleFile:3.7.4]
    at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1233) [bundleFile:3.7.4]
    at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:520) [bundleFile:3.7.4]
    at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:365) [bundleFile:3.7.4]
    at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:316) [bundleFile:3.7.4]
```
but since the fix was already merged, maybe I'll just wait for next release and test then.

**Comment by lsiepel** [comment]
> f

Better wait for the release as the issue you have is related to how karaf handles dependency's in the addon folder. It is not related to this fix.
