### ISSUE TITLE
[homekit]  Room Binding

### ISSUE THREAD

**Issue by theo-69** [openhab/openhab-addons#2243]
Hi there, first I am new to this!

I have the issue that every time i restart the openhab server the items are not connected to the right room anymore. They always connected to the standard room. Is there a solution for this?

**Comment by brendanjerwin** [comment]
I seem to be running into this as well. Couple that with some sort of crashing problem that I seem to be plagued with and the end result is that my devices disappear and later reappear in the default room. Not super usable... :)

## Versions
  * openHAB 2.0.0-1 (Release Build) on RPi3
  * misc-homekit - 2.0.0

## Logs
```
2017-05-06 14:28:18.874 [ERROR] [lfe.hap.impl.http.impl.BinaryHandler] - Exception in binary handler
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)[:1.8.0_121]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)[:1.8.0_121]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)[:1.8.0_121]
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)[:1.8.0_121]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)[:1.8.0_121]
	at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:447)[184:org.openhab.io.homekit:2.0.0]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:880)[184:org.openhab.io.homekit:2.0.0]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:242)[184:org.openhab.io.homekit:2.0.0]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119)[184:org.openhab.io.homekit:2.0.0]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)[184:org.openhab.io.homekit:2.0.0]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)[184:org.openhab.io.homekit:2.0.0]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)[184:org.openhab.io.homekit:2.0.0]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)[184:org.openhab.io.homekit:2.0.0]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)[184:org.openhab.io.homekit:2.0.0]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)[184:org.openhab.io.homekit:2.0.0]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_121]
2017-05-06 14:28:18.891 [ERROR] [.hap.impl.http.impl.AccessoryHandler] - Exception caught in web handler
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)[:1.8.0_121]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)[:1.8.0_121]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)[:1.8.0_121]
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)[:1.8.0_121]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)[:1.8.0_121]
	at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:447)[184:org.openhab.io.homekit:2.0.0]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:880)[184:org.openhab.io.homekit:2.0.0]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:242)[184:org.openhab.io.homekit:2.0.0]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119)[184:org.openhab.io.homekit:2.0.0]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)[184:org.openhab.io.homekit:2.0.0]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)[184:org.openhab.io.homekit:2.0.0]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)[184:org.openhab.io.homekit:2.0.0]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)[184:org.openhab.io.homekit:2.0.0]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)[184:org.openhab.io.homekit:2.0.0]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)[184:org.openhab.io.homekit:2.0.0]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_121]
```

**Comment by brendanjerwin** [comment]
Looks like this might be a dup of #929

**Comment by theo-69** [comment]
yep annoying just switched to homebridge and it works like a charm :-)

**Comment by theo-69** [comment]
still no solution?

**Comment by Gozilla01** [comment]
Any update on this?
thank you

**Comment by baakoo** [comment]
I have similar problems with room assignment running openbab 2.3.0.1 release build. See https://github.com/openhab/openhab2-addons/issues/929 

By the way: Where can I change the startup time, maybe this helps in my case

**Comment by J-N-K** [comment]
Please check if this is still the case with a recent version of OH (i.e. 2.5 SNAPSHOT >= 1601).

**Comment by Gozilla01** [comment]
Can the room be defined using OH configuration files?
Or just in the Ios app?

**Comment by J-N-K** [comment]
I do it in the iOS app. I didn't see anything in the code that would allow to define it in OH configuration files.

**Comment by Gozilla01** [comment]
Can it be a future implementation?

**Comment by J-N-K** [comment]
Feel free to implement it. It's not on my list. I'm just trying to figure out if the reported problem (room association lost on OH restart) is still present or not.

**Comment by yfre** [comment]
room can only assigned in ios home app. there is nothing we can do on the server side. 
it is limitation (or feature) of Apple home app design. 
so, this issue can be closed,

**Comment by J-N-K** [comment]
Closed because implementation is not feasible.
