### ISSUE TITLE
Sonos Binding throws IllegalStateException

### ISSUE THREAD

**Issue by hmerk** [openhab/openhab-addons#239]
I just gave a try on Snapshot 173 and experienced that the Sonos Binding stoped working with my Play:1.
Here is what the log says:
2015-05-20 23:00:24 [DEBUG] [s.internal.SonosHandlerFactory:64   ] - Creating a sonos zone player thing with ID 'sonos:zoneplayer:RINCON_B8E937BDB4D401400'
2015-05-20 23:00:24 [DEBUG] [s.c.d.internal.PersistentInbox:250  ] - Discovery result removed from inbox, because it was added as a Thing to the ThingRegistry.
2015-05-20 23:00:24 [DEBUG] [.c.thing.internal.ThingManager:278  ] - Thing 'sonos:zoneplayer:RINCON_B8E937BDB4D401400' is tracked by ThingManager.
2015-05-20 23:00:24 [DEBUG] [.c.thing.internal.ThingManager:381  ] - Creating handler for thing 'sonos:zoneplayer:RINCON_B8E937BDB4D401400'.
2015-05-20 23:00:24 [DEBUG] [s.internal.SonosHandlerFactory:83   ] - Creating a ZonePlayerHandler for thing 'sonos:zoneplayer:RINCON_B8E937BDB4D401400' with UDN 'RINCON_B8E937BDB4D401400'
2015-05-20 23:00:24 [DEBUG] [.b.s.handler.ZonePlayerHandler:124  ] - Creating a ZonePlayerHandler for thing 'sonos:zoneplayer:RINCON_B8E937BDB4D401400'
2015-05-20 23:00:24 [DEBUG] [.b.s.handler.ZonePlayerHandler:171  ] - Discovered UDN 'RINCON_B8E937BDB4D401400' for thing 'sonos:zoneplayer:RINCON_B8E937BDB4D401400'
2015-05-20 23:00:24 [ERROR] [.c.thing.internal.ThingManager:390  ] - Exception occured while calling handler: Could not update status, because callback is missingjava.lang.IllegalStateException: Could not update status, because callback is missing
    at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.updateStatus(BaseThingHandler.java:303)
    at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.updateStatus(BaseThingHandler.java:330)
    at org.openhab.binding.sonos.handler.ZonePlayerHandler.thingDiscovered(ZonePlayerHandler.java:173)
    at org.eclipse.smarthome.config.discovery.internal.DiscoveryServiceRegistryImpl.addDiscoveryListener(DiscoveryServiceRegistryImpl.java:140)
    at org.openhab.binding.sonos.handler.ZonePlayerHandler.<init>(ZonePlayerHandler.java:131)
    at org.openhab.binding.sonos.internal.SonosHandlerFactory.createHandler(SonosHandlerFactory.java:84)
    at org.eclipse.smarthome.core.thing.binding.BaseThingHandlerFactory.registerHandler(BaseThingHandlerFactory.java:103)
    at org.eclipse.smarthome.core.thing.internal.ThingManager.registerHandler(ThingManager.java:385)
    at org.eclipse.smarthome.core.thing.internal.ThingManager.registerHandler(ThingManager.java:352)
    at org.eclipse.smarthome.core.thing.internal.ThingManager.thingAdded(ThingManager.java:281)
    at org.eclipse.smarthome.core.thing.internal.ThingRegistryImpl.notifyTrackers(ThingRegistryImpl.java:154)

2015-05-20 23:00:24 [DEBUG] [.c.c.r.AbstractManagedProvider:62   ] - Added new element to ManagedThingProvider.
2015-05-20 23:00:24 [DEBUG] [.c.c.r.AbstractManagedProvider:62   ] - Added new element to ManagedItemProvider.
2015-05-20 23:00:24 [DEBUG] [.c.t.internal.ThingLinkManager:309  ] - Assigning linked group item 'sonos_zoneplayer_RINCON_B8E937BDB4D401400' to thing 'sonos:zoneplayer:RINCON_B8E937BDB4D401400'.
2015-05-20 23:00:24 [DEBUG] [.c.c.r.AbstractManagedProvider:62   ] - Added new element to ManagedItemThingLinkProvider.
2015-05-20 23:00:24 [DEBUG] [.c.c.r.AbstractManagedProvider:62   ] - Added new element to ManagedItemProvider.
2015-05-20 23:00:25 [DEBUG] [.c.t.internal.ThingLinkManager:298  ] - Adding linked item 'sonos_zoneplayer_RINCON_B8E937BDB4D401400_control' to channel 'sonos:zoneplayer:RINCON_B8E937BDB4D401400:control'.
2015-05-20 23:00:25 [DEBUG] [.c.c.r.AbstractManagedProvider:62   ] - Added new element to ManagedItemChannelLinkProvider.
2015-05-20 23:00:25 [DEBUG] [.c.c.r.AbstractManagedProvider:62   ] - Added new element to ManagedItemProvider.
2015-05-20 23:00:25 [DEBUG] [.c.t.internal.ThingLinkManager:298  ] - Adding linked item 'sonos_zoneplayer_RINCON_B8E937BDB4D401400_currentalbum' to channel 'sonos:zoneplayer:RINCON_B8E937BDB4D401400:currentalbum'.
2015-05-20 23:00:25 [DEBUG] [.c.c.r.AbstractManagedProvider:62   ] - Added new element to ManagedItemChannelLinkProvider.
2015-05-20 23:00:25 [DEBUG] [.c.c.r.AbstractManagedProvider:62   ] - Added new element to ManagedItemProvider.
2015-05-20 23:00:25 [DEBUG] [.c.t.internal.ThingLinkManager:298  ] - Adding linked item 'sonos_zoneplayer_RINCON_B8E937BDB4D401400_currentartist' to channel 'sonos:zoneplayer:RINCON_B8E937BDB4D401400:currentartist'.
2015-05-20 23:00:25 [DEBUG] [.c.c.r.AbstractManagedProvider:62   ] - Added new element to ManagedItemChannelLinkProvider.
2015-05-20 23:00:25 [DEBUG] [.c.c.r.AbstractManagedProvider:62   ] - Added new element to ManagedItemProvider.
2015-05-20 23:00:26 [DEBUG] [.c.t.internal.ThingLinkManager:298  ] - Adding linked item 'sonos_zoneplayer_RINCON_B8E937BDB4D401400_currenttitle' to channel 'sonos:zoneplayer:RINCON_B8E937BDB4D401400:currenttitle'.
2015-05-20 23:00:26 [DEBUG] [.c.c.r.AbstractManagedProvider:62   ] - Added new element to ManagedItemChannelLinkProvider.
2015-05-20 23:00:26 [DEBUG] [.c.c.r.AbstractManagedProvider:62   ] - Added new element to ManagedItemProvider.
2015-05-20 23:00:26 [DEBUG] [.c.t.internal.ThingLinkManager:298  ] - Adding linked item 'sonos_zoneplayer_RINCON_B8E937BDB4D401400_volume' to channel 'sonos:zoneplayer:RINCON_B8E937BDB4D401400:volume'.

The Device ist showing up in PaperUI inbox and can be added as a thing, but it seems that the state stays uninitialised an it cannot be controlled.

**Comment by kaikreuzer** [comment]
I will have a try tomorrow, thanks for reporting the issue!

**Comment by hmerk** [comment]
Funny Things happening here,

Wenn I add the Sonos Play:1 as a thing from inbox, it is not reacting.
After a restart of oh2, it reacts on comands and shows actual volume settings, but no current title is shown.

**Comment by kaikreuzer** [comment]
Thanks for the info, sounds like some kind of lifecycle problem…

**Comment by kaikreuzer** [comment]
@hmerk Could you check, if this fix works for you?
@kgoderis Please check if you are fine with this code change!

**Comment by kgoderis** [comment]
mmh…. Has this to do with https://bugs.eclipse.org/bugs/show_bug.cgi?id=465762 <https://bugs.eclipse.org/bugs/show_bug.cgi?id=465762> ?

**Comment by kaikreuzer** [comment]
Not really, because #465762 is fixed already!

> Am 21 May 2015 um 09:22 schrieb kgoderis <notifications@github.com>:
> 
> 
> mmh…. Has this to do with https://bugs.eclipse.org/bugs/show_bug.cgi?id=465762 <https://bugs.eclipse.org/bugs/show_bug.cgi?id=465762> ?
>

**Comment by hmerk** [comment]
@kaikreuzer 
Yes, it is working now. Thanks for the quick fix.
