### ISSUE TITLE
[rfxcom] Sending command to misconfigured device renders RFXCOM bridge unresponsive

### ISSUE THREAD

**Issue by seime** [openhab/openhab-addons#2394]
Device configuration for a RFY device which worked fine in the march(?) version of openhab1 causes an error in the rfxcom transceiver which returns a message the binding cannot understand. This renders the binding "dead", silently not *transmitting* new commands to the transceiver (receiving seems to continue working)

## Expected Behavior
The bridge should continue dispatch new messages to the transceiver

## Current Behavior
No more messages can be sent

## Log

Init of bridge:
```
2017-06-24 10:01:42.484 [DEBUG] [g.rfxcom.handler.RFXComBridgeHandler] - Message received: Raw data = 140100010253100008060001031C04524658434F4D, Packet type = INTERFACE_MESSAGE, Seq number = 1, Sub type = RESPONSE, Command = GET_STATUS, Transceiver type = _433_92MHZ_TRANSCEIVER, Hardware version = 0.1, Firmware type = unknown, Firmware version = 16, Output power = 0dBm, Undecoded packets = false, RFU6 packets = false, Byron SX packets packets (433.92) = false, RSL packets packets (433.92) = false, Lighting4 packets (433.92) = false, FineOffset / Viking (433.92) packets = false, Rubicson (433.92) packets = false, AE (433.92) packets = false, BlindsT1/T2/T3 (433.92) packets = false, BlindsT0 (433.92) packets = false, ProGuard (868.35 FSK) packets = false, FS20/Legrand CAD (868.35/433.92) packets = false, La Crosse (433.92/868.30) packets = true, Hideki/UPM (433.92) packets = false, AD LightwaveRF (433.92) packets = false, Mertik (433.92) packets = false, Visonic (315/868.95) packets = false, ATI (433.92) packets = false, Oregon Scientific (433.92) packets = false, Meiantech (433.92) packets = false, HomeEasy EU (433.92) packets = false, AC (433.92) packets = true, ARC (433.92) packets = true, X10 (310/433.92) packets = false, HomeConfort (433.92) packets = false, KEELOQ (433.92/868.95) packets = false
2017-06-24 10:01:42.501 [DEBUG] [g.rfxcom.handler.RFXComBridgeHandler] - RFXCOM transceiver/receiver type: _433_92MHZ_TRANSCEIVER, hw version: 0.1, fw version: 16
2017-06-24 10:01:42.505 [DEBUG] [g.rfxcom.handler.RFXComBridgeHandler] - Ignoring transceiver configuration
2017-06-24 10:01:42.507 [DEBUG] [g.rfxcom.handler.RFXComBridgeHandler] - Start receiver
```

Sending command to shutter:

```
2017-06-24 10:05:51.427 [DEBUG] [g.rfxcom.handler.RFXComBridgeHandler] - Transmitting message 'Raw data = unknown, Packet type = RFY, Seq number = 0, Sub type = RFY, Unit Id = 101011.1, Unit Code = 1, Command = DOWN, Signal level = 0'
2017-06-24 10:05:51.429 [TRACE] [rnal.connector.RFXComSerialConnector] - Send data (len=13): 0C1A0000018A93010300000000

==> /var/log/openhab2/events.log <==
2017-06-24 10:05:51.451 [ItemCommandEvent          ] - Item 'Shutter_gHovedetasje_Stue_Sofa' received command DOWN
2017-06-24 10:05:51.468 [ItemStateChangedEvent     ] - Shutter_gHovedetasje_Stue_Sofa changed from 0.0 to 100

==> /var/log/openhab2/openhab.log <==
2017-06-24 10:05:51.635 [ERROR] [g.rfxcom.handler.RFXComBridgeHandler] - Error occurred during packet receiving, data: 140101000153100008060001031C04524658434F4D
org.openhab.binding.rfxcom.internal.exceptions.RFXComUnsupportedValueException: Unsupported value '1' for Commands
	at org.openhab.binding.rfxcom.internal.messages.RFXComInterfaceMessage$Commands.fromByte(RFXComInterfaceMessage.java:92)
	at org.openhab.binding.rfxcom.internal.messages.RFXComInterfaceMessage.encodeMessage(RFXComInterfaceMessage.java:271)[205:org.openhab.binding.rfxcom:2.1.0.201706222153]
	at org.openhab.binding.rfxcom.internal.messages.RFXComInterfaceMessage.<init>(RFXComInterfaceMessage.java:211)[205:org.openhab.binding.rfxcom:2.1.0.201706222153]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)[:1.8.0_131]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)[:1.8.0_131]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)[:1.8.0_131]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)[:1.8.0_131]
	at org.openhab.binding.rfxcom.internal.messages.RFXComMessageFactory.createMessage(RFXComMessageFactory.java:130)[205:org.openhab.binding.rfxcom:2.1.0.201706222153]
	at org.openhab.binding.rfxcom.handler.RFXComBridgeHandler$MessageListener.packetReceived(RFXComBridgeHandler.java:233)[205:org.openhab.binding.rfxcom:2.1.0.201706222153]
	at org.openhab.binding.rfxcom.internal.connector.RFXComBaseConnector.sendMsgToListeners(RFXComBaseConnector.java:42)[205:org.openhab.binding.rfxcom:2.1.0.201706222153]
	at org.openhab.binding.rfxcom.internal.connector.RFXComStreamReader.run(RFXComStreamReader.java:73)[205:org.openhab.binding.rfxcom:2.1.0.201706222153]
```

## Possible Solution
Add support for command response type '1'

## Steps to Reproduce (for Bugs)
Add rfxcom item in .item file:
```
Rollershutter Shutter_gHovedetasje_Stue_Sofa "Screen sofa" <rollershutter> ( gRestoreOnStartup,gShutterStue)  {channel="rfxcom:rfy:usb0:Shutter_gHovedetasje_Stue_Sofa:shutter"}
```

Add thing in .thing file:

```
Bridge rfxcom:bridge:usb0 [ serialPort="/dev/ttyUSB0" ] {
	Thing rfy Shutter_gHovedetasje_Stue_Sofa "Shutter_gHovedetasje_Stue_Sofa" [deviceId="101011.1", subType="RFY"]
}
```

## Context
Trying to make a SOMFY shutter work in Openhab2 based on Openhab1 configuration details

## Your Environment
RPI2. 
MyOpenhabian image
Openhab2 snapshot as of 2017-06-14.

**Comment by martinvw** [comment]
The manual states: 

> 0x01 = not used.

I'll try to add a test to get some more insight in what is happening

**Comment by martinvw** [comment]
To be completely sure I contacted the creators of the RFXCOM, most of the time they are really quick, I'll keep you posted.

**Comment by seime** [comment]
When assuming 101010 is hex and then trying to send the corresponding decimal value (1052688.1) the bridge responds with 
Unsupported value '16' for Commands
.. which also breaks further sending.

**Comment by martinvw** [comment]
Maybe the community forum works better to find out the correct configuration for your device

**Comment by martinvw** [comment]
Could you post here or on the community forum the configuration you used in your old openHAB instance and what you used in the new one? Note that the (underlying) error message from the rfxcom actually means `unknown RTS remote` so it seems to your hardware is not paired with the remote. This either means that you replaced one of the hardware pieces or that you're using another device id.

**Comment by martinvw** [comment]
>  When assuming 101010 is hex and then trying to send the corresponding decimal value (1052688.1) the bridge responds with
> Unsupported value '16' for Commands

Is this also the `UP `command or did you send another command this time?

**Comment by martinvw** [comment]
I just got an user friendly idea, we could if a user tries discover (rfxcom) devices send a request to the RFXCOM to list the paired RFY devices and put those in the inbox. In that way configuring the rfy device is a know brainer if you already linked the devices.

Although this is not something which I have time/priority for, maybe @mjagdis is willing to sacrifice another evening for the greater good and the RFXCOM binding :-)

**Comment by seime** [comment]
Thanks @martinvw for your swift responses!

I assume that somewhere along the way the rfxcom binding has updated the config of the transceiver which is why it won't accept my ids for the somfy equipment anymore. (the hardware is the same and unchanged). Since I struggled quite a bit to get things running (auto discovery, usb port, definition devices in a things file etc), this one is on me. However, the bug report isn't about my misconfiguration, it is about the fact that the binding renders transmission inop until openhab is rebooted when receiving unsupported command responses.

Regarding the '16' error code; I cannot tell for sure which command I sent (UP/DOWN/STOP). It is easy reproducible though, so I can do a test tonight.

**Comment by mjagdis** [comment]
I hadn't appreciated that Rfy commands return extended responses using interface message rather than the simpler transmitter messages like everything else.

Try this:

[org.openhab.binding.rfxcom-2.1.0-SNAPSHOT.zip](https://github.com/openhab/openhab2-addons/files/1102908/org.openhab.binding.rfxcom-2.1.0-SNAPSHOT.zip)

**Comment by seime** [comment]
Tried the updated binding @mjagdis , it correctly decodes the response message but it throws openhab into an infinite loop talking to the transceiver:

```
2017-06-26 20:53:17.338 [DEBUG] [g.rfxcom.handler.RFXComBridgeHandler] - Transmitting message 'Raw data = unknown, Packet type = RFY, Seq number = 0, Sub type = RFY, Unit Id = 101011.1, Unit Code = 1, Command = DOWN, Signal level = 0'
2017-06-26 20:53:17.339 [TRACE] [rnal.connector.RFXComSerialConnector] - Send data (len=13): 0C1A0000018A93010300000000
2017-06-26 20:53:17.497 [DEBUG] [g.rfxcom.handler.RFXComBridgeHandler] - Message received: Raw data = 140101000153100008060001031C04524658434F4D, Packet type = INTERFACE_MESSAGE, Seq number = 0, Sub type = UNKNOWN_RTS_REMOTE, Command = UNSUPPORTED_COMMAND
2017-06-26 20:53:17.499 [DEBUG] [g.rfxcom.handler.RFXComBridgeHandler] - Transmitting message 'Raw data = unknown, Packet type = RFY, Seq number = 0, Sub type = RFY, Unit Id = 101011.1, Unit Code = 1, Command = DOWN, Signal level = 0'
2017-06-26 20:53:17.501 [TRACE] [rnal.connector.RFXComSerialConnector] - Send data (len=13): 0C1A0000018A93010300000000
2017-06-26 20:53:17.533 [DEBUG] [g.rfxcom.handler.RFXComBridgeHandler] - Message received: Raw data = 140101000153100008060001031C04524658434F4D, Packet type = INTERFACE_MESSAGE, Seq number = 0, Sub type = UNKNOWN_RTS_REMOTE, Command = UNSUPPORTED_COMMAND
2017-06-26 20:53:17.537 [DEBUG] [g.rfxcom.handler.RFXComBridgeHandler] - Transmitting message 'Raw data = unknown, Packet type = RFY, Seq number = 0, Sub type = RFY, Unit Id = 101011.1, Unit Code = 1, Command = DOWN, Signal level = 0'
2017-06-26 20:53:17.540 [TRACE] [rnal.connector.RFXComSerialConnector] - Send data (len=13): 0C1A0000018A93010300000000
2017-06-26 20:53:17.753 [DEBUG] [g.rfxcom.handler.RFXComBridgeHandler] - Message received: Raw data = 140101000153100008060001031C04524658434F4D, Packet type = INTERFACE_MESSAGE, Seq number = 0, Sub type = UNKNOWN_RTS_REMOTE, Command = UNSUPPORTED_COMMAND
2017-06-26 20:53:17.754 [DEBUG] [g.rfxcom.handler.RFXComBridgeHandler] - Transmitting message 'Raw data = unknown, Packet type = RFY, Seq number = 0, Sub type = RFY, Unit Id = 101011.1, Unit Code = 1, Command = DOWN, Signal level = 0'
2017-06-26 20:53:17.756 [TRACE] [rnal.connector.RFXComSerialConnector] - Send data (len=13): 0C1A0000018A93010300000000
2017-06-26 20:53:17.865 [DEBUG] [g.rfxcom.handler.RFXComBridgeHandler] - Message received: Raw data = 140101000153100008060001031C04524658434F4D, Packet type = INTERFACE_MESSAGE, Seq number = 0, Sub type = UNKNOWN_RTS_REMOTE, Command = UNSUPPORTED_COMMAND
2017-06-26 20:53:17.867 [DEBUG] [g.rfxcom.handler.RFXComBridgeHandler] - Transmitting message 'Raw data = unknown, Packet type = RFY, Seq number = 0, Sub type = RFY, Unit Id = 101011.1, Unit Code = 1, Command = DOWN, Signal level = 0'
2017-06-26 20:53:17.869 [TRACE] [rnal.connector.RFXComSerialConnector] - Send data (len=13): 0C1A0000018A93010300000000
2017-06-26 20:53:18.008 [DEBUG] [g.rfxcom.handler.RFXComBridgeHandler] - Message received: Raw data = 140101000153100008060001031C04524658434F4D, Packet type = INTERFACE_MESSAGE, Seq number = 0, Sub type = UNKNOWN_RTS_REMOTE, Command = UNSUPPORTED_COMMAND
2017-06-26 20:53:18.011 [DEBUG] [g.rfxcom.handler.RFXComBridgeHandler] - Transmitting message 'Raw data = unknown, Packet type = RFY, Seq number = 0, Sub type = RFY, Unit Id = 101011.1, Unit Code = 1, Command = DOWN, Signal level = 0'
2017-06-26 20:53:18.012 [TRACE] [rnal.connector.RFXComSerialConnector] - Send data (len=13): 0C1A0000018A93010300000000
2017-06-26 20:53:18.039 [DEBUG] [g.rfxcom.handler.RFXComBridgeHandler] - Message received: Raw data = 140101000153100008060001031C04524658434F4D, Packet type = INTERFACE_MESSAGE, Seq number = 0, Sub type = UNKNOWN_RTS_REMOTE, Command = UNSUPPORTED_COMMAND
```

**Comment by mjagdis** [comment]
Oh, I see. That's a send not a sendNext. That's what comes of trying to code while playing minecraft with a 7 year old. I'll fix it in a bit.

**Comment by mjagdis** [comment]
This should be better:

[org.openhab.binding.rfxcom-2.1.0-SNAPSHOT.zip](https://github.com/openhab/openhab2-addons/files/1103645/org.openhab.binding.rfxcom-2.1.0-SNAPSHOT.zip)

**Comment by martinvw** [comment]
@seime any updates?

**Comment by seime** [comment]
@mjagdis @martinvw 
Got to test it now. The loop is gone, and the transceiver continues to work for other devices. That is the good part. However, now Openhab silently swallows the command response. There is no warning that an error was returned from the transceiver - unless you put the binding logging in debug mode:

```
==> /var/log/openhab2/openhab.log <==
2017-06-29 21:13:30.276 [DEBUG] [binding.rfxcom.handler.RFXComHandler] - Received channel: rfxcom:rfy:usb0:Shutter_gHovedetasje_Stue_TV:shutter, command: UP
2017-06-29 21:13:30.284 [DEBUG] [g.rfxcom.handler.RFXComBridgeHandler] - Transmitting message 'Raw data = unknown, Packet type = RFY, Seq number = 0, Sub type = RFY, Unit Id = 101010.1, Unit Code = 1, Command = UP, Signal level = 0'
2017-06-29 21:13:30.303 [DEBUG] [g.rfxcom.handler.RFXComBridgeHandler] - Message received: Raw data = 140101000153100008060001031C04524658434F4D, Packet type = INTERFACE_MESSAGE, Seq number = 0, Sub type = UNKNOWN_RTS_REMOTE, Command = UNSUPPORTED_COMMAND

==> /var/log/openhab2/events.log <==
2017-06-29 21:13:30.309 [ItemCommandEvent          ] - Item 'Shutter_gHovedetasje_Stue_TV' received command UP
```

IMHO I would like to see a WARN level message in the log informing the user about the problem.

Thanks again for quick response!

**Comment by martinvw** [comment]
@mjagdis wdyt?

**Comment by mjagdis** [comment]
Is it a problem that we ignore signals from devices we know nothing about? Under what circumstances does this occur, why is it a problem, what do you think an appropriate response should be and what is the justification?

**Comment by martinvw** [comment]
I merged the technical fix, whether we should report back in another way I'll leave open for now, another PR can solve that :-)

**Comment by davidgraeff** [comment]
I'd say we are closing this now, until someone finds time and interest to provide a pull request or a related bug appears.
