### ISSUE TITLE
Compat Layer : HistoricItem.getState() return faulty value

### ISSUE THREAD

**Issue by kgoderis** [openhab/openhab-addons#270]
On OH2, with rrd4j persistence 1.7 enabled, I have the following strategy in place:

Items {
    \* : strategy = everyChange, everyDay, restoreOnStartup
}

The first time around, OH is nicely persisting all values. On a second startup, a NPE is thrown in package org.eclipse.smarthome.model.persistence.internalPersistenceManager in the code where the value is restored from persistence

java.lang.NullPointerException
    at org.eclipse.smarthome.model.persistence.internal.PersistenceManager.initialize(PersistenceManager.java:386)
    at org.eclipse.smarthome.model.persistence.internal.PersistenceManager.added(PersistenceManager.java:346)
    at org.eclipse.smarthome.model.persistence.internal.PersistenceManager.added(PersistenceManager.java:1)
    at org.eclipse.smarthome.core.internal.items.ItemRegistryImpl.allItemsChanged(ItemRegistryImpl.java:89)
    at org.eclipse.smarthome.model.item.internal.GenericItemProvider.modelChanged(GenericItemProvider.java:399)
    at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.notifyListeners(ModelRepositoryImpl.java:200)
    at org.eclipse.smarthome.model.core.internal.ModelRepositoryImpl.addOrRefreshModel(ModelRepositoryImpl.java:97)
    at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.checkFile(FolderObserver.java:240)
    at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.notifyUpdateToModelRepo(FolderObserver.java:169)
    at org.eclipse.smarthome.model.core.internal.folder.FolderObserver.updated(FolderObserver.java:150)
    at org.eclipse.equinox.internal.cm.ManagedServiceTracker$1.run(ManagedServiceTracker.java:276)
    at org.eclipse.equinox.internal.cm.SerializedTaskQueue$1.run(SerializedTaskQueue.java:36)

The relevant code is: (line 386 is the call to logger.debug()):

```
                                HistoricItem historicItem = it.next();
                                GenericItem genericItem = (GenericItem) item;
                                genericItem.removeStateChangeListener(this);
                                genericItem.setState(historicItem.getState());
                                genericItem.addStateChangeListener(this);
                                logger.debug(
                                        "Restored item state from '{}' for item '{}' -> '{}'",
                                        new Object[] {
                                                DateFormat.getDateTimeInstance()
                                                        .format(historicItem.getTimestamp()), item.getName(),
                                                historicItem.getState().toString() });
                                return;
                            }
```

In the above piece of code, the variables are resolved as follows, just before the call to logger.debug():
genericItem : gExhaustAirTemperature (Type=GroupItem, Members=0, State=null, Label=null, Category=null)
historicItem : Jun 2, 2015 6:38:59 PM: gExhaustAirTemperature -> 22

It seems from the code that the call to historicItem.getState() yields null, as it is not set afterwards, and as it is the cause of the NPE (I presume toString() on null), which is strange given that it is a DecimalType of value 22. Note that the Item is a GroupItem

**Comment by kaikreuzer** [comment]
This was actually a pretty tricky situation: If you have a GroupItem that has no base type, but inherits its possible state types only from its members, this NPE happened when there were no members associated (yet) for the group. In general, I think persistence of such group items is not too relevant as their state will anyhow be recalculated if any member is added or changes its state. So my solution now simply sets the state to NULL, if there is such a situation.
