### ISSUE TITLE
[airquality] NPE while refreshing data

### ISSUE THREAD

**Issue by kevinshane** [openhab/openhab-addons#2901]
## Current Behavior
AirQuality binding changed status twice at startup

## Environment
hostOS: lubuntu 16.04 desktop with docker installed
openhab docker version: 2.1.0-amd64-debian

Hi, I am using docker openhab 2.1.0 stable version with airquality binding installed, howerver I have some strange errors: when restarting the OS, the airquality binding go online at startup and I get all the weather info, but the binding **immediately** changed from online back to initializing and then go through the process again, finally go online once again, but this time I lose all the weather info, every item changed from current value to UNDEF.. and never go back.. what's the problem here? 
here is the log:
```
2017-12-01 20:57:50.875 [ItemStateChangedEvent     ] - Aqi_Level changed from NULL to 68
2017-12-01 20:57:50.878 [ItemStateChangedEvent     ] - Aqi_Description changed from NULL to MODERATE
2017-12-01 20:57:50.882 [ItemStateChangedEvent     ] - Aqi_Pm25 changed from NULL to 68
2017-12-01 20:57:50.887 [ItemStateChangedEvent     ] - Aqi_Pm10 changed from NULL to 45
2017-12-01 20:57:50.889 [ItemStateChangedEvent     ] - Aqi_O3 changed from NULL to 53.2
2017-12-01 20:57:50.892 [ItemStateChangedEvent     ] - Aqi_No2 changed from NULL to 10.6
2017-12-01 20:57:50.895 [ItemStateChangedEvent     ] - Aqi_Co changed from NULL to 9.1
2017-12-01 20:57:50.899 [ItemStateChangedEvent     ] - Aqi_Temperature changed from NULL to 21.15
2017-12-01 20:57:50.909 [ItemStateChangedEvent     ] - Aqi_Pressure changed from NULL to 1019
2017-12-01 20:57:50.912 [ItemStateChangedEvent     ] - Aqi_Humidity changed from NULL to 68
2017-12-01 20:57:51.034 [hingStatusInfoChangedEvent] - 'airquality:aqi:home' changed from UNINITIALIZED to INITIALIZING
2017-12-01 20:57:51.087 [hingStatusInfoChangedEvent] - 'airquality:aqi:home' changed from INITIALIZING to ONLINE
2017-12-01 20:57:51.091 [ItemStateChangedEvent     ] - Aqi_Level changed from 68 to UNDEF
2017-12-01 20:57:51.095 [ItemStateChangedEvent     ] - Aqi_Description changed from MODERATE to UNDEF
2017-12-01 20:57:51.119 [ItemStateChangedEvent     ] - Aqi_Pm25 changed from 68 to UNDEF
2017-12-01 20:57:51.121 [ItemStateChangedEvent     ] - Aqi_Pm10 changed from 45 to UNDEF
2017-12-01 20:57:51.124 [ItemStateChangedEvent     ] - Aqi_No2 changed from 10.6 to UNDEF
2017-12-01 20:57:51.139 [ItemStateChangedEvent     ] - Aqi_O3 changed from 53.2 to UNDEF
2017-12-01 20:57:51.142 [ItemStateChangedEvent     ] - Aqi_Co changed from 9.1 to UNDEF
2017-12-01 20:57:51.144 [ItemStateChangedEvent     ] - Aqi_Temperature changed from 21.15 to UNDEF
2017-12-01 20:57:51.146 [ItemStateChangedEvent     ] - Aqi_Pressure changed from 1019 to UNDEF
2017-12-01 20:57:51.149 [ItemStateChangedEvent     ] - Aqi_Humidity changed from 68 to UNDEF
2017-12-01 20:57:52.129 [ERROR] [airquality.handler.AirQualityHandler] - Exception occurred during execution: null
java.lang.NullPointerException
	at org.openhab.binding.airquality.internal.json.AirQualityJsonData.getAttributions(AirQualityJsonData.java:86)[194:org.openhab.binding.airquality:2.1.0]
	at org.openhab.binding.airquality.handler.AirQualityHandler.getAirQualityData(AirQualityHandler.java:270)[194:org.openhab.binding.airquality:2.1.0]
	at org.openhab.binding.airquality.handler.AirQualityHandler.updateAirQualityData(AirQualityHandler.java:198)[194:org.openhab.binding.airquality:2.1.0]
	at org.openhab.binding.airquality.handler.AirQualityHandler.access$0(AirQualityHandler.java:196)[194:org.openhab.binding.airquality:2.1.0]
	at org.openhab.binding.airquality.handler.AirQualityHandler$1.run(AirQualityHandler.java:114)[194:org.openhab.binding.airquality:2.1.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_144]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)[:1.8.0_144]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)[:1.8.0_144]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)[:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)[:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)[:1.8.0_144]
	at java.lang.Thread.run(Thread.java:748)[:1.8.0_144]
```
I restart the docker openhab 2.1.0 and all of the sudden all items changed from UNDEF back to read the value again, in this case the value will continue to read without any problem, but the `Exception occurred during execution: null` keep showing in the log for every 30 mins (sort of 30 min, I didn't count)
would u please take a look at what's happening to cause this problem? thanks

**Comment by clinique** [comment]
@kevinshane : do you still face this error with last updates of the binding ?
