### ISSUE TITLE
[oceanic] Baud setting in things causes this error message

### ISSUE THREAD

**Issue by a4ke** [openhab/openhab-addons#3096]
# Expected Behavior
Using baud setting in things like:

Thing oceanic:softener:s1 [ port="/dev/ttyUSB4", baud=9600 , interval=60]

# Current Behavior
**This setting causes the errror:**
```
2018-01-07 23:25:45.546 [INFO ] [el.core.internal.ModelRepositoryImpl] - Refreshing model 'limex.things'
2018-01-07 23:25:45.767 [ERROR] [nal.common.AbstractInvocationHandler] - An error occurred while calling method 'ThingHandler.thingUpdated()' on 'org.openhab.binding.oceanic.handler.OceanicThingHandler@70f2dd': java.math.BigDecimal cannot be cast to java.lang.Integer
java.lang.ClassCastException: java.math.BigDecimal cannot be cast to java.lang.Integer
        at org.openhab.binding.oceanic.handler.OceanicThingHandler.initialize(OceanicThingHandler.java:89) [213:org.openhab.binding.oceanic:2.2.0]
        at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.thingUpdated(BaseThingHandler.java:228) [116:org.eclipse.smarthome.core.thing:0.10.0.b1]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
        at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:153) [109:org.eclipse.smarthome.core:0.10.0.b1]
        at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:53) [109:org.eclipse.smarthome.core:0.10.0.b1]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
        at java.lang.Thread.run(Thread.java:748) [?:?]
2018-01-07 23:25:47.453 [INFO ] [el.core.internal.ModelRepositoryImpl] - Refreshing model 'limex.things
```

# Solution
Change line 89 and 95 for bufferSize variable
https://github.com/openhab/openhab2-addons/blob/98ea4d30f9971614e91112f0969199961ee8b6c1/addons/binding/org.openhab.binding.oceanic/src/main/java/org/openhab/binding/oceanic/handler/OceanicThingHandler.java#L89

https://github.com/openhab/openhab2-addons/blob/98ea4d30f9971614e91112f0969199961ee8b6c1/addons/binding/org.openhab.binding.oceanic/src/main/java/org/openhab/binding/oceanic/handler/OceanicThingHandler.java#L95

to 
`baud = ((BigDecimal) getConfig().get(BAUD_RATE)).intValue();`
and
`bufferSize = ((BigDecimal) getConfig().get(BUFFER_SIZE)).intValue();`

# Environment
OH 2.2 on RPi 2

**Comment by kaikreuzer** [comment]
@kgoderis Could you have a look?

**Comment by ccrusius** [comment]
I'll add to this one in case is in somewhat the same place (if not, it's another bug). OpenHab 2.2.0. In the ZWave binding, for the CT100 Plus thermostat, I'm getting these every now and then.

```
2018-03-11 13:23:37.221 [ERROR] [st.core.internal.thing.ThingResource] - Exception during HTTP PUT request for update config at 'things/zwave:device:65eae4f2:
node10/config'
java.lang.ClassCastException: java.math.BigDecimal cannot be cast to java.lang.Integer
        at org.openhab.binding.zwave.handler.ZWaveThingHandler.handleConfigurationUpdate(ZWaveThingHandler.java:749) [207:org.openhab.binding.zwave:2.2.0]
        at org.eclipse.smarthome.core.thing.internal.ThingRegistryImpl.updateConfiguration(ThingRegistryImpl.java:94) [116:org.eclipse.smarthome.core.thing:0.
10.0.b1]
        at org.eclipse.smarthome.io.rest.core.internal.thing.ThingResource.updateConfiguration(ThingResource.java:413) [126:org.eclipse.smarthome.io.rest.core
:0.10.0.b1]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) [178:org
.glassfish.jersey.core.jersey-server:2.22.2]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) [178:org.glass
fish.jersey.core.jersey-server:2.22.2]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) [178:org.glas
sfish.jersey.core.jersey-server:2.22.2]
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.
java:160) [178:org.glassfish.jersey.core.jersey-server:2.22.2]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) [178:org.gla
ssfish.jersey.core.jersey-server:2.22.2]
```
(etc)

**Comment by hmerk** [comment]
closed due to inactivity
