### ISSUE TITLE
Sonos binding does not support INCREASE/DECREASE for volume

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-addons#31]
Sending INCREASE or DECREASE to the volume channel results in this exception:

```
15:07:52.533 INFO  runtime.busevents[:21] - sonos_zoneplayer_RINCON_B8E93780863601400_volume received command INCREASE
15:07:52.534 DEBUG o.e.s.c.t.i.ThingManager[:161] - Delegating command 'INCREASE' for item 'sonos_zoneplayer_RINCON_B8E93780863601400_volume' to handler for channel 'sonos:zoneplayer:RINCON_B8E93780863601400:volume'
15:07:52.542 ERROR o.e.s.c.t.i.ThingManager[:166] - Exception occured while calling handler: null
java.lang.NumberFormatException: null
    at java.lang.Integer.parseInt(Integer.java:454)
    at java.lang.Integer.valueOf(Integer.java:582)
    at org.openhab.binding.sonos.handler.ZonePlayerHandler.setVolume(ZonePlayerHandler.java:1047)
    at org.openhab.binding.sonos.handler.ZonePlayerHandler.handleCommand(ZonePlayerHandler.java:206)
    at org.eclipse.smarthome.core.thing.internal.ThingManager.receiveCommand(ThingManager.java:164)
    at org.eclipse.smarthome.core.events.AbstractEventSubscriber.receiveCommand(AbstractEventSubscriber.java:135)
    at org.eclipse.smarthome.core.events.AbstractEventSubscriber.handleEvent(AbstractEventSubscriber.java:105)
    at org.eclipse.equinox.internal.event.EventHandlerWrapper.handleEvent(EventHandlerWrapper.java:197)
    at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:197)
    at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:1)
    at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
```

**Comment by kaikreuzer** [comment]
This now works after fixing #98.
