### ISSUE TITLE
[mihome] Xiaomi does not update values after initialization

### ISSUE THREAD

**Issue by drdigital13** [openhab/openhab-addons#3632]
## Expected Behavior
After initial adding of new xiaomi Binding/Thing/Item current value is set. It should update item values on changes.

## Current Behavior
After initial adding of new xiaomi Binding/Thing/Item current value is set. Items do not update values but are all in ONLINE state.

## Steps to Reproduce (for Bugs)
I have followed all steps from https://www.openhab.org/addons/bindings/mihome documentation. I tried both manual and PaperUI config and both shows the same result. Initial correct value is set but there is no update afterwards. I should also point out that everything worked flawlessly until couple of month ago and I'm still having trouble getting it to work.

I tried following:
1. Updating Xiaomi Gateway firmware to latest version (plug-in version 2.57.2)
2. Updating OpenhabianPi from 2.1 to 2.2 and finally to 2.3
3. Clean install of OpenhabianPi 2.2 and 2.3 with only xiaomi binding (Bridge, Gateway and Motion sensor/Motion status item)
4. Adding all of available sensors which worked previously

In all the cases, I had the same result... No item value update.
  
## Your Environment
* Version used: (openhab 2.3 and xiaomi 2.3 versions)
* Operating System and version (openHABian v1.4.1)
* Network: No blocked ports, openHABian and Xiaomi Gateway in the same network
* Logs: No errors in openhab.log nor errors.log detected

**Comment by shreckxie** [comment]
I have the same issue...

**Comment by Voronenko** [comment]
For me works local gateway, but gateway which is in the different network accessed via vpn - works mentioned 5-10 mins and than no updates, also stopped +- after firmware upgrade

**Comment by yuryskaletskiy** [comment]
The similar behaviuor for me

also, I have in output log:
```
openhab> Exception in thread "Thread-41" java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.replaceNode(ConcurrentHashMap.java:1106)
	at java.util.concurrent.ConcurrentHashMap.remove(ConcurrentHashMap.java:1097)
	at org.openhab.binding.mihome.internal.handler.XiaomiBridgeHandler.defer(XiaomiBridgeHandler.java:188)
	at org.openhab.binding.mihome.internal.handler.XiaomiBridgeHandler.onDataReceived(XiaomiBridgeHandler.java:177)
	at org.openhab.binding.mihome.internal.socket.XiaomiSocket$ReceiverThread.notifyAll(XiaomiSocket.java:234)
	at org.openhab.binding.mihome.internal.socket.XiaomiSocket$ReceiverThread.receiveData(XiaomiSocket.java:210)
	at org.openhab.binding.mihome.internal.socket.XiaomiSocket$ReceiverThread.run(XiaomiSocket.java:189)
```

(using openhab Docker image 2.4.0)

**Comment by hmerk** [comment]
closed due to inactivity
