### ISSUE TITLE
[harmonyhub] Nvidia Shield buttonPress channel leads to bluetooth error

### ISSUE THREAD

**Issue by 1nn0v8** [openhab/openhab-addons#3816]
This issue appeared with the last Harmony Hub update.
Environment details:
OpenHAB: 2.3
Harmony Hub binding: 2.3
Harmony Hub devices: LG TV, Denon Receiver, **Nvidia Shield (paired via bluetooth)**

All Harmony Hub "Activity" related actions work as expected.

Nvidia Shield Item with buttonPress Channel:
`String    Harmony_Shield    "Shield Button Press"    {channel="harmonyhub:device:harmonyhub01:56523183:buttonPress" }
`
Controlling the device via Item on the sitemap works as expected. Sitemap config:
`Switch item=Harmony_Shield mappings=["Home"="Power On", "Sleep"="Sleep"]`

If I send a command to the device executed from a rule, I get an Bluetooth error from the binding on the first execution.
Example command within rule: `Harmony_Shield.sendCommand("Home")`

Error message:
```
[INFO ] [smarthome.event.ItemCommandEvent     ] - Item 'Harmony_Shield' received command Home
[INFO ] [smarthome.event.ItemStateChangedEvent] - Harmony_Shield changed from UNDEF to Home
[INFO ] [smarthome.event.ItemStateChangedEvent] - Harmony_Shield changed from Home to UNDEF
[WARN ] [ony.protocol.HarmonyXMPPTCPConnection] - Smack message parsing exception. Content: '<oa xmlns='connect.logitech.com' mime='vnd.logitech.harmony/vnd.logitech.harmony.engine?holdAction' errorcode='505' errorstring='Bluetooth device not reachable'>deviceId=46583425</oa></iq>'
net.whistlingfish.harmony.protocol.HarmonyProtocolException: Got error response [505]: Bluetooth device not reachable
        at net.whistlingfish.harmony.protocol.OAReplyProvider.parse(OAReplyProvider.java:54) [255:org.openhab.binding.harmonyhub:2.3.0]
        at net.whistlingfish.harmony.protocol.OAReplyProvider.parse(OAReplyProvider.java:19) [255:org.openhab.binding.harmonyhub:2.3.0]
        at org.jivesoftware.smack.provider.Provider.parse(Provider.java:31) [255:org.openhab.binding.harmonyhub:2.3.0]
        at org.jivesoftware.smack.util.PacketParserUtils.parseIQ(PacketParserUtils.java:632) [255:org.openhab.binding.harmonyhub:2.3.0]
        at org.jivesoftware.smack.util.PacketParserUtils.parseStanza(PacketParserUtils.java:152) [255:org.openhab.binding.harmonyhub:2.3.0]
        at net.whistlingfish.harmony.protocol.HarmonyXMPPTCPConnection.parseAndProcessStanza(HarmonyXMPPTCPConnection.java:34) [255:org.openhab.binding.harmonyhub:2.3.0]
        at org.jivesoftware.smack.tcp.XMPPTCPConnection.access$500(XMPPTCPConnection.java:149) [255:org.openhab.binding.harmonyhub:2.3.0]
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1026) [255:org.openhab.binding.harmonyhub:2.3.0]
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:980) [255:org.openhab.binding.harmonyhub:2.3.0]
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:996) [255:org.openhab.binding.harmonyhub:2.3.0]
        at java.lang.Thread.run(Thread.java:748) [?:?]
```

If I add the command a second time it works as expected on the second execution:
```
Harmony_Shield.sendCommand("Home")
Thread::sleep(100)
Harmony_Shield.sendCommand("Home")
```

Example output:
```
**[First call]**
[INFO ] [smarthome.event.ItemCommandEvent     ] - Item 'Harmony_Shield' received command Home
[INFO ] [smarthome.event.ItemStateChangedEvent] - Harmony_Shield changed from UNDEF to Home
[INFO ] [smarthome.event.ItemStateChangedEvent] - Harmony_Shield changed from Home to UNDEF
[WARN ] [ony.protocol.HarmonyXMPPTCPConnection] - Smack message parsing exception. Content: '<oa xmlns='connect.logitech.com' mime='vnd.logitech.harmony/vnd.logitech.harmony.engine?holdAction' errorcode='505' errorstring='Bluetooth device not reachable'>deviceId=46583425</oa></iq>'
net.whistlingfish.harmony.protocol.HarmonyProtocolException: Got error response [505]: Bluetooth device not reachable
        at net.whistlingfish.harmony.protocol.OAReplyProvider.parse(OAReplyProvider.java:54) [255:org.openhab.binding.harmonyhub:2.3.0]
        at net.whistlingfish.harmony.protocol.OAReplyProvider.parse(OAReplyProvider.java:19) [255:org.openhab.binding.harmonyhub:2.3.0]
        at org.jivesoftware.smack.provider.Provider.parse(Provider.java:31) [255:org.openhab.binding.harmonyhub:2.3.0]
        at org.jivesoftware.smack.util.PacketParserUtils.parseIQ(PacketParserUtils.java:632) [255:org.openhab.binding.harmonyhub:2.3.0]
        at org.jivesoftware.smack.util.PacketParserUtils.parseStanza(PacketParserUtils.java:152) [255:org.openhab.binding.harmonyhub:2.3.0]
        at net.whistlingfish.harmony.protocol.HarmonyXMPPTCPConnection.parseAndProcessStanza(HarmonyXMPPTCPConnection.java:34) [255:org.openhab.binding.harmonyhub:2.3.0]
        at org.jivesoftware.smack.tcp.XMPPTCPConnection.access$500(XMPPTCPConnection.java:149) [255:org.openhab.binding.harmonyhub:2.3.0]
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1026) [255:org.openhab.binding.harmonyhub:2.3.0]
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:980) [255:org.openhab.binding.harmonyhub:2.3.0]
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:996) [255:org.openhab.binding.harmonyhub:2.3.0]
        at java.lang.Thread.run(Thread.java:748) [?:?]
**[Second call without error]**
[INFO ] [smarthome.event.ItemCommandEvent     ] - Item 'Harmony_Shield' received command Home
[INFO ] [smarthome.event.ItemStateChangedEvent] - MM_OG_Schlafzimmer_Harmony_Shield changed from UNDEF to Home
[INFO ] [smarthome.event.ItemStateChangedEvent] - MM_OG_Schlafzimmer_Harmony_Shield changed from Home to UNDEF
```

Harmony Hub Version: 4.15.193
Environment name and version: Java 8
Operating System and version: Ubuntu 16.04.5 LTS

**Comment by sucre87** [comment]
just found this, which might be the source of the issue: [](https://community.logitech.com/s/question/0D55A00007lUFxzSAG/firmware-415193-of-the-hub-wont-hold-bluetooth-connection-upon-ending-activity
)

**Comment by hmerk** [comment]
closed due to inactivity
