### ISSUE TITLE
[netatmo] Thermostat relay/thermostats not connected

### ISSUE THREAD

**Issue by marcells** [openhab/openhab-addons#4303]
## Expected Behavior
Connecting Netatmo Thermostat relay and thermostats to OpenHAB in order to use its functionality (reading temperature, change modes, etc.).

## Current Behavior
After adding the Netatmo Thermostat relay (the thermostats do not work, too) it is online for a few seconds and changes and stays in offline mode. In the debug logs the following output occurs:

```
2018-12-02 13:10:46.429 [hingStatusInfoChangedEvent] - 'netatmo:NAPlug:11e5cc0d' changed from UNINITIALIZED to INITIALIZING
2018-12-02 13:10:46.432 [hingStatusInfoChangedEvent] - 'netatmo:NAPlug:11e5cc0d' changed from INITIALIZING to OFFLINE: Pending parent object initialization
2018-12-02 13:10:46.437 [hingStatusInfoChangedEvent] - 'netatmo:NAPlug:11e5cc0d' changed from OFFLINE: Pending parent object initialization to ONLINE
2018-12-02 13:11:16.800 [ERROR] [nternal.handler.NetatmoDeviceHandler] - Unable to connect Netatmo API : 404 Not Found
2018-12-02 13:11:16.809 [hingStatusInfoChangedEvent] - 'netatmo:NAPlug:11e5cc0d' changed from ONLINE to OFFLINE (COMMUNICATION_ERROR): Unable to connect Netatmo API : 404 Not Found
2018-12-02 13:11:47.058 [ERROR] [nternal.handler.NetatmoDeviceHandler] - Unable to connect Netatmo API : 404 Not Found
2018-12-02 13:12:17.270 [ERROR] [nternal.handler.NetatmoDeviceHandler] - Unable to connect Netatmo API : 404 Not Found
```

## Possible Solution
If you cannot reproduce the issue, maybe more debug output would be good to identify what's going on here.

## Steps to Reproduce (for Bugs)
1. Install Netatmo binding via PaperUI
2. Add Netatmo API Thing with allowed access to all modules (Weather Station, Thermostat, etc.)  via PaperUI
3. Info: My Weather Modules are automatically discovered
4. Try to manually add a Netatmo Thermostat relay by entering the necessary configuration parameters  via PaperUI
5. Netatmo relay is disconnected/`404 Not Found` occurs in the logs

## Context
I can not access my thermostat data or can change the away/schedule mode.
I tested accessing/changing my thermostat with node-red, which worked without any problem.

## Your Environment
- Version: openHAB 2.4.0 Build #1447 (Snapshot Build)
- Using the Raspberry PI image (openhabian)
- Using PaperUI for configuration

**Comment by OpenSpeedy** [comment]
Hi, I have the same problem with my Netatmo Thermostat Relay in my openHAB configuration.

For a little moment the relay switches from OFFLINE to ONLINE.
Then it's the same procedure like yours.

Here is my log:

`2018-12-22 21:30:49.920 [hingStatusInfoChangedEvent] - 'netatmo:NAPlug:' changed from UNINITIALIZED (DISABLED) to INITIALIZING`

`2018-12-22 21:30:49.941 [hingStatusInfoChangedEvent] - 'netatmo:NAPlug:' changed from INITIALIZING to OFFLINE: Pending parent object initialization`

`2018-12-22 21:30:49.948 [hingStatusInfoChangedEvent] - 'netatmo:NAPlug:' changed from OFFLINE: Pending parent object initialization to ONLINE`

`2018-12-22 21:31:20.538 [ERROR] [nternal.handler.NetatmoDeviceHandler] - Unable to connect Netatmo API : 400 Bad Request`

`2018-12-22 21:31:20.547 [hingStatusInfoChangedEvent] - 'netatmo:NAPlug:' changed from ONLINE to OFFLINE (COMMUNICATION_ERROR): Unable to connect Netatmo API : 400 Bad Request`

I have 3 therms and 1 relay in my flat.

Do you have any solution for this problem?

My other Netatmo products works perfect, only Netatmo Energy products make problems.

**Comment by slydlake** [comment]
Same Problem here. I am using the version 2.3.0.003

**Comment by TheGreatBorg** [comment]
Any new regarding this error? - I'm about to give up - I have tried everything like manual adding into files and using Paper UI and no success at all.

**Comment by lsteelandt** [comment]
Since the last 5 months, is there any news about this error ? I got it with a relay (NAPlug) associated to 3 valves (NRV). 

Extract of logs says : 
```
2019-10-27 19:59:48.194 [ERROR] [nternal.handler.NetatmoDeviceHandler] - Unable to connect Netatmo API : 404 Not Found
retrofit.RetrofitError: 404 Not Found
	at retrofit.RetrofitError.httpError(RetrofitError.java:40) ~[?:?]
	at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:388) ~[?:?]
	at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240) ~[?:?]
	at com.sun.proxy.$Proxy157.getthermostatsdata(Unknown Source) ~[?:?]
	at org.openhab.binding.netatmo.internal.handler.NetatmoBridgeHandler.getThermostatsDataBody(NetatmoBridgeHandler.java:263) ~[?:?]
	at org.openhab.binding.netatmo.internal.thermostat.NAPlugHandler.updateReadings(NAPlugHandler.java:44) ~[?:?]
	at org.openhab.binding.netatmo.internal.thermostat.NAPlugHandler.updateReadings(NAPlugHandler.java:1) ~[?:?]
	at org.openhab.binding.netatmo.internal.handler.NetatmoDeviceHandler.updateChannels(NetatmoDeviceHandler.java:117) ~[?:?]
	at org.openhab.binding.netatmo.internal.handler.NetatmoDeviceHandler.lambda$0(NetatmoDeviceHandler.java:82) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]
```

**Comment by RobinHuds** [comment]
Hi. Any news about this problem?

**Comment by 9037568** [comment]
Looks like a failure in the underlying library. Need a DEBUG or TRACE log to see if there's more information available.

**Comment by RobinHuds** [comment]
Hi.
The problem is only with the relay and the smart Valves. I add to my account the weather station in France and works well, and Paper UI automatic fins all the items.
With the relay I tried to add with Paper UI and manually using things code but displays the same failure.

Bridge netatmo:netatmoapi:home "Netatmo API" [ clientId="???", clientSecret="???", username = "???", password = "???", readStation=true, readHealthyHomeCoach=false, readThermostat=true, readWelcome=false]
{
    Thing NAPlug    Rele  "Rele"   [ id="??:??:??:??:??:??" , refreshInterval=60000 ]   
    Thing NATherm1  thermostat1 "Valvula Radiador Comedor" [ id="??:??:??:??:??:??", parentId="??:??:??:??:??:??" ]
    Thing NATherm1  thermostat3 "Valvula Radiador Habitacion 1" [ id="??:??:??:??:??:??", parentId="??:??:??:??:??:??" ]
    Thing NAMain    inside  [ id="70:ee:50:17:94:56" ]
}

This is the message than I get in the console.

10:48:21.389 [ERROR] [internal.handler.NetatmoDeviceHandler] - Unable to connect Netatmo API : 404 Not Found

![image](https://user-images.githubusercontent.com/59110503/71471090-bc0df900-27ce-11ea-93ca-b3ec77215bdf.png)

If you need anything else do not hesitate to ask me.

**Comment by 9037568** [comment]
If you can't provide the log that was already requested, there's not much that can be done here.

**Comment by RobinHuds** [comment]
Hope this is what you need.
19:22:44.795 [DEBUG] [internal.handler.NetatmoDeviceHandler] - Data aged of 116020 s
19:22:44.800 [DEBUG] [internal.handler.NetatmoDeviceHandler] - Trying to update channels on device 70:ee:50:0f:0d:cc
19:22:44.887 [ERROR] [internal.handler.NetatmoDeviceHandler] - Unable to connect Netatmo API : 404 Not Found
retrofit.RetrofitError: 404 Not Found
        at retrofit.RetrofitError.httpError(RetrofitError.java:40) ~[?:?]
        at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:388) ~[?:?]
        at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240) ~[?:?]
        at com.sun.proxy.$Proxy219.getthermostatsdata(Unknown Source) ~[?:?]
        at org.openhab.binding.netatmo.internal.handler.NetatmoBridgeHandler.getThermostatsDataBody(NetatmoBridgeHandler.java:267) ~[?:?]
        at org.openhab.binding.netatmo.internal.thermostat.NAPlugHandler.updateReadings(NAPlugHandler.java:48) ~[?:?]
        at org.openhab.binding.netatmo.internal.thermostat.NAPlugHandler.updateReadings(NAPlugHandler.java:1) ~[?:?]
        at org.openhab.binding.netatmo.internal.handler.NetatmoDeviceHandler.updateChannels(NetatmoDeviceHandler.java:121) ~[?:?]
        at org.openhab.binding.netatmo.internal.handler.NetatmoDeviceHandler.lambda$0(NetatmoDeviceHandler.java:86) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_222]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_222]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_222]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_222]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_222]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_222]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
19:22:44.925 [DEBUG] [internal.handler.NetatmoDeviceHandler] - Failed to update device 70:ee:50:0f:0d:cc readings! Skip updating channels
19:22:44.933 [DEBUG] [internal.handler.NetatmoDeviceHandler] - Updating child modules of 70:ee:50:0f:0d:cc
19:22:44.940 [DEBUG] [internal.handler.NetatmoDeviceHandler] - cancel refresh job
19:22:44.946 [DEBUG] [internal.handler.NetatmoDeviceHandler] - Scheduling update channel thread in 30 s

**Comment by 9037568** [comment]
Holy Hannah, how terrible.  I marvel at how badly error messages can be written.

>Unable to connect Netatmo API : 404 Not Found 

This occurs when the NetatmoBridgeHandler calls a proxy that calls a proxy that calls a proxy (if I've counted correctly).

In short, we're calling the underlying library which then tries to fetch a URL and gets a 404 Not Found response, then fails to record what URL it failed to retrieve. I have attempted to find the underlying code and have been unable to do so. And it further appears that the version of the library we're using (1.1.3) [doesn't even exist](https://github.com/cbornet/netatmo-swagger-decl/releases).

````
    <dependency>
      <groupId>com.github.cbornet.netatmo-swagger-api</groupId>
      <artifactId>netatmo-java-retrofit</artifactId>
      <version>1.1.3</version>
      <scope>compile</scope>
````

[This defect](https://github.com/cbornet/netatmo-swagger-decl/issues/22) may be on topic.

**Comment by ch3lmi** [comment]
Hi there,

is there any news on this topic ? Anything we could to support you ?
As it appears it is still not working.

**Comment by Olivierr92500** [comment]
Hi everyone,

It seems I have the same problem here. Openhab 2.5 with a Netatmo thermostat and a plug.
I have the API initialized OK but it is not possible to retrieve any data. Every minute I get a log error:
2020-05-29 23:34:59.918 [ERROR] [nternal.handler.NetatmoDeviceHandler] - Unable to connect Netatmo API : 400 Bad Request

My events are the following:
2020-05-28 22:28:38.046 [hingStatusInfoChangedEvent] - 'netatmo:netatmoapi:home' changed from UNINITIALIZED to INITIALIZING
2020-05-28 22:28:38.094 [hingStatusInfoChangedEvent] - 'netatmo:NAPlug:home:plugtherm' changed from UNINITIALIZED to UNINITIALIZED (BRIDGE_UNINITIALIZED)
2020-05-28 22:28:38.100 [hingStatusInfoChangedEvent] - 'netatmo:NATherm1:home:thermostat' changed from UNINITIALIZED to UNINITIALIZED (BRIDGE_UNINITIALIZED)
2020-05-28 22:28:46.577 [hingStatusInfoChangedEvent] - 'netatmo:netatmoapi:home' changed from INITIALIZING to ONLINE
2020-05-28 22:28:46.903 [hingStatusInfoChangedEvent] - 'netatmo:NAPlug:home:plugtherm' changed from UNINITIALIZED (BRIDGE_UNINITIALIZED) to INITIALIZING
2020-05-28 22:28:46.974 [hingStatusInfoChangedEvent] - 'netatmo:NAPlug:home:plugtherm' changed from INITIALIZING to OFFLINE: Pending parent object initialization
2020-05-28 22:28:47.010 [hingStatusInfoChangedEvent] - 'netatmo:NAPlug:home:plugtherm' changed from OFFLINE: Pending parent object initialization to ONLINE
2020-05-28 22:28:47.029 [hingStatusInfoChangedEvent] - 'netatmo:NATherm1:home:thermostat' changed from UNINITIALIZED (BRIDGE_UNINITIALIZED) to INITIALIZING
2020-05-28 22:28:47.067 [hingStatusInfoChangedEvent] - 'netatmo:NATherm1:home:thermostat' changed from INITIALIZING to OFFLINE: Pending parent object initialization
2020-05-28 22:28:52.384 [hingStatusInfoChangedEvent] - 'netatmo:NAPlug:home:plugtherm' changed from ONLINE to OFFLINE (COMMUNICATION_ERROR): Unable to connect Netatmo API : 400 Bad Request

My thing is defined like this:
Bridge netatmo:netatmoapi:home [ clientId="XXXXXXXXXXX", clientSecret="YYYYYYYYYYYYYY", username = "email", password = "password", readStation=false, readHealthyHomeCoach=false, readThermostat=true, readWelcome=false, readPresence=false] {
    Thing NAPlug    plugtherm  [ id="xxxxxxxxxxxxxxxxxx", refreshInterval=60000 ]
    Thing NATherm1  thermostat [ id="yyyyyyyyyyyyyy", parentId="xxxxxxxxxxxxx" ]
}

I have searched the web for any solution without success.
Does anyone have a clue about what the problem could be?

Thanks

**Comment by Olivierr92500** [comment]
If this can help, I workaround the problem with a small script. Better than nothing:

curl -X GET --silent "https://api.netatmo.com/api/homestatus?home_id=XXXXXXXXXXXXXXXXXXXXXXXX" -H "accept: application/json" -H "Authorization: Bearer yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy" | jq '.body.home.rooms[0].therm_measured_temperature'

Where XXXXXXXXXXXXXXXXXXXXXXXXX is your home_id and yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy the key you get from the netatmo API test page for your setup

The same can apply for detecting the valve status. I do not know yet if the status can be updated

**Comment by slydlake** [comment]
> If this can help, I workaround the problem with a small script. Better than nothing:
> 
> curl -X GET --silent "https://api.netatmo.com/api/homestatus?home_id=XXXXXXXXXXXXXXXXXXXXXXXX" -H "accept: application/json" -H "Authorization: Bearer yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy" | jq '.body.home.rooms[0].therm_measured_temperature'
> 
> Where XXXXXXXXXXXXXXXXXXXXXXXXX is your home_id and yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy the key you get from the netatmo API test page for your setup
> 
> The same can apply for detecting the valve status. I do not know yet if the status can be updated

Hey @Olivierr92500 

This is great, thanks! I have a problem to run the script in openHAB. in Terminal it works on my raspberry.
Did you put the command in a .sh file? or in a executeCommandLine in a rule?
Would be nice when you write me your line how you use this 😊 

Thanks!

**Comment by Olivierr92500** [comment]
@slydlake,

Yes I put it in a script files and created a thing to launch it:
Thing exec:command:netatmo_temp [command="/etc/openhab2/scripts/get_netatmo.sh status", interval=60, timeout=5]

You have to put "/etc/openhab2/scripts/get_netatmo.sh status" in your exec.whitelist file in misc

This should work.

I also had to cron a job to refresh the token that is valid only for 3 hours. Let me know if you have problem with this as well and I will post the script I wrote to refresh the key.

**Comment by slydlake** [comment]
@Olivierr92500 

Yeah this script would be nice!
Thank you very much 😊

**Comment by ch3lmi** [comment]
Thanks @Olivierr92500 for your work !

Unfortunately it's only a workaround. 

@9037568 is there any change the binding gets fixed at some point ? Anything we could to do debug and fix it. The binding as it is is pretty much useless for anything besides weather station.
The API is well available and documented at netatmo so I guess it's the binding that needs to be updated.

**Comment by Olivierr92500** [comment]
@slydlake, Here it is

**get_auth.sh:**
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games
curl -X POST -s -d "grant_type=password&client_id=xxxxxxxxxxxxxxxxxxxxxxxxxxxxx&client_secret=yyyyyyyyyyyyyyyyyyyyyyyyy&username=zzzzzzzzzzzz&password=bbbbbbbbbbb&scope=read_thermostat write_thermostat" https://api.netatmo.com/oauth2/token | jq '.access_token' | tail -c +2 > /tmp/token.txt
head -c -1 -q /etc/openhab2/scripts/command1.txt /tmp/token.txt /etc/openhab2/scripts/command2.txt > /tmp/get_temp.sh
sudo chmod a+x /tmp/get_temp.sh
sudo mv /tmp/get_temp.sh /etc/openhab2/scripts/get_netatmo.sh

**command1.txt:**
curl -X GET --silent "https://api.netatmo.com/api/homestatus?home_id=5ecd56b09c9b576f991212c6" -H "accept: application/json" -H "Authorization: Bearer

**command2.txt:**
 | jq '.body.home.rooms[0].therm_measured_temperature'

And you cron get_auth.sh to execute every other hours (the token is valid for 3h bu I did not find a way to cron every 2h50).
crontab -e
* */2 * * * /etc/openhab2/scripts/get_auth.sh

**Comment by Olivierr92500** [comment]
@slydlake, Here it is

get_auth.sh:
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games
curl -X POST -s -d "grant_type=password&client_id=xxxxxxxxxxxxxxxxxxxxxxxxxxxxx&client_secret=yyyyyyyyyyyyyyyyyyyyyyyyy&username=zzzzzzzzzzzz&password=bbbbbbbbbbb&scope=read_thermostat write_thermostat" https://api.netatmo.com/oauth2/token | jq '.access_token' | tail -c +2 > /tmp/token.txt
head -c -1 -q /etc/openhab2/scripts/command1.txt /tmp/token.txt /etc/openhab2/scripts/command2.txt > /tmp/get_temp.sh
sudo chmod a+x /tmp/get_temp.sh
sudo mv /tmp/get_temp.sh /etc/openhab2/scripts/get_netatmo.sh

command1.txt:
curl -X GET --silent "https://api.netatmo.com/api/homestatus?home_id=ggggggggggggggggggggg" -H "accept: application/json" -H "Authorization: Bearer

command2.txt:
| jq '.body.home.rooms[0].therm_measured_temperature'

And you cron get_auth.sh to execute every other hours (the token is valid for 3h bu I did not find a way to cron every 2h50).
crontab -e

    */2 * * * /etc/openhab2/scripts/get_auth.sh

**Comment by slydlake** [comment]
@Olivierr92500  Thank you, it works 😊

**Comment by lolodomo** [comment]
In case it is not unknown, the netatmo binding implements for the thermostat an old API which was deprecated by Netatmo. Netatmo introduced a new API named Energy API.
This API has to be covered first by this project: https://github.com/cbornet/netatmo-swagger-decl
An issue was opened: https://github.com/cbornet/netatmo-swagger-decl/issues/22
Then, it should be used in the binding itself.
Apparently, the old and new API are very different, that why it probably discouraged the voluntaries ;)

**Comment by lolodomo** [comment]
@clinique : I think we should mention the obsolete API for thermostat in the documentation. WDYT ?

**Comment by clinique** [comment]
Your're right. It's true that on my side if did give up a bit on netatmo because the evolution of the API tends to hide more and more direct access to modules. I suppose the old API still work for early users of Thermostat (like me) and not for the new ones, reason why I do not face this bug.

**Comment by lolodomo** [comment]
Ok, very interesting, I was asking myself if the old API was still available for old Netatmo thermostats. That means we must keep the current code by the way.
In case the new API would be supported by the binding, do you think it could be used with your thermostat or do you think that your thermostat can only work with the old API ?

**Comment by clinique** [comment]
I suppose it may work with new API also.

**Comment by Leithian** [comment]
Hi,
I just got into openHAB and wanted to link my netatmo radiator valves where I face exactly this issue. Are there any efforts yet to get the new energy API in? I'm completely new to this, but from what I see in the API it looks like there is no access to individual valves, everything is abstracted through rooms, for which you can read and set temperatures (and schedules). Since currently there are no rooms in the addon, wouldn't it be possible to implement support for these rooms as thermostat equivalents so you can set and read at least some temperatures, even if you can't access every valve?
Or is there some effort already underway, and if so do you want me to pitch in?
