### ISSUE TITLE
[airvisualnode] Json error, manufacturer changed format

### ISSUE THREAD

**Issue by Jollerprutt** [openhab/openhab-addons#4593]
Issue discussed here: https://community.openhab.org/t/airvisual-node-binding-cant-initialize-thing/62530

## Current Behavior
Inizialization of the binding fails due to changed json format.
The binding reaches the following error during initialization:
DEBUG level, but this is the only error message.
```
2019-01-07 11:34:23.860 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception: 

com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 7 column 22 path $.measurements

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224) ~[?:?]

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129) ~[?:?]

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220) ~[?:?]

	at com.google.gson.Gson.fromJson(Gson.java:887) ~[?:?]

	at com.google.gson.Gson.fromJson(Gson.java:852) ~[?:?]

	at com.google.gson.Gson.fromJson(Gson.java:801) ~[?:?]

	at com.google.gson.Gson.fromJson(Gson.java:773) ~[?:?]

	at org.openhab.binding.airvisualnode.internal.handler.AirVisualNodeHandler.pollNode(AirVisualNodeHandler.java:162) ~[?:?]

	at org.openhab.binding.airvisualnode.internal.handler.AirVisualNodeHandler.poll(AirVisualNodeHandler.java:152) ~[?:?]

	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:?]

	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[?:?]

	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[?:?]

	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[?:?]

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]

	at java.lang.Thread.run(Thread.java:748) [?:?]

Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 7 column 22 path $.measurements

	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385) ~[?:?]

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:213) ~[?:?]

	... 15 more
```
Meaning (I think) that it sucessfully processed the date-time response but came to an error when the format of the measurements section have changed.
Also several variables have changed names.
Possibly related to [AirVisual API v2](https://documenter.getpostman.com/view/507654/airvisual-api/2Fvvgg#9961e622-5933-2e43-ada4-c76b31fbdcf2)

## Possible Solution
Add behavior to identify hardware/software/json.
Add new json support.

## Your Environment
* Device version: AirVisual Pro 1.1651-KBG60F82-2
* Version used: openHAB 2.4.0-1, openhabian v1.4, AirVisual 2.4.0
* Environment name and version: Zulu Embedded 8.25.0.76-linux-aarch32hf
* System and version: RPi3B Stretch

Posting current json below (serial numbers removed).
`latest_config_measurements.json`
```
{
    "date_and_time": {
        "date": "2019/01/14",
        "time": "09:56:53",
        "timestamp": "1547459813"
    },
    "measurements": [
        {
            "co2_ppm": "1471",
            "humidity_RH": "62",
            "pm01_ugm3": "5",
            "pm10_ugm3": "12",
            "pm25_AQICN": "10",
            "pm25_AQIUS": "29",
            "pm25_ugm3": "7.0",
            "temperature_C": "20.4",
            "temperature_F": "68.7",
            "voc_ppb": "-1"
        }
    ],
    "serial_number": "XXXXXXX",
    "settings": {
        "follow_mode": "station",
        "followed_station": "1641",
        "is_aqi_usa": true,
        "is_concentration_showed": true,
        "is_indoor": true,
        "is_lcd_on": true,
        "is_network_time": true,
        "is_temperature_celsius": true,
        "language": "en-GB",
        "lcd_brightness": 49,
        "node_name": "Home",
        "power_saving": {
            "2slots": [
                {
                    "hour_off": 9,
                    "hour_on": 7
                },
                {
                    "hour_off": 22,
                    "hour_on": 18
                }
            ],
            "mode": "no",
            "running_time": 99,
            "yes": [
                {
                    "hour": 8,
                    "minute": 0
                },
                {
                    "hour": 21,
                    "minute": 0
                }
            ]
        },
        "sensor_mode": {
            "custom_mode_interval": 3,
            "mode": 1
        },
        "speed_unit": "m/s",
        "timezone": "Asia/Shanghai"
    },
    "status": {
        "app_version": "1.1651",
        "battery": 100,
        "datetime": 1547459813,
        "device_name": "AIRVISUAL-XXXXXXX",
        "ip_address": "192.168.3.112",
        "mac_address": "xxxxxxxxxxxx",
        "model": "20",
        "sensor_life": {
            "pm25": 1514365629119
        },
        "sensor_pm25_serial": "XXXXXXXXXXXXXXXXXXXX",
        "sync_time": 60000,
        "system_version": "KBG60F82",
        "used_memory": 2,
        "wifi_strength": 5
    }
}

```

**Comment by asoltesz** [comment]
The JSON parsing could be quickly fixed if we simply take the new format and update the binding for it.

Do we need to support the old format?

If older devices can be updated to the new firmware (thus using the new format) then it makes no sense to support the old format.

**Comment by Jollerprutt** [comment]
I think the binding should utilize the new format since the manufacturer have dropped the old format.

Preferably someone with an old device could try to update and give feedback here.
Perhaps we could make a copy of the binding and call it airvisualnode legacy so that people who can't or won't update their units can use that?

**Comment by asoltesz** [comment]
I have created a fix for the JSON parsing and also exposed PM10 and PM0.1 values that are now part of the JSON and seem to be real measurements.

A hand-crafted version that should work in OpenHAB 2.4:

https://github.com/asoltesz/openhab2-addons/releases/tag/airvisualnode-for-openhab24

Please test and let me know how it fares on your devices.

If it proves OK, I will send a pull request for inclusion in OpenHAB 2.5.

**Comment by ilveann** [comment]
I have created MR for supporting Arvisual and Airvisual Pro version via configuration: https://github.com/openhab/openhab-addons/pull/8674

**Comment by hmerk** [comment]
closed due to inactivity
