### ISSUE TITLE
[knx] Missing synchronization of access to internal data structures

### ISSUE THREAD

**Issue by mselent** [openhab/openhab-addons#4779]
## Expected Behavior
No Exceptions during normal operation. 

## Current Behavior
Sporadically, the following Exception occures:
`2019-02-02 07:27:23.843 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception: 
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1442) ~[?:?]
	at java.util.HashMap$KeyIterator.next(HashMap.java:1466) ~[?:?]
	at java.util.Collection.removeIf(Collection.java:414) ~[?:?]
	at org.openhab.binding.knx.internal.handler.DeviceThingHandler.rememberRespondingSpec(DeviceThingHandler.java:202) ~[?:?]
	at org.openhab.binding.knx.internal.handler.DeviceThingHandler.lambda$11(DeviceThingHandler.java:347) ~[?:?]
	at org.openhab.binding.knx.internal.handler.DeviceThingHandler.withKNXType(DeviceThingHandler.java:127) ~[?:?]
	at org.openhab.binding.knx.internal.handler.DeviceThingHandler.onGroupWrite(DeviceThingHandler.java:330) ~[?:?]
	at org.openhab.binding.knx.internal.client.AbstractKNXClient$1.lambda$0(AbstractKNXClient.java:107) ~[?:?]
	at org.openhab.binding.knx.internal.client.AbstractKNXClient.lambda$8(AbstractKNXClient.java:254) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]`

## Steps to Reproduce (for Bugs)
It occures sporadically and can not be reproduced.

## Context
I found that number-control or switch-control channels not allways answer knx_read requests. May be it correlates? 

## Your Environment
My KNX installation has 202 channels on one "dummy" Thing.
* Version used: KNX Binding 2.5.0.201902011705
* Environment name and version: Java8
* Operating System and version (desktop or mobile, Windows 10, Raspbian Jessie, ...): Raspbian via openHABian image

**Comment by mcjobo** [comment]
I'm getting the same exception. Afterwards openhab just blinks the lights that are connected there. 
in the Log I'm seeing that Exceptiuon 3 times and then openhab crashes. Here is my stacktrace:
2019-12-27 15:01:04.417 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception: 
java.util.ConcurrentModificationException: null
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445) ~[?:1.8.0_232]
        at java.util.HashMap$KeyIterator.next(HashMap.java:1469) ~[?:1.8.0_232]
        at java.util.Collection.removeIf(Collection.java:414) ~[?:1.8.0_232]
        at org.openhab.binding.knx.internal.handler.DeviceThingHandler.rememberRespondingSpec(DeviceThingHandler.java:202) ~[?:?]
        at org.openhab.binding.knx.internal.handler.DeviceThingHandler.lambda$11(DeviceThingHandler.java:346) ~[?:?]
        at org.openhab.binding.knx.internal.handler.DeviceThingHandler.withKNXType(DeviceThingHandler.java:127) ~[?:?]
        at org.openhab.binding.knx.internal.handler.DeviceThingHandler.onGroupWrite(DeviceThingHandler.java:329) ~[?:?]
        at org.openhab.binding.knx.internal.client.AbstractKNXClient$1.lambda$0(AbstractKNXClient.java:107) ~[?:?]
        at org.openhab.binding.knx.internal.client.AbstractKNXClient.lambda$8(AbstractKNXClient.java:256) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_232]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_232]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_232]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:1.8.0_232]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_232]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_232]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]

**Comment by hmerk** [comment]
closed due to inactivity
