### ISSUE TITLE
[mqtt] ChannelStateTests.receiveDateTimeTest failing

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-addons#5406]
```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.openhab.binding.mqtt.ChannelStateTests
[ERROR] Tests run: 12, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.874 s <<< FAILURE! - in org.openhab.binding.mqtt.ChannelStateTests
[ERROR] receiveDateTimeTest(org.openhab.binding.mqtt.ChannelStateTests)  Time elapsed: 0.672 s  <<< FAILURE!
java.lang.AssertionError:

Expected: is "2019-04-05T20:41:55.077+0100"
     but: was "2019-04-05T20:41:55.077+0200"
        at org.openhab.binding.mqtt.ChannelStateTests.receiveDateTimeTest(ChannelStateTests.java:278)

[INFO] Running org.openhab.binding.mqtt.ChannelStateTransformationTests
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.172 s - in org.openhab.binding.mqtt.ChannelStateTransformationTests
[INFO] Running org.openhab.binding.mqtt.internal.handler.GenericThingHandlerTests
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.016 s - in org.openhab.binding.mqtt.internal.handler.GenericThingHandlerTests
[INFO] Running org.openhab.binding.mqtt.mapping.MqttTopicClassMapperTests
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.078 s - in org.openhab.binding.mqtt.mapping.MqttTopicClassMapperTests
[INFO] Running org.openhab.binding.mqtt.mapping.SubscribeFieldToMQTTtopicTests
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.125 s - in org.openhab.binding.mqtt.mapping.SubscribeFieldToMQTTtopicTests
[INFO] Running org.openhab.binding.mqtt.values.ValueTests
[INFO] Tests run: 13, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 s - in org.openhab.binding.mqtt.values.ValueTests
[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   ChannelStateTests.receiveDateTimeTest:278
Expected: is "2019-04-05T20:41:55.077+0100"
     but: was "2019-04-05T20:41:55.077+0200"
[INFO]
[ERROR] Tests run: 38, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:

[INFO] openHAB Add-ons :: Bundles :: MQTT Things and Channels FAILURE [  4.013 s]

[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.1:test (default-test) on project org.openhab.binding.mqtt.generic: There are test failures.
```

**Comment by wborn** [comment]
I see the same:

```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.openhab.binding.mqtt.values.ValueTests
[INFO] Tests run: 13, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.056 s - in org.openhab.binding.mqtt.values.ValueTests
[INFO] Running org.openhab.binding.mqtt.ChannelStateTests
[ERROR] Tests run: 12, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.561 s <<< FAILURE! - in org.openhab.binding.mqtt.ChannelStateTests
[ERROR] receiveDateTimeTest(org.openhab.binding.mqtt.ChannelStateTests)  Time elapsed: 0.472 s  <<< FAILURE!
java.lang.AssertionError: 

Expected: is "2019-04-05T23:11:16.399+0100"
     but: was "2019-04-05T23:11:16.399+0200"
	at org.openhab.binding.mqtt.ChannelStateTests.receiveDateTimeTest(ChannelStateTests.java:278)

[INFO] Running org.openhab.binding.mqtt.mapping.SubscribeFieldToMQTTtopicTests
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.123 s - in org.openhab.binding.mqtt.mapping.SubscribeFieldToMQTTtopicTests
[INFO] Running org.openhab.binding.mqtt.mapping.MqttTopicClassMapperTests
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.086 s - in org.openhab.binding.mqtt.mapping.MqttTopicClassMapperTests
[INFO] Running org.openhab.binding.mqtt.internal.handler.GenericThingHandlerTests
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.15 s - in org.openhab.binding.mqtt.internal.handler.GenericThingHandlerTests
[INFO] Running org.openhab.binding.mqtt.ChannelStateTransformationTests
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.01 s - in org.openhab.binding.mqtt.ChannelStateTransformationTests
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   ChannelStateTests.receiveDateTimeTest:278 
Expected: is "2019-04-05T23:11:16.399+0100"
     but: was "2019-04-05T23:11:16.399+0200"
[INFO] 
[ERROR] Tests run: 38, Failures: 1, Errors: 0, Skipped: 0

```

**Comment by davidgraeff** [comment]
OMG That is summertime/wintertime difference
