### ISSUE TITLE
[mqtt] MqttEmbeddedBrokerServiceTest fails

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-addons#5411]
The `MqttEmbeddedBrokerServiceTest` in org.openhab.io.mqttembeddedbroker fails see logging below:

```
[INFO] --- maven-surefire-plugin:2.22.1:test (default-test) @ org.openhab.io.mqttembeddedbroker ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.openhab.io.mqttembeddedbroker.internal.MqttEmbeddedBrokerServiceTest
[main] INFO org.openhab.io.mqttembeddedbroker.internal.EmbeddedBrokerService - Broker persistence file: persist.mqtt
[main] INFO io.moquette.broker.Server - Configuring message interceptors...
[main] INFO io.moquette.interception.BrokerInterceptor - Initializing broker interceptor. InterceptorIds=[]
[main] INFO io.moquette.broker.Server - Using default SSL context creator
[main] INFO io.moquette.broker.Server - Authorizator policy io.moquette.broker.security.PermitAllAuthorizatorPolicy instance will be used
[main] INFO io.moquette.persistence.H2Builder - Initializing H2 store
[main] INFO org.openhab.io.mqttembeddedbroker.internal.EmbeddedBrokerService - Using in-memory persistence. No persistence file has been set!
[main] INFO io.moquette.broker.Server - Configuring message interceptors...
[main] INFO io.moquette.interception.BrokerInterceptor - Initializing broker interceptor. InterceptorIds=[]
[main] INFO io.moquette.broker.Server - Using default SSL context creator
[main] INFO io.moquette.broker.Server - Authorizator policy io.moquette.broker.security.PermitAllAuthorizatorPolicy instance will be used
[main] INFO io.moquette.broker.subscriptions.CTrieSubscriptionDirectory - Initializing CTrie
[main] INFO io.moquette.broker.subscriptions.CTrieSubscriptionDirectory - Initializing subscriptions store...
[main] INFO io.moquette.broker.NewNettyAcceptor - Netty is using NIO
[main] INFO io.moquette.broker.NewNettyAcceptor - Server bound to host=0.0.0.0, port=12345, protocol=TCP MQTT
[main] INFO io.moquette.broker.NewNettyAcceptor - Property websocket_port has been setted to disabled. Websocket MQTT will be disabled
[main] INFO io.moquette.broker.Server - Moquette integration has been started successfully in 100 ms
[main] INFO io.moquette.broker.Server - Adding MQTT message interceptor. InterceptorId=logger
[main] INFO io.moquette.interception.BrokerInterceptor - Adding MQTT message interceptor. InterceptorId=logger, handledMessageTypes=[class io.moquette.interception.messages.InterceptConnectMessage, class io.moquette.interception.messages.InterceptDisconnectMessage]
[main] WARN org.openhab.io.mqttembeddedbroker.internal.EmbeddedBrokerService - Embedded broker offline - Reason unknown
[main] INFO org.eclipse.smarthome.io.transport.mqtt.MqttBrokerConnection - Starting MQTT broker connection to 'localhost' with clientid embedded-mqtt-broker and file store '/home/wouter/git/openhab/openhab2-addons/bundles/org.openhab.io.mqttembeddedbroker/userdata/mqtt/localhost'
[nioEventLoopGroup-3-2] INFO io.moquette.broker.metrics.MQTTMessageLogger - C->B CONNECT <null>
[main] INFO org.eclipse.smarthome.io.transport.mqtt.MqttBrokerConnection - Starting MQTT broker connection to 'localhost' with clientid wrongCred and file store 'userdata/mqtt/localhost'
[nioEventLoopGroup-3-3] INFO io.moquette.broker.metrics.MQTTMessageLogger - C->B CONNECT <null>
[nioEventLoopGroup-3-3] ERROR io.moquette.broker.MQTTConnection - Authenticator has rejected the MQTT credentials CId=wrongCred, username=someUser
[nioEventLoopGroup-3-4] INFO io.moquette.broker.metrics.MQTTMessageLogger - C->B CONNECT <null>
[nioEventLoopGroup-3-4] ERROR io.moquette.broker.MQTTConnection - Authenticator has rejected the MQTT credentials CId=wrongCred, username=someUser
[main] INFO org.eclipse.smarthome.io.transport.mqtt.MqttBrokerConnection - Starting MQTT broker connection to 'localhost' with clientid correctCred and file store 'userdata/mqtt/localhost'
[nioEventLoopGroup-3-5] INFO io.moquette.broker.metrics.MQTTMessageLogger - C->B CONNECT <null>
[nioEventLoopGroup-3-5] INFO io.moquette.broker.metrics.MQTTMessageLogger - C->B DISCONNECT <correctCred>
[nioEventLoopGroup-3-5] INFO io.moquette.broker.metrics.MQTTMessageLogger - Channel closed <correctCred>
[nioEventLoopGroup-3-2] INFO io.moquette.broker.metrics.MQTTMessageLogger - C->B DISCONNECT <embedded-mqtt-broker>
[nioEventLoopGroup-3-2] INFO io.moquette.broker.metrics.MQTTMessageLogger - Channel closed <embedded-mqtt-broker>
[ForkJoinPool.commonPool-worker-1] INFO io.moquette.broker.Server - Unbinding integration from the configured ports
[nioEventLoopGroup-3-2] INFO io.moquette.broker.MQTTConnection - Notifying connection lost event. CId: embedded-mqtt-broker, channel: [id: 0x29e6dfe9, L:0.0.0.0/0.0.0.0:12345 ! R:/127.0.0.1:39170]
[nioEventLoopGroup-3-5] INFO io.moquette.broker.MQTTConnection - Notifying connection lost event. CId: correctCred, channel: [id: 0xcef97e14, L:0.0.0.0/0.0.0.0:12345 ! R:/127.0.0.1:39176]
[ForkJoinPool.commonPool-worker-1] INFO io.moquette.broker.NewNettyAcceptor - Waiting for worker and boss event loop groups to terminate...
[main] INFO org.openhab.io.mqttembeddedbroker.internal.EmbeddedBrokerService - Using in-memory persistence. No persistence file has been set!
[main] INFO io.moquette.broker.Server - Configuring message interceptors...
[main] INFO io.moquette.interception.BrokerInterceptor - Initializing broker interceptor. InterceptorIds=[]
[main] INFO io.moquette.broker.Server - Authorizator policy io.moquette.broker.security.PermitAllAuthorizatorPolicy instance will be used
[main] INFO io.moquette.broker.subscriptions.CTrieSubscriptionDirectory - Initializing CTrie
[main] INFO io.moquette.broker.subscriptions.CTrieSubscriptionDirectory - Initializing subscriptions store...
[main] INFO io.moquette.broker.NewNettyAcceptor - Netty is using NIO
[main] INFO io.moquette.broker.NewNettyAcceptor - Property port has been set to disabled. TCP MQTT will be disabled
[main] INFO io.moquette.broker.NewNettyAcceptor - Property websocket_port has been setted to disabled. Websocket MQTT will be disabled
[main] INFO io.moquette.broker.NewNettyAcceptor - Server bound to host=0.0.0.0, port=12345, protocol=SSL MQTT
[main] INFO io.moquette.broker.NewNettyAcceptor - Property secure_websocket_port has been set to disabled. Secure websocket MQTT will be disabled
[main] INFO io.moquette.broker.Server - Moquette integration has been started successfully in 268 ms
[main] INFO io.moquette.broker.Server - Adding MQTT message interceptor. InterceptorId=logger
[main] INFO io.moquette.interception.BrokerInterceptor - Adding MQTT message interceptor. InterceptorId=logger, handledMessageTypes=[class io.moquette.interception.messages.InterceptConnectMessage, class io.moquette.interception.messages.InterceptDisconnectMessage]
[main] WARN org.openhab.io.mqttembeddedbroker.internal.EmbeddedBrokerService - Embedded broker offline - Reason unknown
[main] INFO org.eclipse.smarthome.io.transport.mqtt.MqttBrokerConnection - Starting MQTT broker connection to 'localhost' with clientid embedded-mqtt-broker and file store 'userdata/mqtt/localhost'
[nioEventLoopGroup-5-2] INFO io.moquette.broker.metrics.MQTTMessageLogger - C->B CONNECT <null>
[nioEventLoopGroup-5-2] INFO io.moquette.broker.metrics.MQTTMessageLogger - C->B DISCONNECT <embedded-mqtt-broker>
[nioEventLoopGroup-5-2] INFO io.moquette.broker.metrics.MQTTMessageLogger - Channel closed <embedded-mqtt-broker>
[nioEventLoopGroup-5-2] INFO io.moquette.broker.MQTTConnection - Notifying connection lost event. CId: embedded-mqtt-broker, channel: [id: 0xed4503cc, L:0.0.0.0/0.0.0.0:12345 ! R:/127.0.0.1:39180]
[ERROR] Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.508 s <<< FAILURE! - in org.openhab.io.mqttembeddedbroker.internal.MqttEmbeddedBrokerServiceTest
[ERROR] testPersistence(org.openhab.io.mqttembeddedbroker.internal.MqttEmbeddedBrokerServiceTest)  Time elapsed: 0.345 s  <<< ERROR!
java.lang.IllegalArgumentException: Directory does not exist: nio:/home/wouter/git/openhab/openhab2-addons/bundles/org.openhab.io.mqttembeddedbroker/userdata [1.4.199/0]
	at org.openhab.io.mqttembeddedbroker.internal.MqttEmbeddedBrokerServiceTest.testPersistence(MqttEmbeddedBrokerServiceTest.java:167)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   MqttEmbeddedBrokerServiceTest.testPersistence:167 » IllegalArgument Directory ...
[INFO] 
[ERROR] Tests run: 3, Failures: 0, Errors: 1, Skipped: 0
```

After executing the tests there is a `userdata` dir but when I then run the tests it fails with:

```
[INFO] --- maven-surefire-plugin:2.22.1:test (default-test) @ org.openhab.io.mqttembeddedbroker ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.openhab.io.mqttembeddedbroker.internal.MqttEmbeddedBrokerServiceTest
[main] INFO org.openhab.io.mqttembeddedbroker.internal.EmbeddedBrokerService - Broker persistence file: persist.mqtt
[main] INFO io.moquette.broker.Server - Configuring message interceptors...
[main] INFO io.moquette.interception.BrokerInterceptor - Initializing broker interceptor. InterceptorIds=[]
[main] INFO io.moquette.broker.Server - Using default SSL context creator
[main] INFO io.moquette.broker.Server - Authorizator policy io.moquette.broker.security.PermitAllAuthorizatorPolicy instance will be used
[main] INFO io.moquette.persistence.H2Builder - Initializing H2 store
[main] INFO io.moquette.broker.subscriptions.CTrieSubscriptionDirectory - Initializing CTrie
[main] INFO io.moquette.broker.subscriptions.CTrieSubscriptionDirectory - Initializing subscriptions store...
[main] INFO io.moquette.broker.NewNettyAcceptor - Netty is using NIO
[main] INFO io.moquette.broker.NewNettyAcceptor - Server bound to host=0.0.0.0, port=12345, protocol=TCP MQTT
[main] INFO io.moquette.broker.NewNettyAcceptor - Property websocket_port has been setted to disabled. Websocket MQTT will be disabled
[main] INFO io.moquette.broker.Server - Moquette integration has been started successfully in 175 ms
[main] INFO io.moquette.broker.Server - Adding MQTT message interceptor. InterceptorId=logger
[main] INFO io.moquette.interception.BrokerInterceptor - Adding MQTT message interceptor. InterceptorId=logger, handledMessageTypes=[class io.moquette.interception.messages.InterceptConnectMessage, class io.moquette.interception.messages.InterceptDisconnectMessage]
[main] WARN org.openhab.io.mqttembeddedbroker.internal.EmbeddedBrokerService - Embedded broker offline - Reason unknown
[main] INFO org.eclipse.smarthome.io.transport.mqtt.MqttBrokerConnection - Starting MQTT broker connection to 'localhost' with clientid embedded-mqtt-broker and file store 'userdata/mqtt/localhost'
[nioEventLoopGroup-3-2] INFO io.moquette.broker.metrics.MQTTMessageLogger - C->B CONNECT <null>
[nioEventLoopGroup-3-2] INFO io.moquette.broker.metrics.MQTTMessageLogger - C<-B PUBREC <embedded-mqtt-broker> packetID <1>
[nioEventLoopGroup-3-2] INFO io.moquette.broker.metrics.MQTTMessageLogger - C->B PUBREL <embedded-mqtt-broker> packetID <1>
[nioEventLoopGroup-3-2] INFO io.moquette.broker.metrics.MQTTMessageLogger - C<-B PUBCOMP <embedded-mqtt-broker> packetID <1>
[nioEventLoopGroup-3-2] INFO io.moquette.broker.metrics.MQTTMessageLogger - C->B DISCONNECT <embedded-mqtt-broker>
[nioEventLoopGroup-3-2] INFO io.moquette.broker.metrics.MQTTMessageLogger - Channel closed <embedded-mqtt-broker>
[ForkJoinPool.commonPool-worker-1] INFO io.moquette.broker.Server - Unbinding integration from the configured ports
[nioEventLoopGroup-3-2] INFO io.moquette.broker.MQTTConnection - Notifying connection lost event. CId: embedded-mqtt-broker, channel: [id: 0x7c7dcdd3, L:0.0.0.0/0.0.0.0:12345 ! R:/127.0.0.1:39136]
[ForkJoinPool.commonPool-worker-1] INFO io.moquette.broker.NewNettyAcceptor - Waiting for worker and boss event loop groups to terminate...
[main] INFO io.moquette.broker.Server - Unbinding integration from the configured ports
[main] INFO io.moquette.broker.NewNettyAcceptor - Waiting for worker and boss event loop groups to terminate...
[main] INFO io.moquette.broker.NewNettyAcceptor - Metrics messages[read=4, write=3] bytes[read=83, write=0]
[ForkJoinPool.commonPool-worker-1] INFO io.moquette.broker.NewNettyAcceptor - Metrics messages[read=4, write=3] bytes[read=83, write=0]
[main] INFO io.moquette.broker.Server - Moquette integration has been stopped.
[ForkJoinPool.commonPool-worker-1] INFO io.moquette.broker.Server - Moquette integration has been stopped.
[main] INFO org.openhab.io.mqttembeddedbroker.internal.EmbeddedBrokerService - Using in-memory persistence. No persistence file has been set!
[main] INFO io.moquette.broker.Server - Configuring message interceptors...
[main] INFO io.moquette.interception.BrokerInterceptor - Initializing broker interceptor. InterceptorIds=[]
[main] INFO io.moquette.broker.Server - Using default SSL context creator
[main] INFO io.moquette.broker.Server - Authorizator policy io.moquette.broker.security.PermitAllAuthorizatorPolicy instance will be used
[main] INFO io.moquette.broker.subscriptions.CTrieSubscriptionDirectory - Initializing CTrie
[main] INFO io.moquette.broker.subscriptions.CTrieSubscriptionDirectory - Initializing subscriptions store...
[main] INFO io.moquette.broker.NewNettyAcceptor - Netty is using NIO
[main] INFO io.moquette.broker.NewNettyAcceptor - Server bound to host=0.0.0.0, port=12345, protocol=TCP MQTT
[main] INFO io.moquette.broker.NewNettyAcceptor - Property websocket_port has been setted to disabled. Websocket MQTT will be disabled
[main] INFO io.moquette.broker.Server - Moquette integration has been started successfully in 3 ms
[main] INFO io.moquette.broker.Server - Adding MQTT message interceptor. InterceptorId=logger
[main] INFO io.moquette.interception.BrokerInterceptor - Adding MQTT message interceptor. InterceptorId=logger, handledMessageTypes=[class io.moquette.interception.messages.InterceptConnectMessage, class io.moquette.interception.messages.InterceptDisconnectMessage]
[main] WARN org.openhab.io.mqttembeddedbroker.internal.EmbeddedBrokerService - Embedded broker offline - Reason unknown
[main] INFO org.eclipse.smarthome.io.transport.mqtt.MqttBrokerConnection - Starting MQTT broker connection to 'localhost' with clientid embedded-mqtt-broker and file store 'userdata/mqtt/localhost'
[nioEventLoopGroup-5-2] INFO io.moquette.broker.metrics.MQTTMessageLogger - C->B CONNECT <null>
[main] INFO org.eclipse.smarthome.io.transport.mqtt.MqttBrokerConnection - Starting MQTT broker connection to 'localhost' with clientid wrongCred and file store 'userdata/mqtt/localhost'
[nioEventLoopGroup-5-3] INFO io.moquette.broker.metrics.MQTTMessageLogger - C->B CONNECT <null>
[nioEventLoopGroup-5-3] ERROR io.moquette.broker.MQTTConnection - Authenticator has rejected the MQTT credentials CId=wrongCred, username=someUser
[nioEventLoopGroup-5-4] INFO io.moquette.broker.metrics.MQTTMessageLogger - C->B CONNECT <null>
[nioEventLoopGroup-5-4] ERROR io.moquette.broker.MQTTConnection - Authenticator has rejected the MQTT credentials CId=wrongCred, username=someUser
[main] INFO org.eclipse.smarthome.io.transport.mqtt.MqttBrokerConnection - Starting MQTT broker connection to 'localhost' with clientid correctCred and file store 'userdata/mqtt/localhost'
[nioEventLoopGroup-5-5] INFO io.moquette.broker.metrics.MQTTMessageLogger - C->B CONNECT <null>
[nioEventLoopGroup-5-5] INFO io.moquette.broker.metrics.MQTTMessageLogger - C->B DISCONNECT <correctCred>
[nioEventLoopGroup-5-5] INFO io.moquette.broker.metrics.MQTTMessageLogger - Channel closed <correctCred>
[nioEventLoopGroup-5-5] INFO io.moquette.broker.MQTTConnection - Notifying connection lost event. CId: correctCred, channel: [id: 0xe50ff847, L:0.0.0.0/0.0.0.0:12345 ! R:/127.0.0.1:39146]
[nioEventLoopGroup-5-2] INFO io.moquette.broker.metrics.MQTTMessageLogger - C->B DISCONNECT <embedded-mqtt-broker>
[nioEventLoopGroup-5-2] INFO io.moquette.broker.metrics.MQTTMessageLogger - Channel closed <embedded-mqtt-broker>
[nioEventLoopGroup-5-2] INFO io.moquette.broker.MQTTConnection - Notifying connection lost event. CId: embedded-mqtt-broker, channel: [id: 0x468048d6, L:0.0.0.0/0.0.0.0:12345 ! R:/127.0.0.1:39140]
[ForkJoinPool.commonPool-worker-1] INFO io.moquette.broker.Server - Unbinding integration from the configured ports
[ForkJoinPool.commonPool-worker-1] INFO io.moquette.broker.NewNettyAcceptor - Waiting for worker and boss event loop groups to terminate...
[main] INFO org.openhab.io.mqttembeddedbroker.internal.EmbeddedBrokerService - Using in-memory persistence. No persistence file has been set!
[main] INFO io.moquette.broker.Server - Configuring message interceptors...
[main] INFO io.moquette.interception.BrokerInterceptor - Initializing broker interceptor. InterceptorIds=[]
[main] INFO io.moquette.broker.Server - Authorizator policy io.moquette.broker.security.PermitAllAuthorizatorPolicy instance will be used
[main] INFO io.moquette.broker.subscriptions.CTrieSubscriptionDirectory - Initializing CTrie
[main] INFO io.moquette.broker.subscriptions.CTrieSubscriptionDirectory - Initializing subscriptions store...
[main] INFO io.moquette.broker.NewNettyAcceptor - Netty is using NIO
[main] INFO io.moquette.broker.NewNettyAcceptor - Property port has been set to disabled. TCP MQTT will be disabled
[main] INFO io.moquette.broker.NewNettyAcceptor - Property websocket_port has been setted to disabled. Websocket MQTT will be disabled
[main] INFO io.moquette.broker.NewNettyAcceptor - Server bound to host=0.0.0.0, port=12345, protocol=SSL MQTT
[main] INFO io.moquette.broker.NewNettyAcceptor - Property secure_websocket_port has been set to disabled. Secure websocket MQTT will be disabled
[main] INFO io.moquette.broker.Server - Moquette integration has been started successfully in 212 ms
[main] INFO io.moquette.broker.Server - Adding MQTT message interceptor. InterceptorId=logger
[main] INFO io.moquette.interception.BrokerInterceptor - Adding MQTT message interceptor. InterceptorId=logger, handledMessageTypes=[class io.moquette.interception.messages.InterceptConnectMessage, class io.moquette.interception.messages.InterceptDisconnectMessage]
[main] WARN org.openhab.io.mqttembeddedbroker.internal.EmbeddedBrokerService - Embedded broker offline - Reason unknown
[main] INFO org.eclipse.smarthome.io.transport.mqtt.MqttBrokerConnection - Starting MQTT broker connection to 'localhost' with clientid embedded-mqtt-broker and file store 'userdata/mqtt/localhost'
[nioEventLoopGroup-7-2] INFO io.moquette.broker.metrics.MQTTMessageLogger - C->B CONNECT <null>
[nioEventLoopGroup-7-2] INFO io.moquette.broker.metrics.MQTTMessageLogger - C->B DISCONNECT <embedded-mqtt-broker>
[nioEventLoopGroup-7-2] INFO io.moquette.broker.metrics.MQTTMessageLogger - Channel closed <embedded-mqtt-broker>
[nioEventLoopGroup-7-2] INFO io.moquette.broker.MQTTConnection - Notifying connection lost event. CId: embedded-mqtt-broker, channel: [id: 0x6ce0878e, L:0.0.0.0/0.0.0.0:12345 ! R:/127.0.0.1:39150]
[ERROR] Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 7.81 s <<< FAILURE! - in org.openhab.io.mqttembeddedbroker.internal.MqttEmbeddedBrokerServiceTest
[ERROR] testPersistence(org.openhab.io.mqttembeddedbroker.internal.MqttEmbeddedBrokerServiceTest)  Time elapsed: 4.792 s  <<< FAILURE!
java.lang.AssertionError: 

Expected: is <1>
     but: was <0>
	at org.openhab.io.mqttembeddedbroker.internal.MqttEmbeddedBrokerServiceTest.testPersistence(MqttEmbeddedBrokerServiceTest.java:190)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   MqttEmbeddedBrokerServiceTest.testPersistence:190 
Expected: is <1>
     but: was <0>
[INFO] 
[ERROR] Tests run: 3, Failures: 1, Errors: 0, Skipped: 0
```

**Comment by martinvw** [comment]
This is a test that is in the way of enabling unit-tests in the normal build.

**Comment by J-N-K** [comment]
If you run the test a third time it succeeds. 

The first failure can also be observed in the Homeassistant and Homie tests: the `userdata` directory is not available when the embedded broker is initialized. I can fix that by creating those directories prior to the broker initialization, but is that the way to go?

**Comment by martinvw** [comment]
If you can configure it such that it is ignored or just in the target directory (which I would prefer) that would be okay I think.

My theory would be that it creates the empty data folder the first time but the test actually  requires some message to be there, so that is why it succeeds only the third time

**Comment by martinvw** [comment]
This look fine since #5778, thanks @J-N-K
