### ISSUE TITLE
[boschindego] IndegoInvalidCommandException: The request failed with error: HTTP/1.1 500

### ISSUE THREAD

**Issue by nokia001** [openhab/openhab-addons#5447]
Hello,

this error happens, when the command change to 1=Mow.

```
 b2019-04-12 08:06:51.237 [WARN ] [.internal.handler.BoschIndegoHandler] - An error occurred
de.zazaz.iot.bosch.indego.IndegoInvalidCommandException: The request failed with error: HTTP/1.1 500 
        at de.zazaz.iot.bosch.indego.IndegoController.doPutRequest(IndegoController.java:308) ~[?:?]
        at de.zazaz.iot.bosch.indego.IndegoController.sendCommand(IndegoController.java:190) ~[?:?]
        at org.openhab.binding.boschindego.internal.handler.BoschIndegoHandler.poll(BoschIndegoHandler.java:128) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
        at java.lang.Thread.run(Thread.java:748) [?:?]
```

Operation System: Gentoo
Openhab2.4

**Comment by jpk8201** [comment]
I have the same problem

**Comment by hmerk** [comment]
closed due to inactivity
