### ISSUE TITLE
[groheondus] Unknown response with code 404

### ISSUE THREAD

**Issue by mstjerna** [openhab/openhab-addons#5504]
## Expected Behavior
When trying to add the "GROHE ONDUS Account" from the PapperUI i get:

```
2019-04-24 07:45:57.379 [hingStatusInfoChangedEvent] - 'groheondus:account:f07f65f2' changed from UNKNOWN to UNINITIALIZED (HANDLER_INITIALIZING_ERROR): Unknown response with code 404

==> /var/log/openhab2/openhab.log <==

2019-04-24 07:45:57.377 [ERROR] [core.thing.internal.ThingManagerImpl] - Exception occurred while initializing handler of thing 'groheondus:account:f07f65f2': Unknown response with code 404

```

I have tried using the per-packed version as well as the latest JAR files from GIT but the problem is the same:
org.openhab.binding.groheondus-2.4.0-SNAPSHOT.jar
org.openhab.binding.groheondus-2.5.0-SNAPSHOT.jar

## Your Environment
openhab2  -2.4.0-1 

1x
SenseGuard
Firmware 01.15.z22.0400.0101

3x
Sense
Firmware 1547

**Comment by FlorianSW** [comment]
This is kind of a known issue. Can I guess, that you Grohe account is kind of a new one? If so, then you unfortunately can't login with a plain username/password combo anymore, at least not in the way it is implemented in the underlying library.

This should, however, be fixed with #5209 or probably with https://github.com/FlorianSW/grohe-ondus-api-java/pull/6 :) See also the issue in the libraries repo: https://github.com/FlorianSW/grohe-ondus-api-java/issues/1 :)

**Comment by FlorianSW** [comment]
Does this problem still occurs with the latest snapshot? #5218 should already be included there :)

**Comment by mstjerna** [comment]
@FlorianSW 
Still some issue. Updated to the latest snapshot release added/removed the plugin but still se some issues with a 404...

`2019-09-12 06:17:25.124 [hingStatusInfoChangedEvent] - 'groheondus:account:9055834a' changed from UNKNOWN to UNINITIALIZED (HANDLER_INITIALIZING_ERROR): Unknown response with code 404
==> /var/log/openhab2/openhab.log <==
2019-09-12 06:17:25.134 [ERROR] [core.thing.internal.ThingManagerImpl] - Exception occurred while initializing handler of thing 'groheondus:account:9055834a': Unknown response with code 404

java.lang.IllegalArgumentException: Unknown response with code 404
	at org.grohe.ondus.api.actions.LoginAction.lambda$getToken$3(LoginAction.java:25) ~[?:?]'
	at java.util.Optional.orElseThrow(Optional.java:290) ~[?:?]
	at org.grohe.ondus.api.actions.LoginAction.getToken(LoginAction.java:24) ~[?:?]
	at org.grohe.ondus.api.OndusService.login(OndusService.java:45) ~[?:?]
	at org.grohe.ondus.api.OndusService.login(OndusService.java:37) ~[?:?]
	at org.openhab.binding.groheondus.internal.handler.GroheOndusAccountHandler.initialize(GroheOndusAccountHandler.java:69) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor75.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
	at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:152) [133:org.openhab.core:2.5.0.201909061712]
	at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:53) [133:org.openhab.core:2.5.0.201909061712]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]`

**Comment by mstjerna** [comment]
@FlorianSW 
I see that the documentation has updated a looot... Sorry for that, let me check and get back after reading this :-)

**Comment by mstjerna** [comment]
@FlorianSW 

Some progress for me now :-)
All the Temp/Humidity sensors are now working but not the main "Water Sensor"
It just states: HANDLER_CONFIGURATION_PENDING
Any suggestions on this?


2019-10-10 08:05:11.066 [home.event.InboxAddedEvent] - Discovery Result with UID 'groheondus:senseguard:69333e4d-c27c-45b6-9b52-0656b3910ccf' has been added.

2019-10-10 08:05:11.067 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'groheondus:senseguard:69333e4d-c27c-45b6-9b52-0656b3910ccf' to inbox.

2019-10-10 08:05:25.720 [me.event.InboxRemovedEvent] - Discovery Result with UID 'groheondus:senseguard:69333e4d-c27c-45b6-9b52-0656b3910ccf' has been removed.

2019-10-10 08:05:25.726 [hingStatusInfoChangedEvent] - 'groheondus:senseguard:69333e4d-c27c-45b6-9b52-0656b3910ccf' changed from UNINITIALIZED to UNINITIALIZED (HANDLER_CONFIGURATION_PENDING)

**Comment by FlorianSW** [comment]
Sorry for the long delay here :( I'll take a look into it in the next days. Did you use the UI to configure the things? If not, can you please provide the thing condfg (without credentials) and the item configuration?

**Comment by mstjerna** [comment]
@FlorianSW  I managed to get it working with items file instead of the UI. :-)
Just one question the water consumption, how is it represented? I can't figure it out in compaction to the official app...

**Comment by FlorianSW** [comment]
Sorry for not responding faster (again) :(

> Just one question the water consumption, how is it represented? I can't figure it out in compaction to the official app...

What exactly do you mean? The waterconsumption channel gives you the sum of all withdrawels for the configured timeframe (default is one day/24 hours) :)

Can you give some more details about what you get and what you expect? :)

**Comment by hmerk** [comment]
closed due to inactivity
