### ISSUE TITLE
[hueemulation] Always logs warnings/stacktraces at startup

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-addons#5622]
Whenever I start openHAB with the Demo package installed the hueemulation add-on logs the following warnings/stacktraces:

```
[WARN ] [mulation.internal.HueEmulationService] - The UPnP Server service has not been started!

...

[WARN ] [hueemulation.internal.upnp.UpnpServer] - Upnp server: Address test failed
java.util.concurrent.CompletionException: java.lang.IllegalStateException: Cannot restart thread
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:961) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) [?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:561) [?:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:580) [?:?]
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:?]
Caused by: java.lang.IllegalStateException: Cannot restart thread
	at org.openhab.io.hueemulation.internal.upnp.HueEmulationConfigWithRuntime.startNow(HueEmulationConfigWithRuntime.java:96) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952) ~[?:?]
	... 9 more

...

Exception in thread "upnp-main-28" java.lang.NullPointerException
	at org.openhab.io.hueemulation.internal.rest.StatusResource.remoteDeviceRemoved(StatusResource.java:227)
	at org.jupnp.registry.RemoteItems$4.run(RemoteItems.java:234)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)


```

**Comment by kaikreuzer** [comment]
I am only seeing the warnings:
```
23:34:14.132 [WARN ] [hueemulation.internal.upnp.UpnpServer] - Upnp server: Address test failed
```
but no stacktraces of NPEs.
@davidgraeff Could you have a look at what's causing this?

**Comment by davidgraeff** [comment]
It highly depends on the upnp devices in ones own network. The upnp device is not null annotated so I needed to turn off null checks for the implemented upnp interface methods (`@NonNullByDefault({})`). And apparently some methods still return null depending on what a device response contains, I thought I had ironed those null issues out.
