### ISSUE TITLE
[Homekit]  NPE Exception thrown continuously 

### ISSUE THREAD

**Issue by digitaldan** [openhab/openhab-addons#5645]
## Current Behavior

After enabling the homekit binding, initially it works.  After some amount of time, this could be 10 mins or even an hour, the homekit functionality ceases to work ( Home apps show devices are "not responding" ).   Aditionally i see this message in my logs , hundreds of times:

```
2019-05-26 09:10:20.677 [INFO ] [impl.connections.SubscriptionManager] - Publishing changes for 1928283748
2019-05-26 09:10:20.679 [INFO ] [impl.connections.SubscriptionManager] - Publishing changes for 1928283748
2019-05-26 09:10:20.682 [ERROR] [impl.connections.SubscriptionManager] - Failed to create new event message
java.lang.NullPointerException: null
	at com.beowulfe.hap.impl.connections.SubscriptionManager.publish(SubscriptionManager.java:98) ~[?:?]
	at com.beowulfe.hap.impl.connections.SubscriptionManager.lambda$addSubscription$0(SubscriptionManager.java:37) ~[?:?]
	at org.openhab.io.homekit.internal.HomekitAccessoryUpdater.lambda$1(HomekitAccessoryUpdater.java:55) ~[?:?]
	at org.eclipse.smarthome.core.items.GenericItem$1.run(GenericItem.java:262) [133:org.openhab.core:2.5.0.201905172320]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]
```
This has also been reported on the community forums as well. https://community.openhab.org/t/homekit-the-unsetitemregistry-method-has-thrown-an-exception/70942/5?u=digitaldan

## Possible Solution

I am guessing that the callback here https://github.com/openhab/openhab2-addons/blob/4ff0808f1859038ff88d9b39a9819f8018866ff4/bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitAccessoryUpdater.java#L55 is null, and i could submit a patch that checks for that, but my guess is that would not be solving the core issue of why its null. 

## Steps to Reproduce (for Bugs)

1.  Enable devices in homekit
2. Let run for awhile

## Your Environment

* Version used: (e.g., openhab and addon versions)
openHAB nightly build May 19th (2.5.0.201905191816) 

* Environment name and version (e.g. Chrome 39, node.js 5.4, Java 8, ...):
openjdk version "1.8.0_152"
OpenJDK Runtime Environment (Zulu Embedded 8.25.0.76-linux-aarch32hf) (build 1.8.0_152-b76)
OpenJDK Client VM (Zulu Embedded 8.25.0.76-linux-aarch32hf) (build 25.152-b76, mixed mode, Evaluation)
* Operating System and version (desktop or mobile, Windows 10, Raspbian Jessie, ...):
Debian Jessie, asus tinkerboard

**Comment by J-N-K** [comment]
Will have a look

**Comment by J-N-K** [comment]
The root cause is outside of openHAB in the HAP-java library. It requests a subscription with a null callback. I‘ll check how to catch that as early as possible, but it has to be fixed somewhere else.

**Comment by digitaldan** [comment]
I was wondering if the problem is related to something like how we unregister items and possibly are not removing the callback properly , so its null next time a state is published on the item.  But i don't know the code very well, so was kinda a wild guess.

**Comment by J-N-K** [comment]
Good point. There is at least another flaw (not sure if that is the real problem. When we unset the bridge, we do not remove the accessories from that bridge. Maybe that is, why unsubscribe is not called and an old subscription stays in place. Anyway, I have seen subscribe-requests with a null-callback, that seems to be wrong.

**Comment by J-N-K** [comment]
I have prepared a fix, would you like to try it? The new .jar is [here](https://janessa.me/esh/org.openhab.io.homekit-fix-npe.jar).

You can update your installation with `bundle:update <number> https://janessa.me/esh/org.openhab.io.homekit-fix-npe.jar` and probably restarting that bundle.

**Comment by grzegorz914** [comment]
Hello,

after update OH 2.5.0 to build 1602, 1603 some warn appear during OH start:

```
2019-05-29 08:08:05.006 [INFO ] [internal.service.FeaturesServiceImpl] -   org.openhab.io.homekit/2.5.0.201905290440
2019-05-29 08:08:05.153 [WARN ] [mekit.internal.HomekitChangeListener] - Could not add device PrzedpokojMalyTemp: Thermostats need a CurrentTemperature accessory
2019-05-29 08:08:05.157 [WARN ] [mekit.internal.HomekitChangeListener] - Could not add device LazienkaPietroTemp: Thermostats need a CurrentTemperature accessory
2019-05-29 08:08:05.161 [WARN ] [mekit.internal.HomekitChangeListener] - Could not add device PrzedpokojDuzyTemp: Thermostats need a CurrentTemperature accessory
2019-05-29 08:08:05.166 [WARN ] [mekit.internal.HomekitChangeListener] - Could not add device CwuTemp: Thermostats need a CurrentTemperature accessory
2019-05-29 08:08:05.172 [WARN ] [mekit.internal.HomekitChangeListener] - Could not add device BiuroTemp: Thermostats need a CurrentTemperature accessory
2019-05-29 08:08:05.175 [WARN ] [mekit.internal.HomekitChangeListener] - Could not add device PokojTemp: Thermostats need a CurrentTemperature accessory
2019-05-29 08:08:05.180 [WARN ] [mekit.internal.HomekitChangeListener] - Could not add device SypialniaTemp: Thermostats need a CurrentTemperature accessory
2019-05-29 08:08:05.186 [WARN ] [mekit.internal.HomekitChangeListener] - Could not add device JadalniaTemp: Thermostats need a CurrentTemperature accessory
2019-05-29 08:08:05.191 [WARN ] [mekit.internal.HomekitChangeListener] - Could not add device GarderobaTemp: Thermostats need a CurrentTemperature accessory
2019-05-29 08:08:05.196 [WARN ] [mekit.internal.HomekitChangeListener] - Could not add device KamilaTemp: Thermostats need a CurrentTemperature accessory
2019-05-29 08:08:05.202 [WARN ] [mekit.internal.HomekitChangeListener] - Could not add device LazienkaParterTemp: Thermostats need a CurrentTemperature accessory
2019-05-29 08:08:05.208 [WARN ] [mekit.internal.HomekitChangeListener] - Could not add device KuchniaTemp: Thermostats need a CurrentTemperature accessory
2019-05-29 08:08:05.215 [WARN ] [mekit.internal.HomekitChangeListener] - Could not add device SalonTemp: Thermostats need a CurrentTemperature accessory
```

**Comment by J-N-K** [comment]
Please open a different issue for that, it is not related. Include your item-configuration and if possible the version it worked with before. Thanks
