### ISSUE TITLE
[wifiled] Cannot notify the DiscoveryListener on Thing discovered event Error

### ISSUE THREAD

**Issue by jsetton** [openhab/openhab-addons#5679]
## Current Behavior
Error is generated when the binding is initiated after updating to latest snapshot build.

## Context
Error is not impacting the binding if things already configured. I didn't confirm but I believe this could cause an issue for new setup that want to use the Paper UI Inbox.

## Your Environment
Docker 2.5.0-SNAPSHOT Build 1603

## Logs
```
2019-06-02 20:38:15.039 [DEBUG] [org.openhab.binding.wifiled         ] - BundleEvent STARTING - org.openhab.binding.wifiled
2019-06-02 20:38:15.067 [DEBUG] [org.openhab.binding.wifiled         ] - ServiceEvent REGISTERED - {org.eclipse.smarthome.core.thing.binding.ThingHandlerFactory}={service.id=364, service.bundleid=253, service.s
cope=bundle, component.name=org.openhab.binding.wifiled.internal.WiFiLEDHandlerFactory, component.id=214} - org.openhab.binding.wifiled
2019-06-02 20:38:15.099 [DEBUG] [org.openhab.binding.wifiled         ] - ServiceEvent REGISTERED - {org.eclipse.smarthome.config.discovery.DiscoveryService}={service.id=365, service.bundleid=253, service.scope=
bundle, component.name=org.openhab.binding.wifiled.internal.discovery.WiFiLEDDiscoveryService, component.id=215} - org.openhab.binding.wifiled
2019-06-02 20:38:15.114 [DEBUG] [al.discovery.WiFiLEDDiscoveryService] - Start WiFi LED background discovery
2019-06-02 20:38:15.128 [DEBUG] [al.discovery.WiFiLEDDiscoveryService] - Try to discover all WiFi LED devices
2019-06-02 20:38:15.148 [DEBUG] [org.openhab.binding.wifiled         ] - BundleEvent STARTED - org.openhab.binding.wifiled
2019-06-02 20:38:15.155 [DEBUG] [al.discovery.WiFiLEDDiscoveryService] - Disover message sent: '48 46 2d 41 31 31 41 53 53 49 53 54 48 52 45 41 44'
2019-06-02 20:38:15.410 [DEBUG] [al.discovery.WiFiLEDDiscoveryService] - Disover response received: 'x.x.x.x,xxxxxxxxxxxx,xxxxx-xxxxx' [31 39 32 2e 31 36 38 2e 31 2e 31 xx xx xx xx xx xx xx xx xx xx xx xx
 xx xx xx 2c 41 4b 30 30 31 2d 5a 4a 31 30 30 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00]
2019-06-02 20:38:15.414 [DEBUG] [al.discovery.WiFiLEDDiscoveryService] - Adding a new WiFi LED with IP 'x.x.x.x' and MAC 'xxxxxxxxxxxx' to inbox
2019-06-02 20:38:15.455 [ERROR] [nternal.DiscoveryServiceRegistryImpl] - Cannot notify the DiscoveryListener org.eclipse.smarthome.config.discovery.internal.PersistentInbox on Thing discovered event!
java.lang.IllegalArgumentException: Invalid type '{org.openhab.binding.wifiled.internal.handler.AbstractWiFiLEDDriver.Protocol}' of configuration value!
        at org.eclipse.smarthome.config.core.ConfigUtil.normalizeType(ConfigUtil.java:80) ~[?:?]
        at org.eclipse.smarthome.config.discovery.internal.PersistentInbox.synchronizeConfiguration(PersistentInbox.java:274) ~[?:?]
        at org.eclipse.smarthome.config.discovery.internal.PersistentInbox.add(PersistentInbox.java:243) ~[?:?]
        at org.eclipse.smarthome.config.discovery.internal.PersistentInbox.thingDiscovered(PersistentInbox.java:377) ~[?:?]
        at org.eclipse.smarthome.config.discovery.internal.DiscoveryServiceRegistryImpl$1.run(DiscoveryServiceRegistryImpl.java:265) ~[?:?]
        at org.eclipse.smarthome.config.discovery.internal.DiscoveryServiceRegistryImpl$1.run(DiscoveryServiceRegistryImpl.java:1) ~[?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
        at org.eclipse.smarthome.config.discovery.internal.DiscoveryServiceRegistryImpl.thingDiscovered(DiscoveryServiceRegistryImpl.java:262) ~[?:?]
        at org.eclipse.smarthome.config.discovery.AbstractDiscoveryService.thingDiscovered(AbstractDiscoveryService.java:281) ~[?:?]
        at org.openhab.binding.wifiled.internal.discovery.WiFiLEDDiscoveryService.discover(WiFiLEDDiscoveryService.java:117) ~[?:?]
        at org.openhab.binding.wifiled.internal.discovery.WiFiLEDDiscoveryService.lambda$0(WiFiLEDDiscoveryService.java:64) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
        at java.lang.Thread.run(Thread.java:748) [?:?]
2019-06-02 20:38:15.681 [DEBUG] [al.discovery.WiFiLEDDiscoveryService] - Thing discovered 'DiscoveryResult [thingUID=wifiled:wifiled:xxxxxxxxxxxx, properties={protocol=LD382A, ip=x.x.x.x}, representationProperty=null, flag=NEW, label=xxxxx-xxxxx, bridgeUID=null, ttl=-1, timestamp=1559522295444]'
```

**Comment by J-N-K** [comment]
Which version did you use before?

**Comment by jsetton** [comment]
I unfortunately don't recall exactly but I would say a snapshot build from late March.

**Comment by openhab-5iver** [comment]
I experience this too (just happened with S1627). Before this started happening, which many build ago, I recall that my wifiled devices were being autodiscovered, even though they already existed. Maybe another bug... maybe related.

**Comment by jsetton** [comment]
FYI, this is still happening as of 2.5.2-SNAPSHOT Build 47.

**Comment by hmerk** [comment]
closed due to inactivity
