### ISSUE TITLE
Network binding exception when mDNS device is offline

### ISSUE THREAD

**Issue by idkpmiller** [openhab/openhab-addons#5714]
I am a big user of mDNS so if the device is not attached to the network the broadcast to locate the device will not resolve so the network binging needs to make the item unreachable. rather than throw an exception as it does in version 2.4.0

Chatting in the forum it is quite possible that this exact issue has already been resolved in the 2.5.0 version of network binding and if so then please close the ticket as already solved.

Thank you
Paul

```
2019-06-08 19:31:46.028 [ERROR] [work.internal.handler.NetworkHandler] - Configuration for hostname is faulty
java.net.UnknownHostException: BR3SO4.local: Name or service not known
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method) ~[?:?]
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929) ~[?:?]
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324) ~[?:?]
	at java.net.InetAddress.getAllByName0(InetAddress.java:1277) ~[?:?]
	at java.net.InetAddress.getAllByName(InetAddress.java:1193) ~[?:?]
	at java.net.InetAddress.getAllByName(InetAddress.java:1127) ~[?:?]
	at java.net.InetAddress.getByName(InetAddress.java:1077) ~[?:?]
	at org.openhab.binding.network.internal.PresenceDetection.setHostname(PresenceDetection.java:101) ~[278:org.openhab.binding.network:2.4.0]
	at org.openhab.binding.network.internal.handler.NetworkHandler.initialize(NetworkHandler.java:160) [278:org.openhab.binding.network:2.4.0]
	at org.openhab.binding.network.internal.handler.NetworkHandler.initialize(NetworkHandler.java:211) [278:org.openhab.binding.network:2.4.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
	at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:153) [103:org.eclipse.smarthome.core:0.10.0.oh240]
	at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:53) [103:org.eclipse.smarthome.core:0.10.0.oh240]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]
2019-06-08 19:31:46.039 [WARN ] [core.thing.internal.ThingManagerImpl] - Initializing handler for thing 'network:pingdevice:7222a1a2' takes more than 5000ms.
2019-06-08 19:31:56.092 [ERROR] [work.internal.handler.NetworkHandler] - Configuration for hostname is faulty
java.net.UnknownHostException: BR3SO3.local: Name or service not known
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method) ~[?:?]
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929) ~[?:?]
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324) ~[?:?]
	at java.net.InetAddress.getAllByName0(InetAddress.java:1277) ~[?:?]
	at java.net.InetAddress.getAllByName(InetAddress.java:1193) ~[?:?]
	at java.net.InetAddress.getAllByName(InetAddress.java:1127) ~[?:?]
	at java.net.InetAddress.getByName(InetAddress.java:1077) ~[?:?]
	at org.openhab.binding.network.internal.PresenceDetection.setHostname(PresenceDetection.java:101) ~[278:org.openhab.binding.network:2.4.0]
	at org.openhab.binding.network.internal.handler.NetworkHandler.initialize(NetworkHandler.java:160) [278:org.openhab.binding.network:2.4.0]
	at org.openhab.binding.network.internal.handler.NetworkHandler.initialize(NetworkHandler.java:211) [278:org.openhab.binding.network:2.4.0]
	at sun.reflect.GeneratedMethodAccessor99.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
	at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:153) [103:org.eclipse.smarthome.core:0.10.0.oh240]
	at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:53) [103:org.eclipse.smarthome.core:0.10.0.oh240]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]
2019-06-08 19:31:56.101 [WARN ] [core.thing.internal.ThingManagerImpl] - Initializing handler for thing 'network:pingdevice:6614520a' takes more than 5000ms..
```

**Comment by wborn** [comment]
Looks like @J-N-K  already implemented a catch for this UnknownHostException in https://github.com/openhab/openhab2-addons/pull/4718. So I think it should be fixed in 2.5.0-SNAPSHOT.
