### ISSUE TITLE
[kodi] Unable to report throwable to websocket

### ISSUE THREAD

**Issue by 5iver** [openhab/openhab-addons#5715]
I use Kodi on FireTV devices that are not normally powered unless in use. After upgrading to S1608, I'm receiving this warning every 10s for each Kodi that is not online...

```
2019-06-12 01:51:42.483 [WARN ] [org.eclipse.jetty.websocket.common.events.JettyAnnotatedEventDriver] - Unable to report throwable to websocket (no @OnWebSocketError handler declared): org.openhab.binding.kodi.internal.protocol.KodiClientSocket$KodiWebSocketListener
java.net.NoRouteToHostException: No route to host
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
        at org.eclipse.jetty.io.SelectorManager.doFinishConnect(SelectorManager.java:355) ~[81:org.eclipse.jetty.io:9.4.18.v20190429]
        at org.eclipse.jetty.io.ManagedSelector.processConnect(ManagedSelector.java:221) [81:org.eclipse.jetty.io:9.4.18.v20190429]
        at org.eclipse.jetty.io.ManagedSelector.access$1500(ManagedSelector.java:61) [81:org.eclipse.jetty.io:9.4.18.v20190429]
        at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.processSelected(ManagedSelector.java:531) [81:org.eclipse.jetty.io:9.4.18.v20190429]
        at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.produce(ManagedSelector.java:393) [81:org.eclipse.jetty.io:9.4.18.v20190429]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produceTask(EatWhatYouKill.java:357) [93:org.eclipse.jetty.util:9.4.18.v20190429]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:181) [93:org.eclipse.jetty.util:9.4.18.v20190429]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168) [93:org.eclipse.jetty.util:9.4.18.v20190429]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126) [93:org.eclipse.jetty.util:9.4.18.v20190429]
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366) [93:org.eclipse.jetty.util:9.4.18.v20190429]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:698) [93:org.eclipse.jetty.util:9.4.18.v20190429]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:804) [93:org.eclipse.jetty.util:9.4.18.v20190429]
        at java.lang.Thread.run(Thread.java:748) [?:?]
```

**Comment by kaikreuzer** [comment]
Seems to be related to the recent Jetty upgrade. I've created https://github.com/openhab/openhab2-addons/pull/5730 for it.
