### ISSUE TITLE
[buienradar] Unhandled java.util.concurrent.TimeoutException (Buienradar API frequently takes longer than 3000ms to reply) 

### ISSUE THREAD

**Issue by shutterfreak** [openhab/openhab-addons#5735]
The buienradar binding expects the Buienradar API to return an HTTP request in 3000 milliseconds (see **BuienradarPredictionAPI.java**). However, the Buienradar API often takes longer than the timeout value before it is able to handle the request. In such cases, an unhandled exception is thrown:

> 2019-06-16 00:47:38.618 [WARN ] [uienradar.internal.BuienradarHandler] - Cannot retrieve predictions
> **java.io.IOException: java.util.concurrent.TimeoutException**: Total timeout 3000 ms elapsed
> 	at org.eclipse.smarthome.io.net.http.HttpUtil.executeUrlAndGetReponse(HttpUtil.java:259) ~[?:?]
> 	at org.eclipse.smarthome.io.net.http.HttpUtil.executeUrl(HttpUtil.java:156) ~[?:?]
> 	at org.eclipse.smarthome.io.net.http.HttpUtil.executeUrl(HttpUtil.java:131) ~[?:?]
> 	at org.eclipse.smarthome.io.net.http.HttpUtil.executeUrl(HttpUtil.java:109) ~[?:?]
> 	at org.eclipse.smarthome.io.net.http.HttpUtil.executeUrl(HttpUtil.java:90) ~[?:?]
> 	at org.openhab.binding.buienradar.internal.buienradarapi.BuienradarPredictionAPI.getPredictions(**BuienradarPredictionAPI.java:133**) ~[?:?]
> 	at org.openhab.binding.buienradar.internal.BuienradarHandler.refresh(BuienradarHandler.java:108) ~[?:?]
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
> 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:?]
> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:?]
> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:?]
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
> 	at java.lang.Thread.run(Thread.java:748) [?:?]
> Caused by: java.util.concurrent.TimeoutException: Total timeout 3000 ms elapsed
> 	at org.eclipse.jetty.client.TimeoutCompleteListener.onTimeoutExpired(TimeoutCompleteListener.java:52) ~[?:?]
> 	at org.eclipse.jetty.io.CyclicTimeout$Wakeup.run(CyclicTimeout.java:271) ~[?:?]
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:?]
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:?]
> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:?]
> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:?]
> 	... 3 more

Expected behavior: either one of:

1. Quick hack: Increase the timeout (e.g., set it to 5000 ms)
2. More elaborative solution: If the `java.util.concurrent.TimeoutException` is thrown (response not received within the predefined time), catch it by backing off for a couple seconds and retrying it (up to say max 3 times before bailing out). Optionally the back-off time interval could double after each retry.

**Comment by shutterfreak** [comment]
The TimeOutException is gone forever now, and all IO exceptions are nicely caught with an exponential retry time. Big thanks! Maybe 5 seconds is too short for a first retry when server-side congestion occurs? I'd probably go for 10 seconds, since 10s + 20s + 40s + 80s < 300s (time interval for Buienradar prediction updates).

Apart from the TimeoutException I see there's also the occasional `java.io.EOFException` that is thrown, probably when the server resets the connection as load congestion containment measure. An example is given below (but it is nicely caught by the binding):

> **2019-07-09 00:23:01.803 [WARN ] [uienradarapi.BuienradarPredictionAPI] - IO Exception when trying to retrieve Buienradar results**
> **java.io.IOException: java.util.concurrent.ExecutionException: java.io.EOFException:** HttpConnectionOverHTTP@1a10300::DecryptedEndPoint@1172940{gpsgadget.buienradar.nl/173.223.106.128:443<->/192.168.0.10:55850,OPEN,fill=-,flush=-,to=300125/0}
>         at org.eclipse.smarthome.io.net.http.HttpUtil.executeUrlAndGetReponse(HttpUtil.java:259) ~[?:?]
>         at org.eclipse.smarthome.io.net.http.HttpUtil.executeUrl(HttpUtil.java:156) ~[?:?]
>         at org.eclipse.smarthome.io.net.http.HttpUtil.executeUrl(HttpUtil.java:131) ~[?:?]
>         at org.eclipse.smarthome.io.net.http.HttpUtil.executeUrl(HttpUtil.java:109) ~[?:?]
>         at org.eclipse.smarthome.io.net.http.HttpUtil.executeUrl(HttpUtil.java:90) ~[?:?]
>         **at org.openhab.binding.buienradar.internal.buienradarapi.BuienradarPredictionAPI.getPredictions(BuienradarPredictionAPI.java:144)** ~[?:?]
>         at org.openhab.binding.buienradar.internal.BuienradarHandler.refresh(BuienradarHandler.java:134) ~[?:?]
>         at org.openhab.binding.buienradar.internal.BuienradarHandler.refresh(BuienradarHandler.java:118) ~[?:?]
>         at org.openhab.binding.buienradar.internal.BuienradarHandler.lambda$0(BuienradarHandler.java:109) ~[?:?]
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
>         at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:?]
>         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:?]
>         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:?]
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
>         at java.lang.Thread.run(Thread.java:748) [?:?]
> **Caused by: java.util.concurrent.ExecutionException: java.io.EOFException:** HttpConnectionOverHTTP@1a10300::DecryptedEndPoint@1172940{gpsgadget.buienradar.nl/173.223.106.128:443<->/192.168.0.10:55850,OPEN,fill=-,flush=-,to=300125/0}
>         at org.eclipse.jetty.client.util.FutureResponseListener.getResult(FutureResponseListener.java:118) ~[?:?]
>         at org.eclipse.jetty.client.util.FutureResponseListener.get(FutureResponseListener.java:101) ~[?:?]
>         at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:683) ~[?:?]
>         at org.eclipse.smarthome.io.net.http.HttpUtil.executeUrlAndGetReponse(HttpUtil.java:250) ~[?:?]
>         ... 15 more
> **Caused by: java.io.EOFException:** HttpConnectionOverHTTP@1a10300::DecryptedEndPoint@1172940{gpsgadget.buienradar.nl/173.223.106.128:443<->/192.168.0.10:55850,OPEN,fill=-,flush=-,to=300125/0}
>         at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.earlyEOF(HttpReceiverOverHTTP.java:338) ~[?:?]
>         at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1551) ~[?:?]
>         at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.shutdown(HttpReceiverOverHTTP.java:209) ~[?:?]
>         at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.process(HttpReceiverOverHTTP.java:147) ~[?:?]
>         at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:73) ~[?:?]
>         at org.eclipse.jetty.client.http.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:133) ~[?:?]
>         at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:155) ~[?:?]
>         at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305) ~[?:?]
>         at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103) ~[?:?]
>         at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:427) ~[?:?]
>         at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:321) ~[?:?]
>         at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:159) ~[?:?]
>         at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103) ~[?:?]
>         at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117) ~[?:?]
>         at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:698) ~[?:?]
>         at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:804) ~[?:?]
>         ... 1 more
> 2019-07-09 00:23:01.942 **[WARN ] [uienradar.internal.BuienradarHandler] - Did not get a result from buienradar. Retrying. 4 tries remaining, waiting 5 seconds.**

**Comment by shutterfreak** [comment]
The TimeOutException is still reported in openhab.log:

> **2021-06-25 07:19:12.722 [WARN ] [uienradarapi.BuienradarPredictionAPI] - IO Exception when trying to retrieve Buienradar results**
> **java.io.IOException: java.util.concurrent.TimeoutException: Total timeout 3000 ms elapsed**
>         at org.openhab.core.io.net.http.HttpUtil.executeUrlAndGetReponse(HttpUtil.java:260) ~[bundleFile:?]
>         at org.openhab.core.io.net.http.HttpUtil.executeUrl(HttpUtil.java:156) ~[bundleFile:?]
>         at org.openhab.core.io.net.http.HttpUtil.executeUrl(HttpUtil.java:131) ~[bundleFile:?]
>         at org.openhab.core.io.net.http.HttpUtil.executeUrl(HttpUtil.java:109) ~[bundleFile:?]
>         at org.openhab.core.io.net.http.HttpUtil.executeUrl(HttpUtil.java:90) ~[bundleFile:?]
>         at org.openhab.binding.buienradar.internal.buienradarapi.BuienradarPredictionAPI.getPredictions(BuienradarPredictionAPI.java:144) [bundleFile:?]
>         at org.openhab.binding.buienradar.internal.BuienradarHandler.refresh(BuienradarHandler.java:131) [bundleFile:?]
>         at org.openhab.binding.buienradar.internal.BuienradarHandler.refresh(BuienradarHandler.java:115) [bundleFile:?]
>         at org.openhab.binding.buienradar.internal.BuienradarHandler.lambda$0(BuienradarHandler.java:106) [bundleFile:?]
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
>         at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
>         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
>         at java.lang.Thread.run(Thread.java:829) [?:?]
> **Caused by: java.util.concurrent.TimeoutException: Total timeout 3000 ms elapsed**
>         at org.eclipse.jetty.client.TimeoutCompleteListener.onTimeoutExpired(TimeoutCompleteListener.java:51) ~[?:?]
>         at org.eclipse.jetty.io.CyclicTimeout$Wakeup.run(CyclicTimeout.java:282) ~[?:?]
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
>         at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
>         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
>         ... 3 more
> **2021-06-25 07:19:12.752 [WARN ] [uienradar.internal.BuienradarHandler] - Did not get a result from buienradar. Retrying. 4 tries remaining, waiting 5 seconds.**

Is there a way to:
1. increase the HTTP response timeout from 3000ms to 5000ms? That would probably lower the required number of HTTP retries to the buienradar website.
2. properly catch this IOException when no response is received when the HTTP response times out (currently after 3000ms, hopefully configurable to e.g. 5000ms).
