### ISSUE TITLE
[konnected] HTTP endpoint isn't created and binding fails

### ISSUE THREAD

**Issue by volfan6415** [openhab/openhab-addons#5749]
## Current Behavior
I have a user where the http endpoint is never registered. He has setup 2.4 on a fresh install and
He is using a version of the binding that is known to run on multiple systems.

Here is what i know:

java -version
openjdk version “1.8.0_212”
OpenJDK Runtime Environment (Zulu 8.38.0.13-CA-linux64) (build 1.8.0_212-b04)
OpenJDK 64-Bit Server VM (Zulu 8.38.0.13-CA-linux64) (build 25.212-b04, mixed mode)

CentOS Linux release 7.6.1810 (Core)

He was trying to run openhab from the docker. But he has tested inside and outside of the docker and gets the same error both times.

I know that the error is pointing to some issue with the http service endpoint not being properly registered. But as i can’t recreate the error on my end an i am at a loss to tell him what he should to do try and fix it.

Any help or guidance here would be much appreciated.

Here is the relevant log file:

```
2019-06-10 19:33:16.023 [DEBUG] [org.openhab.binding.konnected       ] - ServiceEvent REGISTERED - {org.eclipse.smarthome.config.discovery.upnp.UpnpDiscoveryParticipant}={service.id=120, service.bundleid=202, service.scope=bundle, component.name=org.openhab.binding.konnected.internal.discovery.KonnectedUPnPServer, component.id=12} - org.openhab.binding.konnected
2019-06-10 19:33:16.075 [DEBUG] [org.openhab.binding.konnected       ] - BundleEvent STARTING - org.openhab.binding.konnected
2019-06-10 19:33:16.076 [DEBUG] [org.openhab.binding.konnected       ] - BundleEvent STARTED - org.openhab.binding.konnected
2019-06-10 19:33:16.096 [DEBUG] [org.openhab.binding.konnected       ] - BundleEvent [unknown:512] - org.openhab.binding.konnected
2019-06-10 19:33:18.334 [ERROR] [org.openhab.binding.konnected       ] - bundle org.openhab.binding.konnected:2.5.0.201902010231 (202)[org.openhab.binding.konnected.internal.KonnectedHandlerFactory(13)] : The deactivate method has thrown an exception
java.lang.IllegalArgumentException: Alias [/konnected] was never registered
	at org.ops4j.pax.web.service.internal.HttpServiceStarted.unregister(HttpServiceStarted.java:321) ~[?:?]
	at org.ops4j.pax.web.service.internal.HttpServiceProxy.unregister(HttpServiceProxy.java:82) ~[?:?]
	at org.openhab.binding.konnected.internal.servlet.KonnectedHTTPServlet.deactivate(KonnectedHTTPServlet.java:96) ~[?:?]
	at org.openhab.binding.konnected.internal.KonnectedHandlerFactory.deactivate(KonnectedHandlerFactory.java:71) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
	at org.apache.felix.scr.impl.inject.methods.BaseMethod.invokeMethod(BaseMethod.java:228) ~[?:?]
	at org.apache.felix.scr.impl.inject.methods.BaseMethod.access$500(BaseMethod.java:41) ~[?:?]
	at org.apache.felix.scr.impl.inject.methods.BaseMethod$Resolved.invoke(BaseMethod.java:664) ~[?:?]
	at org.apache.felix.scr.impl.inject.methods.BaseMethod.invoke(BaseMethod.java:510) ~[?:?]
	at org.apache.felix.scr.impl.inject.methods.ActivateMethod.invoke(ActivateMethod.java:317) ~[?:?]
	at org.apache.felix.scr.impl.inject.methods.ActivateMethod.invoke(ActivateMethod.java:307) ~[?:?]
	at org.apache.felix.scr.impl.manager.SingleComponentManager.disposeImplementationObject(SingleComponentManager.java:381) ~[?:?]
	at org.apache.felix.scr.impl.manager.SingleComponentManager.deleteComponent(SingleComponentManager.java:156) ~[?:?]
	at org.apache.felix.scr.impl.manager.SingleComponentManager.ungetService(SingleComponentManager.java:985) ~[?:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse$2.run(ServiceFactoryUse.java:260) ~[?:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse$2.run(ServiceFactoryUse.java:1) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.factoryUngetService(ServiceFactoryUse.java:258) ~[?:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.ungetService(ServiceFactoryUse.java:160) ~[?:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceConsumer$2.ungetService(ServiceConsumer.java:50) ~[?:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.ungetService(ServiceRegistrationImpl.java:593) ~[?:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.ungetService(ServiceRegistry.java:540) ~[?:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.ungetService(BundleContextImpl.java:666) ~[?:?]
	at com.eclipsesource.jaxrs.publisher.internal.ResourceTracker.delegateAddService(ResourceTracker.java:48) ~[?:?]
	at com.eclipsesource.jaxrs.publisher.internal.ResourceTracker.addingService(ResourceTracker.java:40) ~[?:?]
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:941) ~[?:?]
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:870) ~[?:?]
	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256) ~[?:?]
	at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229) ~[?:?]
	at org.osgi.util.tracker.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:901) ~[?:?]
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:109) ~[?:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:920) ~[?:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230) ~[?:?]
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148) ~[?:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:862) ~[?:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:801) ~[?:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:127) ~[?:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:225) ~[?:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:469) ~[?:?]
	at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:891) ~[?:?]
	at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:877) ~[?:?]
	at org.apache.felix.scr.impl.manager.RegistrationManager.changeRegistration(RegistrationManager.java:128) ~[?:?]
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.registerService(AbstractComponentManager.java:944) ~[?:?]
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:727) ~[?:?]
	at org.apache.felix.scr.impl.manager.DependencyManager$SingleStaticCustomizer.addedService(DependencyManager.java:1053) ~[?:?]
	at org.apache.felix.scr.impl.manager.DependencyManager$SingleStaticCustomizer.addedService(DependencyManager.java:1007) ~[?:?]
	at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.customizerAdded(ServiceTracker.java:1216) ~[?:?]
	at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.customizerAdded(ServiceTracker.java:1137) ~[?:?]
	at org.apache.felix.scr.impl.manager.ServiceTracker$AbstractTracked.trackAdding(ServiceTracker.java:944) ~[?:?]
	at org.apache.felix.scr.impl.manager.ServiceTracker$AbstractTracked.track(ServiceTracker.java:880) ~[?:?]
	at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:1168) ~[?:?]
	at org.apache.felix.scr.impl.BundleComponentActivator$ListenerInfo.serviceChanged(BundleComponentActivator.java:125) ~[?:?]
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:109) ~[?:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:920) ~[?:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230) ~[?:?]
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148) ~[?:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:862) ~[?:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:801) ~[?:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:127) ~[?:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:225) ~[?:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:469) ~[?:?]
	at org.ops4j.pax.web.service.internal.Activator.updateController(Activator.java:424) ~[?:?]
	at org.ops4j.pax.web.service.internal.Activator.lambda$scheduleUpdateFactory$1(Activator.java:342) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]
2019-06-10 19:33:18.397 [DEBUG] [org.openhab.binding.konnected       ] - ServiceEvent REGISTERED - {org.eclipse.smarthome.core.thing.binding.ThingHandlerFactory}={service.id=165, service.bundleid=202, service.scope=bundle, component.name=org.openhab.binding.konnected.internal.KonnectedHandlerFactory, component.id=13} - org.openhab.binding.konnected
2019-06-10 19:33:18.432 [INFO ] [ebuilder.internal.HomeBuilderServlet] - Started Home Builder at /homebuilder
2019-06-10 19:33:18.472 [INFO ] [panel.internal.HABPanelDashboardTile] - Started HABPanel at /habpanel
2019-06-10 19:33:24.091 [INFO ] [thome.model.lsp.internal.ModelServer] - Started Language Server Protocol (LSP) service on port 5007
2019-06-10 19:33:24.778 [INFO ] [.dashboard.internal.DashboardService] - Started Dashboard at http://192.168.83.153:8080
2019-06-10 19:33:24.779 [INFO ] [.dashboard.internal.DashboardService] - Started Dashboard at https://192.168.83.153:8443
2019-06-10 19:33:25.008 [INFO ] [arthome.ui.paper.internal.PaperUIApp] - Started Paper UI at /paperui
```

**Comment by wborn** [comment]
Maybe @volfan6415 can help with this?

**Comment by kaikreuzer** [comment]
@wborn Might be difficult as he entered the issue himself...

**Comment by wborn** [comment]
You certainly have a good point there! ;-)

**Comment by volfan6415** [comment]
Yes trying to get some outside input here. Can’t figure out what is causing this error

**Comment by kaikreuzer** [comment]
@volfan6415 I've had a look at it and came up with https://github.com/openhab/openhab2-addons/pull/5764, which simplifies the code a bit.
The issue was that the servlet was only registered in the `htttpService`, if at least one thing handler was registered. If the factory was started and immediately stopped again, the servlet wasn't registered, but upon the deactivation of the factory it was tried to unregister it, which then failed.

My PR now changes the behavior in a way that the servlet is always directly registered upon factory activation - we thus should not come across that issue again.

**Comment by stiplady** [comment]
Thank you @kaikreuzer for your help with this, it was me who had the original issue that @volfan6415  was struggling with. Looking forward to testing this out and getting it all working.
