### ISSUE TITLE
[groheondus] account connection issue

### ISSUE THREAD

**Issue by TNRichard** [openhab/openhab-addons#5753]
Since some time I got no connection to ONDUS account, so all related things are broken.

In Paper UI I see for the GROHE ONDUS Account:
Status: UNINITIALIZED - HANDLER_INITIALIZING_ERROR org/apache/http/impl/client/HttpClients

I see no further info in the error log.

Used version: SNAPSHOT 2.5.0 (#1619), last updated 21.06.2019

**Comment by wborn** [comment]
Do you think this is a bug or user error @FlorianSW?

**Comment by FlorianSW** [comment]
Looking into it, doesn't look like a user error from a first glance.

**Comment by TNRichard** [comment]
If I can do something for ffurther details, give me a hint.

**Comment by TNRichard** [comment]
here is a similar issue in another binding. MAybe this gives a hint:
https://community.openhab.org/t/sml-reader-how-to-integrate/20206/163

**Comment by FlorianSW** [comment]
Not sure what the root problem is here, however, I think I've the same problem when setting up the IDE from scratch. bnd can not resolve all required dependencies of the ondus-api library, which basically depends on `org.apache.httpcomponents` `httpcore` and `httpclient`. This can be worked around by adding both of the osgi dependencies explicitly in the pom:
```
    <dependency>
      <groupId>org.apache.httpcomponents</groupId>
      <artifactId>httpcore-osgi</artifactId>
      <version>4.4.9</version>
    </dependency>
    <dependency>
      <groupId>org.apache.httpcomponents</groupId>
      <artifactId>httpclient-osgi</artifactId>
      <version>4.5.5</version>
    </dependency>
```

However, httpclient depends on `org.apache.commons.logging`:
```
Resolution failed. Capabilities satisfying the following requirements could not be found:
    [<<INITIAL>>]
      ⇒ osgi.identity: (osgi.identity=org.openhab.binding.groheondus)
          ⇒ [org.openhab.binding.groheondus version=2.5.0.201907041954]
              ⇒ osgi.wiring.package: (&(osgi.wiring.package=org.grohe.ondus.api.model)(&(version>=0.0.0)(!(version>=1.0.0))))
                  ⇒ [ondus-api version=0.0.9]
                      ⇒ osgi.wiring.package: (&(osgi.wiring.package=org.apache.http.client.methods))
                          ⇒ [org.apache.httpcomponents.httpclient version=4.5.5]
                              ⇒ osgi.wiring.package: (&(osgi.wiring.package=org.apache.commons.logging)(&(version>=1.1.0)(!(version>=1.3.0))))
```

Unfortunately there's no osgi bundle for the library, so I tried adding the non-bundled into the pom, too:
```
    <dependency>
      <groupId>commons-logging</groupId>
      <artifactId>commons-logging</artifactId>
      <version>1.2</version>
      <scope>provided</scope>
    </dependency>
```
This didn't work either (with the same error message as above), adding the library both with `mvn:` only or even by wrapping it, doesn't work either :(
```
    <feature name="openhab-binding-groheondus" description="GROHE ONDUS Binding" version="${project.version}">
        <feature>openhab-runtime-base</feature>
        <feature prerequisite="true">wrap</feature>
        <bundle dependency="true">mvn:com.fasterxml.jackson.core/jackson-core/2.9.6</bundle>
        <bundle dependency="true">mvn:com.fasterxml.jackson.core/jackson-annotations/2.9.6</bundle>
        <bundle dependency="true">mvn:com.fasterxml.jackson.core/jackson-databind/2.9.6</bundle>
        <bundle dependency="true">mvn:org.apache.httpcomponents/httpcore-osgi/4.4.9</bundle>
        <bundle dependency="true">mvn:org.apache.httpcomponents/httpclient-osgi/4.5.5</bundle>
        <bundle dependency="true">wrap:mvn:commons-logging/commons-logging/1.2</bundle>
        <bundle dependency="true">mvn:org.grohe/ondus-api/0.0.9</bundle>
        <bundle start-level="80">mvn:org.openhab.addons.bundles/org.openhab.binding.groheondus/${project.version}</bundle>
    </feature>
```
It seems I don't know enough of this stuff, especially with the osgi part, that I can solve it on my own. @wborn or @maggu2810 do you've an idea related to this?

**Comment by maggu2810** [comment]
IIRC I searched for an OSGi bundle that at least fullfill the requirements for a `org.apache.commons.logging` consumer some weeks ago and succeeded. But cannot remember (ATM) for which project this has been necessary... Will try to have a look at but it will take some time...

**Comment by maggu2810** [comment]
I assume this one could help: https://stackoverflow.com/questions/12309007/osgi-ified-apache-commons-logging

**Comment by J-N-K** [comment]
The interesting question is: why does the karaf feature check succeeds when a missing dependency is not there?

**Comment by maggu2810** [comment]
Karaf is using Pax Logging and the referenced stackoverflow page contains a comment that states this package is part of that impl.

**Comment by FlorianSW** [comment]
I wanted to work on another binding on my local environment, which also requires an external mvn-Dependency, `org.openhab.bindig.opensprinkler`. however, this one also fails while resolving the dependencies:
```
Resolution failed. Capabilities satisfying the following requirements could not be found:
    [<<INITIAL>>]
      ⇒ osgi.identity: (osgi.identity=org.openhab.binding.opensprinkler)
          ⇒ [org.openhab.binding.opensprinkler version=2.5.0.201907081555]
              ⇒ osgi.wiring.package: (&(osgi.wiring.package=com.pi4j.io.gpio)(&(version>=1.2.0)(!(version>=2.0.0))))
```

It's pretty hard for me to understand that, I even started from scratch, deleting the whole eclipse installation, all openhab repos as well as my local .m2 and .p2 cache. Then installing Eclipse with the eclipse installer and following the [IDE setup](https://www.openhab.org/docs/developer/ide/eclipse.html) steps, however the above error persists :(

I'm not sure what I'm doing wrong, but my feeling is that the mvn-bundling of external dependencies somehow doesn't work at all on my computer, no clue why. A maven build works fine :(

**Comment by J-N-K** [comment]
Try adding `com.pi4j/pi4j-core/1.2` to the dependencies. The resolver cannot automatically detect which bundle may provide the needed packages.

**Comment by FlorianSW** [comment]
Where would I add the dependency to? The pom already contains it as scope provided :)

**Comment by FlorianSW** [comment]
In order to get my local environment running again, I changed the third-party library[1] so that it does not require the httpclient and httpcomponents dependency anymore. This seems to work fine, see the PR for it. It also should fix this issue, at least I was able to connect to an account and to a GROHE SenseGuard device without any problems.

[1] This was possible in thie case, as I "own" the library as well, however, it would be great to know how this would have worked without changing the third-party library. As I said already before, I don't know enough of this OSGi stuff, and also not Apache Felix, in order to investigate this deeply, but it would be nice to see that it doesn't just create more problems, but also solutions :P

**Comment by maggu2810** [comment]
@FlorianSW We could compile against the commons logging API and need an implementation of that API at runtime. Pax Logging provides a working solution, so we could think about using the Pax Logging framework in the demo app and allow to use `org.apache.commons.logging` at compile time.

**Comment by FlorianSW** [comment]
Hmm, ok, let's see if we need to do that at some time in the future, for now it's working with removing the library.

**Comment by TNRichard** [comment]
Hi @FlorianSW ,
I see your fix and tried the snapshot build  openHAB 2.5.0~S1645-1 (Build #1645).
But stilll get the same result for the Grohe Ondus account: 
"Status: UNINITIALIZED - HANDLER_INITIALIZING_ERROR org/apache/http/impl/client/HttpClients"

**Comment by FlorianSW** [comment]
Ok, where did you download the jar from and what openHAB version do you use?

**Comment by TNRichard** [comment]
I'm using **openHAB 2.5.0~S1645-1 (Build #1645)**. Updating regularly by apt-get.
Recently I stopped openHAB, cleaned cache and restarted openHAB.

In the log I now see:
_2019-07-26 16:44:22.506 [hingStatusInfoChangedEvent] - 'groheondus:account:6a1a10b5' changed from UNINITIALIZED to INITIALIZING

2019-07-26 16:44:22.601 [hingStatusInfoChangedEvent] - 'groheondus:account:6a1a10b5' changed from INITIALIZING to UNKNOWN

==> /var/log/openhab2/openhab.log <==

2019-07-26 16:44:22.821 [ERROR] [nal.common.AbstractInvocationHandler] - An error occurred while calling method 'ThingHandler.initialize()' on 'org.openhab.binding.groheondus.internal.handler.GroheOndusAccountHandler@1ed8cb5': org/apache/http/impl/client/HttpClients

java.lang.NoClassDefFoundError: org/apache/http/impl/client/HttpClients

	at org.grohe.ondus.api.client.ApiClient.<init>(ApiClient.java:30) ~[?:?]

	at org.grohe.ondus.api.OndusService.login(OndusService.java:34) ~[?:?]

	at org.openhab.binding.groheondus.internal.handler.GroheOndusAccountHandler.initialize(GroheOndusAccountHandler.java:73) ~[?:?]

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]

	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]

	at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:153) [140:org.openhab.core:2.5.0.201907230301]

	at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:53) [140:org.openhab.core:2.5.0.201907230301]

	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]

	at java.lang.Thread.run(Thread.java:748) [?:?]

Caused by: java.lang.ClassNotFoundException: org.apache.http.impl.client.HttpClients cannot be found by ondus-api_0.0.9

	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:433) ~[?:?]

	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:395) ~[?:?]

	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:387) ~[?:?]

	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:150) ~[?:?]

	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:?]

	... 13 more

==> /var/log/openhab2/events.log <==

2019-07-26 16:44:22.935 [hingStatusInfoChangedEvent] - 'groheondus:account:6a1a10b5' changed from UNKNOWN to UNINITIALIZED (HANDLER_INITIALIZING_ERROR): org/apache/http/impl/client/HttpClients

==> /var/log/openhab2/openhab.log <==

2019-07-26 16:44:22.925 [ERROR] [core.thing.internal.ThingManagerImpl] - Exception occurred while initializing handler of thing 'groheondus:account:6a1a10b5': org/apache/http/impl/client/HttpClients

java.lang.NoClassDefFoundError: org/apache/http/impl/client/HttpClients

	at org.grohe.ondus.api.client.ApiClient.<init>(ApiClient.java:30) ~[?:?]

	at org.grohe.ondus.api.OndusService.login(OndusService.java:34) ~[?:?]

	at org.openhab.binding.groheondus.internal.handler.GroheOndusAccountHandler.initialize(GroheOndusAccountHandler.java:73) ~[?:?]

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]

	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]

	at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:153) [140:org.openhab.core:2.5.0.201907230301]

	at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:53) [140:org.openhab.core:2.5.0.201907230301]

	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]

	at java.lang.Thread.run(Thread.java:748) [?:?]

Caused by: java.lang.ClassNotFoundException: org.apache.http.impl.client.HttpClients cannot be found by ondus-api_0.0.9

	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:433) ~[?:?]

	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:395) ~[?:?]

	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:387) ~[?:?]

	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:150) ~[?:?]

	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:?]

	... 13 more

==> /var/log/openhab2/events.log <==

2019-07-26 16:44:22.994 [hingStatusInfoChangedEvent] - 'groheondus:senseguard:1938d9da-af4f-4e81-a605-37c37e5d5728' changed from UNINITIALIZED to INITIALIZING_

**Comment by FlorianSW** [comment]
Ah, ok, the PR with the changes you saw above is not yet merged (#5827), that's why the snapshot version does not include this version. Someone from the maintainers of the repo needs to merge the PR, then a new snapshot version needs to be build and your error should be gone :)

**Comment by TNRichard** [comment]
Ah, ok. That makes sense :-)

**Comment by FlorianSW** [comment]
If you want to test the new version of the binding, you can download a locally compiled version (see attached files) :) Just uninstall the binding from openHAB and put this version into the addons folder of your openHAB.

I would appreciate if you would give feedback if it worked on your machine as well :)
[org.openhab.binding.groheondus-2.5.0-SNAPSHOT.zip](https://github.com/openhab/openhab2-addons/files/3436585/org.openhab.binding.groheondus-2.5.0-SNAPSHOT.zip)

**Comment by TNRichard** [comment]
I uninstalled the binding, put your snapshot jar into addon directory and restarted openHAB.
The grohe ONDUS account now shows UNINITIALIZED and in the logs I see:

**_2019-07-27 09:55:23.688 [vent.ItemStateChangedEvent] - logreaderLastWarning changed from 2019-07-27 09:54:13.359 [WARN ] [org.apache.felix.fileinstall        ] - Error while starting bundle: file:/usr/share/openhab2/addons/org.openhab.binding.groheondus-2.5.0-SNAPSHOT.jar to_**

**Comment by FlorianSW** [comment]
Hi! My fault, sorry :) You need to put any dependency jar, like the ondus-api, inside the addons folder, as well, otherwise the container does not know where to install the dependencies from. See a new zip attached to this post with all the jars, just put all of them into the addons folder :)
[addons.zip](https://github.com/openhab/openhab2-addons/files/3438060/addons.zip)

**Comment by TNRichard** [comment]
Now all things are online. Thanks!
