### ISSUE TITLE
[somfytahoma] Add support for the smoke sensor test function

### ISSUE THREAD

**Issue by riederd** [openhab/openhab-addons#5844]
Hi,

as discussed in #5801 it would be great to be able to trigger the smoke sensor alarm manually:

I guess you need this info, to start with:
{"label":"Rauch 2 Büro - Testen - TaHoma PC","shortcut":false,"internal":false,"actions":[{"deviceURL":"io://XXXX-YYYY-ZZZZ/9688780","commands":[{"name":"checkEventTrigger","parameters":["short"]}]}]}

Best
  Dietmar

**Comment by octa22** [comment]
Hi,

please, can you try this version?
https://www.dropbox.com/s/0qpz7gskoxezptw/org.openhab.binding.somfytahoma-2.5.0-SNAPSHOT.jar?dl=1

I have added channel ```short_check``` for the smoke sensor thing of type switch which reacts to ```ON``` command.
You need to remove and auto detect the new sensor thing.

Thanks for testing.
Ondrej

**Comment by octa22** [comment]
Moreover, this version uses the new V2 API, so if you test it, you help me a lot :-)

**Comment by riederd** [comment]
Hi,

I just installed the new jar. I also removed and auto detected one of my smoke sensors. However, when I try to trigger the test sound, I can not hear anything.

This is what I see in the logs:

2019-08-07 21:54:36.534 [ome.event.ItemCommandEvent] - Item 'Rauch1Gang_SmokeSensorShortCheckTrigger' received command ON
2019-08-07 21:54:36.545 [nt.ItemStatePredictedEvent] - Rauch1Gang_SmokeSensorShortCheckTrigger predicted to become ON
2019-08-07 21:54:36.557 [vent.ItemStateChangedEvent] - Rauch1Gang_SmokeSensorShortCheckTrigger changed from NULL to ON
[...]
2019-08-07 21:54:49.642 [ome.event.ItemCommandEvent] - Item 'Rauch1Gang_SmokeSensorShortCheckTrigger' received command OFF
2019-08-07 21:54:49.658 [nt.ItemStatePredictedEvent] - Rauch1Gang_SmokeSensorShortCheckTrigger predicted to become OFF
2019-08-07 21:54:49.669 [vent.ItemStateChangedEvent] - Rauch1Gang_SmokeSensorShortCheckTrigger changed from ON to OFF

How can I help to debug?

**Comment by octa22** [comment]
OK, apparently doesn’t work 😀
what says the openhab.log? is there any error? thanks

**Comment by riederd** [comment]
There is not much. The only related entry is:

2019-08-07 21:48:36.972 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'somfytahoma:smokesensor:764e9cb0:b8bf754d-190f-41f2-9241-1211646da2b6' to inbox.

**Comment by octa22** [comment]
can you enable the debug log please?

**Comment by riederd** [comment]
This is what I get, when triggering ON:

2019-08-08 22:18:23.211 [DEBUG] [.handler.SomfyTahomaBaseThingHandler] - Received command ON for channel somfytahoma:smokesensor:764e9cb0:b8bf754d-190f-41f2-9241-1211646da2b6:short_check

**Comment by octa22** [comment]
Great, debug is working.
what about this one:
https://www.dropbox.com/s/0qpz7gskoxezptw/org.openhab.binding.somfytahoma-2.5.0-SNAPSHOT.jar?dl=1

thanks.

**Comment by riederd** [comment]
Unfortunately the thing seem not to get initialized anymore.


openhab.log:
2019-08-09 19:02:18.922 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'somfytahoma:smokesensor:764e9cb0:b8bf754d-190f-41f2-9241-1211646da2b6' to inbox.

events.log:
2019-08-09 19:01:53.724 [hingStatusInfoChangedEvent] - 'somfytahoma:smokesensor:764e9cb0:b8bf754d-190f-41f2-9241-1211646da2b6' changed from ONLINE to REMOVING
2019-08-09 19:01:53.729 [hingStatusInfoChangedEvent] - 'somfytahoma:smokesensor:764e9cb0:b8bf754d-190f-41f2-9241-1211646da2b6' changed from REMOVING to REMOVED
2019-08-09 19:01:53.821 [hingStatusInfoChangedEvent] - 'somfytahoma:smokesensor:764e9cb0:b8bf754d-190f-41f2-9241-1211646da2b6' changed from REMOVED to UNINITIALIZED
2019-08-09 19:01:53.833 [hingStatusInfoChangedEvent] - 'somfytahoma:smokesensor:764e9cb0:b8bf754d-190f-41f2-9241-1211646da2b6' changed from UNINITIALIZED to UNINITIALIZED (HANDLER_MISSING_ERROR)
[...]
2019-08-09 19:02:35.077 [me.event.InboxRemovedEvent] - Discovery Result with UID 'somfytahoma:smokesensor:764e9cb0:b8bf754d-190f-41f2-9241-1211646da2b6' has been removed.
2019-08-09 19:02:35.089 [hingStatusInfoChangedEvent] - 'somfytahoma:smokesensor:764e9cb0:b8bf754d-190f-41f2-9241-1211646da2b6' changed from UNINITIALIZED to INITIALIZING

**Comment by octa22** [comment]
OK.
still I need the debug/trace log from openhab.log, there's no need to provide me the events.log
without the log we cannot move further :-(
thanks.
Ondrej

**Comment by riederd** [comment]
Oh, sorry, it seem that it made it now, took about 7 minutes:

2019-08-09 19:09:30.516 [hingStatusInfoChangedEvent] - 'somfytahoma:smokesensor:764e9cb0:b8bf754d-190f-41f2-9241-1211646da2b6' changed from INITIALIZING to ONLINE

Unfortunately the test triggers not sound.

**Comment by riederd** [comment]
I'll send the openhab debug/trace later

**Comment by riederd** [comment]
Here we go:

2019-08-09 19:17:44.134 [DEBUG] [.handler.SomfyTahomaBaseThingHandler] - Received command ON for channel somfytahoma:smokesensor:764e9cb0:b8bf754d-190f-41f2-9241-1211646da2b6:short_check
2019-08-09 19:18:04.328 [DEBUG] [nal.handler.SomfyTahomaBridgeHandler] - Getting Tahoma Updates...
2019-08-09 19:18:04.332 [TRACE] [nal.handler.SomfyTahomaBridgeHandler] - Sending POST to Tahoma to url: https://www.tahomalink.com/enduser-mobile-web/enduserAPI/events/<removed>/fetch
2019-08-09 19:18:04.695 [TRACE] [nal.handler.SomfyTahomaBridgeHandler] - Response: []
2019-08-09 19:18:04.698 [DEBUG] [nal.handler.SomfyTahomaBridgeHandler] - Got total of 0 events

**Comment by octa22** [comment]
thanks. 
Can you try this version? I have added more debug info and it should initialize sooner than in 7 minutes...
https://www.dropbox.com/s/0qpz7gskoxezptw/org.openhab.binding.somfytahoma-2.5.0-SNAPSHOT.jar?dl=1

No need to restart OH2, just rewrite the older jar with this one.
thanks.
Ondrej

**Comment by riederd** [comment]
Here we go:
2019-08-10 10:59:07.338 [DEBUG] [.handler.SomfyTahomaBaseThingHandler] - Received command ON for channel somfytahoma:smokesensor:764e9cb0:b8bf754d-190f-41f2-9241-1211646da2b6:short_check
2019-08-10 10:59:07.342 [INFO ] [dler.SomfyTahomaVenetianBlindHandler] - checkEventTrigger skipped
2019-08-10 10:59:07.344 [INFO ] [dler.SomfyTahomaVenetianBlindHandler] - command ON: false
2019-08-10 10:59:07.347 [INFO ] [dler.SomfyTahomaVenetianBlindHandler] - SHORT_CHECK: true
2019-08-10 10:59:11.109 [DEBUG] [.handler.SomfyTahomaBaseThingHandler] - Received command OFF for channel somfytahoma:smokesensor:764e9cb0:b8bf754d-190f-41f2-9241-1211646da2b6:short_check
2019-08-10 10:59:11.112 [INFO ] [dler.SomfyTahomaVenetianBlindHandler] - checkEventTrigger skipped
2019-08-10 10:59:11.121 [INFO ] [dler.SomfyTahomaVenetianBlindHandler] - command ON: false
2019-08-10 10:59:11.124 [INFO ] [dler.SomfyTahomaVenetianBlindHandler] - SHORT_CHECK: true

**Comment by octa22** [comment]
Thank you, now I see why it does nothing. It gets ON, but most probably it is string “ON” and not ON from switch. Can you send ON from switch to this channel?

Thanks
Ondrej

**Comment by riederd** [comment]
I tried in the openhab console the two versions "ON" and ON:

openhab> smarthome:send  Rauch1Gang_SmokeSensorShortCheckTrigger "ON"

2019-08-10 13:43:53.657 [INFO ] [dler.SomfyTahomaVenetianBlindHandler] - checkEventTrigger skipped
2019-08-10 13:43:53.662 [INFO ] [dler.SomfyTahomaVenetianBlindHandler] - command ON: false
2019-08-10 13:43:53.667 [INFO ] [dler.SomfyTahomaVenetianBlindHandler] - SHORT_CHECK: true

and.

smarthome:send  Rauch1Gang_SmokeSensorShortCheckTrigger ON

2019-08-10 13:44:08.538 [INFO ] [dler.SomfyTahomaVenetianBlindHandler] - checkEventTrigger skipped
2019-08-10 13:44:08.541 [INFO ] [dler.SomfyTahomaVenetianBlindHandler] - command ON: false
2019-08-10 13:44:08.545 [INFO ] [dler.SomfyTahomaVenetianBlindHandler] - SHORT_CHECK: true

None of both resulted in a test sound.

Is there any reason why it is showing logs for the SomfyTahomaVenetianBlindHandler ?

**Comment by octa22** [comment]
Great! I thing I have found it.
Now it should really execute it, I am curious what happens now.
https://www.dropbox.com/s/0qpz7gskoxezptw/org.openhab.binding.somfytahoma-2.5.0-SNAPSHOT.jar?dl=1

Please ignore the name of the log handler, now it should print correct one...
Thanks for testing
Ondrej

**Comment by riederd** [comment]
Hi,

unfortunately the thing will not initialize anymore, I waited a hour.


2019-08-10 20:17:54.159 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'somfytahoma:smokesensor:764e9cb0:b8bf754d-190f-41f2-9241-1211646da2b6' to inbox.

2019-08-10 20:18:00.448 [hingStatusInfoChangedEvent] - 'somfytahoma:smokesensor:764e9cb0:b8bf754d-190f-41f2-9241-1211646da2b6' changed from UNINITIALIZED to INITIALIZING


 After restarting openhab it initializes but when trying the trigger I get an exception:

2019-08-10 21:31:25.515 [ERROR] [nal.common.AbstractInvocationHandler] - An error occurred while calling method 'ThingHandler.handleCommand()' on 'org.openhab.binding.somfytahoma.internal.handler.SomfyTahomaSmokeSensorHandler@781c9e': org.eclipse.smarthome.core.thing.Thing.getChannel(Lorg/eclipse/smarthome/core/thing/ChannelUID;)Lorg/eclipse/smarthome/core/thing/Channel;
java.lang.NoSuchMethodError: org.eclipse.smarthome.core.thing.Thing.getChannel(Lorg/eclipse/smarthome/core/thing/ChannelUID;)Lorg/eclipse/smarthome/core/thing/Channel;
        at org.openhab.binding.somfytahoma.internal.handler.SomfyTahomaSmokeSensorHandler.handleCommand(SomfyTahomaSmokeSensorHandler.java:50) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
        at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:153) [102:org.eclipse.smarthome.core:0.10.0.oh240]
        at org.eclipse.smarthome.core.internal.common.InvocationHandlerSync.invoke(InvocationHandlerSync.java:59) [102:org.eclipse.smarthome.core:0.10.0.oh240]
        at com.sun.proxy.$Proxy135.handleCommand(Unknown Source) [191:org.openhab.binding.somfytahoma:2.5.0.201908101809]
        at org.eclipse.smarthome.core.thing.internal.profiles.ProfileCallbackImpl.handleCommand(ProfileCallbackImpl.java:75) [109:org.eclipse.smarthome.core.thing:0.10.0.oh240]
        at org.eclipse.smarthome.core.thing.internal.profiles.SystemDefaultProfile.onCommandFromItem(SystemDefaultProfile.java:49) [109:org.eclipse.smarthome.core.thing:0.10.0.oh240]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
        at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:153) [102:org.eclipse.smarthome.core:0.10.0.oh240]
        at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:53) [102:org.eclipse.smarthome.core:0.10.0.oh240]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
        at java.lang.Thread.run(Thread.java:748) [?:?]
2019-08-10 21:31:27.612 [ERROR] [nal.common.AbstractInvocationHandler] - An error occurred while calling method 'ThingHandler.handleCommand()' on 'org.openhab.binding.somfytahoma.internal.handler.SomfyTahomaSmokeSensorHandler@781c9e': org.eclipse.smarthome.core.thing.Thing.getChannel(Lorg/eclipse/smarthome/core/thing/ChannelUID;)Lorg/eclipse/smarthome/core/thing/Channel;
java.lang.NoSuchMethodError: org.eclipse.smarthome.core.thing.Thing.getChannel(Lorg/eclipse/smarthome/core/thing/ChannelUID;)Lorg/eclipse/smarthome/core/thing/Channel;
        at org.openhab.binding.somfytahoma.internal.handler.SomfyTahomaSmokeSensorHandler.handleCommand(SomfyTahomaSmokeSensorHandler.java:50) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
        at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:153) [102:org.eclipse.smarthome.core:0.10.0.oh240]
        at org.eclipse.smarthome.core.internal.common.InvocationHandlerSync.invoke(InvocationHandlerSync.java:59) [102:org.eclipse.smarthome.core:0.10.0.oh240]
        at com.sun.proxy.$Proxy135.handleCommand(Unknown Source) [191:org.openhab.binding.somfytahoma:2.5.0.201908101809]
        at org.eclipse.smarthome.core.thing.internal.profiles.ProfileCallbackImpl.handleCommand(ProfileCallbackImpl.java:75) [109:org.eclipse.smarthome.core.thing:0.10.0.oh240]
        at org.eclipse.smarthome.core.thing.internal.profiles.SystemDefaultProfile.onCommandFromItem(SystemDefaultProfile.java:49) [109:org.eclipse.smarthome.core.thing:0.10.0.oh240]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
        at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:153) [102:org.eclipse.smarthome.core:0.10.0.oh240]
        at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:53) [102:org.eclipse.smarthome.core:0.10.0.oh240]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
        at java.lang.Thread.run(Thread.java:748) [?:?]

**Comment by octa22** [comment]
ok, my fault. Please this one:
https://www.dropbox.com/s/0qpz7gskoxezptw/org.openhab.binding.somfytahoma-2.5.0-SNAPSHOT.jar?dl=1
Thank you for your patience

**Comment by riederd** [comment]
Now it's working! Great!!! Thanks a lot!

**Comment by octa22** [comment]
Great, do you want log beep too?

so 10. 8. 2019 v 21:57 odesílatel riederd <notifications@github.com> napsal:

**Comment by riederd** [comment]
Yes, would be good as well.

**Comment by octa22** [comment]
ok, this version should add a new channel long_check
https://www.dropbox.com/s/0qpz7gskoxezptw/org.openhab.binding.somfytahoma-2.5.0-SNAPSHOT.jar?dl=1

you need to remove and autodetect the new sensor again  to see and use the new channel.
thanks.
Ondrej

**Comment by riederd** [comment]
Hi,

just tested the "long" function, an it works.

THX
  Dietmar

**Comment by riederd** [comment]
Hi,

I noticed, that since I'm running the new tahoma binding I often get locked out by somfy with the error message:

"Too many requests, try again later : login with mylogin@myaddress" (This I get on the thahoma webinterface.)

Furthermore rules that were automatically controlling my blinds are not working reliable anymore (did not change anything in the rules). They get called but often no action is taken.

Any idea?

**Comment by octa22** [comment]
sorry for late reply, the new version of binding migrated to V2 API and we know, it might generate too many requests error, if you do login more frequently.

What concerns me a bit is the reliability of rules. Do you know, what sends the thing to OFFLINE state?
Do you have some debug log?
OFFLINE to ONLINE is clear - it has successfully logged in, but what brings the thing OFFLINE is not clear...

Thanks.
Ondrej

**Comment by riederd** [comment]
Hi,

unfortunately I had to revert back to an older version of the binding. These problems with unpredictable rule behavior made my "smarthome" become a "dumbhome".
In the old logs there is not much information on this, I was not running on debug level though. I just see that there were communication problems:

2019-08-17 20:36:02.690 [hingStatusInfoChangedEvent] - 'somfytahoma:bridge:764e9cb0' changed from ONLINE to OFFLINE (COMMUNICATION_ERROR)
2019-08-17 20:36:02.731 [hingStatusInfoChangedEvent] - 'somfytahoma:gateway:764e9cb0:1208-2658-1637' changed from ONLINE to OFFLINE (BRIDGE_OFFLINE)

And I remember that at the same time I couldn't login to the tahoma webinterface, were I got ther error: "Too many requests, try again later : login with mylogin@myaddress"

sorry that I do not have more....

**Comment by octa22** [comment]
I understand, I've added the sendor's check support to the current binding version as well (API v1)
hope this will work
https://www.dropbox.com/s/0qpz7gskoxezptw/org.openhab.binding.somfytahoma-2.5.0-SNAPSHOT.jar?dl=1
Ondrej

**Comment by riederd** [comment]
Hi,

unfortunately this version seems not to work. All tahoma things remain uninitialized. This is what I get in the logs:

2019-09-02 21:12:30.242 [WARN ] [org.apache.felix.fileinstall        ] - Error while starting bundle: file:/usr/share/openhab2/addons/org.openhab.binding.somfytahoma-2.5.0-SNAPSHOT.jar
org.osgi.framework.BundleException: Could not resolve module: org.openhab.binding.somfytahoma [191]
  Unresolved requirement: Import-Package: com.google.gson; version="[2.8.0,3.0.0)"

        at org.eclipse.osgi.container.Module.start(Module.java:444) ~[?:?]
        at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:383) ~[?:?]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1260) [10:org.apache.felix.fileinstall:3.6.4]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1233) [10:org.apache.felix.fileinstall:3.6.4]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:520) [10:org.apache.felix.fileinstall:3.6.4]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:365) [10:org.apache.felix.fileinstall:3.6.4]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:316) [10:org.apache.felix.fileinstall:3.6.4]

**Comment by octa22** [comment]
Of course, that's because the binding is for OH2.5 version.
You can try this one:
https://www.dropbox.com/s/0qpz7gskoxezptw/org.openhab.binding.somfytahoma-2.5.0-SNAPSHOT.jar?dl=1

thanks
Ondrej

**Comment by riederd** [comment]
Hi,

I again have problems with to many requests. I get locked out from the tahomalink webinterface for a while with:
"Too many requests, try again later : login with xxx@xxx.xxx)"

openhab.log:
2019-09-03 09:12:57.027 [ERROR] [nal.handler.SomfyTahomaBridgeHandler] - Received error code: 400
2019-09-03 09:12:57.029 [WARN ] [nal.handler.SomfyTahomaBridgeHandler] - Apply command response: {"error":"Managed action group is invalid : setOrientation() : Invalid value for command parameter p1 : expected integer value between 0 and 100 but got 38.0"}

events log:
2019-09-03 09:17:50.318 [vent.ItemStateChangedEvent] - RaffstoreKinderzimmer_Orientation changed from 0 to 46.0
2019-09-03 09:17:50.473 [hingStatusInfoChangedEvent] - 'somfytahoma:bridge:764e9cb0' changed from ONLINE to OFFLINE (COMMUNICATION_ERROR)
2019-09-03 09:17:50.491 [hingStatusInfoChangedEvent] - 'somfytahoma:smokesensor:764e9cb0:b8bf754d-190f-41f2-9241-1211646da2b6' changed from ONLINE to OFFLINE (BRIDGE_OFFLINE)

**Comment by octa22** [comment]
Thanks,
when this error occurs?

[nal.handler.SomfyTahomaBridgeHandler] - Apply command response: {"error":"Managed action group is invalid : setOrientation() : Invalid value for command parameter p1 : expected integer value between 0 and 100 but got 38.0"}

it seems something is sending 38.0 and it expects 38.
Is this a execution result of an actiongroup / your rule / dimmer in UI? What device is this - blinds?
It tries to recover fron this error with a relogin which results in “too many requests”.
 thanks
Ondrej

________________________________
Od: riederd <notifications@github.com>
Odesláno: úterý, září 3, 2019 9:21 dop.
Komu: openhab/openhab2-addons
Kopie: Ondrej Pecta; Comment
Předmět: Re: [openhab/openhab2-addons] [somfytahoma] Add support for the smoke sensor test function (#5844)


Hi,

I again have problems with to many requests. I get locked out from the tahomalink webinterface for a while with:
"Too many requests, try again later : login with xxx@xxx.xxx<mailto:xxx@xxx.xxx>)"

openhab.log:
2019-09-03 09:12:57.027 [ERROR] [nal.handler.SomfyTahomaBridgeHandler] - Received error code: 400
2019-09-03 09:12:57.029 [WARN ] [nal.handler.SomfyTahomaBridgeHandler] - Apply command response: {"error":"Managed action group is invalid : setOrientation() : Invalid value for command parameter p1 : expected integer value between 0 and 100 but got 38.0"}

events log:
2019-09-03 09:17:50.318 [vent.ItemStateChangedEvent] - RaffstoreKinderzimmer_Orientation changed from 0 to 46.0
2019-09-03 09:17:50.473 [hingStatusInfoChangedEvent] - 'somfytahoma:bridge:764e9cb0' changed from ONLINE to OFFLINE (COMMUNICATION_ERROR)
2019-09-03 09:17:50.491 [hingStatusInfoChangedEvent] - 'somfytahoma:smokesensor:764e9cb0:b8bf754d-190f-41f2-9241-1211646da2b6' changed from ONLINE to OFFLINE (BRIDGE_OFFLINE)

**Comment by riederd** [comment]
Hi,

the error/warning: "Invalid value for command parameter p1 : expected integer value between 0 and 100 but got 38.0"}"

was a result from changing the dimmer/orientation for the external venetian blind in the UI (basic UI)

Dietmar

**Comment by octa22** [comment]
It's weird, I always get integer value instead of float (eg. 38 instead of 38.0) - even in the basic UI
Sorry to trouble you, but can you try this version and send me the log for changing the orientation? It should not throw an error, but anyway I would like to see the log...

https://www.dropbox.com/s/0qpz7gskoxezptw/org.openhab.binding.somfytahoma-2.5.0-SNAPSHOT.jar?dl=1

thanks.
Ondrej

**Comment by riederd** [comment]
Hi,

sure! Here we go:

events.log:
2019-09-03 20:12:08.704 [ome.event.ItemCommandEvent] - Item 'RaffstoreBuero_Orientation' received command 48
2019-09-03 20:12:08.718 [vent.ItemStateChangedEvent] - RaffstoreBuero_Orientation changed from 0 to 48

openhab.log:
2019-09-03 20:12:08.722 [INFO ] [.handler.SomfyTahomaBaseThingHandler] - Received command 48 for channel somfytahoma:exteriorvenetianblind:764e9cb0:70b5f19a-b7e5-4166-9045-ec7c951028b5:orientation

It seems to send int now!

HTH
  Dietmar

**Comment by octa22** [comment]
I have not changed anything, just printed out the command value from a command...
Is the same behaviour for the RaffstoreKinderzimmer_Orientation too? (even from basic UI?)

thanks.
Ondrej

**Comment by riederd** [comment]
Hi,

that's strange indeed.

RaffstoreKinderzimmer_Orientation gives the same logs:

2019-09-03 20:25:16.515 [INFO ] [.handler.SomfyTahomaBaseThingHandler] - Received command 24 for channel somfytahoma:exteriorvenetianblind:764e9cb0:cb5b7978-1db9-4d93-839c-2dcd99ca235f:orientation

2019-09-03 20:25:16.495 [ome.event.ItemCommandEvent] - Item 'RaffstoreKinderzimmer_Orientation' received command 24
2019-09-03 20:25:16.538 [vent.ItemStateChangedEvent] - RaffstoreKinderzimmer_Orientation changed from 0 to 24

**Comment by octa22** [comment]
I do not get it, anyway try to use this version and see if it more stable...
If you see a float value in your log (or "too many requests" issue), please provide me the log...
thanks.
Ondrej
