### ISSUE TITLE
[nest] Integration tests fail on Windows

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-addons#5906]
Build on Windows 10:
```
Tests run  : 39
Passed     : 16
Errors     : 23
Failures   : 0
[INFO] 23 Error(s)
```

**Comment by wborn** [comment]
Do you have more details @lolodomo?

Build on Ubuntu 18.04.3 LTS (Bionic Beaver):

```
Tests run  : 39
Passed     : 39
Errors     : 0
Failures   : 0
[INFO] No Errors
```

**Comment by lolodomo** [comment]
These tests take ages and produce many logs, more than what my terminal can saved. I just copied the last errors found:
```
18:15:17.607 [main] DEBUG org.eclipse.smarthome.core.thing.internal.ThingManagerImpl - Thing handler factory 'NestTestHandlerFactory' removed
18:15:17.608 [main] DEBUG org.eclipse.smarthome.core.common.registry.AbstractRegistry - Provider "ChannelItemProvider" has been removed.
18:15:17.609 [main] DEBUG org.eclipse.smarthome.core.common.registry.AbstractRegistry - Provider "ManagedItemChannelLinkProvider" has been removed.
18:15:17.610 [main] DEBUG org.eclipse.smarthome.core.common.registry.AbstractRegistry - Provider "ManagedMetadataProviderImpl" has been removed.
18:15:17.611 [main] DEBUG org.eclipse.smarthome.core.common.registry.AbstractRegistry - Provider "ManagedItemProvider" has been removed.
TEST incompleteThermostatUpdate(org.openhab.binding.nest.handler.NestThermostatHandlerTest) <<< ERROR:
Expected: is <ONLINE>
     but: was <OFFLINE>
java.lang.AssertionError:
Expected: is <ONLINE>
     but: was <OFFLINE>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.openhab.binding.nest.handler.NestThermostatHandlerTest.lambda$5(NestThermostatHandlerTest.java:148)
        at org.eclipse.smarthome.test.java.JavaTest.waitForAssert(JavaTest.java:152)
        at org.eclipse.smarthome.test.java.JavaTest.waitForAssert(JavaTest.java:120)
        at org.eclipse.smarthome.test.java.JavaTest.waitForAssert(JavaTest.java:73)
        at org.openhab.binding.nest.handler.NestThermostatHandlerTest.incompleteThermostatUpdate(NestThermostatHandlerTest.java:148)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at junit.framework.JUnit4TestAdapter.run(JUnit4TestAdapter.java:38)
        at junit.framework.TestSuite.runTest(TestSuite.java:252)
        at junit.framework.TestSuite.run(TestSuite.java:247)
        at aQute.junit.Activator.test(Activator.java:340)
        at aQute.junit.Activator.automatic(Activator.java:236)
        at aQute.junit.Activator.run(Activator.java:177)
        at aQute.launcher.Launcher.lambda$serviceChanged$0(Launcher.java:1385)
        at aQute.launcher.Launcher.run(Launcher.java:352)
        at aQute.launcher.Launcher.main(Launcher.java:152)
...
18:15:27.893 [main] DEBUG org.eclipse.smarthome.core.common.registry.AbstractRegistry - Provider "ManagedThingProvider" has been removed.
18:15:27.894 [main] DEBUG org.eclipse.smarthome.core.thing.internal.ThingManagerImpl - Thing handler factory 'NestHandlerFactory' removed
18:15:27.894 [main] DEBUG org.eclipse.smarthome.core.thing.internal.ThingManagerImpl - Thing handler factory 'NestTestHandlerFactory' removed
18:15:27.894 [main] DEBUG org.eclipse.smarthome.core.thing.internal.ThingManagerImpl - Thing handler factory 'NestHandlerFactory' removed
18:15:27.894 [main] DEBUG org.eclipse.smarthome.core.thing.internal.ThingManagerImpl - Thing handler factory 'NestTestHandlerFactory' removed
18:15:27.894 [main] DEBUG org.eclipse.smarthome.core.common.registry.AbstractRegistry - Provider "ChannelItemProvider" has been removed.
18:15:27.895 [main] DEBUG org.eclipse.smarthome.core.common.registry.AbstractRegistry - Provider "ManagedItemChannelLinkProvider" has been removed.
18:15:27.895 [main] DEBUG org.eclipse.smarthome.core.common.registry.AbstractRegistry - Provider "ManagedMetadataProviderImpl" has been removed.
18:15:27.896 [main] DEBUG org.eclipse.smarthome.core.common.registry.AbstractRegistry - Provider "ManagedItemProvider" has been removed.
TEST handleSetPointCelsiusCommands(org.openhab.binding.nest.handler.NestThermostatHandlerTest) <<< ERROR:
Expected: is <ONLINE>
     but: was <OFFLINE>
java.lang.AssertionError:
Expected: is <ONLINE>
     but: was <OFFLINE>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.openhab.binding.nest.handler.NestThermostatHandlerTest.lambda$13(NestThermostatHandlerTest.java:256)
        at org.eclipse.smarthome.test.java.JavaTest.waitForAssert(JavaTest.java:152)
        at org.eclipse.smarthome.test.java.JavaTest.waitForAssert(JavaTest.java:120)
        at org.eclipse.smarthome.test.java.JavaTest.waitForAssert(JavaTest.java:73)
        at org.openhab.binding.nest.handler.NestThermostatHandlerTest.celsiusCommandsTest(NestThermostatHandlerTest.java:256)
        at org.openhab.binding.nest.handler.NestThermostatHandlerTest.handleSetPointCelsiusCommands(NestThermostatHandlerTest.java:245)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at junit.framework.JUnit4TestAdapter.run(JUnit4TestAdapter.java:38)
        at junit.framework.TestSuite.runTest(TestSuite.java:252)
        at junit.framework.TestSuite.run(TestSuite.java:247)
        at aQute.junit.Activator.test(Activator.java:340)
        at aQute.junit.Activator.automatic(Activator.java:236)
        at aQute.junit.Activator.run(Activator.java:177)
        at aQute.launcher.Launcher.lambda$serviceChanged$0(Launcher.java:1385)
        at aQute.launcher.Launcher.run(Launcher.java:352)
        at aQute.launcher.Launcher.main(Launcher.java:152)
...
18:15:38.559 [main] DEBUG org.eclipse.smarthome.core.thing.internal.ThingManagerImpl - Thing handler factory 'NestTestHandlerFactory' removed
18:15:38.559 [main] DEBUG org.eclipse.smarthome.core.common.registry.AbstractRegistry - Provider "ChannelItemProvider" has been removed.
18:15:38.559 [main] DEBUG org.eclipse.smarthome.core.common.registry.AbstractRegistry - Provider "ManagedItemChannelLinkProvider" has been removed.
18:15:38.559 [main] DEBUG org.eclipse.smarthome.core.common.registry.AbstractRegistry - Provider "ManagedMetadataProviderImpl" has been removed.
18:15:38.575 [main] DEBUG org.eclipse.smarthome.core.common.registry.AbstractRegistry - Provider "ManagedItemProvider" has been removed.
TEST handleMaxSetPointCelsiusCommands(org.openhab.binding.nest.handler.NestThermostatHandlerTest) <<< ERROR:
Expected: is <ONLINE>
     but: was <OFFLINE>
java.lang.AssertionError:
Expected: is <ONLINE>
     but: was <OFFLINE>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.openhab.binding.nest.handler.NestThermostatHandlerTest.lambda$13(NestThermostatHandlerTest.java:256)
        at org.eclipse.smarthome.test.java.JavaTest.waitForAssert(JavaTest.java:152)
        at org.eclipse.smarthome.test.java.JavaTest.waitForAssert(JavaTest.java:120)
        at org.eclipse.smarthome.test.java.JavaTest.waitForAssert(JavaTest.java:73)
        at org.openhab.binding.nest.handler.NestThermostatHandlerTest.celsiusCommandsTest(NestThermostatHandlerTest.java:256)
        at org.openhab.binding.nest.handler.NestThermostatHandlerTest.handleMaxSetPointCelsiusCommands(NestThermostatHandlerTest.java:204)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at junit.framework.JUnit4TestAdapter.run(JUnit4TestAdapter.java:38)
        at junit.framework.TestSuite.runTest(TestSuite.java:252)
        at junit.framework.TestSuite.run(TestSuite.java:247)
        at aQute.junit.Activator.test(Activator.java:340)
        at aQute.junit.Activator.automatic(Activator.java:236)
        at aQute.junit.Activator.run(Activator.java:177)
        at aQute.launcher.Launcher.lambda$serviceChanged$0(Launcher.java:1385)
        at aQute.launcher.Launcher.run(Launcher.java:352)
        at aQute.launcher.Launcher.main(Launcher.java:152)
```
It looks like it is always the same problem: OFFLINE vs ONLINE.

**Comment by lolodomo** [comment]
`Total time: 04:20 min`
It looks like very long just for the integration tests of one binding...

**Comment by wborn** [comment]
IIRC it occasionally fails on Linux too with such failed assertions.

It takes long because it's probably waiting each time 10 seconds for an assertion to become true. Which obviously never happens if the tests fail.

The project builds successfully in 27 seconds on my machine. In which 7 second are spent with SAT. :wink:
