### ISSUE TITLE
[systeminfo] 2.5M2 - ERROR - Cannot instantate Systeminfo object!

### ISSUE THREAD

**Issue by msexton187** [openhab/openhab-addons#5921]
After upgrade to openHab 2.5M2 the systeminfo v2 binding no longer works.  When adding the Local Computer item from the Inbox the following ERROR is raised.

```
2019-08-12 17:35:13.035 [ERROR] [.systeminfo.internal.handler.SysteminfoHandler] - Cannot instantate Systeminfo object!
java.lang.ArrayIndexOutOfBoundsException: 0
	at com.sun.jna.Structure.toArray(Structure.java:1626) ~[?:?]
	at com.sun.jna.platform.win32.Kernel32Util.getLogicalProcessorInformation(Kernel32Util.java:675) ~[?:?]
	at oshi.hardware.platform.windows.WindowsCentralProcessor.calculateProcessorCounts(WindowsCentralProcessor.java:259) ~[?:?]
	at oshi.hardware.common.AbstractCentralProcessor.<init>(AbstractCentralProcessor.java:120) ~[?:?]
	at oshi.hardware.platform.windows.WindowsCentralProcessor.<init>(WindowsCentralProcessor.java:208) ~[?:?]
	at oshi.hardware.platform.windows.WindowsHardwareAbstractionLayer.getProcessor(WindowsHardwareAbstractionLayer.java:70) ~[?:?]
	at org.openhab.binding.systeminfo.internal.model.OSHISysteminfo.initializeSysteminfo(OSHISysteminfo.java:91) ~[302:org.openhab.binding.systeminfo:2.5.0.M2]
	at org.openhab.binding.systeminfo.internal.handler.SysteminfoHandler.instantiateSysteminfoLibrary(SysteminfoHandler.java:123) [302:org.openhab.binding.systeminfo:2.5.0.M2]
	at org.openhab.binding.systeminfo.internal.handler.SysteminfoHandler.initialize(SysteminfoHandler.java:109) [302:org.openhab.binding.systeminfo:2.5.0.M2]
	at sun.reflect.GeneratedMethodAccessor67.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
	at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:152) [133:org.openhab.core:2.5.0.M2]
	at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:53) [133:org.openhab.core:2.5.0.M2]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]
```
This issue wasn't present in 2.4 or 2.5M1

## Your Environment
Windows 10
Java jre1.8.0_191
openhab 2.5.0.M2
systeminfo 2.5.0.M2

**Comment by wborn** [comment]
It seems to be a bug in JNA which can be fixed by upgrading JNA from 5.3.0 to 5.3.1:

See: 
* https://github.com/oshi/oshi/issues/842
* https://github.com/java-native-access/jna/pull/1087
* https://github.com/oshi/oshi/pull/845

**Comment by msexton187** [comment]
Pardon my ignorance; I'm new to Git and Java.  Is this something I can do
on my machine locally or do I need to wait for an OH snapshot build?

**Comment by wborn** [comment]
We'll need to update some version numbers. When those have been updated it will eventually be available in a new snapshot build. :-)
