### ISSUE TITLE
[mqtt] MQTT Binding stop processing outbound publications from rules for Homie Devices

### ISSUE THREAD

**Issue by boc-tothefuture** [openhab/openhab-addons#5972]
## Expected Behavior
MQTT should always process messages when rules updated related items. 

## Current Behavior
After a time period, MQTT stops processing updates. I am seeing it with Homie devices, but that my only outbound use of MQTT in OpenHab.  The duration until failure seems variable, but is resolved by restarting openhab. 

## Steps to Reproduce (for Bugs)
Thing definition:
```
Bridge mqtt:broker:mosquitto [ host="<host>", secure=false, clientID="openhab", username="openhab", password="<password>" ]
{
       Thing homie300 nuvo [ deviceid="nuvo", basetopic="homie"]
}
```

Item definition:
```
String                 Nuvo_Source_5_Display_Line_1      {channel="mqtt:homie300:mosquitto:nuvo:source5#displayline1"}
String                 Nuvo_Source_5_Display_Line_2      {channel="mqtt:homie300:mosquitto:nuvo:source5#displayline2"}
String                 Nuvo_Source_5_Display_Line_3      {channel="mqtt:homie300:mosquitto:nuvo:source5#displayline3"}
String                 Nuvo_Source_5_Display_Line_4      {channel="mqtt:homie300:mosquitto:nuvo:source5#displayline4"}
Number                 Nuvo_Source_5_Track_Duration      {channel="mqtt:homie300:mosquitto:nuvo:source5#duration"}
Number                 Nuvo_Source_5_Track_Position      {channel="mqtt:homie300:mosquitto:nuvo:source5#position"}
String                 Nuvo_Source_5_Source_Status       {channel="mqtt:homie300:mosquitto:nuvo:source5#status"}
```

Example Rule:

```
rule 'Update Chomecast Album'
when Item ChromecastStatusAlbum changed
then
  val state = ChromecastStatusAlbum.state
  if( state != UNDEF) {
    logInfo("Nuvo", "Updating Nuvo Chromecast Album: {}", state)
    Nuvo_Source_5_Display_Line_2.sendCommand(state)
  }
  else{
    logInfo("Nuvo", "Skipping undefined state for Album")
  }
end

```

OpenHab Log Output:
```
2019-08-22 19:24:01.050 [INFO ] [.eclipse.smarthome.model.script.Nuvo] - Updating Nuvo Chromecast Album: Dual
```

Events Log:
```
2019-08-22 19:24:01.051 [ome.event.ItemCommandEvent] - Item 'Nuvo_Source_5_Display_Line_2' received command Dual
2019-08-22 19:24:01.052 [nt.ItemStatePredictedEvent] - Nuvo_Source_5_Display_Line_2 predicted to become NULL
```

I have the MQTT client logging set to debug and I get no output. 

## Your Environment
Openhab 2.5M2

**Comment by boc-tothefuture** [comment]
PEBKAC

**Comment by boc-tothefuture** [comment]
I closed this because I thought I had a configuration error.  It has occured again, but I see no configuration error. 

Additional information:
Thing appears online
`smarthome:things list | grep -i homie
mqtt:homie300:mosquitto:nuvo (Type=Thing, Status=ONLINE, Label=Homie MQTT device, Bridge=mqtt:broker:mosquitto)`

Rules modify a homie item and I see no messages published and no errors or any messages related to MQTT (with debug logging enabled) in the log.

**Comment by boc-tothefuture** [comment]
After restarting OpenHab I am getting errors that the items are null:
```
2019-09-02 06:30:45.179 [INFO ] [.eclipse.smarthome.model.script.Nuvo] - Updating Nuvo Chromecast Album: Stranger in the Alps

2019-09-02 06:30:45.179 [ERROR] [ntime.internal.engine.RuleEngineImpl] - Rule 'Update Chomecast Album': An error occurred during the script execution: Could not invoke method: org.eclipse.smarthome.model.script.actions.BusEvent.sendCommand(org.eclipse.smarthome.core.items.Item,java.lang.String) on instance: null
```
The item does show up in the console:
```
smarthome:items list Nuvo_Source_5_Display_Line_2
Nuvo_Source_5_Display_Line_2 (Type=StringItem, State=NULL, Label=null, Category=null)
```

**Comment by boc-tothefuture** [comment]
I was seeing this behavior between restarts of OpenHab.  To make it work I restarted the mosquitto broker while openhab was stopped and it is now working again.

**Comment by boc-tothefuture** [comment]
This problem persists on OpenHAB 2.5 M3.  Anytime I restart openhab I have to bounce mosquitto as well or homie linked items do not work.

**Comment by J-N-K** [comment]
Can you check if this also happens with non-Homie topics? Just add a new generic Thing with a string channel and some arbitrary topic, link it to a new item (to make sure there is no interference) and send a command in the same rule. You can then use mqtt.fx (or some other mqtt tool) to monitor if that topic is still working if the homie thing stops working.

**Comment by J-N-K** [comment]
@boc-tothefuture is this still the case with the latest snapshot?

**Comment by boc-tothefuture** [comment]
I will upgrade to the latest snapshot this week and test.

**Comment by boc-tothefuture** [comment]
Issue persists on latest snapshot.  
I did find the following in the log this time:
```
2019-12-19 11:48:02.448 [WARN ] [.mqtt.homie.internal.homie300.Device] - Could not subscribe
java.util.concurrent.CompletionException: java.lang.Exception: Did not receive mandatory topic value: homie/nuvo/zone20/$name
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292) ~[?:1.8.0_201]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308) ~[?:1.8.0_201]
        at java.util.concurrent.CompletableFuture.biRelay(CompletableFuture.java:1284) ~[?:1.8.0_201]
        at java.util.concurrent.CompletableFuture$BiRelay.tryFire(CompletableFuture.java:1270) ~[?:1.8.0_201]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[?:1.8.0_201]
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977) ~[?:1.8.0_201]
        at org.openhab.binding.mqtt.generic.mapping.SubscribeFieldToMQTTtopic.timeoutReached(SubscribeFieldToMQTTtopic.java:166) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_201]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_201]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_201]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_201]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_201]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_201]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: java.lang.Exception: Did not receive mandatory topic value: homie/nuvo/zone20/$name
```

Unfortunately, I did not check with mosquitto_sub to validate it was in fact there as I was troubleshooting other parts of the systems that were not functioning after upgrade.

**Comment by mjcumming** [comment]
@boc-tothefuture if the Homie device Thing is OFFLINE, the Homie binding does not publish to MQTT. Not sure this is desirable or not but there should be a warning in the log at least

**Comment by hmerk** [comment]
closed due to inactivity
