### ISSUE TITLE
[boschindego] Indego mower state not updated due to NPE

### ISSUE THREAD

**Issue by henrydiesner** [openhab/openhab-addons#5975]
Since any days i can start and stop the indego mower with the openhab switch, but he gives no feedback about his state like "mow", "return" and so on. The log file says:

```
2019-08-23 18:38:10.955 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception: 
java.lang.NullPointerException: null
	at org.openhab.binding.boschindego.internal.handler.BoschIndegoHandler.getEshStatusFromCommand(BoschIndegoHandler.java:201) ~[?:?]
	at org.openhab.binding.boschindego.internal.handler.BoschIndegoHandler.poll(BoschIndegoHandler.java:135) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

Is it an issue or can I do something with the settings?

**Comment by wborn** [comment]
I don't use this binding but according to the line number (assuming you're not on OH 2.5.0-SNAPSHOT) the command is null:

https://github.com/openhab/openhab2-addons/blob/bdbcd574ae854ed2719b5c7111dfb27f783d279b/addons/binding/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/handler/BoschIndegoHandler.java#L199-L215

If I look at the [DeviceStatus class](https://github.com/zazaz-de/iot-device-bosch-indego-controller/blob/0edf3af71275b3432b85a218e8c5f46c2024e3b9/bosch-indego-controller-lib/src/main/java/de/zazaz/iot/bosch/indego/DeviceStatus.java#L47-L75) the command can be null during:
* Diagnostic mode
* End of live
* Software update

**Comment by jpk8201** [comment]
The program doesn't work for me either.

![screenshot_1335](https://user-images.githubusercontent.com/26160561/64861680-db728300-d630-11e9-8737-abfc44b1d60e.jpg)

**Comment by hmerk** [comment]
closed due to inactivity
