### ISSUE TITLE
[enocean] NumberFormatException for Unknown RADIO_ERP1 RORG Unknown Messages hangs bridge

### ISSUE THREAD

**Issue by henglert** [openhab/openhab-addons#5997]
## Expected Behavior 
Even if an unknown/invalid Enocean Message is received (e.g. transmission error/collision), the bridge should just ignore it and go on receiving.

## Current Behavior
The Transceiver throws a java.lang.NumberFormatException for input string "" at the java.lang.Long.parseLong function and stops the scheduled runnable. This means, that the bridge will not receive/send any more messages.

in the Logfile (YYYYYYYY is the Enocean-ID of one of my Opus GN-BH63AP-pw motion/brightness sensors (EEP A5-08-01):

```
2019-08-16 14:31:05.273 [DEBUG] [rnal.handler.EnOceanBaseThingHandler] - ESP Packet payload A5C875000FYYYYYYYY00 for YYYYYYYY received
2019-08-16 14:31:05.293 [DEBUG] [ernal.transceiver.EnOceanTransceiver] - RADIO_ERP1 with RORG Unknown for  payload E5C835000FYYYYYYYY0101FFFFFFFF5900 received
2019-08-16 14:31:05.301 [DEBUG] [ernal.transceiver.EnOceanTransceiver] - RADIO_ERP1 with RORG Unknown for  payload E5C835000FYYYYYYYY0101FFFFFFFF5600 received
2019-08-16 14:31:05.302 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception:
java.lang.NumberFormatException: For input string: ""
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:?]
        at java.lang.Long.parseLong(Long.java:601) ~[?:?]
        at org.openhab.binding.enocean.internal.transceiver.EnOceanTransceiver.informListeners(EnOceanTransceiver.java:422) ~[?:?]
        at org.openhab.binding.enocean.internal.transceiver.EnOceanTransceiver.processMessage(EnOceanTransceiver.java:313) ~[?:?]
        at org.openhab.binding.enocean.internal.transceiver.EnOceanTransceiver.receivePackets(EnOceanTransceiver.java:200) ~[?:?]
        at org.openhab.binding.enocean.internal.transceiver.EnOceanTransceiver.access$3(EnOceanTransceiver.java:192) ~[?:?]
        at org.openhab.binding.enocean.internal.transceiver.EnOceanTransceiver$1.run(EnOceanTransceiver.java:163) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
        at java.lang.Thread.run(Thread.java:748) [?:?]
2019-08-16 14:31:05.294 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception:
java.lang.NumberFormatException: For input string: ""
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:?]
        at java.lang.Long.parseLong(Long.java:601) ~[?:?]
        at org.openhab.binding.enocean.internal.transceiver.EnOceanTransceiver.informListeners(EnOceanTransceiver.java:422) ~[?:?]
        at org.openhab.binding.enocean.internal.transceiver.EnOceanTransceiver.processMessage(EnOceanTransceiver.java:313) ~[?:?]
        at org.openhab.binding.enocean.internal.transceiver.EnOceanTransceiver.receivePackets(EnOceanTransceiver.java:200) ~[?:?]
        at org.openhab.binding.enocean.internal.transceiver.EnOceanTransceiver.access$3(EnOceanTransceiver.java:192) ~[?:?]
        at org.openhab.binding.enocean.internal.transceiver.EnOceanTransceiver$1.run(EnOceanTransceiver.java:163) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
        at java.lang.Thread.run(Thread.java:748) [?:?]
```

## Possible Solution
The senderId is initialized with an empty byte array (senderId = new byte[0]).
The processMessage(byte) function calls in the switch case "RADIO_ERP1" the informListeners(msg) function, which then compares the senderId with null.
I think the problem is that the comparison of new byte[0] with null returns false and so the function parseLong("",16) is called, which throws the exception.

The comparison of (senderId != null) should be extended to
`((senderId != null) && (senderId.length > 0))` 
At least this solution works for me since 1 week now.

## Steps to Reproduce (for Bugs)
Hard to reproduce because normally there are no Unknown messages.

## Context
Maybe I also should review my Enocean bridges / repeater locations, but for robustness this bug should be fixed.

## Your Environment
* Version used: openhab2 2.5.0, Addons 2.5.0 master
* Ubuntu 18.04

**Comment by fruggy83** [comment]
This issue should be fixed by #6050 now. However I would like to use this issue to implement the not yet supported RORG D0 type 0x06.

**Comment by fruggy83** [comment]
Implementation finished, however PR must wait for merge of #6155. This PR introduces needed batteryLevel channel.

**Comment by fruggy83** [comment]
This exception also occures when an encrypted enocean message is received. A log can be found [here](https://community.openhab.org/t/enocean-binding-exception-in-informlisteners/87032/2?u=fruggy83).
