### ISSUE TITLE
[snmp] Exceptions on startup

### ISSUE THREAD

**Issue by Alex5719** [openhab/openhab-addons#6055]
After updating my configuration from SNMP1 to SNMP(2) binding I get the following exceptions on starting Openhab. The SNMP items seems to work correctly. I am running OpenHAB 2.5.0 M3

```
[ERROR] [ome.core.thing.link.ThingLinkManager] - Exception occurred while informing handler: null
java.lang.NullPointerException: null
	at org.snmp4j.MessageDispatcherImpl.getTransport(MessageDispatcherImpl.java:225) ~[?:?]
	at org.snmp4j.MessageDispatcherImpl.sendPdu(MessageDispatcherImpl.java:446) ~[?:?]
	at org.snmp4j.Snmp.sendMessage(Snmp.java:1087) ~[?:?]
	at org.snmp4j.Snmp.send(Snmp.java:1057) ~[?:?]
	at org.snmp4j.Snmp.send(Snmp.java:1041) ~[?:?]
	at org.openhab.binding.snmp.internal.SnmpServiceImpl.send(SnmpServiceImpl.java:133) ~[?:?]
	at org.openhab.binding.snmp.internal.SnmpTargetHandler.handleCommand(SnmpTargetHandler.java:100) ~[?:?]
	at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.channelLinked(BaseThingHandler.java:229) ~[?:?]
	at org.eclipse.smarthome.core.thing.link.ThingLinkManager.lambda$0(ThingLinkManager.java:266) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]
```

**Comment by J-N-K** [comment]
Please show the thing configuration. The NPE seems to arise from the target address.
.

**Comment by Alex5719** [comment]
My config consists of three snmp things with multiple channels that are all of the same structure shown below:

Thing snmp:target:server [ hostname="xxx.xxx.xxx.xxx", protocol="v2c", community="xxx" ] {
    Channels:
        Type number : temperature [ oid=".x.x.x.x.x.x.x.x.x.x.x.x.x", mode="READ" ]
}

Actually all my SNMP items are working. I only the the described exceptions on startup.

**Comment by Alex5719** [comment]
I recognised that the number of exceptions varies on different start ups. Sometimes even no exceptions are fired. I also have to mention that usually I not only restart the openhab service but restart the whole Linux OS that autostarts the openhab service.
