### ISSUE TITLE
[gardena] Error 400 Bad Request

### ISSUE THREAD

**Issue by UrsusS** [openhab/openhab-addons#6084]
Today I found in the logs the following error:
```
16-Sep-2019 14:32:44.064 [DEBUG] [ng.gardena.internal.GardenaSmartImpl] - Refreshing gardena device data
16-Sep-2019 14:33:45.023 [DEBUG] [ng.gardena.internal.GardenaSmartImpl] - Refreshing gardena device data
16-Sep-2019 14:33:46.561 [DEBUG] [internal.handler.GardenaThingHandler] - Received Gardena command: DURATION_PROPERTY
16-Sep-2019 14:34:16.619 [DEBUG] [internal.handler.GardenaThingHandler] - Received Gardena command: START_OVERRIDE_TIMER
16-Sep-2019 14:34:17.442 [WARN ] [internal.handler.GardenaThingHandler] - Error 400 Bad Request
org.openhab.binding.gardena.internal.exception.GardenaException: Error 400 Bad Request
	at org.openhab.binding.gardena.internal.GardenaSmartImpl.executeRequest(GardenaSmartImpl.java:492) ~[253:org.openhab.binding.gardena:2.5.0.M3]
	at org.openhab.binding.gardena.internal.GardenaSmartImpl.sendCommand(GardenaSmartImpl.java:379) ~[253:org.openhab.binding.gardena:2.5.0.M3]
	at org.openhab.binding.gardena.internal.handler.GardenaThingHandler.handleCommand(GardenaThingHandler.java:228) [253:org.openhab.binding.gardena:2.5.0.M3]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
	at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:152) [133:org.openhab.core:2.5.0.M3]
	at org.eclipse.smarthome.core.internal.common.InvocationHandlerSync.invoke(InvocationHandlerSync.java:59) [133:org.openhab.core:2.5.0.M3]
	at com.sun.proxy.$Proxy845.handleCommand(Unknown Source) [?:?]
	at org.eclipse.smarthome.core.thing.internal.profiles.ProfileCallbackImpl.handleCommand(ProfileCallbackImpl.java:75) [184:org.openhab.core.thing:2.5.0.M3]
	at org.eclipse.smarthome.core.thing.internal.profiles.SystemDefaultProfile.onCommandFromItem(SystemDefaultProfile.java:49) [184:org.openhab.core.thing:2.5.0.M3]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
	at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:152) [133:org.openhab.core:2.5.0.M3]
	at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:53) [133:org.openhab.core:2.5.0.M3]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]
Caused by: org.openhab.binding.gardena.internal.exception.GardenaException: Error 400 Bad Request
	at org.openhab.binding.gardena.internal.GardenaSmartImpl.executeRequest(GardenaSmartImpl.java:473) ~[?:?]
	... 21 more
16-Sep-2019 18:55:57.812 [DEBUG] [internal.handler.GardenaThingHandler] - Received Gardena command: PARK_UNTIL_NEXT_TIMER
```

Even though it was classified as warning, the binding stopped working as the lines were missing until the next command:
`16-Sep-2019 18:56:04.958 [DEBUG] [ng.gardena.internal.GardenaSmartImpl] - Refreshing gardena device data
`
I'm using openhab 2.5.0 M3 on Raspbian GNU/Linux 9 (stretch).

**Comment by kaikreuzer** [comment]
@gerrieg Could you have a look?

**Comment by UrsusS** [comment]
Just found it again:
```
13-Okt-2019 15:32:10.096 [DEBUG] [ng.gardena.internal.GardenaSmartImpl] - Refreshing gardena device data
13-Okt-2019 15:33:11.091 [DEBUG] [ng.gardena.internal.GardenaSmartImpl] - Refreshing gardena device data
13-Okt-2019 15:33:12.616 [DEBUG] [internal.handler.GardenaThingHandler] - Received Gardena command: DURATION_PROPERTY
13-Okt-2019 15:33:44.408 [DEBUG] [internal.handler.GardenaThingHandler] - Received Gardena command: START_OVERRIDE_TIMER
13-Okt-2019 15:33:44.959 [WARN ] [internal.handler.GardenaThingHandler] - Error 400 Bad Request
org.openhab.binding.gardena.internal.exception.GardenaException: Error 400 Bad Request
	at org.openhab.binding.gardena.internal.GardenaSmartImpl.executeRequest(GardenaSmartImpl.java:492) ~[253:org.openhab.binding.gardena:2.5.0.M3]
	at org.openhab.binding.gardena.internal.GardenaSmartImpl.sendCommand(GardenaSmartImpl.java:379) ~[253:org.openhab.binding.gardena:2.5.0.M3]
	at org.openhab.binding.gardena.internal.handler.GardenaThingHandler.handleCommand(GardenaThingHandler.java:228) [253:org.openhab.binding.gardena:2.5.0.M3]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
	at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:152) [133:org.openhab.core:2.5.0.M3]
	at org.eclipse.smarthome.core.internal.common.InvocationHandlerSync.invoke(InvocationHandlerSync.java:59) [133:org.openhab.core:2.5.0.M3]
	at com.sun.proxy.$Proxy902.handleCommand(Unknown Source) [?:?]
	at org.eclipse.smarthome.core.thing.internal.profiles.ProfileCallbackImpl.handleCommand(ProfileCallbackImpl.java:75) [184:org.openhab.core.thing:2.5.0.M3]
	at org.eclipse.smarthome.core.thing.internal.profiles.SystemDefaultProfile.onCommandFromItem(SystemDefaultProfile.java:49) [184:org.openhab.core.thing:2.5.0.M3]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
	at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:152) [133:org.openhab.core:2.5.0.M3]
	at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:53) [133:org.openhab.core:2.5.0.M3]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]
Caused by: org.openhab.binding.gardena.internal.exception.GardenaException: Error 400 Bad Request
	at org.openhab.binding.gardena.internal.GardenaSmartImpl.executeRequest(GardenaSmartImpl.java:473) ~[?:?]
	... 21 more
13-Okt-2019 15:53:01.174 [DEBUG] [internal.handler.GardenaThingHandler] - Received Gardena command: DURATION_PROPERTY
13-Okt-2019 15:53:03.601 [DEBUG] [internal.handler.GardenaThingHandler] - Received Gardena command: DURATION_PROPERTY
13-Okt-2019 15:53:15.917 [DEBUG] [internal.handler.GardenaThingHandler] - Received Gardena command: START_OVERRIDE_TIMER
13-Okt-2019 15:53:23.224 [DEBUG] [ng.gardena.internal.GardenaSmartImpl] - Refreshing gardena device data
13-Okt-2019 15:54:24.008 [DEBUG] [ng.gardena.internal.GardenaSmartImpl] - Refreshing gardena device data
```
And again the binding stops refreshing until next action.

**Comment by UrsusS** [comment]
Dear developers,
it's still some time until the next gardening season, but I would like to raise this issue again, as it is a serious problem for my setup.
When this happens, openHAB receives no new information from the lawn mower. So the system doesn't detect that the mower returns home. The door will not be opened and the mower crashes against the closed door.
Thanks for having a look at this topic!

**Comment by lukasvermeer** [comment]
I installed openHAB day before yesterday and ran into the same problem yesterday evening.

```
2020-05-23 19:28:20.424 [WARN ] [internal.handler.GardenaThingHandler] - Error 400 Bad Request
org.openhab.binding.gardena.internal.exception.GardenaException: Error 400 Bad Request
        at org.openhab.binding.gardena.internal.GardenaSmartImpl.executeRequest(GardenaSmartImpl.java:492) ~[bundleFile:?]
        at org.openhab.binding.gardena.internal.GardenaSmartImpl.sendCommand(GardenaSmartImpl.java:379) ~[bundleFile:?]
        at org.openhab.binding.gardena.internal.handler.GardenaThingHandler.handleCommand(GardenaThingHandler.java:228) [bundleFile:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_152]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_152]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_152]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_152]
        at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:152) [bundleFile:?]
        at org.eclipse.smarthome.core.internal.common.InvocationHandlerSync.invoke(InvocationHandlerSync.java:59) [bundleFile:?]
        at com.sun.proxy.$Proxy246.handleCommand(Unknown Source) [?:?]
        at org.eclipse.smarthome.core.thing.internal.profiles.ProfileCallbackImpl.handleCommand(ProfileCallbackImpl.java:74) [bundleFile:?]
        at org.eclipse.smarthome.core.thing.internal.profiles.SystemDefaultProfile.onCommandFromItem(SystemDefaultProfile.java:48) [bundleFile:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_152]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_152]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_152]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_152]
        at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:152) [bundleFile:?]
        at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:52) [bundleFile:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_152]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_152]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_152]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
Caused by: org.openhab.binding.gardena.internal.exception.GardenaException: Error 400 Bad Request
        at org.openhab.binding.gardena.internal.GardenaSmartImpl.executeRequest(GardenaSmartImpl.java:473) ~[bundleFile:?]
        ... 21 more
2020-05-23 19:28:21.448 [WARN ] [internal.handler.GardenaThingHandler] - Error 400 Bad Request
org.openhab.binding.gardena.internal.exception.GardenaException: Error 400 Bad Request
        at org.openhab.binding.gardena.internal.GardenaSmartImpl.executeRequest(GardenaSmartImpl.java:492) ~[bundleFile:?]
        at org.openhab.binding.gardena.internal.GardenaSmartImpl.sendCommand(GardenaSmartImpl.java:379) ~[bundleFile:?]
        at org.openhab.binding.gardena.internal.handler.GardenaThingHandler.handleCommand(GardenaThingHandler.java:228) [bundleFile:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_152]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_152]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_152]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_152]
        at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:152) [bundleFile:?]
        at org.eclipse.smarthome.core.internal.common.InvocationHandlerSync.invoke(InvocationHandlerSync.java:59) [bundleFile:?]
        at com.sun.proxy.$Proxy250.handleCommand(Unknown Source) [?:?]
        at org.eclipse.smarthome.core.thing.internal.profiles.ProfileCallbackImpl.handleCommand(ProfileCallbackImpl.java:74) [bundleFile:?]
        at org.eclipse.smarthome.core.thing.internal.profiles.SystemDefaultProfile.onCommandFromItem(SystemDefaultProfile.java:48) [bundleFile:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_152]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_152]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_152]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_152]
        at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:152) [bundleFile:?]
        at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:52) [bundleFile:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_152]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_152]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_152]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
Caused by: org.openhab.binding.gardena.internal.exception.GardenaException: Error 400 Bad Request
        at org.openhab.binding.gardena.internal.GardenaSmartImpl.executeRequest(GardenaSmartImpl.java:473) ~[bundleFile:?]
        ... 21 more

```

**Comment by UrsusS** [comment]
Today I had an Error 503 Service Unavailable.
Maybe Gardena had a problem, or ...

The real problem is, that the binding stopped refreshing the data. The same as with the other error.
Consequence as before -  mower tried to work by himself and was trapped in the garage.

**Comment by 9037568** [comment]
The `executeRequest()` method has been refactored in current code.
Someone should try to reproduce with the latest release of the binding and get a log with TRACE enabled.

**Comment by kaikreuzer** [comment]
As the binding has effectively been replaced by a rewrite, I suggest to close this issue.
