### ISSUE TITLE
[amazondashbutton] binding cannot start capture (claims missing permissions)

### ISSUE THREAD

**Issue by DrScheme** [openhab/openhab-addons#6146]
## Expected Behavior

Dashbuttons-Presses should get captured and discovered.

## Current Behavior

Since switching from 2.4.0-1 to 2.5.0-M2, 2.5.0-M3 and also 2.5.0-SNAPSHOT:
Although the user openhab is in a group pcap to be able to start tcpdump in promiscuous mode and java as well as karaf (to be sure this should work in debugging) have the proper capture-rights the following handle is always null.
```
    Pointer handle
      = NativeMappings.pcap_open_live(
          name,
          snaplen,
          mode.getValue(),
          timeoutMillis,
          errbuf
        );
```
```
15:26:27.288 [ERROR] [rnal.capturing.PacketCapturingService] - Capturing packets on device enp7s0 failed.
org.pcap4j.core.PcapNativeException: enp7s0: You don't have permission to capture on that device (socket: Vorgang nicht zulässig)
	at org.pcap4j.core.PcapNetworkInterface.openLive(PcapNetworkInterface.java:258) ~[?:?]
	at org.openhab.binding.amazondashbutton.internal.pcap.PcapNetworkInterfaceWrapper.openLive(PcapNetworkInterfaceWrapper.java:71) ~[?:?]
	at org.openhab.binding.amazondashbutton.internal.capturing.PacketCapturingService.startCapturing(PacketCapturingService.java:89) ~[?:?]
	at org.openhab.binding.amazondashbutton.internal.capturing.PacketCapturingService.startCapturing(PacketCapturingService.java:62) ~[?:?]
	at org.openhab.binding.amazondashbutton.internal.discovery.AmazonDashButtonDiscoveryService.startCapturing(AmazonDashButtonDiscoveryService.java:202) ~[?:?]
	at org.openhab.binding.amazondashbutton.internal.discovery.AmazonDashButtonDiscoveryService.onPcapNetworkInterfaceAdded(AmazonDashButtonDiscoveryService.java:142) ~[?:?]
	at org.openhab.binding.amazondashbutton.internal.pcap.PcapNetworkInterfaceService.notifyNetworkInterfacesAdded(PcapNetworkInterfaceService.java:145) ~[?:?]
	at org.openhab.binding.amazondashbutton.internal.pcap.PcapNetworkInterfaceService.notifyNetworkInterfacesAdded(PcapNetworkInterfaceService.java:132) ~[?:?]
	at org.openhab.binding.amazondashbutton.internal.pcap.PcapNetworkInterfaceService.lambda$0(PcapNetworkInterfaceService.java:69) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]

```
Interestingly i also get this exception (as pcap_open_live returns null) if i change the call to openLive in startCapturing to this:
`openLive(SNAPLEN, PromiscuousMode.NONPROMISCUOUS, READ_TIMEOUT);`

If i start openhab2 as root this does not happen, but the dashbuttons don't get discovered.
Actually no packets at all gets captured. A Breakpoint in packetCaptured doesn't get reached at all.

I can see the packets though in tcpdump:
```
openhab@bluesea:/usr/share/openhab2$ tcpdump | grep f2
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on enp7s0, link-type EN10MB (Ethernet), capture size 262144 bytes
15:23:27.080875 44:65:0d:44:5c:f2 (oui Unknown) > Broadcast Null Supervisory, Receiver not Ready, rcv seq 64, Flags [Poll], length 46
15:23:27.134634 IP 0.0.0.0.bootpc > 255.255.255.255.bootps: BOOTP/DHCP, Request from 44:65:0d:44:5c:f2 (oui Unknown), length 261

```

## Steps to Reproduce (for Bugs)

To get the exceptions:
1. Start openhab in Debug-Mode
2. log:tail in karaf
3. Start Discovery for Amazon Dashbuttons in PaperUI
3. exceptions with stacktrace in log

## Context

Trying to receive presses on my dashbuttons again.

## Your Environment

* Version used: (e.g., openhab and addon versions) openhab 2.5.0 M2, 2.5.0 M3, 2.5.0 SNAPSHOT (S1698, S1701)
* Environment name and version (e.g. Chrome 39, node.js 5.4, Java 8, ...): Java(TM) SE Runtime Environment (build 1.8.0_144-b01), libpcap0.8 (1.8.1-6ubuntu1)
* Operating System and version (desktop or mobile, Windows 10, Raspbian Jessie, ...): Ubuntu 18.04.3 LTS on AMD FX(tm)-8350 Eight-Core Processor

```
openhab@bluesea:/usr/share/openhab2$ getcap $(realpath /usr/bin/java)
/usr/lib/jvm/java-8-oracle/jre/bin/java = cap_net_admin,cap_net_raw+eip cap_net_bind_service+ep
openhab@bluesea:/usr/share/openhab2$ getcap /usr/share/openhab2/runtime/bin/karaf
/usr/share/openhab2/runtime/bin/karaf = cap_net_admin,cap_net_raw+eip
```
```
openhab@bluesea:/usr/share/openhab2$ ls -l /usr/sbin/tcpdump 
-rwxr-x--- 1 root pcap 1130096 Mär 31  2018 /usr/sbin/tcpdump
openhab@bluesea:/usr/share/openhab2$ id
uid=126(openhab) gid=135(openhab) Gruppen=135(openhab),5(tty),20(dialout),29(audio),115(bluetooth),1001(pcap)
```
```
openhab@bluesea:/usr/share/openhab2$ aptitude search libpcap
i   libpcap-dev                                                                                                    - development library for libpcap (transitional package)                                                                  
p   libpcap-dev:i386                                                                                               - development library for libpcap (transitional package)                                                                  
i   libpcap0.8                                                                                                     - system interface for user-level packet capture                                                                          
i A libpcap0.8:i386                                                                                                - system interface for user-level packet capture                                                                          
p   libpcap0.8-dbg                                                                                                 - debugging symbols for libpcap0.8                                                                                        
p   libpcap0.8-dbg:i386                                                                                            - debugging symbols for libpcap0.8                                                                                        
i A libpcap0.8-dev                                                                                                 - development library and header files for libpcap0.8                                                                     
p   libpcap0.8-dev:i386                                                                                            - development library and header files for libpcap0.8                                                                     
p   python-libpcap                                                                                                 - Python wrapper for libpcap packet capture library                                                                       
p   python-libpcap:i386                                                                                            - Python wrapper for libpcap packet capture library                                                                       
v   python2.7-libpcap                                                                                              -                                                                                                                         
v   python2.7-libpcap:i386                                                                                         -                                                                                                                         
```

**Comment by wborn** [comment]
Do you also have this issue with the most recent snapshot build (1702)?
Looks like the binding jna and pcap4j dependencies were recently updated in https://github.com/openhab/openhab2-addons/pull/6005.

**Comment by DrScheme** [comment]
1702 makes, no joke..., my whole system acting weired.... still have to figure out what is happening...

**Comment by wborn** [comment]
It seems some other bundles don't properly start and remain in the Waiting state. :-(

See also this [community thread](https://community.openhab.org/t/update-to-snapshot-1597-partially-failed-allplay-solved-amazondashbutton-wrapper-service-z-wave-solved/74930/70?u=wborn).

**Comment by DrScheme** [comment]
I just pulled openhab2-addons to switch back to 1701 and just replace the amazondashbutton-binding, but could not compile it (missing dependency):

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:44 min
[INFO] Finished at: 2019-09-29T15:38:58+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.karaf.tooling:karaf-maven-plugin:4.2.6:verify (karaf-feature-verification) on project org.openhab.binding.amazondashbutton: Feature resolution failed for [openhab-binding-amazondashbutton/2.5.0.SNAPSHOT]
[ERROR] Message: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=openhab-binding-amazondashbutton; type=karaf.feature; version=2.5.0.SNAPSHOT; filter:="(&(osgi.identity=openhab-binding-amazondashbutton)(type=karaf.feature)(version>=2.5.0.SNAPSHOT))" [caused by: Unable to resolve openhab-binding-amazondashbutton/2.5.0.SNAPSHOT: missing requirement [openhab-binding-amazondashbutton/2.5.0.SNAPSHOT] osgi.identity; osgi.identity=org.openhab.binding.amazondashbutton; type=osgi.bundle; version="[2.5.0.201909291338,2.5.0.201909291338]"; resolution:=mandatory [caused by: Unable to resolve org.openhab.binding.amazondashbutton/2.5.0.201909291338: missing requirement [org.openhab.binding.amazondashbutton/2.5.0.201909291338] osgi.wiring.package; filter:="(osgi.wiring.package=org.pcap4j.core)"]]
[ERROR] Repositories: {
[ERROR] 	file:/mnt/data/andre_data/devel/openhab2-addons/bundles/org.openhab.binding.amazondashbutton/target/feature/feature.xml
[ERROR] 	mvn:org.apache.karaf.features/framework/4.2.6/xml/features
[ERROR] 	mvn:org.apache.karaf.features/standard/4.2.6/xml/features
[ERROR] 	mvn:org.openhab.core.features.karaf/org.openhab.core.features.karaf.openhab-core/2.5.0-SNAPSHOT/xml/features
[ERROR] 	mvn:org.openhab.core.features.karaf/org.openhab.core.features.karaf.openhab-tp/2.5.0-SNAPSHOT/xml/features
[ERROR] 	mvn:org.ops4j.pax.web/pax-web-features/7.2.10/xml/features
[ERROR] }
[ERROR] Resources: {
[ERROR] 	mvn:com.eclipsesource.jaxrs/publisher/5.3.1
[ERROR] 	mvn:com.google.guava/guava/18.0
[ERROR] 	mvn:com.google.guava/guava/21.0
[ERROR] 	mvn:commons-codec/commons-codec/1.6
[ERROR] 	mvn:commons-collections/commons-collections/3.2.1
[ERROR] 	mvn:commons-io/commons-io/2.2
[ERROR] 	mvn:commons-lang/commons-lang/2.6
[ERROR] 	mvn:commons-net/commons-net/3.3
[ERROR] 	mvn:de.jollyday/jollyday/0.5.8
[ERROR] 	mvn:de.maggu2810.p2redist/com.google.inject/3.0.0.v201312141243
[ERROR] 	mvn:de.maggu2810.p2redist/org.antlr.runtime/3.2.0.v201101311130
[ERROR] 	mvn:javax.annotation/javax.annotation-api/1.2
[ERROR] 	mvn:javax.annotation/javax.annotation-api/1.3
[ERROR] 	mvn:javax.el/javax.el-api/3.0.0
[ERROR] 	mvn:javax.mail/mail/1.4.7
[ERROR] 	mvn:javax.measure/unit-api/1.0
[ERROR] 	mvn:javax.servlet/javax.servlet-api/3.1.0
[ERROR] 	mvn:javax.validation/validation-api/1.1.0.Final
[ERROR] 	mvn:javax.websocket/javax.websocket-api/1.1
[ERROR] 	mvn:javax.ws.rs/javax.ws.rs-api/2.0.1
[ERROR] 	mvn:joda-time/joda-time/2.9.2
[ERROR] 	mvn:net.java.dev.jna/jna/5.4.0
[ERROR] 	mvn:org.apache.aries.spifly/org.apache.aries.spifly.dynamic.bundle/1.2
[ERROR] 	mvn:org.apache.aries/org.apache.aries.util/1.1.3
[ERROR] 	mvn:org.apache.commons/commons-exec/1.1
[ERROR] 	mvn:org.apache.felix/org.apache.felix.configadmin/1.9.14
[ERROR] 	mvn:org.apache.felix/org.apache.felix.coordinator/1.0.2
[ERROR] 	mvn:org.apache.felix/org.apache.felix.fileinstall/3.6.4
[ERROR] 	mvn:org.apache.felix/org.apache.felix.inventory/1.0.4
[ERROR] 	mvn:org.apache.felix/org.apache.felix.metatype/1.2.2
[ERROR] 	mvn:org.apache.felix/org.apache.felix.scr/2.1.16
[ERROR] 	mvn:org.apache.felix/org.apache.felix.webconsole.plugins.ds/2.1.0
[ERROR] 	mvn:org.apache.felix/org.apache.felix.webconsole.plugins.event/1.1.8
[ERROR] 	mvn:org.apache.geronimo.specs/geronimo-jaspic_1.0_spec/1.1
[ERROR] 	mvn:org.apache.geronimo.specs/geronimo-jta_1.1_spec/1.1.1
[ERROR] 	mvn:org.apache.karaf.features/org.apache.karaf.features.core/4.2.6
[ERROR] 	mvn:org.apache.karaf.features/org.apache.karaf.features.extension/4.2.6
[ERROR] 	mvn:org.apache.karaf.http/org.apache.karaf.http.core/4.2.6
[ERROR] 	mvn:org.apache.karaf.jaas/org.apache.karaf.jaas.boot/4.2.6
[ERROR] 	mvn:org.apache.karaf.scr/org.apache.karaf.scr.management/4.2.6
[ERROR] 	mvn:org.apache.karaf.scr/org.apache.karaf.scr.state/4.2.6
[ERROR] 	mvn:org.apache.karaf.services/org.apache.karaf.services.eventadmin/4.2.6
[ERROR] 	mvn:org.apache.karaf.shell/org.apache.karaf.shell.commands/4.2.6
[ERROR] 	mvn:org.apache.karaf.shell/org.apache.karaf.shell.core/4.2.6
[ERROR] 	mvn:org.apache.karaf.webconsole/org.apache.karaf.webconsole.http/4.2.6
[ERROR] 	mvn:org.apache.karaf.wrapper/org.apache.karaf.wrapper.core/4.2.6
[ERROR] 	mvn:org.apache.karaf/org.apache.karaf.event/4.2.6
[ERROR] 	mvn:org.apache.servicemix.bundles/org.apache.servicemix.bundles.javax-inject/1_2
[ERROR] 	mvn:org.apache.servicemix.bundles/org.apache.servicemix.bundles.xstream/1.4.7_1
[ERROR] 	mvn:org.apache.servicemix.specs/org.apache.servicemix.specs.activation-api-1.1/2.9.0
[ERROR] 	mvn:org.apache.servicemix.specs/org.apache.servicemix.specs.jaxb-api-2.2/2.9.0
[ERROR] 	mvn:org.apache.xbean/xbean-bundleutils/4.12
[ERROR] 	mvn:org.apache.xbean/xbean-finder/4.12
[ERROR] 	mvn:org.apache.xbean/xbean-reflect/4.12
[ERROR] 	mvn:org.eclipse.emf/org.eclipse.emf.common/2.12.0
[ERROR] 	mvn:org.eclipse.emf/org.eclipse.emf.ecore.change/2.11.0
[ERROR] 	mvn:org.eclipse.emf/org.eclipse.emf.ecore.xmi/2.12.0
[ERROR] 	mvn:org.eclipse.emf/org.eclipse.emf.ecore/2.12.0
[ERROR] 	mvn:org.eclipse.jdt.core.compiler/ecj/4.5.1
[ERROR] 	mvn:org.eclipse.jetty.websocket/javax-websocket-client-impl/9.4.18.v20190429
[ERROR] 	mvn:org.eclipse.jetty.websocket/javax-websocket-server-impl/9.4.18.v20190429
[ERROR] 	mvn:org.eclipse.jetty.websocket/websocket-api/9.4.18.v20190429
[ERROR] 	mvn:org.eclipse.jetty.websocket/websocket-client/9.4.18.v20190429
[ERROR] 	mvn:org.eclipse.jetty.websocket/websocket-common/9.4.18.v20190429
[ERROR] 	mvn:org.eclipse.jetty.websocket/websocket-server/9.4.18.v20190429
[ERROR] 	mvn:org.eclipse.jetty.websocket/websocket-servlet/9.4.18.v20190429
[ERROR] 	mvn:org.eclipse.jetty/jetty-client/9.4.18.v20190429
[ERROR] 	mvn:org.eclipse.jetty/jetty-continuation/9.4.18.v20190429
[ERROR] 	mvn:org.eclipse.jetty/jetty-deploy/9.4.18.v20190429
[ERROR] 	mvn:org.eclipse.jetty/jetty-http/9.4.18.v20190429
[ERROR] 	mvn:org.eclipse.jetty/jetty-io/9.4.18.v20190429
[ERROR] 	mvn:org.eclipse.jetty/jetty-jaas/9.4.18.v20190429
[ERROR] 	mvn:org.eclipse.jetty/jetty-jaspi/9.4.18.v20190429
[ERROR] 	mvn:org.eclipse.jetty/jetty-jmx/9.4.18.v20190429
[ERROR] 	mvn:org.eclipse.jetty/jetty-jndi/9.4.18.v20190429
[ERROR] 	mvn:org.eclipse.jetty/jetty-plus/9.4.18.v20190429
[ERROR] 	mvn:org.eclipse.jetty/jetty-proxy/9.4.18.v20190429
[ERROR] 	mvn:org.eclipse.jetty/jetty-rewrite/9.4.18.v20190429
[ERROR] 	mvn:org.eclipse.jetty/jetty-security/9.4.18.v20190429
[ERROR] 	mvn:org.eclipse.jetty/jetty-server/9.4.18.v20190429
[ERROR] 	mvn:org.eclipse.jetty/jetty-servlet/9.4.18.v20190429
[ERROR] 	mvn:org.eclipse.jetty/jetty-servlets/9.4.18.v20190429
[ERROR] 	mvn:org.eclipse.jetty/jetty-util-ajax/9.4.18.v20190429
[ERROR] 	mvn:org.eclipse.jetty/jetty-util/9.4.18.v20190429
[ERROR] 	mvn:org.eclipse.jetty/jetty-webapp/9.4.18.v20190429
[ERROR] 	mvn:org.eclipse.jetty/jetty-xml/9.4.18.v20190429
[ERROR] 	mvn:org.eclipse.lsp4j/org.eclipse.lsp4j.jsonrpc/0.6.0
[ERROR] 	mvn:org.eclipse.lsp4j/org.eclipse.lsp4j/0.6.0
[ERROR] 	mvn:org.eclipse.orbit.bundles/com.google.gson/2.8.2.v20180104-1110
[ERROR] 	mvn:org.eclipse.platform/org.eclipse.equinox.common/3.9.0
[ERROR] 	mvn:org.eclipse.platform/org.eclipse.equinox.registry/3.6.100
[ERROR] 	mvn:org.eclipse.platform/org.eclipse.equinox.supplement/1.6.100
[ERROR] 	mvn:org.eclipse.xtend/org.eclipse.xtend.lib.macro/2.17.0
[ERROR] 	mvn:org.eclipse.xtend/org.eclipse.xtend.lib/2.17.0
[ERROR] 	mvn:org.eclipse.xtext/org.eclipse.xtext.common.types/2.17.0
[ERROR] 	mvn:org.eclipse.xtext/org.eclipse.xtext.ide/2.17.0
[ERROR] 	mvn:org.eclipse.xtext/org.eclipse.xtext.smap/2.17.0
[ERROR] 	mvn:org.eclipse.xtext/org.eclipse.xtext.util/2.17.0
[ERROR] 	mvn:org.eclipse.xtext/org.eclipse.xtext.xbase.ide/2.17.0
[ERROR] 	mvn:org.eclipse.xtext/org.eclipse.xtext.xbase.lib/2.17.0
[ERROR] 	mvn:org.eclipse.xtext/org.eclipse.xtext.xbase/2.17.0
[ERROR] 	mvn:org.eclipse.xtext/org.eclipse.xtext/2.17.0
[ERROR] 	mvn:org.fusesource.jansi/jansi/1.18
[ERROR] 	mvn:org.glassfish.hk2.external/aopalliance-repackaged/2.4.0-b34
[ERROR] 	mvn:org.glassfish.hk2.external/javax.inject/2.4.0-b34
[ERROR] 	mvn:org.glassfish.hk2/hk2-api/2.4.0-b34
[ERROR] 	mvn:org.glassfish.hk2/hk2-locator/2.4.0-b34
[ERROR] 	mvn:org.glassfish.hk2/hk2-utils/2.4.0-b34
[ERROR] 	mvn:org.glassfish.hk2/osgi-resource-locator/1.0.1
[ERROR] 	mvn:org.glassfish.jersey.bundles.repackaged/jersey-guava/2.22.2
[ERROR] 	mvn:org.glassfish.jersey.containers/jersey-container-servlet-core/2.22.2
[ERROR] 	mvn:org.glassfish.jersey.containers/jersey-container-servlet/2.22.2
[ERROR] 	mvn:org.glassfish.jersey.core/jersey-client/2.22.2
[ERROR] 	mvn:org.glassfish.jersey.core/jersey-common/2.22.2
[ERROR] 	mvn:org.glassfish.jersey.core/jersey-server/2.22.2
[ERROR] 	mvn:org.glassfish.jersey.media/jersey-media-jaxb/2.22.2
[ERROR] 	mvn:org.glassfish.jersey.media/jersey-media-multipart/2.22.2
[ERROR] 	mvn:org.glassfish.jersey.media/jersey-media-sse/2.22.2
[ERROR] 	mvn:org.javassist/javassist/3.18.1-GA
[ERROR] 	mvn:org.jline/jline-builtins/3.11.0
[ERROR] 	mvn:org.jline/jline-reader/3.11.0
[ERROR] 	mvn:org.jline/jline-terminal-jansi/3.11.0
[ERROR] 	mvn:org.jline/jline-terminal/3.11.0
[ERROR] 	mvn:org.jmdns/jmdns/3.5.5
[ERROR] 	mvn:org.jvnet.mimepull/mimepull/1.9.6
[ERROR] 	mvn:org.mapdb/mapdb/1.0.9
[ERROR] 	mvn:org.openhab.addons.bundles/org.openhab.binding.amazondashbutton/2.5.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.audio/2.5.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.auth.oauth2client/2.5.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.binding.xml/2.5.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.boot/2.5.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.config.core/2.5.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.config.discovery.mdns/2.5.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.config.discovery/2.5.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.config.dispatch/2.5.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.config.xml/2.5.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.ephemeris/2.5.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.id/2.5.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.io.console.karaf/2.5.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.io.console/2.5.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.io.http/2.5.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.io.jetty.certificate/2.5.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.io.monitor/2.5.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.io.net/2.5.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.io.rest.audio/2.5.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.io.rest.core/2.5.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.io.rest.mdns/2.5.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.io.rest.optimize/2.5.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.io.rest.sitemap/2.5.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.io.rest.sse/2.5.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.io.rest.voice/2.5.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.io.rest/2.5.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.io.transport.mdns/2.5.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.karaf/2.5.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.model.core/2.5.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.model.item.ide/2.5.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.model.item.runtime/2.5.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.model.item/2.5.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.model.lsp/2.5.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.model.persistence.ide/2.5.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.model.persistence.runtime/2.5.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.model.persistence/2.5.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.model.rule.ide/2.5.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.model.rule.runtime/2.5.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.model.rule/2.5.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.model.script.ide/2.5.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.model.script.runtime/2.5.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.model.script/2.5.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.model.sitemap.ide/2.5.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.model.sitemap.runtime/2.5.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.model.sitemap/2.5.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.model.thing.ide/2.5.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.model.thing.runtime/2.5.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.model.thing/2.5.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.persistence/2.5.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.scheduler/2.5.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.semantics/2.5.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.storage.json/2.5.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.storage.mapdb/2.5.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.thing.xml/2.5.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.thing/2.5.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.transform/2.5.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.ui.icon/2.5.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.ui/2.5.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core.voice/2.5.0-SNAPSHOT
[ERROR] 	mvn:org.openhab.core.bundles/org.openhab.core/2.5.0-SNAPSHOT
[ERROR] 	mvn:org.ops4j.pax.logging/pax-logging-api/1.10.2
[ERROR] 	mvn:org.ops4j.pax.logging/pax-logging-log4j2/1.10.2
[ERROR] 	mvn:org.ops4j.pax.url/pax-url-aether/2.6.1
[ERROR] 	mvn:org.ops4j.pax.web/pax-web-api/7.2.10
[ERROR] 	mvn:org.ops4j.pax.web/pax-web-extender-whiteboard/7.2.10
[ERROR] 	mvn:org.ops4j.pax.web/pax-web-jetty/7.2.10
[ERROR] 	mvn:org.ops4j.pax.web/pax-web-jsp/7.2.10
[ERROR] 	mvn:org.ops4j.pax.web/pax-web-runtime/7.2.10
[ERROR] 	mvn:org.ops4j.pax.web/pax-web-spi/7.2.10
[ERROR] 	mvn:org.osgi/org.osgi.util.function/1.0.0
[ERROR] 	mvn:org.osgi/org.osgi.util.promise/1.0.0
[ERROR] 	mvn:org.ow2.asm/asm-analysis/7.1
[ERROR] 	mvn:org.ow2.asm/asm-commons/7.1
[ERROR] 	mvn:org.ow2.asm/asm-tree/7.1
[ERROR] 	mvn:org.ow2.asm/asm-util/7.1
[ERROR] 	mvn:org.ow2.asm/asm/7.0
[ERROR] 	mvn:org.ow2.asm/asm/7.1
[ERROR] 	mvn:org.threeten/threeten-extra/1.4
[ERROR] 	mvn:tec.uom.lib/uom-lib-common/1.0.3
[ERROR] 	mvn:tec.uom/uom-se/1.0.10
[ERROR] }
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by DrScheme** [comment]
Switched back to 1701 and used the precompiled bundle you linked in the other thread (https://openhab.jfrog.io/openhab/online-repo-snapshot/2.5/org/openhab/addons/bundles/org.openhab.binding.amazondashbutton/2.5.0-SNAPSHOT/org.openhab.binding.amazondashbutton-2.5.0-SNAPSHOT.jar).

But that gave me:
```
2019-09-29 16:10:50.071 [ERROR] [org.openhab.binding.amazondashbutton] - FrameworkEvent ERROR - org.openhab.binding.amazondashbutton

org.osgi.framework.BundleException: Could not resolve module: org.openhab.binding.amazondashbutton [211]

  Unresolved requirement: Import-Package: com.sun.jna; version="[5.4.0,6.0.0)"

	at org.eclipse.osgi.container.Module.start(Module.java:444) ~[?:?]

	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1634) ~[?:?]

	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1614) ~[?:?]

	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1585) ~[?:?]

	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1528) ~[?:?]

	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1) ~[?:?]

	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230) [?:?]

	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340) [?:?]
```

**Comment by wborn** [comment]
There’s now a # 1704 build with a fix so those bundles should no longer remain in the “Waiting” state.

**Comment by J-N-K** [comment]
You need to install jna manually if you don‘t use the feature.

**Comment by DrScheme** [comment]
It's working again in Snapshot 1704
