### ISSUE TITLE
[RFXCom] [rfxtrx433xl] read error - RFXComStreamReader Connector died: java.lang.IndexOutOfBoundsException 

### ISSUE THREAD

**Issue by patrickstephan** [openhab/openhab-addons#6162]
Hello,

I am facing read issues with RFXCom. Below are the details.

## Expected Behavior
Following a restart of the Raspberry everything works as expected and DEBUG and TRACE logs show correctly the messages captured by the RFXCom for the different 433MHz Things.

## Current Behavior
After a period of time, the below show in /var/log/openhab2/openhab.log TRACE logs:
```
2019-09-25 23:25:19.369 [DEBUG] [g.rfxcom.handler.RFXComBridgeHandler] - Checking RFXCOM transceiver connection, thing status = ONLINE
2019-09-25 23:26:19.372 [DEBUG] [g.rfxcom.handler.RFXComBridgeHandler] - Checking RFXCOM transceiver connection, thing status = ONLINE
2019-09-25 23:27:19.374 [DEBUG] [g.rfxcom.handler.RFXComBridgeHandler] - Checking RFXCOM transceiver connection, thing status = ONLINE
2019-09-25 23:28:05.084 [TRACE] [rnal.connector.RFXComSerialConnector] - RXTX library CPU load workaround, sleep forever
2019-09-25 23:28:05.082 [ERROR] [nternal.connector.RFXComStreamReader] - Connector died:
java.lang.IndexOutOfBoundsException: null
        at gnu.io.RXTXPort$SerialInputStream.read(RXTXPort.java:1383) ~[?:?]
        at org.openhab.binding.rfxcom.internal.connector.RFXComBaseConnector.read(RFXComBaseConnector.java:63) ~[?:?]
        at org.openhab.binding.rfxcom.internal.connector.RFXComStreamReader.processMessage(RFXComStreamReader.java:81) ~[?:?]
        at org.openhab.binding.rfxcom.internal.connector.RFXComStreamReader.run(RFXComStreamReader.java:61) ~[?:?]
2019-09-25 23:28:19.377 [DEBUG] [g.rfxcom.handler.RFXComBridgeHandler] - Checking RFXCOM transceiver connection, thing status = ONLINE
2019-09-25 23:29:19.379 [DEBUG] [g.rfxcom.handler.RFXComBridgeHandler] - Checking RFXCOM transceiver connection, thing status = ONLINE
2019-09-25 23:30:19.381 [DEBUG] [g.rfxcom.handler.RFXComBridgeHandler] - Checking RFXCOM transceiver connection, thing status = ONLINE
2019-09-25 23:31:19.384 [DEBUG] [g.rfxcom.handler.RFXComBridgeHandler] - Checking RFXCOM transceiver connection, thing status = ONLINE
```
**Beyond this point 433 MHz transmitted messages by Things are no more read as before.**
Transmission of 433MHz towards Things continues to work as expected. Reading from Things only is impacted.
Note that I was unable to determine this period (after restart) or the trigger for the above error, yet the logs mention “RXTX library CPU load workaround, sleep forever” which I am unsure of the meaning and if it's directly related. 

## Possible Solution
- A first possible workaround **that only delays the issue** so far seems to be by turning off some unnecessary listening channels on the RFXCom (Kept on are: Lightning4, Blinds -both, X10) This seems to delay the issue from happening only. 
- A second possible workaround would be to manually restart the needed service when it goes down (will appreciate any help in coding this). 
- Both of the above are possible workarounds for the issue and not solutions. 

## Steps to Reproduce (for Bugs)
- Standard installation of OpenHab2 in the below mentioned environment. 
- Activate RFXCom rfxtrx433xl all listening channels 

## Context
OpenHab fails to receive 433MHz messages and execute needed actions.
Link to community post i made regarding this: [here](https://community.openhab.org/t/rfxcom-read-error-rfxcomstreamreader-connector-died-java-lang-indexoutofboundsexception/82624)

## Environment
I am running OpenHab 2.4.0 on Raspberry Pi 4 (4G Ram version) with RFXCom RFXtrx433XL running firmware version 1041. The RFXCom is connected to serial port /dev/ttyUSB0.
This is running Java openjdk version "1.8.0_222". 
A ZWave USB binding is also attached. 
All Config Parameters are set to on for the RFXCom (Undecoded Messages, Blinds1, etc...)

**Comment by wborn** [comment]
This issue might already have been fixed by #6143.

**Comment by lolodomo** [comment]
@patrickstephan : was your problem solved in recent versions ?

**Comment by patrickstephan** [comment]
This indeed was fixed.

**Comment by lolodomo** [comment]
Good
