### ISSUE TITLE
[modbus] ModbusDataHandlerTest and ModbusPollerThingHandlerTest fail due to removed thingRegistry field

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-addons#6171]
The build is broken because https://github.com/openhab/openhab-core/pull/1041 removed the `thingRegistry` field from the `BaseThingHandler` and `ModbusDataHandlerTest` depended on it for reflection tricks.

See https://api.travis-ci.org/v3/job/593557047/log.txt

```
[ERROR] testCoilDoesNotAcceptFloat32ValueType(org.openhab.binding.modbus.internal.ModbusDataHandlerTest)  Time elapsed: 0.006 s  <<< ERROR!
java.lang.RuntimeException: java.lang.NoSuchFieldException: thingRegistry
	at org.openhab.binding.modbus.internal.ModbusDataHandlerTest.hookThingRegistry(ModbusDataHandlerTest.java:298)
	at org.openhab.binding.modbus.internal.ModbusDataHandlerTest.createDataHandler(ModbusDataHandlerTest.java:414)
	at org.openhab.binding.modbus.internal.ModbusDataHandlerTest.createDataHandler(ModbusDataHandlerTest.java:382)
	at org.openhab.binding.modbus.internal.ModbusDataHandlerTest.createDataHandler(ModbusDataHandlerTest.java:377)
	at org.openhab.binding.modbus.internal.ModbusDataHandlerTest.testValueTypeGeneric(ModbusDataHandlerTest.java:997)
	at org.openhab.binding.modbus.internal.ModbusDataHandlerTest.testCoilDoesNotAcceptFloat32ValueType(ModbusDataHandlerTest.java:1004)
Caused by: java.lang.NoSuchFieldException: thingRegistry
	at org.openhab.binding.modbus.internal.ModbusDataHandlerTest.hookThingRegistry(ModbusDataHandlerTest.java:294)
	at org.openhab.binding.modbus.internal.ModbusDataHandlerTest.createDataHandler(ModbusDataHandlerTest.java:414)
	at org.openhab.binding.modbus.internal.ModbusDataHandlerTest.createDataHandler(ModbusDataHandlerTest.java:382)
	at org.openhab.binding.modbus.internal.ModbusDataHandlerTest.createDataHandler(ModbusDataHandlerTest.java:377)
	at org.openhab.binding.modbus.internal.ModbusDataHandlerTest.testValueTypeGeneric(ModbusDataHandlerTest.java:997)
	at org.openhab.binding.modbus.internal.ModbusDataHandlerTest.testCoilDoesNotAcceptFloat32ValueType(ModbusDataHandlerTest.java:1004)
```

https://github.com/openhab/openhab2-addons/blob/999500c7df93095f8c7e940ccada38437173d858/bundles/org.openhab.binding.modbus/src/test/java/org/openhab/binding/modbus/internal/ModbusPollerThingHandlerTest.java#L148-L153

Do you know of an easy fix @ssalonen or shall we disable it for now?

**Comment by ssalonen** [comment]
Please disable the test for now, I will need to look how to fix it with time.

Perhaps it is time to convert it to an proper osgi test instead of relying on private internals
