### ISSUE TITLE
[nanoleaf] Nanoleaf Light Panels - Status: OFFLINE Runtime error.

### ISSUE THREAD

**Issue by skosyi** [openhab/openhab-addons#6221]
Nanoleaf Light Panels - Status: OFFLINE Runtime error.
binding: Nanoleaf Binding (nanoleaf)

## Expected Behavior
Setup nanoleaf device

## Current Behavior
Can't setup nanoleaf binding - item shown as 'offline'

## Steps to Reproduce (for Bugs)
1. go to 'inbox'
2. click '+' add 'nanoleaf binding'
3. select discovered nanoleaf device (enable pairing device mode)
4. go to 'configuration' > 'things' observe 
Nanoleaf Light Panels XX:XX:XX
Status: OFFLINE Runtime error. See openHAB log for more details.

## Context
trying to setup new binding for nanoleaf

## Your Environment
* Version used: 2.5.0.M3
* Environment name and version: Chrome 77, Java 8
* Operating System and version: desktop, Windows 10

```
23:04:56.920 [WARN ] [nal.handler.NanoleafControllerHandler] - Update job failed
java.lang.NullPointerException: null
        at org.openhab.binding.nanoleaf.internal.handler.NanoleafControllerHandler.updateFromControllerInfo(NanoleafControllerHandler.java:449) ~[?:?]
        at org.openhab.binding.nanoleaf.internal.handler.NanoleafControllerHandler.runUpdate(NanoleafControllerHandler.java:315) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
        at java.lang.Thread.run(Thread.java:748) [?:?]
```

**Comment by raepple** [comment]
Should be fixed with https://github.com/openhab/openhab2-addons/pull/6270.

**Comment by kaikreuzer** [comment]
Confirmed fixed.
