### ISSUE TITLE
[homematic] Only percentages from 0 to 100 are accepted - homematic needs -1 too

### ISSUE THREAD

**Issue by henrydiesner** [openhab/openhab-addons#6360]
## Expected Behavior
openHAB accept percent values only between 0 and 100. But from homematic came percentages from -1 to 100:
![grafik](https://user-images.githubusercontent.com/5823795/68489088-afe1d280-0246-11ea-9bcc-c78d6a06bb3b.png)

## Current Behavior
No error in the log file in this case.

## Possible Solution
Do not limit percentages.

## Context
See the issue in homematic: [https://github.com/jens-maus/RaspberryMatic/issues/737](url)

## Your Environment
Newest stable openHAB on NUC with Debian 10
RaspberryMatic

**Comment by kaikreuzer** [comment]
> Do not limit percentages.

That's definitely not the right solution, see also https://github.com/jens-maus/RaspberryMatic/issues/737#issuecomment-551886103.
The binding simply must not send the -1 to the channel - it can either ignore it or set the Thing to offline or do whatever the exact semantic meaning of that value is.

**Comment by MHerbst** [comment]
@henrydiesner I have added support for a duty cycle value of -1 and the bridge state will be set to offline while the value is -1. I have  uploaded a  test jar here: https://github.com/MHerbst/openhab-addons-test

**Comment by henrydiesner** [comment]
Sorry for my late replay!
I've installed the new version of the homematic binding as described from MHerbst but I have always the same issue in my logfile:
2020-08-11 17:19:08.418 [ERROR] [ternal.handler.HomematicThingHandler] - Value must be between 0 and 100
java.lang.IllegalArgumentException: Value must be between 0 and 100
	at org.eclipse.smarthome.core.library.types.PercentType.validateValue(PercentType.java:57) ~[bundleFile:?]
	at org.eclipse.smarthome.core.library.types.PercentType.<init>(PercentType.java:52) ~[bundleFile:?]
	at org.eclipse.smarthome.core.library.types.QuantityType.as(QuantityType.java:317) ~[bundleFile:?]
	at org.eclipse.smarthome.core.internal.items.ItemStateConverterImpl.convertToAcceptedState(ItemStateConverterImpl.java:64) ~[?:?]
	at org.eclipse.smarthome.core.thing.internal.profiles.ProfileCallbackImpl.sendUpdate(ProfileCallbackImpl.java:134) ~[bundleFile:?]
	at org.eclipse.smarthome.core.thing.internal.profiles.SystemDefaultProfile.onStateUpdateFromHandler(SystemDefaultProfile.java:53) ~[bundleFile:?]
	at org.eclipse.smarthome.core.thing.internal.CommunicationManager.lambda$9(CommunicationManager.java:467) ~[bundleFile:?]
	at org.eclipse.smarthome.core.thing.internal.CommunicationManager.lambda$11(CommunicationManager.java:487) ~[bundleFile:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_252]
	at org.eclipse.smarthome.core.thing.internal.CommunicationManager.handleCallFromHandler(CommunicationManager.java:483) ~[bundleFile:?]
	at org.eclipse.smarthome.core.thing.internal.CommunicationManager.stateUpdated(CommunicationManager.java:465) ~[bundleFile:?]
	at org.eclipse.smarthome.core.thing.internal.ThingManagerImpl$1.stateUpdated(ThingManagerImpl.java:168) ~[bundleFile:?]
	at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.updateState(BaseThingHandler.java:245) ~[bundleFile:?]
	at org.openhab.binding.homematic.internal.handler.HomematicThingHandler.updateChannelState(HomematicThingHandler.java:380) ~[bundleFile:?]
	at org.openhab.binding.homematic.internal.handler.HomematicThingHandler.updateDatapointState(HomematicThingHandler.java:353) ~[bundleFile:?]
	at org.openhab.binding.homematic.internal.handler.HomematicBridgeHandler.onStateUpdated(HomematicBridgeHandler.java:284) ~[bundleFile:?]
	at org.openhab.binding.homematic.internal.communicator.AbstractHomematicGateway.lambda$1(AbstractHomematicGateway.java:742) ~[bundleFile:?]
	at org.openhab.binding.homematic.internal.misc.DelayedExecuter.start(DelayedExecuter.java:65) [bundleFile:?]
	at org.openhab.binding.homematic.internal.communicator.AbstractHomematicGateway.eventReceived(AbstractHomematicGateway.java:739) [bundleFile:?]
	at org.openhab.binding.homematic.internal.communicator.server.RpcResponseHandler.handleEvent(RpcResponseHandler.java:98) [bundleFile:?]
	at org.openhab.binding.homematic.internal.communicator.server.RpcResponseHandler.handleMethodCall(RpcResponseHandler.java:51) [bundleFile:?]
	at org.openhab.binding.homematic.internal.communicator.server.RpcResponseHandler.handleMethodCall(RpcResponseHandler.java:68) [bundleFile:?]
	at org.openhab.binding.homematic.internal.communicator.server.XmlRpcServer$ResponseHandler.handle(XmlRpcServer.java:125) [bundleFile:?]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) [bundleFile:9.4.20.v20190813]
	at org.eclipse.jetty.server.Server.handle(Server.java:494) [bundleFile:9.4.20.v20190813]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:374) [bundleFile:9.4.20.v20190813]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:268) [bundleFile:9.4.20.v20190813]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) [bundleFile:9.4.20.v20190813]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103) [bundleFile:9.4.20.v20190813]
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117) [bundleFile:9.4.20.v20190813]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336) [bundleFile:9.4.20.v20190813]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313) [bundleFile:9.4.20.v20190813]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171) [bundleFile:9.4.20.v20190813]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129) [bundleFile:9.4.20.v20190813]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:367) [bundleFile:9.4.20.v20190813]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:782) [bundleFile:9.4.20.v20190813]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:918) [bundleFile:9.4.20.v20190813]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
2020-08-11 17:19:12.670 [WARN ] [ternal.handler.HomematicThingHandler] - Value must be between 0 and 100
...

What's getting wrong on my openHAB?

**Comment by MHerbst** [comment]
@henrydiesner I seems that my fix was not sufficient. There seems to be another data point that causes this problem. Can you enable Trace mode and test whether it produces some relevant output? 
But maybe I will have to add some additional trace output to the binding. Will have a look a bit later and probably publish a new test jar.

**Comment by henrydiesner** [comment]
@MHerbst: I made a file with a homematic TRACE: 
[2020-08-11 18:16:44.913 [TRACE] .txt](https://github.com/openhab/openhab-addons/files/5058121/2020-08-11.18.16.44.913.TRACE.txt)
I hope that helps. 
Many thanks for your help!!!

**Comment by MHerbst** [comment]
@henrydiesner Unfortunately the log does not contain the exception. I have created a new test version (https://github.com/MHerbst/openhab-addons-test) that catches the exception and prints an error message with additional information instead. You can set the log level back to INFO or a higher value. After some time please check the log for error messages starting with: "Invalid value" and post the message.

**Comment by henrydiesner** [comment]
@MHerbst Here is the message: 2020-08-11 19:47:48.813 [ERROR] [ternal.handler.HomematicThingHandler] - Invalid Value: Value must be between 0 and 100::HmDatapoint[name=COLOR,value=103,defaultValue=0,type=INTEGER,minValue=0,maxValue=255,step=<null>,options=<null>,readOnly=false,readable=true,unit=<null>,description=COLOR,info=<null>,paramsetType=VALUES,virtual=false,trigger=false]

A data point with the name "COLOR" ??

**Comment by MHerbst** [comment]
@henrydiesner This is interesting. Do you have any HM LEDs where you can set the color? I have searched the HmIP device doc for data points named COLOR. I have found e.g. BSL_V1. But is weird that a percent type is used for this data point.

Maybe I can enhance tomorrow the message to get more information about the device that has got this data point.

**Comment by henrydiesner** [comment]
@MHerbst May be I found it:
![image](https://user-images.githubusercontent.com/5823795/89950006-0a222080-dc29-11ea-8a31-4d7893f2d7a6.png)
The HM-LC-RGBW-WM NEQ0675181:2 is the color value who generate the issue:
2020-08-11 23:11:54.908 [ERROR] [ternal.handler.HomematicThingHandler] - Invalid Value: Value must be between 0 and 100::HmDatapoint[name=COLOR,value=**86**,defaultValue=0,type=INTEGER,minValue=0,maxValue=255,step=<null>,options=<null>,readOnly=false,readable=true,unit=<null>,description=COLOR,info=<null>,paramsetType=VALUES,virtual=false,trigger=false]
The value **86** is the color you see in the picture.
![image](https://user-images.githubusercontent.com/5823795/89950344-bb28bb00-dc29-11ea-89ff-86789aafb170.png)
But why is it restricted between 0 an 100?

**Comment by MHerbst** [comment]
@henrydiesner The definiton of a "PercentType" for this data point is definitely wrong. I have to investigate why this happens. Please create a new issue for this problem because it has a different cause than the original issue.
