### ISSUE TITLE
[hyperion] Binding not working due to NPE in HyperionNgHandler

### ISSUE THREAD

**Issue by petterkatt** [openhab/openhab-addons#6377]
## Expected Behavior
Thing shows up as online, however Im unable to control my Hyperion-ng server using OpenHAB.
Tested using both thing and item files as well as PaperUI.

## Current Behavior
Following shows up in the log:
```
2019-11-11 19:18:00.826 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception: 

java.lang.NullPointerException: null

	at org.openhab.binding.hyperion.internal.handler.HyperionNgHandler.updateHyperion(HyperionNgHandler.java:260) ~[?:?]

	at org.openhab.binding.hyperion.internal.handler.HyperionNgHandler.handleServerInfoResponse(HyperionNgHandler.java:178) ~[?:?]

	at org.openhab.binding.hyperion.internal.handler.HyperionNgHandler$1.run(HyperionNgHandler.java:103) ~[?:?]

	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:?]

	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[?:?]

	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[?:?]

	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[?:?]

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]

	at java.lang.Thread.run(Thread.java:748) [?:?]
```

## Steps to Reproduce (for Bugs)
1. Install binding
2. Set up Thing
3. Try to control Hyperion-ng

## Your Environment

* Version used: 2.5.0M4 (Both OpenHAB and Hyperion Binding)
* Environment name and version (openjdk version "1.8.0_232")
OpenJDK Runtime Environment (Zulu 8.42.0.23-CA-linux64) (build 1.8.0_232-b18)
OpenJDK 64-Bit Server VM (Zulu 8.42.0.23-CA-linux64) (build 25.232-b18, mixed mode)
* Operating System and version (Ubuntu 18.04.3 LTS):

**Comment by wborn** [comment]
Maybe @tavalin can help fixing this NPE?

Looks like the `hyperion` value in the server response is `null`:

https://github.com/openhab/openhab2-addons/blob/99e8cbb39c313719a7aef04bddbf46a371611b29/bundles/org.openhab.binding.hyperion/src/main/java/org/openhab/binding/hyperion/internal/handler/HyperionNgHandler.java#L173-L178

**Comment by posseydon6891** [comment]
Hi,

I just hit this issue while migrating from `hyperion` to `hyperionNG`, alpha6 release. NPE can be seen in OH log and no state updates follow:
```
2020-06-10 22:50:58.777 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception:
java.lang.NullPointerException: null
        at org.openhab.binding.hyperion.internal.handler.HyperionNgHandler.updateHyperion(HyperionNgHandler.java:260) ~[?:?]
        at org.openhab.binding.hyperion.internal.handler.HyperionNgHandler.handleServerInfoResponse(HyperionNgHandler.java:178) ~[?:?]
        at org.openhab.binding.hyperion.internal.handler.HyperionNgHandler$1.run(HyperionNgHandler.java:103) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_232]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[?:1.8.0_232]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_232]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[?:1.8.0_232]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_232]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_232]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
```
As Daniel (@tavalin) discussed in [97747](https://community.openhab.org/t/multiple-state-issues-with-hyperion-ng-binding/97747), Hyperion API was changed and the "hyperion" object seems to be missing in serverInfo response (hence NPE after deserialization). Example response from my NG server: [serverInfo.txt](https://github.com/openhab/openhab-addons/files/4765896/serverInfo.txt)

According to API [docs](https://docs.hyperion-project.org/en/json/ServerInfo.html#components), now HyperionNG state "as a whole" is handled by special component called "ALL".

![Screenshot_20200611_180323](https://user-images.githubusercontent.com/66778456/84409584-e97c2100-ac0d-11ea-9d8e-dda0d8bd05fc.png)

For test, I removed the channel "state" logic from "updateHyperion" and added it to "updateComponent" in HyperionNgHandler.java, rebuilt binding and now testing it. If it works, I will try to go ahead with PR.
