### ISSUE TITLE
[dlinksmarthome] openHAB 2.5 does not work due to build changes

### ISSUE THREAD

**Issue by MikeJMajor** [openhab/openhab-addons#6439]
The D-Link Smart Home binding does not work on 2.5 and throws a SOAPException during initialisation due to problems with SAAJMetaFactoryImpl.

```csv
2019-11-18 11:00:51.171 [DEBUG] [home.internal.DLinkHNAPCommunication] - DLinkHNAPCommunication - Internal error
javax.xml.soap.SOAPException: Unable to create message factory for SOAP: Unable to create SAAJ meta-factory: com.sun.xml.internal.messaging.saaj.soap.SAAJMetaFactoryImpl cannot be cast to javax.xml.soap.SAAJMetaFactory
        at javax.xml.soap.MessageFactory.newInstance(MessageFactory.java:120) ~[bundleFile:1.4.0]
        at org.openhab.binding.dlinksmarthome.internal.DLinkHNAPCommunication.<init>(DLinkHNAPCommunication.java:160) [bundleFile:?]
        at org.openhab.binding.dlinksmarthome.internal.motionsensor.DLinkMotionSensorCommunication.<init>(DLinkMotionSensorCommunication.java:154) [bundleFile:?]
```
I believe this is due to the new build system since SOAP and SAAJ are now listed as dependencies. As far as I can see there have been no actual code changes to the binding in 2.5 and I've confirmed the 2.4 binding works on OH 2.5 when dropped into the addons folder. 

[D-Link Smart Home Binding - DCH-S150](https://community.openhab.org/t/d-link-smart-home-binding-dch-s150/83883)

**Comment by MikeJMajor** [comment]
@J-N-K do you have any ideas on how to fix this?

When I look in Karaf I don't the saaj-impl bundle loaded. If I try and load it manually it has an unresolved dependency.

**Comment by MikeJMajor** [comment]
After many hours of trial and error I've got something working, but I'm not sure its the correct way.

pom.xml becomes:
```csv
<properties>
    <bnd.importpackage>!javax.xml.soap, com.sun.xml.messaging.saaj.soap</bnd.importpackage>
  </properties>

  <dependencies>
    <!-- JAX-WS -->
    <dependency>
      <groupId>org.apache.servicemix.specs</groupId>
      <artifactId>org.apache.servicemix.specs.saaj-api-1.3</artifactId>
      <version>2.9.0</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.apache.servicemix.bundles</groupId>
      <artifactId>org.apache.servicemix.bundles.saaj-impl</artifactId>
      <version>1.3.23_2</version>
      <scope>compile</scope>
    </dependency>
  </dependencies>
```

feature.xml becomes
```csv
 <feature name="openhab-binding-dlinksmarthome" description="D-Link Smart Home Binding" version="${project.version}">
        <feature>openhab-runtime-base</feature>
        <feature>openhab-transport-mdns</feature>
        <feature dependency="true">openhab.tp-jaxws</feature>
        <bundle start-level="80">mvn:org.openhab.addons.bundles/org.openhab.binding.dlinksmarthome/${project.version}</bundle>
    </feature>
```

@J-N-K if that looks  ok, I'll submit a PR.
