### ISSUE TITLE
[nanoleaf] Panel thing updates fail due to HTTP 404 API request failures

### ISSUE THREAD

**Issue by olafWal** [openhab/openhab-addons#6446]
Since the last update the nanoleaf binding causes exceptions on every update:

Setting values still works, thing is displayed as online
-------------------------

2019-11-24 16:28:43.233 [WARN ] [nternal.handler.NanoleafPanelHandler] - Panel data could not be retrieved: OpenAPI request failed. HTTP response code 404

2019-11-24 16:28:43.266 [ERROR] [nternal.items.ItemStateConverterImpl] - A conversion of null was requested:

java.lang.IllegalArgumentException: State must not be null.

	at org.eclipse.smarthome.core.internal.items.ItemStateConverterImpl.convertToAcceptedState(ItemStateConverterImpl.java:58) ~[?:?]

	at org.eclipse.smarthome.core.thing.internal.profiles.ProfileCallbackImpl.sendUpdate(ProfileCallbackImpl.java:134) ~[?:?]

	at org.eclipse.smarthome.core.thing.internal.profiles.SystemDefaultProfile.onStateUpdateFromHandler(SystemDefaultProfile.java:53) ~[?:?]

	at org.eclipse.smarthome.core.thing.internal.CommunicationManager.lambda$9(CommunicationManager.java:467) ~[?:?]

	at org.eclipse.smarthome.core.thing.internal.CommunicationManager.lambda$11(CommunicationManager.java:487) ~[?:?]

	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_232]

	at org.eclipse.smarthome.core.thing.internal.CommunicationManager.handleCallFromHandler(CommunicationManager.java:483) ~[?:?]

	at org.eclipse.smarthome.core.thing.internal.CommunicationManager.stateUpdated(CommunicationManager.java:465) ~[?:?]

	at org.eclipse.smarthome.core.thing.internal.ThingManagerImpl$1.stateUpdated(ThingManagerImpl.java:168) ~[?:?]

	at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.updateState(BaseThingHandler.java:245) ~[?:?]

	at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.updateState(BaseThingHandler.java:264) ~[?:?]

	at org.openhab.binding.nanoleaf.internal.handler.NanoleafPanelHandler.updatePanelColorChannel(NanoleafPanelHandler.java:209) ~[?:?]

	at org.openhab.binding.nanoleaf.internal.handler.NanoleafControllerHandler.lambda$3(NanoleafControllerHandler.java:466) ~[?:?]

	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_232]

	at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1082) ~[?:1.8.0_232]

	at org.openhab.binding.nanoleaf.internal.handler.NanoleafControllerHandler.updateFromControllerInfo(NanoleafControllerHandler.java:462) ~[?:?]

	at org.openhab.binding.nanoleaf.internal.handler.NanoleafControllerHandler.runUpdate(NanoleafControllerHandler.java:315) ~[?:?]

	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_232]

	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_232]

	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_232]

	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_232]

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_232]

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_232]

	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]

**Comment by olafWal** [comment]
Version openHAB 2.5.0~S1762-1 (Build #1762)

**Comment by olafWal** [comment]
Additional Note: Disabling the "Panels" Things make the error go away.

**Comment by mboremski** [comment]
I can confirm this bug with `Nanoleaf-Firmware 3.2.0` and `openHAB 2.5.0 Release Build`

**Comment by 9037568** [comment]
Looks like this should be improved in the latest binding release. Can @olafWal retry?

**Comment by olafWal** [comment]
I checked the logs, it seems to be OK now
