### ISSUE TITLE
[heos] Cannot use heos account with email address that has + sign in it

### ISSUE THREAD

**Issue by cguedel** [openhab/openhab-addons#6491]
## Expected Behavior
Can enter username (foo+bar@example.org) and password and value gets saved

## Current Behavior
Get an exception, value is not saved:
```
17:20:01.781 [ERROR] [est.core.internal.thing.ThingResource] - Exception during HTTP PUT request for update config at 'things/heos:bridge:9ba1f2fb-48c4-1a39-0080-0005cdc58e72/config'
java.lang.NullPointerException: null
        at org.apache.commons.net.telnet.TelnetClient._closeOutputStream(TelnetClient.java:84) ~[?:?]
        at org.apache.commons.net.telnet.TelnetOutputStream.close(TelnetOutputStream.java:163) ~[?:?]
        at org.apache.commons.net.telnet.TelnetClient.disconnect(TelnetClient.java:129) ~[?:?]
        at org.openhab.binding.heos.internal.resources.Telnet.disconnect(Telnet.java:236) ~[?:?]
        at org.openhab.binding.heos.internal.api.HeosSystem.closeConnection(HeosSystem.java:250) ~[?:?]
        at org.openhab.binding.heos.handler.HeosBridgeHandler.dispose(HeosBridgeHandler.java:170) ~[?:?]
        at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.handleConfigurationUpdate(BaseThingHandler.java:116) ~[?:?]
        at org.eclipse.smarthome.core.thing.internal.ThingRegistryImpl.updateConfiguration(ThingRegistryImpl.java:93) ~[?:?]
        at org.eclipse.smarthome.io.rest.core.internal.thing.ThingResource.updateConfiguration(ThingResource.java:438) [bundleFile:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) [bundleFile:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) [bundleFile:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) [bundleFile:?]
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160) [bundleFile:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) [bundleFile:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) [bundleFile:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) [bundleFile:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) [bundleFile:?]
        at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326) [bundleFile:?]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [bundleFile:?]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [bundleFile:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [bundleFile:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [bundleFile:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [bundleFile:?]
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [bundleFile:?]
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) [bundleFile:?]
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) [bundleFile:?]
        at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473) [bundleFile:?]
        at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427) [bundleFile:?]
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388) [bundleFile:?]
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341) [bundleFile:?]
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228) [bundleFile:?]
        at com.eclipsesource.jaxrs.publisher.internal.ServletContainerBridge.service(ServletContainerBridge.java:76) [bundleFile:?]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:852) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:544) [bundleFile:9.4.20.v20190813]
        at org.ops4j.pax.web.service.jetty.internal.HttpServiceServletHandler.doHandle(HttpServiceServletHandler.java:71) [bundleFile:?]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:536) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1581) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1307) [bundleFile:9.4.20.v20190813]
        at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.doHandle(HttpServiceContext.java:293) [bundleFile:?]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:482) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1549) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1204) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [bundleFile:9.4.20.v20190813]
        at org.ops4j.pax.web.service.jetty.internal.JettyServerHandlerCollection.handle(JettyServerHandlerCollection.java:80) [bundleFile:?]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.server.Server.handle(Server.java:494) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:374) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:268) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:367) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:782) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:918) [bundleFile:9.4.20.v20190813]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
```

## Steps to Reproduce (for Bugs)

1. Go to heos bridge configuration
2. Edit configuration
3. Set username to foo+bar@example.org, set any password
4. Observe exception

## Context
Cannot save my heos account, therefore bridge complains about incomplete configuration and won't load favorites

## Your Environment

* Version used: 2.5.0.M5
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...): Chrome Version 78.0.3904.108
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): Windows 10

**Comment by radokristof** [comment]
@martinvw Maybe a fix for this can be included in your PR? :)

**Comment by martinvw** [comment]
Could you check whether https://download.martinvw.nl/org.openhab.binding.heos-2.5.2-SNAPSHOT-6099.jar solves this for you? Thanks!

**Comment by cguedel** [comment]
Sorry, I was on holidays. I quickly checked using the bundle provided. I set the user and password in Paper UI on the bridge configuration. Following entries appear in the log:

```
15:36:31.183 [INFO ] [smarthome.event.InboxRemovedEvent    ] - Discovery Result with UID 'heos:bridge:dfc288dd-82a9-1982-0080-0005cdfe828a' has been removed.
15:36:31.184 [DEBUG] [ding.heos.internal.HeosHandlerFactory] - Register discovery service for HEOS player and HEOS groups by bridge 'dfc288dd-82a9-1982-0080-0005cdfe828a'
15:36:31.186 [INFO ] [ome.event.ThingStatusInfoChangedEvent] - 'heos:bridge:dfc288dd-82a9-1982-0080-0005cdfe828a' changed from UNINITIALIZED to INITIALIZING
15:36:36.190 [DEBUG] [os.internal.handler.HeosBridgeHandler] - Running scheduledStartUp job
15:36:36.190 [DEBUG] [os.internal.handler.HeosBridgeHandler] - Initialize Bridge 'Denon AVR-X4500H' with IP '10.13.37.137'
15:36:36.193 [DEBUG] [.binding.heos.internal.api.HeosSystem] - HEOS command line connected at IP 10.13.37.137 @ port 1255
15:36:36.197 [DEBUG] [.binding.heos.internal.api.HeosSystem] - HEOS event line connected at IP 10.13.37.137 @ port 1255
15:36:36.202 [DEBUG] [.binding.heos.internal.api.HeosSystem] - HEOS System Event Listener is starting....
15:36:36.205 [WARN ] [inding.heos.internal.resources.Telnet] - Starting input listener
15:36:36.206 [DEBUG] [.binding.heos.internal.api.HeosSystem] - HEOS System Event Listener successfully started
15:36:36.206 [DEBUG] [os.internal.handler.HeosBridgeHandler] - HEOS System heart beat started. Pulse time is 60s
15:36:36.207 [INFO ] [ome.event.ThingStatusInfoChangedEvent] - 'heos:bridge:dfc288dd-82a9-1982-0080-0005cdfe828a' changed from INITIALIZING to ONLINE
15:36:36.207 [DEBUG] [nternal.discovery.HeosPlayerDiscovery] - Start scan for HEOS Player
15:36:36.211 [DEBUG] [nternal.discovery.HeosPlayerDiscovery] - Found: 3 new Player
15:36:36.212 [INFO ] [smarthome.event.InboxAddedEvent      ] - Discovery Result with UID 'heos:player:-1834625020' has been added.
15:36:36.211 [INFO ] [ig.discovery.internal.PersistentInbox] - Added new thing 'heos:player:-1834625020' to inbox.
15:36:36.217 [INFO ] [ig.discovery.internal.PersistentInbox] - Added new thing 'heos:player:-1130540665' to inbox.
15:36:36.217 [INFO ] [smarthome.event.InboxAddedEvent      ] - Discovery Result with UID 'heos:player:-1130540665' has been added.
15:36:36.218 [INFO ] [ig.discovery.internal.PersistentInbox] - Added new thing 'heos:player:393952119' to inbox.
15:36:36.218 [INFO ] [smarthome.event.InboxAddedEvent      ] - Discovery Result with UID 'heos:player:393952119' has been added.
15:36:36.219 [DEBUG] [nternal.discovery.HeosPlayerDiscovery] - Start scan for HEOS Groups
15:36:36.222 [DEBUG] [.binding.heos.internal.api.HeosSystem] - Found: Group HEOS 1 + HEOS 4 with 2 Players
15:36:36.223 [DEBUG] [nternal.discovery.HeosPlayerDiscovery] - Found: 1 new Groups
15:36:36.223 [INFO ] [ig.discovery.internal.PersistentInbox] - Added new thing 'heos:group:468120573' to inbox.
15:36:36.223 [INFO ] [smarthome.event.InboxAddedEvent      ] - Discovery Result with UID 'heos:group:468120573' has been added.
15:36:36.228 [INFO ] [ome.event.ThingStatusInfoChangedEvent] - 'heos:bridge:dfc288dd-82a9-1982-0080-0005cdfe828a' changed from ONLINE to ONLINE (CONFIGURATION_ERROR): Can't log in. Username or password not set.
15:36:48.558 [DEBUG] [os.internal.handler.HeosBridgeHandler] - HEOS bridge removed from change notifications
15:36:48.559 [DEBUG] [os.internal.handler.HeosBridgeHandler] - Dispose bridge 'Denon AVR-X4500H'
15:36:48.562 [DEBUG] [.binding.heos.internal.api.HeosSystem] - Shutting down HEOS Heart Beat
15:36:48.563 [DEBUG] [os.internal.resources.HeosSendCommand] - Stopping HEOS event line listener
15:36:48.563 [WARN ] [inding.heos.internal.resources.Telnet] - Stopping input listener
15:36:48.565 [INFO ] [smarthome.event.ThingUpdatedEvent    ] - Thing 'heos:bridge:dfc288dd-82a9-1982-0080-0005cdfe828a' has been updated.
15:36:53.566 [DEBUG] [os.internal.handler.HeosBridgeHandler] - Running scheduledStartUp job
15:36:53.566 [DEBUG] [os.internal.handler.HeosBridgeHandler] - Initialize Bridge 'Denon AVR-X4500H' with IP '10.13.37.137'
15:36:53.570 [DEBUG] [.binding.heos.internal.api.HeosSystem] - HEOS command line connected at IP 10.13.37.137 @ port 1255
15:36:53.577 [DEBUG] [.binding.heos.internal.api.HeosSystem] - HEOS event line connected at IP 10.13.37.137 @ port 1255
15:36:53.581 [DEBUG] [.binding.heos.internal.api.HeosSystem] - HEOS System Event Listener is starting....
15:36:53.583 [WARN ] [inding.heos.internal.resources.Telnet] - Starting input listener
15:36:53.583 [DEBUG] [.binding.heos.internal.api.HeosSystem] - HEOS System Event Listener successfully started
15:36:53.584 [DEBUG] [os.internal.handler.HeosBridgeHandler] - HEOS System heart beat started. Pulse time is 60s
15:36:53.585 [INFO ] [ome.event.ThingStatusInfoChangedEvent] - 'heos:bridge:dfc288dd-82a9-1982-0080-0005cdfe828a' changed from ONLINE (CONFIGURATION_ERROR): Can't log in. Username or password not set. to ONLINE
15:36:53.585 [DEBUG] [nternal.discovery.HeosPlayerDiscovery] - Start scan for HEOS Player
15:36:53.589 [DEBUG] [nternal.discovery.HeosPlayerDiscovery] - Found: 3 new Player
15:36:53.596 [DEBUG] [nternal.discovery.HeosPlayerDiscovery] - Start scan for HEOS Groups
15:36:53.599 [DEBUG] [.binding.heos.internal.api.HeosSystem] - Found: Group HEOS 1 + HEOS 4 with 2 Players
15:36:53.599 [DEBUG] [nternal.discovery.HeosPlayerDiscovery] - Found: 1 new Groups
15:36:53.600 [DEBUG] [os.internal.handler.HeosBridgeHandler] - Logging in to HEOS account.
15:36:54.852 [DEBUG] [os.internal.handler.HeosBridgeHandler] - Failed to login: HeosError{code=#10: User not found, systemErrorNumber=null}
15:36:54.854 [INFO ] [ome.event.ThingStatusInfoChangedEvent] - 'heos:bridge:dfc288dd-82a9-1982-0080-0005cdfe828a' changed from ONLINE to ONLINE (CONFIGURATION_ERROR): #10: User not found
15:37:23.584 [DEBUG] [.binding.heos.internal.api.HeosSystem] - Time since latest event: 52 s
15:37:23.584 [DEBUG] [.binding.heos.internal.api.HeosSystem] - Sending HEOS Heart Beat
```

**Comment by martinvw** [comment]
@cguedel I'm doubting whether I never saw your reply or that I made some changes after your message, it feels a little bit like the world was completely changed since the beginning of the year.

Could you maybe check again with the current snapshot version or with my latest build: https://download.martinvw.nl/org.openhab.binding.heos-2.5.5-SNAPSHOT.jar

Otherwise, we should reopen the issue, sorry for the confusion.

**Comment by cguedel** [comment]
@martinvw Indeed, this is working now, I wanted to mention it as well, but forgot :(
