### ISSUE TITLE
[IPP] Openhab 2.5.0.M6 - ipp binding - java.lang.NoClassDefFoundError 

### ISSUE THREAD

**Issue by klak2** [openhab/openhab-addons#6529]
## Expected Behavior
No Error

## Current Behavior
2019-12-07 13:29:51.058 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception: 
java.lang.NoClassDefFoundError: org/simpleframework/xml/Serializer at ch.ethz.vppserver.ippclient.IppAttributeProviderFactory.createIppAttributeProvider(IppAttributeProviderFactory.java:5) ~[?:?]
	at ch.ethz.vppserver.ippclient.IppResponse.<init>(IppResponse.java:54) ~[?:?]
	at org.cups4j.operations.IppOperation.sendRequest(IppOperation.java:220) ~[?:?]
	at org.cups4j.operations.IppOperation.sendRequest(IppOperation.java:131) ~[?:?]
	at org.cups4j.operations.IppOperation.request(IppOperation.java:67) ~[?:?]
	at rg.cups4j.operations.ipp.IppGetJobsOperation.getPrintJobs(IppGetJobsOperation.java:119) ~[?:?]
	at org.cups4j.CupsPrinter.getJobs(CupsPrinter.java:330) ~[?:?]
	at org.openhab.binding.ipp.internal.handler.IppPrinterHandler.onDeviceStateChanged(IppPrinterHandler.java:131) ~[?:?]
	at org.openhab.binding.ipp.internal.handler.IppPrinterHandler.handleCommand(IppPrinterHandler.java:121) ~[?:?]
	at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.channelLinked(BaseThingHandler.java:191) ~[?:?]
	at org.eclipse.smarthome.core.thing.link.ThingLinkManager.lambda$0(ThingLinkManager.java:267) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_212]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_212]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_212]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.ClassNotFoundException: org.simpleframework.xml.Serializer cannot be found by org.openhab.binding.ipp_2.5.0.M6
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:484) ~[org.eclipse.osgi-3.12.100.jar:?]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:395) ~[org.eclipse.osgi-3.12.100.jar:?]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:387) ~[org.eclipse.osgi-3.12.100.jar:?]
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:150) ~[org.eclipse.osgi-3.12.100.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]
	... 18 more

## Possible Solution
I don't know

## Steps to Reproduce (for Bugs)
Define a new IPP Thing

## Context
-

## Your Environment
KVM-VM Debian Testing
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-8u212-b01-1-b01)
OpenJDK 64-Bit Server VM (build 25.212-b01, mixed mode)

**Comment by kaikreuzer** [comment]
This has been fixed 5 days ago with https://github.com/openhab/openhab2-addons/pull/6481.
