### ISSUE TITLE
[tesla] NPE occurs with unknown Tesla models

### ISSUE THREAD

**Issue by picaschaf** [openhab/openhab-addons#6604]
The Tesla Addon keeps crashing while discovering vehicles in my Tesla account with NullPointerException - probably because of the switch statement that returns null for all unsupported models in the account (like the Cybertruck).

**Comment by kaikreuzer** [comment]
Cool, you ordered a Cybertruck?
Could you post the exception here, should be easy to fix...

**Comment by picaschaf** [comment]
Hell I did 😎

The log entry is
`2019-12-16 18:59:10.646 [ERROR] [internal.handler.TeslaAccountHandler] - An exception occurred while connecting to the Tesla back-end: 'null'
java.lang.NullPointerException: null
	at org.eclipse.smarthome.core.thing.ThingUID.<init>(ThingUID.java:54) ~[?:?]
	at org.openhab.binding.tesla.internal.discovery.TeslaVehicleDiscoveryService.vehicleFound(TeslaVehicleDiscoveryService.java:87) ~[?:?]
	at org.openhab.binding.tesla.internal.handler.TeslaAccountHandler.queryVehicles(TeslaAccountHandler.java:227) ~[?:?]
	at org.openhab.binding.tesla.internal.handler.TeslaAccountHandler.lambda$0(TeslaAccountHandler.java:439) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_222]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_222]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_222]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_222]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
2019-12-16 19:20:14.702 [INFO ] [el.core.internal.ModelRepositoryImpl] - Loading model 'tesla.things'
2019-12-16 19:20:14.843 [WARN ] [re.thing.internal.ThingFactoryHelper] - Could not create channel 'allowwakeup' for thing type 'tesla:models:1', because channel type 'tesla:allowwakeup' could not be found.
2019-12-16 19:20:14.942 [WARN ] [.thing.internal.GenericThingProvider] - Could not create channel 'allowwakeup' for thing 'tesla:models:1', because channel type 'tesla:allowwakeup' could not be found.`

The reason I think it gets that exception is in the file bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/discovery/TeslaVehicleDiscoveryService.java

`private ThingTypeUID identifyModel(VehicleConfig vehicleConfig) {
        logger.debug("Found a {} vehicle", vehicleConfig.car_type);
        switch (vehicleConfig.car_type) {
            case "models":
                return TeslaBindingConstants.THING_TYPE_MODELS;
            case "modelx":
                return TeslaBindingConstants.THING_TYPE_MODELX;
            case "model3":
                return TeslaBindingConstants.THING_TYPE_MODEL3;
            case "modely":
                return TeslaBindingConstants.THING_TYPE_MODELY;
            default:
                return null;
        }
    }`

If that is the reason then it would also cause problems if someone preordered a Roadster or a Semi.

**Comment by kaikreuzer** [comment]
Looks like the reason, yes.
Should be the same issue for the Roadster, yes, but I doubt that end customers can also order Semis...? I'd assume that business accounts for controlling your fleet should look differently :-)

**Comment by kelleyja** [comment]
I get an identical error on discovery, its a 2017 Model S though, no cybertruck here either 

`19:40:09.922 [WARN ] [ommon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception: 
java.lang.NullPointerException: null
	at org.eclipse.smarthome.core.thing.ThingUID.<init>(ThingUID.java:54) ~[?:?]
	at org.openhab.binding.tesla.internal.discovery.TeslaVehicleDiscoveryService.vehicleFound(TeslaVehicleDiscoveryService.java:87) ~[?:?]
	at org.openhab.binding.tesla.internal.handler.TeslaAccountHandler.queryVehicles(TeslaAccountHandler.java:227) ~[?:?]
	at org.openhab.binding.tesla.internal.handler.TeslaAccountHandler.lambda$1(TeslaAccountHandler.java:153) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_232]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_232]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_232]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:1.8.0_232]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_232]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_232]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]`

**Comment by JochenABC** [comment]
Same happens here, no preorders. The Tesla Account does show two Model S though: One for real and one reservation (which is a weird artifact in the account since there is nothing else on order).

Maybe ignoring unknown vehicle types will be the safest option?

**Comment by JochenABC** [comment]
After setting loglevel for the addon to debug using `log:set DEBUG org.openhab.binding.tesla` I get this:

```
21:48:23.574 [DEBUG] [iscovery.TeslaVehicleDiscoveryService] - Found a models2 vehicle
```
So in my case the problem seems to be that car_type is reported as `models2` and not `models`. This is what it looks like if I insert a breakpoint right before the exception occurs:

![image](https://user-images.githubusercontent.com/3257475/71785956-04ff5200-3006-11ea-8621-534af55bbdfa.png)

If I make `ThingTypeUID` return `TeslaBindingConstants.THING_TYPE_MODELS` in default case then everything works.

**Comment by kaikreuzer** [comment]
Thank you both for the reports. I have created https://github.com/openhab/openhab-addons/pull/6768, which should fix the mentioned issues. Just in time for the 2.5.1 patch release next weekend :-)
