### ISSUE TITLE
[harmonyhub] NPE during hub discovery

### ISSUE THREAD

**Issue by as400rcool** [openhab/openhab-addons#6621]
Running openHAB on Windows 10. Using current distribution at 2.5

What would be causing these traps to be issued with Harmony discovery service? Are there assumed required dependencies (services, binding, transforms…) or configuration entries not mentioned in the docs?

Once the Harmony Hubs have been configured, is it even necessary that this be running? Is there a configuration property that can tell it not to run?

Launching the openHAB runtime…

                      __  _____    ____
____ ____ ___ ____ / / / / | / __ )
/ __ / __ / _ / __ / // / /| | / __ |
/ // / // / __/ / / / __ / ___ |/ // /
_/ ./_// /// /// |/___/
/_/ 2.5.0
Release Build

Hit ‘’ for a list of available commands
and ‘[cmd] --help’ for help on a specific command.
Hit ‘’ or type ‘system:shutdown’ or ‘logout’ to shutdown openHAB.

openhab> Exception in thread “HarmonyDiscoveryServer(tcp/55511)” java.lang.NullPointerException
at org.openhab.binding.harmonyhub.internal.discovery.HarmonyHubDiscoveryService.hubDiscovered(HarmonyHubDiscoveryService.java:277)
at org.openhab.binding.harmonyhub.internal.discovery.HarmonyHubDiscoveryService.access$2(HarmonyHubDiscoveryService.java:274)
at org.openhab.binding.harmonyhub.internal.discovery.HarmonyHubDiscoveryService$HarmonyServer.run(HarmonyHubDiscoveryService.java:253)
at java.lang.Thread.run(Thread.java:748)
Exception in thread “HarmonyDiscoveryServer(tcp/55671)” java.lang.NullPointerException
at

**Comment by wborn** [comment]
Do you see this exception all the time or just sometimes? It works fine for me on both Linux and Windows with OH 2.5.

Seems the hostname is missing from the discovery response:

https://github.com/openhab/openhab2-addons/blob/50d850428573c3230c3835131868a5ad209e91bb/bundles/org.openhab.binding.harmonyhub/src/main/java/org/openhab/binding/harmonyhub/internal/discovery/HarmonyHubDiscoveryService.java#L277

There haven't been much changes in that code for some time now.

openHAB does background discovery because it does not know if you one day decide to connect another hub. Also if  you delete existing Things they again are automatically discovered this way.

See the [docs](https://www.openhab.org/docs/concepts/discovery.html#background-discovery) on how to disable background discovery. You can use `discovery.harmonyhub` for that.

**Comment by as400rcool** [comment]
It is a fresh install of OH2.5 production on Windows 10.  The NPE is displayed on the console all day, new one issued every few minutes each time a difference port reference.  
Are there specific bindings or services that this binding depends on? Since a fresh install, maybe I am missing something Dan assumed everyone is using?
The docs don't indicate any required configuration, so I just installed the binding expecting it to find my 2 hubs (both using firmware 4.15.250).  Never found them, so I did manual config from paperui , specifying the IP# of the respective hub. That worked and found all the devices and activities associated with each hub.
However, the discovery as indicated above continues to display the exception all day.
I will try that suggested discovery option, to shut off that specific binding.

**Comment by wborn** [comment]
It shouldn't require anything else to be installed. I'm using the same firmware on my hubs without issues. Maybe @digitaldan has an explanation?

**Comment by as400rcool** [comment]
It is always the little things that nag...  The Discovery Service docs do not say where to put the configuration entry. Many of the doc pages make too many assumptions.

**Comment by digitaldan** [comment]
Other than the errors in the logs, does the binding find your HUB and continue to work?  Trying to understand if it's your HUB that is sending the response or possibly something else.  From the error It sounds like we are getting a discovery response we don't understand and  the way the exception is thrown, it stops listening as soon as that response is processed and the exception is thrown.   The host_name is assumed to always be set by the Harmony software, but maybe thats not the case (although we have not run into this before). 

If you increase the binding log level to TRACE, it should print out a line starting with `"READ ` and then the discovery data thats being processed right before the error is thrown.  For example:
```
[TRACE] [discovery.HarmonyHubDiscoveryService] - READ email:user@domain.com;mode:3;accountId:123456;ip:192.168.90.238;port:5222;uuid:123456106;current_fw_version:4.15.250;productId:Pimento;setupSessionType:0;setupSessionClient:Mob-123456;setupSessionIsStale:true;setupSessionSetupType:;setupStatus:0;host_name:Guest House;friendlyName:Guest House;discoveryServerUri:http://svcs.myharmony.com/Discovery/Discovery.svc;discoveryServerUriCF:https://cf-svcs.myharmony.com/Discovery/Discovery.svc;openApiVersion:2;minimumOpenApiClientVersionRequired:1;recommendedOpenApiClientVersion:1;protocolVersion:{XMPP="1.0", HTTP="1.0", RF="1.0", WEBSOCKET="1.0"};hubProfiles:{Harmony="2.0"};remoteId:5943043;oohEnabled:true
```

It would be very helpful to have this to understand what is responding back.  The response will have your email and a few IDs in it, you might want to remove those before posting (just in case).

**Comment by digitaldan** [comment]
>Never found them, so I did manual config from paperui , specifying the IP# of the respective hub. That worked and found all the devices and activities associated with each hub.

I missed this when reading, so ignore my first question.

**Comment by as400rcool** [comment]
Well based on the trace I do have a theory. Besides the two Harmony Hubs on my network, I also have a older Logitech Revue (old Google TV) which implemented an early subset of harmony function.  I see a reference to that in the trace level log.  
Do you concur? Is there a way to filter/ignore this device type if my theory is correct?  
Also the machine has multiple ethernet adapters and HypverV support (no currently active) installed. I see attempts to poll several subnets that are not primary.
2019-12-19 12:39:48.480 [DEBUG] [tty.util.component.AbstractLifeCycle] - STARTED @19590ms DeflaterPool@958447e{STARTED}
2019-12-19 12:39:48.480 [DEBUG] [tty.util.component.AbstractLifeCycle] - STARTED @19591ms WebSocketExtensionFactory@40c2992a{STARTED}
2019-12-19 12:39:48.481 [DEBUG] [tty.util.component.AbstractLifeCycle] - STARTED @19591ms WebSocketClient@119954[httpClient=HttpClient@4189e7e8{STARTED},openSessions.size=0]
2019-12-19 12:39:48.485 [DEBUG] [org.osgi.framework.ServiceEvent     ] - ServiceEvent REGISTERED - {org.eclipse.smarthome.config.discovery.DiscoveryService}={service.id=359, service.bundleid=210, service.scope=bundle, component.name=org.openhab.binding.harmonyhub.internal.discovery.HarmonyHubDiscoveryService, component.id=213}
2019-12-19 12:39:48.489 [DEBUG] [discovery.HarmonyHubDiscoveryService] - Start Harmony Hub background discovery
2019-12-19 12:39:48.489 [DEBUG] [discovery.HarmonyHubDiscoveryService] - Start Scan
2019-12-19 12:39:48.490 [DEBUG] [discovery.HarmonyHubDiscoveryService] - StartScan called
2019-12-19 12:39:48.491 [DEBUG] [org.osgi.framework.BundleEvent      ] - BundleEvent STARTED
2019-12-19 12:39:48.492 [DEBUG] [discovery.HarmonyHubDiscoveryService] - Creating Harmony server on port 63217
2019-12-19 12:39:48.492 [DEBUG] [mpl.info.InfoBundleTrackerCustomizer] - Ignore incorrect info null provided by bundle org.openhab.binding.harmonyhub
2019-12-19 12:39:48.495 [DEBUG] [org.osgi.framework.BundleEvent      ] - BundleEvent STARTING
2019-12-19 12:39:49.557 [DEBUG] [discovery.HarmonyHubDiscoveryService] - IO error during HarmonyHub discovery: No route to host: Datagram send failed
2019-12-19 12:39:49.558 [TRACE] [discovery.HarmonyHubDiscoveryService] - Request packet sent to: 224.0.0.1 Interface: Intel(R) 82579V Gigabit Network Connection
2019-12-19 12:39:49.558 [TRACE] [discovery.HarmonyHubDiscoveryService] - Request packet sent to: 255.255.255.255 Interface: Intel(R) 82579V Gigabit Network Connection
2019-12-19 12:39:49.558 [TRACE] [discovery.HarmonyHubDiscoveryService] - Request packet sent to: 192.168.10.255 Interface: Intel(R) 82579V Gigabit Network Connection
2019-12-19 12:39:49.559 [DEBUG] [discovery.HarmonyHubDiscoveryService] - IO error during HarmonyHub discovery: No route to host: Datagram send failed
2019-12-19 12:39:49.559 [TRACE] [discovery.HarmonyHubDiscoveryService] - Request packet sent to: 224.0.0.1 Interface: Intel(R) 82579V Gigabit Network Connection
2019-12-19 12:39:49.559 [TRACE] [discovery.HarmonyHubDiscoveryService] - Request packet sent to: 255.255.255.255 Interface: Intel(R) 82579V Gigabit Network Connection
2019-12-19 12:39:49.562 [TRACE] [discovery.HarmonyHubDiscoveryService] - READ email:__REMOVED____@gmail+com;ip:192.168.10.48;port:5222;uuid:0f6b6ff5-d547-4a83-8b14-e19372dd4975;hubId:Revue 2.0;openApiVersion:2;minimumOpenApiClientVersionRequired:1;recommendedOpenApiClientVersion:1
2019-12-19 12:39:49.579 [DEBUG] [discovery.HarmonyHubDiscoveryService] - IO error during HarmonyHub discovery: No route to host: Datagram send failed
2019-12-19 12:39:49.579 [TRACE] [discovery.HarmonyHubDiscoveryService] - Request packet sent to: 224.0.0.1 Interface: Hyper-V Virtual Ethernet Adapter
2019-12-19 12:39:49.580 [TRACE] [discovery.HarmonyHubDiscoveryService] - Request packet sent to: 255.255.255.255 Interface: Hyper-V Virtual Ethernet Adapter
2019-12-19 12:39:49.580 [TRACE] [discovery.HarmonyHubDiscoveryService] - Request packet sent to: 172.17.247.175 Interface: Hyper-V Virtual Ethernet Adapter
2019-12-19 12:39:49.580 [DEBUG] [discovery.HarmonyHubDiscoveryService] - IO error during HarmonyHub discovery: No route to host: Datagram send failed
2019-12-19 12:39:49.580 [TRACE] [discovery.HarmonyHubDiscoveryService] - Request packet sent to: 224.0.0.1 Interface: Hyper-V Virtual Ethernet Adapter
2019-12-19 12:39:49.581 [TRACE] [discovery.HarmonyHubDiscoveryService] - Request packet sent to: 255.255.255.255 Interface: Hyper-V Virtual Ethernet Adapter
2019-12-19 12:39:50.497 [DEBUG] [rg.apache.aries.spifly.BaseActivator] - Bundle Considered for SPI providers: org.openhab.core.boot
2019-12-19 12:39:50.497 [DEBUG] [rg.apache.aries.spifly.BaseActivator] - No 'SPI-Provider' Manifest header. Skipping bundle: org.openhab.core.boot
2019-12-19 12:39:50.498 [DEBUG] [org.apache.felix.configadmin        ] - listConfigurations(filter=(|(service.factoryPid=org.openhab.ui.iconforwarder)(service.factoryPid=org.openhab.ui.iconforwarder|org.openhab.core.boot)(service.factoryPid=org.openhab.ui.iconforwarder|org.openhab.core.boot|2.5.0)(service.factoryPid=org.openhab.ui.iconforwarder|org.openhab.core.boot|2.5.0|mvn:org.openhab.core.bundles/org.openhab.core.boot/2.5.0)))
2019-12-19 12:39:50.499 [DEBUG] [org.apache.felix.configadmin        ] - Listing configurations matching (|(service.factoryPid=org.openhab.ui.iconforwarder)(service.factoryPid=org.openhab.ui.iconforwarder|org.openhab.core.boot)(service.factoryPid=org.openhab.ui.iconforwarder|org.openhab.core.boot|2.5.0)(service.factoryPid=org.openhab.ui.iconforwarder|org.openhab.core.boot|2.5.0|mvn:org.openhab.core.bundles/org.openhab.core.boot/2.5.0))
2019-12-19 12:39:50.499 [DEBUG] [org.apache.felix.configadmin        ] - listConfigurations(filter=(|(service.pid=org.openhab.ui.iconforwarder)(service.pid=org.openhab.ui.iconforwarder|org.openhab.core.boot)(service.pid=org.openhab.ui.iconforwarder|org.openhab.core.boot|2.5.0)(service.pid=org.openhab.ui.iconforwarder|org.openhab.core.boot|2.5.0|mvn:org.openhab.core.bundles/org.openhab.core.boot/2.5.0)))
2019-12-19 12:39:50.499 [DEBUG] [org.apache.felix.configadmin        ] - Listing configurations matching (|(service.pid=org.openhab.ui.iconforwarder)(service.pid=org.openhab.ui.iconforwarder|org.openhab.core.boot)(service.pid=org.openhab.ui.iconforwarder|org.openhab.core.boot|2.5.0)(service.pid=org.openhab.ui.iconforwarder|org.openhab.core.boot|2.5.0|mvn:org.openhab.core.bundles/org.openhab.core.boot/2.5.0))

**Comment by digitaldan** [comment]
Yep, that would be it, it was the "something else" theory.  I have a fix that will prevent this, i also noticed some other cleanup that needs to be done in that class as well. Thanks for the detailed log,.  I'll submit something shortly.

**Comment by digitaldan** [comment]
Fix submitted.
