### ISSUE TITLE
[OpenSprinkler] binding throwing class cast exception

### ISSUE THREAD

**Issue by JonathanGiles** [openhab/openhab-addons#6646]
It appears that the OpenSprinkler binding has a bug in it. I see the following exception:

```
2019-12-21 20:48:29.644 [ERROR] [nal.common.AbstractInvocationHandler] - An error occurred while calling method 'ThingHandler.handleCommand()' on 'org.openhab.binding.opensprinkler.internal.handler.OpenSprinklerStationHandler@2c64d7': org.eclipse.smarthome.core.library.types.QuantityType cannot be cast to org.eclipse.smarthome.core.library.types.DecimalType

java.lang.ClassCastException: org.eclipse.smarthome.core.library.types.QuantityType cannot be cast to org.eclipse.smarthome.core.library.types.DecimalType

	at org.openhab.binding.opensprinkler.internal.handler.OpenSprinklerStationHandler.handleNextDurationCommand(OpenSprinklerStationHandler.java:92) ~[?:?]

	at org.openhab.binding.opensprinkler.internal.handler.OpenSprinklerStationHandler.handleCommand(OpenSprinklerStationHandler.java:76) ~[?:?]
```

If you look at [this method](https://github.com/openhab/openhab-addons/blob/master/bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/handler/OpenSprinklerStationHandler.java#L86), there is a bug. Firstly, the method is the following:

```java
    private void handleNextDurationCommand(ChannelUID channelUID, Command command) {
        if (!(command instanceof QuantityType<?>)) {
            logger.info("Ignoring implausible non-DecimalType command for NEXT_DURATION");
            return;
        }
        this.nextDurationTime = ((QuantityType<?>) command).toBigDecimal();
        updateState(channelUID, (DecimalType) command);
    }
```

In this code we are checking if the `command` is a `QuantityType`. If it is not, we fail. Therefore, after this first 'if' statement, we know that command is a `QuantityType`. The next line gets the duration time as a big decimal. The final line is type-casting the `command` argument, which we know is a `QuantityType` to be a `DecimalType`, which results in the class path exception. 

// cc @FlorianSW

**Comment by FlorianSW** [comment]
Interesting, not sure what I'd in my head when writing this. I'll take a look into it :)
