### ISSUE TITLE
[buienradar] TimeoutException

### ISSUE THREAD

**Issue by lsiepel** [openhab/openhab-addons#6698]
While using 2.5.0 stable, i get some exceptions/stacktraces in the logfile about buienradar not getting a response in a fashionable time.

```
2019-12-28 09:11:51.742 [WARN ] [uienradar.internal.BuienradarHandler] - Did not get a result from buienradar. Retrying. 4 tries remaining, waiting 5 seconds.
2019-12-28 09:11:59.743 [WARN ] [uienradarapi.BuienradarPredictionAPI] - IO Exception when trying to retrieve Buienradar results
java.io.IOException: java.util.concurrent.TimeoutException: Total timeout 3000 ms elapsed
	at org.eclipse.smarthome.io.net.http.HttpUtil.executeUrlAndGetReponse(HttpUtil.java:259) ~[?:?]
	at org.eclipse.smarthome.io.net.http.HttpUtil.executeUrl(HttpUtil.java:156) ~[?:?]
	at org.eclipse.smarthome.io.net.http.HttpUtil.executeUrl(HttpUtil.java:131) ~[?:?]
	at org.eclipse.smarthome.io.net.http.HttpUtil.executeUrl(HttpUtil.java:109) ~[?:?]
	at org.eclipse.smarthome.io.net.http.HttpUtil.executeUrl(HttpUtil.java:90) ~[?:?]
	at org.openhab.binding.buienradar.internal.buienradarapi.BuienradarPredictionAPI.getPredictions(BuienradarPredictionAPI.java:144) ~[?:?]
	at org.openhab.binding.buienradar.internal.BuienradarHandler.refresh(BuienradarHandler.java:134) ~[?:?]
	at org.openhab.binding.buienradar.internal.BuienradarHandler.lambda$1(BuienradarHandler.java:139) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_232]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_232]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_232]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_232]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_232]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_232]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
Caused by: java.util.concurrent.TimeoutException: Total timeout 3000 ms elapsed
	at org.eclipse.jetty.client.TimeoutCompleteListener.onTimeoutExpired(TimeoutCompleteListener.java:51) ~[?:?]
	at org.eclipse.jetty.io.CyclicTimeout$Wakeup.run(CyclicTimeout.java:282) ~[?:?]
	... 7 more
2019-12-28 09:11:59.754 [WARN ] [uienradar.internal.BuienradarHandler] - Did not get a result from buienradar. Retrying. 3 tries remaining, waiting 10 seconds.
2019-12-28 09:12:12.755 [WARN ] [uienradarapi.BuienradarPredictionAPI] - IO Exception when trying to retrieve Buienradar results
java.io.IOException: java.util.concurrent.TimeoutException: Total timeout 3000 ms elapsed
	at org.eclipse.smarthome.io.net.http.HttpUtil.executeUrlAndGetReponse(HttpUtil.java:259) ~[?:?]
	at org.eclipse.smarthome.io.net.http.HttpUtil.executeUrl(HttpUtil.java:156) ~[?:?]
	at org.eclipse.smarthome.io.net.http.HttpUtil.executeUrl(HttpUtil.java:131) ~[?:?]
	at org.eclipse.smarthome.io.net.http.HttpUtil.executeUrl(HttpUtil.java:109) ~[?:?]
	at org.eclipse.smarthome.io.net.http.HttpUtil.executeUrl(HttpUtil.java:90) ~[?:?]
	at org.openhab.binding.buienradar.internal.buienradarapi.BuienradarPredictionAPI.getPredictions(BuienradarPredictionAPI.java:144) ~[?:?]
	at org.openhab.binding.buienradar.internal.BuienradarHandler.refresh(BuienradarHandler.java:134) ~[?:?]
	at org.openhab.binding.buienradar.internal.BuienradarHandler.lambda$1(BuienradarHandler.java:139) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_232]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_232]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_232]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_232]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_232]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_232]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
Caused by: java.util.concurrent.TimeoutException: Total timeout 3000 ms elapsed
	at org.eclipse.jetty.client.TimeoutCompleteListener.onTimeoutExpired(TimeoutCompleteListener.java:51) ~[?:?]
	at org.eclipse.jetty.io.CyclicTimeout$Wakeup.run(CyclicTimeout.java:282) ~[?:?]
	... 7 more
2019-12-28 09:12:12.764 [WARN ] [uienradar.internal.BuienradarHandler] - Did not get a result from buienradar. Retrying. 2 tries remaining, waiting 20 seconds.
2019-12-28 09:12:35.766 [WARN ] [uienradarapi.BuienradarPredictionAPI] - IO Exception when trying to retrieve Buienradar results
java.io.IOException: java.util.concurrent.TimeoutException: Total timeout 3000 ms elapsed
	at org.eclipse.smarthome.io.net.http.HttpUtil.executeUrlAndGetReponse(HttpUtil.java:259) ~[?:?]
	at org.eclipse.smarthome.io.net.http.HttpUtil.executeUrl(HttpUtil.java:156) ~[?:?]
	at org.eclipse.smarthome.io.net.http.HttpUtil.executeUrl(HttpUtil.java:131) ~[?:?]
	at org.eclipse.smarthome.io.net.http.HttpUtil.executeUrl(HttpUtil.java:109) ~[?:?]
	at org.eclipse.smarthome.io.net.http.HttpUtil.executeUrl(HttpUtil.java:90) ~[?:?]
	at org.openhab.binding.buienradar.internal.buienradarapi.BuienradarPredictionAPI.getPredictions(BuienradarPredictionAPI.java:144) ~[?:?]
	at org.openhab.binding.buienradar.internal.BuienradarHandler.refresh(BuienradarHandler.java:134) ~[?:?]
	at org.openhab.binding.buienradar.internal.BuienradarHandler.lambda$1(BuienradarHandler.java:139) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_232]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_232]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_232]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_232]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_232]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_232]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
Caused by: java.util.concurrent.TimeoutException: Total timeout 3000 ms elapsed
	at org.eclipse.jetty.client.TimeoutCompleteListener.onTimeoutExpired(TimeoutCompleteListener.java:51) ~[?:?]
	at org.eclipse.jetty.io.CyclicTimeout$Wakeup.run(CyclicTimeout.java:282) ~[?:?]
	... 7 more
2019-12-28 09:12:35.776 [WARN ] [uienradar.internal.BuienradarHandler] - Did not get a result from buienradar. Retrying. 1 tries remaining, waiting 40 seconds.
```

If i understand https://github.com/openhab/openhab-addons/issues/5735#issuecomment-509528595 it should have been fixed. 

Anyway, i would suggest to 1. make the timeout configurable. And 2. i do not see why the stacktrace should be logged when there is a timeoutexception. 
A WARN: "IO/Timeout Exception (Total timeout 3000 ms elapsed) when trying to retrieve Buienradar results. x tries remaining."
Should be enough, as it happens quite often.

**Comment by lsiepel** [comment]
Still happening at openHAB 2.5.5.

**Comment by martinvw** [comment]
@gedejong did you ever take another look at this, could it be that the behaviour was broken again? Or that one flow was missed, I checked my snapshot version and I see the same logs.
