### ISSUE TITLE
[kostal inverter] value updates not working anymore after firmware update

### ISSUE THREAD

**Issue by mbremer99** [openhab/openhab-addons#6745]
After update of my kostal inverter (model plenticore plus 8.5) to the latest firmware 1.40 released on 2019-12-17 querying the vales runs into an error.

The info page of the inverter UI shows the following version information after update:
UI-Version: 01.13.04122
MC-Version: 01.40
IOC-Version: 01.40

Update files are located here:
https://www.kostal-solar-electric.com/download/download#PLENTICORE%20plus/PLENTICORE%20plus%208.5/Deutschland/Update/
There are also release notes available which do not mention any changes to the WEB API which is used by openhab for the third generation inverter models. Only mentioned a “general UI optimization”, no mention of the API whatsoever.
I already put a support request to the manufacturer inquiring about any changes made to the WEB API in this release. Will post an update here with the answer.

## Expected Behavior
Values being queried from the inverter as before.

## Current Behavior
After the update openhab lost the connection to the inverter - this error shows up in the log:

`2020-01-01 23:31:28.007 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception: 
com.google.gson.JsonSyntaxException: Expected a com.google.gson.JsonArray but was com.google.gson.JsonPrimitive
	at com.google.gson.internal.bind.TypeAdapters$35$1.read(TypeAdapters.java:896) ~[?:?]
	at com.google.gson.Gson.fromJson(Gson.java:888) ~[?:?]
	at com.google.gson.Gson.fromJson(Gson.java:853) ~[?:?]
	at com.google.gson.Gson.fromJson(Gson.java:802) ~[?:?]
	at com.google.gson.Gson.fromJson(Gson.java:774) ~[?:?]
	at org.openhab.binding.internal.kostal.inverter.thirdgeneration.ThirdGenerationHttpHelper.getJsonArrayFromResponse(ThirdGenerationHttpHelper.java:144) ~[?:?]
	at org.openhab.binding.internal.kostal.inverter.thirdgeneration.ThirdGenerationHandler.updateChannelValues(ThirdGenerationHandler.java:195) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_231]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[?:1.8.0_231]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_231]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[?:1.8.0_231]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_231]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_231]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_231]
`

So it looks the authentication and opening of a session still works, binding fails, when it tries to query values. It seems that the API was changed and the "/processdata" call now returns different values than expected.

## Steps to Reproduce (for Bugs)
Upgrade firmware on inverter to version 1.40
I have this version installed and would be willing to test changes - just get in touch.

## Your Environment
openHAB 2.5.000, SPK package running on Synology using default kostal inverter binding from that release

**Comment by mbremer99** [comment]
Quick update: The binding works again now.
What did I change:
- restarted the inverter (once again)
- removed all items/things etc. for binding, uninstalled binding, installed and configured binding again

As I did this more or less at the same time I cannot say which was the solution, but after that everything works as before.
