### ISSUE TITLE
[wifiled] Scheduled runnable ended with exception

### ISSUE THREAD

**Issue by 5iver** [openhab/openhab-addons#6848]
## Current Behavior
It does not seem to affect functionality, but when OH starts, there is an exception...

```
2020-01-17 07:11:09.780 [WARN ] [org.eclipse.smarthome.core.internal.common.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception: 
java.lang.ArrayIndexOutOfBoundsException: 1
        at org.openhab.binding.wifiled.internal.discovery.WiFiLEDDiscoveryService.discover(WiFiLEDDiscoveryService.java:107) ~[?:?]
        at org.openhab.binding.wifiled.internal.discovery.WiFiLEDDiscoveryService.lambda$0(WiFiLEDDiscoveryService.java:64) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_232]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_232]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_232]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:1.8.0_232]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_232]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_232]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232
```

## Steps to Reproduce (for Bugs)
I have 2 Arilux AL-LC02 controllers configured as LD382A Things. All I do is restart OH to reproduce the issue. This has been happening for a long while.

## Your Environment

* Version used: (e.g., openHAB and add-on versions) OH 2.5.1-2
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): FedoraServer 31

**Comment by hpd96** [comment]
Hello,

noted the same issue using OH 2.5.0 final using delivered WIFILED binding and Magic UFO-Wifi-led controller LD382A

**the autodiscovery of WIFI LED binding does not work. .(NOK)**

this was working without problems in OH 2.5.0 milestone 3

click on SCAN in PaperUI:

```
2020-01-21 21:40:15.300 [DEBUG] [al.discovery.WiFiLEDDiscoveryService] - Start WiFi LED scan
2020-01-21 21:40:15.302 [DEBUG] [al.discovery.WiFiLEDDiscoveryService] - Try to discover all WiFi LED devices
2020-01-21 21:40:15.305 [DEBUG] [al.discovery.WiFiLEDDiscoveryService] - Disover message sent: '48 46 2d 41 31 31 41 53 53 49 53 54 48 52 45 41 44'
2020-01-21 21:40:15.315 [DEBUG] [al.discovery.WiFiLEDDiscoveryService] - Disover response received: 'HF-A11ASSISTHREAD' [48 46 2d 41 31 31 41 53 53 49 53 54 48 52 45 41 44 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00]
2020-01-21 21:40:15.317 [ERROR] [nternal.DiscoveryServiceRegistryImpl] - Cannot trigger scan for thing types '[wifiled:wifiled]' on 'WiFiLEDDiscoveryService'!
java.lang.ArrayIndexOutOfBoundsException: 1
        at org.openhab.binding.wifiled.internal.discovery.WiFiLEDDiscoveryService.discover(WiFiLEDDiscoveryService.java:107) ~[?:?]
```

The WiFiLEDDiscoveryService expects to receive a value that consists of 3 parts: IP Address, MAC Address, and Hostname:

192.168.178.25,ACCF23489C9A,HF-LPB100-ZJ200

log shows not getting that:

2020-01-21 21:31:26.582 [DEBUG] [al.discovery.WiFiLEDDiscoveryService] - Disover response received: 'HF-A11ASSISTHREAD' 



startup exception also always:

```
2020-01-20 21:59:07.151 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception:
java.lang.ArrayIndexOutOfBoundsException: 1
at org.openhab.binding.wifiled.internal.discovery.WiFiLEDDiscoveryService.discover(WiFiLEDDiscoveryService.java:107) ~[?:?]
at org.openhab.binding.wifiled.internal.discovery.WiFiLEDDiscoveryService.lambda$0(WiFiLEDDiscoveryService.java:64) ~[?:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_201]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_201]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_201]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:1.8.0_201]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_201]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_201]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
```


Please check this issue. Thanks!

**Comment by 9037568** [comment]
I'm preparing a fix for this that will allow the discovery process to ignore these unparseable values and continue searching.

**Comment by hpd96** [comment]
PASSED :-)
274 x Active   x  80 x 2.5.2.202001241311      x openHAB Add-ons :: Bundles :: WiFiLED Binding
