### ISSUE TITLE
[lghombot] images not available and exception

### ISSUE THREAD

**Issue by mstormi** [openhab/openhab-addons#6885]
These are my image items, they both do not get displayed in sitemap:

```
Image HomBot_Image "Kamera"     (Hombot)        { channel="lghombot:LGHomBot:Luigi:camera" }
Image HomBot_Map "Map"            (Hombot)        { channel="lghombot:LGHomBot:Luigi:map" }

```

On OH startup, I keep getting the error below:
```
2020-01-21 11:26:39.831 [ERROR] [ome.core.thing.link.ThingLinkManager] - Exception occurred while informing handler: null
java.lang.NullPointerException: null
        at org.openhab.binding.lghombot.internal.LGHomBotHandler.parseImage(LGHomBotHandler.java:559) ~[?:?]
        at org.openhab.binding.lghombot.internal.LGHomBotHandler.refreshFromState(LGHomBotHandler.java:291) ~[?:?]
        at org.openhab.binding.lghombot.internal.LGHomBotHandler.handleCommand(LGHomBotHandler.java:107) ~[?:?]
        at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.channelLinked(BaseThingHandler.java:191) ~[?:?]
        at org.eclipse.smarthome.core.thing.link.ThingLinkManager.lambda$0(ThingLinkManager.java:267) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_222]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_222]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_222]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_222]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_222]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_222]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
```

**Comment by lsiepel** [comment]
Is this still an issue? 
I found a PR that might be related that was merged shortly after this issue. https://github.com/openhab/openhab-addons/pull/7163

Can you confirm or close this issue?

**Comment by mstormi** [comment]
Haven't seen in a long time so assume it's fixed for now. Will reopen should I encounter it again.
