### ISSUE TITLE
[feed] NullPointerException if all Channels are not linked

### ISSUE THREAD

**Issue by 5iver** [openhab/openhab-addons#6906]
OH and feed 2.5.1-2

Whenever the feed binding or OH is restarted, I see the following log entries. I think the The INFO entries can be set to DEBUG, though maybe it can be handled better. The WARNING is an exception and seems like there is something wrong, but everything seems to be working fine. It is annoying though.
```
2020-01-26 08:48:55.163 [INFO ] [org.openhab.binding.feed.internal.handler.FeedHandler] - Cannot update channel with ID latest-description; no data has been downloaded from the server!
2020-01-26 08:48:55.164 [INFO ] [org.openhab.binding.feed.internal.handler.FeedHandler] - Cannot update channel with ID author; no data has been downloaded from the server!
2020-01-26 08:48:55.164 [INFO ] [org.openhab.binding.feed.internal.handler.FeedHandler] - Cannot update channel with ID latest-date; no data has been downloaded from the server!
2020-01-26 08:48:55.164 [INFO ] [org.openhab.binding.feed.internal.handler.FeedHandler] - Cannot update channel with ID description; no data has been downloaded from the server!
2020-01-26 08:48:55.164 [INFO ] [org.openhab.binding.feed.internal.handler.FeedHandler] - Cannot update channel with ID last-update; no data has been downloaded from the server!
2020-01-26 08:48:55.164 [INFO ] [org.openhab.binding.feed.internal.handler.FeedHandler] - Cannot update channel with ID title; no data has been downloaded from the server!
2020-01-26 08:48:55.164 [INFO ] [org.openhab.binding.feed.internal.handler.FeedHandler] - Cannot update channel with ID number-of-entries; no data has been downloaded from the server!
2020-01-26 08:50:55.510 [WARN ] [org.eclipse.smarthome.core.internal.common.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception: 
java.lang.NullPointerException: null
        at org.openhab.binding.feed.internal.handler.FeedHandler.publishChannelIfLinked(FeedHandler.java:142) ~[?:?]
        at org.openhab.binding.feed.internal.handler.FeedHandler.refreshFeedState(FeedHandler.java:117) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_232]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[?:1.8.0_232]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_232]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[?:1.8.0_232]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_232]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_232]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
```

**Comment by 9037568** [comment]
Isn't this the same issue you were wrangling [over a year ago](https://community.openhab.org/t/feed-binding-null-pointer-exception/60921/5)? Did you not ever open that ticket?

**Comment by openhab-5iver** [comment]
Embarrassing... your memory is better than mine. It looks like I never created the issue... until now!

**Comment by 9037568** [comment]
Ok. No matter, I can have a fix in a few minutes.
