### ISSUE TITLE
[shelly] IllegalArgumentException while Discovery

### ISSUE THREAD

**Issue by UrsusS** [openhab/openhab-addons#7018]
While the discovery process of the shelly binding my printer answers. His message is different than expected and causes an IllegalArgumentException.
Version of the binding: 2.5.1

```
2020-02-16 11:56:47.690 [ERROR] [onfig.discovery.mdns.internal.MDNSDiscoveryService] - Participant 'org.openhab.binding.shelly.internal.discovery.ShellyDiscoveryParticipant' threw an exception

java.lang.IllegalArgumentException: ID segment '472x series (sec001599a05d95)' contains invalid characters. Each segment of the ID must match the pattern [A-Za-z0-9_-]*.

	at org.eclipse.smarthome.core.common.AbstractUID.validateSegment(AbstractUID.java:97) ~[bundleFile:?]

	at org.eclipse.smarthome.core.common.AbstractUID.<init>(AbstractUID.java:75) ~[bundleFile:?]

	at org.eclipse.smarthome.core.common.AbstractUID.<init>(AbstractUID.java:58) ~[bundleFile:?]

	at org.eclipse.smarthome.core.thing.UID.<init>(UID.java:57) ~[bundleFile:?]

	at org.eclipse.smarthome.core.thing.ThingUID.<init>(ThingUID.java:43) ~[bundleFile:?]

	at org.openhab.binding.shelly.internal.discovery.ShellyThingCreator.getThingUID(ShellyThingCreator.java:34) ~[?:?]

	at org.openhab.binding.shelly.internal.discovery.ShellyDiscoveryParticipant.getThingUID(ShellyDiscoveryParticipant.java:185) ~[?:?]

	at org.eclipse.smarthome.config.discovery.mdns.internal.MDNSDiscoveryService.serviceRemoved(MDNSDiscoveryService.java:241) [bundleFile:?]

	at javax.jmdns.impl.ListenerStatus$ServiceListenerStatus.serviceRemoved(ListenerStatus.java:81) [bundleFile:3.5.5]

	at javax.jmdns.impl.JmDNSImpl$5.run(JmDNSImpl.java:1322) [bundleFile:3.5.5]

	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]

	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]

	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]

```

**Comment by markus7017** [comment]
Fix is included in PR #6965

**Comment by UrsusS** [comment]
After installing 2.5.4 I observed the issue again and I thought that the fix has already been included in this version:
247 │ Active │  80 │ 2.5.4                   │ openHAB Add-ons :: Bundles :: Shelly Binding

```
2020-04-21 08:45:06.418 [ERROR] [onfig.discovery.mdns.internal.MDNSDiscoveryService] - Participant 'org.openhab.binding.shelly.internal.discovery.ShellyDiscoveryParticipant' threw an exception
java.lang.IllegalArgumentException: ID segment '472x series (sec001599a05d95)' contains invalid characters. Each segment of the ID must match the pattern [A-Za-z0-9_-]*.
	at org.eclipse.smarthome.core.common.AbstractUID.validateSegment(AbstractUID.java:97) ~[bundleFile:?]
	at org.eclipse.smarthome.core.common.AbstractUID.<init>(AbstractUID.java:75) ~[bundleFile:?]
	at org.eclipse.smarthome.core.common.AbstractUID.<init>(AbstractUID.java:58) ~[bundleFile:?]
	at org.eclipse.smarthome.core.thing.UID.<init>(UID.java:57) ~[bundleFile:?]
	at org.eclipse.smarthome.core.thing.ThingUID.<init>(ThingUID.java:43) ~[bundleFile:?]
	at org.openhab.binding.shelly.internal.discovery.ShellyThingCreator.getThingUID(ShellyThingCreator.java:32) ~[?:?]
	at org.openhab.binding.shelly.internal.discovery.ShellyDiscoveryParticipant.getThingUID(ShellyDiscoveryParticipant.java:205) ~[?:?]
	at org.eclipse.smarthome.config.discovery.mdns.internal.MDNSDiscoveryService.serviceRemoved(MDNSDiscoveryService.java:241) [bundleFile:?]
	at javax.jmdns.impl.ListenerStatus$ServiceListenerStatus.serviceRemoved(ListenerStatus.java:81) [bundleFile:3.5.5]
	at javax.jmdns.impl.JmDNSImpl$5.run(JmDNSImpl.java:1322) [bundleFile:3.5.5]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```

**Comment by markus7017** [comment]
No, this is not a problem of the binding. It may be a bug in jMDNS. I'm already investigating with Alterco/Shelly on that, but the guy is on vacation. Usually you overcome this problem when doing the discovery more than once.

**Comment by markus7017** [comment]
No feedback from Alterco
