### ISSUE TITLE
[mqtt][homeassistant] ComponentSensors (/BinarySensors) - Allow forced_update true

### ISSUE THREAD

**Issue by jpwise9** [openhab/openhab-addons#7063]
Tasmota has frc_upd set to true by default for Home Assistant integration, causing exception event.

Line 45 & 67.
https://github.com/arendst/Tasmota/blob/004df125a5f71d77aa0f7650717bbfab2bd19d5a/tasmota/xdrv_12_home_assistant.ino

HomeAssistant module rejects forced_updates = true with exception.

        if (channelConfiguration.force_update) {
            throw new UnsupportedOperationException("Component:Sensor does not support forced updates");
        }

Sidenote: ComponentBinarySensor also excepts with the same text string, so you can't tell which sensor is triggering the exception.

I believe this is the cause of Tasmota modules unexpectedly reporting as offline after discovery and adding.
```
Status: OFFLINE - GONE At least one component not active
[WARN ] [mqtt.homeassistant.internal.CFactory] - Not supported
java.lang.UnsupportedOperationException: Component:Sensor does not support forced updates
```
https://www.home-assistant.io/integrations/sensor.mqtt/#force_update

From my understanding of the forced update function it's intended to trigger an update to the value even if it hasn't changed, so from the perspective of OpenHAB the homeassistant discovery shouldn't actually be interacting with this? If OH is subscribed to the mqtt topic it's over to how the user has configured the item persistence settings whether the data is stored or not, and the force update flag isn't relevant in this use case?  If that's correct there shouldn't be reason to trigger an exception that I can see?

**Comment by jochen314** [comment]
@davidgraeff: My thinking was going in the same direction. `force_update` is HA specific. we should ignore it.
And similiarly `optimistic`. Should we really throw an exception or just ignore it. As far as I understand `optimistic` mode would be a general configuration in OH.

**Comment by lukasvermeer** [comment]
I think this issue might also be breaking auto discovery for Tasmota devices?

After applying `SetOption19 1` as described in the [Tasmota docs](https://tasmota.github.io/docs/Home-Assistant/), my device appears in the openHAB (2.5.5 Release Build) inbox. When added, configuration of the device is incomplete (sensor channels missing for a switch+sensor) and the follow error appears in the log.

```
2020-06-02 19:53:23.348 [WARN ] [mqtt.homeassistant.internal.CFactory] - Not supported
java.lang.UnsupportedOperationException: Component:Sensor does not support forced updates
	at org.openhab.binding.mqtt.homeassistant.internal.ComponentSensor.<init>(ComponentSensor.java:51) ~[?:?]
	at org.openhab.binding.mqtt.homeassistant.internal.CFactory.createComponent(CFactory.java:72) ~[?:?]
	at org.openhab.binding.mqtt.homeassistant.internal.DiscoverComponents.processMessage(DiscoverComponents.java:99) ~[?:?]
	at org.eclipse.smarthome.io.transport.mqtt.internal.ClientCallback.lambda$3(ClientCallback.java:96) ~[?:?]
	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_152]
	at org.eclipse.smarthome.io.transport.mqtt.internal.ClientCallback.messageArrived(ClientCallback.java:96) ~[?:?]
	at org.eclipse.smarthome.io.transport.mqtt.internal.ClientCallback.messageArrived(ClientCallback.java:71) ~[?:?]
	at com.hivemq.client.internal.mqtt.mqtt3.Mqtt3AsyncClientView.lambda$callbackView$1(Mqtt3AsyncClientView.java:73) ~[bundleFile:?]
	at com.hivemq.client.internal.mqtt.MqttAsyncClient$CallbackSubscriber.onNext(MqttAsyncClient.java:227) [bundleFile:?]
	at com.hivemq.client.internal.mqtt.MqttAsyncClient$CallbackSubscriber.onNext(MqttAsyncClient.java:212) [bundleFile:?]
	at com.hivemq.client.rx.FlowableWithSingle$SingleFutureSubscriber.onNext(FlowableWithSingle.java:377) [bundleFile:?]
	at com.hivemq.client.internal.rx.operators.FlowableWithSingleCombine$SplitSubscriber$Default.tryOnNextActual(FlowableWithSingleCombine.java:206) [bundleFile:?]
	at com.hivemq.client.internal.rx.operators.FlowableWithSingleCombine$SplitSubscriber.tryOnNext(FlowableWithSingleCombine.java:171) [bundleFile:?]
	at io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnConditionalSubscriber.runAsync(FlowableObserveOn.java:649) [bundleFile:?]
	at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176) [bundleFile:?]
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66) [bundleFile:?]
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57) [bundleFile:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_152]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_152]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_152]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_152]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_152]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
```

**Comment by lukasvermeer** [comment]
> configuration of the device is incomplete 

Upon further investigation, I think this is not quite correct.

The channels are listed when editing the thing in the Paper UI. Under Configuration Parameters then MQTT Config Topic they seem to be listed just fine. I cannot find these channels anywhere else, though.

Saving the configuration results in the same warnings appearing again.

**Comment by lukasvermeer** [comment]
> If that's correct there shouldn't be reason to trigger an exception that I can see?

I did some digging trying to understand _why_ this exception might be there in the first place. 

Apologies if all of this was obvious to you. I'm new to OH, so this was mostly a learning excercise for me. Documenting it in case it's useful to anyone.

- I think the exception originates in [this file](https://github.com/openhab/openhab-addons/blob/b2496e1af1d81f717c07791e998faf061189861c/bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/ComponentBinarySensor.java#L48).

- Git blame points to [a massive PR](https://github.com/openhab/openhab-addons/pull/4625) by @kaikreuzer which seems to have merged another repo into this one.

- The same exception existed in the [equivalent file there](https://github.com/eclipse-archived/smarthome/blob/master/extensions/binding/org.eclipse.smarthome.binding.mqtt.generic/src/main/java/org/eclipse/smarthome/binding/mqtt/generic/internal/convention/homeassistant/ComponentSensor.java#L62).

- Git blame there points to [another massive PR](https://github.com/eclipse-archived/smarthome/pull/5880) which was a re-take on [an earlier attempt](https://github.com/eclipse-archived/smarthome/pull/5101) which doesn't seem to have the same exception, so I guess it was introduced by @davidgraeff?

**Comment by jpwise9** [comment]
> * I think the exception originates in [this file](https://github.com/openhab/openhab-addons/blob/b2496e1af1d81f717c07791e998faf061189861c/bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/ComponentBinarySensor.java#L48).
> * The same exception existed in the [equivalent file there](https://github.com/eclipse-archived/smarthome/blob/master/extensions/binding/org.eclipse.smarthome.binding.mqtt.generic/src/main/java/org/eclipse/smarthome/binding/mqtt/generic/internal/convention/homeassistant/ComponentSensor.java#L62).

Hey @lukasvermeer - yes, those were the two files I was referencing with the title - ComponentSensors (/BinarySensors) which both include the exception check code.   My understanding is that the addon was written to support the homeassistant spec at the time - force update is detailed at : https://www.home-assistant.io/integrations/sensor.mqtt/#force_update  
So in a HA environment (as some tasmota units may be) the force update flag is valid. 
But in a OH environment it's not as relevant and IMHO there doesn't need to be an exception for it.

Earlier discussion above appears to concur, but no updates been made as yet.

**Comment by jochen314** [comment]
I have PR #7206 open where I want to change this (among others)
