### ISSUE TITLE
[boschindego] The Bosch Indego Binding doesn't work

### ISSUE THREAD

**Issue by henrydiesner** [openhab/openhab-addons#7269]
The Bosch Indego binding doesn't work since release 2.5.3.
The binding is offline. The user data are correct, with the Bosch Android app it works.
In openHAB I've uninstalled and reinstalled the binding with no effect.
Last year it works without response, but it works (see issue #5975 [https://github.com/openhab/openhab-addons/issues/5975](url)).
The log file says:
2020-04-01 15:46:38.829 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception: 
java.lang.NoClassDefFoundError: org/apache/http/impl/client/HttpClients
	at de.zazaz.iot.bosch.indego.IndegoController.connect(IndegoController.java:116) ~[?:?]
	at org.openhab.binding.boschindego.internal.handler.BoschIndegoHandler.poll(BoschIndegoHandler.java:110) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_232]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[?:1.8.0_232]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_232]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[?:1.8.0_232]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_232]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_232]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
Caused by: java.lang.ClassNotFoundException: org.apache.http.impl.client.HttpClients cannot be found by org.openhab.binding.boschindego_2.5.3
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:433) ~[org.eclipse.osgi-3.12.100.jar:?]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:395) ~[org.eclipse.osgi-3.12.100.jar:?]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:387) ~[org.eclipse.osgi-3.12.100.jar:?]
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:150) ~[org.eclipse.osgi-3.12.100.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_232]
	... 9 more

I use a NUC with Debian buster with openhabian (openHAB 2.5.3-1)

**Comment by J-N-K** [comment]
Can you please show

```
bundle:list -s | grep org.apache.http
```

I have seen a similar report some days ago and IIRC there was a different/older version installed than needed.

**Comment by J-N-K** [comment]
Can you try:

```
bundle:list -s | grep indego
```

The number in the first column is the bundle-number. Use it to update the bundle: 

```
bundle:update number https://janessa.me/esh/org.openhab.binding.boschindego-2.5.3-SNAPSHOT.jar
```

If you don't have httpclient 4.5.5 and httpcore 4.4.9 installed, install them:

```
bundle:install https://repo1.maven.org/maven2/org/apache/httpcomponents/httpclient-osgi/4.5.9/httpclient-osgi-4.5.5.jar
bundle:install https://repo1.maven.org/maven2/org/apache/httpcomponents/httpcore-osgi/4.4.9/httpcore-osgi-4.4.9.jar
```

If it does not work OOTB: 

```
bundle:resolve number
bundle:restart number
```

And report back. Thanks.

**Comment by henrydiesner** [comment]
Many thanks for your help.
I've updated the binding and now the version is 2.5.3.202004041447
Unfortunately I have a problem with the httpclient and httpcore. My versions are 4.2.3 but the installing of the newer ones failed:
openhab> bundle:install https://repo1.maven.org/maven2/org/apache/httpcomponents/httpclient-osgi/4.5.9/htt             pclient-osgi-4.5.5.jar
Bundle IDs:
Error executing command: Error installing bundles:
        Unable to install bundle https://repo1.maven.org/maven2/org/apache/httpcomponents/httpclient-osgi/             4.5.9/httpclient-osgi-4.5.5.jar: org.osgi.framework.BundleException: Error reading bundle content.
openhab> bundle:install https://repo1.maven.org/maven2/org/apache/httpcomponents/httpclient-osgi/4.5.9/htt             pclient-osgi-4.5.5.jar
Bundle IDs:
Error executing command: Error installing bundles:
        Unable to install bundle https://repo1.maven.org/maven2/org/apache/httpcomponents/httpclient-osgi/             4.5.9/httpclient-osgi-4.5.5.jar: org.osgi.framework.BundleException: Error reading bundle content.
................................
Can you tell me what I can do? That woud be great!

**Comment by J-N-K** [comment]
My fault. Change the 4.5.9 in the URL to 4.5.5

**Comment by henrydiesner** [comment]
Great, now the mower works!
Many thanks and stay healthy!

**Comment by J-N-K** [comment]
Re-opening as PR is still needed to fix it properly
