### ISSUE TITLE
[folding] Binding fails on slotListType JSON

### ISSUE THREAD

**Issue by janenen** [openhab/openhab-addons#7271]
Hello Everyone,
on trying to monitor my Folding PCs I had a problem, as the correlated Items woudn't initialize.

## Expected Behavior

After manualy adding the Client items (ip, port, pw) the individual compute-slots should appear in the Inbox.
Client and Slot items should eventualy get thier status changed to correct values.

## Current Behavior

Client items were added and after fixing permission issues on the folding-clients and restarting openhab their status changed to online but the channels weren't updated.

Also no Slot items were recognized by auto-detect.

After manually adding them, they were stuck on uninitialized.

<details>
  <summary>Log shows: Expected BEGIN_ARRAY but was STRING </summary> 
    2020-04-01 12:10:56.430 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception: 

com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1 path $

	at com.google.gson.Gson.fromJson(Gson.java:900) ~[?:?]

	at org.openhab.binding.folding.internal.handler.FoldingClientHandler.refresh(FoldingClientHandler.java:130) ~[?:?]

	at org.openhab.binding.folding.internal.handler.FoldingClientHandler.lambda$1(FoldingClientHandler.java:157) ~[?:?]

	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_222]

	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_222]

	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_222]

	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:1.8.0_222]

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_222]

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_222]

	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]

Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1 path $

	at com.google.gson.stream.JsonReader.beginArray(JsonReader.java:350) ~[?:?]

	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:80) ~[?:?]

	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61) ~[?:?]

	at com.google.gson.Gson.fromJson(Gson.java:888) ~[?:?]

	... 9 more
    
</details>

**Comment by Huib0513** [comment]
Same problem here. The problem only occurs when connecting to a **Windows** client. Connecting to my single UNIX (Debian) client works perfectly

**Comment by janenen** [comment]
Updated the client on Ubuntu to 7.6.13 and tried again on Windows and Ubuntu but I got the same result as before.

Just a guess:
I don't know much about GSON and JSON, but maybe it has to do with line endings, so the parser wich reads the answer from the F@H-client doesn't split the input String to multiple array entries.

In the meantime I got another Warning:
<details>
  <summary>Java heap space</summary>
  
  
  
  ```
2020-05-11 21:29:38.491 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception: 

java.lang.OutOfMemoryError: Java heap space

	at java.util.Arrays.copyOf(Arrays.java:3332) ~[?:1.8.0_222]

	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124) ~[?:1.8.0_222]

	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:649) ~[?:1.8.0_222]

	at java.lang.StringBuilder.append(StringBuilder.java:202) ~[?:1.8.0_222]

	at org.openhab.binding.folding.internal.handler.FoldingClientHandler.readUntilPrompt(FoldingClientHandler.java:219) ~[?:?]

	at org.openhab.binding.folding.internal.handler.FoldingClientHandler.getSocket(FoldingClientHandler.java:191) ~[?:?]

	at org.openhab.binding.folding.internal.handler.FoldingClientHandler.refresh(FoldingClientHandler.java:122) ~[?:?]

	at org.openhab.binding.folding.internal.handler.FoldingClientHandler$$Lambda$495/3336978.run(Unknown Source) ~[?:?]

	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_222]

	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[?:1.8.0_222]

	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_222]

	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[?:1.8.0_222]

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_222]

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_222]

	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
  ```
  
</details>

I was deleting and recreating F@H items several times so this might not be directly related.

**Comment by gabuzi** [comment]
I can confirm this issue is still present with the current F@H version on windows (version 7.6.21) and openhab 3.1. I can successfully connect to F@H client running on debian (version 7.4.4). In both cases, a password is set.

I tracked the different behavior down to a different response in the F@H communication: the Windows client includes an empty line after the PyON header, while the debian client does not (see bottom).

The relevant portion of code seems to be FoldingClientHandler::refresh(), which removes the PyON header, but does no further checking whether there is an empty line following that header, see following line.
https://github.com/openhab/openhab-addons/blob/e24d43aecbcfc5af551c8e9087d9be6992e5c69a/bundles/org.openhab.binding.folding/src/main/java/org/openhab/binding/folding/internal/handler/FoldingClientHandler.java#L124


Communication sample from windows client, tested through netcat:
```
> slot-info

PyON 1 slots
[
  {
    "id": "00",
    "status": "PAUSED",
    "description": "cpu:22",
    "options": {"paused": "true"},
    "reason": "by user",
    "idle": False
  }]
---
```
</details>

Debian client:
```
> slot-info
PyON 1 slots
[
  {
    "id": "00",
    "status": "FINISHING",
    "description": "cpu:32",
    "options": {},
    "reason": "",
    "idle": False
  }
]
---
```

**Comment by lsiepel** [comment]
Could not find a related PR, so i guess this is still an issue. If so, i might try to get a fix. But before i do, is there anyone available to test? I will probably come up with a JAR for 3.4.x
