### ISSUE TITLE
[homekit] HomeKit stops working after some days, SubscriptionManager NPE in log

### ISSUE THREAD

**Issue by abbe79** [openhab/openhab-addons#7274]
After some days where HomeKit integration in openHAB 2.5 works perfectly fine all devices inside the iOS/macOS Home app are flagged as "keine Antwort" (~"not responding").

In the openhab.log now appear hundreds of error entries:
`2020-04-02 22:35:22.636 [ERROR] [impl.connections.SubscriptionManager] - Failed to create new event message
java.lang.NullPointerException: null`

## Expected Behavior
HomeKit integration should work permanently

## Current Behavior
HomeKit stops working after some days.
Tried to "bundle:refresh org.openhab.io.homekit", also "bundle:restart", no success.
Restarting of openHAB fixes the issue for some days.

## Steps to Reproduce (for Bugs)
1. Add homekit io addon and some items
2. Wait a few days
3. Boom!

## Context
Trying to get important items into HomeKit, currently 33 items. Mostly lighting, rollershutters and thermostats. Also some state items (like "sleeping", "summer mode") that are represented as switch item.

## Your Environment
* Version used: openHAB 2.5.0 
* Environment name and version: official Docker image running on Synology NAS.

**Comment by abbe79** [comment]
Should have been fixed in https://github.com/openhab/openhab-addons/pull/5647 but seems not to work. :-(

**Comment by abbe79** [comment]
Increased the logging level:

`2020-04-09 21:11:47.673 [ERROR] [impl.connections.SubscriptionManager] - Failed to create new event message
java.lang.NullPointerException: null
	at io.github.hapjava.impl.connections.SubscriptionManager.publish(SubscriptionManager.java:130) ~[?:?]
	at io.github.hapjava.impl.connections.SubscriptionManager.lambda$addSubscription$0(SubscriptionManager.java:41) ~[?:?]
	at org.openhab.io.homekit.internal.HomekitAccessoryUpdater.lambda$1(HomekitAccessoryUpdater.java:59) ~[?:?]
	at org.eclipse.smarthome.core.items.GenericItem$1.run(GenericItem.java:261) [bundleFile:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_232]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_232]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
`

**Comment by grouchal** [comment]
I have 80 items in my openhab.
When I use add HomeKit support then after a couple of days the openhab server can no longer connect with the KNX bus (where my 80 items are).

This is consistently a problem when I add HomeKit support, all runs fine without.

I am not clear if the problem is related to the issue here or related to the number of requests that HomeKit causes to be sent via KNX.

I have had to disable homeKit again - which is a real shame as the integration worked fine for two days and was really great.

**Comment by J-N-K** [comment]
We have upgraded the hap-java library and improved the openHAB implementation. Maybe you can check with the latest snapshot.

**Comment by abbe79** [comment]
> I am not clear if the problem is related to the issue here or related to the number of requests that HomeKit causes to be sent via KNX.

I am also using KNX with 77 HomeKit items.

Had no chance to test the upgraded hap-java library yet, hope I'll find some time for this the next days.

**Comment by manudar** [comment]
Hi, I have 130 items with homekit link in openhab and after almost every reboot of openhab, I need to remove and add openhab to HomeKit in iOS again. Is like the id of openhab HomeKit changes and iOS does not recognise it anymore.
Also with no reboot, after 2 or 3 days it stops working.
I am using openhab 2.5.7 build from the 28th of June.
The only error I get is the following
`[WARN ] [.server.impl.connections.HttpSession] - Exception encountered while verifying pairing
java.lang.Exception: Unknown user: C1E14C30-53E7-418F-AA26-33D53C40F2BF
	at io.github.hapjava.server.impl.pairing.PairVerificationManager.stage2(PairVerificationManager.java:113) ~[bundleFile:?]
	at io.github.hapjava.server.impl.pairing.PairVerificationManager.handle(PairVerificationManager.java:51) ~[bundleFile:?]
	at io.github.hapjava.server.impl.connections.HttpSession.handlePairVerify(HttpSession.java:127) [bundleFile:?]
	at io.github.hapjava.server.impl.connections.HttpSession.handleRequest(HttpSession.java:56) [bundleFile:?]
	at io.github.hapjava.server.impl.connections.ConnectionImpl.doHandleRequest(ConnectionImpl.java:56) [bundleFile:?]
	at io.github.hapjava.server.impl.connections.ConnectionImpl.handleRequest(ConnectionImpl.java:49) [bundleFile:?]
	at io.github.hapjava.server.impl.http.impl.AccessoryHandler.channelRead0(AccessoryHandler.java:52) [bundleFile:?]
	at io.github.hapjava.server.impl.http.impl.AccessoryHandler.channelRead0(AccessoryHandler.java:17) [bundleFile:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [bundleFile:4.1.42.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [bundleFile:4.1.42.Final]
	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:56) [bundleFile:4.1.42.Final]
	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:365) [bundleFile:4.1.42.Final]
	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66) [bundleFile:4.1.42.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044) [bundleFile:4.1.42.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [bundleFile:4.1.42.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [bundleFile:4.1.42.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
`

**Comment by yfre** [comment]
@manudar do you still have this issue? 


this issue is well known with the "Unknown user" exception was already ofter reported. for some unknown reasons openHAB forget the paired devices. 
some user reported that changing the homekit PIN helped to fix it. 
could you please try it as well?
if you still have this issue please try to upgrade to latest snapshot. it has some additional logging that you could to trouble shoot the root cause.

**Comment by manudar** [comment]
Hi, I installed 11 days ago 2.5.7~S165-1  and since then I had no problem at all (I use ubuntu 16.04). 
 - It was 7 days running with no issue and no restart.
 - I have restarted since then more that 20 time (I am testing something) and it has worked every time.
 - I have more than 300 Loxone items and I have restarted Loxone several times making its items unavailable and this has not broken the HomeKit setup. When the link to Loxone automatically fixed itself the HomeKit items were available again.

I will keep this version until there is a feature that I really need, because so far everything works very well.

**Comment by yfre** [comment]
Hi @manudar 

thank for the update. happy to hear that everything working.  sure, never touch the running system - dont update homekit. 


i will close the ticket as:
- initial issue with subscription manager is not relevant anymore
- additionally reported "unkown user" issue is not appearing anymore.
