### ISSUE TITLE
[bluetooth] BluetoothDiscoveryServiceTest unstable

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-addons#7286]
This test failed for me while doing a local parallel build on Java 11:

```
[ERROR] Tests run: 16, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2.996 s <<< FAILURE! - in org.openhab.binding.bluetooth.discovery.internal.BluetoothDiscoveryServiceTest
[ERROR] multiDiscoverySingleConnectionTest(org.openhab.binding.bluetooth.discovery.internal.BluetoothDiscoveryServiceTest)  Time elapsed: 1.38 s  <<< FAILURE!
org.mockito.exceptions.verification.WantedButNotInvoked: 

Wanted but not invoked:
mockDiscoveryListener.thingDiscovered(
    same(org.openhab.binding.bluetooth.discovery.internal.BluetoothDiscoveryService@5e77f0f4),
    <Bluetooth discovery service test$$ lambda$ 8 6/ 0x 0 0 0 0 0 0 0 8 0 0 2 2 6c 4 0>
);
-> at org.openhab.binding.bluetooth.discovery.internal.BluetoothDiscoveryServiceTest.multiDiscoverySingleConnectionTest(BluetoothDiscoveryServiceTest.java:235)
Actually, there were zero interactions with this mock.

	at org.openhab.binding.bluetooth.discovery.internal.BluetoothDiscoveryServiceTest.multiDiscoverySingleConnectionTest(BluetoothDiscoveryServiceTest.java:235)
```

**Comment by cpmeister** [comment]
I'll sort it out
