### ISSUE TITLE
[mqtt] BrokerHandlerTest unstable

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-addons#7304]
This test failed for me while doing a local parallel build on Java 11:

```
[ERROR] Failures: 
[ERROR]   BrokerHandlerTest.handlerInit:105->initializeHandlerWaitForTimeout:137 
brokerHandlerEx.connectionStateChanged(
    <any>,
    <any>
);
Wanted 3 times:
-> at org.openhab.binding.mqtt.handler.BrokerHandlerTest.initializeHandlerWaitForTimeout(BrokerHandlerTest.java:137)
But was 4 times:
-> at org.eclipse.smarthome.io.transport.mqtt.MqttBrokerConnection.lambda$3(MqttBrokerConnection.java:700)
-> at org.eclipse.smarthome.io.transport.mqtt.MqttBrokerConnection$ConnectionCallback.lambda$3(MqttBrokerConnection.java:144)
-> at org.openhab.binding.mqtt.handler.AbstractBrokerHandler.lambda$1(AbstractBrokerHandler.java:114)
-> at org.eclipse.smarthome.io.transport.mqtt.MqttBrokerConnection$ConnectionCallback.lambda$4(MqttBrokerConnection.java:162)
```

**Comment by wborn** [comment]
Let's hope this is fixed by #9297!
