### ISSUE TITLE
[amazonechocontrol] AccountHandler: refresh data fails with unexpected error

### ISSUE THREAD

**Issue by 5iver** [openhab/openhab-addons#7383]
I'm receiving the following error in the log after a restart of OH and several times throughoiut the day. I'm failr confident that this began happening after enabling Severe Weather Alerts, which was [added in February](https://www.amazon.com/b?node=21100773011).
```
2020-04-16 01:12:25.426 [ERROR] [org.openhab.binding.amazonechocontrol.internal.handler.AccountHandler] - refresh data fails with unexpected error
java.time.format.DateTimeParseException: Text '2020-04-16Tnull-04:00' could not be parsed at index 11
        at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1949) ~[?:1.8.0_242]
        at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1851) ~[?:1.8.0_242]
        at java.time.ZonedDateTime.parse(ZonedDateTime.java:597) ~[?:1.8.0_242]
        at java.time.ZonedDateTime.parse(ZonedDateTime.java:582) ~[?:1.8.0_242]
        at org.openhab.binding.amazonechocontrol.internal.handler.EchoHandler.updateNotifications(EchoHandler.java:1308) ~[?:?]
        at org.openhab.binding.amazonechocontrol.internal.handler.AccountHandler.refreshNotifications(AccountHandler.java:437) ~[?:?]
        at org.openhab.binding.amazonechocontrol.internal.handler.AccountHandler.refreshData(AccountHandler.java:538) ~[?:?]
        at org.openhab.binding.amazonechocontrol.internal.handler.AccountHandler.checkData(AccountHandler.java:406) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_242]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_242]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_242]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_242]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
```
![image](https://user-images.githubusercontent.com/21967853/79419686-49937580-7f85-11ea-9287-dcc4a36b30b7.png)

## Your Environment
* Version used: OH 2.5.4 S86, amazonechocontrol 2.5.4.202004150344

**Comment by J-N-K** [comment]
This is improper null-handling and still present in 3.0. I'll provide a fix for that.
