### ISSUE TITLE
[hueemulation] Announces wrong IP when run in Docker container

### ISSUE THREAD

**Issue by tfelix** [openhab/openhab-addons#7410]
## Context

I recently ran into issues with my Hue lamps and deleted from for troubleshooting from the Alexa App and wanted them to get re-discovered (they where working with Alexa before!). So I assume that only the discovery process is broken and if Alexa has the lamps it would work. I did the discovery long time ago when OH was not running inside da docker container.

There is a similar issue which describes a similar problem but was closed: https://github.com/openhab/openhab-addons/issues/1317 However I experience this bug.

## Current Behavior

* Switched the emulation into discovery mode (tried also V1) and searched for the lamps via Alexa app, none where discovered.
* I added port forwards IP rule (for port 80) which did not work and tried a nginx reverse proxy which did no work.
* My servers IP is 192.168.178.220
* Checking the http://192.168.178.220/description.xml I found:

 ```
<root xmlns="urn:schemas-upnp-org:device-1-0">
  <specVersion>
    <major>1</major>
    <minor>0</minor>
  </specVersion>
  <URLBase>http://[fe80:0:0:0:14fd:83ff:fe3e:e5a]:80/</URLBase>
  <device>
    <deviceType>urn:schemas-upnp-org:device:Basic:1</deviceType>
    <friendlyName>
      openHAB Hue Emulation ([fe80:0:0:0:14fd:83ff:fe3e:e5a])
    </friendlyName>
    <manufacturer>Royal Philips Electronics</manufacturer>
    <manufacturerURL>http://www.openhab.org</manufacturerURL>
    <modelDescription>Philips hue Personal Wireless Lighting</modelDescription>
    <modelName>Philips hue bridge 2015</modelName>
    <modelNumber>BSB002</modelNumber>
    <modelURL>http://www.meethue.com</modelURL>
    <serialNumber>91533E207962</serialNumber>
    <UDN>uuid:91533e20-7962-4039-8209-f8d25110b15b</UDN>
    <gatewayName>openHAB</gatewayName>
    <presentationURL>index.html</presentationURL>
    <iconList>
      <icon>
        <mimetype>image/png</mimetype>
        <height>48</height>
        <width>48</width>
        <depth>24</depth>
        <url>hue_logo_0.png</url>
      </icon>
      <icon>
        <mimetype>image/png</mimetype>
        <height>120</height>
        <width>120</width>
        <depth>24</depth>
        <url>hue_logo_3.png</url>
      </icon>
    </iconList>
  </device>
</root>
```

Please notice the **[fe80:0:0:0:14fd:83ff:fe3e:e5a]** address which I find odd. I run the docker container in network mode host (as documented in OpenHab docs), so I suspect the Hosts IP address could be known by the plugin. I tried to manually set the discovery address to 192.168.178.220 but this was ignored. Other settings like bridge ID or exposed port (its set to 80 as you can see) is respected.

I confirmed that this IP is not reachable from external systems. Doing an `ip address list` yields:

```
[...]
196: veth5329921@if195: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-11accfeb69d8 state UP group default
    link/ether 16:fd:83:3e:0e:5a brd ff:ff:ff:ff:ff:ff link-netnsid 3
    inet6 fe80::14fd:83ff:fe3e:e5a/64 scope link
       valid_lft forever preferred_lft forever
[...]
```

which I think marks this IP as a docker used IP? (I am not sure here).

Another thing I notice when turning on the hue discovery, I see this in my OpenHab log:

```
16:15:12.953 [WARN ] [hueemulation.internal.upnp.UpnpServer] - Upnp server: Address test failed
java.util.concurrent.CompletionException: java.net.BindException: Cannot assign requested address (Bind failed)
        at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:326) ~[?:1.8.0_232]
        at java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:338) ~[?:1.8.0_232]
        at java.util.concurrent.CompletableFuture.uniRelay(CompletableFuture.java:925) ~[?:1.8.0_232]
        at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:967) ~[?:1.8.0_232]
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:940) ~[?:1.8.0_232]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_232]
        at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:575) [?:1.8.0_232]
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:594) [?:1.8.0_232]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456) [?:1.8.0_232]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
Caused by: java.net.BindException: Cannot assign requested address (Bind failed)
        at java.net.PlainDatagramSocketImpl.bind0(Native Method) ~[?:1.8.0_232]
        at java.net.AbstractPlainDatagramSocketImpl.bind(AbstractPlainDatagramSocketImpl.java:93) ~[?:1.8.0_232]
        at java.net.DatagramSocket.bind(DatagramSocket.java:392) ~[?:1.8.0_232]
        at java.net.DatagramSocket.<init>(DatagramSocket.java:242) ~[?:1.8.0_232]
        at org.openhab.io.hueemulation.internal.upnp.UpnpServer.accept(UpnpServer.java:446) ~[?:?]
        at org.openhab.io.hueemulation.internal.upnp.UpnpServer.accept(UpnpServer.java:1) ~[?:?]
        at org.openhab.io.hueemulation.internal.upnp.HueEmulationConfigWithRuntime.run(HueEmulationConfigWithRuntime.java:111) ~[?:?]
```

## Expected Behavior

I expect the manual discovery address to be respected when entered.

## Steps to Reproduce (for Bugs)
1. Setup a docker container with the Emulation Hue binding 
2. Input a manual discovery address and switch the Hue emulation into discovery
3. Check the http://<YOUR_OPENHAB_IP>/description.xml page

## Your Environment
* Ubuntu 16.04
* Docker Image: openhab/openhab:2.5.3

**Comment by tfelix** [comment]
After doing a little more research and checking the code I have found the problem! `HueEmulationConfig` assums the variable is called `public @Nullable String discoveryIps;` however inside the openhab ui the property is named as  discoveryIp. When manipulating the REST call from the panel to the backend via curl from (faulty):

```
curl 'http://192.168.178.220:8080/rest/services/org.openhab.hueemulation/config' -X PUT --data-binary '{"permanentV1bridge":false,"createNewUserOnEveryEndpoint":false,"ignoreItemsWithTags":"internal","discoveryIp":"192.168.178.221","uuid":"91533e20-7962-4039-8209-f8d25110b16c","restrictToTagsSwitches":"Switchable","pairingEnabled":false,"pairingTimeout":180,"temporarilyEmulateV1bridge":false,"restrictToTagsColorLights":"ColorLighting","restrictToTagsWhiteLights":"Lighting","discoveryHttpPort":80}' --compressed --insecure
```
to 
```
curl 'http://192.168.178.220:8080/rest/services/org.openhab.hueemulation/config' -X PUT --data-binary '{"permanentV1bridge":false,"createNewUserOnEveryEndpoint":false,"ignoreItemsWithTags":"internal","discoveryIps":"192.168.178.221","uuid":"91533e20-7962-4039-8209-f8d25110b16c","restrictToTagsSwitches":"Switchable","pairingEnabled":false,"pairingTimeout":180,"temporarilyEmulateV1bridge":false,"restrictToTagsColorLights":"ColorLighting","restrictToTagsWhiteLights":"Lighting","discoveryHttpPort":80}' --compressed --insecure
```

fixed the problem. Now the IP is correctly displayed in the 
`<URLBase>http://192.168.178.220:80/</URLBase>`
field. I prepare a PR.
