### ISSUE TITLE
[tado] Error when trying to add new Tado Home thing via PaperUI

### ISSUE THREAD

**Issue by Dorme** [openhab/openhab-addons#7500]
I'm trying to add a Tado Home thing but I'm getting an error (COMMUNICATION_ERROR) when I try to add it via PaperUI.

## Expected Behavior
After entering the email and password in the PaperUI, the Tado Home thing status should become 'ONLINE'.

## Current Behavior
An error is shown: `OFFLINE - COMMUNICATION_ERROR Could not connect to server due to Error calling https://auth.tado.com/oauth/token`
In the logs I can find following error:
`2020-04-29 11:10:30.856 [hingStatusInfoChangedEvent] - 'tado:home:e719ce7d' changed from INITIALIZING to OFFLINE (COMMUNICATION_ERROR): Could not connect to server due to Error calling https://auth.tado.com/oauth/token`

## Steps to Reproduce (for Bugs)
1. add the Tado binding (binding-tado - 2.5.4)
2. add a Tado Home thing via PaperUI
3. enter your Tado username and password
4. Tado Home thing shows status: OFFLINE - COMMUNICATION_ERROR

## Context
I'm running OpenHab in a Docker container and I'm using the latest OpenHab image.
On webpage https://my.tado.com/webapp/#/account/sign-in I can login with the same credentials as I use in OpenHab and see my home.

## Your Environment
* Version used: Docker OpenHab image: openhab/openhab:latest@sha256:102d7de5ca5044270032b3acef9ad2fb7d57d735934f3269881e3c1e18b88383

**Comment by pytekmobile** [comment]
I have the same problem on my raspberry pi 3 (1GB RAM) with openhabian. It works fine when I initially installed it. But a few weeks ago my sd card got corrupted and I had to reinstall openhabian and import a backup configuration. Since then I was unable to connect to tado api. Either through the tado.things configuration or the PaperUI.

I've done some research and debugging and this is what I found out:

After enabling DEBUG-Log for Tado Binding I found this exception in the logs:


>`2020-08-13 21:53:27.261 [DEBUG] [ado.internal.handler.TadoHomeHandler] - Error accessing tado server: Error calling https://auth.tado.com/oauth/token
java.io.IOException: Error calling https://auth.tado.com/oauth/token
	at org.openhab.binding.tado.internal.api.auth.OAuthAuthorizer.initializeTokens(OAuthAuthorizer.java:118) ~[?:?]
	at org.openhab.binding.tado.internal.api.auth.OAuthAuthorizer.getToken(OAuthAuthorizer.java:138) ~[?:?]
	at org.openhab.binding.tado.internal.api.auth.OAuthAuthorizer.addAuthorization(OAuthAuthorizer.java:148) ~[?:?]
	at org.openhab.binding.tado.internal.api.client.HomeApi.showUser(HomeApi.java:234) ~[?:?]
	at org.openhab.binding.tado.internal.handler.TadoHomeHandler.initializeBridgeStatusAndPropertiesIfOffline(TadoHomeHandler.java:83) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_252]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_252]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_252]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
Caused by: java.util.concurrent.TimeoutException: Total timeout 5000 ms elapsed
	at org.eclipse.jetty.client.HttpDestination$TimeoutTask.onTimeoutExpired(HttpDestination.java:529) ~[?:?]
	at org.eclipse.jetty.io.CyclicTimeout$Wakeup.run(CyclicTimeout.java:282) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_252]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_252]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_252]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:1.8.0_252]
	... 3 more`

It seems that there is a default timeout of 5 s for the tado api request.
That seems enough put I created a python3 script with the login request and it took 6-7 s on the raspberry pi. So it seems that this timeout is a little bit too short for low end PCs.

I tried to fix it myself but the timeout is hard coded in a 3rd party library (https://github.com/dfrommi/swagger-codegen-openhab/blob/master/src/main/resources/oh-templates/api.mustache) and doesn't offer methods to manipulate it.

I think the bug would be fixed, if it the connect timeout is configurable in the things definition.

**Comment by CliffDabbs** [comment]
I had this - same problem - tado auth timeout exceptions in the logs - 5000ms...

In my case - my Pi was looking at a dead DNS server - it had 3 configured - but first one was dead - got that fixed and its straight back to life....

anyone else facing the same - check your ALL configured dns servers are responding!

**Comment by JimmyB8** [comment]
Hi @CliffDabbs, please could you advise how to check ALL configured dns servers are responding? I am a newbie so would appreciate a really dumbed down version.

**Comment by Dorme** [comment]
Changing the DNS server resolved the issue.
