### ISSUE TITLE
[mqtt.homie] The connection object has not been set.

### ISSUE THREAD

**Issue by ArdKuijpers** [openhab/openhab-addons#7520]
Setting the temperature on my thermostat connected via the mqtt-homie binding failed.

I set the temperature via the item ATAGOne_TargetTemperature which is connected via the binding to the homie device. 

## Expected Behavior
OpenHAB sends the target temperature via the MQTT broker to my thermostat

## Current Behavior
The log showed: 
```
10:50:35.657 [INFO ] [smarthome.event.ItemCommandEvent     ] - Item 'ATAGOne_TargetTemperature' received command 18 °C
10:50:35.703 [INFO ] [arthome.event.ItemStatePredictedEvent] - ATAGOne_TargetTemperature predicted to become 17.5 °C
10:50:35.707 [DEBUG] [mqtt.generic.AbstractMQTTThingHandler] - Failed publishing value 18 °C to topic homie/atagone/controls/ch-target-temperature/set: The connection object has not been set. start() should have been called!
```
It seems to be similar to this [issue on the openHAB forum](https://community.openhab.org/t/mqtt-homie-error/88599).

This has been working for more than a month now. All other MQTT devices that I have connected are still working. The only one that is not working is the one using the mqtt-homie binding.

Looking back in the log, I see that earlier this morning, The binding disconnected. It might be a coincidence, but this was just after the connection to openHAB cloud failed:

```
2020-05-02 04:10:31.394 [ERROR] [io.openhabcloud.internal.CloudClient] - Error connecting to the openHAB Cloud instance: {}
io.socket.engineio.client.EngineIOException: websocket error
	at io.socket.engineio.client.Transport.onError(Transport.java:63) [bundleFile:?]
	at io.socket.engineio.client.transports.WebSocket.access$400(WebSocket.java:24) [bundleFile:?]
	at io.socket.engineio.client.transports.WebSocket$1$5.run(WebSocket.java:107) [bundleFile:?]
	at io.socket.thread.EventThread$2.run(EventThread.java:80) [bundleFile:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_232]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_232]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
Caused by: java.io.EOFException
	at okio.RealBufferedSource.require(RealBufferedSource.java:60) ~[?:?]
	at okio.RealBufferedSource.readByte(RealBufferedSource.java:73) ~[?:?]
	at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:113) ~[?:?]
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:97) ~[?:?]
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:262) ~[?:?]
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:201) ~[?:?]
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:141) ~[?:?]
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) ~[?:?]
	... 3 more
2020-05-02 04:10:36.865 [INFO ] [io.openhabcloud.internal.CloudClient] - Disconnected from the openHAB Cloud service (UUID =<redacted>, base URL = http://localhost:18080)
2020-05-02 04:10:47.655 [INFO ] [io.openhabcloud.internal.CloudClient] - Connected to the openHAB Cloud service (UUID =<redacted>, base URL = http://localhost:18080)
2020-05-02 04:11:02.542 [INFO ] [.reconnect.PeriodicReconnectStrategy] - Try to restore connection to '192.168.249.5'. Next attempt in 60000ms
2020-05-02 04:11:02.855 [DEBUG] [e.internal.handler.HomieThingHandler] - About to stop Homie device Atag One
2020-05-02 04:11:03.127 [DEBUG] [ab.binding.mqtt.generic.ChannelState] - Unsubscribed channel mqtt:homie300:mosquitto:atagone:burner#modulation form topic: homie/atagone/burner/modulation
2020-05-02 04:11:03.220 [DEBUG] [ab.binding.mqtt.generic.ChannelState] - Unsubscribed channel mqtt:homie300:mosquitto:atagone:burner#target form topic: homie/atagone/burner/target
...
mqtt:homie300:mosquitto:atagone:controls#ch_2Dtarget_2Dtemperature form topic: homie/atagone/controls/ch-target-temperature
...
2020-05-02 04:11:03.480 [DEBUG] [ab.binding.mqtt.generic.ChannelState] - Unsubscribed channel mqtt:homie300:mosquitto:atagone:weather#temperature form topic: homie/atagone/weather/temperature
2020-05-02 04:11:06.286 [INFO ] [.transport.mqtt.MqttBrokerConnection] - Starting MQTT broker connection to '192.168.249.5' with clientid 70e5567c-91f1-4ead-830c-ecc8b80a9b2b
2020-05-02 04:11:10.648 [DEBUG] [e.internal.handler.HomieThingHandler] - About to start Homie device Atag One
```
But the binding never subscribed again to the channels.

## Possible Solution
```
bundle:restart org.openhab.binding.mqtt.homie
```
Then I do see that openHAB subscribes to the channels from the homie Thing.

## Steps to Reproduce (for Bugs)

I cannot reproduce it. It was the first time this happened.

## Your Environment

* Version used: openHAB 2.5.2, binding: mqtt.homie 2.5.2
```
264 │ Active │  82 │ 2.5.2                   │ openHAB Add-ons :: Bundles :: MQTT Homie Convention
```
* Environment name and version: not relevant
* Operating System and version: official openHAB docker image on Synology NAS.

**Comment by ArdKuijpers** [comment]
I filed an issue on Github: https://github.com/openhab/openhab-addons/issues/7520.

**Comment by mjcumming** [comment]
I have not seen this issue lately - have been on 2.5.4 for 2 weeks or so.  I'll update here is I see it.

**Comment by ArdKuijpers** [comment]
I am now on 2.5.5. I haven't seen this error anymore.

**Comment by bodiroga** [comment]
Thanks for your feedback @ArdKuijpers, would you be so kind as to close the issue?

**Comment by TGit-Tech** [comment]
COMMUNICATION_ERROR
The connection object has not been set. start() should have been called! 

I'm getting this error.  Once I had the interface all setup for the 'homie' device.
1)  I reboot the Pi
2)  I open Openhabian:8080.
3)  I plug in the device (using USB serial).  The device publishes 'homie' data as soon as it recognizes an MQTT connection.
4)  Openhabian UI widgets tied to those channels don't work so I see what's going on.
The 'homie' added device now shows.

COMMUNICATION_ERROR
The connection object has not been set. start() should have been called! 

However;  as soon as I click 'Save' (top right corner) it goes to.
COMMUNICATION_ERROR
Did not receive all required topics (which is were it always goes; but works anyways)
Then the Widgets start to communicate.

2023-02-14 05:27:08.995 [INFO ] [openhab.event.ItemCommandEvent      ] - Item 'tode_onoffa3' received command ON
2023-02-14 05:27:09.109 [INFO ] [penhab.event.ItemStatePredictedEvent] - Item 'tode_onoffa3' predicted to become ON
2023-02-14 05:27:09.194 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'tode_onoffa3' changed from NULL to ON
2023-02-14 05:27:09.213 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'mqtt:homie300:58b97f2f4b:tode' changed from ONLINE to OFFLINE (COMMUNICATION_ERROR): The connection object has not been set. start() should have been called!
