### ISSUE TITLE
[mqtt.homeassistant] ConcurrentModificationException in console/log

### ISSUE THREAD

**Issue by bodiroga** [openhab/openhab-addons#7661]
## Expected Behavior
Home Assistant extension for MQTT shouldn't throw any exception.

## Current Behavior
While I was developing the #7656 feature and making some tests, I have seen many ConcurrentModificationException exceptions in the Eclipse IDE console. Here you can see the exact error:

```
18:01:10.658 [ionThreadPool-2] ERROR o.e.s.i.t.m.internal.ClientCallback:98 - MQTT message received. MqttMessageSubscriber#processMessage() implementation failure
java.util.ConcurrentModificationException: null
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1561)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at org.openhab.binding.mqtt.homeassistant.internal.discovery.HomeAssistantDiscovery.receivedMessage(HomeAssistantDiscovery.java:172)
	at org.openhab.binding.mqtt.discovery.TopicSubscribe.processMessage(TopicSubscribe.java:57)
	at org.eclipse.smarthome.io.transport.mqtt.internal.ClientCallback.lambda$3(ClientCallback.java:96)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.eclipse.smarthome.io.transport.mqtt.internal.ClientCallback.messageArrived(ClientCallback.java:96)
	at org.eclipse.smarthome.io.transport.mqtt.internal.ClientCallback.messageArrived(ClientCallback.java:71)
	at com.hivemq.client.internal.mqtt.mqtt3.Mqtt3AsyncClientView.lambda$callbackView$1(Mqtt3AsyncClientView.java:73)
	at com.hivemq.client.internal.mqtt.MqttAsyncClient$CallbackSubscriber.onNext(MqttAsyncClient.java:227)
	at com.hivemq.client.internal.mqtt.MqttAsyncClient$CallbackSubscriber.onNext(MqttAsyncClient.java:212)
	at com.hivemq.client.rx.FlowableWithSingle$SingleFutureSubscriber.onNext(FlowableWithSingle.java:377)
	at com.hivemq.client.internal.rx.operators.FlowableWithSingleCombine$SplitSubscriber$Default.tryOnNextActual(FlowableWithSingleCombine.java:206)
	at com.hivemq.client.internal.rx.operators.FlowableWithSingleCombine$SplitSubscriber.tryOnNext(FlowableWithSingleCombine.java:171)
	at io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnConditionalSubscriber.runAsync(FlowableObserveOn.java:649)
	at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Sometimes the error points to [HomeAssistantDiscovery.java:172](https://github.com/openhab/openhab-addons/blob/2.5.x/bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/discovery/HomeAssistantDiscovery.java#L172) and other times to [HomeAssistantDiscovery.java:174](https://github.com/openhab/openhab-addons/blob/2.5.x/bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/discovery/HomeAssistantDiscovery.java#L174).

## Possible Solution
I don't know what is causing the error, that's the reason why I am creating this issue. Anyone has seen it? Any idea? @jochen314? @J-N-K? @cpmeister? @davidgraeff? Thanks for your work!

## Your Environment
* Version used: openHAB 2.5.X (launched from Eclipse IDE, latest commit tag: 7c88cbe96929e403af448ce9725fb1b4ed50fcbf)
* Environment name and version: Eclipse IDE 2020.06, Java 8 (openJDK "1.8.0_252")
* Operating System and version: Dell XPS 13 with Ubuntu 18.04. Intel Core i7-10510U, Intel UHD Graphics, 16GB of RAM and 512GB NVMe.

**Comment by bodiroga** [comment]
Hi @jochen314!

I have seen a similar error again when editing a Home Assistant Thing. Here you can see the error message:

```
14:02:23.149 [safeCall-2] ERROR o.e.s.c.i.c.AbstractInvocationHandler:100 - An error occurred while calling method 'ThingHandler.thingUpdated()' on 'org.openhab.binding.mqtt.homeassistant.internal.handler.HomeAssistantThingHandler@9786787': java.util.ConcurrentModificationException
java.util.ConcurrentModificationException: java.util.ConcurrentModificationException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593)
	at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677)
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:735)
	at java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:714)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at org.openhab.binding.mqtt.homeassistant.internal.handler.HomeAssistantThingHandler.stop(HomeAssistantThingHandler.java:216)
	at org.openhab.binding.mqtt.generic.AbstractMQTTThingHandler.dispose(AbstractMQTTThingHandler.java:252)
	at org.openhab.binding.mqtt.homeassistant.internal.handler.HomeAssistantThingHandler.dispose(HomeAssistantThingHandler.java:174)
	at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.thingUpdated(BaseThingHandler.java:164)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:152)
	at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.ConcurrentModificationException: null
	at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1633)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:747)
	at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:721)
	at java.util.stream.AbstractTask.compute(AbstractTask.java:327)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
```

The error points to https://github.com/openhab/openhab-addons/blob/2.5.x/bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/handler/HomeAssistantThingHandler.java#L216, but a few lines before the following message can be read: ```haComponents does not need to be synchronised -> the discovery thread is disabled```. What do you mean with ```the discovery thread is disabled```? If the Thing is edited the stop() method is triggered, but the discovery process is still active :confused:

I will implement what you suggested in https://github.com/openhab/openhab-addons/pull/8239#issuecomment-682052420 and see if that fixes the problem!

Best regards,

Aitor

**Comment by bodiroga** [comment]
Ummmm... after changing ```componentsPerThingID``` and ```thingIDPerTopic```to ```ConcurrentHashMap```, I have seen a new ConcurrentModificationException after adding a new Home Assistant Thing from the Inbox. I'm not sure if this new errors are appearing because I'm fixing the previous ones or because I'm doing something wrong :thinking: Here you can see the error message:

```
17:58:41.349 [OH-discovery-4] ERROR o.e.s.c.d.i.DiscoveryServiceRegistryImpl:270 - Cannot notify the DiscoveryListener org.eclipse.smarthome.config.discovery.internal.PersistentInbox on Thing discovered event!
java.util.ConcurrentModificationException: null
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:911)
	at java.util.ArrayList$Itr.next(ArrayList.java:861)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:96)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:125)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:243)
	at com.google.gson.Gson.toJson(Gson.java:669)
	at com.google.gson.Gson.toJson(Gson.java:648)
	at com.google.gson.Gson.toJson(Gson.java:603)
	at com.google.gson.Gson.toJson(Gson.java:583)
	at org.eclipse.smarthome.storage.mapdb.internal.MapDbStorage.serialize(MapDbStorage.java:140)
	at org.eclipse.smarthome.storage.mapdb.internal.MapDbStorage.put(MapDbStorage.java:88)
	at org.eclipse.smarthome.core.common.registry.AbstractManagedProvider.update(AbstractManagedProvider.java:116)
	at org.eclipse.smarthome.config.discovery.internal.PersistentInbox.add(PersistentInbox.java:247)
	at org.eclipse.smarthome.config.discovery.internal.PersistentInbox.thingDiscovered(PersistentInbox.java:376)
	at org.eclipse.smarthome.config.discovery.internal.DiscoveryServiceRegistryImpl$1.run(DiscoveryServiceRegistryImpl.java:265)
	at org.eclipse.smarthome.config.discovery.internal.DiscoveryServiceRegistryImpl$1.run(DiscoveryServiceRegistryImpl.java:1)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.smarthome.config.discovery.internal.DiscoveryServiceRegistryImpl.thingDiscovered(DiscoveryServiceRegistryImpl.java:262)
	at org.eclipse.smarthome.config.discovery.AbstractDiscoveryService.thingDiscovered(AbstractDiscoveryService.java:279)
	at org.openhab.binding.mqtt.homeassistant.internal.discovery.HomeAssistantDiscovery.publishResults(HomeAssistantDiscovery.java:199)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

@jochen314, do you know why are this discovery processes executed when a new Thing is added? That's what I was trying to avoid with https://github.com/openhab/openhab-addons/pull/7716, perhaps I should try to push it again :wink:
