### ISSUE TITLE
[samsungtv] [v3] Couldn't execute commandline 'arp 192.168.15.54'

### ISSUE THREAD

**Issue by lduesing** [openhab/openhab-addons#7697]
## Expected Behavior
Initializing addon

## Current Behavior
[ERROR] [rg.openhab.core.io.net.exec.ExecUtil] - couldn't execute commandLine 'arp 192.168.15.54'
java.io.IOException: Cannot run program "arp 192.168.15.54": error=2, Datei oder Verzeichnis nicht gefunden
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1128) ~[?:?]
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1071) ~[?:?]
        at org.openhab.core.io.net.exec.ExecUtil.internalExecute(ExecUtil.java:103) [bundleFile:?]
        at org.openhab.core.io.net.exec.ExecUtil.executeCommandLineAndWaitResponse(ExecUtil.java:72) [bundleFile:?]
        at org.openhab.binding.samsungtv.internal.WakeOnLanUtility.getMACAddress(WakeOnLanUtility.java:77) [bundleFile:?]
        at org.openhab.binding.samsungtv.internal.handler.SamsungTvHandler.thingDiscovered(SamsungTvHandler.java:342) [bundleFile:?]
        at org.openhab.core.config.discovery.internal.DiscoveryServiceRegistryImpl.lambda$1(DiscoveryServiceRegistryImpl.java:187) [bundleFile:?]
        at java.lang.Iterable.forEach(Iterable.java:75) [?:?]
        at org.openhab.core.config.discovery.internal.DiscoveryServiceRegistryImpl.lambda$0(DiscoveryServiceRegistryImpl.java:187) [bundleFile:?]
        at java.util.HashMap.forEach(HashMap.java:1336) [?:?]
        at org.openhab.core.config.discovery.internal.DiscoveryServiceRegistryImpl.addDiscoveryListener(DiscoveryServiceRegistryImpl.java:186) [bundleFile:?]
        at org.openhab.binding.samsungtv.internal.handler.SamsungTvHandler.initialize(SamsungTvHandler.java:159) [bundleFile:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.openhab.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:152) [bundleFile:?]
        at org.openhab.core.internal.common.Invocation.call(Invocation.java:52) [bundleFile:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.io.IOException: error=2, Datei oder Verzeichnis nicht gefunden
        at java.lang.ProcessImpl.forkAndExec(Native Method) ~[?:?]
        at java.lang.ProcessImpl.<init>(ProcessImpl.java:340) ~[?:?]
        at java.lang.ProcessImpl.start(ProcessImpl.java:271) ~[?:?]
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1107) ~[?:?]
        ... 21 more

## Possible Solution
I got none. 

## Steps to Reproduce (for Bugs)

1. initialize plugin 
2.

## Context
On every try to initialize the plugin, on each TV set.

## Your Environment

openhab-3.0.0-SNAPSHOT
openhab-addons-3.0.0-SNAPSHOT.kar

Both Build #1855 / 2020/05/19

**Comment by lolodomo** [comment]
And with OH 2.5.5 ? 
At my knowledge, OH 3 does not yet contain last changes done on the bindings.

**Comment by lolodomo** [comment]
I think it makes no sense to report bugs for bindings built form the master branch. The current reference branch for binding is the 2.5.x branch.

**Comment by lduesing** [comment]
Works on 2.5.6-SNAPSHOT Build #124   / 2020/05/20
As well as on the docker image 3.0.0-SNAPSHOT (which is 10 days old)

**Comment by lolodomo** [comment]
That is not a surprise because I improved that in the 2.5.5 version.
As mentioned, don't use the v3 built, they do not contain all recent changes.

I suggest to close this issue and you could reopen it if still relevant when OH3 is released.

**Comment by lduesing** [comment]
That is ok with me. I just wanted to tell at once. I am just playing with v3. 
Thanks and keep healthy!
