### ISSUE TITLE
[homematic ipwired] No function after a few days

### ISSUE THREAD

**Issue by thielen-t** [openhab/openhab-addons#7762]
@MHerbst  
after I have done the Update to 2.5.5 I have problems with Homematic IP Wired.

After rebooting openHab everything ist OK.
A few days later the HomematicWired things doesn't work.

Maybe there is a context to #7473 

![99289294_10221902480380948_8498322394115473408_o](https://user-images.githubusercontent.com/65848728/82750089-28a51800-9dae-11ea-8b4c-ba6ad66fb6ac.jpg)

**Comment by MHerbst** [comment]
I remember that there have been several problems like this before 2.5.5. Always in combination with HmIP devices. 

In this situation the binding tries to set a value but the CCU does not respond in time. You can try to set a higher timeout value in the bridge configuration (you have press "Show More" to see the value).

What kind of CCU are you using?

**Comment by thielen-t** [comment]
With 2.5.4 I don't have these problemes.
But I will try to set the value.
My CCU is the CCU3.

**Comment by chrostek** [comment]
same here. only hmip, but no problems before 2.5.5
now after about 20-24 hours this error appears in the logs and nothing with hmip works.
ccu restart does not help, binding restart results in

hmip=false in the HmGatewayInfo

HmGatewayInfo[id=CCU,type=CCU2,firmware=3.51.6.20200420,address=PEQ1944622,rf=true,wired=false,hmip=false,cuxd=false,group=true]

only a complete restart of openhab solves the problem.

**Comment by MHerbst** [comment]
Hmm, that's strange. Especially that it seems to happen only if probably several HmIP devices are used. I am using the binding too, but have only 1 HmIP device and did not have this problem before.

@chrostek Do you get the same exception in openhab.log
@thielen-t If this exception happens again please also post the lines before and after the exception

I see a possible cause of this problem. Maybe I can provide a test version of the binding (also with some enhanced message output) this afternoon.

**Comment by chrostek** [comment]
> 2020-05-23 21:00:52.604 [ERROR] [ternal.handler.HomematicThingHandler] - null
> java.io.IOException: null
>         at org.openhab.binding.homematic.internal.communicator.client.XmlRpcClient.sendMessage(XmlRpcClient.java:116) ~[bundleFile:?]
>         at org.openhab.binding.homematic.internal.communicator.client.XmlRpcClient.sendMessage(XmlRpcClient.java:120) ~[bundleFile:?]
>         at org.openhab.binding.homematic.internal.communicator.client.XmlRpcClient.sendMessage(XmlRpcClient.java:71) ~[bundleFile:?]
>         at org.openhab.binding.homematic.internal.communicator.client.RpcClient.setDatapointValue(RpcClient.java:335) ~[bundleFile:?]
>         at org.openhab.binding.homematic.internal.communicator.AbstractHomematicGateway$1.execute(AbstractHomematicGateway.java:686) ~[bundleFile:?]
>         at org.openhab.binding.homematic.internal.misc.DelayedExecuter.start(DelayedExecuter.java:65) ~[bundleFile:?]
>         at org.openhab.binding.homematic.internal.communicator.AbstractHomematicGateway.sendDatapoint(AbstractHomematicGateway.java:665) ~[bundleFile:?]
>         at org.openhab.binding.homematic.internal.communicator.AbstractHomematicGateway.sendDatapoint(AbstractHomematicGateway.java:644) ~[bundleFile:?]
>         at org.openhab.binding.homematic.internal.handler.HomematicThingHandler.sendDatapoint(HomematicThingHandler.java:306) ~[bundleFile:?]
>         at org.openhab.binding.homematic.internal.handler.HomematicThingHandler.handleCommand(HomematicThingHandler.java:282) [bundleFile:?]
>         at sun.reflect.GeneratedMethodAccessor95.invoke(Unknown Source) ~[?:?]
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
>         at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
>         at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:152) [bundleFile:?]
>         at org.eclipse.smarthome.core.internal.common.InvocationHandlerSync.invoke(InvocationHandlerSync.java:59) [bundleFile:?]
>         at com.sun.proxy.$Proxy5493.handleCommand(Unknown Source) [?:?]
>         at org.eclipse.smarthome.core.thing.internal.profiles.ProfileCallbackImpl.handleCommand(ProfileCallbackImpl.java:74) [bundleFile:?]
>         at org.eclipse.smarthome.core.thing.internal.profiles.SystemDefaultProfile.onCommandFromItem(SystemDefaultProfile.java:48) [bundleFile:?]
>         at sun.reflect.GeneratedMethodAccessor94.invoke(Unknown Source) ~[?:?]
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
>         at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
>         at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:152) [bundleFile:?]
>         at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:52) [bundleFile:?]
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_252]
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
>         at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
> Caused by: java.util.concurrent.TimeoutException
>         at org.eclipse.jetty.client.util.InputStreamResponseListener.get(InputStreamResponseListener.java:216) ~[bundleFile:9.4.20.v20190813]
>         at org.openhab.binding.homematic.internal.communicator.client.XmlRpcClient.sendMessage(XmlRpcClient.java:89) ~[bundleFile:?]
>         ... 26 more

i get this every 30 seconds after the error appeared for the first time

**Comment by thielen-t** [comment]
Thanks for your response.
I will check it the next days.

@chrostek your log looks like my log

**Comment by MHerbst** [comment]
@chrostek @thielen-t I have changed the binding and added a bit more detailed output if this exception occurs again.

You can download it from here: https://github.com/MHerbst/openhab-addons-test/blob/master/org.openhab.binding.homematic-2.5.6-SNAPSHOT.jar

To install it please proceed as follow:
- uninstall the Homematic binding
- stop openHAB
- clear the content of the cache folder
- copy the jar to the addons folder
- start openHAB new

**Comment by thielen-t** [comment]
thanks for your work, I will test it.

**Comment by chrostek** [comment]
thanks, i have installed your version and will wait for the error :-)

**Comment by chrostek** [comment]
crashed again, here your new logging (every 30 seconds from this time on):

> 2020-05-25 22:12:25.706 [ERROR] [ternal.handler.HomematicThingHandler] - setValuefailed: null
> java.io.IOException: setValuefailed: null
>         at org.openhab.binding.homematic.internal.communicator.client.XmlRpcClient.sendMessage(XmlRpcClient.java:117) ~[bundleFile:?]
>         at org.openhab.binding.homematic.internal.communicator.client.XmlRpcClient.sendMessage(XmlRpcClient.java:121) ~[bundleFile:?]
>         at org.openhab.binding.homematic.internal.communicator.client.XmlRpcClient.sendMessage(XmlRpcClient.java:71) ~[bundleFile:?]
>         at org.openhab.binding.homematic.internal.communicator.client.RpcClient.setDatapointValue(RpcClient.java:335) ~[bundleFile:?]
>         at org.openhab.binding.homematic.internal.communicator.AbstractHomematicGateway$1.execute(AbstractHomematicGateway.java:686) ~[bundleFile:?]
>         at org.openhab.binding.homematic.internal.misc.DelayedExecuter.start(DelayedExecuter.java:65) ~[bundleFile:?]
>         at org.openhab.binding.homematic.internal.communicator.AbstractHomematicGateway.sendDatapoint(AbstractHomematicGateway.java:665) ~[bundleFile:?]
>         at org.openhab.binding.homematic.internal.communicator.AbstractHomematicGateway.sendDatapoint(AbstractHomematicGateway.java:644) ~[bundleFile:?]
>         at org.openhab.binding.homematic.internal.handler.HomematicThingHandler.sendDatapoint(HomematicThingHandler.java:306) ~[bundleFile:?]
>         at org.openhab.binding.homematic.internal.handler.HomematicThingHandler.handleCommand(HomematicThingHandler.java:282) [bundleFile:?]
>         at sun.reflect.GeneratedMethodAccessor126.invoke(Unknown Source) ~[?:?]
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
>         at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
>         at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:152) [bundleFile:?]
>         at org.eclipse.smarthome.core.internal.common.InvocationHandlerSync.invoke(InvocationHandlerSync.java:59) [bundleFile:?]
>         at com.sun.proxy.$Proxy6134.handleCommand(Unknown Source) [?:?]
>         at org.eclipse.smarthome.core.thing.internal.profiles.ProfileCallbackImpl.handleCommand(ProfileCallbackImpl.java:74) [bundleFile:?]
>         at org.eclipse.smarthome.core.thing.internal.profiles.SystemDefaultProfile.onCommandFromItem(SystemDefaultProfile.java:48) [bundleFile:?]
>         at sun.reflect.GeneratedMethodAccessor125.invoke(Unknown Source) ~[?:?]
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
>         at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
>         at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:152) [bundleFile:?]
>         at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:52) [bundleFile:?]
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_252]
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
>         at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
> Caused by: java.util.concurrent.TimeoutException
>         at org.eclipse.jetty.client.util.InputStreamResponseListener.get(InputStreamResponseListener.java:216) ~[bundleFile:9.4.20.v20190813]
>         at org.openhab.binding.homematic.internal.communicator.client.XmlRpcClient.sendMessage(XmlRpcClient.java:89) ~[bundleFile:?]
>         ... 26 more
> 2020-05-25 22:13:12.332 [INFO ] [nal.communicator.client.XmlRpcClient] - XmlRpcMessage failure, sending message again 1/1
> 

and as before, if i do a:

> ssh openhab@localhost -p8101 'bundle:restart org.openhab.binding.homematic'

i get:

> [INFO ] [ommunicator.AbstractHomematicGateway] - HmGatewayInfo[id=CCU,type=CCU2,firmware=3.51.6.20200420,address=PEQ1944622,rf=true,wired=false,hmip=false,cuxd=false,group=true]

(hmip=false)
so something in openHAB seems to be crashed/hung at the time the error appeared first

**Comment by MHerbst** [comment]
Yesterday I also got this error for the first time in my environment. It happened while I was using two OH installations at the same time. Are you also using more than one OH installations or did you used the ccu web interface at the same the exception happened? It seems to me that it crashed the HmIP service on the Ccu. Are You using a CCU2 or is it a Raspberrymatic or something else?

**Comment by chrostek** [comment]
I am using RaspberryMatic (latest version on CCU3/Charly hardware). i did not use a second OH installation or the ccu webinterface at this time. but i have an icinga check which querys the xmlapi on the ccu every 10 minutes to check if devices are offline or have service messages - but i do this already for a few years - nothing changed.

**Comment by thielen-t** [comment]
I don't have any problems, since installation. 
But my timeout value is still 45.

**Comment by thielen-t** [comment]
New Error:
![Unbenannt](https://user-images.githubusercontent.com/65848728/82880910-4fdf1f00-9f3f-11ea-83d6-12112ebfc987.JPG)


But only openHab said it is offline.
For the Homematic CCU3 it isn't offline.

**Comment by MHerbst** [comment]
It seem that the CCU in combination with HmIP devices is a bit sensitive. I think I can revert the implementation to the pre 2.5.5 version and use the current communication technique only if the messages sent by the CCU are too larger. This should solve this problem.

**Comment by chrostek** [comment]
what if i have a lange installation with hmip devices ;-)

**Comment by MHerbst** [comment]
In most request the large buffer support is not necessary. E.g. your last log output showed that a setValue request failed. This request will never need s large buffer. As far as I know the response from the CCU can only be too large when a discovery is executed or at the start. On the other side, it seems that the CCU has got problems if all request are executed with like it is done now.

Therefore, I think a combination of both techniques can solve the problem. This means the binding will always try the pre 2.5.5 method. If the request fails because of a too-large response, it will try the request again with large buffer support.

BTW can you have a look into the CCU's log file? It would be interesting to see if there are any messages logged at the time the request from openHAB failed.

**Comment by chrostek** [comment]
ok, thanks for the details

in /var/log/messages and /var/log/hmserver.log is nothing special at the time of the crash

**Comment by thielen-t** [comment]
@MHerbst  since today I have problemens with Homematic.

Here the Log
2020-05-27 18:53:12.418 [hingStatusInfoChangedEvent] - 'homematic:HM-LC-Bl1PBU-FM:3014F711A0001F9A498BA50A:OEQ0886178' changed from ONLINE to OFFLINE (COMMUNICATION_ERROR)

==> /var/log/openhab2/openhab.log <==

2020-05-27 18:53:12.412 [ERROR] [ternal.handler.HomematicThingHandler] - -1 Failure (sending <?xml version="1.0" encoding="ISO-8859-1"?>

<methodCall><methodName>setValue</methodName>

<params><param><value>OEQ0886178:1</value></param><param><value>LEVEL</value></param><param><value><double>0.99</double></value></param></params></methodCall>)

org.openhab.binding.homematic.internal.communicator.client.UnknownRpcFailureException: -1 Failure (sending <?xml version="1.0" encoding="ISO-8859-1"?>

<methodCall><methodName>setValue</methodName>

<params><param><value>OEQ0886178:1</value></param><param><value>LEVEL</value></param><param><value><double>0.99</double></value></param></params></methodCall>)

	at org.openhab.binding.homematic.internal.communicator.parser.RpcResponseParser.parse(RpcResponseParser.java:47) ~[bundleFile:?]

	at org.openhab.binding.homematic.internal.communicator.client.XmlRpcClient.sendMessage(XmlRpcClient.java:112) ~[bundleFile:?]

	at org.openhab.binding.homematic.internal.communicator.client.XmlRpcClient.sendMessage(XmlRpcClient.java:71) ~[bundleFile:?]

	at org.openhab.binding.homematic.internal.communicator.client.RpcClient.setDatapointValue(RpcClient.java:335) ~[bundleFile:?]

	at org.openhab.binding.homematic.internal.communicator.AbstractHomematicGateway$1.execute(AbstractHomematicGateway.java:686) ~[bundleFile:?]

	at org.openhab.binding.homematic.internal.misc.DelayedExecuter.start(DelayedExecuter.java:65) ~[bundleFile:?]

	at org.openhab.binding.homematic.internal.communicator.AbstractHomematicGateway.sendDatapoint(AbstractHomematicGateway.java:665) ~[bundleFile:?]

	at org.openhab.binding.homematic.internal.communicator.AbstractHomematicGateway.sendDatapoint(AbstractHomematicGateway.java:644) ~[bundleFile:?]

	at org.openhab.binding.homematic.internal.handler.HomematicThingHandler.sendDatapoint(HomematicThingHandler.java:306) ~[bundleFile:?]

	at org.openhab.binding.homematic.internal.handler.HomematicThingHandler.handleCommand(HomematicThingHandler.java:282) [bundleFile:?]

	at sun.reflect.GeneratedMethodAccessor817.invoke(Unknown Source) ~[?:?]

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]

	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]

	at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:152) [bundleFile:?]

	at org.eclipse.smarthome.core.internal.common.InvocationHandlerSync.invoke(InvocationHandlerSync.java:59) [bundleFile:?]

	at com.sun.proxy.$Proxy22828.handleCommand(Unknown Source) [?:?]

	at org.eclipse.smarthome.core.thing.internal.profiles.ProfileCallbackImpl.handleCommand(ProfileCallbackImpl.java:74) [bundleFile:?]

	at org.eclipse.smarthome.core.thing.internal.profiles.SystemDefaultProfile.onCommandFromItem(SystemDefaultProfile.java:48) [bundleFile:?]

	at sun.reflect.GeneratedMethodAccessor816.invoke(Unknown Source) ~[?:?]

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]

	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]

	at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:152) [bundleFile:?]

	at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:52) [bundleFile:?]

	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_252]

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]

	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]

**Comment by thielen-t** [comment]
@MHerbst now i have to reboot the Homematic CCU too.

The states of my Rollershuter didn't fit together.

OpenHab state = 100            Homematic state = 1(0)      realstate = 1(0)
OpenHab state = 1                Homematic state = 100 (99)   realstat = 100 (99)

**Comment by MHerbst** [comment]
@thielen-t Rollershutters are something really special. There is already another issue here (https://github.com/openhab/openhab-addons/issues/6145). I have seen that the binding inverts the value reported by Homematic depending on the device type. And it seems that Homematic devices use different values. Maybe you can add your information to the other issue.

**Comment by MHerbst** [comment]
@thielen-t @chrostek I have uploaded a new test version: https://github.com/MHerbst/openhab-addons-test/blob/master/org.openhab.binding.homematic-2.5.6-SNAPSHOT.jar Would be great if you could test it and give me feedback whether the binding is more stable with this version. If it is better I will create a PR.

**Comment by thielen-t** [comment]
@MHerbst  thank you, I will test it tomorrow.

**Comment by chrostek** [comment]
thank you - i am getting this warning on openhab start with this version (cache cleaned before start):

```
2020-06-01 22:06:26.733 [WARN ] [org.apache.felix.fileinstall        ] - Error while starting bundle: file:/usr/share/openhab2/addons/org.openhab.binding.homematic-2.5.6-SNAPSHOT.jar
org.osgi.framework.BundleException: Could not resolve module: org.openhab.binding.homematic [204]
  Unresolved requirement: Import-Package: org.eclipse.smarthome.config.discovery.upnp

        at org.eclipse.osgi.container.Module.start(Module.java:444) ~[org.eclipse.osgi-3.12.100.jar:?]
        at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:383) ~[org.eclipse.osgi-3.12.100.jar:?]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1260) [bundleFile:3.6.4]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1233) [bundleFile:3.6.4]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:520) [bundleFile:3.6.4]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:365) [bundleFile:3.6.4]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:316) [bundleFile:3.6.4]

```

but it seems to work

**Comment by MHerbst** [comment]
@chrostek This seems to be a general timing issue. I get the same warnings (not only for the Homematic binding) each time after deleting the cache. It seems that the jars in addons folder are loaded too early. Therefore I always start openHAB twice after cleaning the cache.

**Comment by chrostek** [comment]
ok, thanks. i restarted twice as everytime after cleaning the cache and at the second restart there was no error. 

the binding runs for nearly 24 hours - it had 3 error messages like this:

```
2020-06-02 15:01:45.748 [ERROR] [ternal.handler.HomematicThingHandler] - Total timeout 15000 ms elapsed
java.io.IOException: Total timeout 15000 ms elapsed
        at org.openhab.binding.homematic.internal.communicator.client.XmlRpcClient.sendMessage(XmlRpcClient.java:83) ~[bundleFile:?]
        at org.openhab.binding.homematic.internal.communicator.client.RpcClient.setDatapointValue(RpcClient.java:335) ~[bundleFile:?]
        at org.openhab.binding.homematic.internal.communicator.AbstractHomematicGateway$1.execute(AbstractHomematicGateway.java:686) ~[bundleFile:?]
        at org.openhab.binding.homematic.internal.misc.DelayedExecuter.start(DelayedExecuter.java:65) ~[bundleFile:?]
        at org.openhab.binding.homematic.internal.communicator.AbstractHomematicGateway.sendDatapoint(AbstractHomematicGateway.java:665) ~[bundleFile:?]
        at org.openhab.binding.homematic.internal.communicator.AbstractHomematicGateway.sendDatapoint(AbstractHomematicGateway.java:644) ~[bundleFile:?]
        at org.openhab.binding.homematic.internal.handler.HomematicThingHandler.sendDatapoint(HomematicThingHandler.java:306) ~[bundleFile:?]
        at org.openhab.binding.homematic.internal.handler.HomematicThingHandler.handleCommand(HomematicThingHandler.java:282) [bundleFile:?]
        at sun.reflect.GeneratedMethodAccessor105.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
        at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:152) [bundleFile:?]
        at org.eclipse.smarthome.core.internal.common.InvocationHandlerSync.invoke(InvocationHandlerSync.java:59) [bundleFile:?]
        at com.sun.proxy.$Proxy2911.handleCommand(Unknown Source) [?:?]
        at org.eclipse.smarthome.core.thing.internal.profiles.ProfileCallbackImpl.handleCommand(ProfileCallbackImpl.java:74) [bundleFile:?]
        at org.eclipse.smarthome.core.thing.internal.profiles.SystemDefaultProfile.onCommandFromItem(SystemDefaultProfile.java:48) [bundleFile:?]
        at sun.reflect.GeneratedMethodAccessor104.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
        at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:152) [bundleFile:?]
        at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:52) [bundleFile:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_252]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
Caused by: java.util.concurrent.TimeoutException: Total timeout 15000 ms elapsed
        at org.eclipse.jetty.client.TimeoutCompleteListener.onTimeoutExpired(TimeoutCompleteListener.java:51) ~[?:?]
        at org.eclipse.jetty.io.CyclicTimeout$Wakeup.run(CyclicTimeout.java:282) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_252]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_252]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_252]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:1.8.0_252]
        ... 3 more

```

But everything is still working.

**Comment by MHerbst** [comment]
@chrostek @thielen-t I have re-activated a retry. Maybe this reduces the timeout messages. You can find it here: https://github.com/MHerbst/openhab-addons-test/blob/master/org.openhab.binding.homematic-2.5.6-SNAPSHOT.jar

**Comment by chrostek** [comment]
thanks. i installed it and will try. but i had no more timeouts since i changed the timeout from 15 to 30 - maybe you should change the default timeout value to a higher value than 15?

**Comment by MHerbst** [comment]
I would assume that for the most installations a timeout value of 15s is sufficient. I can't remember that I had a timeout in the past. I have now re-activated a retry, i.e. the binding tries a maximum of 3 times to send the request (each with the configured timeout). I would assume that this will work in most situations.

**Comment by chrostek** [comment]
the snapshot works for many days now without any issues - can you please make a pull request with this code? it seems that they do a point release every month - would be great if this gets into 2.5.6 :-)

**Comment by MHerbst** [comment]
> the snapshot works for many days now without any issues - can you please make a pull request with this code? it seems that they do a point release every month - would be great if this gets into 2.5.6 :-)

Thanks for the information. PR has been created.

**Comment by chrostek** [comment]
thanks!
