### ISSUE TITLE
[amazonechocontrol] Websocket error after out of memory OH2 crash

### ISSUE THREAD

**Issue by Wikibear** [openhab/openhab-addons#7910]
Get websocket error of amazon binding and after a while out of memory.

https://community.openhab.org/t/web-socket-error/100553

**Comment by Wikibear** [comment]
`
2020-06-13 10:49:26.260 [INFO ] [control.internal.WebSocketConnection] - Web Socket error
java.nio.channels.AsynchronousCloseException: null
        at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.close(HttpConnectionOverHTTP.java:181) ~[?:?]
        at java.util.ArrayList.forEach(ArrayList.java:1257) [?:1.8.0_252]
        at org.eclipse.jetty.client.AbstractConnectionPool.close(AbstractConnectionPool.java:208) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.client.DuplexConnectionPool.close(DuplexConnectionPool.java:237) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.client.HttpDestination.close(HttpDestination.java:385) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.client.HttpClient.doStop(HttpClient.java:260) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:93) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.stop(ContainerLifeCycle.java:180) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStop(ContainerLifeCycle.java:201) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.websocket.client.WebSocketClient.doStop(WebSocketClient.java:371) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:93) [bundleFile:9.4.20.v20190813]
        at org.openhab.binding.amazonechocontrol.internal.WebSocketConnection.close(WebSocketConnection.java:159) [bundleFile:?]
        at org.openhab.binding.amazonechocontrol.internal.handler.AccountHandler.closeWebSocketConnection(AccountHandler.java:374) [bundleFile:?]
        at org.openhab.binding.amazonechocontrol.internal.handler.AccountHandler.cleanup(AccountHandler.java:298) [bundleFile:?]
        at org.openhab.binding.amazonechocontrol.internal.handler.AccountHandler.dispose(AccountHandler.java:263) [bundleFile:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
        at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:152) [bundleFile:?]
        at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:52) [bundleFile:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_252]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]`

**Comment by olialb** [comment]
I can confirm the same issue. Please have a look in it.

**Comment by helmar74** [comment]
Same issue here.

**Comment by haribo01** [comment]
1+

**Comment by lucarui** [comment]
+1

**Comment by andyzle** [comment]
+1

**Comment by andyzle** [comment]
See also [Web Socket Error on AmazonEchoControl binding every 65 seconds](https://community.openhab.org/t/web-socket-error-on-amazonechocontrol-binding-every-65-seconds/100581)

**Comment by jaywiseman1971** [comment]
I've been running this version since it came out w/o any issues still.  Have 15 Echo's that used quite a bit daily.  It has over 629 downloads from it since it was released.

https://community.openhab.org/t/release-candidate-and-support-amazon-echo-control-binding/37844

I'm also running OH 2.4 which may be a variable to be aware of.

Best, Jay

**Comment by vdraack** [comment]
+1

**Comment by GumbyMan82** [comment]
+1 Just for completeness:

Normally I get the following exception:
```
2020-06-13 22:53:22.202 [INFO ] [control.internal.WebSocketConnection] - Web Socket error
java.nio.channels.AsynchronousCloseException: null
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.close(HttpConnectionOverHTTP.java:181) [bundleFile:9.4.20.v20190813]
	at java.util.ArrayList.forEach(ArrayList.java:1540) [?:?]
	at org.eclipse.jetty.client.AbstractConnectionPool.close(AbstractConnectionPool.java:208) [bundleFile:9.4.20.v20190813]
	at org.eclipse.jetty.client.DuplexConnectionPool.close(DuplexConnectionPool.java:237) [bundleFile:9.4.20.v20190813]
	at org.eclipse.jetty.client.HttpDestination.close(HttpDestination.java:385) [bundleFile:9.4.20.v20190813]
	at org.eclipse.jetty.client.HttpClient.doStop(HttpClient.java:260) [bundleFile:9.4.20.v20190813]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:93) [bundleFile:9.4.20.v20190813]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.stop(ContainerLifeCycle.java:180) [bundleFile:9.4.20.v20190813]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStop(ContainerLifeCycle.java:201) [bundleFile:9.4.20.v20190813]
	at org.eclipse.jetty.websocket.client.WebSocketClient.doStop(WebSocketClient.java:371) [bundleFile:9.4.20.v20190813]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:93) [bundleFile:9.4.20.v20190813]
	at org.openhab.binding.amazonechocontrol.internal.WebSocketConnection.close(WebSocketConnection.java:159) [bundleFile:?]
	at org.openhab.binding.amazonechocontrol.internal.WebSocketConnection$2.run(WebSocketConnection.java:184) [bundleFile:?]
	at java.util.TimerThread.mainLoop(Timer.java:556) [?:?]
	at java.util.TimerThread.run(Timer.java:506) [?:?]
```

But as others also report OH crashes as well sometimes. In that case, i see the following exception.
```
2020-06-13 22:55:03.188 [INFO ] [control.internal.WebSocketConnection] - Web Socket error
org.eclipse.jetty.io.EofException: null
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:283) ~[?:?]
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.flush(SslConnection.java:910) ~[?:?]
	at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:422) ~[?:?]
	at org.eclipse.jetty.io.WriteFlusher.completeWrite(WriteFlusher.java:378) ~[?:?]
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.lambda$fill$1(SslConnection.java:669) ~[?:?]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:782) [bundleFile:9.4.20.v20190813]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:918) [bundleFile:9.4.20.v20190813]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.io.IOException: Broken pipe
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method) ~[?:?]
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47) ~[?:?]
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:113) ~[?:?]
	at sun.nio.ch.IOUtil.write(IOUtil.java:58) ~[?:?]
	at sun.nio.ch.IOUtil.write(IOUtil.java:50) ~[?:?]
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:466) ~[?:?]
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:261) ~[?:?]
	
```

**Comment by idkpmiller** [comment]
+1
Had to return to backup, not sure what had gone on memory leak and things seemed to be missing so I rolled back, disabled the binding and all came right. major loss of functionality as no lastvoicecommand capability.

I am going to try an older version of the binding to see if that helps.
currently broke version is 2.5.5

**Comment by olialb** [comment]
@GumbyMan82: Thanks for highlight tw type of exceptions. 
Can this be a difference between 2.5.4 and 2.5.5? My OH had 2.5.4 when it chrashed. Now I updated to 2.5.5 and I get the first execption...

**Comment by magicofit** [comment]
same error-combination here:
Web Socket errors->memory running low->things jsondb corrupt.
As a first "solution" i disabled my "amazon account"-thing to stop the errors. 

I think now my openhab is stable again....but without echo-functionalities :(

**Comment by nesys** [comment]
+1 same issue here. 2.5.5.1

**Comment by alex-voigt** [comment]
+1

**Comment by KaiLuettmann** [comment]
+1

**Comment by GumbyMan82** [comment]
> @GumbyMan82: Thanks for highlight tw type of exceptions.
> Can this be a difference between 2.5.4 and 2.5.5? My OH had 2.5.4 when it chrashed. Now I updated to 2.5.5 and I get the first execption...

@olialb Honestely i don't know. But since the echocontrol binding hasn't changed between 2.5.4 and 2.5.5 i believe that you'll propebaly get the same errors. Maybe your openHAB instance crashed due to something else?

**Comment by tom-kaltofen** [comment]
+1

**Comment by puuhderbaer** [comment]
+1

**Comment by olialb** [comment]
> @olialb Honestely i don't know. But since the echocontrol binding hasn't changed between 2.5.4 and 2.5.5 i believe that you'll propebaly get the same errors. Maybe your openHAB instance crashed due to something else?

@GumbyMan82 : Yes possible that it was caused by another problem. Only strange that other see same issues to.

**Comment by rickoman** [comment]
I had made no changes to my system when I started seeing these issues.  Maybe it is a change on Amazon's side that is revealing an old bug or now invalid assumption in the binding.

**Comment by daynaskully** [comment]
> I had made no changes to my system when I started seeing these issues. Maybe it is a change on Amazon's side that is revealing an old bug or now invalid assumption in the binding.

Same. Old system working for months, no changes. Now I'm here.

**Comment by jaywiseman1971** [comment]
JNK @ GitHub fixed the RC version of the binding earlier this week.  The fix is here.

https://ci.openhab.org/job/openHAB2.5.x-Addons/ws/bundles/org.openhab.binding.amazonechocontrol/target/ 

Best, Jay

**Comment by BigGeorgeTx** [comment]
I was able to load it using this method:
https://community.openhab.org/t/solved-openhabian-how-do-i-update-one-binding-to-latest-snapshot-only/69324

**Comment by modenet** [comment]
when it will be release?

**Comment by J-N-K** [comment]
Already part of 2.5.6
