### ISSUE TITLE
[lghombot] out of bounds exception on startup

### ISSUE THREAD

**Issue by mstormi** [openhab/openhab-addons#8036]
getting this on every OH startup
OH 2.5.6-2 with Zulu 11 OpenJDK Client VM Zulu11.39+61-CA (build 11.0.7+10-LTS, mixed mode)

```
2020-06-28 15:48:45.564 [WARN ] [ng.lghombot.internal.LGHomBotHandler] - Channel refresh for pause not implemented!
2020-06-28 15:48:45.703 [ERROR] [ome.core.thing.link.ThingLinkManager] - Exception occurred while informing handler: Index 84 out of bounds for length 73
java.lang.ArrayIndexOutOfBoundsException: Index 84 out of bounds for length 73
        at org.openhab.binding.lghombot.internal.LGHomBotHandler.parseMap(LGHomBotHandler.java:617) ~[?:?]
        at org.openhab.binding.lghombot.internal.LGHomBotHandler.refreshFromState(LGHomBotHandler.java:309) ~[?:?]
        at org.openhab.binding.lghombot.internal.LGHomBotHandler.handleCommand(LGHomBotHandler.java:107) ~[?:?]
        at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.channelLinked(BaseThingHandler.java:191) ~[bundleFile:?]
        at org.eclipse.smarthome.core.thing.link.ThingLinkManager.lambda$0(ThingLinkManager.java:267) [bundleFile:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by hmerk** [comment]
@mstormi Is this still valid for oh 3.3 .
If not, please close this issue.

**Comment by mstormi** [comment]
haven't seen lately
