### ISSUE TITLE
[nikohomecontrol] Niko home control 2 Digital black thermostat 

### ISSUE THREAD

**Issue by hadberg6200** [openhab/openhab-addons#8099]
When adding thermostat in the digital black the binder are crashing

## Expected Behavior
Works as the normal thermostats

## Current Behavior
Throws this exeption:
_2020-07-10 12:10:30.214 [ERROR] [ansport.mqtt.internal.ClientCallback] - MQTT message received. MqttMessageSubscriber#processMessage() implementation failure

java.lang.NullPointerException: null

	at org.openhab.binding.nikohomecontrol.internal.protocol.nhc2.NikoHomeControlCommunication2.updateThermostatState(NikoHomeControlCommunication2.java:496) ~[?:?]

	at org.openhab.binding.nikohomecontrol.internal.protocol.nhc2.NikoHomeControlCommunication2.updateState(NikoHomeControlCommunication2.java:439) ~[?:?]

	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_252]

	at org.openhab.binding.nikohomecontrol.internal.protocol.nhc2.NikoHomeControlCommunication2.devicesEvt(NikoHomeControlCommunication2.java:314) ~[?:?]

	at org.openhab.binding.nikohomecontrol.internal.protocol.nhc2.NikoHomeControlCommunication2.processMessage(NikoHomeControlCommunication2.java:778) ~[?:?]

	at org.eclipse.smarthome.io.transport.mqtt.internal.ClientCallback.lambda$3(ClientCallback.java:96) ~[?:?]

	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_252]

	at org.eclipse.smarthome.io.transport.mqtt.internal.ClientCallback.messageArrived(ClientCallback.java:96) ~[?:?]

	at org.eclipse.smarthome.io.transport.mqtt.internal.ClientCallback.messageArrived(ClientCallback.java:71) ~[?:?]

	at com.hivemq.client.internal.mqtt.mqtt3.Mqtt3AsyncClientView.lambda$callbackView$1(Mqtt3AsyncClientView.java:73) ~[bundleFile:?]

	at com.hivemq.client.internal.mqtt.MqttAsyncClient$CallbackSubscriber.onNext(MqttAsyncClient.java:227) [bundleFile:?]

	at com.hivemq.client.internal.mqtt.MqttAsyncClient$CallbackSubscriber.onNext(MqttAsyncClient.java:212) [bundleFile:?]

	at com.hivemq.client.rx.FlowableWithSingle$SingleFutureSubscriber.onNext(FlowableWithSingle.java:377) [bundleFile:?]

	at com.hivemq.client.internal.rx.operators.FlowableWithSingleCombine$SplitSubscriber$Default.tryOnNextActual(FlowableWithSingleCombine.java:206) [bundleFile:?]

	at com.hivemq.client.internal.rx.operators.FlowableWithSingleCombine$SplitSubscriber.tryOnNext(FlowableWithSingleCombine.java:171) [bundleFile:?]

	at io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnConditionalSubscriber.runAsync(FlowableObserveOn.java:649) [bundleFile:?]

	at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176) [bundleFile:?]

	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66) [bundleFile:?]

	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57) [bundleFile:?]

	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_252]

	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_252]

	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_252]

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]

	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]_

## Possible Solution
Implement error handleing for this error

## Steps to Reproduce (for Bugs)
Update digital black to 2.8.1 and add a thermostat function

## Context
Not able to get any informations from the API

## Your Environment
Running on an raspbian

**Comment by mherwege** [comment]
Could you switch on debug logging? I would like to see the content of the received message. There seems to be a difference with the published api.

**Comment by mherwege** [comment]
@hadberg6200 I do need a debug log to solve this. Catching the exception will not make the thermostat work in OH.

**Comment by sindalschmidt** [comment]
Is this helpful?

> 2020-07-30 15:16:16.440 [TRACE] [l.nhc2.NikoHomeControlCommunication2] - Niko Home Control: received topic hobby/control/devices/evt, payload {"Method":"devices.changed","Params":[{"Devices":[{"PropertyDefinitions":[{"OverruleActive":{"Description":"Boolean","HasStatus":"true","CanControl":"true"}},{"SetpointTemperature":{"Description":"Range(5.00,30.00,0.50)","HasStatus":"true","CanControl":"false"}},{"OverruleSetpoint":{"Description":"Range(5.00,30.00,0.50)","HasStatus":"true","CanControl":"true"}},{"OverruleTime":{"Description":"Range(1.00,1439.00,1.00)","HasStatus":"true","CanControl":"true"}},{"Program":{"Description":"Choice(Day,Night,Eco,Off,Cool,Prog1,Prog2,Prog3)","HasStatus":"true","CanControl":"true"}},{"EcoSave":{"Description":"Boolean","HasStatus":"true","CanControl":"true"}},{"Demand":{"Description":"Choice(Heating,Cooling,None)","HasStatus":"true","CanControl":"false"}},{"AmbientTemperature":{"Description":"Range(-5.00,45.00,0.50)","HasStatus":"true","CanControl":"false"}}],"Uuid":"2a6fc15b-9691-4cb8-b606-395c68cd094c"},{"PropertyDefinitions":[{"OverruleActive":{"Description":"Boolean","HasStatus":"true","CanControl":"true"}},{"SetpointTemperature":{"Description":"Range(5.00,30.00,0.50)","HasStatus":"true","CanControl":"false"}},{"OverruleSetpoint":{"Description":"Range(5.00,30.00,0.50)","HasStatus":"true","CanControl":"true"}},{"OverruleTime":{"Description":"Range(1.00,1439.00,1.00)","HasStatus":"true","CanControl":"true"}},{"Program":{"Description":"Choice(Day,Night,Eco,Off,Cool,Prog1,Prog2,Prog3)","HasStatus":"true","CanControl":"true"}},{"EcoSave":{"Description":"Boolean","HasStatus":"true","CanControl":"true"}},{"Demand":{"Description":"Choice(Heating,Cooling,None)","HasStatus":"true","CanControl":"false"}},{"AmbientTemperature":{"Description":"Range(-5.00,45.00,0.50)","HasStatus":"true","CanControl":"false"}}],"Uuid":"8f357a31-c840-4210-ae3e-cfac085f6f58"},{"PropertyDefinitions":[{"OverruleActive":{"Description":"Boolean","HasStatus":"true","CanControl":"true"}},{"SetpointTemperature":{"Description":"Range(5.00,30.00,0.50)","HasStatus":"true","CanControl":"false"}},{"OverruleSetpoint":{"Description":"Range(5.00,30.00,0.50)","HasStatus":"true","CanControl":"true"}},{"OverruleTime":{"Description":"Range(1.00,1439.00,1.00)","HasStatus":"true","CanControl":"true"}},{"Program":{"Description":"Choice(Day,Night,Eco,Off,Cool,Prog1,Prog2,Prog3)","HasStatus":"true","CanControl":"true"}},{"EcoSave":{"Description":"Boolean","HasStatus":"true","CanControl":"true"}},{"Demand":{"Description":"Choice(Heating,Cooling,None)","HasStatus":"true","CanControl":"false"}},{"AmbientTemperature":{"Description":"Range(-5.00,45.00,0.50)","HasStatus":"true","CanControl":"false"}}],"Uuid":"a294f613-176d-4753-bb8a-0d44247cf4c2"},{"PropertyDefinitions":[{"OverruleActive":{"Description":"Boolean","HasStatus":"true","CanControl":"true"}},{"SetpointTemperature":{"Description":"Range(5.00,30.00,0.50)","HasStatus":"true","CanControl":"false"}},{"OverruleSetpoint":{"Description":"Range(5.00,30.00,0.50)","HasStatus":"true","CanControl":"true"}},{"OverruleTime":{"Description":"Range(1.00,1439.00,1.00)","HasStatus":"true","CanControl":"true"}},{"Program":{"Description":"Choice(Day,Night,Eco,Off,Cool,Prog1,Prog2,Prog3)","HasStatus":"true","CanControl":"true"}},{"EcoSave":{"Description":"Boolean","HasStatus":"true","CanControl":"true"}},{"Demand":{"Description":"Choice(Heating,Cooling,None)","HasStatus":"true","CanControl":"false"}},{"AmbientTemperature":{"Description":"Range(-5.00,45.00,0.50)","HasStatus":"true","CanControl":"false"}}],"Uuid":"1d45d223-7afd-41eb-9c76-e94f35b54146"},{"PropertyDefinitions":[{"OverruleActive":{"Description":"Boolean","HasStatus":"true","CanControl":"true"}},{"SetpointTemperature":{"Description":"Range(5.00,30.00,0.50)","HasStatus":"true","CanControl":"false"}},{"OverruleSetpoint":{"Description":"Range(5.00,30.00,0.50)","HasStatus":"true","CanControl":"true"}},{"OverruleTime":{"Description":"Range(1.00,1439.00,1.00)","HasStatus":"true","CanControl":"true"}},{"Program":{"Description":"Choice(Day,Night,Eco,Off,Cool,Prog1,Prog2,Prog3)","HasStatus":"true","CanControl":"true"}},{"EcoSave":{"Description":"Boolean","HasStatus":"true","CanControl":"true"}},{"Demand":{"Description":"Choice(Heating,Cooling,None)","HasStatus":"true","CanControl":"false"}},{"AmbientTemperature":{"Description":"Range(-5.00,45.00,0.50)","HasStatus":"true","CanControl":"false"}}],"Uuid":"401a381c-3720-4b93-a7ec-515f4a667d0a"}]}]}
2020-07-30 15:16:16.441 [ERROR] [ansport.mqtt.internal.ClientCallback] - MQTT message received. MqttMessageSubscriber#processMessage() implementation failure
java.lang.NullPointerException: null
        at org.openhab.binding.nikohomecontrol.internal.protocol.nhc2.NikoHomeControlCommunication2.updateThermostatState(NikoHomeControlCommunication2.java:496) ~[?:?]
        at org.openhab.binding.nikohomecontrol.internal.protocol.nhc2.NikoHomeControlCommunication2.updateState(NikoHomeControlCommunication2.java:439) ~[?:?]
        at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_251]
        at org.openhab.binding.nikohomecontrol.internal.protocol.nhc2.NikoHomeControlCommunication2.devicesEvt(NikoHomeControlCommunication2.java:314) ~[?:?]
        at org.openhab.binding.nikohomecontrol.internal.protocol.nhc2.NikoHomeControlCommunication2.processMessage(NikoHomeControlCommunication2.java:778) ~[?:?]
        at org.eclipse.smarthome.io.transport.mqtt.internal.ClientCallback.lambda$3(ClientCallback.java:96) ~[?:?]
        at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_251]
        at org.eclipse.smarthome.io.transport.mqtt.internal.ClientCallback.messageArrived(ClientCallback.java:96) ~[?:?]
        at org.eclipse.smarthome.io.transport.mqtt.internal.ClientCallback.messageArrived(ClientCallback.java:71) ~[?:?]
        at com.hivemq.client.internal.mqtt.mqtt3.Mqtt3AsyncClientView.lambda$callbackView$1(Mqtt3AsyncClientView.java:73) ~[bundleFile:?]
        at com.hivemq.client.internal.mqtt.MqttAsyncClient$CallbackSubscriber.onNext(MqttAsyncClient.java:227) [bundleFile:?]
        at com.hivemq.client.internal.mqtt.MqttAsyncClient$CallbackSubscriber.onNext(MqttAsyncClient.java:212) [bundleFile:?]
        at com.hivemq.client.rx.FlowableWithSingle$SingleFutureSubscriber.onNext(FlowableWithSingle.java:377) [bundleFile:?]
        at com.hivemq.client.internal.rx.operators.FlowableWithSingleCombine$SplitSubscriber$Default.tryOnNextActual(FlowableWithSingleCombine.java:206) [bundleFile:?]
        at com.hivemq.client.internal.rx.operators.FlowableWithSingleCombine$SplitSubscriber.tryOnNext(FlowableWithSingleCombine.java:171) [bundleFile:?]
        at io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnConditionalSubscriber.runAsync(FlowableObserveOn.java:649) [bundleFile:?]
        at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176) [bundleFile:?]
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66) [bundleFile:?]
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57) [bundleFile:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_251]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_251]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_251]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_251]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_251]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]

**Comment by sindalschmidt** [comment]
I have been able to catch the following message before the mentioned exception. Is this helpful? If not, please let me know how I can provide more helpful information.

> 2020-07-30 15:16:16.440 [TRACE] [l.nhc2.NikoHomeControlCommunication2] - Niko Home Control: received topic hobby/control/devices/evt, payload {"Method":"devices.changed","Params":[{"Devices":[{"PropertyDefinitions":[{"OverruleActive":{"Description":"Boolean","HasStatus":"true","CanControl":"true"}},{"SetpointTemperature":{"Description":"Range(5.00,30.00,0.50)","HasStatus":"true","CanControl":"false"}},{"OverruleSetpoint":{"Description":"Range(5.00,30.00,0.50)","HasStatus":"true","CanControl":"true"}},{"OverruleTime":{"Description":"Range(1.00,1439.00,1.00)","HasStatus":"true","CanControl":"true"}},{"Program":{"Description":"Choice(Day,Night,Eco,Off,Cool,Prog1,Prog2,Prog3)","HasStatus":"true","CanControl":"true"}},{"EcoSave":{"Description":"Boolean","HasStatus":"true","CanControl":"true"}},{"Demand":{"Description":"Choice(Heating,Cooling,None)","HasStatus":"true","CanControl":"false"}},{"AmbientTemperature":{"Description":"Range(-5.00,45.00,0.50)","HasStatus":"true","CanControl":"false"}}],"Uuid":"2a6fc15b-9691-4cb8-b606-395c68cd094c"},{"PropertyDefinitions":[{"OverruleActive":{"Description":"Boolean","HasStatus":"true","CanControl":"true"}},{"SetpointTemperature":{"Description":"Range(5.00,30.00,0.50)","HasStatus":"true","CanControl":"false"}},{"OverruleSetpoint":{"Description":"Range(5.00,30.00,0.50)","HasStatus":"true","CanControl":"true"}},{"OverruleTime":{"Description":"Range(1.00,1439.00,1.00)","HasStatus":"true","CanControl":"true"}},{"Program":{"Description":"Choice(Day,Night,Eco,Off,Cool,Prog1,Prog2,Prog3)","HasStatus":"true","CanControl":"true"}},{"EcoSave":{"Description":"Boolean","HasStatus":"true","CanControl":"true"}},{"Demand":{"Description":"Choice(Heating,Cooling,None)","HasStatus":"true","CanControl":"false"}},{"AmbientTemperature":{"Description":"Range(-5.00,45.00,0.50)","HasStatus":"true","CanControl":"false"}}],"Uuid":"8f357a31-c840-4210-ae3e-cfac085f6f58"},{"PropertyDefinitions":[{"OverruleActive":{"Description":"Boolean","HasStatus":"true","CanControl":"true"}},{"SetpointTemperature":{"Description":"Range(5.00,30.00,0.50)","HasStatus":"true","CanControl":"false"}},{"OverruleSetpoint":{"Description":"Range(5.00,30.00,0.50)","HasStatus":"true","CanControl":"true"}},{"OverruleTime":{"Description":"Range(1.00,1439.00,1.00)","HasStatus":"true","CanControl":"true"}},{"Program":{"Description":"Choice(Day,Night,Eco,Off,Cool,Prog1,Prog2,Prog3)","HasStatus":"true","CanControl":"true"}},{"EcoSave":{"Description":"Boolean","HasStatus":"true","CanControl":"true"}},{"Demand":{"Description":"Choice(Heating,Cooling,None)","HasStatus":"true","CanControl":"false"}},{"AmbientTemperature":{"Description":"Range(-5.00,45.00,0.50)","HasStatus":"true","CanControl":"false"}}],"Uuid":"a294f613-176d-4753-bb8a-0d44247cf4c2"},{"PropertyDefinitions":[{"OverruleActive":{"Description":"Boolean","HasStatus":"true","CanControl":"true"}},{"SetpointTemperature":{"Description":"Range(5.00,30.00,0.50)","HasStatus":"true","CanControl":"false"}},{"OverruleSetpoint":{"Description":"Range(5.00,30.00,0.50)","HasStatus":"true","CanControl":"true"}},{"OverruleTime":{"Description":"Range(1.00,1439.00,1.00)","HasStatus":"true","CanControl":"true"}},{"Program":{"Description":"Choice(Day,Night,Eco,Off,Cool,Prog1,Prog2,Prog3)","HasStatus":"true","CanControl":"true"}},{"EcoSave":{"Description":"Boolean","HasStatus":"true","CanControl":"true"}},{"Demand":{"Description":"Choice(Heating,Cooling,None)","HasStatus":"true","CanControl":"false"}},{"AmbientTemperature":{"Description":"Range(-5.00,45.00,0.50)","HasStatus":"true","CanControl":"false"}}],"Uuid":"1d45d223-7afd-41eb-9c76-e94f35b54146"},{"PropertyDefinitions":[{"OverruleActive":{"Description":"Boolean","HasStatus":"true","CanControl":"true"}},{"SetpointTemperature":{"Description":"Range(5.00,30.00,0.50)","HasStatus":"true","CanControl":"false"}},{"OverruleSetpoint":{"Description":"Range(5.00,30.00,0.50)","HasStatus":"true","CanControl":"true"}},{"OverruleTime":{"Description":"Range(1.00,1439.00,1.00)","HasStatus":"true","CanControl":"true"}},{"Program":{"Description":"Choice(Day,Night,Eco,Off,Cool,Prog1,Prog2,Prog3)","HasStatus":"true","CanControl":"true"}},{"EcoSave":{"Description":"Boolean","HasStatus":"true","CanControl":"true"}},{"Demand":{"Description":"Choice(Heating,Cooling,None)","HasStatus":"true","CanControl":"false"}},{"AmbientTemperature":{"Description":"Range(-5.00,45.00,0.50)","HasStatus":"true","CanControl":"false"}}],"Uuid":"401a381c-3720-4b93-a7ec-515f4a667d0a"}]}]}
2020-07-30 15:16:16.441 [ERROR] [ansport.mqtt.internal.ClientCallback] - MQTT message received. MqttMessageSubscriber#processMessage() implementation failure
java.lang.NullPointerException: null
        at org.openhab.binding.nikohomecontrol.internal.protocol.nhc2.NikoHomeControlCommunication2.updateThermostatState(NikoHomeControlCommunication2.java:496) ~[?:?]
        at org.openhab.binding.nikohomecontrol.internal.protocol.nhc2.NikoHomeControlCommunication2.updateState(NikoHomeControlCommunication2.java:439) ~[?:?]
        at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_251]
        at org.openhab.binding.nikohomecontrol.internal.protocol.nhc2.NikoHomeControlCommunication2.devicesEvt(NikoHomeControlCommunication2.java:314) ~[?:?]
        at org.openhab.binding.nikohomecontrol.internal.protocol.nhc2.NikoHomeControlCommunication2.processMessage(NikoHomeControlCommunication2.java:778) ~[?:?]
        at org.eclipse.smarthome.io.transport.mqtt.internal.ClientCallback.lambda$3(ClientCallback.java:96) ~[?:?]
        at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_251]
        at org.eclipse.smarthome.io.transport.mqtt.internal.ClientCallback.messageArrived(ClientCallback.java:96) ~[?:?]
        at org.eclipse.smarthome.io.transport.mqtt.internal.ClientCallback.messageArrived(ClientCallback.java:71) ~[?:?]
        at com.hivemq.client.internal.mqtt.mqtt3.Mqtt3AsyncClientView.lambda$callbackView$1(Mqtt3AsyncClientView.java:73) ~[bundleFile:?]
        at com.hivemq.client.internal.mqtt.MqttAsyncClient$CallbackSubscriber.onNext(MqttAsyncClient.java:227) [bundleFile:?]
        at com.hivemq.client.internal.mqtt.MqttAsyncClient$CallbackSubscriber.onNext(MqttAsyncClient.java:212) [bundleFile:?]
        at com.hivemq.client.rx.FlowableWithSingle$SingleFutureSubscriber.onNext(FlowableWithSingle.java:377) [bundleFile:?]
        at com.hivemq.client.internal.rx.operators.FlowableWithSingleCombine$SplitSubscriber$Default.tryOnNextActual(FlowableWithSingleCombine.java:206) [bundleFile:?]
        at com.hivemq.client.internal.rx.operators.FlowableWithSingleCombine$SplitSubscriber.tryOnNext(FlowableWithSingleCombine.java:171) [bundleFile:?]
        at io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnConditionalSubscriber.runAsync(FlowableObserveOn.java:649) [bundleFile:?]
        at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176) [bundleFile:?]
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66) [bundleFile:?]
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57) [bundleFile:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_251]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_251]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_251]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_251]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_251]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]

**Comment by mherwege** [comment]
The issue seems to be no property state is provided in the above message, only property definitions. I had not seen that before. The PR catches these type of conditions, so no NPE should be thrown anymore.
However, I would still be curious to know if the Digital Black Thermostat actually works with the binding. Do you get any temperature updates visible in OH?

**Comment by sindalschmidt** [comment]
Unfortunately the issue has not been resolved. After adding a thermostat to a digital black and starting OpenHAB (2.5.8), the binding crashes. The binding stops working, after adding the thermostat.

> 2020-08-25 19:12:10.984 [DEBUG] [l.nhc2.NikoHomeControlCommunication2] - Niko Home Control: adding thermostat device ce875ad0-c72d-42b7-b734-b2cf263c6cd0, Gang Digital black
2020-08-25 19:12:10.987 [ERROR] [ansport.mqtt.internal.ClientCallback] - MQTT message received. MqttMessageSubscriber#processMessage() implementation failure
java.lang.NumberFormatException: empty String
        at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1842) ~[?:1.8.0_251]
        at sun.misc.FloatingDecimal.parseFloat(FloatingDecimal.java:122) ~[?:1.8.0_251]
        at java.lang.Float.parseFloat(Float.java:451) ~[?:1.8.0_251]
        at org.openhab.binding.nikohomecontrol.internal.protocol.nhc2.NikoHomeControlCommunication2.lambda$25(NikoHomeControlCommunication2.java:510) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_251]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_251]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_251]
        at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1359) ~[?:1.8.0_251]
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) ~[?:1.8.0_251]
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499) ~[?:1.8.0_251]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486) ~[?:1.8.0_251]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_251]
        at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152) ~[?:1.8.0_251]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_251]
        at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464) ~[?:1.8.0_251]
        at org.openhab.binding.nikohomecontrol.internal.protocol.nhc2.NikoHomeControlCommunication2.updateThermostatState(NikoHomeControlCommunication2.java:510) ~[?:?]
        at org.openhab.binding.nikohomecontrol.internal.protocol.nhc2.NikoHomeControlCommunication2.updateState(NikoHomeControlCommunication2.java:450) ~[?:?]
        at org.openhab.binding.nikohomecontrol.internal.protocol.nhc2.NikoHomeControlCommunication2.devicesListRsp(NikoHomeControlCommunication2.java:274) ~[?:?]
        at org.openhab.binding.nikohomecontrol.internal.protocol.nhc2.NikoHomeControlCommunication2.processMessage(NikoHomeControlCommunication2.java:794) ~[?:?]
        at org.eclipse.smarthome.io.transport.mqtt.internal.ClientCallback.lambda$3(ClientCallback.java:96) ~[?:?]
        at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_251]
        at org.eclipse.smarthome.io.transport.mqtt.internal.ClientCallback.messageArrived(ClientCallback.java:96) ~[?:?]
        at org.eclipse.smarthome.io.transport.mqtt.internal.ClientCallback.messageArrived(ClientCallback.java:71) ~[?:?]
        at com.hivemq.client.internal.mqtt.mqtt3.Mqtt3AsyncClientView.lambda$callbackView$1(Mqtt3AsyncClientView.java:73) ~[bundleFile:?]
        at com.hivemq.client.internal.mqtt.MqttAsyncClient$CallbackSubscriber.onNext(MqttAsyncClient.java:227) [bundleFile:?]
        at com.hivemq.client.internal.mqtt.MqttAsyncClient$CallbackSubscriber.onNext(MqttAsyncClient.java:212) [bundleFile:?]
        at com.hivemq.client.rx.FlowableWithSingle$SingleFutureSubscriber.onNext(FlowableWithSingle.java:377) [bundleFile:?]
        at com.hivemq.client.internal.rx.operators.FlowableWithSingleCombine$SplitSubscriber$Default.tryOnNextActual(FlowableWithSingleCombine.java:206) [bundleFile:?]
        at com.hivemq.client.internal.rx.operators.FlowableWithSingleCombine$SplitSubscriber.tryOnNext(FlowableWithSingleCombine.java:171) [bundleFile:?]
        at io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnConditionalSubscriber.runAsync(FlowableObserveOn.java:649) [bundleFile:?]
        at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176) [bundleFile:?]
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66) [bundleFile:?]
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57) [bundleFile:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_251]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_251]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_251]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_251]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_251]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]
