### ISSUE TITLE
zwave:2.0_snapshot cannot set properties of ge dimmer ex: nightlight

### ISSUE THREAD

**Issue by ifUpEth0** [openhab/openhab-addons#814]
When trying to set any property on my ge dimmer. I see a 404 error in the bottom right in paperUI and get the following output in debug. Also the setting does not take effect.

`19:49:36.664 [WARN ] [ding.zwave.handler.ZWaveThingHandler] - NODE22: Configuration invalid zwave_class_basic
19:49:36.665 [WARN ] [ding.zwave.handler.ZWaveThingHandler] - NODE22: Configuration invalid zwave_class_generic
19:49:36.669 [WARN ] [ding.zwave.handler.ZWaveThingHandler] - NODE22: Configuration invalid zwave_version`

**Comment by cdjackson** [comment]
Can you confirm if this problem exists with HABmin?

**Comment by ifUpEth0** [comment]
I do not have HABmin installed at the moment, but I will try and get to that tonight and see if I can still reproduce the issue. Are there any logs beyond the log for openhab that I should pull?

**Comment by ifUpEth0** [comment]
I found the log file from that night now. Sorry about the confusion. 

[openhab.txt](https://github.com/openhab/openhab2-addons/files/230852/openhab.txt)

**Comment by cdjackson** [comment]
Sorry - there’s still no debug entries. I’m not sure why - the command you specified for karat to enable logging looked ok, but there’s only INFO and ERRORs being logged…

**Comment by ifUpEth0** [comment]
Here is the debug log for trying to set the night light on the ge switch. This seems to be the relevant section line no 1592 - 1608

> 2016-04-21 18:59:25.103 [INFO ] [smarthome.event.ThingUpdatedEvent   ] - Thing 'zwave:device:5abab6a5:node22' has been updated.
2016-04-21 18:59:25.103 [WARN ] [.core.thing.binding.BaseThingHandler] - Error while applying configuration changes: 'IllegalStateException: Could not update configuration, because callback is missing' - reverting configuration changes on thing 'zwave:device:5abab6a5:node22'.
2016-04-21 18:59:25.103 [ERROR] [ome.core.thing.internal.ThingManager] - Exception occured during notification of thing 'zwave:device:5abab6a5:node22' about bridge initialization at 'null': Could not update configuration, because callback is missing
java.lang.IllegalStateException: Could not update configuration, because callback is missing
	at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.updateConfiguration(BaseThingHandler.java:398)[101:org.eclipse.smarthome.core.thing:0.8.0.201604180906]
	at org.eclipse.smarthome.core.thing.binding.ConfigStatusThingHandler.updateConfiguration(ConfigStatusThingHandler.java:64)[101:org.eclipse.smarthome.core.thing:0.8.0.201604180906]
	at org.openhab.binding.zwave.handler.ZWaveThingHandler.bridgeStatusChanged(ZWaveThingHandler.java:497)[159:org.openhab.binding.zwave:2.0.0.201604200106]
	at org.openhab.binding.zwave.handler.ZWaveThingHandler.bridgeHandlerInitialized(ZWaveThingHandler.java:382)[159:org.openhab.binding.zwave:2.0.0.201604200106]
	at org.eclipse.smarthome.core.thing.internal.ThingManager$8.run(ThingManager.java:709)[101:org.eclipse.smarthome.core.thing:0.8.0.201604180906]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_77]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_77]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)[:1.8.0_77]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)[:1.8.0_77]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_77]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_77]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_77]
2016-04-21 18:59:25.104 [DEBUG] [ding.zwave.handler.ZWaveThingHandler] - Handler disposed. Unregistering listener.

> 
[openhab.txt](https://github.com/openhab/openhab2-addons/files/230913/openhab.txt)

**Comment by cdjackson** [comment]
FTR: Going back to the original warning -:

> 19:49:36.664 [WARN ] [ding.zwave.handler.ZWaveThingHandler] - NODE22: Configuration invalid zwave_class_basic 19:49:36.665 [WARN ] [ding.zwave.handler.ZWaveThingHandler] - NODE22: Configuration invalid zwave_class_generic 19:49:36.669 [WARN ] [ding.zwave.handler.ZWaveThingHandler] - NODE22: Configuration invalid zwave_version

and your statement -:

> Also the setting does not take effect.

This warning will not stop the configuration - it is just a warning that the configuration is not in the expected format, and it continues to the next one. So, if you can't configure the device, then it's not related to this warning, but likely related to the second warning about the callback missing.

**Comment by ifUpEth0** [comment]
As an update. I pulled the latest snapshot yesterday afternoon US CST and this issue is resolved in it.

**Comment by cdjackson** [comment]
I think this is fixed with the updates to the bundle initialisation in ESH
