### ISSUE TITLE
[netatmo] Thing is displayed as online but the device is offline

### ISSUE THREAD

**Issue by Novanic** [openhab/openhab-addons#8162]
I have a Presence camera which is currently not power connected, but the thing is displayed as online.

I would expect that it is displayed as offline, when it isn't available.

Possible solution: The Netatmo /gethomedata endpoint returns the camera with "status" : "disconnected" instead of "on". I would expect that this information is used to determine the thing status.

**Comment by lolodomo** [comment]
For weather station, I believe there is the reachabke property that could be used too.

**Comment by lolodomo** [comment]
@Novanic : are you working on that ? If not, I can have a look myself. Just let me know.

**Comment by Novanic** [comment]
Hi, no I'm not currently working on it. You can start with it if you want.

**Comment by lolodomo** [comment]
I just discovered we have an exception when the camera is off:
```
16:56:58.219 [ERROR] [internal.items.ItemStateConverterImpl] - A conversion of null was requested:
java.lang.IllegalArgumentException: State must not be null.
        at org.eclipse.smarthome.core.internal.items.ItemStateConverterImpl.convertToAcceptedState(ItemStateConverterImpl.java:58) ~[?:?]
        at org.eclipse.smarthome.core.thing.internal.profiles.ProfileCallbackImpl.sendUpdate(ProfileCallbackImpl.java:134) ~[?:?]
        at org.eclipse.smarthome.core.thing.internal.profiles.SystemDefaultProfile.onStateUpdateFromHandler(SystemDefaultProfile.java:53) ~[?:?]
        at org.eclipse.smarthome.core.thing.internal.CommunicationManager.lambda$9(CommunicationManager.java:467) ~[?:?]
        at org.eclipse.smarthome.core.thing.internal.CommunicationManager.lambda$11(CommunicationManager.java:487) ~[?:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_152]
        at org.eclipse.smarthome.core.thing.internal.CommunicationManager.handleCallFromHandler(CommunicationManager.java:483) ~[?:?]
        at org.eclipse.smarthome.core.thing.internal.CommunicationManager.stateUpdated(CommunicationManager.java:465) ~[?:?]
        at org.eclipse.smarthome.core.thing.internal.ThingManagerImpl$1.stateUpdated(ThingManagerImpl.java:168) ~[?:?]
        at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.updateState(BaseThingHandler.java:245) ~[?:?]
        at org.openhab.binding.netatmo.internal.handler.AbstractNetatmoThingHandler.lambda$3(AbstractNetatmoThingHandler.java:156) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_152]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_152]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:1.8.0_152]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_152]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_152]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_152]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_152]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_152]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_152]
        at org.openhab.binding.netatmo.internal.handler.AbstractNetatmoThingHandler.updateDataChannels(AbstractNetatmoThingHandler.java:151) ~[?:?]
        at org.openhab.binding.netatmo.internal.handler.AbstractNetatmoThingHandler.updateChannels(AbstractNetatmoThingHandler.java:144) ~[?:?]
        at org.openhab.binding.netatmo.internal.handler.NetatmoModuleHandler.updateChannels(NetatmoModuleHandler.java:106) ~[?:?]
        at org.openhab.binding.netatmo.internal.handler.NetatmoDeviceHandler.lambda$9(NetatmoDeviceHandler.java:209) ~[?:?]
        at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_152]
        at org.openhab.binding.netatmo.internal.handler.NetatmoDeviceHandler.lambda$7(NetatmoDeviceHandler.java:207) ~[?:?]
        at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597) ~[?:1.8.0_152]
        at org.openhab.binding.netatmo.internal.handler.NetatmoDeviceHandler.updateChildModules(NetatmoDeviceHandler.java:206) ~[?:?]
        at org.openhab.binding.netatmo.internal.handler.NetatmoDeviceHandler.updateChannels(NetatmoDeviceHandler.java:164) ~[?:?]
        at org.openhab.binding.netatmo.internal.handler.NetatmoDeviceHandler.lambda$0(NetatmoDeviceHandler.java:83) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_152]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_152]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_152]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_152]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_152]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_152]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
```
When adding null annotations, I suppressed a test againt state being null, this was probably a bad idea but I don't understand how the state can be null. To be investigated and identify the channel for which we determine a null state.

I can confirm that the state of the camera switched to "disconnected" after few minutes.

**Comment by lolodomo** [comment]
`HttpUtil.downloadImage` is in fact returning null when the camera is off. I will fix that immediately.

**Comment by lolodomo** [comment]
OK, this is implemented.
Works well for the camera.
For the weather station, I commented the code for the device because it seems to take a lot of time until the station is seen as unreachable (I waited for 35 minutes with no change) and during this time, the data is requested every 30 seconds. I fear it could lead to a banishment.

**Comment by lolodomo** [comment]
In fact, this refresh interval switching to 30 seconds when the station is no more sending data is in fact not something new. If it was a problem, I suppose we will already know it. So I just have to be sure that the "reachable" property is going to false after a certain time.

**Comment by lolodomo** [comment]
The "reachable" property is OK for additional weather modules but not for the weather station itself (always true). I believe we should also consider the age of data: if too old, we consider the thing as OFFLINE.

**Comment by Novanic** [comment]
> The "reachable" property is OK for additional weather modules but not for the weather station itself (always true). I believe we should also consider the age of data: if too old, we consider the thing as OFFLINE.

Hm, how have you tested that? Have you removed the power consumtion of the weather station? Maybe it takes some time until Netatmo realizes that the weather station is offline.

**Comment by Novanic** [comment]
Should the thing status also affect the inbox? One of my Presence cameras is offline since months, but it appears within the inbox, that is confusing. ;-) Or does OpenHAB automatically hide offline things from the inbox?
