### ISSUE TITLE
[innogysmarthome] Insufficient reconnect attempts

### ISSUE THREAD

**Issue by Novanic** [openhab/openhab-addons#8182]
I noticed that the connection from OpenHAB to Innogy SmartHome was disconnected / not working anymore (couldn't switch my power sockets/outlets via OpenHAB), but the Innogy app is working normally. I noticed that at 23:15 o'clock. The OpenHAB log shows the last error message from 06:54 o'clock. That means there weren't any reconnect attempts since hours. That should get optimized...

OpenHAB 2.5.6 is used.

Log:
`2020-07-22 20:42:50.854 [INFO ] [gysmarthome.internal.InnogyWebSocket] - Connected to innogy Webservice.
2020-07-22 20:42:58.370 [INFO ] [control.internal.WebSocketConnection] - Web Socket close 1006. Reason: Disconnected
2020-07-23 00:16:22.561 [INFO ] [oauth2client.internal.OAuthConnector] - grant type refresh_token to URL https://auth.services-smarthome.de/AUTH/token success
2020-07-23 00:16:59.119 [INFO ] [gysmarthome.internal.InnogyWebSocket] - Connection to innogy Webservice was closed abnormally (code: 1006). Reason: Disconnected
2020-07-23 00:16:59.374 [INFO ] [gysmarthome.internal.InnogyWebSocket] - Connected to innogy Webservice.
2020-07-23 06:53:56.661 [INFO ] [gysmarthome.internal.InnogyWebSocket] - Connection to innogy Webservice was closed abnormally (code: 1006). Reason: Disconnected
2020-07-23 06:54:35.176 [WARN ] [internal.handler.InnogyBridgeHandler] - Error starting websocket.
java.util.concurrent.ExecutionException: java.net.ConnectException: Connection refused
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357) ~[?:1.8.0_152]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895) ~[?:1.8.0_152]
	at org.openhab.binding.innogysmarthome.internal.InnogyWebSocket.start(InnogyWebSocket.java:84) ~[?:?]
	at org.openhab.binding.innogysmarthome.internal.handler.InnogyBridgeHandler.startWebsocket(InnogyBridgeHandler.java:272) ~[?:?]
	at org.openhab.binding.innogysmarthome.internal.handler.InnogyBridgeHandler.startClient(InnogyBridgeHandler.java:247) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_152]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_152]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_152]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_152]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_152]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_152]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:1.8.0_152]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:1.8.0_152]
	at org.eclipse.jetty.io.SelectorManager.doFinishConnect(SelectorManager.java:355) ~[?:?]
	at org.eclipse.jetty.io.ManagedSelector.processConnect(ManagedSelector.java:223) ~[?:?]
	at org.eclipse.jetty.io.ManagedSelector.access$1500(ManagedSelector.java:61) ~[?:?]
	at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.processSelected(ManagedSelector.java:533) ~[?:?]
	at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.produce(ManagedSelector.java:395) ~[?:?]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produceTask(EatWhatYouKill.java:360) ~[?:?]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:184) ~[?:?]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171) ~[?:?]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:135) ~[?:?]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:782) ~[?:?]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:918) ~[?:?]
	... 1 more`

**Comment by Novanic** [comment]
@mmans @Hilbrand @ollie-dev 

Ok, I think I found the bug. Nothing is restarted when a crash occurs within org.openhab.binding.innogysmarthome.internal.handler.InnogyBridgeHandler#startClient.

The reason is, that the startClient method is only started by a scheduler (there are no other usages). A second call of "scheduleRestartClient" (which is triggered when an Exception within the startClient method occurs) has no effect, because the condition "!localReinitJob.isDone()" within the scheduleRestartClient method is everytime true... The scheduled task is never done within this method, because it was started by a scheduler itself...

**Comment by Hilbrand** [comment]
Reopened because fix doesn't seem to work: reverted in #8224

**Comment by Novanic** [comment]
I'm sorry for the high amount of pull-requests. It seems to be very difficult to fix the reconnect problems without side-effects (and the side-effects were visible after a few days).

These are the bugs which I needed to fix to solve the problems:

1. - Original problem) When an error occurs while starting (or re-starting) the websocket, no reconnect attempt was executed. So the binding / things / items got unusable. Solution: The scheduler is now also applied when a reconnect attempt fails (again).
2.) In combination with the fix of issue #8080 it could now happen that too many reconnect attempts were executed (about 1 per second). Solution 1: An explicit close of the websocket (by a reconnect attempt) is now recognized to avoids an additional reconnect attempt. Solution 2: There is now everytime a delay of 30 seconds between reconnect attemps in any case to avoid such critical side-effects by general (which could also slow down the whole system or cause blocked accounts).
3.) When an error occurred, the binding could get in a mode which executed every 60 seconds a restart of the websocket even when no error occurs. Solution: That should not be required, because this mode is also not activated before the first error occurs and the error handing triggers also a reconnect attempt. Solution: The fixed rate of the scheduler could get removed.
4.) An occurred Exception could cancel the scheduler, so no reconnect attempt is executed. The error handling starts a reconnect attemps (with a delay of 30 seconds), but the Exception is not re-thrown, therefore the code runs normally again after the error handling which cancels the scheduler...

**Comment by Novanic** [comment]
I think I have now finally a working version and added some automatic tests and it's still some time for testing since the release of OpenHAB 2.5.9... ;-)
