### ISSUE TITLE
[modbus] Error invalidating connection in pool for endpoint ModbusTCPSlaveEndpoint@...

### ISSUE THREAD

**Issue by skazi0** [openhab/openhab-addons#8187]
## Expected Behavior
Retry logic for modbus connection should work correctly :o)
Expected (old) log snippet:
```
2020-07-21 03:20:28.543 [WARN ] [rt.modbus.internal.ModbusManagerImpl] - Try 1 out of 3 failed when executing request (ModbusPollerThingHandlerImpl.ModbusPollerReadRequest@646ed239[slaveId=2,functionCode=READ_INPUT_REGISTERS,start=0,length=4,maxTries=3]). Will try again soon. Error was I/O error, so reseting the connection. Error details: net.wimpi.modbus.ModbusIOException I/O exception: SocketTimeoutException Read timed out [operation ID c7372f68-7141-4d17-821b-0c94c0474aaa]
2020-07-21 03:20:32.009 [ERROR] [wimpi.modbus.io.ModbusTCPTransaction] - execute try 1/1 error: I/O exception: SocketTimeoutException Read timed out. Request: net.wimpi.modbus.msg.ReadInputRegistersRequest@67183c3c (unit id 2 & transaction 17487). Address: /10.21.4.7:502
2020-07-21 03:20:32.107 [ERROR] [wimpi.modbus.io.ModbusTCPTransaction] - execute reached max tries 1, throwing last error: I/O exception: SocketTimeoutException Read timed out. Request: net.wimpi.modbus.msg.ReadInputRegistersRequest@67183c3c (unit id 2 & transaction 17487). Address: /10.21.4.7:502
2020-07-21 03:20:32.176 [WARN ] [rt.modbus.internal.ModbusManagerImpl] - Try 2 out of 3 failed when executing request (ModbusPollerThingHandlerImpl.ModbusPollerReadRequest@646ed239[slaveId=2,functionCode=READ_INPUT_REGISTERS,start=0,length=4,maxTries=3]). Will try again soon. Error was I/O error, so reseting the connection. Error details: net.wimpi.modbus.ModbusIOException I/O exception: SocketTimeoutException Read timed out [operation ID c7372f68-7141-4d17-821b-0c94c0474aaa]
```

## Current Behavior
One try and it stops polling completely:
Log:
```
2020-07-24 12:12:15.388 [WARN ] [rt.modbus.internal.ModbusManagerImpl] - Try 1 out of 3 failed when executing request (ModbusPollerThingHand
ler.ModbusPollerReadRequest@1cea4824[slaveId=2,functionCode=READ_INPUT_REGISTERS,start=0,length=4,maxTries=3]). Will try again soon. Error w
as I/O error, so reseting the connection. Error details: net.wimpi.modbus.ModbusIOException I/O exception: SocketTimeoutException Read timed
 out [operation ID 0d9d5df1-6b99-45be-98f7-34ce4967cacd]
2020-07-24 12:12:15.411 [WARN ] [rt.modbus.internal.ModbusManagerImpl] - Error invalidating connection in pool for endpoint ModbusTCPSlaveEndpoint@4b56be57[address=10.21.4.7,port=502]. Error was: java.lang.NullPointerException null
java.lang.NullPointerException: null
        at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936) ~[?:1.8.0_262]
        at org.openhab.io.transport.modbus.internal.pooling.ModbusSlaveConnectionFactoryImpl$PooledConnection.maybeResetConnection(ModbusSlaveConnectionFactoryImpl.java:87) ~[?:?]
        at org.openhab.io.transport.modbus.internal.pooling.ModbusSlaveConnectionFactoryImpl.passivateObject(ModbusSlaveConnectionFactoryImpl.java:223) ~[?:?]
        at org.openhab.io.transport.modbus.internal.pooling.ModbusSlaveConnectionFactoryImpl.passivateObject(ModbusSlaveConnectionFactoryImpl.java:1) ~[?:?]
        at org.apache.commons.pool2.impl.GenericKeyedObjectPool.addIdleObject(GenericKeyedObjectPool.java:1272) ~[?:?]
        at org.apache.commons.pool2.impl.GenericKeyedObjectPool.addObject(GenericKeyedObjectPool.java:1255) ~[?:?]
        at org.apache.commons.pool2.impl.GenericKeyedObjectPool.invalidateObject(GenericKeyedObjectPool.java:589) ~[?:?]
        at org.openhab.io.transport.modbus.internal.ModbusManagerImpl.lambda$1(ModbusManagerImpl.java:407) ~[?:?]
        at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_262]
        at org.openhab.io.transport.modbus.internal.ModbusManagerImpl.invalidate(ModbusManagerImpl.java:405) ~[?:?]
        at org.openhab.io.transport.modbus.internal.ModbusManagerImpl.lambda$9(ModbusManagerImpl.java:642) ~[?:?]
        at org.openhab.io.transport.modbus.internal.SimpleStopWatch.timeConsumer(SimpleStopWatch.java:169) ~[?:?]
        at org.openhab.io.transport.modbus.internal.ModbusManagerImpl.executeOperation(ModbusManagerImpl.java:642) ~[?:?]
        at org.openhab.io.transport.modbus.internal.ModbusManagerImpl.access$2(ModbusManagerImpl.java:525) ~[?:?]
        at org.openhab.io.transport.modbus.internal.ModbusManagerImpl$ModbusCommunicationInterfaceImpl.lambda$1(ModbusManagerImpl.java:782) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_262]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_262]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_262]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_262]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_262]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_262]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
```

## Steps to Reproduce (for Bugs)
Simulate connectivity problems by disconnecting the device or something similar.

## Context
I experience this problem with a DIY modbus device (connected via mgate) which times out sometimes.
Retry logic worked until I upgraded to 2.5.7. Downgrade to 2.5.6 made it work again.

## Your Environment
* Version used: 2.5.7
* Zulu Java 1.8
openjdk version "1.8.0_262"
OpenJDK Runtime Environment (Zulu 8.48.0.51-CA-linux64) (build 1.8.0_262-b19)
OpenJDK 64-Bit Server VM (Zulu 8.48.0.51-CA-linux64) (build 25.262-b19, mixed mode)
* Debian GNU/Linux 10 (buster)

**Comment by sjek13** [comment]
same problem here, only modbus stopped polling arround 00:03 last night by itself, i was not updating openhab or anything.
I am running openhab 2.5.6

I restored a backup from yesterday and cleared temp and cache folder, then it is working for a few minutes and then it stops again.

**Comment by kjoglum** [comment]
Same problem here as well: Polling stops by itself, things appear to remain online. Manage to restart and get the polling to work for a couple of minutes before it stops again.

**Comment by tomcio1205** [comment]
Also have this problem. Version 2.5.6. Maybe someone found temporary solution?

**Comment by kjoglum** [comment]
See also #8205 and #8206

**Comment by massimilianocasini** [comment]
Same problem with 2.5.8.202007261630      │ openHAB Add-ons :: Bundles :: IO :: Modbus Transport

**Comment by jonwhitear** [comment]
I have the same problem. I'm on 2.5.7.

Log:

`2020-08-12 22:12:30.171 [WARN ] [rt.modbus.internal.ModbusManagerImpl] - Try 1 out of 3 failed when executing request (ModbusReadRequestBlueprint@3237ca7d[slaveId=1,functionCode=READ_MULTIPLE_REGISTERS,start=40188,length=107,maxTries=3]). Will try again soon. Error was I/O error, so reseting the connection. Error details: net.wimpi.modbus.ModbusIOException I/O exception: SocketException Connection reset [operation ID eec7b363-23ee-4283-8eee-9084fc9cf3c3]
2020-08-12 22:12:30.178 [WARN ] [rt.modbus.internal.ModbusManagerImpl] - Error invalidating connection in pool for endpoint ModbusTCPSlaveEndpoint@5a35daf0[address=inverter.whitear.org,port=1502]. Error was: java.lang.NullPointerException null
java.lang.NullPointerException: null
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936) ~[?:1.8.0_232]
	at org.openhab.io.transport.modbus.internal.pooling.ModbusSlaveConnectionFactoryImpl$PooledConnection.maybeResetConnection(ModbusSlaveConnectionFactoryImpl.java:87) ~[?:?]
	at org.openhab.io.transport.modbus.internal.pooling.ModbusSlaveConnectionFactoryImpl.passivateObject(ModbusSlaveConnectionFactoryImpl.java:223) ~[?:?]
	at org.openhab.io.transport.modbus.internal.pooling.ModbusSlaveConnectionFactoryImpl.passivateObject(ModbusSlaveConnectionFactoryImpl.java:1) ~[?:?]
	at org.apache.commons.pool2.impl.GenericKeyedObjectPool.addIdleObject(GenericKeyedObjectPool.java:1272) ~[?:?]
	at org.apache.commons.pool2.impl.GenericKeyedObjectPool.addObject(GenericKeyedObjectPool.java:1255) ~[?:?]
	at org.apache.commons.pool2.impl.GenericKeyedObjectPool.invalidateObject(GenericKeyedObjectPool.java:589) ~[?:?]
	at org.openhab.io.transport.modbus.internal.ModbusManagerImpl.lambda$1(ModbusManagerImpl.java:407) ~[?:?]
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_232]
	at org.openhab.io.transport.modbus.internal.ModbusManagerImpl.invalidate(ModbusManagerImpl.java:405) ~[?:?]
	at org.openhab.io.transport.modbus.internal.ModbusManagerImpl.lambda$9(ModbusManagerImpl.java:642) ~[?:?]
	at org.openhab.io.transport.modbus.internal.SimpleStopWatch.timeConsumer(SimpleStopWatch.java:169) ~[?:?]
	at org.openhab.io.transport.modbus.internal.ModbusManagerImpl.executeOperation(ModbusManagerImpl.java:642) ~[?:?]
	at org.openhab.io.transport.modbus.internal.ModbusManagerImpl.access$2(ModbusManagerImpl.java:525) ~[?:?]
	at org.openhab.io.transport.modbus.internal.ModbusManagerImpl$ModbusCommunicationInterfaceImpl.lambda$1(ModbusManagerImpl.java:782) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_232]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_232]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_232]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_232]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_232]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_232]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]`

**Comment by ssalonen** [comment]
Hi all,


This should be fixed in the 2.5.8-SNAPSHOT version of the transport . This slipped in 2.5.7 version 

Please follow update instructions from this post https://community.openhab.org/t/binding-modbus-2-5-7-stops-working-after-unsuccessful-read-attempt/102809/16?u=ssalonen and report back.

Please pay attention to instructions, many people on forum thought that they updated correctly but might end up having two versions of binding installed and old one still actually being used.

**Comment by ssalonen** [comment]
@sjek13 binding version 2.5.6 is not affected by this issue. However, we have users who have reported that openHAB 2.5.6 auto-updates bindings to 2.5.7 (!). When this happens, you might experience the issue even with older openHAB.

Please check version of bindings and report back. In karaf console 

bundle:list -s|grep modbus

**Comment by ssalonen** [comment]
Openhab 2.5.8 stable is now released with the fixes.
