### ISSUE TITLE
[innogy smarthome] power measure of medion pss

### ISSUE THREAD

**Issue by acidburn78** [openhab/openhab-addons#8196]
I would like to get the power measurement data of the medion powerplugs

**Comment by acidburn78** [comment]
Log:
`2020-08-26 10:56:08.166 [ERROR] [core.thing.internal.ThingManagerImpl] - Exception occurred while initializing handler of thing 'innogysmarthome:BT-PSS:ad7d5608:769ced2cfc7c4c1592bbe7d10ff043ec': null
java.lang.NullPointerException: null
	at org.openhab.binding.innogysmarthome.internal.client.entity.capability.CapabilityState.getEnergyConsumptionSensorEnergyConsumptionMonthKWhState(CapabilityState.java:219) ~[?:?]
	at org.openhab.binding.innogysmarthome.internal.handler.InnogyDeviceHandler.onDeviceStateChanged(InnogyDeviceHandler.java:604) ~[?:?]
	at org.openhab.binding.innogysmarthome.internal.handler.InnogyDeviceHandler.initializeProperties(InnogyDeviceHandler.java:300) ~[?:?]
	at org.openhab.binding.innogysmarthome.internal.handler.InnogyDeviceHandler.initializeThing(InnogyDeviceHandler.java:225) ~[?:?]
	at org.openhab.binding.innogysmarthome.internal.handler.InnogyDeviceHandler.initialize(InnogyDeviceHandler.java:195) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor79.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
	at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:152) [bundleFile:?]
	at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:52) [bundleFile:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]`

**Comment by hmerk** [comment]
Closed as there will be no more fixes/enhancements for openHAB 2. If still valid for openHAB 3, please open a new issue with actuals logs.
