### ISSUE TITLE
[shelly] NPE when thing is not reachable

### ISSUE THREAD

**Issue by markus7017** [openhab/openhab-addons#8197]
Sometimes the following NPE is shown in the log if a thing is not reachable
```
2020-07-23 21:53:38.917 [WARN ] org.eclipse.smarthome.core.internal.common.WrappedScheduledExecutorService:67    | Scheduled runnable ended with an exception: java.lang.IllegalStateException: Stopwatch is not running. 
	at org.apache.commons.lang.time.StopWatch.stop(StopWatch.java:142)
	at org.openhab.binding.shelly.internal.handler.ShellyBaseHandler.setThingOffline(ShellyBaseHandler.java:461)
	at org.openhab.binding.shelly.internal.handler.ShellyBaseHandler.initializeThing(ShellyBaseHandler.java:242)
	at org.openhab.binding.shelly.internal.handler.ShellyBaseHandler.lambda$0(ShellyBaseHandler.java:161)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
```

**Comment by markus7017** [comment]
fixed, will be included in the next release
