### ISSUE TITLE
[digitalstrom] NPE due to race condition

### ISSUE THREAD

**Issue by alexf2015** [openhab/openhab-addons#8214]
Randomly there is a NPE thrown:

```
java.lang.NullPointerException: null
        at org.openhab.binding.digitalstrom.internal.lib.sensorjobexecutor.AbstractSensorJobExecutor$ExecutorRunnable.run(AbstractSensorJobExecutor.java:77) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_211]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[?:1.8.0_211]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_211]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[?:1.8.0_211]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_211]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_211]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
```

I think this is due to unsafe access to "pollingSchedulers" by at least 2 threads at the same time.
The Runnable should at least create a local copy and do a null check on this. Maybe a lock in addition would be even better.

**Comment by alexf2015** [comment]
```
2020-07-30 15:49:40.563 [ERROR] [verconnection.impl.HttpTransportImpl] - SSLHandshakeException: Remote host closed connection during handshake
2020-07-30 15:49:40.651 [DEBUG] [al.lib.manager.impl.SceneManagerImpl] - start SceneManager
2020-07-30 15:49:40.653 [DEBUG] [al.lib.manager.impl.SceneManagerImpl] - EventListener is set, add this SceneManager as EventHandler
2020-07-30 15:49:40.656 [DEBUG] [rom.internal.lib.event.EventListener] - Start EventListener
2020-07-30 15:49:40.659 [DEBUG] [al.lib.manager.impl.SceneManagerImpl] - start SceneManager
2020-07-30 15:49:40.698 [DEBUG] [al.lib.manager.impl.SceneManagerImpl] - stop SceneManager
2020-07-30 15:49:40.708 [DEBUG] [rom.internal.lib.event.EventListener] - internal stop EventListener
2020-07-30 15:49:40.710 [DEBUG] [rom.internal.lib.event.EventListener] - Min one subscribed events was deleted, EventListener will be restarted
2020-07-30 15:49:40.725 [DEBUG] [rom.internal.lib.event.EventListener] - internal start EventListener
2020-07-30 15:49:40.732 [DEBUG] [rom.internal.lib.event.EventListener] - internal stop EventListener
2020-07-30 15:49:40.735 [DEBUG] [rom.internal.lib.event.EventListener] - Min one subscribed events was deleted, EventListener will be restarted
2020-07-30 15:49:40.749 [DEBUG] [rom.internal.lib.event.EventListener] - internal start EventListener
2020-07-30 15:49:40.752 [DEBUG] [rom.internal.lib.event.EventListener] - Stop EventListener
2020-07-30 15:49:40.760 [DEBUG] [rom.internal.lib.event.EventListener] - internal stop EventListener
2020-07-30 15:49:55.933 [DEBUG] [al.lib.manager.impl.SceneManagerImpl] - start SceneManager
2020-07-30 15:49:55.936 [DEBUG] [al.lib.manager.impl.SceneManagerImpl] - EventListener is set, add this SceneManager as EventHandler
2020-07-30 15:49:56.013 [DEBUG] [rom.internal.lib.event.EventListener] - subscribed event: callScene to subscriptionID: 15
2020-07-30 15:49:56.085 [DEBUG] [rom.internal.lib.event.EventListener] - subscribed event: undoScene to subscriptionID: 15
2020-07-30 15:49:56.089 [DEBUG] [rom.internal.lib.event.EventListener] - eventHandler: SceneManagerImpl-[callScene, undoScene] added
2020-07-30 15:49:56.092 [DEBUG] [rom.internal.lib.event.EventListener] - Start EventListener
2020-07-30 15:49:56.095 [DEBUG] [rom.internal.lib.event.EventListener] - internal start EventListener
2020-07-30 15:49:56.109 [DEBUG] [al.lib.manager.impl.SceneManagerImpl] - start SceneManager
2020-07-30 15:49:56.113 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception:
java.lang.NullPointerException: null
        at org.openhab.binding.digitalstrom.internal.lib.sensorjobexecutor.AbstractSensorJobExecutor$ExecutorRunnable.run(AbstractSensorJobExecutor.java:77) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_211]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[?:1.8.0_211]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_211]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[?:1.8.0_211]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_211]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_211]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
2020-07-30 15:49:56.197 [DEBUG] [rom.internal.lib.event.EventListener] - subscribed event: deviceSensorValue to subscriptionID: 15
2020-07-30 15:49:56.274 [DEBUG] [rom.internal.lib.event.EventListener] - subscribed event: deviceBinaryInputEvent to subscriptionID: 15
2020-07-30 15:49:56.277 [DEBUG] [rom.internal.lib.event.EventListener] - eventHandler: org.openhab.binding.digitalstrom.internal.lib.manager.impl.DeviceStatusManagerImpl added
2020-07-30 15:49:56.280 [DEBUG] [rom.internal.lib.event.EventListener] - Start EventListener
```

I set logging to be more verbose. It is obvious that there is a weird behaviour. 
1. new instances of SceneManager and EventListener seem to be started before old instances are stopped. In addition it seems that there are more instances started than there are stopped.

**Comment by alexf2015** [comment]
At least I could identify and fix the NPE:
In "AbstractSensorJobExecutor" there was a unsafe access to member variable "pollingSchedulers"
