### ISSUE TITLE
[lametrictime] Exception in log when device cannot be reached

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-addons#8276]
In openHAB 3, the lametrictime binding logs a long exception in the log in case the device cannot be reached through HTTP:

```
2020-08-10 22:13:09.905 [WARN ] [ache.cxf.phase.PhaseInterceptorChain] - Interceptor for {https://192.168.0.144:4343/api/v2}WebClient has thrown exception, unwinding now
org.apache.cxf.interceptor.Fault: Could not receive Message.
	at org.apache.cxf.interceptor.MessageSenderInterceptor$MessageSenderEndingInterceptor.handleMessage(MessageSenderInterceptor.java:65) ~[bundleFile:1.0.8]
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308) [bundleFile:1.0.8]
	at org.apache.cxf.jaxrs.client.AbstractClient.doRunInterceptorChain(AbstractClient.java:702) [bundleFile:1.0.8]
	at org.apache.cxf.jaxrs.client.WebClient.doChainedInvocation(WebClient.java:1081) [bundleFile:1.0.8]
	at org.apache.cxf.jaxrs.client.WebClient.doInvoke(WebClient.java:927) [bundleFile:1.0.8]
	at org.apache.cxf.jaxrs.client.WebClient.doInvoke(WebClient.java:896) [bundleFile:1.0.8]
	at org.apache.cxf.jaxrs.client.WebClient.invoke(WebClient.java:461) [bundleFile:1.0.8]
	at org.apache.cxf.jaxrs.client.SyncInvokerImpl.method(SyncInvokerImpl.java:135) [bundleFile:1.0.8]
	at org.apache.cxf.jaxrs.client.SyncInvokerImpl.get(SyncInvokerImpl.java:55) [bundleFile:1.0.8]
	at org.apache.cxf.jaxrs.client.spec.InvocationBuilderImpl.get(InvocationBuilderImpl.java:93) [bundleFile:1.0.8]
	at org.openhab.binding.lametrictime.api.local.impl.LaMetricTimeLocalImpl.getApi(LaMetricTimeLocalImpl.java:94) [bundleFile:?]
	at org.openhab.binding.lametrictime.api.local.impl.LaMetricTimeLocalImpl.getDevice(LaMetricTimeLocalImpl.java:110) [bundleFile:?]
	at org.openhab.binding.lametrictime.internal.handler.LaMetricTimeHandler.lambda$0(LaMetricTimeHandler.java:111) [bundleFile:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.net.SocketTimeoutException: SocketTimeoutException invoking https://192.168.0.144:4343/api/v2: connect timed out
	at jdk.internal.reflect.GeneratedConstructorAccessor335.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.mapException(HTTPConduit.java:1402) ~[bundleFile:1.0.8]
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.close(HTTPConduit.java:1386) ~[bundleFile:1.0.8]
	at org.apache.cxf.io.AbstractWrappedOutputStream.close(AbstractWrappedOutputStream.java:77) ~[bundleFile:1.0.8]
	at org.apache.cxf.transport.AbstractConduit.close(AbstractConduit.java:56) ~[bundleFile:1.0.8]
	at org.apache.cxf.transport.http.HTTPConduit.close(HTTPConduit.java:673) ~[bundleFile:1.0.8]
	at org.apache.cxf.interceptor.MessageSenderInterceptor$MessageSenderEndingInterceptor.handleMessage(MessageSenderInterceptor.java:63) ~[bundleFile:1.0.8]
	... 18 more 
```

This is due to using CXF as JAX-RS implementation and can only be fixed once the binding source code is moved to the master branch.

**Comment by lsiepel** [comment]
Old issue, wonder if it is still relevant.

**Comment by kaikreuzer** [comment]
Just tested it and I cannot reproduce it anymore - so let's close it!
