### ISSUE TITLE
[modbus] NullPointerException on serial port IO error

### ISSUE THREAD

**Issue by Wolfgang1966** [openhab/openhab-addons#8298]
Since a few days I use the modbus binding with an USB to serial converter to read out data from a SDM630 smartmeter. After some time (a few minutes to hours) I see the following exception in openhab.log:

`2020-08-14 17:23:49.144 [WARN ] [rt.modbus.internal.ModbusManagerImpl] - Try 1 out of 3 failed when executing request (ModbusPollerThingHandler.ModbusPollerReadRequest@1ea0e95[slaveId=1
,functionCode=READ_INPUT_REGISTERS,start=358,length=6,maxTries=3]). Will try again soon. Error was I/O error, so reseting the connection. Error details: net.wimpi.modbus.ModbusIOExcepti
on I/O exception: IOException Error reading response (EOF) [operation ID 0c67c478-754b-4442-8d6c-5ac04b3aa806]
2020-08-14 17:23:49.284 [WARN ] [rt.modbus.internal.ModbusManagerImpl] - Error invalidating connection in pool for endpoint ModbusSerialSlaveEndpoint@1d9bd72[portName=/dev/ttyUSB0]. Err
or was: java.lang.NullPointerException null
java.lang.NullPointerException: null
        at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936) ~[?:1.8.0_252]
        at java.util.concurrent.ConcurrentHashMap.getOrDefault(ConcurrentHashMap.java:1588) ~[?:1.8.0_252]
        at org.openhab.io.transport.modbus.internal.pooling.ModbusSlaveConnectionFactoryImpl$PooledConnection.maybeResetConnection(ModbusSlaveConnectionFactoryImpl.java:90) ~[?:?]
        at org.openhab.io.transport.modbus.internal.pooling.ModbusSlaveConnectionFactoryImpl.passivateObject(ModbusSlaveConnectionFactoryImpl.java:223) ~[?:?]
        at org.openhab.io.transport.modbus.internal.pooling.ModbusSlaveConnectionFactoryImpl.passivateObject(ModbusSlaveConnectionFactoryImpl.java:1) ~[?:?]
        at org.apache.commons.pool2.impl.GenericKeyedObjectPool.addIdleObject(GenericKeyedObjectPool.java:1272) ~[?:?]
        at org.apache.commons.pool2.impl.GenericKeyedObjectPool.addObject(GenericKeyedObjectPool.java:1255) ~[?:?]
        at org.apache.commons.pool2.impl.GenericKeyedObjectPool.invalidateObject(GenericKeyedObjectPool.java:589) ~[?:?]
        at org.openhab.io.transport.modbus.internal.ModbusManagerImpl.lambda$1(ModbusManagerImpl.java:407) ~[?:?]
        at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_252]
        at org.openhab.io.transport.modbus.internal.ModbusManagerImpl.invalidate(ModbusManagerImpl.java:405) ~[?:?]
        at org.openhab.io.transport.modbus.internal.ModbusManagerImpl.lambda$9(ModbusManagerImpl.java:642) ~[?:?]
        at org.openhab.io.transport.modbus.internal.SimpleStopWatch.timeConsumer(SimpleStopWatch.java:169) ~[?:?]
        at org.openhab.io.transport.modbus.internal.ModbusManagerImpl.executeOperation(ModbusManagerImpl.java:642) ~[?:?]
        at org.openhab.io.transport.modbus.internal.ModbusManagerImpl.access$2(ModbusManagerImpl.java:525) ~[?:?]
        at org.openhab.io.transport.modbus.internal.ModbusManagerImpl$ModbusCommunicationInterfaceImpl.lambda$1(ModbusManagerImpl.java:782) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_252]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_252]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_252]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_252]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
`
## Expected Behavior

Reconnect without exception 😄 

## Current Behavior

No reconnect

## Possible Solution

I already fixed it, PR follows in a couple of minutes

## Steps to Reproduce (for Bugs)

Don't know how to forcefully produce an I/O error. In my case: Just sit and wait for some time

## Your Environment

* Openhab 2.5.7
* Modbus binding
* SDM630 smart meter
* USB to serial bridge with FTDI Chip FT232R
* Odroid HC1 with Ubuntu 
* zulu8.46.0.225-ca-jdk8.0.252-linux_aarch32hf

**Comment by ssalonen** [comment]
Fixed already in https://github.com/openhab/openhab-addons/pull/8206?

**Comment by ssalonen** [comment]
@Wolfgang1966 should this be closed?

**Comment by Wolfgang1966** [comment]
Closed, duplicate.
