### ISSUE TITLE
ZWaveClockCommandClassTest test failed

### ISSUE THREAD

**Issue by tavalin** [openhab/openhab-addons#832]
```
Error Message

expected:<true> but was:<false>

Stacktrace

java.lang.AssertionError: expected:<true> but was:<false>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:144)
    at org.openhab.binding.zwave.test.internal.protocol.commandclass.ZWaveClockCommandClassTest.reportTimeOffset(ZWaveClockCommandClassTest.java:46)

```

This broke the Jenkins check on https://github.com/openhab/openhab2-addons/pull/831

**Comment by cdjackson** [comment]
Dates and times in tests - what a pain in the backside!

I'll look at this shortly...

**Comment by tavalin** [comment]
Sorry @cdjackson! My PR was completely unrelated too :cry:

**Comment by cdjackson** [comment]
I know - I’m not completely sure why this failed now but was ok earlier. The test is comparing times and days, so I suspect a timezone issue which I had to solve on another test earlier. I runs fine here, but seemingly not in cloudbee-land (where-ever that is)  :) ....

**Comment by cdjackson** [comment]
Looks like it's back to normal - I'm not 100% sure it won't come back at a different time of day though!
