### ISSUE TITLE
[upnpcontrol] Playlists stop occasionally

### ISSUE THREAD

**Issue by 5iver** [openhab/openhab-addons#8321]
When playing a playlist after browsing or searching, occasionally the playlist will stop playing. It is possible that this occurs with albums too. Using the latest code as of now from https://github.com/mherwege/openhab-addons/tree/upnp...
```
2020-08-20 16:26:15.013 [INFO ] [org.jupnp.transport.impl.async.AsyncServlet] - HttpServlet.service(): id: 1903, request URI: /upnpcallback/dev/5f9ec1b3-ed59-1900-4530-30f9ed4f6395/svc/upnp-org/AVTransport/event/cb
2020-08-20 16:26:15.015 [DEBUG] [org.openhab.binding.upnpcontrol.internal.handler.UpnpRendererHandler] - Upnp device Portable received variable LastChange with value <Event xmlns="urn:schemas-upnp-org:metadata-1-0/AVT/">
  <InstanceID val="0">
    <TransportState val="PLAYING"/>
    <CurrentTrackDuration val="0:02:30"/>
    <CurrentMediaDuration val="0:02:30"/>
    <CurrentTransportActions val="Pause,Stop,Next,Previous,Seek,X_DLNA_SeekTime"/>
  </InstanceID>
</Event> from service AVTransport
2020-08-20 16:26:15.017 [DEBUG] [org.openhab.binding.upnpcontrol.internal.handler.UpnpRendererHandler] - Upnp device Portable received variable CurrentTransportActions with value Pause,Stop,Next,Previous,Seek,X_DLNA_SeekTime from service AVTransport
2020-08-20 16:26:15.017 [DEBUG] [org.openhab.binding.upnpcontrol.internal.handler.UpnpRendererHandler] - Upnp device Portable received variable InstanceID with value 0 from service AVTransport
2020-08-20 16:26:15.018 [DEBUG] [org.openhab.binding.upnpcontrol.internal.handler.UpnpRendererHandler] - Upnp device Portable received variable CurrentMediaDuration with value 0:02:30 from service AVTransport
2020-08-20 16:26:15.018 [DEBUG] [org.openhab.binding.upnpcontrol.internal.handler.UpnpRendererHandler] - Upnp device Portable received variable CurrentTrackDuration with value 0:02:30 from service AVTransport
2020-08-20 16:26:15.018 [DEBUG] [org.openhab.binding.upnpcontrol.internal.handler.UpnpRendererHandler] - Upnp device Portable received variable TransportState with value PLAYING from service AVTransport
2020-08-20 16:26:15.018 [DEBUG] [org.openhab.binding.upnpcontrol.internal.handler.UpnpRendererHandler] - Update server TwonkyMedia [NAS01] channel upnpcontrol:upnprenderer:5f9ec1b3-ed59-1900-4530-30f9ed4f6395:control state from renderer Portable
2020-08-20 16:28:45.615 [INFO ] [org.jupnp.transport.impl.async.AsyncServlet] - HttpServlet.service(): id: 1904, request URI: /upnpcallback/dev/5f9ec1b3-ed59-1900-4530-30f9ed4f6395/svc/upnp-org/AVTransport/event/cb
2020-08-20 16:28:45.617 [DEBUG] [org.openhab.binding.upnpcontrol.internal.handler.UpnpRendererHandler] - Upnp device Portable received variable LastChange with value <Event xmlns="urn:schemas-upnp-org:metadata-1-0/AVT/">
  <InstanceID val="0">
    <TransportState val="STOPPED"/>
    <CurrentTransportActions val="Play"/>
  </InstanceID>
</Event> from service AVTransport
2020-08-20 16:28:45.618 [DEBUG] [org.openhab.binding.upnpcontrol.internal.handler.UpnpRendererHandler] - Upnp device Portable received variable CurrentTransportActions with value Play from service AVTransport
2020-08-20 16:28:45.618 [DEBUG] [org.openhab.binding.upnpcontrol.internal.handler.UpnpRendererHandler] - Upnp device Portable received variable InstanceID with value 0 from service AVTransport
2020-08-20 16:28:45.618 [DEBUG] [org.openhab.binding.upnpcontrol.internal.handler.UpnpRendererHandler] - Upnp device Portable received variable TransportState with value STOPPED from service AVTransport
2020-08-20 16:28:45.619 [DEBUG] [org.openhab.binding.upnpcontrol.internal.handler.UpnpRendererHandler] - Update server TwonkyMedia [NAS01] channel upnpcontrol:upnprenderer:5f9ec1b3-ed59-1900-4530-30f9ed4f6395:control state from renderer Portable
2020-08-20 16:28:45.619 [DEBUG] [org.openhab.binding.upnpcontrol.internal.handler.UpnpRendererHandler] - Serve next media 'Dam That River' from queue on renderer Portable
2020-08-20 16:28:46.446 [DEBUG] [org.openhab.binding.upnpcontrol.internal.handler.UpnpHandler] - Upnp device Portable invoke upnp action SetAVTransportURI on service AVTransport with inputs {InstanceID=0, CurrentURI=http://10.5.5.10:9000/disk/DLNA-PNWMABASE-OP01-FLAGS01700000/O0$1$8I8677388.wma, CurrentURIMetaData=<DIDL-Lite xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/" xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/"><item id="0$1$9$154574P1R8677388" parentID="0$1$9$154574" restricted="true"><dc:title>Dam That River</dc:title><upnp:class>object.item.audioItem.musicTrack</upnp:class><upnp:album>Dirt</upnp:album><upnp:albumArtURI>http://10.5.5.10:9000/disk/DLNA-PNJPEG_TN-OP01-CI1-FLAGS00d00000/defaa/A/O0$1$8I8677388.jpg?scale=org</upnp:albumArtURI><dc:creator>Alice in Chains</dc:creator><upnp:artist>Alice in Chains</upnp:artist><dc:publisher></dc:publisher><upnp:genre>Alternative</upnp:genre><upnp:originalTrackNumber>1</upnp:originalTrackNumber></item></DIDL-Lite>}
2020-08-20 16:28:46.446 [DEBUG] [org.openhab.binding.upnpcontrol.internal.handler.UpnpHandler] - Upnp device Portable invoke upnp action SetAVTransportURI on service AVTransport reply {}
2020-08-20 16:28:46.652 [INFO ] [org.jupnp.transport.impl.async.AsyncServlet] - HttpServlet.service(): id: 1905, request URI: /upnpcallback/dev/5f9ec1b3-ed59-1900-4530-30f9ed4f6395/svc/upnp-org/AVTransport/event/cb
2020-08-20 16:28:46.989 [INFO ] [org.jupnp.transport.impl.async.AsyncServlet] - HttpServlet.service(): id: 1906, request URI: /upnpcallback/dev/5f9ec1b3-ed59-1900-4530-30f9ed4f6395/svc/upnp-org/AVTransport/event/cb
2020-08-20 16:28:48.163 [DEBUG] [org.openhab.binding.upnpcontrol.internal.handler.UpnpRendererHandler] - Cannot play, media URI not yet set in the renderer
2020-08-20 16:28:48.163 [DEBUG] [org.openhab.binding.upnpcontrol.internal.handler.UpnpRendererHandler] - Error: {}
java.util.concurrent.TimeoutException: null
        at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1784) ~[?:1.8.0_242]
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1928) ~[?:1.8.0_242]
        at org.openhab.binding.upnpcontrol.internal.handler.UpnpRendererHandler.play(UpnpRendererHandler.java:335) [bundleFile:?]
        at org.openhab.binding.upnpcontrol.internal.handler.UpnpRendererHandler.serve(UpnpRendererHandler.java:1101) [bundleFile:?]
        at org.openhab.binding.upnpcontrol.internal.handler.UpnpRendererHandler.serveNext(UpnpRendererHandler.java:1044) [bundleFile:?]
        at org.openhab.binding.upnpcontrol.internal.handler.UpnpRendererHandler.onValueReceivedTransportState(UpnpRendererHandler.java:876) [bundleFile:?]
        at org.openhab.binding.upnpcontrol.internal.handler.UpnpRendererHandler.onValueReceived(UpnpRendererHandler.java:769) [bundleFile:?]
        at org.openhab.binding.upnpcontrol.internal.handler.UpnpRendererHandler.onValueReceivedLastChange(UpnpRendererHandler.java:852) [bundleFile:?]
        at org.openhab.binding.upnpcontrol.internal.handler.UpnpRendererHandler.onValueReceived(UpnpRendererHandler.java:765) [bundleFile:?]
        at org.eclipse.smarthome.io.transport.upnp.internal.UpnpIOServiceImpl$UpnpSubscriptionCallback.eventReceived(UpnpIOServiceImpl.java:161) [bundleFile:?]
        at org.jupnp.controlpoint.SubscriptionCallback$2.eventReceived(SubscriptionCallback.java:222) [bundleFile:?]
        at org.jupnp.model.gena.RemoteGENASubscription.receive(RemoteGENASubscription.java:114) [bundleFile:?]
        at org.jupnp.protocol.sync.ReceivingEvent$2.run(ReceivingEvent.java:130) [bundleFile:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
2020-08-20 16:28:48.230 [DEBUG] [org.openhab.binding.upnpcontrol.internal.handler.UpnpHandler] - Upnp device Portable invoke upnp action SetNextAVTransportURI on service AVTransport with inputs {InstanceID=0, NextURI=http://10.5.5.10:9000/disk/DLNA-PNWMABASE-OP01-FLAGS01700000/O0$1$8I8677900.wma, NextURIMetaData=<DIDL-Lite xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/" xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/"><item id="0$1$9$154574P2R8677900" parentID="0$1$9$154574" restricted="true"><dc:title>Rain When I Die</dc:title><upnp:class>object.item.audioItem.musicTrack</upnp:class><upnp:album>Dirt</upnp:album><upnp:albumArtURI>http://10.5.5.10:9000/disk/DLNA-PNJPEG_TN-OP01-CI1-FLAGS00d00000/defaa/A/O0$1$8I8677900.jpg?scale=org</upnp:albumArtURI><dc:creator>Alice in Chains</dc:creator><upnp:artist>Alice in Chains</upnp:artist><dc:publisher></dc:publisher><upnp:genre>Alternative</upnp:genre><upnp:originalTrackNumber>2</upnp:originalTrackNumber></item></DIDL-Lite>}
2020-08-20 16:28:48.230 [DEBUG] [org.openhab.binding.upnpcontrol.internal.handler.UpnpHandler] - Upnp device Portable invoke upnp action SetNextAVTransportURI on service AVTransport reply {}
2020-08-20 16:28:48.314 [INFO ] [org.jupnp.transport.impl.async.AsyncServlet] - HttpServlet.service(): id: 1907, request URI: /upnpcallback/dev/5f9ec1b3-ed59-1900-4530-30f9ed4f6395/svc/upnp-org/AVTransport/event/cb
2020-08-20 16:28:48.319 [DEBUG] [org.openhab.binding.upnpcontrol.internal.handler.UpnpRendererHandler] - Upnp device Portable received variable LastChange with value <Event xmlns="urn:schemas-upnp-org:metadata-1-0/AVT/">
  <InstanceID val="0">
    <NextAVTransportURI val="http://10.5.5.10:9000/disk/DLNA-PNWMABASE-OP01-FLAGS01700000/O0$1$8I8677900.wma"/>
    <NextAVTransportURIMetaData val="&lt;DIDL-Lite xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; xmlns:upnp=&quot;urn:schemas-upnp-org:metadata-1-0/upnp/&quot; xmlns=&quot;urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/&quot;&gt;&lt;item id=&quot;0$1$9$154574P2R8677900&quot; parentID=&quot;0$1$9$154574&quot; restricted=&quot;true&quot;&gt;&lt;dc:title&gt;Rain When I Die&lt;/dc:title&gt;&lt;upnp:class&gt;object.item.audioItem.musicTrack&lt;/upnp:class&gt;&lt;upnp:album&gt;Dirt&lt;/upnp:album&gt;&lt;upnp:albumArtURI&gt;http://10.5.5.10:9000/disk/DLNA-PNJPEG_TN-OP01-CI1-FLAGS00d00000/defaa/A/O0$1$8I8677900.jpg?scale=org&lt;/upnp:albumArtURI&gt;&lt;dc:creator&gt;Alice in Chains&lt;/dc:creator&gt;&lt;upnp:artist&gt;Alice in Chains&lt;/upnp:artist&gt;&lt;dc:publisher&gt;&lt;/dc:publisher&gt;&lt;upnp:genre&gt;Alternative&lt;/upnp:genre&gt;&lt;upnp:originalTrackNumber&gt;2&lt;/upnp:originalTrackNumber&gt;&lt;/item&gt;&lt;/DIDL-Lite&gt;"/>
  </InstanceID>
</Event> from service AVTransport
2020-08-20 16:28:48.320 [DEBUG] [org.openhab.binding.upnpcontrol.internal.handler.UpnpRendererHandler] - Upnp device Portable received variable NextAVTransportURIMetaData with value <DIDL-Lite xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/" xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/"><item id="0$1$9$154574P2R8677900" parentID="0$1$9$154574" restricted="true"><dc:title>Rain When I Die</dc:title><upnp:class>object.item.audioItem.musicTrack</upnp:class><upnp:album>Dirt</upnp:album><upnp:albumArtURI>http://10.5.5.10:9000/disk/DLNA-PNJPEG_TN-OP01-CI1-FLAGS00d00000/defaa/A/O0$1$8I8677900.jpg?scale=org</upnp:albumArtURI><dc:creator>Alice in Chains</dc:creator><upnp:artist>Alice in Chains</upnp:artist><dc:publisher></dc:publisher><upnp:genre>Alternative</upnp:genre><upnp:originalTrackNumber>2</upnp:originalTrackNumber></item></DIDL-Lite> from service AVTransport
2020-08-20 16:28:48.320 [DEBUG] [org.openhab.binding.upnpcontrol.internal.handler.UpnpRendererHandler] - Upnp device Portable received variable InstanceID with value 0 from service AVTransport
2020-08-20 16:28:48.320 [DEBUG] [org.openhab.binding.upnpcontrol.internal.handler.UpnpRendererHandler] - Upnp device Portable received variable NextAVTransportURI with value http://10.5.5.10:9000/disk/DLNA-PNWMABASE-OP01-FLAGS01700000/O0$1$8I8677900.wma from service AVTransport
```

**Comment by mherwege** [comment]
@openhab-5iver 
These lines are interesting:

> 2020-08-20 16:28:46.652 [INFO ] [org.jupnp.transport.impl.async.AsyncServlet] - HttpServlet.service(): id: 1905, request URI: /upnpcallback/dev/5f9ec1b3-ed59-1900-4530-30f9ed4f6395/svc/upnp-org/AVTransport/event/cb
2020-08-20 16:28:46.989 [INFO ] [org.jupnp.transport.impl.async.AsyncServlet] - HttpServlet.service(): id: 1906, request URI: /upnpcallback/dev/5f9ec1b3-ed59-1900-4530-30f9ed4f6395/svc/upnp-org/AVTransport/event/cb

It looks like the underlying call is made twice and these calls block eachother. I only call invokeAction once, so I am wondering where the second line comes from.
Could you go back further in the log? I would like to see the log when setting the URI of the previous entry before the timeout. I am wondering if something already gets stuck there.

**Comment by mherwege** [comment]
@openhab-5iver Both of these should be solved in my current branch.
For the timeouts, the reason was I had some long running processes triggered from the information returned by the GENA subscriptions, so running in the same process as the GENA event callback. This blocked receiving further GENA events, hence waiting for these events would time out. This looks like an issue in the jupnp library to me, but I could easily work around it by running the next actions on a GENA event in a separate task.

**Comment by openhab-5iver** [comment]
This is resolved in the latest code that is yet to be submitted.
