### ISSUE TITLE
[Binding Modbus]  Pool not open

### ISSUE THREAD

**Issue by massimilianocasini** [openhab/openhab-addons#8343]
## Expected Behavior
No Exception:

2020-08-25 14:47:19.166 [WARN ] [rt.modbus.internal.ModbusManagerImpl] - Connection pool swallowed unexpected exception:IllegalStateException Pool not open
java.lang.IllegalStateException: Pool not open
        at org.apache.commons.pool2.impl.BaseGenericObjectPool.assertOpen(BaseGenericObjectPool.java:704) [bundleFile:2.4.3]
        at org.apache.commons.pool2.impl.GenericKeyedObjectPool.evict(GenericKeyedObjectPool.java:867) ~[bundleFile:2.4.3]
        at org.apache.commons.pool2.impl.BaseGenericObjectPool$Evictor.run(BaseGenericObjectPool.java:1068) [bundleFile:2.4.3]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]

## Current Behavior
Binding seems working fine

## Steps to Reproduce (for Bugs)
1. Normal polling

## Your Environment

* Version used: openHAB 2.5.8-1 (Release Build)
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...):
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): openhabian

**Comment by massimilianocasini** [comment]
After openhabian-cli clean-cache the problem has been solved.
