### ISSUE TITLE
[mqtt.homeassistant] Error when trying to delete a Home Assistant Thing

### ISSUE THREAD

**Issue by bodiroga** [openhab/openhab-addons#8397]
After https://github.com/openhab/openhab-addons/pull/8317 was merged, I've seen this error message when trying to delete a Home Assistant Thing:

```
22:04:21.311 [ndlerExecutor-1] INFO  smarthome.event.ThingStatusInfoEvent:53 - 'mqtt:homeassistant_zigbee2mqtt_5F0x14b457fffe7eeb7b:15616d5a:zigbee2mqtt_5F0x14b457fffe7eeb7b' updated: REMOVING
22:04:21.312 [ndlerExecutor-1] INFO  s.event.ThingStatusInfoChangedEvent:53 - 'mqtt:homeassistant_zigbee2mqtt_5F0x14b457fffe7eeb7b:15616d5a:zigbee2mqtt_5F0x14b457fffe7eeb7b' changed from ONLINE to REMOVING
22:04:21.371 [-thingManager-1] ERROR o.e.s.c.t.internal.ThingManagerImpl:958 - The ThingHandler caused an exception while handling the removal of its thing
java.lang.IllegalArgumentException: Illegal status transition from REMOVING to ONLINE, only REMOVED would have been allowed.
	at org.eclipse.smarthome.core.thing.internal.ThingManagerImpl$1.statusUpdated(ThingManagerImpl.java:190)
	at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.updateStatus(BaseThingHandler.java:357)
	at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.updateStatus(BaseThingHandler.java:372)
	at org.openhab.binding.mqtt.homeassistant.internal.handler.HomeAssistantThingHandler.updateThingStatus(HomeAssistantThingHandler.java:301)
	at org.openhab.binding.mqtt.generic.AbstractMQTTThingHandler.calculateThingStatus(AbstractMQTTThingHandler.java:366)
	at org.openhab.binding.mqtt.generic.AbstractMQTTThingHandler.resetMessageReceived(AbstractMQTTThingHandler.java:353)
	at org.openhab.binding.mqtt.generic.AbstractMQTTThingHandler.stop(AbstractMQTTThingHandler.java:117)
	at org.openhab.binding.mqtt.homeassistant.internal.handler.HomeAssistantThingHandler.stop(HomeAssistantThingHandler.java:220)
	at org.openhab.binding.mqtt.generic.AbstractMQTTThingHandler.handleRemoval(AbstractMQTTThingHandler.java:246)
	at org.eclipse.smarthome.core.thing.internal.ThingManagerImpl$7.run(ThingManagerImpl.java:951)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

I will provide a PR soon :wink:

**Comment by lsiepel** [comment]
The related PR was closed. Was the issue fixed or is it still active?
