### ISSUE TITLE
[verisure] NPE when Eventlog query gives unexpected result

### ISSUE THREAD

**Issue by jannegpriv** [openhab/openhab-addons#8495]
NPE when Eventlog query gives unexpected result:

````
2020-09-10 07:05:41.553 [TRACE] [ng.verisure.internal.VerisureSession] - Response body: {"errors":[{"message":"socket hang up","locations":[{"line":3,"column":2}],"path":["installation","eventLog"],"data"
:{"logTraceId":"45e9b8fd-b80b-4d35-adef-b60b0790c1f2"}}],"data":{"installation":{"eventLog":null,"__typename":"Installation"}}}
````

````
java.lang.NullPointerException: null
        at org.openhab.binding.verisure.internal.handler.VerisureEventLogThingHandler.triggerEventChannels(VerisureEventLogThingHandler.java:196) ~[?:?]
        at org.openhab.binding.verisure.internal.handler.VerisureEventLogThingHandler.getValue(VerisureEventLogThingHandler.java:168) ~[?:?]
        at org.openhab.binding.verisure.internal.handler.VerisureEventLogThingHandler.lambda$2(VerisureEventLogThingHandler.java:75) ~[?:?]
````

**Comment by J-N-K** [comment]
There is no l. 196 `VerisureEventLogThingHandler.java`. What version did you use?

**Comment by jannegpriv** [comment]
Sorry, this should be closed, I fixed it in:
https://github.com/openhab/openhab-addons/pull/8507
