### ISSUE TITLE
[shelly][oh3] Log filled with jmdns warnings after restart of OH

### ISSUE THREAD

**Issue by MHerbst** [openhab/openhab-addons#8531]
After OH has been restarted a lot of messages like this one appear in openhab.log:

```
22:41:43.109 [8-2-187.local.)] WARN  javax.jmdns.impl.DNSIncoming:266 - DNSIncoming() dump dns[response,192.168.2.73:5353, length=882, id=0x0, flags=0x8400:r:aa, answers=5
answers:
	[Pointer@-1318115680 type: TYPE_PTR index 12, class: CLASS_IN index 1, name: _services._dns-sd._udp.local. ttl: '119/120' alias: '_http._tcp.']
	[Pointer@-1127321630 type: TYPE_PTR index 12, class: CLASS_IN index 1, name: _http._tcp.local. ttl: '119/120' alias: 'shellyplug-s-376D1F._http._tcp.local.']
	[Service@1050894886 type: TYPE_SRV index 33, class: CLASS_IN index 1-unique, name: shellyplug-s-376D1F._http._tcp.local. ttl: '120/120' server: 'shellyplug-s-376D1F.local.:80']
	[Text@-572833272 type: TYPE_TXT index 16, class: CLASS_IN index 1-unique, name: shellyplug-s-376D1F._http._tcp.local. ttl: '120/120' text: 'id=shellyplug-s-...']
	[IPv4Address@859634236 type: TYPE_A index 1, class: CLASS_IN index 1-unique, name: shellyplug-s-376D1F.local. ttl: '120/120' address: '192.168.2.73']]
	answer:        [Pointer@-1318115680 type: TYPE_PTR index 12, class: CLASS_IN index 1, name: _services._dns-sd._udp.local. ttl: '119/120' alias: '_http._tcp.']
	answer:        [Pointer@-1127321630 type: TYPE_PTR index 12, class: CLASS_IN index 1, name: _http._tcp.local. ttl: '119/120' alias: 'shellyplug-s-376D1F._http._tcp.local.']
	answer:        [Service@1050894886 type: TYPE_SRV index 33, class: CLASS_IN index 1-unique, name: shellyplug-s-376D1F._http._tcp.local. ttl: '120/120' server: 'shellyplug-s-376D1F.local.:80']
	answer:        [Text@-572833272 type: TYPE_TXT index 16, class: CLASS_IN index 1-unique, name: shellyplug-s-376D1F._http._tcp.local. ttl: '120/120' text: 'id=shellyplug-s-...']
	answer:        [IPv4Address@859634236 type: TYPE_A index 1, class: CLASS_IN index 1-unique, name: shellyplug-s-376D1F.local. ttl: '120/120' address: '192.168.2.73']
   0: 0000840000000006 00000000095f7365 727669636573075f 646e732d7364045f     ........ ....._se rvices._ dns-sd._
  20: 756470056c6f6361 6c00000c00010000 0078000c055f6874 7470045f74637000     udp.loca l....... .x..._ht tp._tcp.
  40: 055f68747470045f 746370056c6f6361 6c00000c00010000 0078002613736865     ._http._ tcp.loca l....... .x.&.she
  60: 6c6c79706c75672d 732d333736443146 055f68747470045f 746370056c6f6361     llyplug- s-376D1F ._http._ tcp.loca
  80: 6c00137368656c6c 79706c75672d732d 333736443146055f 68747470045f7463     l..shell yplug-s- 376D1F._ http._tc
  a0: 70056c6f63616c00 0021800100000078 0021000000000050 137368656c6c7970     p.local. .!.....x .!.....P .shellyp
  c0: 6c75672d732d3337 36443146056c6f63 616c00137368656c 6c79706c75672d73     lug-s-37 6D1F.loc al..shel lyplug-s
  e0: 2d33373644314605 5f68747470045f74 6370056c6f63616c 0000108001000000     -376D1F. _http._t cp.local ........
 100: 78004a1669643d73 68656c6c79706c75 672d732d33373644 31462566775f6964     x.J.id=s hellyplu g-s-376D 1F%fw_id
 120: 3d32303230303832 372d303730333036 2f76312e382e3340 3461386263343237     =2020082 7-070306 /v1.8.3@ 4a8bc427
 140: 0c617263683d6573 7038323636137368 656c6c79706c7567 2d732d3337364431     .arch=es p8266.sh ellyplug -s-376D1
 160: 46056c6f63616c00 0001800100000078 0004c0a802491373 68656c6c79706c75     F.local. .......x .....I.s hellyplu
 180: 672d732d33373644 3146056c6f63616c 00002f8001000000 78001e137368656c     g-s-376D 1F.local ../..... x...shel
 1a0: 6c79706c75672d73 2d33373644314605 6c6f63616c000001 4000008400000000     lyplug-s -376D1F. local... @.......
 1c0: 0600000000095f73 6572766963657307 5f646e732d736404 5f756470056c6f63     ......_s ervices. _dns-sd. _udp.loc
 1e0: 616c00000c000100 000078000c055f68 747470045f746370 00055f6874747004     al...... ..x..._h ttp._tcp .._http.
 200: 5f746370056c6f63 616c00000c000100 0000780026137368 656c6c79706c7567     _tcp.loc al...... ..x.&.sh ellyplug
 220: 2d732d3337364431 46055f6874747004 5f746370056c6f63 616c00137368656c     -s-376D1 F._http. _tcp.loc al..shel
 240: 6c79706c75672d73 2d33373644314605 5f68747470045f74 6370056c6f63616c     lyplug-s -376D1F. _http._t cp.local
 260: 0000218001000000 7800210000000000 50137368656c6c79 706c75672d732d33     ..!..... x.!..... P.shelly plug-s-3
 280: 3736443146056c6f 63616c0013736865 6c6c79706c75672d 732d333736443146     76D1F.lo cal..she llyplug- s-376D1F
 2a0: 055f68747470045f 746370056c6f6361 6c00001080010000 0078004a1669643d     ._http._ tcp.loca l....... .x.J.id=
 2c0: 7368656c6c79706c 75672d732d333736 4431462566775f69 643d323032303038     shellypl ug-s-376 D1F%fw_i d=202008
 2e0: 32372d3037303330 362f76312e382e33 4034613862633432 370c617263683d65     27-07030 6/v1.8.3 @4a8bc42 7.arch=e
 300: 7370383236361373 68656c6c79706c75 672d732d33373644 3146056c6f63616c     sp8266.s hellyplu g-s-376D 1F.local
 320: 0000018001000000 780004c0a8024913 7368656c6c79706c 75672d732d333736     ........ x.....I. shellypl ug-s-376
 340: 443146056c6f6361 6c00002f80010000 0078001e13736865 6c6c79706c75672d     D1F.loca l../.... .x...she llyplug-
 360: 732d333736443146 056c6f63616c0000 0140                                  s-376D1F .local.. .@

 exception 
java.io.IOException: Received a message with the wrong length.
	at javax.jmdns.impl.DNSIncoming.<init>(DNSIncoming.java:263)
	at javax.jmdns.impl.SocketListener.run(SocketListener.java:50)
```

As far as I can see these messages are issued for every Shelly device. The messages appear only once (per device) and it seems that the devices are working correctly.

There is another messages that also only accurs at startup:

```
22:41:50.593 [ool-14-thread-1] WARN  o.o.c.c.d.DiscoveryResultBuilder:155 - Representation property 'shellyplug-s-b86ee4' of discovery result for thing 'shelly:shellyplugs:b86ee4' is missing in properties map. It has to be fixed by the bindings developer.
	at java.base/java.lang.Thread.getStackTrace(Thread.java:1174)
	at org.openhab.core.config.discovery.DiscoveryResultBuilder$1.run(DiscoveryResultBuilder.java:181)
	at org.openhab.core.config.discovery.DiscoveryResultBuilder$1.run(DiscoveryResultBuilder.java:1)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:678)
	at org.openhab.core.config.discovery.DiscoveryResultBuilder.getStackTrace(DiscoveryResultBuilder.java:178)
	at org.openhab.core.config.discovery.DiscoveryResultBuilder.build(DiscoveryResultBuilder.java:157)
	at org.openhab.binding.shelly.internal.discovery.ShellyDiscoveryParticipant.createResult(ShellyDiscoveryParticipant.java:189)
	at org.openhab.core.config.discovery.mdns.internal.MDNSDiscoveryService.considerService(MDNSDiscoveryService.java:214)
	at org.openhab.core.config.discovery.mdns.internal.MDNSDiscoveryService.serviceResolved(MDNSDiscoveryService.java:206)
	at javax.jmdns.impl.ListenerStatus$ServiceListenerStatus.serviceResolved(ListenerStatus.java:106)
	at javax.jmdns.impl.JmDNSImpl$1.run(JmDNSImpl.java:894)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:836)
```

**Comment by markus7017** [comment]
This is a known issue related to Shelly's mDNS implementation of jmdns. I raised it already at Alterco, but without any result

the 2nd issue has already been fixed, PR #8642 will solve this issue
