### ISSUE TITLE
[SamsungTV] The binding is broken in master/OH3 (fails to register a TV because getMacAddress fails with NPE)

### ISSUE THREAD

**Issue by ivmarkov** [openhab/openhab-addons#8619]
(Sorry for skipping the nice bug reporting template, but I think I nailed the root cause, so I don't have the nerves after a couple of hours of code inspection to follow it.)

* `org.openhab.binding.samsungtv.internal.handler.SamsungTvHandler.thingDiscovered` fails with NPE
* The NPE comes from calling `org.openhab.binding.samsungtv.internal.WakeOnLanUtility.getMACAddress(WakeOnLanUtility.java:78)`
* The above call, in turn tries to figure out the MAC address of the TV by invoking `arp` (or `arping` in my case) by utilizing ExecUtil from openhab core. 
* ExecUtils is currently broken however. See https://github.com/openhab/openhab-core/issues/1677. It fails to execute the command line and returns null
* Since the code does not expect a null response, it happily passes it to the regexp matcher which is trying to extract the mac address

A simple workaround until ExecUtil is fixed is to call it with the "@@" magic, which I think will still work.
A better fix is to fix/enhance ExecUtil to mimic the ProcessBuilder API (i.e. an array of command + arguments) rather than passing a single line and then relying on parsing tricks.

Not to mention that ExecUtil silently returning null on process execution failure is not so ideal. An exception should probably be raised instead.

**Comment by ivmarkov** [comment]
Forgot to add some evidence of the problem:
```
20:55:14.311 [DEBUG] [org.openhab.core.io.net.exec.ExecUtil] - couldn't execute commandLine 'arping -r -c 1 -C 1 192.168.10.61'
java.io.IOException: Cannot run program "arping -r -c 1 -C 1 192.168.10.61": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1128) ~[?:?]
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1071) ~[?:?]
	at org.openhab.core.io.net.exec.ExecUtil.internalExecute(ExecUtil.java:105) [bundleFile:?]
	at org.openhab.core.io.net.exec.ExecUtil.executeCommandLineAndWaitResponse(ExecUtil.java:72) [bundleFile:?]
	at org.openhab.binding.samsungtv.internal.WakeOnLanUtility.getMACAddress(WakeOnLanUtility.java:77) [bundleFile:?]
	at org.openhab.binding.samsungtv.internal.handler.SamsungTvHandler.thingDiscovered(SamsungTvHandler.java:341) [bundleFile:?]
	at org.openhab.core.config.discovery.internal.DiscoveryServiceRegistryImpl.lambda$1(DiscoveryServiceRegistryImpl.java:184) [bundleFile:?]
	at java.lang.Iterable.forEach(Iterable.java:75) [?:?]
	at org.openhab.core.config.discovery.internal.DiscoveryServiceRegistryImpl.lambda$0(DiscoveryServiceRegistryImpl.java:184) [bundleFile:?]
	at java.util.HashMap.forEach(HashMap.java:1336) [?:?]
	at org.openhab.core.config.discovery.internal.DiscoveryServiceRegistryImpl.addDiscoveryListener(DiscoveryServiceRegistryImpl.java:183) [bundleFile:?]
	at org.openhab.binding.samsungtv.internal.handler.SamsungTvHandler.initialize(SamsungTvHandler.java:158) [bundleFile:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.openhab.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:152) [bundleFile:?]
	at org.openhab.core.internal.common.Invocation.call(Invocation.java:52) [bundleFile:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.ProcessImpl.forkAndExec(Native Method) ~[?:?]
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:340) ~[?:?]
	at java.lang.ProcessImpl.start(ProcessImpl.java:271) ~[?:?]
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1107) ~[?:?]
	... 21 more
20:55:14.313 [ERROR] [rnal.common.AbstractInvocationHandler] - An error occurred while calling method 'ThingHandler.initialize()' on 'org.openhab.binding.samsungtv.internal.handler.SamsungTvHandler@3f4ccdd8': null
java.lang.NullPointerException: null
	at java.util.regex.Matcher.getTextLength(Matcher.java:1770) ~[?:?]
	at java.util.regex.Matcher.reset(Matcher.java:416) ~[?:?]
	at java.util.regex.Matcher.<init>(Matcher.java:253) ~[?:?]
	at java.util.regex.Pattern.matcher(Pattern.java:1133) ~[?:?]
	at org.openhab.binding.samsungtv.internal.WakeOnLanUtility.getMACAddress(WakeOnLanUtility.java:78) ~[?:?]
	at org.openhab.binding.samsungtv.internal.handler.SamsungTvHandler.thingDiscovered(SamsungTvHandler.java:341) ~[?:?]
	at org.openhab.core.config.discovery.internal.DiscoveryServiceRegistryImpl.lambda$1(DiscoveryServiceRegistryImpl.java:184) ~[?:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at org.openhab.core.config.discovery.internal.DiscoveryServiceRegistryImpl.lambda$0(DiscoveryServiceRegistryImpl.java:184) ~[?:?]
	at java.util.HashMap.forEach(HashMap.java:1336) ~[?:?]
	at org.openhab.core.config.discovery.internal.DiscoveryServiceRegistryImpl.addDiscoveryListener(DiscoveryServiceRegistryImpl.java:183) ~[?:?]
	at org.openhab.binding.samsungtv.internal.handler.SamsungTvHandler.initialize(SamsungTvHandler.java:158) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.openhab.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:152) [bundleFile:?]
	at org.openhab.core.internal.common.Invocation.call(Invocation.java:52) [bundleFile:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by lolodomo** [comment]
At my knowledge, the same code is used in several bindings. So several bindings could be impacted,
