### ISSUE TITLE
Zwave clock config NumberFormatException 

### ISSUE THREAD

**Issue by jongj** [openhab/openhab-addons#874]
With online build 277, tried to updated the automatic update offset to 300 with habmin (latest snapshot) but got this exception.

```
2016-05-02 20:01:48.795 [ERROR] [ve.internal.protocol.ZWaveController] - Exception during ZWave thread: Input 2. {}
java.lang.NumberFormatException: For input string: "300.0"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)[:1.8.0_92]
        at java.lang.Integer.parseInt(Integer.java:580)[:1.8.0_92]
        at java.lang.Integer.parseInt(Integer.java:615)[:1.8.0_92]
        at org.openhab.binding.zwave.internal.converter.ZWaveClockConverter.handleEvent(ZWaveClockConverter.java:74)[192:org.openhab.binding.zwave:2.0.0.201605020102]
        at org.openhab.binding.zwave.handler.ZWaveThingHandler.ZWaveIncomingEvent(ZWaveThingHandler.java:1140)[192:org.openhab.binding.zwave:2.0.0.201605020102]
        at org.openhab.binding.zwave.internal.protocol.ZWaveController.notifyEventListeners(ZWaveController.java:547)[192:org.openhab.binding.zwave:2.0.0.201605020102]
        at org.openhab.binding.zwave.internal.protocol.commandclass.ZWaveClockCommandClass.handleApplicationCommandRequest(ZWaveClockCommandClass.java:146)[192:org.openhab.binding.zwave:2.0.0.201605020102]
        at org.openhab.binding.zwave.internal.protocol.serialmessage.ApplicationCommandMessageClass.handleRequest(ApplicationCommandMessageClass.java:119)[192:org.openhab.binding.zwave:2.0.0.201605020102]
        at org.openhab.binding.zwave.internal.protocol.ZWaveController.handleIncomingRequestMessage(ZWaveController.java:247)[192:org.openhab.binding.zwave:2.0.0.201605020102]
        at org.openhab.binding.zwave.internal.protocol.ZWaveController.handleIncomingMessage(ZWaveController.java:213)[192:org.openhab.binding.zwave:2.0.0.201605020102]
        at org.openhab.binding.zwave.internal.protocol.ZWaveController.access$6(ZWaveController.java:207)[192:org.openhab.binding.zwave:2.0.0.201605020102]
        at org.openhab.binding.zwave.internal.protocol.ZWaveController$ZWaveInputThread.run(ZWaveController.java:1091)[192:org.openhab.binding.zwave:2.0.0.201605020102]
```

**Comment by jongj** [comment]
Resoled in last nights build.
