### ISSUE TITLE
Ring Door Bell Binding openHAB 3.0.0

### ISSUE THREAD

**Issue by Daniel100111** [openhab/openhab-addons#8782]
Ring door bell binding not working. OpenHAB 3.0.0
[Ring] -->Ring door bell binding not working.

at org.eclipse.osgi.container.Module.start(Module.java:444) ~[org.eclipse.osgi-3.12.100.jar:?]
    at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:383) ~[org.eclipse.osgi-3.12.100.jar:?]
    at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1260) [bundleFile:3.6.4]
    at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1233) [bundleFile:3.6.4]
    at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:520) [bundleFile:3.6.4]
    at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:365) [bundleFile:3.6.4]
    at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:316) [bundleFile:3.6.4]

https://community.openhab.org/t/ring-doorbell/4477/310

**Comment by Daniel10001** [comment]
Version used: OpenHab 3.0.0-SNAPSHOT
Environment name and version Chrome 76, Java 11, 
Operating System and version Windows 10

**Comment by wborn** [comment]
The Ring Binding source code was never added to the official openHAB add-ons .
We don't track issues here for code that is not maintained by openHAB.

**Comment by Daniel10001** [comment]
Hi Wouter.  Does this mean we will never get it working?

**Comment by wborn** [comment]
You should ask that to the person who maintains the code.

**Comment by Daniel10001** [comment]
I do not think anyone is maintaining it. That is why I've done a new request.

**Comment by wborn** [comment]
We only maintain issues here for the code that is part of this repository. So I suggest you create an issue for adding the source code of an OH3 compatible Ring Binding instead (similar to [these issues](https://github.com/openhab/openhab-addons/issues?q=is%3Aopen+is%3Aissue+label%3A%22new+binding%22)). That is something which can be fixed with a PR. Issues for code that is not part of this repo cannot be fixed with a PR.
