### ISSUE TITLE
[tesla] Does not reauthenticate after access token expires for reasons other than timeout

### ISSUE THREAD

**Issue by thigger** [openhab/openhab-addons#8873]
Tesla binding v2.5.9

Binding works fine initially (single Tesla Model 3. Lease car so my account is a secondary account).
On using the same account in the app (Android) - app briefly displays "session expired" before then successfully logging in (no username/password required)
Tesla binding then immediately becomes unable to update and reports 401 unauthorized
Only way to get the binding working again is to use "openhab-cli clean-cache" as otherwise it seems to keep trying to use old tokens ("Found a request token created at...")
Once binding works again, re-opening the android app will kill it once more.

## Expected Behavior
Binding to use refresh-token to log generate new access-token and log back in.

## Current Behavior
Binding does not automatically log back in; I can't see exactly what it's doing but I'm assuming it keeps using the old access-token (because it's expired by login limits rather than time, and it doesn't know that it needs to generate a new one)

## Possible Solution
Binding responds to 401 by going back through the "authenticate()" steps

## Steps to Reproduce (for Bugs)
Use binding with a secondary account (at least I'm assuming this is the difference to explain why others aren't experiencing this)
Log into phone app on the same account

## Context
Unable to use binding for more than a few minutes

## Your Environment
OpenHAB 2.5.9
Ubuntu 18.04.5 LTS

## Log
App opened at 16:10 before the "Unauthorized" line
`2020-10-26 16:08:53.855 [DEBUG] [internal.handler.TeslaVehicleHandler] - Querying the vehicle : Response : 200:OK
2020-10-26 16:08:53.858 [DEBUG] [internal.handler.TeslaVehicleHandler] - Querying the vehicle: VIN ***MY_VIN***
2020-10-26 16:09:54.534 [DEBUG] [internal.handler.TeslaVehicleHandler] - Querying the vehicle : Response : 200:OK
2020-10-26 16:09:54.536 [DEBUG] [internal.handler.TeslaVehicleHandler] - Querying the vehicle: VIN ***MY_VIN***
2020-10-26 16:09:54.537 [DEBUG] [internal.handler.TeslaVehicleHandler] - Vehicle is inactive
2020-10-26 16:10:55.215 [DEBUG] [internal.handler.TeslaVehicleHandler] - Querying the vehicle : Response : 401:Unauthorized
2020-10-26 16:10:55.217 [WARN ] [internal.handler.TeslaVehicleHandler] - Got an unsuccessful result, setting vehicle to offline and will try again
2020-10-26 16:10:55.219 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception:
java.lang.NullPointerException: null
        at org.openhab.binding.tesla.internal.handler.TeslaVehicleHandler.checkResponse(TeslaVehicleHandler.java:564) ~[?:?]
        at org.openhab.binding.tesla.internal.handler.TeslaVehicleHandler.queryVehicle(TeslaVehicleHandler.java:709) ~[?:?]
        at org.openhab.binding.tesla.internal.handler.TeslaVehicleHandler.queryVehicleAndUpdate(TeslaVehicleHandler.java:737) ~[?:?]
        at org.openhab.binding.tesla.internal.handler.TeslaVehicleHandler.lambda$0(TeslaVehicleHandler.java:941) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
`

**Comment by kaikreuzer** [comment]
Could you check if this still happen on 3.0.0?

**Comment by thigger** [comment]
I'll try - is this because 3.0.0 contains a potential fix or just housekeeping around old bugs? I've been avoiding upgrading to 3.0.0 until I have a weekend free to fix breakages!

**Comment by kaikreuzer** [comment]
There have been a few small changes, but nothing directly directed at this issue. So it's indeed more like housekeeping or making sure that an issue is still existing before spending time with it. But if you're not yet on 3.0.0, don't feel forced to spend the time right now. If you plan the upgrade in the coming weeks, that should be just fine.

**Comment by thigger** [comment]
Seems to have been fixed as part of fixing #10016 , thanks!

**Comment by cauer71** [comment]
`2021-06-14 09:30:37.037 [DEBUG] [internal.handler.TeslaVehicleHandler] - Querying the vehicle : Response : 200:org.apache.cxf.jaxrs.impl.ResponseImpl$1@1722372
2021-06-14 09:30:37.041 [DEBUG] [internal.handler.TeslaVehicleHandler] - Querying the vehicle: VIN 5YJ3E7EB3MF825474
2021-06-14 09:31:37.872 [DEBUG] [internal.handler.TeslaVehicleHandler] - Querying the vehicle : Response : 200:org.apache.cxf.jaxrs.impl.ResponseImpl$1@fe762
2021-06-14 09:31:37.875 [DEBUG] [internal.handler.TeslaVehicleHandler] - Querying the vehicle: VIN 5YJ3E7EB3MF825474
2021-06-14 09:32:48.713 [DEBUG] [internal.handler.TeslaVehicleHandler] - Querying the vehicle : Response : 408:org.apache.cxf.jaxrs.impl.ResponseImpl$1@1a8a724
2021-06-14 09:32:48.715 [WARN ] [internal.handler.TeslaVehicleHandler] - Got an unsuccessful result, setting vehicle to offline and will try again
2021-06-14 09:32:48.718 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception: 
java.lang.NullPointerException: null
	at org.openhab.binding.tesla.internal.handler.TeslaVehicleHandler.checkResponse(TeslaVehicleHandler.java:564) ~[?:?]
	at org.openhab.binding.tesla.internal.handler.TeslaVehicleHandler.queryVehicle(TeslaVehicleHandler.java:709) ~[?:?]
	at org.openhab.binding.tesla.internal.handler.TeslaVehicleHandler.queryVehicleAndUpdate(TeslaVehicleHandler.java:737) ~[?:?]
	at org.openhab.binding.tesla.internal.handler.TeslaVehicleHandler.lambda$0(TeslaVehicleHandler.java:941) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]`

Does anyone else experience this?

**Comment by cauer71** [comment]
I have the same issue with 3.0.2 after a few hours:

`2021-06-14 09:30:37.037 [DEBUG] [internal.handler.TeslaVehicleHandler] - Querying the vehicle : Response : 200:org.apache.cxf.jaxrs.impl.ResponseImpl$1@1722372
2021-06-14 09:30:37.041 [DEBUG] [internal.handler.TeslaVehicleHandler] - Querying the vehicle: VIN 5YJ3E7EB3MF825474
2021-06-14 09:31:37.872 [DEBUG] [internal.handler.TeslaVehicleHandler] - Querying the vehicle : Response : 200:org.apache.cxf.jaxrs.impl.ResponseImpl$1@fe762
2021-06-14 09:31:37.875 [DEBUG] [internal.handler.TeslaVehicleHandler] - Querying the vehicle: VIN 5YJ3E7EB3MF825474
2021-06-14 09:32:48.713 [DEBUG] [internal.handler.TeslaVehicleHandler] - Querying the vehicle : Response : 408:org.apache.cxf.jaxrs.impl.ResponseImpl$1@1a8a724
2021-06-14 09:32:48.715 [WARN ] [internal.handler.TeslaVehicleHandler] - Got an unsuccessful result, setting vehicle to offline and will try again
2021-06-14 09:32:48.718 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception: 
java.lang.NullPointerException: null
	at org.openhab.binding.tesla.internal.handler.TeslaVehicleHandler.checkResponse(TeslaVehicleHandler.java:564) ~[?:?]
	at org.openhab.binding.tesla.internal.handler.TeslaVehicleHandler.queryVehicle(TeslaVehicleHandler.java:709) ~[?:?]
	at org.openhab.binding.tesla.internal.handler.TeslaVehicleHandler.queryVehicleAndUpdate(TeslaVehicleHandler.java:737) ~[?:?]
	at org.openhab.binding.tesla.internal.handler.TeslaVehicleHandler.lambda$0(TeslaVehicleHandler.java:941) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]`
