### ISSUE TITLE
[amazonechocontrol] NPE in DynamicStateDescriptionSmartHome

### ISSUE THREAD

**Issue by paulo9999** [openhab/openhab-addons#8885]
Hello, after the latest update my sitemap stopped working, especially when it involves frame. 

I saved the sitemap to see if there's an issue with the logs, but there is no warning on it.

When I click at the frame "Sala", nothing happens. 

 Frame label="Sala" {
        Text label="Sala" icon="sofa" {
          Frame {
              Switch item=Abajur_light label="Abajur"
              Switch item=Hall_light label="Hall"
              Switch item=Sala_estar_light label="Sala de estar"
              Switch item=Sala_jantar_middle_light label="Sala de Jantar meio"
              Switch item=Sala_jantar_edge_light label="Sala de Jantar pontas"
              Switch item=Sacada_light label="Sacada"
              Switch item=Philips_Power label="Philips"
              Switch item=Corredor_light label="Corredor"
              Switch item=Dining_Strip_power label="Ambiente"
              Colorpicker  item=Dining_Strip_color label="Cor" icon="Colorwheel"
       }

and at the logs I can see these errors:

2020-10-26 08:36:21.131 [WARN ] [org.openhab.core.items.GenericItem  ] - failed notifying listener 'org.openhab.core.io.rest.sitemap.internal.PageChangeListener@fec914' about state update of item Dining_Strip_color: null

java.lang.NullPointerException: null

	at org.openhab.binding.amazonechocontrol.internal.smarthome.DynamicStateDescriptionSmartHome.getStateDescription(DynamicStateDescriptionSmartHome.java:69) ~[?:?]

	at org.openhab.core.thing.internal.ChannelStateDescriptionProvider.getDynamicStateDescription(ChannelStateDescriptionProvider.java:134) ~[?:?]

	at org.openhab.core.thing.internal.ChannelStateDescriptionProvider.getStateDescription(ChannelStateDescriptionProvider.java:120) ~[?:?]

	at org.openhab.core.thing.internal.ChannelStateDescriptionProvider.getStateDescriptionFragment(ChannelStateDescriptionProvider.java:86) ~[?:?]

	at org.openhab.core.internal.service.StateDescriptionServiceImpl.getMergedStateDescriptionFragments(StateDescriptionServiceImpl.java:71) ~[bundleFile:?]

	at org.openhab.core.internal.service.StateDescriptionServiceImpl.getStateDescription(StateDescriptionServiceImpl.java:63) ~[bundleFile:?]

	at org.openhab.core.items.GenericItem.getStateDescription(GenericItem.java:409) ~[bundleFile:?]

	at org.openhab.core.items.GenericItem.getStateDescription(GenericItem.java:403) ~[bundleFile:?]

	at org.openhab.core.ui.internal.items.ItemUIRegistryImpl.getLabel(ItemUIRegistryImpl.java:313) ~[?:?]

	at org.openhab.core.io.rest.sitemap.internal.PageChangeListener.constructSitemapEvents(PageChangeListener.java:228) ~[?:?]

	at org.openhab.core.io.rest.sitemap.internal.PageChangeListener.constructSitemapEvents(PageChangeListener.java:214) ~[?:?]

	at org.openhab.core.io.rest.sitemap.internal.PageChangeListener.constructAndSendEvents(PageChangeListener.java:172) ~[?:?]

	at org.openhab.core.io.rest.sitemap.internal.PageChangeListener.stateChanged(PageChangeListener.java:186) ~[?:?]

	at org.openhab.core.items.GenericItem.lambda$1(GenericItem.java:259) [bundleFile:?]

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]

	at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by CSchlipp** [comment]
Same here, but the issue seems to be related to the update of OH to 2.5.10. 
I'm using the same manually installed snapshot build of the addon in OH 2.5.10 as I was using before in OH 2.5.9.

Seems like Channel.getChannelTypeUID() is suddenly returning null instead of a ChannelTypeUID...

**Comment by J-N-K** [comment]
Fixed with #8891 and #8888
