### ISSUE TITLE
[neato] Error when getting Robot State. Error message: Could not find robot_serial for specified vendor_name

### ISSUE THREAD

**Issue by stuart938503** [openhab/openhab-addons#8983]
OH + binding 2.5.10, on Ubuntu 18.04.5 LTS

Trying to get  setup with the Neato binding. I've added the Neato Account thing via the PaperUI. Auto discovery of our robot fails (believe related to #8930), so added the robot manually. I extracted the serial and secret from the debug logs when troubleshooting the auto-discovery, but am presented with the error below when the binding tries to get the robot state:

```
2020-11-07 23:47:38.811 [DEBUG] [ab.binding.neato.internal.NeatoRobot] - Will get STATE for Robot <my serial>

2020-11-07 23:47:38.811 [DEBUG] [ab.binding.neato.internal.NeatoRobot] - Calling Neato WS with body: {"reqId":"1","cmd":"getRobotState","params":{}}

2020-11-07 23:47:39.218 [DEBUG] [ab.binding.neato.internal.NeatoRobot] - Result from getRobotState: {"message":"Could not find robot_serial for specified vendor_name"}

2020-11-07 23:47:39.219 [ERROR] [ab.binding.neato.internal.NeatoRobot] - Error when getting Robot State. Error message: Could not find robot_serial for specified vendor_name

2020-11-07 23:47:39.219 [DEBUG] [.neato.internal.handler.NeatoHandler] - Error when refreshing state.

org.openhab.binding.neato.internal.CouldNotFindRobotException: Could not find robot_serial for specified vendor_name

	at org.openhab.binding.neato.internal.NeatoRobot.sendGetState(NeatoRobot.java:207) ~[?:?]

	at org.openhab.binding.neato.internal.handler.NeatoHandler.refreshStateAndUpdate(NeatoHandler.java:117) ~[?:?]

	at org.openhab.binding.neato.internal.handler.NeatoHandler.lambda$0(NeatoHandler.java:131) ~[?:?]

	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_265]

	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_265]

	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_265]

	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_265]

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_265]

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_265]

	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
```

**Comment by stuart475898** [comment]
Hmmm ok. So I had a few (seemingly) unrelated problems with OH that I fixed with a service restart, which appears to have resolved this. I had restarted the service previously but for whatever reason that did nothing.

I suspect that this issue isn't a bug with the binding itself, and looking online others have had similar messages for different bindings that were fixed with a service restart/binding reinstall. On that basis, closing.
