### ISSUE TITLE
[neeo] forwardChain incorrectly being set to "true" instead of blank

### ISSUE THREAD

**Issue by morph166955** [openhab/openhab-addons#9027]
Separating from: https://github.com/openhab/openhab-addons/issues/8984

After moving to OH3, forwardChain is no longer blank when not configured under the thing.  For reasons unknown, it is now set to "true" when not specified.  Configuring as forwardChain="" resolves this issue and removes the error seen below.

```
2020-11-14 17:18:23.600 [TRACE] [inding.neeo.internal.net.HttpRequest] - sendPostJsonCommand: target=true, body={"action":"launch","device":"Top TV","room":"Theater","recipe":"Top TV"}
2020-11-14 17:18:23.603 [WARN ] [ache.cxf.phase.PhaseInterceptorChain] - Interceptor for {true}WebClient has thrown exception, unwinding now
java.lang.IllegalArgumentException: URI is not absolute
        at java.net.URL.fromURI(URL.java:692) ~[?:?]
        at java.net.URI.toURL(URI.java:1116) ~[?:?]
        at org.apache.cxf.transport.http.Address.getURL(Address.java:60) ~[bundleFile:1.0.9]
        at org.apache.cxf.transport.http.URLConnectionHTTPConduit.createConnection(URLConnectionHTTPConduit.java:113) ~[bundleFile:1.0.9]
        at org.apache.cxf.transport.http.URLConnectionHTTPConduit.setupConnection(URLConnectionHTTPConduit.java:126) ~[bundleFile:1.0.9]
        at org.apache.cxf.transport.http.HTTPConduit.prepare(HTTPConduit.java:505) ~[bundleFile:1.0.9]
        at org.apache.cxf.interceptor.MessageSenderInterceptor.handleMessage(MessageSenderInterceptor.java:47) ~[bundleFile:1.0.9]
        at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308) [bundleFile:1.0.9]
        at org.apache.cxf.jaxrs.client.AbstractClient.doRunInterceptorChain(AbstractClient.java:705) [bundleFile:1.0.9]
        at org.apache.cxf.jaxrs.client.WebClient.doChainedInvocation(WebClient.java:1081) [bundleFile:1.0.9]
        at org.apache.cxf.jaxrs.client.WebClient.doInvoke(WebClient.java:927) [bundleFile:1.0.9]
        at org.apache.cxf.jaxrs.client.WebClient.doInvoke(WebClient.java:896) [bundleFile:1.0.9]
        at org.apache.cxf.jaxrs.client.WebClient.invoke(WebClient.java:461) [bundleFile:1.0.9]
        at org.apache.cxf.jaxrs.client.SyncInvokerImpl.method(SyncInvokerImpl.java:150) [bundleFile:1.0.9]
        at org.apache.cxf.jaxrs.client.SyncInvokerImpl.method(SyncInvokerImpl.java:145) [bundleFile:1.0.9]
        at org.apache.cxf.jaxrs.client.SyncInvokerImpl.post(SyncInvokerImpl.java:85) [bundleFile:1.0.9]
        at org.apache.cxf.jaxrs.client.spec.InvocationBuilderImpl.post(InvocationBuilderImpl.java:153) [bundleFile:1.0.9]
        at org.openhab.binding.neeo.internal.net.HttpRequest.sendPostJsonCommand(HttpRequest.java:97) [bundleFile:?]
        at org.openhab.binding.neeo.internal.handler.NeeoForwardActionsServlet.lambda$0(NeeoForwardActionsServlet.java:105) [bundleFile:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
2020-11-14 17:18:23.604 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception:
java.lang.IllegalArgumentException: URI is not absolute
        at java.net.URL.fromURI(URL.java:692) ~[?:?]
        at java.net.URI.toURL(URI.java:1116) ~[?:?]
        at org.apache.cxf.transport.http.Address.getURL(Address.java:60) ~[?:?]
        at org.apache.cxf.transport.http.URLConnectionHTTPConduit.close(URLConnectionHTTPConduit.java:100) ~[?:?]
        at org.apache.cxf.endpoint.AbstractConduitSelector.close(AbstractConduitSelector.java:77) ~[?:?]
        at org.apache.cxf.jaxrs.client.AbstractClient.close(AbstractClient.java:360) ~[?:?]
        at org.apache.cxf.jaxrs.client.spec.ClientImpl.close(ClientImpl.java:90) ~[?:?]
        at org.openhab.binding.neeo.internal.net.HttpRequest.close(HttpRequest.java:113) ~[?:?]
        at org.openhab.binding.neeo.internal.handler.NeeoForwardActionsServlet.lambda$0(NeeoForwardActionsServlet.java:112) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]

```

**Comment by morph166955** [comment]
@J-N-K calling your attention to this as we were working it on the other issue.  As you requested, I tested by adding forwardChain="" to the thing configuration and that makes this error stop.  Not sure why this changed when we went to OH3.

**Comment by J-N-K** [comment]
This is more likely a core-issue then. I have added a debug statement, can you try the latest version? At the same place as before.

**Comment by morph166955** [comment]
I assume I need to remove the forwardChain from the thing config to see this debug correct?

**Comment by J-N-K** [comment]
Depends. You should see a „brain ... with config ...“ message in the log. Forwardchain should be empty. If you remove the config, you should see „true“. If that is the case, then it‘s a core issue. If it stays empty, it‘s in the binding.

**Comment by morph166955** [comment]
I did one with and one without the forwardChain in the thing configs:

```
2020-11-14 18:58:23.683 [TRACE] [eo.internal.handler.NeeoBrainHandler] - Brain-UID neeo:brain:05dbea22: config is NeeoBrainConfig{ipAddress='REMOVED', enableForwardActions=true, forwardChain='true', discoverEmptyRooms=false, checkStatusInterval=10}
2020-11-14 18:58:23.684 [TRACE] [eo.internal.handler.NeeoBrainHandler] - Brain-UID neeo:brain:713af1e8: config is NeeoBrainConfig{ipAddress='REMOVED', enableForwardActions=true, forwardChain='', discoverEmptyRooms=false, checkStatusInterval=10}
```

**Comment by morph166955** [comment]
Also to note, with this new version of the binding, my things are not coming online.

**Comment by J-N-K** [comment]
Ok. Will check that.

**Comment by morph166955** [comment]
3.0.0.202011121116 seems to work just fine with forwardChain set to "" in the thing config.  If that helps.  Only this newest version seems to not work properly.  Possibly something in the debug code you added?

**Comment by J-N-K** [comment]
No. It was a silly `!` in the wrong place at another code improvement. Could you please try again?

I also found the other issue. The default for `forwardChain` was set to `true` in the thing defintion XML. This is obviously wrong and causes this issue.

**Comment by morph166955** [comment]
With the newest code.  Notice it says null and not ""

```
2020-11-14 19:43:48.760 [TRACE] [eo.internal.handler.NeeoBrainHandler] - Brain-UID neeo:brain:05dbea22: config is NeeoBrainConfig{ipAddress='REMOVED', enableForwardActions=true, forwardChain='null', discoverEmptyRooms=false, checkStatusInterval=10}

2020-11-14 19:43:48.763 [TRACE] [eo.internal.handler.NeeoBrainHandler] - Brain-UID neeo:brain:713af1e8: config is NeeoBrainConfig{ipAddress='REMOVED', enableForwardActions=true, forwardChain='', discoverEmptyRooms=false, checkStatusInterval=10}

```

**Comment by J-N-K** [comment]
`null` is the correct value if nothing is set. Are the things coming online again?

**Comment by morph166955** [comment]
Yes, everything works with that updated version as best as I can tell.

My understanding from the documentation was that it should actually be blank, not null.  Could just be how they documented it though.  I'm fine either way, doesn't much matter to me since it all works and no errors are kicking.

**Comment by J-N-K** [comment]
`null` is the internal representation of `not configured`. `""` is configured as empty string. Not much of a difference in most cases. At least not here, as it only checks if the configured value has at least one character. Thanks for your cooperation.

**Comment by morph166955** [comment]
Works for me.  Everything seems to be working so I'd say you're good to commit.  Thanks for the help!
