### ISSUE TITLE
[ipcamera] Support for SMD Plus for Dahua XVR with AI

### ISSUE THREAD

**Issue by colcm** [openhab/openhab-addons#9129]
Hello,

1. openHAB 2.5.10 Release Build
2.  IpCamera Binding  (binding-ipcamera - 2.5.10)
3.  Dahua XVR function description:

Dahua XVR like XVR5108HS-I2 have new SMD Plus (Smart Motion Detection) that is a filter image after a MD trigger was started.
SMD Plus has two components (Effective Target):
- Human 
- Motor Vehicle
![image](https://user-images.githubusercontent.com/47666049/100228968-2faf0d80-2f2c-11eb-911f-fd829359b04e.png)
These two generate three type of events:
- Human
- Motor Vehicle
- Human&Motor Vehicle
![image](https://user-images.githubusercontent.com/47666049/100229211-90d6e100-2f2c-11eb-89bf-d272e9e0094b.png)

4. IpCamera Binding function request (proposal):
- add new SMD Alarm channel - Switch (ON/OFF)
- add new SMD Alarm Type channel - String  (Human, Motor Vehicle, Human&Motor Vehicle)
- NVR Channel no.  - this can be from Thing config "NVR input Channel" in this case will be create on Thing per NVR channel, or separated channel on Thing to be string and have no. NVR channel

5. Output example (TRACE log):

```
2020-11-23 17:12:45.124 [TRACE] [era.internal.handler.IpCameraHandler] - HTTP Result back from camera is 	:--myboundary

Content-Type: text/plain

Content-Length:153

Code=SmartMotionHuman;action=Start;index=1;data={

   "object" : [

      {

         "HumanID" : 0,

         "Rect" : [ 29, 103, 171, 920 ]

      }

   ]

}

:

2020-11-23 17:12:57.858 [TRACE] [era.internal.handler.IpCameraHandler] - HTTP Result back from camera is 	:--myboundary

Content-Type: text/plain

Content-Length:76

Code=VideoMotion;action=Stop;index=1;data={

   "SmartMotionEnable" : true

}

:

2020-11-23 17:13:01.121 [TRACE] [era.internal.handler.IpCameraHandler] - HTTP Result back from camera is 	:--myboundary

Content-Type: text/plain

Content-Length:41

Code=SmartMotionHuman;action=Stop;index=1

:
```

**Comment by Skinah** [comment]
Does the Bindings log show it changes between something like these? Since I dont have a camera with the feature, more exact information is needed.... Also what happens with the other features like `Stranger Mode`?

Code=SmartMotionHuman;action=Start;index=1;data={......
Code=SmartMotionMotorVehicle;action=Start;index=1;data={......
Code=SmartMotionHuman&MotorVehicle;action=Start;index=1;data={......

There may be another way to handle this that means future alarms are automatically supported. Maybe if an Alarm starts with the word 'Smart' or perhaps 'SmartMotion' then do the following with a single channel called `smartMotion` of type String.

No Alarm it contains
Code=SmartMotionHuman;action=Stop;index=1

Any alarm that occurs regardless of type then dumps the full string that you can handle in a rule anyway you wish..

```
Code=SmartMotionHuman;action=Start;index=1;data={

   "object" : [

      {

         "HumanID" : 0,

         "Rect" : [ 29, 103, 171, 920 ]

      }

   ]

}
```

Or would it be more useful to strip it back to make a rule handle it easier?

```
"object" : [

      {

         "HumanID" : 0,

         "Rect" : [ 29, 103, 171, 920 ]

      }

   ]
```

**Comment by colcm** [comment]
Hello,

first I did not check the "Stranger Mode" if you talk about "Face Recognition" because on AI SMD and "Face Recognition" are not working in parallel on this DVR.

Regarding SMD function, I have made other tests and seams that are only two actions with Start and Stop even on DVR is on alert (ex.Human&Motor Vehicle):
Code=SmartMotionHuman;action=Start;index=2
Code=SmartMotionHuman;action=Stop;index=2

Code=SmartMotionVehicle;action=Start;index=2
Code=SmartMotionVehicle;action=Stop;index=2

In the log I can not identify the DVR channel from where the alarm come . I have made test on other camera but no channel number inside of info.
My idea is to be the same like IVS on Dahua cameras that works. I am using "Line Crossing Alarm" and "Image". When "Line Crossing Alarm" is trigger I have collected a snapshot from "Image" and sent Telegram for example.

How can an "Alarm" code must be in the log? For example "Motion Alarm" on Dahua?

Can be a string like an output and manage on one rule, but more simple will a status ON/OFF - Start/Stop for SmartMotionHuman and for SmartMotionVehicle.

Bellow my tests:

Test1:

```
2020-11-26 11:11:43.172 [TRACE] [era.internal.handler.IpCameraHandler] - HTTP Result back from camera is 	:--myboundary

Content-Type: text/plain

Content-Length:76

Code=VideoMotion;action=Stop;index=1;data={

   "SmartMotionEnable" : true

}

:

2020-11-26 11:11:51.125 [TRACE] [era.internal.handler.IpCameraHandler] - HTTP Result back from camera is 	:--myboundary

Content-Type: text/plain

Content-Length:154

Code=SmartMotionHuman;action=Start;index=2;data={

   "object" : [

      {

         "HumanID" : 0,

:

2020-11-26 11:11:51.126 [TRACE] [era.internal.handler.IpCameraHandler] - HTTP Result back from camera is 	:         "Rect" : [ 800, 256, 858, 615 ]

      }

   ]

}

:

2020-11-26 11:12:06.550 [TRACE] [era.internal.handler.IpCameraHandler] - HTTP Result back from camera is 	:--myboundary

Content-Type: text/plain

Content-Length:76

Code=VideoMotion;action=Stop;index=2;data={

   "SmartMotionEnable" : true

}

:

2020-11-26 11:12:09.609 [TRACE] [era.internal.handler.IpCameraHandler] - HTTP Result back from camera is 	:--myboundary

Content-Type: text/plain

Content-Length:41

Code=SmartMotionHuman;action=Stop;index=2

:

==> /var/log/openhab2/events.log <==

2020-11-26 11:12:16.754 [vent.ItemStateChangedEvent] - Sun_Azimuth changed from 165.6265173741724 ° to 165.8752356691046 °

2020-11-26 11:12:16.755 [vent.ItemStateChangedEvent] - Sun_Elevation changed from 22.785277980565983 ° to 22.82868453134157 °

==> /var/log/openhab2/openhab.log <==

2020-11-26 11:12:18.741 [TRACE] [era.internal.handler.IpCameraHandler] - HTTP Result back from camera is 	:--myboundary

Content-Type: text/plain

Content-Length:76

Code=VideoMotion;action=Stop;index=1;data={

   "SmartMotionEnable" : true

}

:

2020-11-26 11:12:45.390 [TRACE] [era.internal.handler.IpCameraHandler] - HTTP Result back from camera is 	:--myboundary

Content-Type: text/plain

Content-Length:76

Code=VideoMotion;action=Stop;index=1;data={

   "SmartMotionEnable" : true

}

:



Test 2

2020-11-26 11:23:20.025 [TRACE] [era.internal.handler.IpCameraHandler] - HTTP Result back from camera is 	:--myboundary

Content-Type: text/plain

Content-Length:158

Code=SmartMotionVehicle;action=Start;index=2;data={

   "object" : [

      {

         "Rect" : [ 64, 433, 736, 1006 ],

         "VehicleID" : 0

   :

2020-11-26 11:23:20.026 [TRACE] [era.internal.handler.IpCameraHandler] - HTTP Result back from camera is 	:   }

   ]

}

:

2020-11-26 11:23:25.962 [TRACE] [era.internal.handler.IpCameraHandler] - HTTP Result back from camera is 	:--myboundary

Content-Type: text/plain

Content-Length:76

Code=VideoMotion;action=Stop;index=2;data={

   "SmartMotionEnable" : true

}

:

2020-11-26 11:23:30.964 [TRACE] [era.internal.handler.IpCameraHandler] - HTTP Result back from camera is 	:--myboundary

Content-Type: text/plain

Content-Length:76

Code=VideoMotion;action=Stop;index=1;data={

   "SmartMotionEnable" : true

}

:

2020-11-26 11:23:31.619 [TRACE] [era.internal.handler.IpCameraHandler] - HTTP Result back from camera is 	:--myboundary

Content-Type: text/plain

Content-Length:43

Code=SmartMotionVehicle;action=Stop;index=2

:

2020-11-26 11:24:08.969 [TRACE] [era.internal.handler.IpCameraHandler] - HTTP Result back from camera is 	:--myboundary

Content-Type: text/plain

Content-Length:76

Code=VideoMotion;action=Stop;index=1;data={

   "SmartMotionEnable" : true

}

:




Test3
2020-11-26 11:29:38.170 [TRACE] [era.internal.handler.IpCameraHandler] - HTTP Result back from camera is 	:--myboundary

Content-Type: text/plain

Content-Length:76

Code=VideoMotion;action=Stop;index=1;data={

   "SmartMotionEnable" : true

}

:

2020-11-26 11:29:43.043 [TRACE] [era.internal.handler.IpCameraHandler] - HTTP Result back from camera is 	:--myboundary

Content-Type: text/plain

Content-Length:154

Code=SmartMotionHuman;action=Start;index=2;data={

   "object" : [

      {

         "HumanID" : 0,

         "Rect" : [ 794, 263, 861, 604 ]

      }

   ]

}

:

2020-11-26 11:29:46.456 [TRACE] [era.internal.handler.IpCameraHandler] - HTTP Result back from camera is 	:--myboundary

Content-Type: text/plain

Content-Length:158

Code=SmartMotionVehicle;action=Start;index=2;data={

   "object" : [

      {

         "Rect" : [ 64, 433, 738, 1006 ],

         "VehicleID" : 0

      }

   ]

}

:

2020-11-26 11:29:59.371 [TRACE] [era.internal.handler.IpCameraHandler] - HTTP Result back from camera is 	:--myboundary

Content-Type: text/plain

Content-Length:76

Code=VideoMotion;action=Stop;index=2;data={

   "SmartMotionEnable" : true

}

:

2020-11-26 11:30:02.613 [TRACE] [era.internal.handler.IpCameraHandler] - HTTP Result back from camera is 	:--myboundary

Content-Type: text/plain

Content-Length:41

Code=SmartMotionHuman;action=Stop;index=2

:

2020-11-26 11:30:02.618 [TRACE] [era.internal.handler.IpCameraHandler] - HTTP Result back from camera is 	:--myboundary

Content-Type: text/plain

Content-Length:43

Code=SmartMotionVehicle;action=Stop;index=2

:


```

**Comment by colcm** [comment]
> Does the Bindings log show it changes between something like these? Since I dont have a camera with the feature, more exact information is needed.... Also what happens with the other features like `Stranger Mode`?
> 
> Code=SmartMotionHuman;action=Start;index=1;data={......
> Code=SmartMotionMotorVehicle;action=Start;index=1;data={......
> Code=SmartMotionHuman&MotorVehicle;action=Start;index=1;data={......
> 
> There may be another way to handle this that means future alarms are automatically supported. Maybe if an Alarm starts with the word 'Smart' or perhaps 'SmartMotion' then do the following with a single channel called `smartMotion` of type String.
> 
> No Alarm it contains
> Code=SmartMotionHuman;action=Stop;index=1
> 
> Any alarm that occurs regardless of type then dumps the full string that you can handle in a rule anyway you wish..
> 
> ```
> Code=SmartMotionHuman;action=Start;index=1;data={
> 
>    "object" : [
> 
>       {
> 
>          "HumanID" : 0,
> 
>          "Rect" : [ 29, 103, 171, 920 ]
> 
>       }
> 
>    ]
> 
> }
> ```
> 
> Or would it be more useful to strip it back to make a rule handle it easier?
> 
> ```
> "object" : [
> 
>       {
> 
>          "HumanID" : 0,
> 
>          "Rect" : [ 29, 103, 171, 920 ]
> 
>       }
> 
>    ]
> ```

Hello Skinah,

did you had time to see this point?

Thank you!
Catalin

**Comment by Skinah** [comment]
Yes just it is a busy time of year. Have a few weeks holidays next week so should be able to look at it then. You have provided all that is needed with the traces.

**Comment by colcm** [comment]
Hello Skinah,

did you had time to look on it?

Thank you!
Catalin

**Comment by Skinah** [comment]
Just started on this now.

**Comment by Skinah** [comment]
I have a build ready for you to test here:

http://www.pcmus.com/openhab/IpCameraBinding/

This build has a full rework of handling alarms and will now log any unknown alarm codes in DEBUG. 
TRACE gives you lots of info on the alarms.

Note you will/may need to delete the re-add the camera thing for the channels to get seen or copy the UID before you delete it so you can use the exact same UID for everything to link back up. You also need to uninstall the merged binding, then drop the unzipped jar files into the addons folder.

**Comment by colcm** [comment]
Hello Skinah,

the binding is for OH 3 only? Me I have installed 2.5.11 and the installation failed:

2021-02-02 13:49:04.141 [WARN ] [org.apache.felix.fileinstall        ] - Error while starting bundle: file:/usr/share/openhab2/addons/org.openhab.binding.ipcamera-3.1.0-SNAPSHOT.jar

org.osgi.framework.BundleException: Could not resolve module: org.openhab.binding.ipcamera [274]

  Unresolved requirement: Import-Package: org.openhab.core.config.discovery

	at org.eclipse.osgi.container.Module.start(Module.java:444) ~[org.eclipse.osgi-3.12.100.jar:?]

	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:383) ~[org.eclipse.osgi-3.12.100.jar:?]

	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1260) [bundleFile:3.6.4]

	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1233) [bundleFile:3.6.4]

	at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:520) [bundleFile:3.6.4]

	at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:365) [bundleFile:3.6.4]

	at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:316) [bundleFile:3.6.4]



Thank you!
Catalin

**Comment by colcm** [comment]
Hello Skinah,

I have installed on OH3 and put the files on add-on folder but:
- on Add-ons: bindings - the ipcamera binding is not present
![image](https://user-images.githubusercontent.com/47666049/106615439-19997b00-6575-11eb-996c-79b0ad87c8f6.png)

- I have an error at connection to Dahua XVR:
2021-02-02 16:31:12.800 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'ipcamera:dahua:1921682151' changed from OFFLINE (CONFIGURATION_ERROR): Camera gave no WWW-Authenticate: Your login details must be wrong. to ONLINE

2021-02-02 16:31:12.826 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'ipcamera:dahua:1921682151' changed from ONLINE to OFFLINE (CONFIGURATION_ERROR): Camera gave no WWW-Authenticate: Your login details must be wrong.

The account is OK and also the connection to an IP camera works (ex. IPC-HFW4431E-SE) 

Thank you!

**Comment by Skinah** [comment]
Every thing looks normal, manually installed jars don’t show up in that list, I hope that changes in the future as I have now had to tell at least 3 confused people that.

if you can run the DEBUG level logs for a while and report any unknown alarms that get logged that would be helpful.

**Comment by colcm** [comment]
Hello Skinah,

till now I have following entry on log with DEBUG level:

2021-02-03 14:13:40.610 [DEBUG] [era.internal.handler.IpCameraHandler] - Unrecognised Dahua event, Code=RecordDelete, action=Pulse

2021-02-03 14:13:59.302 [DEBUG] [era.internal.handler.IpCameraHandler] - Unrecognised Dahua event, Code=RecordDelete, action=Pulse

2021-02-03 14:17:59.751 [DEBUG] [era.internal.handler.IpCameraHandler] - Unrecognised Dahua event, Code=RecordDelete, action=Pulse

2021-02-03 14:18:14.331 [DEBUG] [era.internal.handler.IpCameraHandler] - Unrecognised Dahua event, Code=RecordDelete, action=Pulse

2021-02-03 14:19:40.966 [DEBUG] [era.internal.handler.IpCameraHandler] - Unrecognised Dahua event, Code=RecordDelete, action=Pulse

2021-02-03 14:20:04.642 [DEBUG] [era.internal.handler.IpCameraHandler] - Unrecognised Dahua event, Code=RecordDelete, action=Pulse

Thank you!
