### ISSUE TITLE
[shelly] NPE in ShellyDeviceProfile.inButtonMode() (Shelly 1L)

### ISSUE THREAD

**Issue by markus7017** [openhab/openhab-addons#9219]
Using Shelly 1L the following exception might happen (could also affect other devices)

```
2020-11-30 18:13:45.747 [DEBUG] [elly.internal.coap.ShellyCoapHandler] - shelly1l-arbeitszimmer_schalter: Unable to process data from sensor[4], devId=SHSW-L#84CCA8ACEDF8#2, payload={"G":[[0,9103,1],[0,1101,1],[0,2101,1],[0,2102,""],[0,2103,0],[0,2201,0],[0,2202,""],[0,2203,0],[0,3104,43.19],[0,3105,109.74],[0,6101,0]]}
java.lang.NullPointerException: null
	at org.openhab.binding.shelly.internal.api.ShellyDeviceProfile.inButtonMode(ShellyDeviceProfile.java:276) ~[?:?]
	at org.openhab.binding.shelly.internal.coap.ShellyCoIoTProtocol.handleInputEvent(ShellyCoIoTProtocol.java:192) ~[?:?]
	at org.openhab.binding.shelly.internal.coap.ShellyCoIoTVersion2.handleStatusUpdate(ShellyCoIoTVersion2.java:138) ~[?:?]
	at org.openhab.binding.shelly.internal.coap.ShellyCoapHandler.handleStatusUpdate(ShellyCoapHandler.java:418) ~[?:?]
	at org.openhab.binding.shelly.internal.coap.ShellyCoapHandler.processResponse(ShellyCoapHandler.java:237) ~[?:?]
	at org.openhab.binding.shelly.internal.coap.ShellyCoapServer.lambda$0(ShellyCoapServer.java:105) ~[?:?]
	at java.lang.Iterable.forEach(Iterable.java:75) [?:1.8.0_222]
	at org.openhab.binding.shelly.internal.coap.ShellyCoapServer.processResponse(ShellyCoapServer.java:105) [bundleFile:?]
	at org.openhab.binding.shelly.internal.coap.ShellyCoapServer$ShellyStatusListener.handleRequest(ShellyCoapServer.java:71) [bundleFile:?]
	at org.eclipse.californium.core.server.ServerMessageDeliverer.deliverRequest(ServerMessageDeliverer.java:108) [bundleFile:?]
	at org.eclipse.californium.core.network.stack.BaseCoapStack$StackTopAdapter.receiveRequest(BaseCoapStack.java:200) [bundleFile:?]
	at org.eclipse.californium.core.network.stack.AbstractLayer.receiveRequest(AbstractLayer.java:84) [bundleFile:?]
	at org.eclipse.californium.core.network.stack.AbstractLayer.receiveRequest(AbstractLayer.java:84) [bundleFile:?]
	at org.eclipse.californium.core.network.stack.BlockwiseLayer.receiveRequest(BlockwiseLayer.java:398) [bundleFile:?]
	at org.eclipse.californium.core.network.stack.ReliabilityLayer.receiveRequest(ReliabilityLayer.java:272) [bundleFile:?]
	at org.eclipse.californium.core.network.stack.AbstractLayer.receiveRequest(AbstractLayer.java:84) [bundleFile:?]
	at org.eclipse.californium.core.network.stack.BaseCoapStack.receiveRequest(BaseCoapStack.java:133) [bundleFile:?]
	at org.eclipse.californium.core.network.CoapEndpoint$1.receiveRequest(CoapEndpoint.java:267) [bundleFile:?]
	at org.eclipse.californium.core.network.UdpMatcher$2.run(UdpMatcher.java:256) [bundleFile:?]
	at org.eclipse.californium.elements.util.SerialExecutor$1.run(SerialExecutor.java:276) [bundleFile:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_222]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_222]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_222]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_222]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
2020-11-30 18:13:45.983 [DEBUG] [lly.internal.util.ShellyChannelCache] - shelly1l-arbeitszimmer_schalter: Channel device#uptime updated with 269 s (type class org.eclipse.smarthome.core.library.types.QuantityType).
2020-11-30 18:13:45.986 [DEBUG] [lly.internal.util.ShellyChannelCache] - shelly1l-arbeitszimmer_schalter: Channel relay#input updated with ON (type class org.eclipse.smarthome.core.library.types.OnOffType).
2020-11-30 18:13:45.988 [DEBUG] [lly.internal.util.ShellyChannelCache] - shelly1l-arbeitszimmer_schalter: Channel relay#input updated with OFF (type class org.eclipse.smarthome.core.library.types.OnOffType).
```

**Comment by markus7017** [comment]
I updated the DEV build, try again
