### ISSUE TITLE
openhabcloud should not print out stack traces in openhab.log file

### ISSUE THREAD

**Issue by robnielsen** [openhab/openhab-addons#9405]
If the connection to openHAB cloud instance goes down, an ERROR message along with the stack trace appears in the log. For example:

```
2020-12-16 17:47:42.894 [ERROR] [io.openhabcloud.internal.CloudClient] - Error connecting to the openHAB Cloud instance: {}
io.socket.engineio.client.EngineIOException: websocket error
        at io.socket.engineio.client.Transport.onError(Transport.java:63) [bundleFile:?]
        at io.socket.engineio.client.transports.WebSocket.access$400(WebSocket.java:24) [bundleFile:?]
        at io.socket.engineio.client.transports.WebSocket$1$5.run(WebSocket.java:107) [bundleFile:?]
        at io.socket.thread.EventThread$2.run(EventThread.java:80) [bundleFile:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.io.EOFException
        at okio.RealBufferedSource.require(RealBufferedSource.java:60) ~[?:?]
        at okio.RealBufferedSource.readByte(RealBufferedSource.java:73) ~[?:?]
        at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:113) ~[?:?]
        at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:97) ~[?:?]
        at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:262) ~[?:?]
        at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:201) ~[?:?]
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:141) ~[?:?]
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) ~[?:?]
        ... 3 more
```

For the typical user, this information is useless and fills up the log file.  A pattern that has been used elsewhere and should be used here is to only print the stack trace if DEBUG is enabled.  See https://github.com/openhab/openhab-core/pull/1628 for an example.

**Comment by kaikreuzer** [comment]
Note that this is not thrown by the openhabcloud code at all, but by `io.socket`. There isn't much that can be done by that add-on about it. We would need to change the general logging configuration in the distro itself (which is also not nice as it is only relevant for users that use that specific add-on).

Any suggestion how to go about it?

**Comment by cweitkamp** [comment]
Just my 2ct in this: I personally would prefer if we take into account a bigger refactoring and get rid of all those clumsy dependencies used by the openHAB Cloud Connector Binding and try to use framework provided websocket / http bundles - if possible.

**Comment by robnielsen** [comment]
@kaikreuzer, are you sure? here's the offending code at https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.io.openhabcloud/src/main/java/org/openhab/io/openhabcloud/internal/CloudClient.java#L201

```
public void call(Object... args) {
    logger.error("Error connecting to the openHAB Cloud instance: {}", args[0]);
}
```

**Comment by kaikreuzer** [comment]
Good point @robnielsen, I guess you are right. So feel free to do a simple PR as a fix for it 👍 .

**Comment by robnielsen** [comment]
@kaikreuzer, submitted a PR to address this.
