### ISSUE TITLE
netatmo should not print out stack traces in openhab.log file

### ISSUE THREAD

**Issue by robnielsen** [openhab/openhab-addons#9406]
If the connection is down with netatmo, an ERROR followed by a WARN message with the stack trace appears in the log. For example:

```
2020-12-16 11:11:31.432 [ERROR] [nternal.handler.NetatmoDeviceHandler] - Unable to connect Netatmo API : java.net.SocketTimeoutException: timeout
2020-12-16 11:11:53.963 [WARN ] [nternal.handler.NetatmoBridgeHandler] - Unable to connect Netatmo API : Error on trying to get an access token!
java.lang.RuntimeException: Error on trying to get an access token!
        at org.openhab.binding.netatmo.internal.handler.NetatmoBridgeHandler.initializeApiClient(NetatmoBridgeHandler.java:207) ~[bundleFile:?]
        at org.openhab.binding.netatmo.internal.handler.NetatmoBridgeHandler.lambda$1(NetatmoBridgeHandler.java:147) [bundleFile:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: org.apache.oltu.oauth2.common.exception.OAuthSystemException: java.io.IOException: Server returned HTTP response code: 504 for URL: https://api.netatmo.net/oauth2/token
        at org.apache.oltu.oauth2.client.URLConnectionClient.execute(URLConnectionClient.java:108) ~[bundleFile:?]
        at org.apache.oltu.oauth2.client.OAuthClient.accessToken(OAuthClient.java:65) ~[bundleFile:?]
        at org.apache.oltu.oauth2.client.OAuthClient.accessToken(OAuthClient.java:55) ~[bundleFile:?]
        at org.openhab.binding.netatmo.internal.handler.NetatmoBridgeHandler.initializeApiClient(NetatmoBridgeHandler.java:195) ~[bundleFile:?]
        ... 7 more
Caused by: java.io.IOException: Server returned HTTP response code: 504 for URL: https://api.netatmo.net/oauth2/token
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1974) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1969) ~[?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1968) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1536) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520) ~[?:?]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250) ~[?:?]
        at org.apache.oltu.oauth2.client.URLConnectionClient.execute(URLConnectionClient.java:102) ~[bundleFile:?]
        at org.apache.oltu.oauth2.client.OAuthClient.accessToken(OAuthClient.java:65) ~[bundleFile:?]
        at org.apache.oltu.oauth2.client.OAuthClient.accessToken(OAuthClient.java:55) ~[bundleFile:?]
        at org.openhab.binding.netatmo.internal.handler.NetatmoBridgeHandler.initializeApiClient(NetatmoBridgeHandler.java:195) ~[bundleFile:?]
        ... 7 more
Caused by: java.io.IOException: Server returned HTTP response code: 504 for URL: https://api.netatmo.net/oauth2/token
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1924) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520) ~[?:?]
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527) ~[?:?]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:334) ~[?:?]
        at org.apache.oltu.oauth2.client.URLConnectionClient.execute(URLConnectionClient.java:98) ~[bundleFile:?]

        at org.apache.oltu.oauth2.client.OAuthClient.accessToken(OAuthClient.java:65) ~[bundleFile:?]
        at org.apache.oltu.oauth2.client.OAuthClient.accessToken(OAuthClient.java:55) ~[bundleFile:?]
        at org.openhab.binding.netatmo.internal.handler.NetatmoBridgeHandler.initializeApiClient(NetatmoBridgeHandler.java:195) 
```

For the typical user, this information is useless and fills up the log file.  A pattern that has been used elsewhere and should be used here is to only print the stack trace if DEBUG is enabled.  See https://github.com/openhab/openhab-core/pull/1628 for an example.

**Comment by lolodomo** [comment]
Was this issue fixed by the merged PR ? Please close it in case it is.
