### ISSUE TITLE
[tr064] Bridge not connecting to fritzbox

### ISSUE THREAD

**Issue by LukasA83** [openhab/openhab-addons#9485]
## Expected Behavior
tr064 fritzbox thing (bridge) connects to fritz.box, as it worked before latest change.

## Current Behavior
I tried both the url "fritz.box" or the ip "192.168.178.1", same result.
While connecting there seems to be an error: 
`

16:00:54.020 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception: 

java.lang.IllegalArgumentException: Invalid URI host: null (authority: null)

	at org.eclipse.jetty.client.HttpClient.checkHost(HttpClient.java:510) ~[?:?]

	at org.eclipse.jetty.client.HttpClient.newHttpRequest(HttpClient.java:495) ~[?:?]

	at org.eclipse.jetty.client.HttpClient.newRequest(HttpClient.java:453) ~[?:?]

	at org.eclipse.jetty.client.HttpClient.newRequest(HttpClient.java:442) ~[?:?]

	at org.openhab.binding.tr064.internal.soap.SOAPConnector.prepareSOAPRequest(SOAPConnector.java:108) ~[?:?]

	at org.openhab.binding.tr064.internal.soap.SOAPConnector.doSOAPRequest(SOAPConnector.java:132) ~[?:?]

	at org.openhab.binding.tr064.internal.Tr064RootHandler.establishSecureConnectionAndUpdateProperties(Tr064RootHandler.java:223) ~[?:?]

	at org.openhab.binding.tr064.internal.Tr064RootHandler.internalInitialize(Tr064RootHandler.java:153) ~[?:?]

	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]

	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]

	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]

	at java.lang.Thread.run(Thread.java:834) [?:?]`

**Comment by J-N-K** [comment]
Which version?

**Comment by LukasA83** [comment]
Sorry... Latest snapshot build 3.1.0 - Build 2099. When downgrading to Release 3, everything is operational again.

**Comment by LukasA83** [comment]
Just flipping through the code I believe the sequence is the problem... in "Tr064Roothandler" the soapconnector is created before the endpointBaseUrl is assigned from config.

**Comment by J-N-K** [comment]
I overlooked one call so soapConnector. Please try if `update org.openhab.binding.tr064 https://janessa.me/esh/org.openhab.binding.tr064-3.1.0-SNAPSHOT.jar` fixes your problem. Thanks.

**Comment by LukasA83** [comment]
Yep, it does, thanks. 
Maybe off-topic, but is there also an action (planned) for number / phonebook resolving (e.g. in rules)? I'm trying to set-up a missed calls push message, easy to do with rules and call list channel. But not sure how to apply the Phonebook profile there.

**Comment by J-N-K** [comment]
I guess that's possible. Can you open an issue for that, so it's not forgotten?
