### ISSUE TITLE
[DenonMarantz] Telnet Thread Issue

### ISSUE THREAD

**Issue by morph166955** [openhab/openhab-addons#9494]
Opening as per @kaikreuzer from https://github.com/openhab/openhab-core/issues/1998

It permanently blocks one thread from the thread pool as it uses it to listen to a telnet connection. It should use its own thread instead of the shared thread pool for that.

```
"OH-thingHandler-2" #226 daemon prio=5 os_prio=0 cpu=76.63ms elapsed=3419.19s tid=0x00007fbd1402c000 nid=0x40cdb runnable  [0x00007fbd00825000]
   java.lang.Thread.State: RUNNABLE
	at java.net.SocketInputStream.socketRead0(java.base@11.0.9.1/Native Method)
	at java.net.SocketInputStream.socketRead(java.base@11.0.9.1/SocketInputStream.java:115)
	at java.net.SocketInputStream.read(java.base@11.0.9.1/SocketInputStream.java:168)
	at java.net.SocketInputStream.read(java.base@11.0.9.1/SocketInputStream.java:140)
	at sun.nio.cs.StreamDecoder.readBytes(java.base@11.0.9.1/StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(java.base@11.0.9.1/StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(java.base@11.0.9.1/StreamDecoder.java:178)
	- locked <0x00000000c45000f0> (a java.io.InputStreamReader)
	at java.io.InputStreamReader.read(java.base@11.0.9.1/InputStreamReader.java:185)
	at java.io.BufferedReader.fill(java.base@11.0.9.1/BufferedReader.java:161)
	at java.io.BufferedReader.readLine(java.base@11.0.9.1/BufferedReader.java:326)
	- locked <0x00000000c45000f0> (a java.io.InputStreamReader)
	at java.io.BufferedReader.readLine(java.base@11.0.9.1/BufferedReader.java:392)
	at org.openhab.binding.denonmarantz.internal.connector.telnet.DenonMarantzTelnetClient.run(DenonMarantzTelnetClient.java:71)
```

**Comment by jwveldhuis** [comment]
Will have a look at this.

**Comment by jwveldhuis** [comment]
@morph166955 can you review my change, is this what you meant?

**Comment by morph166955** [comment]
I'll defer to @kaikreuzer. I was just copy/pasting his comments from the original issue.

**Comment by morph166955** [comment]
I pulled and compiled a jar to test this after #9511 was merged.  Ran a thread dump. Output below.

```
"OH-binding-denonmarantz:avr:0005cdf9dcee" #609800 prio=5 os_prio=0 cpu=3.85ms elapsed=414.99s tid=0x00007f766999b800 nid=0x18e929 runnable  [0x00007f7637a94000]
   java.lang.Thread.State: RUNNABLE
        at java.net.SocketInputStream.socketRead0(java.base@11.0.9.1/Native Method)
        at java.net.SocketInputStream.socketRead(java.base@11.0.9.1/SocketInputStream.java:115)
        at java.net.SocketInputStream.read(java.base@11.0.9.1/SocketInputStream.java:168)
        at java.net.SocketInputStream.read(java.base@11.0.9.1/SocketInputStream.java:140)
        at sun.nio.cs.StreamDecoder.readBytes(java.base@11.0.9.1/StreamDecoder.java:284)
        at sun.nio.cs.StreamDecoder.implRead(java.base@11.0.9.1/StreamDecoder.java:326)
        at sun.nio.cs.StreamDecoder.read(java.base@11.0.9.1/StreamDecoder.java:178)
        - locked <0x00000000dd407b48> (a java.io.InputStreamReader)
        at java.io.InputStreamReader.read(java.base@11.0.9.1/InputStreamReader.java:185)
        at java.io.BufferedReader.fill(java.base@11.0.9.1/BufferedReader.java:161)
        at java.io.BufferedReader.readLine(java.base@11.0.9.1/BufferedReader.java:326)
        - locked <0x00000000dd407b48> (a java.io.InputStreamReader)
        at java.io.BufferedReader.readLine(java.base@11.0.9.1/BufferedReader.java:392)
        at org.openhab.binding.denonmarantz.internal.connector.telnet.DenonMarantzTelnetClientThread.run(DenonMarantzTelnetClientThread.java:69)

   Locked ownable synchronizers:
        - None


```
