### ISSUE TITLE
OH3 release  mysql-persistence create table error

### ISSUE THREAD

**Issue by Sputnick85** [openhab/openhab-addons#9534]
Hi there,

today i migrated from 2.5 to 3.0 release.

build-no        : Release Build
online-repo     : https://openhab.jfrog.io/openhab/libs-release
openhab-distro  : 3.0.0
openhab-core    : 3.0.0
openhab-addons  : 3.0.0
karaf           : 4.2.7
openjdk 11.0.9.1 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.18.04)
mysql  Ver 14.14 Distrib 5.7.32

After configure the mysql-persistence some tables couldn't be created with value -> timestamp

`2020-12-26 21:30:00.084 [ERROR] [org.knowm.yank.Yank                 ] - Error in SQL query!!!
java.sql.SQLException: Invalid default value for 'value' Query: CREATE TABLE IF NOT EXISTS item0026 (time TIMESTAMP(3) NOT NULL, value TIMESTAMP(3), PRIMARY KEY(time)) Parameters: []
        at org.apache.commons.dbutils.AbstractQueryRunner.rethrow(AbstractQueryRunner.java:392) ~[bundleFile:?]
        at org.apache.commons.dbutils.QueryRunner.update(QueryRunner.java:491) ~[bundleFile:?]
        at org.apache.commons.dbutils.QueryRunner.update(QueryRunner.java:457) ~[bundleFile:?]
        at org.knowm.yank.Yank.execute(Yank.java:194) [bundleFile:?]
        at org.knowm.yank.Yank.execute(Yank.java:177) [bundleFile:?]
        at org.openhab.persistence.jdbc.db.JdbcBaseDAO.doCreateItemTable(JdbcBaseDAO.java:319) [bundleFile:?]
        at org.openhab.persistence.jdbc.internal.JdbcMapper.createItemTable(JdbcMapper.java:136) [bundleFile:?]
        at org.openhab.persistence.jdbc.internal.JdbcMapper.getTable(JdbcMapper.java:274) [bundleFile:?]
        at org.openhab.persistence.jdbc.internal.JdbcMapper.storeItemValue(JdbcMapper.java:143) [bundleFile:?]
        at org.openhab.persistence.jdbc.internal.JdbcPersistenceService.store(JdbcPersistenceService.java:140) [bundleFile:?]
        at org.openhab.core.persistence.internal.PersistenceManagerImpl.handleStateEvent(PersistenceManagerImpl.java:152) [bundleFile:?]
        at org.openhab.core.persistence.internal.PersistenceManagerImpl.stateChanged(PersistenceManagerImpl.java:473) [bundleFile:?]
        at org.openhab.core.items.GenericItem.lambda$1(GenericItem.java:259) [bundleFile:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
2020-12-26 21:30:00.091 [ERROR] [org.knowm.yank.Yank                 ] - Error in SQL query!!!`

The problem here is the default sqlmode config:
`mysql> show variables like 'sql_mode' ;
+---------------+-------------------------------------------------------------------------------------------------------------------------------------------+
| Variable_name | Value                                                                                                                                     |
+---------------+-------------------------------------------------------------------------------------------------------------------------------------------+
| sql_mode      | ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION |
+---------------+-------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.01 sec)
`

While time is a PK and autoincremented with current timestamp by default, the value filed can't be left blank. 
With sqlmode set to 'strict' or something like 'no zero in date' or 'no zero date' the timestamp has to be set to something. The create query should look like this or something similar:
`CREATE TABLE IF NOT EXISTS item0026 (time TIMESTAMP(3) NOT NULL, value TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3), PRIMARY KEY(time));`

**Comment by cweitkamp** [comment]
Thanks for reporting this issue. [Here](https://community.openhab.org/t/jdbc-mysql-persistence-in-oh3/109922/8) you can find a explanation and a solution. I guess we have to add this hint somewhere to the docs.
