### ISSUE TITLE
[neato] NPE on discovery

### ISSUE THREAD

**Issue by jjlauterbach** [openhab/openhab-addons#9561]
## Current Behavior

There's a null pointer exception due to a null bridgeUID being passed to the ThingUID constructor.

```
2020-12-28 10:50:47.462 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception: 

java.lang.NullPointerException: null
    at org.openhab.core.thing.ThingUID.<init>(ThingUID.java:58) ~[?:?]
    at org.openhab.binding.neato.internal.discovery.NeatoAccountDiscoveryService.addThing(NeatoAccountDiscoveryService.java:97) ~[?:?]
    at org.openhab.binding.neato.internal.discovery.NeatoAccountDiscoveryService.findRobots(NeatoAccountDiscoveryService.java:60) ~[?:?]
    at org.openhab.binding.neato.internal.discovery.NeatoAccountDiscoveryService.lambda$0(NeatoAccountDiscoveryService.java:74) ~[?:?]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
    at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
    at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by jensflorian** [comment]
This is not related to #8931 ?

**Comment by jjlauterbach** [comment]
No its not related to #8931.  This seems to have been caused by changes for #8449.  I'm not sure on the "correct" approach to resolve 8449 as bridgeUID is null when this code is being executed.  

Am happy to work on a proper fix for obtaining the bridgeUID during discovery, but this PR addresses the NPE and allows items to be discovered again.
