### ISSUE TITLE
[helios] Handler_Initializing_Error 

### ISSUE THREAD

**Issue by jmone1** [openhab/openhab-addons#9588]
Trying to use the OH3 Helios Binding, I get the following errors:

```
Status: UNINITIALIZED
HANDLER_INITIALIZING_ERROR
java.lang.ClassNotFoundException
```
```
2020-12-30 08:31:53.096 [ERROR] [core.thing.internal.ThingManagerImpl] - Exception occurred while initializing handler of thing 'helios:ipvario221:b552813b92': URI can not be built
javax.ws.rs.core.UriBuilderException: URI can not be built
	at org.apache.cxf.jaxrs.impl.UriBuilderImpl.doBuild(UriBuilderImpl.java:117) ~[bundleFile:1.0.9]
	at org.apache.cxf.jaxrs.impl.UriBuilderImpl.build(UriBuilderImpl.java:95) ~[bundleFile:1.0.9]
	at org.apache.cxf.jaxrs.client.spec.ClientImpl$WebTargetImpl.initTargetClientIfNeeded(ClientImpl.java:350) ~[bundleFile:1.0.9]
	at org.apache.cxf.jaxrs.client.spec.ClientImpl$WebTargetImpl.request(ClientImpl.java:265) ~[bundleFile:1.0.9]
	at org.apache.cxf.jaxrs.client.spec.ClientImpl$WebTargetImpl.request(ClientImpl.java:383) ~[bundleFile:1.0.9]
	at org.openhab.binding.helios.internal.handler.HeliosHandler221.initialize(HeliosHandler221.java:189) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor37.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.openhab.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:154) [bundleFile:?]
	at org.openhab.core.internal.common.Invocation.call(Invocation.java:52) [bundleFile:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.net.URISyntaxException: Illegal character in authority at index 8: https://{ip}/api/system/info
	at java.net.URI$Parser.fail(URI.java:2913) ~[?:?]
	at java.net.URI$Parser.parseAuthority(URI.java:3247) ~[?:?]
	at java.net.URI$Parser.parseHierarchical(URI.java:3158) ~[?:?]
	at java.net.URI$Parser.parse(URI.java:3114) ~[?:?]
	at java.net.URI.<init>(URI.java:685) ~[?:?]
	at org.apache.cxf.jaxrs.impl.UriBuilderImpl.buildURI(UriBuilderImpl.java:183) ~[bundleFile:1.0.9]
	at org.apache.cxf.jaxrs.impl.UriBuilderImpl.doBuild(UriBuilderImpl.java:115) ~[bundleFile:1.0.9]
	... 14 more
```

## Your Environment

* 3.1.0-Snapshot : Clean Install
* Windows 10 64-Bit

**Comment by lsiepel** [comment]
Did you get this sorted?
Had a short look at the code and it points to an ipaddress from the configuration. 
If this is still an issue, i suggest you share your configuration settings. If it is the configuration, we might also need a code change to improve the error and or validation.
