### ISSUE TITLE
[ecobee] 'setHold' is not a member of 'org.openhab.core.thing.binding.ThingActions'

### ISSUE THREAD

**Issue by morph166955** [openhab/openhab-addons#9630]
As reported in https://community.openhab.org/t/ecobee-binding-v2/97733/134

```
   val ecobeeActions = getActions("ecobee","ecobee:thermostat:account:REDACTED")
    ecobeeActions.setHold(72|"°F",70|"°F",null,null,null,"nextTransition",null)

2021-01-01 12:50:25.342 [ERROR] [internal.handler.ScriptActionHandler] - Script execution of rule with UID 'monitor-8' failed: 'setHold' is not a member of 'org.openhab.core.thing.binding.ThingActions'; line 176, column 3, length 75 in monitor
javax.script.ScriptException: 'setHold' is not a member of 'org.openhab.core.thing.binding.ThingActions'; line 176, column 3, length 75 in monitor
        at org.openhab.core.model.script.runtime.internal.engine.DSLScriptEngine.eval(DSLScriptEngine.java:127) ~[?:?]
        at org.openhab.core.automation.module.script.internal.handler.ScriptActionHandler.lambda$0(ScriptActionHandler.java:62) [bundleFile:?]
        at java.util.Optional.ifPresent(Optional.java:183) [?:?]
        at org.openhab.core.automation.module.script.internal.handler.ScriptActionHandler.execute(ScriptActionHandler.java:59) [bundleFile:?]
        at org.openhab.core.automation.internal.RuleEngineImpl.executeActions(RuleEngineImpl.java:1179) [bundleFile:?]
        at org.openhab.core.automation.internal.RuleEngineImpl.runRule(RuleEngineImpl.java:987) [bundleFile:?]
        at org.openhab.core.automation.internal.TriggerHandlerCallbackImpl$TriggerData.run(TriggerHandlerCallbackImpl.java:89) [bundleFile:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by mhilbush** [comment]
Thanks for reporting.

I broke this in my recent PR to rework the discovery process. A fix is forthcoming.

**Comment by morph166955** [comment]
No worries.  Happy to test the fix when ready.
