### ISSUE TITLE
[innogysmarthome] NullPointerException when no device state is available

### ISSUE THREAD

**Issue by Novanic** [openhab/openhab-addons#9660]
A NullPointerException can occur when a device is returned by the API ("/devices" endpoint) when no device state is available for the device ("/devices/states" endpoint). That happed with the virtual device "NotificationSender". When this exception occurs, the bridge thing becomes offline, therefore the binding isn't usable anymore.

Stacktrace (from OpenHAB 3.0.0):
`java.lang.NullPointerException: null
	at org.openhab.binding.innogysmarthome.internal.client.entity.device.Device.setReachable(Device.java:394) ~[?:?]
	at org.openhab.binding.innogysmarthome.internal.client.entity.device.Device.setMessageList(Device.java:376) ~[?:?]
	at org.openhab.binding.innogysmarthome.internal.client.InnogyClient.getFullDevices(InnogyClient.java:499) ~[?:?]
	at org.openhab.binding.innogysmarthome.internal.manager.DeviceStructureManager.refreshDevices(DeviceStructureManager.java:85) ~[?:?]
	at org.openhab.binding.innogysmarthome.internal.handler.InnogyBridgeHandler.startClient(InnogyBridgeHandler.java:228) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]`

**Comment by Novanic** [comment]
The fix was merged in January last year (2021).
