### ISSUE TITLE
[samsungtv] 3.1.0-S2112 breaks all functionality

### ISSUE THREAD

**Issue by morph166955** [openhab/openhab-addons#9673]
@kaikreuzer @paulianttila FYI

It looks like S2112 completely breaks this binding.  Likely related to https://github.com/openhab/openhab-addons/pull/9525

All 3 of my TVs (2 legacy, 1 websocket) are not reporting online/offline or updating any channels.  The network binding shows pings starting/stopping as the device goes up/down.  I'd post logs, but I'm not getting anything at all.

openhab> bundle:list -s | grep -i samsung
253 │ Active │  80 │ 3.1.0.202101030505      │ org.openhab.binding.samsungtv

EDIT: One caveat, if the TV is on when OH starts, the thing does go into an ONLINE state, but it doesn't update any channels and never changes from that state.

EDIT2: @kaikreuzer I went back through some of the commits you had done to your train before the final that I had compiled. e904b8b seems to be the last that was working just fine.

**Comment by kaikreuzer** [comment]
I cannot reproduce any issue. I am on build 2119 and the TV is working nicely since more than a day, reporting channel updates and reacting on commands with no issues.

**Comment by morph166955** [comment]
I will update to 2119 and test.

**Comment by morph166955** [comment]
As S2127 is the most current, I'm going to go to that unless there is a specific reason to go to 2119.

**Comment by morph166955** [comment]
@kaikreuzer This is still present for me in S2127.

My things are configured as:

Thing samsungtv:tv:09896802_00a0_1000_adfd_bc1485733bf2 [ hostName="REDACTED", port=8001, refreshInterval=1000, protocol="Legacy", macAddress="REDACTED"]
Thing samsungtv:tv:09896802_00a0_1000_b47c_bc1485733bd4 [ hostName="REDACTED", port=8001, refreshInterval=1000, protocol="Legacy", macAddress="REDACTED"]
Thing samsungtv:tv:18f315ed_28c8_4066_a4a4_d3cadd59a670 [ hostName="REDACTED", port=8001, refreshInterval=1000, protocol="WebSocket", macAddress="REDACTED"]

openhab> bundle:list -s | grep -i samsung
253 │ Active │  80 │ 3.1.0.202101080345      │ org.openhab.binding.samsungtv

2021-01-08 15:53:25.143 [INFO ] [openhab.event.ItemCommandEvent      ] - Item 'GC000C1E04A4F7_M1C1_Button' received command SAMSUNGTV_POWER_TOGGLE
2021-01-08 15:53:25.144 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'GC000C1E04A4F7_M1C1_Button' changed from NULL to SAMSUNGTV_POWER_TOGGLE
2021-01-08 15:53:25.214 [INFO ] [openhab.event.ItemCommandEvent      ] - Item 'GC000C1E04A4F7_M1C1' received command SAMSUNGTV_POWER_TOGGLE
2021-01-08 15:53:25.215 [INFO ] [penhab.event.ItemStatePredictedEvent] - Item 'GC000C1E04A4F7_M1C1' predicted to become SAMSUNGTV_POWER_TOGGLE
2021-01-08 15:53:25.216 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'GC000C1E04A4F7_M1C1' changed from NULL to SAMSUNGTV_POWER_TOGGLE
2021-01-08 15:53:26.349 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'networksamsunga4a4online' changed from OFF to ON
2021-01-08 15:53:26.349 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'networksamsunga4a4time' changed from UNDEF to 23.0
2021-01-08 15:53:27.163 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'GC000C1E04A4F7_M1C1' changed from SAMSUNGTV_POWER_TOGGLE to EMPTY
2021-01-08 15:53:28.380 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'networksamsunga4a4time' changed from 23.0 to 1.0
2021-01-08 15:53:30.432 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'networksamsunga4a4time' changed from 1.0 to 2.0
2021-01-08 15:53:38.641 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'networksamsunga4a4time' changed from 2.0 to 3.0
2021-01-08 15:53:40.692 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'networksamsunga4a4time' changed from 3.0 to 2.0
2021-01-08 15:53:53.640 [INFO ] [openhab.event.ItemCommandEvent      ] - Item 'GC000C1E04A4FD_M1C1_Button' received command SAMSUNGTV_POWER_TOGGLE
2021-01-08 15:53:53.650 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'GC000C1E04A4FD_M1C1_Button' changed from NULL to SAMSUNGTV_POWER_TOGGLE
2021-01-08 15:53:53.651 [INFO ] [openhab.event.ItemCommandEvent      ] - Item 'GC000C1E04A4FD_M1C1' received command SAMSUNGTV_POWER_TOGGLE
2021-01-08 15:53:53.655 [INFO ] [penhab.event.ItemStatePredictedEvent] - Item 'GC000C1E04A4FD_M1C1' predicted to become SAMSUNGTV_POWER_TOGGLE
2021-01-08 15:53:53.661 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'GC000C1E04A4FD_M1C1' changed from NULL to SAMSUNGTV_POWER_TOGGLE
2021-01-08 15:53:55.385 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'GC000C1E04A4FD_M1C1' changed from SAMSUNGTV_POWER_TOGGLE to EMPTY
2021-01-08 15:53:57.115 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'networksamsunga4a4time' changed from 2.0 to 5.0
2021-01-08 15:53:59.166 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'networksamsunga4a4time' changed from 5.0 to 4.0
2021-01-08 15:54:00.190 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'networksamsungb47conline' changed from OFF to ON
2021-01-08 15:54:00.191 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'networksamsungb47ctime' changed from UNDEF to 7.0
2021-01-08 15:54:01.216 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'networksamsunga4a4time' changed from 4.0 to 2.0
2021-01-08 15:54:03.268 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'networksamsunga4a4time' changed from 2.0 to 1.0
2021-01-08 15:54:05.320 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'networksamsunga4a4time' changed from 1.0 to 2.0
2021-01-08 15:54:20.127 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'networksamsunga4a4time' changed from 2.0 to 1.0
2021-01-08 15:54:24.231 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'networksamsunga4a4time' changed from 1.0 to 2.0

**Comment by morph166955** [comment]
More info, I removed my things file and the inbox was able to find the TVs as they powered on.  I added them via the GUI and they populated channels but then stopped updating.  Same as when OH starts and gets the info from a TV if it's on but then loses it.

**Comment by morph166955** [comment]
@kaikreuzer I spent some time today adding some debugs to the code and I believe I have found the offending issue.

In SamsungTvHandler.java @ line 326 there is the following:

```
    public void remoteDeviceAdded(@Nullable Registry registry, @Nullable RemoteDevice device) {
            if (configuration.hostName != null && device != null && device.getIdentity() != null
                && device.getIdentity().getDescriptorURL() == null
                && configuration.hostName.equals(device.getIdentity().getDescriptorURL().getHost())
                && device.getType() != null) {
```

I believe device.getIdentity().getDescriptorURL() == null should actually be != null

That IF statement seems to always fail when a TV turns on.  I added the following debug and here is the output:

```
    public void remoteDeviceAdded(@Nullable Registry registry, @Nullable RemoteDevice device) {
        logger.debug("RDA Fired");

         } else { logger.debug("RDA Failed First IF {} | {} | {} | {} | {} | {}",configuration.hostName,device,device.getIdentity(),device.getIdentity().getDescriptorURL(),configuration.hostName.equals(device.getIdentity().getDescriptorURL().getHost()),device.getType()); }

2021-01-09 14:22:15.478 [DEBUG] [tv.internal.handler.SamsungTvHandler] - RDA Fired
2021-01-09 14:22:15.478 [DEBUG] [tv.internal.handler.SamsungTvHandler] - RDA Fired
2021-01-09 14:22:15.478 [DEBUG] [tv.internal.handler.SamsungTvHandler] - RDA Failed First IF REDACTED.136 | (RemoteDevice) Identity: (RemoteDeviceIdentity) UDN: uuid:055d4a80-00fa-1000-868e-bc1485733bd4, Descriptor: http://REDACTED.136:7676/smp_20_, Root: true | (RemoteDeviceIdentity) UDN: uuid:055d4a80-00fa-1000-868e-bc1485733bd4, Descriptor: http://REDACTED.136:7676/smp_20_ | http://REDACTED.136:7676/smp_20_ | true | urn:samsung.com:device:MainTVServer2:1
2021-01-09 14:22:15.478 [DEBUG] [tv.internal.handler.SamsungTvHandler] - RDA Failed First IF REDACTED.133 | (RemoteDevice) Identity: (RemoteDeviceIdentity) UDN: uuid:055d4a80-00fa-1000-868e-bc1485733bd4, Descriptor: http://REDACTED.136:7676/smp_20_, Root: true | (RemoteDeviceIdentity) UDN: uuid:055d4a80-00fa-1000-868e-bc1485733bd4, Descriptor: http://REDACTED.136:7676/smp_20_ | http://REDACTED.136:7676/smp_20_ | false | urn:samsung.com:device:MainTVServer2:1
2021-01-09 14:22:15.478 [DEBUG] [tv.internal.handler.SamsungTvHandler] - RDA Fired
2021-01-09 14:22:15.478 [DEBUG] [tv.internal.handler.SamsungTvHandler] - RDA Failed First IF REDACTED.153 | (RemoteDevice) Identity: (RemoteDeviceIdentity) UDN: uuid:055d4a80-00fa-1000-868e-bc1485733bd4, Descriptor: http://REDACTED.136:7676/smp_20_, Root: true | (RemoteDeviceIdentity) UDN: uuid:055d4a80-00fa-1000-868e-bc1485733bd4, Descriptor: http://REDACTED.136:7676/smp_20_ | http://REDACTED.136:7676/smp_20_ | false | urn:samsung.com:device:MainTVServer2:1
```

When I change device.getIdentity().getDescriptorURL() == null to be != null, the binding begins to work again.  

```
2021-01-09 14:26:35.390 [DEBUG] [tv.internal.handler.SamsungTvHandler] - RDA Fired
2021-01-09 14:26:35.390 [DEBUG] [tv.internal.handler.SamsungTvHandler] - RDA Fired
2021-01-09 14:26:35.390 [DEBUG] [tv.internal.handler.SamsungTvHandler] - RDA Fired
2021-01-09 14:26:35.390 [DEBUG] [tv.internal.handler.SamsungTvHandler] - RDA Failed First IF REDACTED.153 | (RemoteDevice) Identity: (RemoteDeviceIdentity) UDN: uuid:05f5e101-0064-1000-bc6f-bc1485733bd4, Descriptor: http://REDACTED.136:7676/smp_24_, Root: true | (RemoteDeviceIdentity) UDN: uuid:05f5e101-0064-1000-bc6f-bc1485733bd4, Descriptor: http://REDACTED.136:7676/smp_24_ | http://REDACTED.136:7676/smp_24_ | false | urn:samsung.com:device:RemoteControlReceiver:1
2021-01-09 14:26:35.390 [DEBUG] [tv.internal.handler.SamsungTvHandler] - RDA Failed First IF REDACTED.133 | (RemoteDevice) Identity: (RemoteDeviceIdentity) UDN: uuid:05f5e101-0064-1000-bc6f-bc1485733bd4, Descriptor: http://REDACTED.136:7676/smp_24_, Root: true | (RemoteDeviceIdentity) UDN: uuid:05f5e101-0064-1000-bc6f-bc1485733bd4, Descriptor: http://REDACTED.136:7676/smp_24_ | http://REDACTED.136:7676/smp_24_ | false | urn:samsung.com:device:RemoteControlReceiver:1
2021-01-09 14:26:35.390 [DEBUG] [tv.internal.handler.SamsungTvHandler] - remoteDeviceAdded: RemoteControlReceiver, http://REDACTED.136:7676/smp_24_

```

**Comment by morph166955** [comment]
One other last note that I've noticed.  Once I fix the == to !=, my event log shows the following.

```
2021-01-09 14:33:47.500 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'samsungtv:tv:09896802_00a0_1000_b47c_bc1485733bd4' changed from ONLINE to OFFLINE (COMMUNICATION_ERROR): Cannot connect to remote control service
2021-01-09 14:33:50.660 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'samsungtv:tv:09896802_00a0_1000_b47c_bc1485733bd4' changed from OFFLINE (COMMUNICATION_ERROR): Cannot connect to remote control service to ONLINE
2021-01-09 14:33:51.562 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'samsungtv:tv:09896802_00a0_1000_b47c_bc1485733bd4' changed from ONLINE to OFFLINE (COMMUNICATION_ERROR): Cannot connect to remote control service
2021-01-09 14:33:51.562 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'samsungtv:tv:09896802_00a0_1000_b47c_bc1485733bd4' changed from OFFLINE (COMMUNICATION_ERROR): Cannot connect to remote control service to ONLINE
```

This lines up to two instances of this error:

```
2021-01-09 14:33:47.196 [DEBUG] [rnal.service.RemoteControllerService] - Creating a Samsung TV RemoteController service: false
2021-01-09 14:33:47.197 [INFO ] [rnal.service.RemoteControllerService] - Using Legacy interface
2021-01-09 14:33:47.197 [DEBUG] [rnal.protocol.RemoteControllerLegacy] - Open connection to host 'REDACTED.136:8001'
2021-01-09 14:33:47.199 [DEBUG] [rnal.protocol.RemoteControllerLegacy] - Connection successfully opened...querying access
2021-01-09 14:33:47.500 [DEBUG] [tv.internal.handler.SamsungTvHandler] - Error was reported: Cannot connect to remote control service
org.openhab.binding.samsungtv.internal.protocol.RemoteControllerException: Unknown response received for access query
        at org.openhab.binding.samsungtv.internal.protocol.RemoteControllerLegacy.readInitialInfo(RemoteControllerLegacy.java:183) ~[bundleFile:?]
        at org.openhab.binding.samsungtv.internal.protocol.RemoteControllerLegacy.openConnection(RemoteControllerLegacy.java:111) ~[bundleFile:?]
        at org.openhab.binding.samsungtv.internal.service.RemoteControllerService.start(RemoteControllerService.java:229) [bundleFile:?]
        at org.openhab.binding.samsungtv.internal.handler.SamsungTvHandler.startService(SamsungTvHandler.java:315) [bundleFile:?]
        at org.openhab.binding.samsungtv.internal.handler.SamsungTvHandler.checkCreateManualConnection(SamsungTvHandler.java:301) [bundleFile:?]
        at org.openhab.binding.samsungtv.internal.handler.SamsungTvHandler.checkAndCreateServices(SamsungTvHandler.java:246) [bundleFile:?]
        at org.openhab.binding.samsungtv.internal.handler.SamsungTvHandler.remoteDeviceAdded(SamsungTvHandler.java:352) [bundleFile:?]
        at org.jupnp.registry.RemoteItems$1.run(RemoteItems.java:114) [bundleFile:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]

2021-01-09 14:33:51.400 [DEBUG] [rnal.service.RemoteControllerService] - Creating a Samsung TV RemoteController service: true
2021-01-09 14:33:51.400 [INFO ] [rnal.service.RemoteControllerService] - Using Legacy interface
2021-01-09 14:33:51.400 [DEBUG] [rnal.protocol.RemoteControllerLegacy] - Open connection to host 'REDACTED.136:8001'
2021-01-09 14:33:51.402 [DEBUG] [rnal.protocol.RemoteControllerLegacy] - Connection successfully opened...querying access
2021-01-09 14:33:51.562 [DEBUG] [tv.internal.handler.SamsungTvHandler] - Error was reported: Cannot connect to remote control service
org.openhab.binding.samsungtv.internal.protocol.RemoteControllerException: Unknown response received for access query
        at org.openhab.binding.samsungtv.internal.protocol.RemoteControllerLegacy.readInitialInfo(RemoteControllerLegacy.java:183) ~[bundleFile:?]
        at org.openhab.binding.samsungtv.internal.protocol.RemoteControllerLegacy.openConnection(RemoteControllerLegacy.java:111) ~[bundleFile:?]
        at org.openhab.binding.samsungtv.internal.service.RemoteControllerService.start(RemoteControllerService.java:229) [bundleFile:?]
        at org.openhab.binding.samsungtv.internal.handler.SamsungTvHandler.startService(SamsungTvHandler.java:315) [bundleFile:?]
        at org.openhab.binding.samsungtv.internal.handler.SamsungTvHandler.createService(SamsungTvHandler.java:265) [bundleFile:?]
        at org.openhab.binding.samsungtv.internal.handler.SamsungTvHandler.checkAndCreateServices(SamsungTvHandler.java:243) [bundleFile:?]
        at org.openhab.binding.samsungtv.internal.handler.SamsungTvHandler.remoteDeviceAdded(SamsungTvHandler.java:352) [bundleFile:?]
        at org.jupnp.registry.RemoteItems$1.run(RemoteItems.java:114) [bundleFile:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
2021-01-09 14:33:51.562 [DEBUG] [tv.internal.handler.SamsungTvHandler] - Restarting service in UPnP mode for: UN60H7100, RemoteControlReceiver (05f5e101-0064-1000-bc6f-bc1485733bd4)

```
