### ISSUE TITLE
HueBridgeHandlerOSGiTest unstable

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-addons#9763]
This test failed in: https://ci.openhab.org/job/PR-openHAB-Addons/2001/

```
TEST org.openhab.binding.hue.internal.handler.HueBridgeHandlerOSGiTest#verifyStatusIfNewUserCannotBeCreated() <<< ERROR: expected: <CONFIGURATION_ERROR> but was: <NONE>
org.opentest4j.AssertionFailedError: expected: <CONFIGURATION_ERROR> but was: <NONE>
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
	at org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1124)
	at org.openhab.binding.hue.internal.handler.HueBridgeHandlerOSGiTest.lambda$3(HueBridgeHandlerOSGiTest.java:185)
	at org.openhab.core.test.java.JavaTest.waitForAssert(JavaTest.java:152)
	at org.openhab.core.test.java.JavaTest.waitForAssert(JavaTest.java:120)
	at org.openhab.core.test.java.JavaTest.waitForAssert(JavaTest.java:73)
	at org.openhab.binding.hue.internal.handler.HueBridgeHandlerOSGiTest.verifyStatusIfNewUserCannotBeCreated(HueBridgeHandlerOSGiTest.java:185)
```

**Comment by wborn** [comment]
Today it failed in: https://ci.openhab.org/job/openHAB-Addons/340/

```
TEST org.openhab.binding.hue.internal.handler.HueBridgeHandlerOSGiTest#verifyStatusIfLinkButtonIsNotPressed() <<< ERROR: expected: <CONFIGURATION_ERROR> but was: <NONE>
org.opentest4j.AssertionFailedError: expected: <CONFIGURATION_ERROR> but was: <NONE>
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
	at org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1124)
	at org.openhab.binding.hue.internal.handler.HueBridgeHandlerOSGiTest.verifyStatusIfLinkButtonIsNotPressed(HueBridgeHandlerOSGiTest.java:161)
```
