### ISSUE TITLE
[samsungtv] Legacy TVs have issues on poweron with "ONLINE to OFFLINE (COMMUNICATION_ERROR): Cannot connect to remote control service"

### ISSUE THREAD

**Issue by morph166955** [openhab/openhab-addons#9765]
See errors below:

```
2021-01-09 14:33:47.500 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'samsungtv:tv:09896802_00a0_1000_b47c_bc1485733bd4' changed from ONLINE to OFFLINE (COMMUNICATION_ERROR): Cannot connect to remote control service
2021-01-09 14:33:50.660 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'samsungtv:tv:09896802_00a0_1000_b47c_bc1485733bd4' changed from OFFLINE (COMMUNICATION_ERROR): Cannot connect to remote control service to ONLINE
2021-01-09 14:33:51.562 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'samsungtv:tv:09896802_00a0_1000_b47c_bc1485733bd4' changed from ONLINE to OFFLINE (COMMUNICATION_ERROR): Cannot connect to remote control service
2021-01-09 14:33:51.562 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'samsungtv:tv:09896802_00a0_1000_b47c_bc1485733bd4' changed from OFFLINE (COMMUNICATION_ERROR): Cannot connect to remote control service to ONLINE
```

This lines up to two instances of this error:

```
2021-01-09 14:33:47.196 [DEBUG] [rnal.service.RemoteControllerService] - Creating a Samsung TV RemoteController service: false
2021-01-09 14:33:47.197 [INFO ] [rnal.service.RemoteControllerService] - Using Legacy interface
2021-01-09 14:33:47.197 [DEBUG] [rnal.protocol.RemoteControllerLegacy] - Open connection to host 'REDACTED.136:8001'
2021-01-09 14:33:47.199 [DEBUG] [rnal.protocol.RemoteControllerLegacy] - Connection successfully opened...querying access
2021-01-09 14:33:47.500 [DEBUG] [tv.internal.handler.SamsungTvHandler] - Error was reported: Cannot connect to remote control service
org.openhab.binding.samsungtv.internal.protocol.RemoteControllerException: Unknown response received for access query
        at org.openhab.binding.samsungtv.internal.protocol.RemoteControllerLegacy.readInitialInfo(RemoteControllerLegacy.java:183) ~[bundleFile:?]
        at org.openhab.binding.samsungtv.internal.protocol.RemoteControllerLegacy.openConnection(RemoteControllerLegacy.java:111) ~[bundleFile:?]
        at org.openhab.binding.samsungtv.internal.service.RemoteControllerService.start(RemoteControllerService.java:229) [bundleFile:?]
        at org.openhab.binding.samsungtv.internal.handler.SamsungTvHandler.startService(SamsungTvHandler.java:315) [bundleFile:?]
        at org.openhab.binding.samsungtv.internal.handler.SamsungTvHandler.checkCreateManualConnection(SamsungTvHandler.java:301) [bundleFile:?]
        at org.openhab.binding.samsungtv.internal.handler.SamsungTvHandler.checkAndCreateServices(SamsungTvHandler.java:246) [bundleFile:?]
        at org.openhab.binding.samsungtv.internal.handler.SamsungTvHandler.remoteDeviceAdded(SamsungTvHandler.java:352) [bundleFile:?]
        at org.jupnp.registry.RemoteItems$1.run(RemoteItems.java:114) [bundleFile:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]

2021-01-09 14:33:51.400 [DEBUG] [rnal.service.RemoteControllerService] - Creating a Samsung TV RemoteController service: true
2021-01-09 14:33:51.400 [INFO ] [rnal.service.RemoteControllerService] - Using Legacy interface
2021-01-09 14:33:51.400 [DEBUG] [rnal.protocol.RemoteControllerLegacy] - Open connection to host 'REDACTED.136:8001'
2021-01-09 14:33:51.402 [DEBUG] [rnal.protocol.RemoteControllerLegacy] - Connection successfully opened...querying access
2021-01-09 14:33:51.562 [DEBUG] [tv.internal.handler.SamsungTvHandler] - Error was reported: Cannot connect to remote control service
org.openhab.binding.samsungtv.internal.protocol.RemoteControllerException: Unknown response received for access query
        at org.openhab.binding.samsungtv.internal.protocol.RemoteControllerLegacy.readInitialInfo(RemoteControllerLegacy.java:183) ~[bundleFile:?]
        at org.openhab.binding.samsungtv.internal.protocol.RemoteControllerLegacy.openConnection(RemoteControllerLegacy.java:111) ~[bundleFile:?]
        at org.openhab.binding.samsungtv.internal.service.RemoteControllerService.start(RemoteControllerService.java:229) [bundleFile:?]
        at org.openhab.binding.samsungtv.internal.handler.SamsungTvHandler.startService(SamsungTvHandler.java:315) [bundleFile:?]
        at org.openhab.binding.samsungtv.internal.handler.SamsungTvHandler.createService(SamsungTvHandler.java:265) [bundleFile:?]
        at org.openhab.binding.samsungtv.internal.handler.SamsungTvHandler.checkAndCreateServices(SamsungTvHandler.java:243) [bundleFile:?]
        at org.openhab.binding.samsungtv.internal.handler.SamsungTvHandler.remoteDeviceAdded(SamsungTvHandler.java:352) [bundleFile:?]
        at org.jupnp.registry.RemoteItems$1.run(RemoteItems.java:114) [bundleFile:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
2021-01-09 14:33:51.562 [DEBUG] [tv.internal.handler.SamsungTvHandler] - Restarting service in UPnP mode for: UN60H7100, RemoteControlReceiver (05f5e101-0064-1000-bc6f-bc1485733bd4)

```

**Comment by Schm1tz1** [comment]
Same issue here after switching to OH3. Same settings for OH1 and OH2 for years bit with legacy interface I get the same issues.

**Comment by morph166955** [comment]
I think I see where in the code it's doing this. I'm going to see if I can put in a fix for it. I believe we need to add a check thats along the lines of "if legacy, don't attempt to make these first connections "

**Comment by Schm1tz1** [comment]
Very nice! I still have some higher prio issue with the heating control which is more crucial in winter ;-).

**Comment by morph166955** [comment]
I believe that I've resolved some of this in https://github.com/openhab/openhab-addons/pull/9923

Now it does (note, this is same as above except it doesnt go OFF -> ON -> OFF -> ON):

```
2021-01-24 12:46:21.534 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'samsungtv:tv:09896802_00a0_1000_b47c_bc1485733bd4' changed from OFFLINE to OFFLINE (COMMUNICATION_ERROR): Cannot connect to remote control service
2021-01-24 12:46:21.536 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'samsungtv:tv:09896802_00a0_1000_b47c_bc1485733bd4' changed from OFFLINE (COMMUNICATION_ERROR): Cannot connect to remote control service to ONLINE

```
