### ISSUE TITLE
[digitalstrom] ClassCastException

### ISSUE THREAD

**Issue by alexf2015** [openhab/openhab-addons#9843]
```
2021-01-16 10:00:05.806 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception:
java.lang.ClassCastException: org.openhab.binding.digitalstrom.internal.lib.structure.devices.impl.CircuitImpl cannot be cast to org.openhab.binding.digitalstrom.internal.lib.structure.devices.Device
        at org.openhab.binding.digitalstrom.internal.handler.CircuitHandler.onDeviceRemoved(CircuitHandler.java:190) ~[?:?]
        at org.openhab.binding.digitalstrom.internal.handler.CircuitHandler.onDeviceAdded(CircuitHandler.java:219) ~[?:?]
        at org.openhab.binding.digitalstrom.internal.lib.structure.devices.AbstractGeneralDeviceInformations.registerDeviceStatusListener(AbstractGeneralDeviceInformations.java:127) ~[?:?]
        at org.openhab.binding.digitalstrom.internal.lib.manager.impl.StructureManagerImpl.updateCircuitConfig(StructureManagerImpl.java:404) ~[?:?]
        at org.openhab.binding.digitalstrom.internal.lib.manager.impl.DeviceStatusManagerImpl$PollingRunnable.run(DeviceStatusManagerImpl.java:264) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_275]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[?:1.8.0_275]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_275]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[?:1.8.0_275]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_275]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_275]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
```
This exception randomly appears and causes my meters to stop providing any further data.
Detected in Openhab 2.5.11.

**Comment by alexf2015** [comment]
I submitted the same bug (#9049) already some months ago. I did not recognize that it is already fixed in 3.0.0
