### ISSUE TITLE
[digitalstrom] Binding crashes on openhab startup

### ISSUE THREAD

**Issue by alexf2015** [openhab/openhab-addons#9844]
When starting openhab the digitalstrom binding has a chance of > 90% to crash immediately with this exception:

```
2021-01-16 18:20:59.141 [ERROR] [verconnection.impl.HttpTransportImpl] - An IOException occurred:
javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
        at sun.security.ssl.SSLSocketImpl.handleEOF(SSLSocketImpl.java:1369) ~[?:1.8.0_275]
        at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1210) ~[?:1.8.0_275]
        at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1111) ~[?:1.8.0_275]
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:398) ~[?:1.8.0_275]
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:370) ~[?:1.8.0_275]
        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559) ~[?:1.8.0_275]
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185) ~[?:1.8.0_275]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:167) ~[?:1.8.0_275]
        at org.openhab.binding.digitalstrom.internal.lib.serverconnection.impl.HttpTransportImpl.getPEMCertificateFromServer(HttpTransportImpl.java:541) [bundleFile:?]
        at org.openhab.binding.digitalstrom.internal.lib.serverconnection.impl.HttpTransportImpl.init(HttpTransportImpl.java:207) [bundleFile:?]
        at org.openhab.binding.digitalstrom.internal.lib.serverconnection.impl.HttpTransportImpl.<init>(HttpTransportImpl.java:117) [bundleFile:?]
        at org.openhab.binding.digitalstrom.internal.lib.manager.impl.ConnectionManagerImpl.init(ConnectionManagerImpl.java:264) [bundleFile:?]
        at org.openhab.binding.digitalstrom.internal.lib.manager.impl.ConnectionManagerImpl.<init>(ConnectionManagerImpl.java:106) [bundleFile:?]
        at org.openhab.binding.digitalstrom.internal.handler.BridgeHandler$Initializer.run(BridgeHandler.java:137) [bundleFile:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_275]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_275]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_275]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_275]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_275]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_275]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
        Suppressed: java.net.SocketException: Broken pipe (Write failed)
                at java.net.SocketOutputStream.socketWrite0(Native Method) ~[?:1.8.0_275]
                at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111) ~[?:1.8.0_275]
                at java.net.SocketOutputStream.write(SocketOutputStream.java:155) ~[?:1.8.0_275]
                at sun.security.ssl.SSLSocketOutputRecord.encodeAlert(SSLSocketOutputRecord.java:81) ~[?:1.8.0_275]
                at sun.security.ssl.TransportContext.fatal(TransportContext.java:379) ~[?:1.8.0_275]
                at sun.security.ssl.TransportContext.fatal(TransportContext.java:291) ~[?:1.8.0_275]
                at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:408) ~[?:1.8.0_275]
                at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:370) ~[?:1.8.0_275]
                at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559) ~[?:1.8.0_275]
                at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185) ~[?:1.8.0_275]
                at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:167) ~[?:1.8.0_275]
                at org.openhab.binding.digitalstrom.internal.lib.serverconnection.impl.HttpTransportImpl.getPEMCertificateFromServer(HttpTransportImpl.java:541) [bundleFile:?]
                at org.openhab.binding.digitalstrom.internal.lib.serverconnection.impl.HttpTransportImpl.init(HttpTransportImpl.java:207) [bundleFile:?]
                at org.openhab.binding.digitalstrom.internal.lib.serverconnection.impl.HttpTransportImpl.<init>(HttpTransportImpl.java:117) [bundleFile:?]
                at org.openhab.binding.digitalstrom.internal.lib.manager.impl.ConnectionManagerImpl.init(ConnectionManagerImpl.java:264) [bundleFile:?]
                at org.openhab.binding.digitalstrom.internal.lib.manager.impl.ConnectionManagerImpl.<init>(ConnectionManagerImpl.java:106) [bundleFile:?]
                at org.openhab.binding.digitalstrom.internal.handler.BridgeHandler$Initializer.run(BridgeHandler.java:137) [bundleFile:?]
                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_275]
                at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_275]
                at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_275]
                at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_275]
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_275]
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_275]
                at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
Caused by: java.io.EOFException: SSL peer shut down incorrectly
        at sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:481) ~[?:1.8.0_275]
        at sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:470) ~[?:1.8.0_275]
        at sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160) ~[?:1.8.0_275]
        at sun.security.ssl.SSLTransport.decode(SSLTransport.java:110) ~[?:1.8.0_275]
        at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1202) ~[?:1.8.0_275]
        ... 19 more
2021-01-16 18:20:59.420 [ERROR] [verconnection.impl.HttpTransportImpl] - Cert is empty
```
The binding will work fine when doing a restart of just the digitalstrom binding via karaf console.
Detected in openhab 2.5.11

**Comment by hmerk** [comment]
Readin your log, I would think this is an issue on your DSS side
 Remote host terminated the handshake

Never saw this with my DSS11….

**Comment by alexf2015** [comment]
Well my dss11 has the most recent firmware but I improved the situation by using a reverse proxy.
In the meantime I upgraded to openhab 3.1 I will check again if this still occours if I remove the reverse proxy.

**Comment by alexf2015** [comment]
Since running openhab 3.x digitalstrom is quite stable. I could not observe this behaviour anymore.
