### ISSUE TITLE
[yamahareceiver] Preset String Conversion Error Every Minute in Log

### ISSUE THREAD

**Issue by bj-github** [openhab/openhab-addons#9847]
## Expected Behavior
No errors logged handling Presets as part of Yamaha Receiver status check each minute.

## Current Behavior
I am able to add my Yamaha Receiver itself (RX-V745: https://au.yamaha.com/en/products/audio_visual/av_receivers_amps/rx-v475/) via auto-discovery without issue.

However, subsequently adding the auto-discovered Main_Zone results in the following appearing each minute in the log, even before anything has been configured:

```
2021-01-17 16:47:46.368 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception: 
java.lang.NumberFormatException: For input string: "o Preset"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:?]
	at java.lang.Integer.parseInt(Integer.java:652) ~[?:?]
	at java.lang.Integer.parseInt(Integer.java:770) ~[?:?]
	at org.openhab.binding.yamahareceiver.internal.protocol.xml.InputWithPresetControlXML.convertToPresetNumber(InputWithPresetControlXML.java:157) ~[?:?]
	at org.openhab.binding.yamahareceiver.internal.protocol.xml.InputWithPresetControlXML.update(InputWithPresetControlXML.java:123) ~[?:?]
	at org.openhab.binding.yamahareceiver.internal.handler.YamahaZoneThingHandler.lambda$2(YamahaZoneThingHandler.java:725) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

This is the version/status information via the OH3 About page:
[Yamaha.Config.txt](https://github.com/openhab/openhab-addons/files/5825669/Yamaha.Config.txt)

This is the Amp response to the URL included as the first text line in the file:
[Yamaha.RemoteControl.xml.txt](https://github.com/openhab/openhab-addons/files/5825673/Yamaha.RemoteControl.xml.txt)

## Possible Solution
I'm guessing it's looking in the wrong place for Preset information?

(Alas, it also offers Radio sources of FM and DAB+, but mine is FM and AM, but I assume it'd need a different request to have fixing that considered!)

## Steps to Reproduce (for Bugs)
1. Install Yamaha Receiver Binding.
2. Use auto-discovery to add the receiver itself, and note nothing unusual in the log.
3. Use auto-discovery to add the receiver's Main_Zone and note that the error shown above is logged at one minute intervals.

## Context
Limits my ability to integrate my Yamaha Receiver into OpenHAB. Not a big issue, but if I can help get it addressed ...

While researching this, I found a couple of times it had been previously raised in the Community:

- https://community.openhab.org/t/yamahareceiver-scheduled-runnable-ended-with-an-exception/46496
- https://community.openhab.org/t/warning-in-my-logs-every-10-seconds/69267

but it appears neither of those really went anywhere. Not could I find an issue raised for it, so here I am.

## Your Environment

* Version used: OpenHAB 3.0
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...):  RPi-based image `openhabian-pi-raspios32-v1.6.2.img` from the OpenHAB website, as updated as I could make it via `openhabian-config`
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): Whatever is packaged by OpenHAB community on their Raspberry Pi image

**Comment by bj-github** [comment]
Thinking a bit more about this, I wondered if my "aside" comment about AM/FM support might actually be at the core of the problem: something about responses from an AM/FM variant is different to what comes from an FM/DAB+ version?

I did try removing AM stations from my radio presets, but adding the Zone Thing still generated the log entries. So, even if I'm right, I'm guessing the issue is a bit deeper.

(Unfortunately, Australia has only rolled out DAB+ in the federal and state capitals. Those of us living out in the regions still have to rely on a mix of AM and FM stations.)

**Comment by bj-github** [comment]
Just to confirm the linked fix has addressed the problem for me, thank you.
