### ISSUE TITLE
[tr064] Exception due to duplicate phone number in phonebook contact

### ISSUE THREAD

**Issue by cherub-i** [openhab/openhab-addons#9852]
## Expected Behavior
Binding is able to build the phonebook info, even when a phonebook entry contain the same number twice. 

## Current Behavior
I get log errors, due to entries in my FRITZ!Box phonebook (actually from a phonebook that's synchronized from a different service into the FRITZ!Box) which contain the same number twice.
As a consequence, phonebook-lookups fails altogether.

No question, my contact data here is faulty (no need to store the same number twice - I cleaned that up now).
Nevertheless, it would be nice if the binding could cope with this problem in a better way.

Please note: the "n" stands for a number in the first second of the exception, firstname, surename is the name of the contact in question.
```
==> /home10/services/openhab_blue/userdata/logs/openhab.log <==
2021-01-17 16:31:23.991 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception:
java.lang.IllegalStateException: Duplicate key +nn (nn) nn nn n-nnn (attempted merging values firstname, surename and firstname, surename)
        at java.util.stream.Collectors.duplicateKeyException(Collectors.java:133) ~[?:?]
        at java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:180) ~[?:?]
        at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
        at org.openhab.binding.tr064.internal.phonebook.Tr064PhonebookImpl.lambda$0(Tr064PhonebookImpl.java:76) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:589) ~[?:?]
        at org.openhab.binding.tr064.internal.phonebook.Tr064PhonebookImpl.getPhonebook(Tr064PhonebookImpl.java:77) ~[?:?]
        at org.openhab.binding.tr064.internal.phonebook.Tr064PhonebookImpl.<init>(Tr064PhonebookImpl.java:58) ~[?:?]
        at org.openhab.binding.tr064.internal.Tr064RootHandler.lambda$21(Tr064RootHandler.java:331) ~[?:?]
        at java.util.Optional.map(Optional.java:265) ~[?:?]
        at org.openhab.binding.tr064.internal.Tr064RootHandler.lambda$20(Tr064RootHandler.java:331) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
        at org.openhab.binding.tr064.internal.Tr064RootHandler.processPhonebookList(Tr064RootHandler.java:336) ~[?:?]
        at org.openhab.binding.tr064.internal.Tr064RootHandler.lambda$26(Tr064RootHandler.java:351) ~[?:?]
        at java.util.Optional.map(Optional.java:265) ~[?:?]
        at org.openhab.binding.tr064.internal.Tr064RootHandler.retrievePhonebooks(Tr064RootHandler.java:349) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

## Your Environment
OH 3.0 release in docker container on Linux

**Comment by J-N-K** [comment]
Already fixed in SNAPSHOT.

**Comment by cherub-i** [comment]
Stupid me - I should have looked through the already closed bugs. I only checked open bugs (of which there were none)...

**Comment by J-N-K** [comment]
Sometimes we are very fast :-)
