### ISSUE TITLE
[miio] Xiaomi Binding - Air Purifier MB3

### ISSUE THREAD

**Issue by kom101** [openhab/openhab-addons#9893]
In version 3.1.0 snapshot i have errors in log:

[WARN ] [io.internal.handler.MiIoBasicHandler] - Error creating channel structure
java.lang.IllegalArgumentException: ID segment 'ZHIMI_AIRPURIFIER_MB3_pm2.5-density' contains invalid characters. Each segment of the ID must match the pattern [\w-]*.
        at org.openhab.core.common.AbstractUID.validateSegment(AbstractUID.java:98) ~[bundleFile:?]
        at org.openhab.core.common.AbstractUID.<init>(AbstractUID.java:76) ~[bundleFile:?]
        at org.openhab.core.common.AbstractUID.<init>(AbstractUID.java:59) ~[bundleFile:?]
        at org.openhab.core.thing.UID.<init>(UID.java:57) ~[bundleFile:?]
        at org.openhab.core.thing.type.ChannelTypeUID.<init>(ChannelTypeUID.java:52) ~[bundleFile:?]
        at org.openhab.binding.miio.internal.basic.BasicChannelTypeProvider.addChannelType(BasicChannelTypeProvider.java:64) ~[bundleFile:?]
        at org.openhab.binding.miio.internal.handler.MiIoBasicHandler.buildChannelStructure(MiIoBasicHandler.java:425) [bundleFile:?]
        at org.openhab.binding.miio.internal.handler.MiIoBasicHandler.checkChannelStructure(MiIoBasicHandler.java:371) [bundleFile:?]
        at org.openhab.binding.miio.internal.handler.MiIoBasicHandler.updateData(MiIoBasicHandler.java:301) [bundleFile:?]
        at org.openhab.binding.miio.internal.handler.MiIoAbstractHandler.lambda$2(MiIoAbstractHandler.java:154) [bundleFile:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by marcelrv** [comment]
Thanks. This issue has been mentioned indeed earlier this week and a fix is in the approval process
